### PR TITLE
Increase write_vio.ndone only if sending DATA frame is succeeded

### PR DESCRIPTION
**Pull request by masaori335**
This is alternate approach of #2805 (fix for ~~#2759~~ #2795). As we concerned, "cancel closing on `Http2Stream::do_io_close()`" was bad idea.  It led connection leaks (#2834).
And I couldn't find reasons of connection leaks. So I revisited ~~#2759~~ #2795.

## Root cause of ~~#2759~~ #2795
1) The `write_vio.ndone` is increased regardless the stream could send data frame or not. 
https://github.com/apache/trafficserver/blob/e2bccd5384a4a3e769f994ee794888f3efacb335/proxy/http2/Http2Stream.cc#L561

2) This leads `VC_EVENT_WRITE_COMPLETE` event on `HttpTunnel` even if the response is not proceed (especially `ChunkHandler` is used). 
https://github.com/apache/trafficserver/blob/e2bccd5384a4a3e769f994ee794888f3efacb335/proxy/http/HttpTunnel.cc#L1510-L1512

3) Finally `Http2Stream::do_io_close()` is called from `HttpSM`.
https://github.com/apache/trafficserver/blob/e2bccd5384a4a3e769f994ee794888f3efacb335/proxy/http/HttpSM.cc#L3297

## Approach
Fix 1) in above by undo `write_vio.ndone` increase when actual sent length is different from expected.

## Concerns
- This patch doesn't support stream priority. Ideally `write_vio.ndone` should be increased in  `Http2ConnectionState::send_a_data_frame()`. But I'm not confident about removing the logic from `Http2Stream::update_write_request()`. 
- It looks like when ATS receive WINDOW_UPDATE frame and restart sending, `write_vio.ndone` is not increased. Could this be problem in some cases?

### CODE REVIEW

**Comment by bryancall** [comment]
@masaori335 What PR are you referring to #2759 is about DNS?

**Comment by masaori335** [comment]
Oops, #2795 is the issue.

**Comment by zwoop** [comment]
@masaori335 So we should revert #2805 on master in favor of this PR?

**Comment by masaori335** [comment]
@zwoop Yes, we should. But it will break CI builds for PRs.
So I'll add the revert commit in this PR.

**Comment by masaori335** [comment]
@shinrich Right, the big file test should be passed. I'll check it.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Slightly confused now, since we reverted on the 7.1.x branch already, we also need this on the 7.x Backports project?

**Comment by masaori335** [comment]
@zwoop I added a revert commit. So this PR has 2 commits. We can cherry-pick only f90134f to 7.1.x branch.
Actually I'm still tracking the autest failure (big file test), so the hash will be changed.

**Comment by masaori335** [comment]
Added new commit includes fixing autest failure and refactoring `Http2Stream::update_write_request()`.

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
This changes break tests for tls hooks. I'll revert the `Http2Stream::update_write_request()` refactoring.

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci FreeBSD]
[approve ci ICC]
[approve ci RAT]
[approve ci clang-format]

**Comment by masaori335** [comment]
@shinrich Could you take another look?

**Comment by masaori335** [comment]
[approve ci CentOS]
[approve ci Ubuntu]

**Comment by zwoop** [comment]
What's the status on this? Do we want this for 7.1.2? Wait to 7.1.3 or 7.2 ? Please advice.

**Pull request merged**
