### PR TITLE
Normalized ae cache lookup before cache lookup 

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Comment by maskit** [comment]
remap_load_missing_failure failed

**Comment by maskit** [comment]
[approve ci autest]

**Review by bryancall — APPROVED** [review]

**Review by bryancall — APPROVED** [review]

**Comment by maskit** [comment]
[approve ci rocky]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
