### PR TITLE
Address performance issue by removing use of read_avail

### PR DESCRIPTION
**Pull request by shinrich**
Going through the great list of local fixes while getting ready for the 8.x sync.  We had been seeing performance hot spots with these unnecessary read_avail calls.

### CODE REVIEW

**Comment by masaori335** [comment]
I agree with that calling `read_avail()` should be avoided as much as possible. 

Looks this changes doing logically same things without `read_avail()`. I bit worried about replacing `memcpy() & consume()` to `read()`, but it looks OK so far.

**Comment by SolidWallOfCode** [comment]
Actually, @masaori335, I think that's a bug. I want to talk with Susan before we commit this. I don't think `read` does the same thing as `consume` in this context.

**Comment by SolidWallOfCode** [comment]
Spoke with Susan, I misunderstood the `IOBufferReader` API. The code looks correct.

**Comment by bryancall** [comment]
Cherry picked to 8.1.0

**Pull request merged**
