### PR TITLE
Revert "bugfix for malformed chunked response will be cached under so…

### PR DESCRIPTION
**Pull request by zwoop**
…me terrible network circumstances,"

This reverts commit c2df5ba8d33b5774a35d5bc06289a7808149a337.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
This looks wrong to me - I thought this fix was accepted, it was just the single line that was the problem wiithout these other changes.

**Comment by zwoop** [comment]
I got an email from scw00, urging me to revert this because it was not needed with the single line revert. It's all very confusing ....

**Comment by SolidWallOfCode** [comment]
Yes, I agree swc00's code is useless if you revert Susan's fix, but I thought the best was to keep both because Susan's fix actually fixes a problem.

**Comment by zwoop** [comment]
Yeh, i tried to unravel all of this, but there was no good indication on the issue itself what the hell people wanted :-/.

**Comment by bryancall** [comment]
I think it is better to close the connection on a misbehaving origin than caching a partial response.  For now it would be better to revert the changes, until there is a better fix.

**Comment by shinrich** [comment]
The revert looks accurate.  I am confused as well as to why the original PR is no longer needed.  Touching base with folks before proceeding seems reasonable.

**Comment by scw00** [comment]
As far as I can talk, the c2df5ba has broken TS-3054 at all. It is the same as reverting TS-3054.  

c2df5ba send EOS to ua_session  in `HttpTunnel::finish_all_internal`, that will signal ats the client has closed .  I'm not sure if there is a problem here.

 For TS-3054, we should fix the problem with not only the chunk request. So it also need to revert TS-3054 I think.

I agree with @bryancall , we can revert this temporarily and make a better on instead.

**Comment by oknet** [comment]
With TS-3054, we still lost last data from origin server even there is not a chunked response.

IMO, TS-3054 only fixed the problem on chunked encoding, it is more important to dig out the root cause and solve it.

**Pull request merged**
