### PR TITLE
Integrate clang-tidy into the build.

### PR DESCRIPTION
**Pull request by jpeach**
Add a recursive tidy rule to run clang-tidy over all the source.
The mor recommended way to do this is to build a compilation database,
however the tools for doing that are not very portable, and the
compilation database doesn't easilt let you fix code in header
files.

### CODE REVIEW

**Comment by jpeach** [comment]
@zwoop @PSUdaemon 

Please take this for a spin, but let's not merge yet. It looks like ``clang-tidy`` still get various build errors which cause it to eat code in unfortunate ways.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/387/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/283/ for details.

**Comment by zwoop** [comment]
Unless there's a penalty (or error) to always use $(sort ...), I'd recommend doing so consistently. That avoids future kids from having to know when, or when not to, use it.

Where is tidy.mk?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/396/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/292/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/397/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/293/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
