### PR TITLE
TS-4100: Remove custom XML metrics.

### PR DESCRIPTION
**Pull request by jpeach**
This PR is a heads-up. I'm still going to work on some config file documentation before I merge this. Additionally we need to figure out an upgrade path, since we need the latest version of ``metrics.config`` to be installed and the current installation target always installs the new version to the side.

Ping @bryancall @zwoop @PSUdaemon @shukitchan

### CODE REVIEW

**Comment by zwoop** [comment]
This should wait to be landed until after the issues with ASAN and Lua has been resolved.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/144/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/246/ for details.

**Comment by shukitchan** [comment]
👍

**Comment by jpeach** [comment]
Ok, [TS-4119](https://issues.apache.org/jira/browse/TS-4119) is fixed. How do people feel about landing this? Please read my upgrade comments above :)

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/197/ for details.

**Pull request merged**
