### PR TITLE
Fixed std::array initialization for older compilers

### PR DESCRIPTION
**Pull request by bryancall**
Will hopefully fix the ubuntu clang 5 master build.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
Error message from Ubuntu with clang5:
```
master/compiler/clang/label/ubuntu_16_04/type/debug/1648/build/BUILDS/../proxy/Milestones.h:92:50: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  std::array<ink_hrtime, entries> _milestones = {0};
                                                 ^
                                                 {}

```

**Comment by masaori335** [comment]
I saw that message on the CI job and this change fixed. Probably, the brace elision is supported on somewhere between clang -6 to -8.

**Comment by masaori335** [comment]
Actually, clang-5 has support but `-Wmissing-braces` has mis-behavior.  It looks like the warning is suppressed by https://reviews.llvm.org/rL314838. (Released on clang-6).

**Comment by zwoop** [comment]
Cherry-picked to 8.1.x

**Pull request merged**
