### PR TITLE
TS-3785 List --command options in traffic_server usage information

### PR DESCRIPTION
**Pull request by alyssaq**
[TS-3785](https://issues.apache.org/jira/browse/TS-3785)

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/617/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/721/ for details.

**Comment by shinrich** [comment]
Looks good to me.

**Comment by jpeach** [comment]
@alyssaq Since you are documenting these, can you please update the ``traffic_server`` man page as well?

**Pull request merged**
