### PR TITLE
TS-4680: thread safe initialization in TS*DirGet() functions

### PR DESCRIPTION
**Pull request by yatsukhnenko**
@zwoop, @jpeach, review please. I'm not sure about that.

### CODE REVIEW

**Comment by zwoop** [comment]
@jpeach Wdyt? Would TLS make more sense here? It would duplicate those static strings, but avoids locks, no ?

**Comment by jpeach** [comment]
These are globals, so I don't think that thread local storage makes sense here.

There are 2 reasonable approaches to this. The most straight-forward is to use static initialization (which is guaranteed to be thread-safe by the [language](http://en.cppreference.com/w/cpp/language/storage_duration)). Alternatively, we could use ``pthread_once`` directly.

For example, using the first alternative:
```C
const char *
TSFooDirGet()
{
    static const char * path = ReadFooDirPath();
    return path;
}
```

**Comment by zwoop** [comment]
Interesting, so e.g.

    static char *runtimedir = RecConfigReadRuntimeDir();


would be thread safe. That seems like a no-brainer to me :). +1

**Comment by zwoop** [comment]
If I understand C++ at all, I don't think that example is thread safe? But, moving it outside (file scope) would be. No?

**Comment by jpeach** [comment]
File scope would not work since these initializers can depend on librecords.

**Comment by zwoop** [comment]
Gotcha. Well, you showed me C++11 has this requirement for thread safety, and we've said that v7.0.0 will require C++11 support, so +1 on that.

**Comment by yatsukhnenko** [comment]
@zwoop, @jpeach, something like this?

**Comment by zwoop** [comment]
Yeah, like that. Makes you wonder why TSPluginDirGet() was so different though ... I've had issues before with these APIs, where transfer of ownership was not clear. I'll take a peek in a bit.

[approve ci].

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/462/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/358/ for details.

**Comment by jpeach** [comment]
👍

**Pull request merged**
