### PR TITLE
Do not turn off cache for internal requests

### PR DESCRIPTION
**Pull request by vmamidi**
As of now, auth proxy disables cache for all the internal requests. Auth proxy disables the cache for any plugin that generates internal requests and goes through the same remap rule. For example, background fetch plugin which generates a internal request doesn't cache internal requests.

If there is a requirement to disable caching, it can be achieved by using the conf_remap plugin.  

Update: retained the existing behavior and added a variable to enable caching

### CODE REVIEW

**Review by zwoop — CHANGES_REQUESTED** [review]
How does this work to make sure it doesn’t serve the auth request via a cached response?

**Comment by vmamidi** [comment]
> How does this work to make sure it doesn’t serve the auth request via a cached response?

The plugin doesn't make sure that auth requests are not served from the cache. Disabling cache in auth proxy for existing remap( existing behavior) also doesn't guarantee that as auth requests may go to a different remap rule.

**Comment by bryancall** [comment]
[approve ci]

**Comment by vmamidi** [comment]
> > How does this work to make sure it doesn’t serve the auth request via a cached response?
> 
> The plugin doesn't make sure that auth requests are not served from the cache. Disabling cache in auth proxy for existing remap( existing behavior) also doesn't guarantee that as auth requests may go to a different remap rule.

Added configuration to enable/disable caching.

**Comment by vmamidi** [comment]
[approve ci centos}

**Comment by vmamidi** [comment]
[approve ci centos]

**Comment by vmamidi** [comment]
[approve ci]

**Comment by vmamidi** [comment]
[approve ci]

**Review by bryancall — CHANGES_REQUESTED** [review]
please update the docs for the PR

**Comment by vmamidi** [comment]
> please update the docs for the PR

updated.

**Comment by vmamidi** [comment]
[approve ci]

**Review by bryancall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
