### PR TITLE
YAML config:  output erroneous keyword and line number

### PR DESCRIPTION
**Pull request by ywkaras**
In YAML file it appears on in diags.log.

### CODE REVIEW

**Comment by bryancall** [comment]
1. Can you keep the name as item.  I don't see a reason to change it.
2. Can you also update YamlLogConfig::decodeLogObject().  It looks like it has the same issue.

**Comment by ywkaras** [comment]
I think as a rule of thumb it's best not to have local variables in sub-blocks that have the same name as function parameters, do you disagree @bryancall ?

**Comment by ywkaras** [comment]
I tested this by temporarily changing the h2enable Au test in my cloned repo to put a bad keyword in sni.yaml.

**Comment by bryancall** [comment]
Yes, I agree.  I didn't see the function argument had the same name.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
