### PR TITLE
Use the correct Lua symbol for verify-server setting

### PR DESCRIPTION
**Pull request by zwoop**
This has to be back ported to 7.1.x as well, assuming this is the correct fix.

### CODE REVIEW

**Comment by shukitchan** [comment]
good catch.
how do u find it ? :)

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
@shukitchan I was adding the new overridable configuration, and noticed it.

**Comment by zwoop** [comment]
Cherry-picked to 7.1.x

**Pull request merged**
