### PR TITLE
rectify a minor error in test_server_intercept.lua

### PR DESCRIPTION
**Pull request by taoyunxing**
line 33:
return resp
should modified as
ts.say(resp)

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci]

**Comment by atsci** [comment]
clang-format check *successful*! See https://ci.trafficserver.apache.org/job/clang-format-github/7/ for details.

**Comment by atsci** [comment]
RAT check *successful*! See https://ci.trafficserver.apache.org/job/RAT-github/20/ for details.

**Comment by atsci** [comment]
FreeBSD11 build *failed*! https://ci.trafficserver.apache.org/job/freebsd-github/1702/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/7/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/133/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1598/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/265/

**Comment by shukitchan** [comment]
thanks for spotting the mistake.

👍

**Pull request merged**
