### PR TITLE
Update doc/README.md for cmake

### PR DESCRIPTION
**Pull request by bneradt**
Update the README for generate the docs to use the cmake instructions. This simplifies the instructions significantly.

---

Here's a link to the rendered docs:
https://github.com/bneradt/trafficserver/tree/update_doc_readme_for_cmake/doc

### CODE REVIEW

**Review by JosiahWI — APPROVED** [review]
Thank you for improving the docs! With a preset this might be even simpler, but this looks good for now.

**Review by cmcfarlen — APPROVED** [review]
Agree with @JosiahWI about the preset, but this looks good!

**Comment by bneradt** [comment]
[approve ci freebsd]

**Comment by bneradt** [comment]
[approve ci freebsd]

**Pull request merged**
