### PR TITLE
Change cookie_remap plugin to use pristine URL.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
This PR replaces by https://github.com/apache/trafficserver/pull/5118 .

**Review by randall — APPROVED** [review]

**Comment by ywkaras** [comment]
Waiting for the OK from the VzM prod peeps, then I'll merge.

**Comment by ywkaras** [comment]
@randall can you tell me if Apple uses this plugin (without having to kill me)?

**Comment by ywkaras** [comment]
Making this a draft for now, I now realize it's possible it may break VzM stuff.  Sorry @randall jumped the gun putting this up for review.

**Comment by ywkaras** [comment]
It turns out this change is unlikely to work properly for VzM production proxies.  I'll be creating a new PR that's more flexible.

**Pull request closed without merging**
