### PR TITLE
Don't send image/webp responses from cache to broswers that don't support it

### LINKED ISSUE #7099: ATS will send image/webp content to browsers that don't support it
If a browser that support webp makes a requests through ATS and the origin responds with Content-Type: image/webp that is cacheable ATS will cache the content.  If a browser that doesn't support webp, like Safari, then makes a request ATS will serve back the image/webp response.  This is because browser's send image/* and */* in their Accept: header.

Request from Safari that doesn't support webp:
```
+++++++++ Incoming Request +++++++++
-- State Machine Id: 0
GET http:///eyJrZXkiOiJ1cGxvYWRzL21lZGl1bS9hc3NldC8xODE4L3Rlc2xhX3dpdGhfYV9yb3NlX29uX3RvcF9vZl9pdC5qcGciLCJidWNrZXQiOiJvc2xvLXByb2R1Y3Rpb24iLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjcwMCwiaGVpZ2h0IjpudWxsfX19 HTTP/1.1
Host: 192.168.1.10:8080
Connection: keep-alive
Accept: image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
Accept-Language: en-us
Referer: http://192.168.1.10:81/safari.html
Accept-Encoding: gzip, deflate
```

### PR DESCRIPTION
**Pull request by bryancall**
This closes #7099

What this patch does is only use exact match with the client Accept header field  and `Content-Type: image/webp` if there is a webp response in cache.

This change is also dependent on `proxy.config.http.cache.ignore_accept_mismatch` set to 0.  Alternatively I can make the change independent of `proxy.config.http.cache.ignore_accept_mismatch`.  Feedback is welcomed.

### CODE REVIEW

**Comment by maskit** [comment]
Chrome has `image/avif` and `image/apng` in its accept header. I'm not sure how much popular these formats are, but I guess similar things would happen if they were cached. We might want to handle these in the same way.
```
image/avif,image/webp,image/apng,image/*,*/*;q=0.8
```

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by bryancall** [comment]
Cherry picked to 9.0.x

**Pull request merged**
