### PR TITLE
client_bytes should be initialized as 0, it is exclusevely used by ge…

### PR DESCRIPTION
**Pull request by danm-netlify**
…t_info_from_buffer to count the number of copied bytes and set the last byte to 0

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
This is interesting, in that in 7.x, we didn't initialize client_bytes at all. I wonder if we need a separate PR for 7.1.x, to initialize it to 0 (I'm guessing it's 0 by happenstance now?).

**Comment by zwoop** [comment]
Also, for future references, please try to keep the first line on the commit message shorter, such that it fits on the Github page. Then add additional information on a separate line, which can then be ~70 characters wide if needed.

**Comment by danm-netlify** [comment]
it works all right in 7. I will try to remember the guidelines. Thank you

**Comment by bryancall** [comment]
There was a separate PR for this change to the 8.0.x branch and it is going to make it into the 8.0.1 release.  I am removing the milestone on this PR since it is already in a release.

**Pull request merged**
