### PR TITLE
TS-3965: regex_remap plugin does not deal with all possible redirects

### PR DESCRIPTION
**Pull request by davidbz**
Newbie here: I'm not sure I got them all, would appreciate a review :)

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
Looks good, 
:+1:

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/490/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/387/ for details.

**Pull request merged**
