### PR TITLE
TS-4729: Fix dead assignment.

### PR DESCRIPTION
**Pull request by shinrich**
Alternative to PR 847

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/515/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/412/ for details.

**Comment by zwoop** [comment]
@bryancall  Can you review please, you had some concerns on the previous PR.

**Comment by jpeach** [comment]
This change looks consistent with the nearby handling of ``is_done`` 👍

**Comment by bryancall** [comment]
The return value for {{response_initialize_data_handling}} should be changed.  It is a bad design to return a bool (normally that would be mean success or failure) from this method and have it mean that the chunking has been completed.

It would better to call mark_body_done() in the method or pass in an argument in the method call.

**Comment by shinrich** [comment]
Addressed @bryancall 's concerns with a new commit (squashed).

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/562/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/458/ for details.

**Pull request merged**
