### PR TITLE
TS-4660: Improve remap.config error messages.

### PR DESCRIPTION
**Pull request by jpeach**
Improve some of the confusion about which error message buffer to
use in remap_parse_config_bti. The final message is now constructed
to append the original failure message.

### CODE REVIEW

**Comment by jpeach** [comment]
@zwoop This is a stopgap to fix the error messages until we can do the larger refactoring in TS-4660.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/426/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/320/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
