### PR TITLE
Fix logging log file roll issue (#2544).

### PR DESCRIPTION
**Pull request by pbchou**
Perform the BaseLogFile::close_file() operation when rolling log files generated by the logging system.
Do not perform this operation for diagnostic log files (this was removed by commit 346b419).

### CODE REVIEW

**Comment by shinrich** [comment]
So without this change, the logging for diags won't move to the new file?

**Comment by pbchou** [comment]
@shinrich -- Please reference the issue #2544 for a description of the problem. What happened was a change was made to address diagnostic log files, but this broke the logging log files. My analysis is in the comments for the commit. Thanks for taking a look.

**Comment by pbchou** [comment]
@shinrich -- Sorry, with regards to the diag log files -- I did not touch those. My change only affects logging log files since it is called from the LogFile containing object.

**Comment by pbchou** [comment]
@shinrich -- The BaseLogFile::close_file() is called automatically when the destructor is called. This applies to diag log files since diag log files will destruct/construct to accomplish a roll. For the logging log files you keep the same object but do a close/open to accomplish the roll. Thus, removing the close to address diag log files breaks logging log files. This PR adds the close back in but only for logging log files. Hope this makes sense.

**Comment by danobi** [comment]
I don't remember much of this but I do apologize anyways :)

**Comment by zwoop** [comment]
@pbchou Do we need this for 7.1.x as well? If so, can you please make a PR against the 7.1.x branch?

**Comment by pbchou** [comment]
@zwoop -- Please see PR #4534 just opened. Sorry for the delay. I was out on vacation.

**Comment by pbchou** [comment]
@bryancall -- Can we get this back-ported to 8.0.x also? It will cherry-pick cleanly.

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
