### PR TITLE
Fix a ssl handshake crash during shutdown

### PR DESCRIPTION
**Pull request by duke8253**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
How is this different from `shutdown_event_system`?

**Comment by shinrich** [comment]
He is setting the ssl_shutdown before the hook handling completes.  So any TLS processing should stop sooner.  With our other plugin fix, not entirely sure this one is necessary, but it shouldn't hurt anything.

**Comment by duke8253** [comment]
Since the lifecycle hook might take some time to finish, depending on the implementation of the handler, it seems to be a better choice to make sure the ssl handshake stops before it.

**Comment by SolidWallOfCode** [comment]
Why not set `shutdown_event_system` before calling the hooks?

**Comment by duke8253** [comment]
Because we want to make sure the event loop shuts down last to make sure things are not messed up.

**Pull request merged**
