### PR TITLE
Doc: tweaks and cleanup

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Just getting annoyed at the range of errors in the documentation build so cleaning up a few. The version tweaking clears up over 400+ errors for me, so I definitely like that. I am also trying to clear out all the cluster documentation as AFAIK there is no clustering anymore.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1059/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/951/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1060/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/952/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1061/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/953/ for details.

**Comment by zwoop** [comment]
@jsime Can you review please?

**Comment by SolidWallOfCode** [comment]
I'm a bit at a loss about what to do with enums. For some bizarre reason the C++ domain has enum support but C doesn't. The choices are

* Use C 'type' and 'var'
* Use C 'type' and 'member'
* Use C++ 'enum' and 'enumerator'

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1063/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/955/ for details.

**Comment by jsime** [comment]
Sorry it took a couple days to review, but everything non-enum related looks good. Thanks for all the cleanup, @SolidWallOfCode!

The lack of proper enum support in the C sphinx domain is bothersome. I'd be inclined to either abuse the C++ domain's enum support even for C code, or take the longer view of trying to port (or encourage someone to port) the enumerator from the C++ domain to the C domain in Sphinx. The latter would involve us bumping Sphinx versions, but at least it would feel less wrong than using the wrong Sphinx domain for parts of the TS C API docs.

**Comment by zwoop** [comment]
@SolidWallOfCode If I read Jon's comments right, he's asking that we do this differently?

**Comment by jsime** [comment]
Ah, no, sorry - this does look good as-is and I'm going to merge here momentarily. I was more thinking aloud about a somewhat longer-term approach to the enum issue (since we don't have an ideal solution with the current domains in Sphinx). But that shouldn't hold this PR up, since there's lots of other great cleanup in here.

**Pull request merged**
