### PR TITLE
Fix HTTPInfo::unmarshal function memory leak by call ats_malloc.

### PR DESCRIPTION
**Pull request by WolfgangBai**
about Issue 2436 https://github.com/apache/trafficserver/issues/2436. @SolidWallOfCode

### CODE REVIEW

**Comment by scw00** [comment]
I'm wondering if we do clean that copy of frag_table, What should we do with the `HttpTransaction::State::object_read` and the raw data in RamCache.

**Comment by scw00** [comment]
I push another fixes to refactor the m_frag_offsets marshaling.

**Comment by SolidWallOfCode** [comment]
The fragment table should be cleaned up in `HttpCacheAlt::destroy` when the instance is put on the proxy allocator free list. Is there any evidence that is not happening?

**Comment by WolfgangBai** [comment]
tim 20190128221315
yes, you can see unmarshal_helper.it is not have a  HTTPInfo  instance when it was called.

**Comment by SolidWallOfCode** [comment]
Interesting. However, that's an error case. It seems to be the better approach would be to change `unmarshal_helper` to clean up the fragment table at that moment, rather than making a more complex change elsewhere which might have unanticipated side effects. Or, alternatively, change `HTTPINfo::unmarshal` to not allocate the fragment table until the URL and MIME heaps have been successfully unpacked.

**Comment by WolfgangBai** [comment]
first of all.this problem from [https://github.com/apache/trafficserver/commit/84fa7a4d7123c86e6debc42bac2684945769bb3c](url).if it is ture,it will influences all above 3.3.1.
 besides, I generally agree with your two ideas. first idea, because HTTPCacheAlt::copy_frag_offsets_from function use that ats_malloc memory, so  i free in a new function HTTPCacheAlt::copy_frag_offsets_from_and_free. second idea is [https://github.com/apache/trafficserver/pull/4874](url)
   finally,No matter  pick which solution, I just hope that the problem can be paid attention to and solved. I hope that trafficserver will become better and better.

**Comment by zwoop** [comment]
Can we close this now that we landed scw00s fix? We don’t need both, right? And thanks for the work and PR!

**Comment by WolfgangBai** [comment]
sure,you can!

**Pull request closed without merging**
