### PR TITLE
Avoid using possibly freed memory when getting next link

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
I think the analyzer is wrong - it will never be the case that `n` == `x` and therefore freeing `n` doesn't invalidate `x`.  I think I'd rather try changing line 361 to be `n = next(x);` and see if that works.

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Pull request closed without merging**
