### PR TITLE
Check return values of openssl api calls

### PR DESCRIPTION
**Pull request by duke8253**
Check return values of openssl api calls when trying to resume sessions.

### CODE REVIEW

**Review by bneradt — COMMENTED** [review]
Looks good. Pretty straightforward.

**Review by randall — APPROVED** [review]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
I thought there was a autest problem on Monday, but looks like it's fixed now.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
