### PR TITLE
Add generic "guard" class (PostScript) for exception and early function return safety.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
I would think the implementation would be simpler with `std::function`.  It avoids any need of templates and supports passing in lambdas with bound arguments.

Why have two classes? What would be the problem with using `GuardX` and not calling `release`?

**Comment by ywkaras** [comment]
Unnatural lust for std::function notwithstanding, it works fine with lambdas the way it is.  See the updated unit test please.

Yeah we don't strictly need two classes.  The problem with working with PhDs is, every code review is like defending your thesis.

**Comment by SolidWallOfCode** [comment]
I'm curious as to why you are convinced there is never a good situation to use `std::function`, even if it means duplicating the logic in that class. Why not use something that's already written and tested?

**Comment by ywkaras** [comment]
How am I duplicating any logic?  Look at the constructor for std::thread :  https://en.cppreference.com/w/cpp/thread/thread/thread
std::function is just one function-like thingy.  The way this is coded currently, the optimizer seems able to optimize it down to the inlined to the inlined destructor of Guard.

**Comment by ywkaras** [comment]
By the way, you can't avoid templates because of the use of parameter packs.

**Comment by SolidWallOfCode** [comment]
Yes you can. Here's a working implementation without templates -
```
class Guard {
public:
  using F = std::function<void ()>;
  Guard(F const& f) : _f(f) {}
  ~Guard() { if (_active_p) _f(); }
  void release() { _active_p = false; }
protected:
  F  _f;
  bool _active_p { true };
};
```
I think you're over micro-optimizing because the actual performance difference is on the order of single digit nanoseconds, in cases where the overall cost of handling exceptions is several orders of magnitude larger.

**Comment by ywkaras** [comment]
That approach would require using a lambda every time.  Don't see how that's simpler.  Note that, when Guard / GuardX is used, the template type arguments are deduced typically.

When designing something for heavy reuse, makes sense to pay some amount of attention to performance.  The implementation of std::function is very tricky, I'm not sure what the performance cost is.  And, it's a template, by the way, so not a template-free alternate, if it matters.

**Comment by ywkaras** [comment]
wkaras ~/REPOS/TS
$ fgrep goto $(find . -name \*.h -o -name \*.cc ) | wc -l
     796

Most of these gotos are probably associated with cases where `Guard` is what's needed.  So having Guard's runtime footprint be unnecessarily bloated is best avoided.

**Comment by ywkaras** [comment]
https://godbolt.org/g/qhbJqy

86 lines of assembler versus 12

**Comment by SolidWallOfCode** [comment]
All the code reduces to assembler, too, so your code is not assembler free in the same way my code is not template free. It doesn't seem a useful claim.

Performance is usually a trade off between code complexity and speed and in a code base that is already complex, sacrificing a marginal if not completely undetectable performance change for simpler and more maintainable code can be a good choice. In this case, I don't think really matters much, but you do seem excessively sensitive to use of certain STL mechanisms for reasons that are not clear to me. In this case I think the over complexity is the existence of two classes that do almost the same thing, with no real penalty for using the more complex case (unless your view is the extra 500 picoseconds or so for the flag check is too much of a performance cost).

**Comment by ywkaras** [comment]
Whether there are two classes or just one is a separate issue from whether we should force the use of lambda function in virtually all cases.

Optimizations can't be judge properly based just on what is saved in a single instance.  The more something is used, the lower the threshold for what is a useful optimization of it.

When something has better performance and is also generally easier to use, it makes no sense to say we shouldn't use it because we don't want to optimize prematurely.

**Comment by ywkaras** [comment]
OK GuardX is gone.

**Comment by SolidWallOfCode** [comment]
Now we can argue about the name! "Guard" is usually used for protective mechanisms, such as locks or guards against garbage collection. This will normally do the opposite and guarantee destruction. Something like "Always" or "Afterwards" or "PostAction" or "OnExit" or "PostScope" or "ScopeAction" or "PostScript". I kind of like "Afterwards" or "PostScript".

**Comment by ywkaras** [comment]
I think I'm using the term "guard" in a common way.

https://www.boost.org/doc/libs/1_31_0/libs/pool/doc/implementation/guard.html

A guard against exiting a block without doing something that needs doing before you exit.  Because of an exception, or because of forgetting to do it at all the explicit block exit points (typically function returns).  If we used RAII religiously, we probably would have little or no use for Guard.  It's more of a transitional thingy as we hopefully move towards consistent use of RAII.

But really your code reviews come close to breaking my will to live, so I'll go along with whatever name you want.

**Comment by SolidWallOfCode** [comment]
I guess I read that different, in that the guard is about protecting a data structure with the mutex, a key difference being that guard does the lock and the unlock, rather than just doing clean up, e.g. RAII. The  lock release is an implementation detail.

I'm not sure more thorough RAII will work, because the cases where this is useful are exactly those where RAII is problematic. For instance, if it involves a resource where `delete` suffices, then I'd just used `std::unique_ptr` instead of this class. Your example, with releasing an `MLoc`, is the kind of thing that requires a specialized RAII class. I suppose in the long run those could be written.

**Comment by ywkaras** [comment]
Well how can we move this along, because I want to use it for some minor cleanup as I'm doing the xdebug changes.

**Comment by SolidWallOfCode** [comment]
OK, let's go with "PostScript".

**Comment by ywkaras** [comment]
Why not PDF?

**Comment by SolidWallOfCode** [comment]
It's not a display format.

**Pull request merged**
