### PR TITLE
Issue 1597: refactor ParentSelection to remove duplicate code

### PR DESCRIPTION
**Pull request by jrushford**
ParentConsistentHash and ParentRoundRobin had identical implementations for markParentUp() and markParentDown().  This pr eliminates the duplication moving these functions to ParentConfigParams.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by zwoop** [comment]
You should squash the two commits, and there's some build errors too :-).

**Comment by zwoop** [comment]
The tests are failing e.g.

```
libinknet.a(Socks.o): In function `SocksEntry::findServer()':
/var/jenkins/workspace/linux-github/src/iocore/net/Socks.cc:101: undefined reference to `ParentConfigParams::markParentDown(ParentResult*, unsigned int, unsigned int)'
libinknet.a(Socks.o): In function `SocksEntry::free()':
/var/jenkins/workspace/linux-github/src/iocore/net/Socks.cc:155: undefined reference to `ParentConfigParams::markParentUp(ParentResult*)'
```

Maybe you need some includes or additional library to the test builds?

**Comment by jrushford** [comment]
I know, I’m working on it.  Something is fishy though, all the includes and libraries are correct.  Builds fine here.

**Comment by vmamidi** [comment]
@jrushford hey can you check why the checks are failing ?

**Comment by jrushford** [comment]
Hi vijay, I know why checks are failing.  Just haven’t had time to fix it.  I’ll get it fixed in a day or two.

**Comment by zwoop** [comment]
Also, when fixing this, please squash the commits.

**Comment by jrushford** [comment]
fixed unit test link errors, test_lookupcert and test_UDPNet

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Pull request merged**
