### PR TITLE
TS-5070 Add configuration variables to set file permissions for diags.log & traffic.out

### PR DESCRIPTION
**Pull request by danobi**
We add 2 more config variables to control file permissions for
diagnostics logs. These are not reloadable.

### CODE REVIEW

**Comment by danobi** [comment]
I'm not sure if using `CAP_FOWNER` is the "correct" approach, but at least it works. :/

**Comment by shinrich** [comment]
[approve ci]

**Comment by shinrich** [comment]
The logic looks reasonable.  The invocation of the OWNER privilege looks correct.  I guess we could avoid that elevation if we did the chmod at the point of the file was created, but I would assume that would be a pretty significant code change.

The default permissions look odd, but that seems to be the pre-existing default.  As -1, I assume that chmod() interprets that as all bits set so in addition to setting everything wide open (0x777), it would set the setuid/setguid bits as well.  But again, that is a separate issue.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1294/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1188/ for details.

**Comment by zwoop** [comment]
For future references, this really should have been squashed down to one commit before merging.

**Comment by bryancall** [comment]
Please squash commits before merging.

**Pull request merged**
