### PR TITLE
Unify all the connect timeouts into one

### PR DESCRIPTION
**Pull request by shinrich**
Eliminate proxy.config.http.parent_proxy.connect_attempts_timeout and proxy.config.http.post_connect_attempts_timeout and   instead use proxy.config.http.connect_attempts_timeout and associated overrides to control all connection to origin timeouts.

I sent a mail to the dev mailing list to start a discussion on this.  I forget about the proxy.config.http.post_connect_attempts_timeout option and we have left this at the default of 1800 seconds.  

Differentiating on the method may have been useful when the connect timeouts were really measuring TTFB.  But now that they are only applied to the time for the TCP or TLS handshake, it seems more confusing to separate them.

Similarly having a different timeout for the parent connect case seems like more confusion than it is worth.

Since I did not leave placeholders in the override enums, this PR is a breaking change. If it was brought into the 9.x releases after 9.0.0 is released, we would have to add some placeholder enums.

### CODE REVIEW

**Review by bryancall — DISMISSED** [review]

**Comment by bryancall** [comment]
@ezelkow1 is going to take a look at it.

**Review by ezelkow1 — DISMISSED** [review]
lgtm

**Comment by ezelkow1** [comment]
oh do we need to update the docs for this too before you have to rebase? Since i think we have that 'whats changed' section now

**Comment by shinrich** [comment]
Looks like I need to rebase anyway.  So I'll update the changed info too.

**Review by ezelkow1 — APPROVED** [review]

**Pull request merged**
