### PR TITLE
Drain stop and drain improve

### PR DESCRIPTION
**Pull request by zizhong**
This PR includes 

1. `Add maximum time limit for draining` from @maskit, 
2. `Add traffic_ctl server stop --drain` from @maskit and 
3. `Fixing #2906: improve draining` from me.

For the `Fixing #2906: improve draining`,

1. Adding `traffic server drain` subcommand
2. Adding default option, --no-new-connection option and --undo option

TODO:
1. implement `is_server_idle_from_new_connection()`
2. update docs
3. adding tests

@maskit @bryancall @zwoop @oknet @scw00 @masaori335 can you guys review it when you got time? Any ideas would be much appreciated!

### CODE REVIEW

**Comment by maskit** [comment]
Thanks for making progress on drain feature.

Some parts of the changes are written by me, but to be honest, I'm not familiar with this area. I just imitated code that is already there. I'd like to traffic_manager / traffic_ctl experts to review this.

@jpeach This includes what we discussed on the list long time ago. Please review it if you have time.

**Comment by maskit** [comment]
[approve ci]

**Comment by zizhong** [comment]
The autest failure is not reachable now. Can you help to trigger another one? @maskit @bryancall @zwoop @scw00 ? Thanks!

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci]

**Comment by maskit** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci debian]

**Comment by zwoop** [comment]
@zizhong This is getting close, can you squash the commits into one?

**Comment by zizhong** [comment]
@zwoop Thanks. Did the squash.

**Pull request merged**
