### PR TITLE
Make Cripts contexts use Proxy Allocator, and cleanup

### PR DESCRIPTION
**Pull request by zwoop**
In addition:

* Some docs updates
* Makes the immutable URLs (such as remap From-URL) read-only.
* Don't reset() those immutable URLs, once setup, it can be reused between all hooks inside the transaction.

Fwiw, the reset to reset() URLs between hooks is because other plugins may modify URLs, and then the header heaps etc. can reallocate / move, and then it's hilarious to debug ...

### CODE REVIEW

**Review by cmcfarlen — DISMISSED** [review]

**Comment by JosiahWI** [comment]
The AuTests prefetch_simple and proxy_serve_stale failed.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
The AuTest tunnel_transform failed (client returned exit code 35).

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
The AuTest proxy_protocol failed on the run "Proxy Protocol v1 without blind tunneling on TLS connection to origin" because the default process returned exit code 1 instead of 0.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Review by cmcfarlen — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
