### PR TITLE
Add retry of killproc in trafficserver script for RedHat/Fedora.

### PR DESCRIPTION
**Pull request by ywkaras**
Work-around for:  https://github.com/apache/trafficserver/issues/2758 .

### CODE REVIEW

**Comment by bryancall** [comment]
How are you testing this?  Also, I am not able to get killproc to exit with 7 when the process is not running:

```
15:22:06 homer:(master)~/dev/apache/trafficserver$ cat /usr/local/var/trafficserver/server.lock
666
15:22:24 homer:(master)~/dev/apache/trafficserver$ sudo /etc/redhat-lsb/lsb_killproc -p /usr/local/var/trafficserver/server.lock /usr/local/bin/traffic_server; echo $?
0
```

**Comment by ywkaras** [comment]
I don't know of any way to test the retry logic in a repeatable way.  If it's possible it would probably require a high-volume traffic generator or some sort.

**Comment by zwoop** [comment]
Are you sure that this wasn't fixed already with dcc193f3518857f685280b6d9b42a81ff259e1bb ? killproc has support for the retry already, with a more aggressive signal on the second try. This is what we've been using with 7.1.x in production for a while now, and have not seen this issue since.

**Comment by shinrich** [comment]
We are running with the  dcc193f change, and still see the problem of trafficserver stop failing.  That commit adds a 35 second delay before giving up on kill -TERM <pid>.  Then it calls kill -9 <pid> and waits 0.1 second before determining whether the process really went away.  In some cases, it seems that a really slow process that isn't responding to the kill -TERM takes more than 0.1 seconds for the kill -9 to propagate and update the /proc files that the script is checking.  We really need to add some time after the kill -9 which I think this commit is doing.

**Comment by ywkaras** [comment]
@zwoop the change you link to is already present in the in-house Oath TS branch.  But it seems to happen a lot that the TERM won't stop traffic_server, and the 0.1 sec wait for KILL to kill traffic_server is too short.  The alternative to retrying killproc is to copy the bash code out of Red Hat Land into the trafficserver script, and increase the KILL wait time.  But it's a lot of code to copy just to change one line.  Derek (sorry can't remember his gamer/ATS name) has suggested we configure our package manager to retry the whole trafficserver script when it fails.  Or we could find a script command to trigger the Universe Big Crunch as the ultimate retry when killproc fails.

dragon512 says he's never seen a problem with just sending  TERM to traffic_cop and letting it shut manager and server down.  (Or I'm just thinking he said it because I'm senile.)

**Comment by d2r** [comment]
> Derek (sorry can't remember his gamer/ATS name) has suggested we configure our package manager to retry the whole trafficserver script when it fails. 

I suggested this as a temporary, internal work-around to our packaging. It is not something to discuss here as a solution, I think.

**Comment by dragon512** [comment]
@zwoop I think we should rethink this. I am seeing with the latest testing some issue with traffic_cop shutting down. This forced me to fix the last set of test to Term traffic_cop process group in the Autest extensions, as traffic_cop would not shut everything down correctly. There would still be a running process of trafficserver running on the ports preventing start up of trafficserver in the next test ( as these test used the default 8080 ports) I am 100% positive we have a bug in ATS. The term here, if I understand correct, should speed up restarts.

**Comment by ywkaras** [comment]
Closing to remove clutter from open PR list.

**Pull request closed without merging**
