### PR TITLE
Deal with the case when the hostdb cont may not have a mutex

### PR DESCRIPTION
**Pull request by shinrich**
Caused some crashes for an internal deployment.

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
can you share what the crash stack trace looks like ?

**Comment by vmamidi** [comment]
can you share the stack trace?

**Comment by zwoop** [comment]
I'm going to remove the 7.1.5 Project on this, since going forward, we will need to make a second PR against the 7.1.x for proposed back ports.

**Comment by bryancall** [comment]
Cherry picked to 8.1.0

**Pull request merged**
