### PR TITLE
Add test for ticket reuse with proxy.config.ssl.server.ticket_key.filename

### PR DESCRIPTION
**Pull request by shinrich**
~In the original order, a random ticket was created instead of using the global default.~

[From the comments]
I've changed this PR into a test-only PR. Using openssl s_client against two different instances of traffic_server using the same ticket key file to verify that the ticket can move between the two Traffic Server processes. However, this test requires the next version of autest (1.7.0).

### CODE REVIEW

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
This does not fix what I'm seeing on 7.1.x. I'm still trying to debug on my side.

**Comment by zwoop** [comment]
we still need more work on this? @randall I think you should "-1" this until it's resolved, so we don't merge it accidentally.

**Comment by shinrich** [comment]
Yes, we should wait until we know this fixes things for @randall.  I'll go ahead and add an autest for this case.

**Comment by randall** [comment]
Investigated our issue. 

Root cause was differing ca-bundle.crt (pointed to via proxy.config.ssl.CA.cert.filename) across machines.

The variations were differences in order for our local CAs.

**Comment by shinrich** [comment]
So once you fixed the ca-bundle.crt things started working even without this code change?

**Comment by shinrich** [comment]
Ok, I must have been seeing things in Sunnyvale.  Things work with the code change and without.  So I've changed this PR into a test-only PR.  Using openssl s_client against two different instances of traffic_server using the same ticket key file to verify that the ticket can move between the two Traffic Server processes.  However, this test requires the next version of autest (1.7.0).

**Comment by randall** [comment]
Sorry @shinrich for not answering your question.

Without the code change and with the identical ca-bundle.crt, tickets across hosts started working for me.

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Pull request merged**
