### PR TITLE
TS-4635: Fix RefCountCacheSerializer file descriptor leaks.

### PR DESCRIPTION
**Pull request by jpeach**
Fix various file descriptor leaks on the RefCountCacheSerializer error path. Move RefCountCacheSerializer to a separate header so that it only gets included in the one place that needs it.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/411/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/305/ for details.

**Comment by zwoop** [comment]
Hmmm, this code looks overly complicated already to begin with :-/. Why is RefCountCacheSerializer a template class? It's tightly coupled with HostDB it seems, and is only used to contain HostDBInfo?

If we are going to clean this up, I'd strongly suggest not using templates just because. I know this isn't your fault James (in any way), and you are trying to make it better, but this is not good.

That much said, I'm ok with the refactoring, it's making it a bit better (but I still don't like this :). As someone smart said, this is premature generalization.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
