### PR TITLE
add API to replace OCSP refresh function

### PR DESCRIPTION
**Pull request by mrmiywj**
Add an API to register user-customized OCSP refresh function.

### CODE REVIEW

**Comment by mrmiywj** [comment]
#3997

**Comment by persiaAziz** [comment]
Please add documentation for this API

**Comment by zizhong** [comment]
@mrmiywj can you redo it against the master branch?  We'd always push changes to master first, then backport to the old branch.

**Comment by PSUdaemon** [comment]
I think that even if 6.2.x wasn't EOL that this wouldn't be a candidate for a backport as it's adding a new feature. I am closing, please open up a new PR against master.

**Pull request closed without merging**
