### PR TITLE
Make README a Markdown Doc, Add Badges

### PR DESCRIPTION
**Pull request by moonchen**
* An almost 1-for-1 translation from plain text to Markdown.
* Add badges for build status from Jenkins builds.
* Remove badges when building a release tarball.

### CODE REVIEW

**Comment by bneradt** [comment]
Ah, funny. Our  jenkins scripts by convention perform a `head` on README just as a sanity check in the job's console output to show that things got checked out the way we expect. Let me tweak this...

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by maskit** [comment]
I'm fine with showing the badges on GitHub, but having those lines for badges doesn't look great for a README in a tar-ball release.

**Comment by ezelkow1** [comment]
[approve ci osx]

**Comment by ezelkow1** [comment]
[approve ci freebsd]

**Comment by bneradt** [comment]
[approve ci]

**Comment by moonchen** [comment]
> I'm fine with showing the badges on GitHub, but having those lines for badges doesn't look great for a README in a tar-ball release.

I agree that the raw Markdown doesn't look as good as the raw text file.  I haven't found a good way to have both, without duplicating information.

For what it's worth, this method is commonly accepted.  I referenced the most starred repositories under Apache's GH org, and trending GH repositories in general.  All of the badged repositories have chosen to include badges in their README.md under the root directory.

**Review by bneradt — DISMISSED** [review]

**Comment by maskit** [comment]
Yeah, I checked other Apache projects too, and many projects keep them in releases. A possible way is to remove the lines when we make tar ball.

@bryancall @zwoop Do we have a script to make release tar balls? Is it possible to modify README.md on the script if we have it?

**Comment by moonchen** [comment]
> I'm fine with showing the badges on GitHub, but having those lines for badges doesn't look great for a README in a tar-ball release.

I added some code to remove badges from the release tarball.

**Review by bneradt — APPROVED** [review]
Thank you for working on this. I think this will present a better face for the project when people visit our GitHub page.

**Review by maskit — APPROVED** [review]
👍

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
