### PR TITLE
Issue #1685: Use TS_MILESTONE_UA_BEGIN for cqt* log fields

### PR DESCRIPTION
**Pull request by masaori335**
- Add functions to marshal milestone in some formats (unix timestamp, squid, netscape, date, and time)
- Use TS_MILESTONE_UA_BEGIN for cqtd, cqtn, cqtq, cqts, cqth, and cqtt
- Add description of `cqth` in docs

### CODE REVIEW

**Comment by masaori335** [comment]
Fix #1685

**Comment by zwoop** [comment]
[approve ci]

**Comment by maskit** [comment]
Although this is obviously a bug fix, I think we should probably label this incompatible because aggregating logs with and without this fix will make inconsistent records.

**Comment by danobi** [comment]
Been in japan the past few weeks. Hopefully I get some downtime to look at this in a couple days.

**Comment by masaori335** [comment]
@zwoop I tested those 6 formats in my local env. But it looks hard to add unit tests or autest:(
@danobi Thanks, I'll leave this open for a while.

**Comment by zwoop** [comment]
I'm cherry-picking this into 7.1.1.

**Pull request merged**
