### PR TITLE
verify client certificate callback with client verify hook

### PR DESCRIPTION
**Pull request by persiaAziz**
verify_cert plugin is included in the example to show the usage of the client verify hook

### CODE REVIEW

**Comment by shinrich** [comment]
Need to fix make check to reflect hook state addition.  Otherwise, looks good.

**Comment by persiaAziz** [comment]
yah forgot to add the client verify hook in InkAPITest

**Comment by persiaAziz** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
This might have build issues:

```
../../../iocore/net/SSLUtils.cc: In function 'SSL_CTX* SSLInitServerContext(const SSLConfigParams*, const ssl_user_config*, std::vector<x509_st*>&)':
../../../iocore/net/SSLUtils.cc:1736:51: error: 'ssl_verify_client_callback' was not declared in this scope
     SSL_CTX_set_verify(ctx, server_verify_client, ssl_verify_client_callback);

```

**Comment by persiaAziz** [comment]
https://github.com/apache/trafficserver/pull/3229 -- this might fix the problem

**Pull request merged**
