### PR TITLE
Metalink Plugin: Must not destroy the Transform Contp, only shutdown write on it while received WRITE_COMPLETE

### PR DESCRIPTION
**Pull request by oknet**
The Transform Contp is belongs to TransformVC chain and it will be closed by TransformVC. And then the plugin will be callback with EVENT_IMMEDIATE, the plugin will find the Transform Contp is closed by  TSVConnClosedGet() and call TSContDestroy() to destroy it.

### CODE REVIEW

**Comment by oknet** [comment]
@jablko

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1674/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1571/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/107/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1675/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/106/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1570/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/239/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/238/ for details.

**Comment by zwoop** [comment]
@oknet Can you please add the appropriate Label andMilestone for this PR? ("Plugins" and "7.2.0" respectively).

**Comment by zwoop** [comment]
I think this would be good for @jablko to review. Also, Jack, I think you have to go through the MATT process again to link your account, I'm not able to assign this to you for review.

**Comment by oknet** [comment]
@zwoop Could you create a new Label：Transform ？

**Comment by zwoop** [comment]
[approve ci] to test the new Github builds jobs configs.

**Comment by atsci** [comment]
clang-format check *successful*! See https://ci.trafficserver.apache.org/job/clang-format-github/1/ for details.

**Comment by atsci** [comment]
RAT check *successful*! See https://ci.trafficserver.apache.org/job/RAT-github/14/ for details.

**Comment by atsci** [comment]
FreeBSD11 build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1696/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1591/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/127/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/259/ for details.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/93/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/106/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/90/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1788/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1681/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/219/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/351/

**Comment by oknet** [comment]
The transform contp will be closed and destroied after TransformVC is closed.
The transformation plugin receives EVENT_IMMEDIATE when transform contp close then the plugin could release 'TransformData' and call TSContDestroy().

**Comment by zwoop** [comment]
@jablko Can you review this please? And also, I think your MATT connection needs to be redone, since we got moved to gitbox for the internal ASF sync service).

**Comment by oknet** [comment]
[approve ci]

**Comment by zwoop** [comment]
Should we merge this? We might have lost @jablko  ?? :)

**Comment by zwoop** [comment]
If this is a candidate for 7.x, please mark it as such (in the Projects tab).

**Pull request merged**
