### PR TITLE
update autest version

### PR DESCRIPTION
**Pull request by dragon512**

### CODE REVIEW

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
Are the last 4 commits of AuTest diff from `1.10.1`?  ( I can't find the 1.10.1 tag )
https://bitbucket.org/autestsuite/reusable-gold-testing-system/commits/tag/1.10.2

**Comment by masaori335** [comment]
Replying to myself, the release note is below.

> Release 1.10.2
> - [Fix][[PR #29](https://bitbucket.org/autestsuite/reusable-gold-testing-system/pull-requests/29)] Improve StreamWriter performance
> - [Fix] Exists test for file enities did not work correctly when setting False value in constructor
> - Clean up testing logic to include 3.11
> - [Fix] Change to using inspect.getfullargspec() api as older API has been removed from python core

https://bitbucket.org/autestsuite/reusable-gold-testing-system/src/master/docsrc/source/changelog.rst

**Review by masaori335 — APPROVED** [review]

**Comment by bneradt** [comment]
In case it's helpful, one of the things going into this AuTest release is a performance improvement with stream output processing for processes that produce a lot of output. Our ASF CI handles the new `http2_flow_control` test well, but we noticed in our internal Yahoo CI that we were getting test failures in `http2_flow_control` because the test was timing out processing the output. This new AuTest release addresses that issue.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
