### PR TITLE
Temporarily disable ParentProxy API tests.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by jpeach** [comment]
@zwoop

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/404/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/299/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
