### PR TITLE
Revert "DNS: Fix lack of nameserver failover in low use circumstances…

### PR DESCRIPTION
**Pull request by bneradt**
…. (#7843)"

This reverts commit 2fbec37b64d9d01c4a8c45a80245b432b9484e18.

I'm reverting this to test whether this commit introduced CI regression
test instability.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
That patch fixed a Yahoo! production bug (where an ATS is sitting directly in front of a Jetty application on the same box, and only ever resolves for the FQDN of that box). Flaky DNS would eventually disable all of the nameservers, requiring a restart. The interesting question is, why would changes in HostDB have this effect?

**Comment by ywkaras** [comment]
Can we make a fake PR that turns on certain debug tags in the regression test runs in CI?  Would that perhaps provide better info?

**Comment by ywkaras** [comment]
In failed regression tests in #8662 like https://ci.trafficserver.apache.org/job/Github_Builds/job/centos/508/console we see:
```
REGRESSION TEST SDK_API_TSHttpConnectServerIntercept started
[Feb 10 15:53:20.173] [ET_NET 0] WARNING: connection to DNS server 10.255.250.30 lost, marking as down
[Feb 10 15:53:20.173] [ET_NET 0] WARNING: connection to DNS server 10.255.251.30 lost, marking as down
[Feb 10 15:53:20.173] [ET_NET 0] WARNING: connection to all DNS servers lost, retrying
TEST 158 *** STARTING ***
*** TEST 158 *** PASSED ***
...
Regression test(SDK_API_TSHttpConnectServerIntercept) still in progress
Regression test(SDK_API_TSHttpConnectServerIntercept) still in progress
[Feb 10 15:53:50.174] [ET_NET 2] WARNING: Synserver failed to bind to port 65535.
Fatal: traffic_server/InkAPITest.cc:910: failed assertion `!"Synserver must be able to bind to a port, check system netstat"`
```
In successful tests, we'll eventually see:
```
[Feb 10 15:52:11.589] [ET_NET 0] WARNING: connection to DNS server 10.255.250.30 restored
```
What's weird is that I don't think the ConnectServerIntercept test should really need any DNS lookup, it's testing the APIs for intercept plugins.

**Review by ezelkow1 — APPROVED** [review]

**Comment by bneradt** [comment]
What confuses me is that, given this message:

```
[Feb 10 15:53:50.174] [ET_NET 2] WARNING: Synserver failed to bind to port 65535.
```

That failure is associated with the `#define SYNSERVER_DUMMY_PORT -1` value. However, that occurs in the `synserver_vc_refuse` which is only associated with a continuation in a single place:

https://github.com/apache/trafficserver/blob/92d238a8fad483c58bc787f784b2ceae73aed532/src/traffic_server/InkAPITest.cc#L7335

How did that function get called back with the 65535 (-1 for 16 bits) rather than the `#define SYNSERVER_LISTEN_PORT 3300` value?

**Comment by bneradt** [comment]
> What confuses me is that, given this message:
> 
> ```
> [Feb 10 15:53:50.174] [ET_NET 2] WARNING: Synserver failed to bind to port 65535.
> ```
> 
> That failure is associated with the `#define SYNSERVER_DUMMY_PORT -1` value. However, that occurs in the `synserver_vc_refuse` which is only associated with a continuation in a single place:
> 
> https://github.com/apache/trafficserver/blob/92d238a8fad483c58bc787f784b2ceae73aed532/src/traffic_server/InkAPITest.cc#L7335
> 
> How did that function get called back with the 65535 (-1 for 16 bits) rather than the `#define SYNSERVER_LISTEN_PORT 3300` value?

Oh, I see. There are two messages with that exact same `Synserver failed to bind to port` warning, one in `synserver_vc_refuse` and another in `synserver_vc_accept`. I was looking at the wrong message location.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
