### PR TITLE
Do NOT kill tunnel if it has any consumer besides HT_HTTP_CLIENT

### PR DESCRIPTION
**Pull request by masaori335**
An alternative of #7605 for #7603.

### CODE REVIEW

**Comment by shinrich** [comment]
This also seems like a reasonable approach.  Will be interesting to hear how it works in your environment.

**Comment by vmamidi** [comment]
Shouldn’t the check be for any alive consumer?

**Comment by SolidWallOfCode** [comment]
Need to verify the `HttpSM` is shut down when the `CacheVC` terminates.

**Comment by masaori335** [comment]
Side effects (more active client connections and fewer client aborts) of #7605 are gone with this approach. I'll update this to check other consumer types.

**Comment by masaori335** [comment]
@SolidWallOfCode The background fill is working for "HTTP/1.1 over TCP" and "HTTP/2". Do we have any issues with `CacheVC` termination? It should not special for "background fill on HTTP/1.1 over TLS".

**Review by shinrich — APPROVED** [review]
This seems reasonable.  Since it is an EOS, you won't be delaying any additional requests waiting on the HTTP/1.x client session.

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by ezelkow1** [comment]
Do we still want this for 8.1? If so we will need a backport

**Comment by masaori335** [comment]
Yeh, the issue (#7603) was introduced 7.1.5.

**Pull request merged**
