### PR TITLE
Fixes the number of traversal events

### PR DESCRIPTION
**Pull request by hankai17**

### CODE REVIEW

**Comment by zwoop** [comment]
Can you please make a more descriptive Subject on this PR? The current is very non descriptive.

**Comment by hankai17** [comment]
We know that: poll return a positive number when success; this is the number of structures which have non-zero revents fields (in other words, those descriptors
with events or errors reported). We should go through the number of structures which have non-zero revents fields  instead of the value "ip".

**Comment by zwoop** [comment]
Perfect, thanks!

**Comment by randall** [comment]
[approve ci]

**Pull request merged**
