### PR TITLE
[TS-4157] traffic_via tests use bad characters in the file name

### PR DESCRIPTION
**Pull request by dragon512**
Changed the usage of : to ; which seems to be more filename friendly.
Changed test files to have ; in them

### CODE REVIEW

**Comment by zwoop** [comment]
I don't think you can just change the ':' to a ';'. The ':' is what the Via: header will have, which means, you'd break compatibility. Meaning, it would no longer properly parse the input from a Via: header (I think at least).

One option is to allow the separator to be either ';' or ':', such that the file names can use the ;, whereas the string in the Via: header continues to use ':'.

**Comment by dragon512** [comment]
Thanks. I have updated the patch with this fix

**Comment by meeramn** [comment]
Updated patch looks good.

**Comment by jpeach** [comment]
There is not really a good reason for these tests to store weird names in the filesystem. It just happened to be an easy way to do what I needed at the time. A better solution would be to figure out a way to not need these files in the first place.

**Comment by SolidWallOfCode** [comment]
Ultimately I think you'd just want the values in file, one per line. But that's a bigger fix.

**Comment by dragon512** [comment]
I agree with James in that the test are badly written. A better fix would be to use a real testing system. I working on that as well. It would be worse just to fix these tests and not others as this just adds to random chaos that already exists in the source tree of ATS. I am working on presenting a better test setup for ATS ( unit testing and a fix for TSQA), as well as trying to fix the build and source layout. This has to be done correctly and in baby steps with a plan.
However the main fix here was not to fix badly written and apparently rushed tests, but solve use of values that break ATS from being checked out on file systems that don't allow certain values in the file name. This is only a small fix of many we need to clean up ATS infra.

**Pull request closed without merging**
