### PR TITLE
TS-4976: Regularize example plugin basic_auth.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Incremental #1114

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/freebsd-github/1670/ for details.

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/102/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1566/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/234/ for details.

**Comment by bryancall** [comment]
Looks like you removed a file and didn't add one.

**Comment by SolidWallOfCode** [comment]
Yeah, I must have used `mv` instead of `git mv`. Sigh.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/freebsd-github/1683/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1579/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/115/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/247/ for details.

**Comment by maskit** [comment]
Could you also update the documentation?
```
$ git grep basic-auth.c doc
doc/developer-guide/plugins/example-plugins/basic-authorization/index.en.rst:The sample basic authorization plugin, ``basic-auth.c``, checks for
doc/developer-guide/plugins/example-plugins/index.en.rst:and ``basic-auth.c``.
doc/developer-guide/plugins/getting-started/index.en.rst:-  ``basic-auth.c`` performs basic HTTP proxy authorization.
doc/developer-guide/plugins/introduction.en.rst:``blacklist-1.c``, ``basic-auth.c``, and ``redirect-1.c``.
```
You can ignore `*.po` files.

**Comment by SolidWallOfCode** [comment]
Allright.

**Comment by SolidWallOfCode** [comment]
@maskit For future reference, in your `.bashrc`.
```
function findrst {
find . -name '*.rst' -exec grep "$1" {} \; -print
}
```
Then `findrst basic-auth` in either the base directory or `doc`.

**Comment by atsci** [comment]
clang-format check *successful*! See https://ci.trafficserver.apache.org/job/clang-format-github/2/ for details.

**Comment by atsci** [comment]
RAT check *successful*! See https://ci.trafficserver.apache.org/job/RAT-github/15/ for details.

**Comment by atsci** [comment]
FreeBSD11 build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1697/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1592/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/128/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/260/ for details.

**Pull request merged**
