### PR TITLE
Fix use-of-uninitialized value problem found by fuzzing

### PR DESCRIPTION
**Pull request by shukitchan**
Details here - https://oss-fuzz.com/testcase-detail/4793610426449920

### CODE REVIEW

**Comment by JosiahWI** [comment]
It'd be nice to have see the input that caused this. Zero-initializing the array may not be an appropriate fix, because if the data in the array is being processed past the correct number of bytes, we're probably reading an incorrect value.

**Comment by JosiahWI** [comment]
I do not have authorization to the above link.  Thank you for the stack trace.

**Comment by shukitchan** [comment]
The input causing this is here 
[clusterfuzz-testcase-fuzz_http3frame-4793610426449920.txt](https://github.com/user-attachments/files/16665283/clusterfuzz-testcase-fuzz_http3frame-4793610426449920.txt)

**Comment by shukitchan** [comment]
Yeah, not a good idea at this point to initialize with zero.

**Pull request closed without merging**
