### PR TITLE
cache_promote plugin:  put a mutex-protected critical section into a Continuation.

### PR DESCRIPTION
**Pull request by ywkaras**
This should hopefully reduce event thread blocking.

This PR is dependent on https://github.com/apache/trafficserver/pull/4848 .

The drawback is that this new version involves three dynamic memory allocations each time the critical section is entered.  So it depends on jemalloc whether there is a net benefit.  Whether jemalloc is good at avoiding the need to take a mutex for allocation, and at keeping the critical section short when taking a mutex is necessary.

If you fetch the branch for this PR and do a diff with 'meld', it shows more clearly what has really been changed.

### CODE REVIEW

**Comment by zwoop** [comment]
I would very much prefer keeping the cppapi out of this plugin. Well, I’m -1 on it, try again.

**Comment by zwoop** [comment]
Also help me understand which critical section is stalling the net thread? I find the idea of three allocations really discouraging on top of the cppapi shenanigans.

**Comment by zwoop** [comment]
Ok, I see what section you are referring to, you are positive this is a bottleneck? You see that in traffic?

**Comment by ywkaras** [comment]
Note that Continuation.h/Continuation.cc is stand-alone from the rest of the cppapi.  So there is little reason to think that the dubiously-documented cppapi performance problems would be an issue with it.

If you looked at the change with a diff utility that was good at detect moved code allowing for white space changes, it would look much smaller.  I don't using try-lock and reentering cont_handle_policy() would be as simple as you're thinking.

I am just trying to explore ways we can align better with TS's event-driven core.  Maybe we need to conclude that it's generally better to create a new thread in some way to avoid blocking a core event-handling thread.

The core doesn't seem to have good facilities to handle prioritizing transactions that need to be low-latency.  Event threads would need priority queues for continuations.  An event thread would need to be able to bump up the priority of another thread that was holding a mutex it needed to take (priority inheritance).

**Comment by mlibbey** [comment]
Walt-- how much time has this cache promote change seen in production? It's a critical plugin for us, so need to ensure it has seen a lot of action before it is merged.

**Comment by ywkaras** [comment]
I don't know if we use this one in production, my changes have not been tested.  It's a WIP at best.

**Comment by mlibbey** [comment]
Hmm. Seems like we should abandon this change until it's seen some serious testing.

**Comment by ywkaras** [comment]
Our efforts to create a suite of automated regression tests should focus first on the features / plugins that are most used.  Do you all have any regression tests for this plugin that you could open source?

**Comment by ywkaras** [comment]
Replaced by https://github.com/apache/trafficserver/pull/5412 .

**Pull request closed without merging**
