### PR TITLE
stop individual threads using signals

### PR DESCRIPTION
**Pull request by duke8253**
Like proposed in the mailing list, this should be used by plugins to create threads that want to be stopped when the traffic server process receives an terminating signal (SIGINT, SIGTERM).

### CODE REVIEW

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
Looks like it is failing the autest you added in the PR.

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
@duke8253 please pull this into our tree and test in prod.

**Comment by duke8253** [comment]
[approve ci]

**Comment by duke8253** [comment]
[approve ci]

**Comment by duke8253** [comment]
Looks like everything is working as intended in prod.

**Comment by bryancall** [comment]
We should use the LifecycleHook instead of this: https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSLifecycleHookAdd.en.html

**Pull request closed without merging**
