### PR TITLE
TS-5076: Test and set the in_enabled_list by atomic function

### PR DESCRIPTION
**Pull request by oknet**
(cherry picked from commit f84b4333d2743a8275f4974e32c733e989968a67)

### CODE REVIEW

**Comment by oknet** [comment]
TS-5076 backport for 7.0.x

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1137/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1242/ for details.

**Comment by zwoop** [comment]
clang-format :).

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1139/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1244/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1246/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1141/ for details.

**Pull request merged**
