### PR TITLE
TextView: First pass on converting StringView to TextView

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This is a replacement for the current `ts::StringView`. Once this is added, all uses of `ts::ConstBuffer` and `ts::StringView` can be replaced by this or `ts::string_view`.

The changes from `ts::StringView` are
* Changed the name to avoid confusion with `ts::string_view`
* Method names changed to be stylistically compatible with `ts::string_view`
* Subclassed from `ts::string_view` for compatibility and conversions.

`ts::TextView` or `ts::string_view`? By default, use `ts::string_view`. Use `ts::TextView` if the view will be manipulated as a piece of text (prime example - token parsing). Conversion from one to the other is extremely fast as it takes only two 64-bit assignments. It's even faster if a `ts::TextView` is passed by reference because it is also a `ts::string_view` with no additional members so the conversion takes zero instructions.

As requested, this PR now removes all use of `StringView` and the class itself.

The tests for `ink_inet.cc` were also moved to the Catch unit test framework because I had to work with them due to the other changes in the PR and it was worth moving them to the new standard.

ForwardedConfig testing was tweaked a bit as well as the old behavior of `StringView` it depended on was, IMHO, broken. `TextView` does the correct thing and that test was adjusted to require that.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
Related to #2564.

**Comment by SolidWallOfCode** [comment]
[approve ci freebsd]

**Comment by SolidWallOfCode** [comment]
[approve ci clang-format]

**Comment by SolidWallOfCode** [comment]
[approve ci linux]

**Comment by bryancall** [comment]
I would like to see StringView also be removed and the usage replaced in this PR.  I hate to see more code added around strings...

**Comment by SolidWallOfCode** [comment]
That's going to make this a rather large PR.

**Comment by SolidWallOfCode** [comment]
[approve ci linux]

**Comment by SolidWallOfCode** [comment]
[approve ci linux]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Pull request merged**
