### PR TITLE
Improve config_describe logs to print a better output format.

### PR DESCRIPTION
**Pull request by brbzull0**
Improve  `CtrlEngine::config_describe` output logs to display a better formatted output.
Previous output:

```
Name: proxy.config.http.per_server.connection.match
Current Value: ip
Default Value: ip
Record Type: standard config
Data Type: STRING
Access Control: default
Update Type: dynamic, no restart
Update Status: 0
Source: built in default
Syntax Check: string matching a regular expression^(?:ip|host|both|none)$
Version: 0
Order: 945
Raw Stat Block: 0
```
With the change:

```
Name            : proxy.config.http.per_server.connection.match
Current Value   : ip
Default Value   : ip
Record Type     : standard config
Data Type       : STRING
Access Control  : default
Update Type     : dynamic, no restart
Update Status   : 0
Source          : built in default
Syntax Check    : string matching a regular expression
Version         : 0
Order           : 528
Raw Stat Block  : 0
```

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by bryancall** [comment]
Or you could have added `<< std::setw(16) << std::left`

**Comment by randall** [comment]
should this go into 9? Is tool output considered a breaking change?

**Comment by bryancall** [comment]
It can go into 9 if we want, 9.0.0 doesn't need to be "compatible"

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
