### PR TITLE
Remove %<pqsn> logging for ATS 8.x

### PR DESCRIPTION
**Pull request by dyrock**
What current `%<pqsn>` logs should be `%<shn>` and there is no value in ATS corresponding to the `%<pqsn>` as described in the [doc](https://docs.trafficserver.apache.org/en/latest/admin-guide/logging/formatting.en.html). 
This PR 1) removed `%<pqsn>` logic (marshal_proxy_req_server_name) and is related to https://github.com/apache/trafficserver/pull/3860
2) Replaced old `traffic_logstats` test files to accommodate this change in logging. (logstats.blog, logstats.json, logstats.summary)
3) Added a file under `src/traffic_logstats/tests/` which contains the list of urls used to generate the new .blog file so it is easier for people to modify/regenerate the .blog later.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci].

**Comment by SolidWallOfCode** [comment]
Need to

* Resolve conflicts.
* Update documentation.

**Comment by dyrock** [comment]
@SolidWallOfCode Done!

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
Re running CI after merging the validation PR for traffic_logstats

**Comment by dyrock** [comment]
@bryancall Done!

**Pull request merged**
