### PR TITLE
Update to the new MicroServer 1.0.6 release

### PR DESCRIPTION
**Pull request by bneradt**
The new MicroServer 1.0.6 release has the following:

1. Fixes a bug in response body generation to POST requests.
2. Implements the handling of non-existent parts of keys in
   transactions.

### CODE REVIEW

**Comment by shukitchan** [comment]
i think autest will fail because of this 

https://github.com/apache/trafficserver/blob/master/tests/gold_tests/pluginTest/compress/compress.gold#L187

The length should be 71 if the microserver is handling the body for post response

**Comment by bneradt** [comment]
> i think autest will fail because of this
> 
> https://github.com/apache/trafficserver/blob/master/tests/gold_tests/pluginTest/compress/compress.gold#L187
> 
> The length should be 71 if the microserver is handling the body for post response

Thanks. Updated to 71.

Currently the tests will fail until we get the CI's version of microserver updated. I'm working with @zwoop to get that done presently.

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
@shukitchan: 

The test failed. Did I update the wrong gold file?

https://ci.trafficserver.apache.org/job/autest-github/14684/console

**Review by shukitchan — APPROVED** [review]

**Review by dragon512 — APPROVED** [review]

**Review by randall — APPROVED** [review]

**Comment by bneradt** [comment]
8.1.x will need this as well, but it has a conflict with Pipfile. I'll do that as a separate PR.

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
