### PR TITLE
Schedule Transform on the same thread as the continuation

### PR DESCRIPTION
**Pull request by sudheerv**
This fixes the below assert in our prod. 

Related PRs
https://github.com/apache/trafficserver/pull/4379
https://github.com/apache/trafficserver/pull/5170

```
(gdb) bt
#0  0x00002ab8490ee207 in raise () from /lib64/libc.so.6
#1  0x00002ab8490ef8f8 in abort () from /lib64/libc.so.6
#2  0x00002ab8467ae35b in ink_abort (message_format=message_format@entry=0x2ab84682b2a7 "%s:%d: failed assertion `%s`") at ink_error.cc:99
#3  0x00002ab8467ab045 in _ink_assert (expression=expression@entry=0x828118 "!\"BUG: It must have acquired the NetHandler's lock before doing anything on keep_alive_queue.\"", file=file@entry=0x827e10 "UnixNetVConnection.cc", line=line@entry=1442) at ink_assert.cc:37
#4  0x00000000007702c9 in UnixNetVConnection::add_to_keep_alive_queue (this=0x2ab89ffaaa80) at UnixNetVConnection.cc:1442
#5  0x0000000000524287 in Http1ClientSession::release (this=0x2ab8590fbb20, trans=0x2ab8590fbe90) at Http1ClientSession.cc:443
#6  0x000000000071d25c in ProxyTransaction::release (this=0x2ab8590fbe90, r=<optimized out>) at ProxyTransaction.cc:66
#7  0x000000000053c9b4 in HttpSM::tunnel_handler_ua (this=0x2ab84f147210, event=103, c=0x2ab84f148248) at HttpSM.cc:3431
#8  0x000000000059dae3 in HttpTunnel::consumer_handler (this=this@entry=0x2ab84f148190, event=event@entry=103, c=c@entry=0x2ab84f148248) at HttpTunnel.cc:1326
#9  0x000000000059e128 in HttpTunnel::finish_all_internal (this=this@entry=0x2ab84f148190, p=p@entry=0x2ab84f1484b8, chain=chain@entry=false) at HttpTunnel.cc:1512
#10 0x000000000053a92a in local_finish_all (p=0x2ab84f1484b8, this=<optimized out>) at HttpTunnel.h:379
#11 HttpSM::tunnel_handler_transform_read (this=<optimized out>, event=104, p=0x2ab84f1484b8) at HttpSM.cc:4005
#12 0x000000000059caf0 in HttpTunnel::producer_handler (this=this@entry=0x2ab84f148190, event=104, p=0x2ab84f1484b8) at HttpTunnel.cc:1182
#13 0x000000000059e3ea in HttpTunnel::main_handler (this=0x2ab84f148190, event=<optimized out>, data=<optimized out>) at HttpTunnel.cc:1607
#14 0x0000000000723b03 in TransformTerminus::handle_event (this=0x2ab84f91a4d8, event=<optimized out>) at Transform.cc:223
#15 0x00000000007bf371 in handleEvent (data=0x2ab8b36fb2a0, event=1, this=0x2ab84f91a4d8) at I_Continuation.h:190
#16 EThread::process_event (this=this@entry=0x2ab84ba20000, e=e@entry=0x2ab8b36fb2a0, calling_code=1) at UnixEThread.cc:127
#17 0x00000000007c0284 in EThread::execute_regular (this=this@entry=0x2ab84ba20000) at UnixEThread.cc:236
#18 0x00000000007c0712 in EThread::execute (this=0x2ab84ba20000) at UnixEThread.cc:327
#19 0x00000000007beab9 in spawn_thread_internal (a=0x2ab84a5658c0) at Thread.cc:92
#20 0x00002ab848404dd5 in start_thread () from /lib64/libpthread.so.0
#21 0x00002ab8491b5ead in clone () from /lib64/libc.so.6
(gdb) 

(gdb) p *nh
$16 = {<Continuation> = {<force_VFPT_to_top> = {_vptr.force_VFPT_to_top = 0x827448 <vtable for NetHandler+16>}, handler = (int (Continuation::*)(Continuation * const, int, void *)) 0x761360 <NetHandler::mainNetEvent(int, Event*)>, mutex = {m_ptr = 0x2ab84ad1f170}, 
    link = {<SLink<Continuation>> = {next = 0x0}, prev = 0x0}, control_flags = {raw_flags = 0}, thread_affinity = 0x0}, <EThread::LoopTailHandler> = {_vptr.LoopTailHandler = 0x827478 <vtable for NetHandler+64>}, thread = 0x2ab84b913000, trigger_event = 0x0, 
  read_ready_list = {<DLL<NetEvent, NetEvent::Link_read_ready_link>> = {head = 0x0}, tail = 0x0}, write_ready_list = {<DLL<NetEvent, NetEvent::Link_write_ready_link>> = {head = 0x0}, tail = 0x0}, open_list = {<DLL<NetEvent, NetEvent::Link_open_link>> = {head = 0x2ab89ffaac30}, 
    tail = 0x2ab88f819e20}, cop_list = {head = 0x2ab852b96c70}, read_enable_list = {al = {head = {s = {pointer = 0x0, version = 0}, data = 0x00000000000000000000000000000000}, name = 0x7fdeb9 "AtomicSLL", offset = 136}}, write_enable_list = {al = {head = {s = {pointer = 0x0, version = 1}, 
        data = 0x00000000000000010000000000000000}, name = 0x7fdeb9 "AtomicSLL", offset = 248}}, keep_alive_queue = {<DLL<NetEvent, NetEvent::Link_keep_alive_queue_link>> = {head = 0x2ab88f824210}, tail = 0x2ab852b8fdc0}, keep_alive_queue_size = 2, 
  active_queue = {<DLL<NetEvent, NetEvent::Link_active_queue_link>> = {head = 0x2ab89ffaac30}, tail = 0x2ab89ffaac30}, active_queue_size = 1, static global_config = {max_connections_in = 100000, max_connections_active_in = 10000, inactive_threshold_in = 0, 
    transaction_no_activity_timeout_in = 0, keep_alive_no_activity_timeout_in = 0, default_inactivity_timeout = 300}, config = {max_connections_in = 100000, max_connections_active_in = 10000, inactive_threshold_in = 0, transaction_no_activity_timeout_in = 0, 
    keep_alive_no_activity_timeout_in = 0, default_inactivity_timeout = 300}, max_connections_per_thread_in = 2777, max_connections_active_per_thread_in = 277, static CONFIG_ITEM_COUNT = 6, static config_value_affects_per_thread_value = {<std::_Base_bitset<1>> = {
      _M_w = 3}, <No data fields>}, static active_thread_types = {<std::_Base_bitset<1>> = {_M_w = 1}, <No data fields>}}
(gdb) p *(ProxyMutex*)0x2ab84ad1f170
$17 = {<RefCountObj> = {<ForceVFPTToTop> = {_vptr.ForceVFPTToTop = 0x7c5748 <vtable for ProxyMutex+16>}, m_refcount = 5}, the_mutex = {__data = {__lock = 1, __count = 0, __owner = 9024, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
    __size = "\001\000\000\000\000\000\000\000@#\000\000\001", '\000' <repeats 26 times>, __align = 1}, thread_holding = 0x2ab84b913000, nthread_holding = 1}

```

### CODE REVIEW

**Comment by sudheerv** [comment]
@dmorilha This may be related to the asserts you ran into and reverted in 7.1.x 

https://github.com/apache/trafficserver/pull/5170

**Comment by vmamidi** [comment]
This is okay as long as the plugin doesn't create any thread. Approving the PR as it handles the scenario when the plugin doesn't create any threads.

**Comment by sudheerv** [comment]
> This is okay as long as the plugin doesn't create any thread. Approving the PR as it handles the scenario when the plugin doesn't create any threads.

Yeah, I tried digging but, couldn't quite see how a transform can be scheduled on a separate thread by a plugin. The interface is purely through the API hooks and with the thread affinity requirements, we have been trying to keep the request on the same thread in all of our plugins in. general. 

Transform alone is an exception and that isn't directly controlled by the Plugin but done within the ATS core (the root cause of this assert/PR). So, I figured if someone has such a use case or mechanism to do that, we can probably revisit then based on how that is being done.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
