### PR TITLE
TS-2978 Reorder member variables in HttpSM State

### PR DESCRIPTION
**Pull request by danobi**
Reduce padding by grouping non four byte aligned variables together.
Packing was done by hand, and pretty much only touched bools and chars. There was no attempt to pack any structs/objects. 
Testing with sizeof()s showed a reduction in the size of HttpTransact::State from 4088B to 4064B.

### CODE REVIEW

**Comment by danobi** [comment]
Further testing with pahole may be done later, when I get a vm setup with a supported OS.

**Comment by jpeach** [comment]
Can you show the pahole(1) results for before and after?

**Comment by danobi** [comment]
pahole results for [unpacked](http://pastebin.com/WwLFSrrG)
pahole results for [packed](http://pastebin.com/Cr6jtZac)

Although it looks like there's another 200B we can squeeze out, I'm not sure if scrambling up all the variable groupings is worth it. 

I'll spend some more time trying to get some free bytes today.

**Comment by danobi** [comment]
Packed a little more. Now down to 4056B. 

pahole results [here](http://pastebin.com/rutZmEN7)

**Pull request closed without merging**
