### PR TITLE
strlen() is defined in strings.h

### PR DESCRIPTION
**Pull request by postwait**

### CODE REVIEW

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/50/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1617/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1512/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/182/ for details.

**Comment by SolidWallOfCode** [comment]
Can you see if #1491 fixes the issue? That's my preferred solution. @zwoop was concerned about just including `strings.h` and preferred `ink_platform.h`.

**Comment by postwait** [comment]
The proposed fix in #1491 fixes the issue as well.

**Pull request closed without merging**
