### PR TITLE
Enhance Connection Collapse in ATS core

### PR DESCRIPTION
**Pull request by sudheerv**
Add an option to support cache open read retry on a write lock
failure. With this option, as long as read-while-writer is set
up following the guidelines in the docs, there should be no need
for any plugins to augment the core. Eventual plan is to deprecate
collapsed_forwarding plugin with this new support.

For more context on this, see
https://cwiki.apache.org/confluence/display/TS/Presentations+-+2019?preview=/112821251/132320653/Collapsed%20Forwarding%20.pdf

### CODE REVIEW

**Comment by scw00** [comment]
link to #6028

**Comment by sudheerv** [comment]
Thanks @scw00 for the thorough review!

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
@sudheerv Should we remove the connection collapsing plugin from v10.0.0 ?

**Comment by zwoop** [comment]
Also, if we want this for an 8.x release, we'll need a PR for it.

**Comment by sudheerv** [comment]
> @sudheerv Should we remove the connection collapsing plugin from v10.0.0 ?

Yeah, Agree. Will send out an email to dev@ first though and cleanup the old configs and plugin after that.

**Comment by sudheerv** [comment]
> Also, if we want this for an 8.x release, we'll need a PR for it.

Sure, will create a PR.

**Pull request merged**
