### PR TITLE
traffic_ctl: Refactor and convert traffic_ctl to use ArgParser

### PR DESCRIPTION
**Pull request by chitianhao**
This is a refactoring of traffic_ctl to use the new command line parsing library ArgParser. There are almost 300 lines of codes less than previous and all the commands, subcommands and option handling are unified in the main function.

An engine, called `CtrlEngine` used for the parser and all methods, is defined in `traffic_ctl.h`. This engine makes the traffic_ctl more stable.

Some `printf`'s are converted to `cout`.

### CODE REVIEW

**Comment by chitianhao** [comment]
Depends on https://github.com/apache/trafficserver/pull/4585 . I need to update the runroot_handler part.

**Comment by chitianhao** [comment]
I'll also try to update the `printf`s to use BufferWriter.

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
@chitianhao It looks lie this PR has broken 'traffic_ctl host'.  The reason string in status_up() and status_down() always comes back empty from arguments.get("reason).value();  So, when you use

`traffic_ctl host down --reason active p1.foo.com`

the manual status tag is always updated instead of the active tag as reason is empty so it defaults to manual.

**Pull request merged**
