### PR TITLE
Cleanup server_entry before do dns lookup

### PR DESCRIPTION
**Pull request by oknet**
ATS has server connection retry mechanism. It tries to connect
server ip first then other ip by DNS round robin.

Currently, ATS will do cleanup server_entry before retry to connect
server ip. But it does not cleanup server_entry before do dns lookup.

### CODE REVIEW

**Comment by oknet** [comment]
@vmamidi please try this for issue #1930.

**Comment by vmamidi** [comment]
I don't think this is related to just DNS. 

look at this stack trace. 

abort
ink_abort(char const*, ...)
HttpSM::state_http_server_open(int, void*)
HttpSM::main_handler(int, void*)
write_to_net_io(NetHandler*, UnixNetVConnection*, EThread*)
NetHandler::mainNetEvent(int, Event*)
EThread::execute()

and corresponding log message.
traffic_server[29074]: {0x2aaab730c700} ERROR: [HttpSM::state_http_server_open] Unknown event: 103

**Comment by zwoop** [comment]
Testing with this PR on docs/ci.trafficserver right now.

**Comment by oknet** [comment]
@zwoop This PR is a patch for the 1st scenario (HttpSM::history) in issue #1930.

The 2nd HttpSM::history in issue #1930 is not covered by this patch. @scw00 is working on it.

+1 for 7.1.x

**Comment by oknet** [comment]
@vmamidi I think the PR #1995 could be a solution for 2nd HttpSM::history in issue #1930. Can you have a try ?

Currently, the request transform can not work together with server connection retry mechanism. Because ATS can not replay the post content.

**Comment by oknet** [comment]
@zwoop @vmamidi According to the issue #1994 & #1930 , the best suggestion is to disable the retry mechanism for POST & PUT request.

**Comment by zwoop** [comment]
I merged this, and cherry-picked to 7.1.0.

**Pull request merged**
