### PR TITLE
Fix a crash on connection migration to the advertised preferred address

### LINKED ISSUE #7045: UnixUDPConnection crashes on sending packet
Seems like this is not new but rare.

```
Fatal: UnixUDPConnection.cc:127: failed assertion `mutex == c->mutex`
```

```
/opt/ats/lib/libtscore.so.10(_Z20signal_crash_handleriP9siginfo_tPv+0x18)[0x7f2facbd7d18]
/opt/ats/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x168)[0x78a5b0]
/lib64/libpthread.so.0(+0x12080)[0x7f2fab272080]
/lib64/libc.so.6(gsignal+0x10b)[0x7f2faa394eab]
/lib64/libc.so.6(abort+0x123)[0x7f2faa37f5b9]
/opt/ats/lib/libtscore.so.10(_Z11ink_warningPKcz+0x0)[0x7f2facb7c396]
/opt/ats/lib/libtscore.so.10(+0x202fc3)[0x7f2facb73fc3]
/opt/ats/bin/traffic_server(_ZN13UDPConnection4sendEP12ContinuationP9UDPPacket+0x93)[0xe9c81b]
/opt/ats/bin/traffic_server(_ZN17QUICPacketHandler12_send_packetEP13UDPConnectionR10IpEndpoint3PtrI13IOBufferBlockE+0x567)[0xf225af]
/opt/ats/bin/traffic_server(_ZN17QUICPacketHandler11send_packetEP18QUICNetVConnection3PtrI13IOBufferBlockE+0xe6)[0xf268b0]
/opt/ats/bin/traffic_server(_ZN18QUICNetVConnection25_state_common_send_packetEv+0x17c3)[0xec4f91]
/opt/ats/bin/traffic_server(_ZN18QUICNetVConnection28state_connection_establishedEiP5Event+0x3a9)[0xebb72b]
/opt/ats/bin/traffic_server(_ZN12Continuation11handleEventEiPv+0x19e)[0x796936]
/opt/ats/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x331)[0xf6d633]
/opt/ats/bin/traffic_server(_ZN7EThread15execute_regularEv+0x720)[0xf6e476]
/opt/ats/bin/traffic_server(_ZN7EThread7executeEv+0x2e9)[0xf6f0cb]
/opt/ats/bin/traffic_server[0xf6b9a0]
/lib64/libpthread.so.0(+0x7594)[0x7f2fab267594]
/lib64/libc.so.6(clone+0x3f)[0x7f2faa457f4f]
```

### PR DESCRIPTION
**Pull request by maskit**
This closes #7045

### CODE REVIEW

**Comment by maskit** [comment]
This fixes the last known crash on 9.0.x at the moment.

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
