### PR TITLE
Fix traffic_wccp makefile for SNI / Lua based config.

### PR DESCRIPTION
**Pull request by persiaAziz**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by persiaAziz** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
I don't think this change will work when there is Lua installed on the system.  Please take a look at other Makefile.am that add the Lua lib for linking.

**Comment by bryancall** [comment]
It is also still breaking the build on OSX:
```
/bin/sh ../../libtool  --tag=CXX   --mode=link ccache c++ -std=c++11 -g -pipe -Wall -Wno-deprecated-declarations -Qunused-arguments -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -O3 -fno-strict-aliasing -Werror -Wno-invalid-offsetof -mcx16  -no-undefined -version-info 8:0:0 -L/usr/local/Cellar/openssl/1.0.2l/lib -L/usr/local/lib -L/usr/local/Cellar/pcre/8.41/lib -o libtsconfig.la -rpath /usr/local/lib Errata.lo TsBuilder.lo TsConfigLua.lo TsErrataUtil.lo TsValue.lo  TsConfigGrammar.lo TsConfigSyntax.lo
libtool: link: c++ -dynamiclib  -o .libs/libtsconfig.8.dylib  .libs/Errata.o .libs/TsBuilder.o .libs/TsConfigLua.o .libs/TsErrataUtil.o .libs/TsValue.o .libs/TsConfigGrammar.o .libs/TsConfigSyntax.o   -L/usr/local/Cellar/openssl/1.0.2l/lib -L/usr/local/lib -L/usr/local/Cellar/pcre/8.41/lib  -g -O3 -mcx16   -install_name  /usr/local/lib/libtsconfig.8.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_lua_toboolean", referenced from:
      TsConfigBool::loader(lua_State*) in TsConfigLua.o
  "_lua_tolstring", referenced from:
      TsConfigString::loader(lua_State*) in TsConfigLua.o
  "_lua_tonumber", referenced from:
      TsConfigInt::loader(lua_State*) in TsConfigLua.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Pull request merged**
