### PR TITLE
Fix Findunwind.cmake on RHEL

### PR DESCRIPTION
**Pull request by phongn**
Fix change in #10811 intended for Ubuntu that caused build issues on RHEL.

### CODE REVIEW

**Comment by phongn** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by brbzull0** [comment]
@phongn tested this locallty in ubuntu 20.04. Works great! Thanks.

**Review by JosiahWI — COMMENTED** [review]
Thank you, looks great to me! Not marking an explicit approval since I count as a Yahoo person.

**Review by cmcfarlen — APPROVED** [review]
Thanks!

**Pull request merged**
