### PR TITLE
TS-993: OpenBSD sbindir should be ${exec_prefix}/sbin

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1407/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1300/ for details.

**Comment by jablko** [comment]
Thanks @zwoop! Merged.

**Comment by zwoop** [comment]
You want this for 7.1.x?

**Comment by zwoop** [comment]
Ah wth, it seems safe, cherry-picking.

**Pull request merged**
