### PR TITLE
TS-4772: Add delay and max-age control to the generator plugin.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/584/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/480/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/586/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/481/ for details.

**Comment by zwoop** [comment]
I guess I don't have a strong opinion, but it seems unfortunate to me to introduce these new options as headers, rather than URI components. The original plugin for lighthttpd did everything in the URI paths, no? Keeping it this way seems more consistent, and easier to use for e.g. setting up various performance and load patters where you want to mix various options for various requests.

In a sense, it'd cool to mimic some of the behavior of httpbin.

**Comment by bryancall** [comment]
Instead of headers I would like to seem them in the URL.  Possibly as query parameters.

**Comment by jpeach** [comment]
It is done in headers so that you can trivially hit the same URL with different attributes. For example, hit URL1 with a short MaxAge to populate the cache. Then hit URL1 again with a long delay to lock the cache entry, then hit URL1. This is much harder to do with query parameters, though I have no objection to adding them as an additional mechanism.

**Comment by jpeach** [comment]
Are we good with headers (at least for now)?

**Comment by zwoop** [comment]
I dislike the inconsistency, but your explanation / use case makes a lot of sense. And if we agree that this makes things better, and not worse, do it. Maybe file a Jira to have a future addition to support both headers and URIs for all parameters?

**Pull request merged**
