### PR TITLE
Stabilize autest for traffic_dump

### PR DESCRIPTION
**Pull request by maskit**
Messages sent by traffic_ctl are processed periodically and may not be applied immediately.

### CODE REVIEW

**Review by bneradt — COMMENTED** [review]
Make sense, but would one second be enough?

**Comment by maskit** [comment]
I tried one sec too but it wasn't enough, it was better than no pause though.

**Comment by bneradt** [comment]
> I tried one sec too but it wasn't enough, it was better than no pause though.

OK, thanks for trying. Definitely keeping it stable with 2 seconds is better than it failing some. Thanks for making it more reliable.

**Review by bneradt — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
