### PR TITLE
Cleanup: remove ts::Buffer from LogField.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Remove and replace `ts::Buffer`.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
Fail:
AuTest 2 - tls_0rtt_server

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Review by cmcfarlen — APPROVED** [review]

**Pull request merged**
