### PR TITLE
h2spec: The endpoint MUST ignore any flags that is undefined.

### PR DESCRIPTION
**Pull request by zizhong**
(cherry picked from commit 0d39b4a2c07ae81954087acefeb029222a6381f2)

Conflicts:
	proxy/http2/HTTP2.cc

### CODE REVIEW

**Comment by zizhong** [comment]
This is the backport of https://github.com/apache/trafficserver/pull/1747. @zwoop

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
@zizhong I think you need to rebase to address that clang-analyzer failure.

@zwoop should this still be an issue?

**Comment by zizhong** [comment]
@PSUdaemon rebased. Can you try it again?

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
Trying again, the CA and cutest failures are probably as expected (sigh), but the RAT failure was due to an issue on the CI. [approve ci]

**Pull request merged**
