### PR TITLE
TS-5035: plugin 'background_fetch' can be built normally.

### PR DESCRIPTION
**Pull request by yunwen0111**

### CODE REVIEW

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1169/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1062/ for details.

**Comment by jpeach** [comment]
Wow, that is embarrassing. Thanks @yunwen0111!

**Pull request merged**
