### PR TITLE
Issue #1360: REGRESSION_TEST(SDK_API_OVERRIDABLE_CONFIGS) crash sometimes

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by zwoop** [comment]
7.1.0 candidate?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1373/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1266/ for details.

**Comment by shinrich** [comment]
Probably.  We will be pulling this back into our 7.1

**Pull request merged**
