### PR TITLE
TS-3780: Custom log add incoming interface ip

### PR DESCRIPTION
**Pull request by zizhong**
Extending the custom log fields to support incoming server (interface) ip.

### CODE REVIEW

**Comment by bgaff** [comment]
I worked with @zizhong on this pull request and it looks good to me.

**Comment by jpeach** [comment]
Looks quite reasonable. I think we can improve the commit messages though. [These](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) guidelines are good  advice.

**Comment by ericcarlschwartz** [comment]
This looks like it's solving/a duplicate of https://issues.apache.org/jira/browse/TS-2152

The code looks good to me too. If you're renaming commits per @jpeach's comments might want to reflect this & we can close out both issues.

**Comment by bgaff** [comment]
Hi @ericcarlschwartz , if you're cool with he proposed patch I'll land this one and we can close out TS-2152 as a dupe.

**Comment by zwoop** [comment]
Yeah, close TS-2152 as a dupe of TS-3780, since there's so much work done on this PR already. In general, please file Jira's before work / pull requests are done, such that we avoid (minimize) risk of duplicated efforts / work.

**Comment by ericcarlschwartz** [comment]
Sounds good to me just wanted to make sure they both get closed out!

**Pull request merged**
