### PR TITLE
libsowc - remove legacy Errata.

### PR DESCRIPTION
**Pull request by brbzull0**
This is a continuation of the work started by Alan (https://github.com/apache/trafficserver/pull/10112) +
-  Update for the JSONRPC logic which wasn't complete on his original PR due to changes needed in the libswoc which are now completed.
- Make sure all autests/cpptests are green.

co-author: @SolidWallOfCode

### CODE REVIEW

**Comment by brbzull0** [comment]
@cmcfarlen ping!

**Review by cmcfarlen — APPROVED** [review]
I guess we don't need the tests in test_Errata.cc anymore as these are covered by swoc?

**Comment by brbzull0** [comment]
> I guess we don't need the tests in test_Errata.cc anymore as these are covered by swoc?

Yup.
Thanks Chris

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
