### PR TITLE
TS-4650: cachekey: not thread safe

### PR DESCRIPTION
**Pull request by ftarnell**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/312/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/418/ for details.

**Comment by gtenev** [comment]
@ftarnell looks good, thanks for fixing!
@zwoop it will be great if we can back port to 6.2.1

**Comment by zwoop** [comment]
Thanks @gtenev. @ftarnell can you fix the clang format error (see the linux build above), and then we can land this.

Thanks!

**Comment by ftarnell** [comment]
clang-format should be fixed now.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/469/ for details.

**Pull request merged**
