### PR TITLE
TS-4959: Remove remnants of old UA configurations and handling

### PR DESCRIPTION
**Pull request by zwoop**
I made this as two commits:

1) Remove some definitely strange code around MSIE.

2) Remove all the code around the accept_encoding_filter_enabled.

For #2, this configuration doesn't actually exist in RecordsConfig.cc, and it's also missing all possible ways of configuring the regular expressions that it needs. So I figured, we can just nuke it :).

### CODE REVIEW

**Comment by bryancall** [comment]
👍  - Looks good

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/985/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/877/ for details.

**Comment by zwoop** [comment]
Rebuilding again, because I think the trees on the buildbots was busted [approve ci].

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/988/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/880/ for details.

**Pull request merged**
