### PR TITLE
Move ts/Vec to ts/Map

### PR DESCRIPTION
**Pull request by webdriverrr**
In regards of #2680 

ts::Vec now is a part of ts::Map source and used internally within it.

test_Vec remained for covering ts::Vec with needed tests.

NO more include of "ts/Vec.h".

BUT with including "ts/Map.h" anyone can get access to the ts::Vec implementation but this is rather intermediate step more than final solution.

Specific design of ts::Map class enables usage of ts::Vec heavily within it.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by zwoop** [comment]
Yeh, not sure I understand this, if we're replacing Vec with std::vector, why do we need to move all this code from Vec into the libts Map?

**Comment by webdriverrr** [comment]
@bryancall ts::Vec used as vector container not only within ts::Map but appears as type of argument to some methods as well. Thus eliminating ts::Vec completely w/o some re-work of ts::Map IMHO is not possible. I will look at the code one more time precisely and study all the cases where ts::Map is used.

@zwoop the idea behind moving all the ts::Vec code to ts::Map is to hide its implementation so no one can use it in future versus the decision of using only std::vector. But it still possible to include _ts/Map.h_ and get ts::Vec access due to what I explained above in this message addressed to Bryan Call.

**Comment by webdriverrr** [comment]
@bryancall @zwoop I've just finished review of ts::Map and rest of related custom data structures containers implemented in libts and found that simply replacing ts::Vec with std::vector without ***heavy*** refactoring is impossible due to:

- ts::Vec is used as basic class for: ts::Map, ts::HashSet;
- ts::Vec is used as a type for its members referencing within ts::Map;
- ts::Vec is used as a type for methods arguments of ts::Map, ts::HashMap, ts::ChainHash, ts::ChainHashMap;
- the rest of custom data structure containers within libts are using ts::Map as well.

All these given above brings some difficulties into eliminating ts::Vec completely (at least from the public access via Map.h).

**Comment by bryancall** [comment]
I am still -1 on this and I don't see any benefit unless you are going to hide Vec.  It is just moving the code around.

**Comment by maskit** [comment]
@bryancall How can we hide Vec completely? We can still access Vec with any of these.

- Preprocessor magic (https://github.com/apache/trafficserver/blob/7.1.1/iocore/eventsystem/I_Thread.h#L62-L64)
- Move Vec into "internal" namespace or directory
- Make Vec abstract class

 IMO, removing "Vec.h" file would deter using Vec alone. Adding comments (like "This is internal use only") would make it clearer.

**Comment by zwoop** [comment]
I don't know that hiding the ts::Vec has a value. What we should do is to -1 (request changes) on any PR that is using the Vec object rather than std::vector. Then the real fix here is to eliminate Vec entirely, replacing it consistently with std::vector.

**Comment by webdriverrr** [comment]
@zwoop makes sense, but as of now ts::Map heavily uses ts::Vec so entire termination of ts::Vec w/o refactoring ts::Map is possible - I am working on bringing more STL containers into ATS code instead of custom ones that present back from old days.
Moreover refactoring of ts::Map as of ts::Vec termination requires creating extra logic - they both are too much coupled.

**Comment by webdriverrr** [comment]
@maskit @zwoop @bryancall I am standing for removing all custom semi-like containers in the end and clear the way for the STL containers that bring more flexibility.

**Comment by bryancall** [comment]
@webdriverrr 
The only approved STL container at the moment is std::vector.  Every proposed container that we would like to use needs to be evaluated based on performance.

**Comment by webdriverrr** [comment]
@bryancall that is very interesting - I've made a lot of changes in regards of changing ts::HashMap to std::unordered_map, better to stash them before time I would spend increase dramatically.

**Comment by webdriverrr** [comment]
Switching back to usage of std::vector - so what is the better approach of hiding it and never let it use by anyone except std::vector?

**Comment by maskit** [comment]
Are we going to remove the logic (currently named Vec) or a homemade vector type?

**Comment by webdriverrr** [comment]
@maskit removing logic w/o refactoring related stuff (like ts::Map) is hard, removing homemade vector type is also will get us into refactoring - ts::Vec now used as input argument type for some ts::Map methods.

**Comment by webdriverrr** [comment]
DO NOT TRIGGER CI JOBS FOR THIS COMMIT! THIS IS ONLY FOR SAVING INTERMEDIATE STATE.

**Comment by maskit** [comment]
@webdriverrr Yeh, I understand that. I was asking others that whether the code for Vec need to be removed.

Personally, I don’t think we need to remove the entire code for Vec because I see Vec as just a base class for Map. So, I’m fine with just moving the code. It would be great if we could hide it completely so that nobody can use it accidentally.

On the other hand, some people here want complete removement of code for Vec. This is ideal but takes time. And we are finding thread-safe containers recently. It may bring an acceptable map implementation. This is another reason I don’t think we need to remove Vec now.

**Comment by SolidWallOfCode** [comment]
Addressing @bryancall's complaint, while I agree this isn't a complete solution, let's not let the perfect be the enemy of the good. Moving `Vec` to a hidden place is, IMHO, clearly an improvement over having it as a top level include.

**Comment by zwoop** [comment]
Ok, I'm ok with this too, thanks for the explanations. It might be worthwhile explaining in the commit message why there's value here in moving Vec into the Map implementation (because of the tight dependency).

[approve ci]

**Comment by zwoop** [comment]
Merge conflicts now, and need to fix clang-format. Then I'll +1 this.

**Comment by webdriverrr** [comment]
Ahhh I shouldn't been deleted this branch

**Comment by webdriverrr** [comment]
And it seems I cannot re-open it - **Reopen and comment** button inactive.

**Comment by maskit** [comment]
@webdriverrr Me neither. Please open a new PR.

**Pull request closed without merging**
