### PR TITLE
Adds voluspa - a configuration generator

### PR DESCRIPTION
**Pull request by randall**
This generates configuration files for ATS from simpler high-level YAML specifications.

It is a stand-alone command line utility and package implemented in Go.

### CODE REVIEW

**Comment by zwoop** [comment]
Also, the plan was to code-drop this into a separate branch in ATS for now, not master. Sorry I missed that.

**Comment by zwoop** [comment]
@SolidWallOfCode See other comment, but agreed. For now, we should do this in a separate branch, long term, it will likely move to the ATC project.

**Comment by zwoop** [comment]
[approve ci RAT]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by randall** [comment]
Dusting off this changes...

> We need to
> 
> 1. Fix the RAT reports (IMO). Ideally, avoid adding to .rat-excludes unless necessary.

Tried. The .confs, gometalint.conf, and .config_default are all config files (son or YAML).
gojsonschema is a vendor-ed library. I could move to gomod which would eliminate the copy of gojsonschema, but would require relatively new versions of go for people to use.

```
# tools/voluspa related
^.gometalint.conf$
.*\.conf$
.*config_default$
gojsonschema(?:                      Apache 2.0. Properly documented in LICENSE-APACHE-2.0.txt ){0}
```
> 2. We should land this in a branch named Voluspa, not master. The plan / goal is to move this over to ATC if they see this useful to them.

The voluspa branch is the target here.

**Comment by randall** [comment]
@bryancall Can you take a look at this? I think I've addressed everything @zwoop requested.

**Comment by bryancall** [comment]
It looks like it has the clang-tidy changes I did on master and then @zwoop reverted.  We should either update the PR from the current master and not have the clang-tidy changes in this PR or wait until I do clang-tidy again on master before merging this.

**Pull request closed without merging**
