### PR TITLE
[TS-4437] Add new limit rate example plugin

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by zwoop** [comment]
Taking a quick look, two comments:

1) You must add the AL2 license blurb to all new files.

2) As is, this does belong as an example. I'm wondering / hoping that we'd eventually turn this into a real plugin?

**Comment by yatsukhnenko** [comment]
1) done
2) I used vconn and timer to control a portioning of data. What do you think about that? Maybe it should be done on the "lower" level or maybe we should use different algorithm?
What else we need to turn this in real plugin? :)

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
Also, would you mind adding the Jira number to the Subject line to this commit / PR? It helps us associate the PR with the correct Jira.

**Comment by yatsukhnenko** [comment]
There is no Jira for this PR and I can't create new issue :(

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
Not sure why you couldn't create the Jira, but I made one for you: https://issues.apache.org/jira/browse/TS-4437. All you should have to do is to register with the Jira instance, and anyone can create Jira's against ATS.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Pull request closed without merging**
