### PR TITLE
TS-4678 Promotes a few plugins to stable

### PR DESCRIPTION
**Pull request by zwoop**
The following are moved:

  authproxy
  background_fetch
  esi
  generator
  regex_revalidate
  s3_auth
  xdebug

### CODE REVIEW

**Comment by zwoop** [comment]
@mlibbey  Please review.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/472/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/369/ for details.

**Comment by mlibbey** [comment]
Think we need trafficserver/doc/admin-guide/plugins/index.en.rst changes too?

**Comment by zwoop** [comment]
@mlibbey  Yes. Updated, see second commit. (I will squash the commits before committing)

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/473/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/370/ for details.

**Pull request merged**
