### PR TITLE
Add RPC documentation

### PR DESCRIPTION
**Pull request by xf6wang**
Documents local and remote RPC including:
- Serialization Mechanism 
- API
- Message passing examples

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by SolidWallOfCode** [comment]
[approve ci docs]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci docs]

**Pull request merged**
