### PR TITLE
Only close on successful open

### LINKED ISSUE #10593: CID 1522781: Argument cannot be negative
Looks like the last fix made new ones.

ssl_session_reuse/src/config.cc
```
CID 1522782: Argument cannot be negative (NEGATIVE_RETURNS) [[select issue](https://scan6.scan.coverity.com/defectInstanceId=34843144&fileInstanceId=166426161&mergedDefectId=1522782)]
   	
CID 1522781 (#1 of 1): Argument cannot be negative (NEGATIVE_RETURNS)
4. negative_returns: fd is passed to a parameter that cannot be negative.
 89  close(fd);
```

### PR DESCRIPTION
**Pull request by duke8253**
This resolves #10593

### CODE REVIEW

**Comment by duke8253** [comment]
[approve ci clang-format]

**Comment by duke8253** [comment]
[approve ci]

**Comment by duke8253** [comment]
[approve ci]

**Comment by duke8253** [comment]
[approve ci clang-format]

**Comment by duke8253** [comment]
[approve ci]

**Review by maskit — APPROVED** [review]

**Pull request merged**
