### PR TITLE
TS-4719: Make AIO threads interleave memory across NUMA nodes.

### PR DESCRIPTION
**Pull request by PSUdaemon**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/539/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/436/ for details.

**Comment by bryancall** [comment]
👍 - Looks good

**Comment by gtenev** [comment]
@PSUdaemon, tested the change and it seems it worked.

WITHOUT the fix:

```
Per-node process memory usage (in MBs) for PID 33486 ([ET_NET 0])
                           Node 0          Node 1           Total
                  --------------- --------------- ---------------
Huge                         0.00            0.00            0.00
Heap                         0.00            0.00            0.00
Stack                        1.10            1.93            3.04
Private                 188774.40        58365.61       247140.01
----------------  --------------- --------------- ---------------
Total                   188775.50        58367.55       247143.05
```

WITH the fix:

```
Per-node process memory usage (in MBs) for PID 19187 ([ET_NET 0])
                           Node 0          Node 1           Total
                  --------------- --------------- ---------------
Huge                         0.00            0.00            0.00
Heap                         0.00            0.00            0.00
Stack                        1.05            0.58            1.63
Private                 117512.30       118122.88       235635.18
----------------  --------------- --------------- ---------------
Total                   117513.35       118123.46       235636.80
```

**Pull request merged**
