### PR TITLE
TS-4747: make marking parent proxies down in hostdb configurable.

### PR DESCRIPTION
**Pull request by jrushford**
Back port of https://github.com/apache/trafficserver/pull/1464 to 6.2.2

(cherry picked from commit 2752c758fd480c1becd814f40ff53896d44b315b)

Conflicts:
	doc/admin-guide/files/records.config.en.rst
	doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
	lib/ts/apidefs.h.in
	mgmt/RecordsConfig.cc
	plugins/experimental/ts_lua/ts_lua_http_config.c
	proxy/InkAPI.cc
	proxy/InkAPITest.cc
	proxy/http/HttpConfig.cc
	proxy/http/HttpConfig.h

### CODE REVIEW

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/72/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1535/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1639/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/204/ for details.

**Comment by zwoop** [comment]
Set a milestone please.

**Comment by PSUdaemon** [comment]
Can you rebase this so we can get the Intel build clear? Thanks.

**Comment by jrushford** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1572/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1676/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/108/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/109/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1573/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1677/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/240/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/241/ for details.

**Pull request merged**
