### PR TITLE
TS-4745: Initializes pRecord.failCount in ParentRecord::ProcessParents.

### PR DESCRIPTION
**Pull request by jrushford**
New pull request on behalf of keith2008 to insure that pRecord.failCount is properly initialized.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/611/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/507/ for details.

**Comment by zwoop** [comment]
Fwiw, we should make sure to review and mark a PR for CI build before merging.

**Comment by jrushford** [comment]
Ok, got it.


Thanks
--
John J. Rushford

**Pull request merged**
