### PR TITLE
Fix simple remapping in regex_remap plugin.

### PR DESCRIPTION
**Pull request by ywkaras**
Adds a test run to successfully remap a URL with host example.three, resulting in a 200 response.
It includes a bug fix for regex_remap.cc, needed so the test run will succeed.  The bug was probably
introduced by commit fee5ba1.

### CODE REVIEW

**Comment by bryancall** [comment]
@ywkaras Please reference the PR that broke this and write up a description.

**Comment by ywkaras** [comment]
Verizon Media production has tested and approved this change.

**Review by randall — APPROVED** [review]

**Comment by randall** [comment]
Should this also go into 9.0.x since the other 2 related PRs (#7347 and #7437) went there?

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
Cherry-picked to v9.1.x branch.

**Pull request merged**
