### PR TITLE
TS-3826: Traffic Server adds body "No Content" to 204 response

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/590/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/486/ for details.

**Comment by maskit** [comment]
👍

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
