### PR TITLE
Fix clang build issue for libswoc.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
* Fix a build issue for clang.
* Comment and code sleanup in IP support.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci centos]

**Comment by SolidWallOfCode** [comment]
[approve ci debian]

**Comment by SolidWallOfCode** [comment]
[approve ci fedora]

**Comment by SolidWallOfCode** [comment]
[approve ci ubuntu]

**Review by bneradt — APPROVED** [review]

**Review by bryancall — CHANGES_REQUESTED** [review]
I am getting these errors when compiling on Fedora 35 with clang 13:
```
In file included from ../../../lib/swoc/src/bw_ip_format.cc:8:
/home/bcall/dev/apache/trafficserver/build-Linux_clang/../lib/swoc/include/swoc/swoc_ip.h:579:3: error: definition of implicit copy assignment operator for 'IPAddr' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  IPAddr(self_type const &that) = default; ///< Copy constructor.
  ^
/home/bcall/dev/apache/trafficserver/build-Linux_clang/../lib/swoc/include/swoc/swoc_ip.h:2887:9: note: in implicit copy assignment operator for 'swoc::IPAddr' first required here
  _addr = addr & mask;
        ^
1 error generated.
```

**Comment by SolidWallOfCode** [comment]
CentOS failure
```
Fatal: traffic_server/InkAPITest.cc:910: failed assertion `!"Synserver must be able to bind to a port, check system netstat"
```

**Comment by SolidWallOfCode** [comment]
[approve ci centos]

**Comment by SolidWallOfCode** [comment]
Fedora failure
```
Fatal: traffic_server/InkAPITest.cc:910: failed assertion `!"Synserver must be able to bind to a port, check system netstat"
```

**Comment by SolidWallOfCode** [comment]
[approve ci fedora]

**Comment by SolidWallOfCode** [comment]
Ubuntu failure
```
Fatal: ../../src/traffic_server/InkAPITest.cc:910: failed assertion `!"Synserver must be able to bind to a port, check system netstat"
```

**Comment by SolidWallOfCode** [comment]
[approve ci ubuntu]

**Comment by SolidWallOfCode** [comment]
Ubuntu failure
```
Fatal: ../../src/traffic_server/InkAPITest.cc:910: failed assertion `!"Synserver must be able to bind to a port, check system netstat"
```

**Comment by SolidWallOfCode** [comment]
[ci approve ubuntu]

**Comment by SolidWallOfCode** [comment]
[ci approve Ubuntu]

**Comment by SolidWallOfCode** [comment]
[approve ci ubuntu]

**Comment by cmcfarlen** [comment]
Still seeing compile errors with clang-13:

```
  CXX      src/bw_ip_format.lo
In file included from src/bw_ip_format.cc:8:
/work/lib/swoc/include/swoc/swoc_ip.h:244:50: error: type 'const swoc::IP4Addr::bytes' (aka 'const array<unsigned char, 4>') does not provide a subscript operator
    return reinterpret_cast<bytes const &>(_addr)[idx];
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/work/lib/swoc/include/swoc/swoc_ip.h:546:21: error: implicit instantiation of undefined template 'std::array<unsigned long, 2>'
    word_store_type _store = {0}; ///< 0 is MSW, 1 is LSW.
 ```

**Review by bneradt — APPROVED** [review]

**Comment by ezelkow1** [comment]
[approve ci rocky]

**Pull request merged**
