### PR TITLE
TS-5082: define IOBufferReader::is_read_avail_more_than with TS_INLINE keyword

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1254/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1149/ for details.

**Comment by zwoop** [comment]
Hmmm, it seems we are incredibly inconsistent here. Why singling out this one place for this change? Do we really need TS_INLINE in general? I notice we turn off inlining via #define in some places, but then I'd argue that we should not use it at all in those place, no?

I think what I'm saying is

1) Why not remove TS_INLINE ? I.e. just use inline.

2) In those places where TS_INLINE is used, but #define'd to nothing, we just remove TS_INLINE.

3) Maybe also make an effort to reduce the use of inline in general, and let the compiler deal with it.

I'm fine landing this as-is in this patch, but maybe file another Jira for a general cleanup here?

**Comment by oknet** [comment]
From my understand:

- The TS_INLINE defined as inline in lib/ts/ink_apidefs.h only for libts, for libts.so these functions declared by TS_INLINE is inline function.
- And TS_INLINE defined as empty in iocore/\*/Inline.cc, for a sub module static libs (\*.a) these functions declared by TS_INLINE is NOT inline function.

I don't know the reasons about the TS_INLINE macro, this case only fix the compile error.

**Comment by oknet** [comment]
A function of Event System and it is defined with TS_INLINE, e.g. bool is_read_avail_more_than()

- It is compile into net/Inline.o and it is not inline function if it is called from Net Sub-system.
- It is compile into eventsystem/libinkevent.a and it is inline function if it is called from Event System (internal calls).

@zwoop

**Comment by oknet** [comment]
Do I have to backport it to 6.2.x and 7.0.x ? @zwoop

**Pull request merged**
