### PR TITLE
Logging cache code map size fix

### PR DESCRIPTION
**Pull request by gtenev**
The size of the cache code map does not correspond to the number of cache result code values.
Discrepancy introduced with commit eadc9cfa4020799859c4c65be6608990b6f0fe80

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1640/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/73/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1536/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/205/ for details.

**Comment by jpeach** [comment]
Can you look into fixing the APIs so this can't happen again?

**Comment by zwoop** [comment]
We should file an Issue on that improvement.

**Comment by gtenev** [comment]
@jpeach: sounds like right thing to do, needed a quick fix, will find some time to make the API less error-prone. 
@zwoop: sir, yes, sir!

**Pull request merged**
