### PR TITLE
TS-3978: Allow empty document caching to follow normal logic

### PR DESCRIPTION
**Pull request by ftarnell**

### CODE REVIEW

**Comment by sudheerv** [comment]
Hmm..the requirement in the jira certainly seems reasonable, but, the current state of this is mainly to ensure ATS is not caching broken responses (connection failure in the middle of download). 

Allowing to cache the empty docs only when Content-Length=0 indirectly ensures that the response was not broken. So, the patch must somehow ensure that the response is not broken, otherwise, there's a danger of caching invalid responses.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
I'm not sure that we're comfortable with this change, since it's been known to cause problems with empty docs in other areas (e.g. clustering). We'll have to take a close look at this, and decide if we should get this in for 7.0.0.

Also, the branch has now diverged, can you please rebase against current master?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
.

**Comment by zwoop** [comment]
I'm going to close this for now, please open a new PR after we discuss this more?

**Pull request closed without merging**
