### PR TITLE
fix rpath flags when multiple "--with-*" arguments are given.

### PR DESCRIPTION
**Pull request by jaaju**
@bgaff 
  Using TS_ADDTO to add the custom locations of libraries results in incorrect "-rpath" directive to the linker. This is because TS_ADDTO creates a unique list of tokens that it adds to its target. E.g.,

    ./configure --with-openssl=/usr/local/openssl --with-zlib=/usr/local/zlib

the above should result in

    LIBTOOL_LINK_FLAGS: -rpath /usr/local/openssl/lib /usr/local/zlib/lib

The absence of "-rpath" in front of the second path causes an error in the linker!

This is fixed by introducing a new macro TS_ADD_RPATH_TO that takes a path and adds it with the "-rpath " prefix.

Also added influential environmental variable RPATH that can be used to give a base value for the rpath. So, the following

    ./configure --with-openssl=/usr/local/openssl --with-zlib=/usr/local/zlib RPATH=/foo

will result in

    LIBTOOL_LINK_FLAGS: -rpath /foo -rpath /usr/local/zlib/lib -rpath /usr/local/openssl/lib

### CODE REVIEW

**Comment by bgaff** [comment]
This has proven to be very useful for us. I've reviewed the patch and obviously am comfortable with it, it'd be great to get the autoconf expert @SolidWallOfCode to take a look. (cc. @zwoop, @jpeach)

**Comment by jpeach** [comment]
I think that if you just pass ```-R/path/to/foo``` to ```TS_ADDTO()``` it will do the right thing. I like the addition of the RPATH option. You don't need to ```AC_SUBST(RPATH)``` since ```RPATH``` is never present in  and generated files.

Here's how I think this should work:

- Rename ```TS_ADD_RPATH_TO``` to ```TS_ADDTO_RPATH```
- ```TS_ADDTO_RPATH``` should start with ```$RPATH``` then append paths
- The argument to ```TS_ADDTO_RPATH``` should be a path, so that the macro can still uniquify

**Comment by jaaju** [comment]
@bgaff, @jpeach 
I have incorporated James' feedback and resolved conflicts by merging changes from upstream. Let me know if this is good. Thanks!

**Comment by jpeach** [comment]
I filed this as [TS-4047](https://issues.apache.org/jira/browse/TS-4047).

**Comment by bgaff** [comment]
@jpeach , if you're good, I'll land this.

**Comment by jpeach** [comment]
This is getting closer. Please rebase your changes onto latest master and force push the branch to refresh.

There are a number of places that still need to be updated to use ```TS_ADDTO_RPATH```:

    $ grep LIBTOOL_LINK_FLAGS build./
    common.m4:  TS_ADDTO(LIBTOOL_LINK_FLAGS, [-Wl,-rpath -Wl,$1])
    jemalloc.m4:    TS_ADDTO(LIBTOOL_LINK_FLAGS, [-R${jemalloc_ldflags}])
    lzma.m4:    TS_ADDTO(LIBTOOL_LINK_FLAGS, [-R${lzma_ldflags}])
    pcre.m4:    TS_ADDTO(LIBTOOL_LINK_FLAGS, [-R${pcre_ldflags}])
    xml.m4:        TS_ADDTO(LIBTOOL_LINK_FLAGS, [-R${libxml2_ldflags}])
    xml.m4:    TS_ADDTO(LIBTOOL_LINK_FLAGS, [-R${expat_ldflags}])

Notice that these all use the ```-R/path``` syntax. This is because the portable syntax for specifying the RPATH is ```-Wl,-rpath -Wl,/path```. The ```-Wl,-rpath=/path``` syntax appears to be specific to the GNU linker (at least it is not supported by the OS X linker). When I tried the portable syntax, ```TS_ADDTO``` doesn't do the right thing (it splits on whitespace). You end up with something like this:

        LIBTOOL_LINK_FLAGS: -Wl,-rpath -Wl,/usr/local/lib -Wl,/opt/jpeach/lib

Finally, you need to append ```$RPATH``` in the main ```configure.ac``` since it is possible for ```TS_ADDTO_RPATH``` to never get called.

**Comment by jaaju** [comment]
@jpeach - I have pulled in the latest from upstream and addressed your feedback. Thanks!

**Comment by bgaff** [comment]
Hey @jpeach I'm gonna land this within the next day (rebased into a single commit), unless you have any other questions or concerns? But after my review it appears that @jaaju has addressed all open concerns.

**Pull request closed without merging**
