### PR TITLE
TS-5051 Add a new log tag %<vbn> AppVersionInfo.BldNumStr

### PR DESCRIPTION
**Pull request by sekimura**

### CODE REVIEW

**Comment by jpeach** [comment]
I really don't think this is worth a log tag. It is trivial to add this information as Lua constants to be consumed by `logging.config`. Alternatively, a logging tag that can log an arbitrary metric would be interesting. This is just too specific IMHO.

**Comment by sekimura** [comment]
+1 to " a logging tag that can log an arbitrary metric"

**Comment by zwoop** [comment]
Hmmm, logging most metrics seems somewhat useless. What would be useful would be to have generic access to the underlying data that is used to update the metrics for that transactions.

There are exceptions; Those metric which are static (tracking things like versions, startup time, etc.) might be useful to provide as a generic log field? If we have easy access to those from the Lua logging.config format, then I'm definitely +1 on using that instead. Is there a Lua API to inspect the lib records, or would the Lua script have to do a request on the mgmt port? The latter seems potentially expensive, unless it can be saved in a static variable.

**Comment by jpeach** [comment]
Well it is trivial to make those constants available in the Lua API. I don't think these things are worth adding log tags on their own.

**Comment by zwoop** [comment]
@sekimura You want to take  stab at adding this as Lua definitions? I assume the intent would be to expose some of these constants in an internal Lua table?

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
Lets close this, I also like the idea of having a generic log tag for all process metrics.

**Comment by randall** [comment]
FWIW, the build number is exposed in records and can be accessed via the record container in logging.config.

eg

`%<{proxy.process.version.server.build_number}record>`

**Pull request closed without merging**
