### PR TITLE
Fix lost pending_actions causing actions on stale objects.

### PR DESCRIPTION
**Pull request by shinrich**
(cherry picked from commit 493803c4e26348a9c707320a134709d832f9a182)

Conflicts:
	proxy/http/HttpSM.cc

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[ci approve autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
Closing this in preference for PR #4380.

For some reason the merge done in the autest build dropped a closing brace.  I redid the PR and all is well.  Perhaps it got confused with intervening commits?

**Pull request closed without merging**
