### PR TITLE
Doc: Provide more context for HSTS example in header_rewrite.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Fix warnings.
Add documentation for some TSMimeHdrField functions.
Add notes on HSTS example in header_rewrite.

### CODE REVIEW

**Comment by maskit** [comment]
I would approve this if it were 3 or 4 commits.

**Comment by SolidWallOfCode** [comment]
Allright, let me set that up.

**Comment by SolidWallOfCode** [comment]
OK, split in to 4 commits :+1:

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
@SolidWallOfCode Thanks. Can you also update this PR's title?

**Comment by SolidWallOfCode** [comment]
Done.

**Pull request merged**
