### PR TITLE
TS-5019: Add total header length checks in HPACK (back-port)

### PR DESCRIPTION
**Pull request by masaori335**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1119/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1013/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1018/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1125/ for details.

**Comment by PSUdaemon** [comment]
This should be a cherry-pick from a5c11a863d961099af500649c4669fb711d48991 and not 79da839ba8fa85cb17593528c046d38b676e6126 which doesn't exist in my tree. It looks like you cherry-picked from your PR feature branch.

Also, make sure to have any conflicts uncommented.

Thanks.

**Comment by masaori335** [comment]
Updated. Please take another look.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1139/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1032/ for details.

**Comment by PSUdaemon** [comment]
Can you explain what this is doing and why you want it back ported? I checked the JIRA and it was empty and the original PR doesn't say much either.

Thanks.

**Pull request merged**
