### PR TITLE
[TS-4530] Enable hostdb.host_file.path by default

### PR DESCRIPTION
**Pull request by ericcarlschwartz**

### CODE REVIEW

**Comment by jpeach** [comment]
[approve ci]

**Comment by jpeach** [comment]
I'm +1 on this. @jacksontj ? @SolidWallOfCode ?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/638/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/534/ for details.

**Comment by jpeach** [comment]
Thanks @ericcarlschwartz, but there was consensus to leave the current defaults.

**Pull request closed without merging**
