### PR TITLE
TS-4911: ts_lua plugin is modified to clear 'client_response_hdrp' po…

### PR DESCRIPTION
**Pull request by brkishore**
…inter when it enters SEND_RESPONSE_HDR hook.

(cherry picked from commit 7662c30e48a444d0d8d37b2e2d34f71b21e3bfcd)

### CODE REVIEW

**Comment by brkishore** [comment]
its by mistake..needs to be backported on to 6.2.x

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1159/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1052/ for details.

**Comment by shukitchan** [comment]
looks good. 👍

**Pull request merged**
