### PR TITLE
Use type info to assign an affinity thread

### PR DESCRIPTION
**Pull request by duke8253**
Had some discussions here https://github.com/duke8253/trafficserver/pull/7

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by duke8253** [comment]
Changed the base to the new 0-rtt feature branch.

**Comment by randall** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
[approve ci autest]

**Pull request merged**
