### PR TITLE
fix grammar

### PR DESCRIPTION
**Pull request by hankai17**

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Review by maskit — APPROVED** [review]

**Comment by maskit** [comment]
[approve ci clang-format]

**Comment by maskit** [comment]
Thank you for the fix.

The change is fine, but it seems like we have a problem with our CI box at the moment.
```
New python executable in /var/jenkins/workspace/clang-format-github/src/.git/fmt/autopep8_1.5.3_venv/bin/python3
Also creating executable in /var/jenkins/workspace/clang-format-github/src/.git/fmt/autopep8_1.5.3_venv/bin/python
Installing setuptools, pip, wheel...
done.
ERROR: Could not find a version that satisfies the requirement pycodestyle==2.6.0 (from versions: none)
ERROR: No matching distribution found for pycodestyle==2.6.0
make: *** [Makefile:1489: autopep8] Error 1
```

**Comment by bneradt** [comment]
[approve ci clang-format]

**Review by bneradt — APPROVED** [review]

**Pull request merged**
