### PR TITLE
Add path param url signing option and client ipv6 verification to url_sig plugin

### PR DESCRIPTION
**Pull request by jrushford**
This is an update to the url_sig plugin that adds verification of IPV6 addresses used in the signature.  In addition it adds an option to use an opaque base64 encoded signing package embedded in the URI as a path parameter.  See the README for details and usage.  The path parameter encoded signature has proven useful for signing requests where relative url paths are obtained from an HLS video manifest.

### CODE REVIEW

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci]

**Comment by zwoop** [comment]
Status on this? You expect / need this for the 71.2. release? @jrushford @gtenev

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci]

**Comment by ywkaras** [comment]
Seems like there should be some code added to the url_sig.test.py gold test.

**Comment by jrushford** [comment]
Looks like it is, I’ll fix that.

**Comment by jrushford** [comment]
Walt,

I’ll have a look.  Thanks for pointing this out.

**Comment by zwoop** [comment]
@jrushford What's the status on this Issue?

**Comment by jrushford** [comment]
Needs to be reviewed, I asked @PSUdaemon to look at it.  Once merged, I’ll create a backport PR for 7.1.x

**Comment by PSUdaemon** [comment]
Do we plan to update the tests first?

**Comment by chassell** [comment]
@PSUdaemon  are you thinking of a separate PR for the url_sig.py gold test?

**Comment by chassell** [comment]
@PSUdaemon  is "we" going to be you first?

**Comment by zwoop** [comment]
Ping on this?

**Comment by chassell** [comment]
I've got a smaller PR that depends on it ... so I'd like to see this reviewed and put in?

**Comment by jrushford** [comment]
I created an issue for autests and will circle back on it when i have an environment setup.  With that said, I've run tests on this PR and all tests okay.   See issue #3021

**Comment by zwoop** [comment]
This has a pretty noticeable merge conflicts on 7.1.x now, do we still need this? If so, can you please either add it to #3196, or, make a new PR against the 7.1.x branch ?

**Comment by jrushford** [comment]
the commit for #2914 has been cherry-picked into #3196.  Only #3196 is for backport.

**Pull request merged**
