### PR TITLE
Add Assertion when fragment_size is large than MAX_FRAG_SIZE

### PR DESCRIPTION
**Pull request by scw00**
link to #5055

### CODE REVIEW

**Comment by scw00** [comment]
also need to document it .

**Comment by oknet** [comment]
It is better to revalidate the `fragment_size` during config reload since it is dynamic variable.

**Comment by SolidWallOfCode** [comment]
Yes, I had the same observation as @oknet - this should be checked when configured, not when used. E.g. around line 3214 in "Cache.cc".  Unfortunately you'll probably need to do a specialized callback for that, rather than rely on `REC_EstablishStaticConfigInt32`.

**Comment by scw00** [comment]
Updated ...

**Pull request merged**
