### PR TITLE
Fixes coverity ID 1374582 and 1374581

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/316/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/329/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/313/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2011/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1904/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/442/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/575/

**Comment by SolidWallOfCode** [comment]
This looks very problematic to me. If you look at the `invoke_remote` implementation it can `free` the value passed as `msg` depending on a flag, but that flag doesn't depend on whether `msg` is on the stack via `alloca` or not. I'd be more tempted to remove the `alloca` logic and put in an `assert` that `data != nullptr`. This is also because if you look, there are other  cases in the switch that have this same problem. Better to make coverity shut up about all of them at once, especially in dead code.

**Comment by zwoop** [comment]
Well, clustering is going, so I can just remove that portion of the change. The patch though is how they do it in other areas.

**Pull request closed without merging**
