### PR TITLE
TSan: Make Thread::cur_time thread local

### PR DESCRIPTION
**Pull request by masaori335**
The alternative (original) approach of #9168 to fix the data race.

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci fedora]

**Review by SolidWallOfCode — APPROVED** [review]

**Comment by zwoop** [comment]
We'd like to see this in the 9.2.x tree, but my recommendation is that we wait for v9.2.2, since we need to make a safe, stable v9.2.1 soon.

**Comment by masaori335** [comment]
We haven't seen any issue with this change so far, but I'm +1 for v9.2.2 for the stability of v9.2.1 release.

A note is this change made 18% improvement on the high rps benchmark. I'm surprised by that, but it makes sense because the `Thread::cur_time` shows up on perf top without the change.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
