### PR TITLE
Try TCP_FASTOPEN socket option with mptcp

### PR DESCRIPTION
**Pull request by serrislew**
With support for TCP_FASTOPEN in newer kernels, allow ATS to try to use TCP_FASTOPEN with mptcp enabled

### CODE REVIEW

**Comment by JosiahWI** [comment]
Where is `TCP_FASTOPEN` defined?

```
% grep -Ir "TCP_FASTOPEN"
./doc/admin-guide/files/records.yaml.en.rst:        TCP_FASTOPEN (8)
./doc/admin-guide/files/records.yaml.en.rst:   Note: If MPTCP is enabled, TCP_NODELAY is only supported on Linux kernels 5.17+. TCP_FASTOPEN
./doc/admin-guide/files/records.yaml.en.rst:        TCP_FASTOPEN (8)
./src/proxy/http/HttpProxyServerMain.cc:#ifdef TCP_FASTOPEN
./src/iocore/net/Connection.cc:#ifdef TCP_FASTOPEN
./src/iocore/net/Connection.cc:      Warning("[Server::listen] TCP_FASTOPEN socket option not valid on MPTCP socket level");
./src/iocore/net/Connection.cc:    } else if (safe_setsockopt(fd, IPPROTO_TCP, TCP_FASTOPEN, (char *)&opt.tfo_queue_length, sizeof(int))) {
```

We don't define it anywhere ourselves. Is it defined in a system header?

**Comment by serrislew** [comment]
yes @JosiahWI  it's defined in the system header files `tcp.h`, like all of the other TCP socket options

**Review by JosiahWI — COMMENTED** [review]
The [POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799/) doesn't list `EOPNOTSUPP` as a case where `setsockopt` (our `safe_setsockopt` wraps it in a retry on interrupt) shall or may fail. I don't see that listed as a possible error code for a `setsockopt` call by [FreeBSD](https://man.freebsd.org/cgi/man.cgi?query=setsockopt&sektion=2) or [Apple](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setsockopt.2.html) either. Do we need to check it? Is it just to be defensive?

**Comment by JosiahWI** [comment]
@serrislew

**Review by JosiahWI — APPROVED** [review]
Thank you for adding support for fast open with mptcp, looks good!

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
