### PR TITLE
Third party build update

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
In trying to start using libswoc I ran in to some build issues. I put this partially in to an earlier PR updating libswoc but was requested to make it a separate PR.

This PR does two things. The major one is to move "lib/records" out of "lib" and in to "src" and "include", splitting the headers from the implementation code, to be more consistent with other base libraries such as `tscore`. The move is needed for two reasons.

* Consistency - "lib" has transitioned from internal libraries to third party libraries. "records" is the anomaly here, as it is the only one in "lib" that is internal. That should be changed.

* Relatedly the presence of a non-third party library in "lib" creates build ordering issue where it is necessary to build "lib" first to because of the third party support for other base libraries, but also to not build it early because "records" depends on other internal libraries such as `tscore`.

In my view the best approach is to go all the way on making "lib" third party only and build it first because at that point, by definition, "lib" cannot have any dependencies on our code base.

This doesn't fully solve the problem, because "src" contains a mix of code, some of which is depended on by other top level directories (e.g. `iocore` depending on `tscore`) and final build objects such as `traffic_server`. Currently this is dealt with by a make in the top level "Makefile.am" to specifically build those dependencies first, but it would be better if there was a non-cyclic dependency graph on the top level directories.

The other reason for this PR is to change how `libyaml` and `libswoc` are built to make them more consistent with each other and other third party libraries. The existing mechanism is a hold over from when `libyaml` was build along side `luajit` for reasons I was unable to determine. That mechanism only works for a single third party library, but now that `libswoc` is around it's not sufficient. The additional support for these two libraries is to support independent internal and external use. The default autotools rules either build and export headers, or not. However the goal is to support building and exporting headers independently for each library.

### CODE REVIEW

**Comment by maskit** [comment]
The direction looks good to me.

How about moving `records` into `/src/shared`? `rpc` was added into `/src/shared` on 10-Dev branch. I wonder what should be under `/`, `/src` and `/src/shared`.

**Comment by SolidWallOfCode** [comment]
I considered "/shared" but I wasn't confident that was a good idea. The original point of "/shared" was for source files that are literally shared between executables. I think I'd prefer to wait on a bigger re-organization that deals with the build ordering in "/src", including "tscore" and "tscpp".

**Review by zwoop — APPROVED** [review]
I'm fine with this, send a note to the mailing list and get some lazy consensus with no objections. Then merge it.

**Comment by bneradt** [comment]
Looks fine. This should be a 10-Dev change though? Maybe at this point it doesn't matter if we've decided that current master will switch to becoming 10-Dev.

**Comment by SolidWallOfCode** [comment]
The problem is I need this for master to do the libswoc upgrade, which @zwoop is hassling me about. Once I start replacing things in `tscpp` with libswoc stuff then the current cyclic dependency will break.

**Comment by bneradt** [comment]
> The problem is I need this for master to do the libswoc upgrade, which @zwoop is hassling me about. Once I start replacing things in `tscpp` with libswoc stuff then the current cyclic dependency will break. We can talk about it Monday when Leif's not around.

I see. Approved.

**Review by bneradt — APPROVED** [review]

**Comment by SolidWallOfCode** [comment]
@maskit - note that only a single shared source file is under "src/shared/rpc". The full RPC implementation is in "mgmt/rpc".

**Comment by maskit** [comment]
> note that only a single shared source file is under "src/shared/rpc". The full RPC implementation is in "mgmt/rpc".

Right, and nothing is under "src/rpc". That's why I had the question, but I can see this PR's focus is on how we build third party libraries and where to move "records" is not really important here.

**Review by maskit — APPROVED** [review]

**Pull request merged**
