### PR TITLE
Plugin ts_lua - Incorrect mapping of transaction configuration parame…

### PR DESCRIPTION
**Pull request by pbchou**
…ter.

TS_LUA_CONFIG_HTTP_NEGATIVE_CACHING_LIFETIME was mapped to the wrong
TS_CONFIG_... value. This patch corrects the mapping thus allowing
the negative caching lifetime to be changed via the Lua plugin.

### CODE REVIEW

**Comment by shukitchan** [comment]
looks good. thanks.

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
[approve ci]

**Comment by zwoop** [comment]
Backported to 7.1.x

**Pull request merged**
