### PR TITLE
Cleanup RamCacheCLFUS

### PR DESCRIPTION
**Pull request by scw00**
- no logic change
 - make some of member private

### CODE REVIEW

**Comment by ywkaras** [comment]
Since an underscore at the beginning means it's a private member, it seems redundant to also use this-> .

**Comment by scw00** [comment]
@calavera Why we need to do that ?

https://cwiki.apache.org/confluence/display/TS/Coding+Style
```
Naming conventions
Classes and Structures
Upper case for the first character of the name
Use camel case (GoodClassName)
Methods
Use STL style underscored lower case names for method names, (e.g. find_if).
Predicates should use a prefix of "is_" or "has_" to check for a specific propery (e.g. is_valid).
Use "this→" when calling other methods in the same class, to distinguish from free functions.
```

**Comment by calavera** [comment]
fair question. I just went through the rest of the code base and it looks like this change is consistent with many other classes as it is. So let's merge it, no need to change anything. :+1:

**Comment by ywkaras** [comment]
My $0.02:  if you're getting confused about what is or isn't a member, that's a sign that you need to try to  write some nested classes in the class and then re-implement the class based on its nested classes.  A rule I've heard is that, for code to be ideally understandable, every scope should have at most 7 direct components.

**Comment by scw00** [comment]
@ywkaras thanks to your tips. It make sense to me.

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
Renrunning CI since it has been awhile.

**Comment by bryancall** [comment]
[approve ci autest]

**Pull request merged**
