### PR TITLE
TS-4287: Add a simple and unavailable server retry feature to Parent Selection.

### PR DESCRIPTION
**Pull request by jrushford**
@zwoop, @jpeach, @PSUdaemon, @bryancall please review and comment.  This is the simple retry and unavailable server retry submitted before in a pull request that also had multi-site origin.  At the last PR meeting I was asked to split this out into a separate pull request.  This is the separate pull request.

### CODE REVIEW

**Comment by jrushf1239k** [comment]
Dead Server retry is confusing and not accurate.  Change the configuration variable names and description to use unavailabe server retry.

**Comment by jrushf1239k** [comment]
Updated this pull request and renamed dead server retry to unavailable server retry.

**Comment by zwoop** [comment]
I'll review this tomorrow (Monday).

**Comment by jrushford** [comment]
Changes have been committed.

**Pull request closed without merging**
