### PR TITLE
Replace ts::MemSpan with swoc::MemSpan

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This replaces `ts::MemSpan` with `swoc::MemSpan`. The changes are extensive because to do this it was also necessary to update the build to use libswoc for both includes and library.

This sets the stage for others to work on replacing the old versions with the newer ones in libswoc, as further build changes should not be required.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[ci approve fedora]

**Comment by SolidWallOfCode** [comment]
[ci approve AuTest 0of4]

**Comment by SolidWallOfCode** [comment]
[ci AuTest 0of4 approve]

**Comment by SolidWallOfCode** [comment]
[ci approve Clang-Format]

**Comment by SolidWallOfCode** [comment]
[approve ci autest 0]

**Review by ywkaras — APPROVED** [review]

**Pull request merged**
