### PR TITLE
Makes sure the types are correct, avoiding compiler warnings

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Review by maskit — APPROVED** [review]
I'm fine with this if compilers are happy with it.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci]

**Review by bryancall — APPROVED** [review]

**Comment by maskit** [comment]
@zwoop Why don't you backport this to 9.1.x and make Jenkins happy?
https://ci.trafficserver.apache.org/view/9.1.x/job/ubuntu_20_04-9.1.x/compiler=gcc,label=ubuntu_20_04,type=debug/21/console

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
