### PR TITLE
C++ API Mocks

### PR DESCRIPTION
**Pull request by myraid**
@bgaff Can you review.

This one works. Is there a better approach?

### CODE REVIEW

**Comment by shukitchan** [comment]
@bgaff. you have a chance to look at this yet?

**Comment by bryancall** [comment]
@bgaff can you shepard this?

**Comment by bgaff** [comment]
Yes, let me take a look.

**Comment by bgaff** [comment]
Would it be possible to see an example test using these Mocks?

**Comment by shukitchan** [comment]
yeah. let's write one for the webp_transform plugin and see.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by myraid** [comment]
I have to write an example test using the mocks.  Let me use webp_transform and write a test.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
After the Summit, is this still a path we want to take? I'm not against this, just asking.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
.

**Comment by myraid** [comment]
@bgaff @zwoop can you take a look.

**Comment by shukitchan** [comment]
@SolidWallOfCode , can you also take a look pls?
We are proposing a unit test framework for cpp api plugins. We have used the webp transform plugin and updated it with unit tests to demonstrate the use of the unit test framework.

**Comment by PSUdaemon** [comment]
This needs to be rebased.

**Comment by PSUdaemon** [comment]
This should get assigned to @dragon512 once we can assign things to him.

**Comment by bryancall** [comment]
@shukitchan Did you want to work on this?  It needs to be rebase.

**Comment by shukitchan** [comment]
let me talk to @myraid

**Comment by bryancall** [comment]
[approve ci]

**Comment by myraid** [comment]
@shukitchan @bryancall let me rebase and update the code.

**Comment by bryancall** [comment]
Please reopen when you rebase it.  We are closing out old PRs.

**Pull request closed without merging**
