### PR TITLE
[TS-4445] Remove double call to NetVConnection->do_io_read.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by atsci** [comment]
--none--

**Comment by zwoop** [comment]
ok to test

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
@shinrich  Can you review this please?

**Comment by zwoop** [comment]
This passed the build tests on the CI, see

https://ci.trafficserver.apache.org/view/github/job/Github-Linux/71/
https://ci.trafficserver.apache.org/view/github/job/Github-FreeBSD/163/

**Comment by shinrich** [comment]
Looks like this fixes a stupid error.  I'll go ahead and merge it up.

**Pull request merged**
