### PR TITLE
Undo most of the previous clang-format config

### PR DESCRIPTION
**Pull request by zwoop**
It retains the nicely formatted apidefs.h though.

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/235/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/341/ for details.

**Comment by zwoop** [comment]
@jpeach @PSUdaemon @bryancall If we're ok with this, I'm pretty sure we should land this. Sorry about the mess-up, it's my bad.

**Comment by zwoop** [comment]
@SolidWallOfCode Can you decide what to do here? I'm going back and forth on this :-/. You get to put the final word on this, I'm honestly ok keeping the current state and just close this.

**Comment by zwoop** [comment]
@SolidWallOfCode decided that we should keep this, so closing.

**Pull request closed without merging**
