### PR TITLE
Make TsSharedMutex.h compile on MacOS.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by zwoop** [comment]
@ywkaras Do we need this for 9.1.x too ?

**Review by cmcfarlen — APPROVED** [review]
This PR worked for me compiling on mac.

**Review by zwoop — APPROVED** [review]

**Review by bneradt — APPROVED** [review]

**Comment by ywkaras** [comment]
@zwoop I think we can live without it in 9.1.  Worst case, without it, we'd see a memory corruption crash when we were already executing a Fatal() or TSFatal().

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
