### PR TITLE
TS3848

### PR DESCRIPTION
**Pull request by pushkarpradhan**
Fixes TS-3848.
A new variable proxy.config.http.cache.required (range: 0-2) controls whether we will exit on cache or volume initialization failure. 
0     Continue serving requests even if we failed to initialize the cache
1     Stop serving requests if none of the cache disks or volumes could be initialized
2     Stop serving requests even if one or some of the cache disks or volumes could not be initialized

### CODE REVIEW

**Comment by sudheerv** [comment]
Some questions/comments:
1) What happens when one or more disks fail during run time? The setting name *proxy.config.http.cache.required* seems too confusing/restrictive that it only applies to initialization.

2) Discussions on the IRC seem to indicate the *proxy.config.http.cache.http* should not be used to indicate whether or not cache is enabled. In particular, it is possible today to have *proxy.config.http.cache.http* disabled globally, but, still have cache initialized (allowing plugins to override *proxy.config.http.cache.http* for individual transactions). So, using *proxy.config.http.cache.http = 0* to ignore *proxy.config.http.cache.required* doesn't look correct and is not compatible.

**Comment by SolidWallOfCode** [comment]
While I think that using the `cache.http` override for transaction level caching control is bad design, it is nonetheless the current design and I must agree with Sudheer on this. I think it is sufficient and correct at this point to check only the `wait_for_cache` flag.

Otherwise the patch looks good.

**Comment by jpeach** [comment]
This branch needs to be cleaned up before it can be merged. Please rebase the patches so that there is:

   - a patch that adds CacheProcessor::cacheRequired() with no other change of behavior
  - other no-op patches that don't change behaviour
  - a single patch that implements the desires behavior.

You need to add comments. Commit comments explaining what each patch in doing and why. Code comments.

Please run ```clang-format``` on the patches. Squash and remove patches that fix bugs in earlier patches. Follow existing coding style (eg. we don't use Hungarian notation).

The documentation of ```proxy.config.http.cache.required``` seems inaccurate. The 0 value conflicts with ```wait_for_cache```, so you should explain how that interacts. Is there any code here that actually stops serving if we lose a disk?

**Comment by pushkarpradhan** [comment]
jpeach: I am confused by the patch requirements, can you explain what do you mean by a no-op patch etc. A no-op patch and a single patch, that seems contradictory?

**Comment by jpeach** [comment]
What I mean is to separate refactoring patches from patches that change behaviour. In a nice, clean patch series, make the refactoring up front in independent patches so they can be reviewed and tested. Then in subsequent patches, make the behavioral changes that depend on the refactoring.

**Comment by SolidWallOfCode** [comment]
I think you should read "patch" as "commit". A co-op commit would just change documentation or formatting.

**Comment by pushkarpradhan** [comment]
Creating a newer pull request so closing this one.

**Pull request closed without merging**
