### PR TITLE
[TS-4243] Collapsed Forwarding Plugin based on Open Write Fail Action…

### PR DESCRIPTION
**Pull request by sudheerv**
… feature.

### CODE REVIEW

**Comment by sudheerv** [comment]
@zwoop : could you pls review?

**Comment by jpeach** [comment]
Needs documentation and ``clang-format`` :)

**Comment by sudheerv** [comment]
@jpeach: clang-formatted the source file. Was planning to add docs (will need to spend some time) in a separate commit after the plugin gets in. Would you rather have it in the same commit?

**Comment by jpeach** [comment]
I'm OK with a separate commit. Can you please remove ``rcsId__header_normalize_cc`` and make all the internal functions and data ``static``?

**Comment by sudheerv** [comment]
Thanks, @jpeach : updated with the comments and squashed the commits.

**Pull request merged**
