### PR TITLE
TS-5060: Fix DNAME support for OSX and FreeBSD.

### PR DESCRIPTION
**Pull request by jrushford**
This PR fixes the build errors found for OSX caused by removing nameser_compat.h in the PR that adds DNAME support.  nameser_compat.h is being added back in and T_DNAME is defined in lib/ts/ink_resolver.h for OSX and FreeBSD.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1251/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1146/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1252/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1253/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1148/ for details.

**Pull request merged**
