### PR TITLE
Set `TS_HAVE_TLS_EARLY_DATA` correctly

### LINKED ISSUE #11575: The `TS_HAS_TLS_EARLY_DATA` define can never evaluate as false
```cmake
+set(TS_HAS_TLS_EARLY_DATA
+    ${HAVE_SSL_SET_MAX_EARLY_DATA}
+    |
+    ${HAVE_SSL_READ_EARLY_DATA}
+    |
+    ${HAVE_SSL_WRITE_EARLY_DATA}
+    |
+    ${HAVE_SSL_IN_EARLY_DATA}
+)

# I added this debug message locally to demonstrate the problem.
message(STATUS "The TS_HAS_TLS_EARLY_DATA variable has the value \"${TS_HAS_TLS_EARLY_DATA}\".")          
```                                                                                                                                       

```
-- The TS_HAS_TLS_EARLY_DATA variable has the value "1;|;1;|;1;|".
```

This was added in #11215 and this incorrect logic is now being copied to other places (#11564). I have tested the impact of this incorrect value by simulating the absence of any TLS early data support, and checking the value of the define in a source file.

### Simulation of `TS_HAS_TLS_EARLY_DATA` Getting Set With Bad Values
```cmake
set(TS_HAS_TLS_EARLY_DATA "0" | "0" | "0" | "0")
```

### Check for Bug in SourceFile
```cpp
// in CacheWrite.cc
#if TS_HAS_TLS_EARLY_DATA
#error "not good"
#endif
```

### Output from GCC

```
/trafficserver/src/iocore/cache/CacheWrite.cc:30:2: error: #error "not good"
   30 | #error "not good"
```

### PR DESCRIPTION
**Pull request by JosiahWI**
I chose a conditional over a generator expression because the community is likely more familiar with the conditional, and the generator expressions can look kind of messy.

Fixes #11575.

### CODE REVIEW

**Review by maskit — APPROVED** [review]
Looks good to me.

**Comment by maskit** [comment]
[approve ci]

**Review by duke8253 — APPROVED** [review]
Looks good, thanks!

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
