### PR TITLE
Record the amount of early data correctly

### PR DESCRIPTION
**Pull request by maskit**
I found two bugs around early data.

The first commit fixes a bug in autest tls_0rtt_server (more specifically, the test client, test-0rtt-s_client). The test does not use ALPN to use H2 on TLS a TLS connection (protocol violation). The violation was found on #11881 (the test fails with the fix on #11881). 

The second commit fixes the other bug in SSLNetVC. It increments the total amount of early data received only after TLS handshake is completed. The first commit revealed this bug because it slightly changes the timing of read operations.

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Comment by maskit** [comment]
[approve ci]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci ubuntu]

**Review by duke8253 — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
