### PR TITLE
tests: fixes various python code issues found by pyflakes

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci freebsd]

**Comment by bneradt** [comment]
Looks great.

Should we consider a pre-commit hook for this as well? I have in mind something similar to our clang-format hook. That would be a separate PR, naturally.

**Comment by randall** [comment]
@bneradt a hook/script/profile for running the lint would be good. These imports are only a fraction of lint issues found by `pycodestyle`

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
