### PR TITLE
AuTest: Update to Proxy Verifier 2.5.2

### PR DESCRIPTION
**Pull request by bneradt**
This fixes a long time crash in Proxy Verifier when no arguments or options were passed.

### CODE REVIEW

**Review by duke8253 — COMMENTED** [review]
+1 this also fixes a bug where some machines can't run the 2.5.0 binary.

**Comment by cmcfarlen** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci AuTest]

**Review by brbzull0 — DISMISSED** [review]

**Review by ezelkow1 — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
