### PR TITLE
Ignore MgmtMessageHdr if ProcessManager is not running

### LINKED ISSUE #4736: Crash in SSLParseCertificateConfiguration
We have more details, but it's a bit sensitive but the  "summary" backtrace is:

```
   [  0] libc-2.12.so              __libc_waitpid
   [  1] traffic_server            crash_logger_invoke (traffic_server/Crash.cc:165)
   [  2] libc-2.12.so              0x2b6c64bd4570
*  [  3] libc-2.12.so              __GI_raise
   [  4] libc-2.12.so              abort
   [  5] libtscore.so.8.0.1        ink_abort (ink_error.cc:99)
   [  6] libtscore.so.8.0.1        enqueue (../../include/tscore/ink_mutex.h:0)
   [  8] traffic_server            ProcessManager::signalConfigFileChild(char const*, char const*, unsigned int) (ProcessManager.cc:229)
   [  9] traffic_server            SSLInitServerContext (SSLUtils.cc:1705)
   [ 10] traffic_server            ssl_store_ssl_context (SSLUtils.cc:1930)
   [ 11] traffic_server            SSLParseCertificateConfiguration (SSLUtils.cc:2153)
   [ 12] traffic_server            SSLCertificateConfig::reconfigure() (SSLConfig.cc:534)
   [ 13] traffic_server            SSLCertificateConfig::startup() (SSLConfig.cc:512)
   [ 14] traffic_server            SSLNetProcessor::start(int, unsigned long) (SSLNetProcessor.cc:67)
   [ 15] traffic_server            main (traffic_server/traffic_server.cc:1886)
```

### PR DESCRIPTION
**Pull request by masaori335**
Fix #4736

### CODE REVIEW

**Comment by masaori335** [comment]
This should go to v9.0.0 because this fixes a crash.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
This now has a merge conflict if I try to cherry-pick to 8.0.x, can you please make a new PR (and link to this one) for the 8.1.x branch?

**Comment by bryancall** [comment]
There was a separate PR #6534 for 8.1.x and this change when into the 8.1.0 release.

**Pull request merged**
