### PR TITLE
TS-4513: Error when building with gcc 6.1.1 with luajit

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by jpeach** [comment]
👍

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/581/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/477/ for details.

**Comment by PSUdaemon** [comment]
How does this affect us since this code is in a `subtree`?

**Pull request merged**
