### PR TITLE
Lua plugin: add ts.server_response.get_maxage()

### PR DESCRIPTION
**Pull request by ema**

### CODE REVIEW

**Comment by shinrich** [comment]
@maskit's PR should address the clang analyzer issue.

Many of the tls_hook PR's are failing because traffic server dumped core.  Which seems very unlikely to be related to this code change.  I'll try to reproduce locally.

**Comment by shukitchan** [comment]
This looks fine. Thanks .

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci clang-analyzer]

**Pull request merged**
