### PR TITLE
Remove unused _setFunc parameter to LogField constructor overload.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Review by masaori335 — APPROVED** [review]
Looks good.

**Comment by ywkaras** [comment]
[approve ci rocky]

**Comment by ywkaras** [comment]
[approve ci rocky]

**Comment by ywkaras** [comment]
[approve ci rocky]

**Comment by brbzull0** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
LSan detected a leak in the magick plugin.

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Pull request merged**
