### PR TITLE
remap_reload test: Spacing out file modification and reload

### PR DESCRIPTION
**Pull request by bneradt**
The remap_reload.test.py AuTest is still flaky despite the last effort
to make it reliable. It looks like this might be because the
modification of the remap file and the reload is racing with each other.
This puts them in separate TestRuns and spaces them out by a few seconds
to see whether this makes the test more reliable.

---

## For Review

Let's run this a few times in CI to see if this improves reliability. Running this in a loop locally failed to reproduce this locally for me.

### CODE REVIEW

**Comment by bneradt** [comment]
The first remap_reload autest passed. Running again.

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Review by masaori335 — APPROVED** [review]
Looks good. Please merge when your retry test on the ci box is done.

**Comment by zwoop** [comment]
This file doesn't exist in 9.2.x

**Comment by bneradt** [comment]
> This file doesn't exist in 9.2.x

Ah, right. Good catch. I forgot that we didn't put this work in 9.2.x. I'll remove that project.

Thanks!

**Pull request merged**
