### PR TITLE
Update configuring-traffic-server.en.rst : 'config' option missing

### PR DESCRIPTION
**Pull request by persiaAziz**
The correct set command is 
traffic_ctl config set VARIABLE VALUE

### CODE REVIEW

**Comment by zwoop** [comment]
Hmmm, wasn't the idea that we'd use :program:`traffic_ctl`? :)

**Comment by jpeach** [comment]
For a suboption, I think the syntax would be:

    :option:`traffic_ctl config set` NAME VALUE

But I'd have to render the docs locally to see exactly what happens. @persiaAziz what happens?

**Comment by jpeach** [comment]
@zwoop I'm going to merge this as is for now, ok?

**Comment by persiaAziz** [comment]
I tried to build the documentation using the following link 
[https://docs.trafficserver.apache.org/en/latest/developer-guide/documentation/building.en.html](https://docs.trafficserver.apache.org/en/latest/developer-guide/documentation/building.en.html)

But I am getting error 
```
PAPEROPT_a4="-D latex_paper_size=a4" PAPEROPT_letter="-D latex_paper_size=letter" PAPER="letter" ./sbuild false -c .  -d docbuild/doctrees -b html . docbuild/html
make: *** [html-local] Error 1
```

**Comment by jpeach** [comment]
Do you have the ``sphinx-doc`` package installed?

**Comment by persiaAziz** [comment]
Yes I just did. But still getting the same error.

**Comment by jpeach** [comment]
What is the output of ``python ./doc/checkvers.py  --check-version``?

**Comment by persiaAziz** [comment]
`checking for sphinx version >= 1.1...  found 0.6.6`

**Comment by persiaAziz** [comment]
needs an update?

**Comment by jpeach** [comment]
Yup

**Comment by persiaAziz** [comment]
Unfortunately the machine I am working on can not find a later version. I will probably try later when I have my own machine. I think it is better if you merge this as is for now.

**Pull request merged**
