### PR TITLE
Change api TSSslTicketKeyUpdate to return TSReturnCode

### PR DESCRIPTION
**Pull request by duke8253**
Making changes as discussed in the mailing list.

### CODE REVIEW

**Comment by bneradt** [comment]
[approve ci fedora]

**Comment by duke8253** [comment]
[approve ci clang-analyzer]

**Comment by bneradt** [comment]
[approve ci ubuntu]

**Review by SolidWallOfCode — APPROVED** [review]

**Comment by zwoop** [comment]
How is this not breaking compatibility ? This can't go into 9.x, and likely shouldn't have gone into master either ?

**Pull request merged**
