### PR TITLE
TS API and hooks to manipulate the ATS session cache and ticket keys

### PR DESCRIPTION
**Pull request by shinrich**
The API changes are described in http://home.apache.org/~shinrich/docs/developer-guide/ssl-session-api.en.html.  I will distribute on the mailing list for a more formal API review.

Once it is accepted, I'll transition the contents of that page into the appropriate documentation pages.  

We have a plugin that exercises these APIs.  It needs another cleanup pass or so, but my aim to get that plugin up as an example plugin (it requires redis for communication thus the example placement rather than experimental).

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci fedora]

**Comment by SolidWallOfCode** [comment]
Apparently I really like this PR.

**Comment by PSUdaemon** [comment]
Is `experimental.h` still a thing?

**Comment by shinrich** [comment]
@PSUdaemon I'm not sure what you mean by experimental.h.

**Comment by shinrich** [comment]
Updated the PR to add documentation since it seems that the API review view the mailing list passed.  Also added logic to deal with ticket key update races between the file API and the function API.  Still need to test that logic.  Will do that today or tomorrow and updated code if needed.

**Comment by shinrich** [comment]
[ci approve autest]

**Comment by shinrich** [comment]
[approve ci fedora]

**Comment by shinrich** [comment]
[approve ci linux]

**Comment by shinrich** [comment]
[approve ci linux]

**Comment by chenglongwei** [comment]
@shinrich I am very interested in this patch especially the **session ticket key rotation** API. However, we run version 6.2.x currently, which makes us very difficult to cherry-pick this pull request.

I am wondering whether we can have a backport for 6.2.x?

**Pull request merged**
