### PR TITLE
TS-4356 Deprecate cacheurl plugin

### PR DESCRIPTION
**Pull request by gtenev**
Added a "deprecated" message and `cachekey` examples to the `cacheurl` doc.

### CODE REVIEW

**Comment by jpeach** [comment]
Should we also add a ``TSError`` message at cache url load time?

**Comment by gtenev** [comment]
Sounds good, will add the message.

**Comment by zwoop** [comment]
@gtenev  Can you push an update to this PR, with the addition of the suggested TSError() to the plugin? I'll commit when done (this should go into 6.2.0 IMO).

**Comment by gtenev** [comment]
PR updated, TS-4356 already marked "Backport to Version: 6.2.0"

**Pull request closed without merging**
