### PR TITLE
cache_range_requests plugin optional support for special IMS header

### PR DESCRIPTION
**Pull request by traeak**
To support slice plugin self healing a regex_revalidate type feature can be enabled for cache_range_requests (param _-c_ or _--consider-ims_):

```X-CRR-IMS: (date) (ie: Tue, 19 Nov 2019 13:26:45 GMT)```

Use case: During slice stitching if 2 adjacent range requests disagree for etag/last modifed, the "older" of the 2 block ranges will be re-requested with this **X-CRR-IMS: (newer block range date)** which can propagate up through layers of a CDN to an origin if necessary (assuming they all use the cache_range_request plugin with the _--consider-ims_ param).

When enabled and using with the slice plugin, for security purposes it is advisable to add a header_rewrite rule to strip the X-CRR-IMS header at the edge if the incoming port (php) is NOT 0 (the internal ATS loopback port).

Converted the plugin configuration to use getopt_long() and deprecated _ps_mode:cache_key_url_ in favor of _-p_ or _--ps-cachekey_ Modified base autest for both new and deprecated option check.

Also included: TSMBuffer/TSMLoc variable name changes, switching a txndata::char* to std::string (no extra malloc/freees), switching static const char* to constexpr std::string_view, moving functions into a private namespace.

Extra testing:  valgrind with small canned set of requests, automated range requester which dual issues through ATS and origin.

### CODE REVIEW

**Comment by traeak** [comment]
Oof the PR pulled way to much code in.

**Comment by jrushford** [comment]
[approve ci]

**Comment by traeak** [comment]
Added a cache_range_requests admin guide.

**Comment by jrushford** [comment]
@traeak Thanks for adding the cache_range_requests to the admin-guide however, a link to the doc is needed in doc/admin-guide/plugins/index.en.rst so that the doc can be found.  Also 'make html' gives this error:  

`/trafficserver/doc/admin-guide/plugins/cache_range_requests.en.rst: WARNING: document isn't included in any toctree`

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
