### PR TITLE
Fix out-of-bounds access in append_string function.

### PR DESCRIPTION
**Pull request by jrushford**
Adjust the math in calculating 'num' when total size exceeds 'max_len'.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by jrushford** [comment]
[approve ci clang-analyzer]

**Comment by jrushford** [comment]
[approve ci clang-analyzer]

**Pull request merged**
