### PR TITLE
Update HttpConfig.h

### PR DESCRIPTION
**Pull request by zhouxiangxiang**
memory leak

### CODE REVIEW

**Comment by shinrich** [comment]
Looks reasonable.

**Comment by shinrich** [comment]
@jpeach points out that the existing code should recursively free the chain of port objects.  So we are not understanding the leak case.  How did you detect this leak?  And can you link the JIRA that describes the issue?

**Comment by zwoop** [comment]
Bike shedding and side-tracking a bit, but we should encourage to not use the pattern

    if (foo)
        delete foo;


it should be just

    delete foo;

**Comment by zhouxiangxiang** [comment]
@zwoop  I'm a newbie of ats.   
I use it in my company, and the memory is always increasing.    
The memory's management puzzle me a lot.

**Comment by zwoop** [comment]
Yeah, maybe we should close this PR ?

**Pull request closed without merging**
