### PR TITLE
HostDB: cancel timeout on free

### PR DESCRIPTION
**Pull request by a-canary**
adding a line to cancel the hostdb cont timeout, when the hostdb cont is freed.

### CODE REVIEW

**Comment by shinrich** [comment]
The two failing tls tests are core dumping which is concerning.

**Comment by shinrich** [comment]
The two TLS ones fail to an assert in NetHandler::startIO.  Some other thread is holding the nethandler mutex.  Seems very unrelated to this change.

```
Fatal: P_UnixNet.h:757: failed assertion `this->mutex->thread_holding == this_ethread()`
```

**Comment by a-canary** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
Cherry picked to 8.1.0.

**Pull request merged**
