### PR TITLE
Add a case to the tls_client_cert2 to exercise one file with cert and key

### PR DESCRIPTION
**Pull request by shinrich**
This new test will currently fail.  Pushing up the fix in a moment.  Need to have a test case to catch possible future regression.

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Pull request merged**
