### PR TITLE
Test: Convert test_arena.cc to Catch

### PR DESCRIPTION
**Pull request by chitianhao**
``test_arena.cc`` split from https://github.com/apache/trafficserver/pull/4254

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci clang-format]

**Comment by chitianhao** [comment]
I think I need to rebase this on https://github.com/apache/trafficserver/pull/4282

**Comment by bryancall** [comment]
[approve ci clang-format]

**Comment by bryancall** [comment]
You shouldn't need to rebase.  We rebase the PR on master when running tests.

**Comment by chitianhao** [comment]
The new fixed is not merged yet.

**Pull request merged**
