### PR TITLE
Ran clang-tidy with readability-braces-around-statements

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by atsci** [comment]
RAT check *failed*! https://ci.trafficserver.apache.org/job/RAT-github/160/

**Comment by bryancall** [comment]
This is a big change.  We should determine if we would like to have braces and all conditionals and loops.  This is something I do myself almost all the time.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/145/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/143/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/271/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1841/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1732/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/403/

**Comment by SolidWallOfCode** [comment]
I'm -0 on requiring braces. I am +1 on requiring that if any `if` clause has braces, all must. But I see nothing wrong with
```
if (condition)
    do_this();
```

**Comment by zwoop** [comment]
I think the "Subject" line on this PR is slightly confusing, "more readable" ? It seems this enforces braces on all conditionals?  I definitely don't have a strong opinion on this, but maybe this is something to bring to the mailing list / summit to discuss ?

**Comment by zwoop** [comment]
Oops, looks like there are conflicts here, that has to be resolved, but still +1.

**Pull request merged**
