### PR TITLE
Add cache_range_requests autest, add to x-parentselectiion-key to xdebug plugin.

### PR DESCRIPTION
**Pull request by traeak**
add basic functionality test for cache_range_requests, including an addition to the xdebug plugin to add parent selection key inspection (x-parentselection-key).

### CODE REVIEW

**Comment by traeak** [comment]
These tests all pass except the python microserver doesn't exit properly for some reason at the end.

**Comment by traeak** [comment]
[ci]

**Comment by jrushford** [comment]
[approve ci]

**Comment by zwoop** [comment]
The subject here is slightly confusing. I would have preferred to see it as "Adding X-ParentSelection-Key to xdebug", with the more detailed description saying that it's also adding autest. I know, bike shedding, but these things can be important, particularly when we put together release notes.

**Comment by traeak** [comment]
Of we didn't squash checkpoints you could see that xdebug was modified to
support testing the cache range requests plugin. I well add one more small
test case to the plugin to verify that the patent selection option is
different when turned on and off.

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
