### PR TITLE
Fixes leak in SNIAction name globbing

### PR DESCRIPTION
**Pull request by randall**
pcre_compile allocated object is never pcre_free-ed

### CODE REVIEW

**Comment by randall** [comment]
This goes back to at least ATS 9.

**Review by bneradt — APPROVED** [review]

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]
Thanks for cleaning these leaks up.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
