### PR TITLE
Autest test extension modification using opensourced testing tools

### PR DESCRIPTION
**Pull request by macisasandwich**
Removes MicroServer, MicroDNS, Traffic-Replay, and SessionValidation out of tests/tools into their independent BitBucket repo together with Autest. 

All the relevant test extensions and the affected tests have been modified to work with the new setup. 

tests/bootstrap.py has also been updated to automatically install all the dependencies for the tests to run properly.

Updated tests/README.md and cleaned up

### CODE REVIEW

**Comment by dragon512** [comment]
[approve ci]

**Comment by shinrich** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by duke8253** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci autest]

**Pull request merged**
