### PR TITLE
TS-3782: Add normal scenario tests for HTTP/2

### PR DESCRIPTION
**Pull request by masaori335**
- Part of [TS-3782](https://issues.apache.org/jira/browse/TS-3782)
- Fix [normal_scenario_tests_001.patch](https://issues.apache.org/jira/secure/attachment/12746286/normal_scenario_tests_001.patch)

### CODE REVIEW

**Comment by masaori335** [comment]
@jacksontj Please take another look.

**Comment by jacksontj** [comment]
LGTM, this is a *very* basic test for HTTP2, but should make it much easier for others to contribute tests for http2

**Comment by masaori335** [comment]
Yes, it is purpose of this patch. HTTP/2 has many features and ATS supports parts of them currently.
I hope somebody who add features or fix bugs, add suitable tests here.

**Comment by jacksontj** [comment]
If someone is around to merge we are ready, otherwise I can grab this once
I'm on front of one

**Comment by zwoop** [comment]
Thanks Masaori and Thomas. I've merged this pull request.

**Comment by masaori335** [comment]
This is merged as 1cbe7c70bf81b6ba678070670da649de510b7991.
Thanks!

**Pull request closed without merging**
