### PR TITLE
Cleanup: Remove old SDKTest for thread_pool example plugin

### LINKED ISSUE #8561: Test of thread pool example plugin
The thread_pool example plugin (psi) has some tests, but it's not built nor running. Do we want to maintain this test or KIWF?

https://github.com/apache/trafficserver/tree/master/example/plugins/c-api/thread_pool
https://github.com/apache/trafficserver/tree/master/example/plugins/c-api/thread_pool/test/SDKTest

### PR DESCRIPTION
**Pull request by masaori335**
Get rid of unmaintained code from initial commit. Close #8561.

### CODE REVIEW

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by guneshmunjal** [comment]
@masaori335 @bryancall  hello sir i am really very sorry to disturb you but could you help me . i am gunesh and i am new to open source i really liked this project and want to contribute in this project. i am well aware of C++.
i subscribed to the mailing list but still i am not able to join .
could you please help me out in figuring things correctly.

**Review by bneradt — APPROVED** [review]

**Comment by masaori335** [comment]
@guneshmunjal Hello, welcome! Sending an e-mail to `users-subscribe@trafficserver.apache.org` should work. But if you need help, please send me an e-mail ( you can find my e-mail address from the commit log :) )

- SUBSCRIBING AND UNSUBSCRIBING - Mailing Lists
https://www.apache.org/foundation/mailinglists.html#subscribing

**Pull request merged**
