### PR TITLE
TS-4726: Remove unnecessary assert in ProxyClientTransaction::release

### PR DESCRIPTION
**Pull request by masaori335**
[TS-4726](https://issues.apache.org/jira/browse/TS-4726)

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/512/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/409/ for details.

**Comment by JamesPeach** [comment]
Is the reader actually *guaranteed* to be NULL here?

**Comment by shinrich** [comment]
Agreed that the assert doesn't mean much at this point.

current_reader (the HttpSM) may be NULL here or not.  If the StateMachine calls ua_session->release then it will not be null.  But Http2Stream::release() calls do_io_close which calls super::release() again for good measure.  The second time through current_reader will be NULL.

**Comment by zwoop** [comment]
I think I see this, we only set current_reader=NULL after that assert, right?

**Comment by masaori335** [comment]
Yes, it is moved to `ProxyClientTransaction::destroy()` by TS-4507
https://github.com/apache/trafficserver/blob/master/proxy/ProxyClientTransaction.cc#L85

**Comment by zwoop** [comment]
Should we land this?

**Comment by shinrich** [comment]
Yes, we should land it.

**Pull request merged**
