### PR TITLE
RFC: Build with non-recursive make.

### PR DESCRIPTION
**Pull request by jpeach**
Stop using recursive make to build subdirectories.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1031/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/923/ for details.

**Comment by zwoop** [comment]
Besides the failures ( ;-) ) I think this is something we should do. It's a fairly simple change (hopefully), retains the modularity (by retaining the Makefile.inc's and then include them), and allow for much more parallelized builds.

**Comment by jpeach** [comment]
Closing for now. Will make separate PR(s) with a slightly different approach.

**Pull request closed without merging**
