### PR TITLE
Add hooks for outbound TLS start and close.

### PR DESCRIPTION
**Pull request by shinrich**
Requires PR #5236 and #5235 to be merged first.  This PR has all three commits.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
This again has a merge conflict, but we'll need this for 8.1.x. Maybe there's another 8.1.x-nogo PR that needs to be added as well.

**Comment by zwoop** [comment]
Removing from 8.1.x, please add Project 8.x back again if this is critical for 8.1.0 (and, provide a PR with the cherry-pick as well, since this doesn't pick cleanly).

**Pull request merged**
