### PR TITLE
TS-4695 Removes the --enable-cppapi build option

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/526/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/423/ for details.

**Comment by JamesPeach** [comment]
Need to remove the configure option from ``ci/regression`` too. Probably worth doing a ``git grep enable-cppapi`` to find the stragglers.

**Comment by bgaff** [comment]
I have no objections with this. Thanks

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/546/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/442/ for details.

**Comment by zwoop** [comment]
Sigh, freebsd regression arbitrarily failed it seems ... try again [approve ci]

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/547/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/443/ for details.

**Comment by zwoop** [comment]
Rebooted the FreeBSD VM's again, [approve ci].

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/548/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/444/ for details.

**Pull request merged**
