### PR TITLE
Change comment handling for long lines in url_sig plugin

### LINKED ISSUE #7419: url_sig plugin: line parsing only 300 chars, potential problem with comments.
url_sig's config file parser only handles lines 300 characters or less.  An auto generated comment can exceed that.  As long as there is no '=' character in the leftover comment only an error message is generated but the plugin still loads.  If an '=' character is encountered this will cause the plugin to error out on loading.

### PR DESCRIPTION
**Pull request by ezelkow1**
There is a 300char max buffer size on lines url sig. If there is a comment longer than this then it will show up in the next fgets. If that happens to contain an `=` then it may end up being parsed as a rule otherwise it is thrown away but has an error printed.
This changes the comment handling so that if there is no `\n` seen at the end of the string in the buffer then it is assumed it is a long comment line and urlsig will continue eating the buffer until it hits a `\n`

Fixes #7419

### CODE REVIEW

**Comment by shukitchan** [comment]
perhaps add a small test here ? 
https://github.com/apache/trafficserver/tree/master/tests/gold_tests/pluginTest/url_sig

**Comment by ezelkow1** [comment]
> perhaps add a small test here ?
> https://github.com/apache/trafficserver/tree/master/tests/gold_tests/pluginTest/url_sig

👍 will do that today

**Comment by ezelkow1** [comment]
@shukitchan Do you know if the autests have fixed the issue of monitoring log files? Since testing this would depend on being able to check diags for an issue

**Comment by ezelkow1** [comment]
[approve ci clang-format]

**Comment by ezelkow1** [comment]
@shukitchan added a check to look for an invalid parse error, which would catch this issue without the fix

**Review by shukitchan — APPROVED** [review]
looks good. thanks

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
