### PR TITLE
Metric Library

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
The Metric library is a header only library that supports scaled integer values.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1338/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1234/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1341/ for details.

**Comment by SolidWallOfCode** [comment]
Closing this out - based on feedback from the gang it's been renamed "Scalar" and I've done a lot of clean up and extending so I'll bring it around again in the new improved form.

**Pull request closed without merging**
