### PR TITLE
Replace EXTRA_CXX_LDFLAGS with AM_LDFLAGS

### PR DESCRIPTION
**Pull request by jablko**
We've never had different LDFLAGS for C and C++, so drop
EXTRA_CC_LDFLAGS and EXTRA_CXX_LDFLAGS. Just use AM_LDFLAGS.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1456/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1349/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/Github-Clang/21/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1463/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1356/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/Github-Clang/28/ for details.

**Comment by jablko** [comment]
This PR is included in #1416. I'm landing that one, so I'm merging both pull requests.

**Pull request merged**
