### PR TITLE
TS-4519 This adds three new log formats, using new UUID APIs.

### PR DESCRIPTION
**Pull request by zwoop**
Three commits (one for each log-tag):

    * TS-4519 Adds a new log tag, %<crid> for the sm_id
    * TS-4519 Adds a new log tag, %<puuid> for the process UUID
    * TS-4519 Adds a new log tag, %<cruuid> client_req unique ID

This is in reality just a concatenation of %<puiid>-%<crid>, but
is convenient to have, and also assures consistency with other
features (e.g. header_rewrite, and Debug() in the HttpSM).

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/352/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/246/ for details.

**Comment by zwoop** [comment]
@PSUdaemon  Please review? :)

**Comment by zwoop** [comment]
Also, I'm not married to the new log tags. It seems Github mangled my comment badly, which I fixed right now. If someone has better suggestions for naming the tags, please voice your opinion.

**Pull request closed without merging**
