### PR TITLE
Multiplexer plugin: Fix bug with chunk decoding, add some comments.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
The chunk decoding issue was discovered in production and this was verified to fix the problem.

### CODE REVIEW

**Comment by shukitchan** [comment]
This looks reasonable.

**Comment by SolidWallOfCode** [comment]
[ci approve clang-format]

**Comment by SolidWallOfCode** [comment]
[ci approve clang-format]

**Comment by SolidWallOfCode** [comment]
[ci approve clang-format]

**Comment by SolidWallOfCode** [comment]
[approve ci clang-format]

**Pull request merged**
