### PR TITLE
Refactor QUICPacket class

### PR DESCRIPTION
**Pull request by maskit**
This includes:
- Separate classes for each QUIC packet types
- Interface change to `QUICPacketFactory::create_*_packet()` to reuse a buffer when creating sending packets (the same idea as `QUICFrameFactory::creat_*_frame()`) and to remove a `memcpy`
- Fixes for handling multiple `IOBufferBlock`s

This improves throughput about 8%.

Class hierarchy:
```
QUICPacket
├── QUICLongHeaderPacket
│   ├── QUICVersionNegotiationPacket
│   ├── QUICInitialPacket
│   ├── QUICHandshakePacket
│   ├── QUICZeroRttPacket
│   └── QCUIRetryPacket
├── QCUIShortHeaderPacket
└── QUICStatelessResetPacket
```

The goal of this refactoring is to remove `QUICPacketHeader` class, but the new classes are just for sending for now (in other words, `QUICPacketHeader` is no longer used for sending packets).

At minimum I'm going to add tests for the new classes on this PR.

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci Ubuntu]

**Comment by maskit** [comment]
Introduced classes for receiving packets too.

QUICPacket
├── QUICPacketR
│   ├── QUICLongHeaderPacketR
│   │   ├── QUICVersionNegotiationPacketR
│   │   ├── QUICInitialPacketR
│   │   ├── QUICHandshakePacketR
│   │   ├── QUICZeroRttPacketR
│   │   └── QCIURetryPacketR
│   ├── QCUIShortHeaderPacket
│   └── QUICStatelessResetPacket
├── QUICLongHeaderPacket
│   ├── QUICVersionNegotiationPacket
│   ├── QUICInitialPacket
│   ├── QUICHandshakePacket
│   ├── QUICZeroRttPacket
│   └── QUICRetryPacket
├── QUICShortHeaderPacket
└── QUICStatelessResetPacket

**Comment by maskit** [comment]
There are several places that are not ideal (memcpy), but I'd like to land this as is for now and work on cleanup later, because this is a pretty big change and easily conflicts with other changes (spin bit, passing IOBufferBlock to handle huge H3 DATA frames, etc.).

**Comment by scw00** [comment]
It seems we have two type packets Receive packets (QUICPacketR) and Send Packets. And QUICPacketR consist of connection information like peer address, local address and UDP connection.

I'm ok with this. I had preliminary idea for QUICConnection .

How about sink it into QUICConnection. QUICConnection has responsibility to convert UDPPacket to QUICPacket. So QUICConnection know where is the packet from and where to deliver . Also if migration happen, QUICConnection might need to send probe QUIC Packet.

In general,  QUICNetVConnection doesn't not need to know which address to send or receive. It just  call `QUICConnection::send` to send QUICPacket and QUICConnection decide which udp connection to used.

**Comment by maskit** [comment]
> How about sink it into QUICConnection. QUICConnection has responsibility to convert UDPPacket to QUICPacket. So QUICConnection know where the packet is from and where to deliver . Also if migration happen, QUICConnection might need to send probe QUIC Packet.

At some point we had code like that, but I changed it because I realized that we need to know which packets are from which addresses and packets can be arrived random order. So we cannot simply use current peer address QUICConnection knows. If we are going to have multiple connection object then it may be possible.

**Comment by maskit** [comment]
This closes #4990

**Comment by maskit** [comment]
I had to push new commits to resolve conflicts. There's no logical change.

**Pull request merged**
