### PR TITLE
Upgrade stats over http to use libswoc.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This depends on #9193 , the set of changes will reduce to just the plugin file once those are merged and this rebased.

Primarily this replaces `IpMap` with a class based on `IPSpace`.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci AuTest2of4]

**Comment by SolidWallOfCode** [comment]
[ci approve autest2of4]

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by SolidWallOfCode** [comment]
[ci approve AuTest 2of4]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]

**Comment by SolidWallOfCode** [comment]
Thanks, Neue Brie, but I think I'll wait a bit so Evil Kow can verify.

**Review by ezelkow1 — APPROVED** [review]
LGTM and tested here just some of the basic functionality of path/ip blocking, works as expected

**Pull request merged**
