### PR TITLE
8.1.x backport: header_rewrite: this fixes parsing where the [ ] section gets merged into values

### PR DESCRIPTION
**Pull request by traeak**
For example:

    cond %{SEND_RESPONSE_HDR_HOOK}
     set-header X-First "First"
     set-header X-Last "Last" [L]

would set the header X-Last: Last [L].

In addition, it also fixes a typo (I think?) in an unrelated test,
however, it's unclear as to why it's not failing that test.

    CHECK_EQ(p.get_tokens()[1], "%{METHOD}c”);

(cherry picked from commit 6eb82a932daa97668432681d34f4d603180b8d83)

### CODE REVIEW

**Comment by randall** [comment]
@zwoop This should be cherry-picked into 8.1.x (I missed that in my original merge of header_rewrite changes for 8.1)

**Comment by traeak** [comment]
[autest ci clang-format]

**Comment by traeak** [comment]
[ci approve autest]

**Comment by traeak** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci ubuntu]

**Pull request merged**
