### PR TITLE
TS-2987: Add new TS API TSHttpTxnPluginTagGet

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/429/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/532/ for details.

**Comment by zwoop** [comment]
clang-format. Also, was this proposed on dev@ as well? I might have missed it though.

**Comment by shinrich** [comment]
I didn't send one out.  I'm resurrecting this one.  So if a review was sent around it was quite some time back.  I'll send out a new one.

**Comment by jpeach** [comment]
👍

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/734/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/630/ for details.

**Comment by jpeach** [comment]
👍 Ship it!

**Pull request merged**
