### PR TITLE
Update TSHttpTxnAborted API to distinguish client/server aborts

### LINKED ISSUE #7902: Update TS API TSHttpTxnAborted to Distinguish client/server aborts
Currently, the purpose of the API is limited to providing success/error on overall transaction aborts. We should be able to distinguish client-side aborts from the actual server aborts. While client aborts may not be indicative of any direct problems with downstream servers, it's the server aborts that can be used as passive health-checks for the downstream origin hosts. Also, this makes troubleshooting the 'transaction aborts' easier because now we are able to eliminate an entire set of either client-side or server-side investigations, due to the ability to distinguish between them.

### PR DESCRIPTION
**Pull request by singhsanjay12**
This fixes #7902

### CODE REVIEW

**Comment by shinrich** [comment]
As an API change, could you send around your proposal to the dev mailing list for review?

**Comment by singhsanjay12** [comment]
> As an API change, could you send around your proposal to the dev mailing list for review?

I have sent a proposal email to dev@trafficserver.apache.org

**Comment by shinrich** [comment]
Looks like the lua API array needs to be updated

```
/bin/sh ../libtool  --tag=CC   --mode=compile ccache gcc -DHAVE_CONFIG_H -I. -I../include  -Dlinux -DDEBUG -D_DEBUG -D_LARGEFILE64_SOURCE=1 -D_COMPILE64BIT_SOURCE=1 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/var/jenkins/workspace/centos-github/src/proxy/api -I/var/jenkins/workspace/centos-github/src/proxy/api -I/var/jenkins/workspace/centos-github/src/include/cppapi/include -I/var/jenkins/workspace/centos-github/src/lib/cppapi/include -I/var/jenkins/workspace/centos-github/src/include -I/var/jenkins/workspace/centos-github/src/lib -I/var/jenkins/workspace/centos-github/src/lib/yamlcpp/include -I/var/jenkins/workspace/centos-github/src/lib/yamlcpp/include   -I/usr/include/luajit-2.1  -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -std=gnu99 -ggdb3 -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -Werror -mcx16  -MT lua/tslua_la-ts_lua_server_response.lo -MD -MP -MF lua/.deps/tslua_la-ts_lua_server_response.Tpo -c -o lua/tslua_la-ts_lua_server_response.lo `test -f 'lua/ts_lua_server_response.c' || echo './'`lua/ts_lua_server_response.c
lua/ts_lua_http.c: In function 'ts_lua_http_is_aborted':
lua/ts_lua_http.c:771:7: error: too few arguments to function 'TSHttpTxnAborted'
   if (TSHttpTxnAborted(http_ctx->txnp)) {
       ^~~~~~~~~~~~~~~~
In file included from lua/ts_lua_common.h:30,
                 from lua/ts_lua_util.h:21,
                 from lua/ts_lua_http.c:19:
../include/ts/ts.h:2363:20: note: declared here
 tsapi TSReturnCode TSHttpTxnAborted(TSHttpTxn txnp, bool *client_abort);
                    ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:5826: lua/tslua_la-ts_lua_http.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by singhsanjay12** [comment]
> Looks like the lua API array needs to be updated
> 
> ```
> /bin/sh ../libtool  --tag=CC   --mode=compile ccache gcc -DHAVE_CONFIG_H -I. -I../include  -Dlinux -DDEBUG -D_DEBUG -D_LARGEFILE64_SOURCE=1 -D_COMPILE64BIT_SOURCE=1 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/var/jenkins/workspace/centos-github/src/proxy/api -I/var/jenkins/workspace/centos-github/src/proxy/api -I/var/jenkins/workspace/centos-github/src/include/cppapi/include -I/var/jenkins/workspace/centos-github/src/lib/cppapi/include -I/var/jenkins/workspace/centos-github/src/include -I/var/jenkins/workspace/centos-github/src/lib -I/var/jenkins/workspace/centos-github/src/lib/yamlcpp/include -I/var/jenkins/workspace/centos-github/src/lib/yamlcpp/include   -I/usr/include/luajit-2.1  -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -std=gnu99 -ggdb3 -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -Werror -mcx16  -MT lua/tslua_la-ts_lua_server_response.lo -MD -MP -MF lua/.deps/tslua_la-ts_lua_server_response.Tpo -c -o lua/tslua_la-ts_lua_server_response.lo `test -f 'lua/ts_lua_server_response.c' || echo './'`lua/ts_lua_server_response.c
> lua/ts_lua_http.c: In function 'ts_lua_http_is_aborted':
> lua/ts_lua_http.c:771:7: error: too few arguments to function 'TSHttpTxnAborted'
>    if (TSHttpTxnAborted(http_ctx->txnp)) {
>        ^~~~~~~~~~~~~~~~
> In file included from lua/ts_lua_common.h:30,
>                  from lua/ts_lua_util.h:21,
>                  from lua/ts_lua_http.c:19:
> ../include/ts/ts.h:2363:20: note: declared here
>  tsapi TSReturnCode TSHttpTxnAborted(TSHttpTxn txnp, bool *client_abort);
>                     ^~~~~~~~~~~~~~~~
> make[2]: *** [Makefile:5826: lua/tslua_la-ts_lua_http.lo] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ```

Updated the API call to fix

**Comment by shinrich** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by sudheerv** [comment]
Hey @singhsanjay12 Can you pls update the docs with the new API change?

https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSHttpTxnAborted.en.html

**Comment by sudheerv** [comment]
> > As an API change, could you send around your proposal to the dev mailing list for review?
> 
> I have sent a proposal email to [dev@trafficserver.apache.org](mailto:dev@trafficserver.apache.org)

Here's the link to Sanjay's email to dev@ and Bryan's 👍 

https://www.mail-archive.com/dev@trafficserver.apache.org/msg15815.html

**Comment by singhsanjay12** [comment]
> Hey @singhsanjay12 Can you pls update the docs with the new API change?
> 
> https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSHttpTxnAborted.en.html

Updated the API docs

**Comment by shinrich** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Review by bryancall — APPROVED** [review]

**Pull request merged**
