### PR TITLE
TS-5107: Fix documentation for docutils >= 0.13

### PR DESCRIPTION
**Pull request by jbfavre**
Change introduced in docutils 0.13.0 breaks current documentation build.

Current doc build uses docutils Inliner monkey patching which is likely to
break with each docutils internal changes.

Therefore, I removed the Inliner monkey patching, introduced classic docutils roles
definition using traffic_server extension.

I also updated the documentation using the new rst syntax introduced by the role.
To declare an issue in the documentation one must now use following syntax:
``:ts:jira:`XXXX` `` where XXXX is the Jira's issue number.
You also can reference Github issues using ``:ts:github:`XXXX` ``

Jira's base url is defined in `doc/conf.py` in variable `trafficserver_jira_url`.
Github's base url is defined in `doc/conf.py` in variable `trafficserver_github_url`.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
I would prefer to put the role in the 'ts' domain, e.g. `:ts:issue:` or `ts:jira`. This would be more consistent with existing practice. E.g.
```
:ts:cv:`proxy.config.net.sock_packet_tos_in` and :ts:jira:`1090`
```
instead of
```
:ts:cv:`proxy.config.net.sock_packet_tos_in` and :tsissue:`1090`
```

**Comment by jsime** [comment]
Seconding @SolidWallOfCode's suggestion on a rename. My preference would be for this to be renamed `:ts:jira:` for two reasons: following the existing convention used by `:ts:cv:` and friends as well as distinguishing between Jira issues and GitHub issues.

Other than the name, this looks good.

**Comment by jbfavre** [comment]
@jsime I just wonder wether keeping the difference between Jira and Github is still relevant, after the Jira to Github move annouced by Brian ?

**Comment by jsime** [comment]
I was thinking mostly in terms of the historical references, since the old & closed Jira issues aren't being migrated. Only the new work (and existing, but codeless, Jira tickets) are GitHub-bound as I understand it, and the two systems have independent sequences for the issue numbers.

Grep shows a dozen-ish Jira issue mentions on head (most with no markup, so this PR will be a great improvement). Marking them up with a `:ts:jira:` would leave their links intact and valid for all posterity while we add a separate `:ts:issue:` for referencing all future tickets to GitHub.

**Comment by jbfavre** [comment]
All right, I'll implement both, shouldn't be too difficult :)
But I first have to figure out how to build a link with a XRefRole subclass. Doesn't work for now :-/

**Comment by jbfavre** [comment]
I've updated the pull request.
Now supports `:ts:jira:` as well as `:ts:github:` syntax.

I've updated the current documentation to fix issues which used the old syntax.

Still have to update the whole documentation, but my concern here is to get the PR merged so that I can backport it to Debian package and avoid its removal (because build fails because of docutils 0.13.1 being in Debian)

**Comment by suenway** [comment]
This is an automatically generated message.

sunwei@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Pull request merged**
