### PR TITLE
Update client streams count in Http2ConnectionState::release_stream.

### PR DESCRIPTION
**Pull request by jaaju**
This addresses issue #1394.

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1422/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1315/ for details.

**Comment by zwoop** [comment]
Giving to @PSUdaemon, this is for him to consider for backport.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1392/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1499/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/63/ for details.

**Comment by PSUdaemon** [comment]
@jaaju can you please rebase this?

**Comment by jaaju** [comment]
@PSUdaemon I rebased this to apache:6.2.x.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1530/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1423/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/94/ for details.

**Pull request merged**
