### PR TITLE
Avoid stale client_vc

### PR DESCRIPTION
**Pull request by shinrich**
Conflicts:
	proxy/http/Http1ClientSession.cc
	proxy/http2/Http2ClientSession.cc

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
I don't think this was merged on master yet, right ? Once we do that, we should redo this PR, such that it's a proper "git cherry-pick -x". But this is good, because now I can test this on docs.

**Comment by shinrich** [comment]
Closing this.  I added another commit to  PR #6732 which includes the changes we identified tested on this 9.0.x branch.  Should commit the master PR and cherry-pick back.

**Pull request closed without merging**
