### PR TITLE
Include cstring to make the compiler stop complaining about strlen

### PR DESCRIPTION
**Pull request by duke8253**
bug fix for cachekey, issue #2715

### CODE REVIEW

**Comment by scw00** [comment]
@duke8253 Can you please make a pr against master ?

**Comment by duke8253** [comment]
sure

**Comment by zwoop** [comment]
Yeh, we shouldn't land this, either close this one, or rebase against master and push again.

**Comment by duke8253** [comment]
I thought this was just in 7.1, I just created a new pr for master

**Pull request closed without merging**
