### PR TITLE
Undo the TS-3054 since it make ats cache the incomplete content

### PR DESCRIPTION
**Pull request by scw00**

### CODE REVIEW

**Comment by zwoop** [comment]
Was the intent here to make this PR against master?

**Comment by scw00** [comment]
@zwoop Considering porting it to 6.2.x . I think 6.2.x has the same issue.

This pr could be closed since #2871 merged.

**Comment by zwoop** [comment]
Assigning to Phil, since he's the RM for 6.2.x

**Comment by bryancall** [comment]
[approve ci ubuntu]

**Comment by bryancall** [comment]
[approve ci centos]

**Comment by bryancall** [comment]
@PSUdaemon if you want this for 6.2.x please talk to @scw00.  This PR is for master and the change is already there.

**Pull request closed without merging**
