### PR TITLE
[TS-4444] Prevent segfault dealocating a NULL buffer_reader.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by atsci** [comment]
--none--

**Comment by atsci** [comment]
--none--

**Comment by bgaff** [comment]
Can you provide a TS ticket or some explanation of what triggers this? Have you seen a crash associated with this code path, if so, can you share the backtrace?

**Comment by calavera** [comment]
@bgaff https://issues.apache.org/jira/browse/TS-4444

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Testing one more manual comment post.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
Passed CI build tests.

https://ci.trafficserver.apache.org/view/github/job/Github-FreeBSD/164/
https://ci.trafficserver.apache.org/view/github/job/Github-Linux/72/

**Comment by zwoop** [comment]
@shinrich Can  you review this please?

**Comment by shinrich** [comment]
I'm ok with this change.  It does solve the immediate problem, but I fear that this may be a symptom of a broader issue.  I spent some time this winter tracking down read buffers that were going NULL in the midst of a transaction.  That problem ultimately was the result of a race condition that was freeing the underlying iobuffer.

**Comment by calavera** [comment]
Yeah, I totally agree with @shinrich. I don't think the NULL reference is the real issue either. Unfortunately, my expertise with ATS code base and internal behavior is still quite limited to find a better immediate solution.

**Comment by bgaff** [comment]
Does this only happen on SSL connections? We're seeing something strange related to IOBuffers and SSL connections.

**Comment by calavera** [comment]
No, we've seen it without SSL enabled too.

**Comment by bgaff** [comment]
@shinrich , according to @calavera 's git bisect it's this commit: https://github.com/apache/trafficserver/commit/af76977adb9f3c0296a232688bbcb5a1421a6768, we're seeing a similar issue related to POSTS w/ HTTP/2 where read complete events aren't being fired on a VIO. I'm suspecting it's also related to this commit. Our situation seems to happen w/ small posts where the entire payload is sent in a single chunk. It definitely sounds like these two issues could be related.

**Comment by shinrich** [comment]
The TS-3612 commit resulted into significant restructuring resulting in new issues or adjusting timing to reveal latent issues.  I'll take a look at the small post scenario. 

For the disappearing buffer_reader problem, sounds like that is a broader issue covering http1.x and probably http2.  I think this may be a latent issue since @oknet noted in the bug comments seeing a similar crash in 6.0.x (which is before the TS-3612 commit).

I'm going to go ahead and merge this commit, but file two more issues.  One to track the short post problem and another to track the disappearing buffer reader problem.

**Pull request merged**
