### PR TITLE
Extract opening a pre_warm connection

### PR DESCRIPTION
**Pull request by JosiahWI**
This extracts opening a pre_warm connection into a few functions and moves PreWarmManager from proxy/http into iocore/net. This makes the logic easier to follow, and the PreWarmManager is used primarily in iocore; moving it there brings us closer to getting rid of the cyclic dependency between iocore/net and proxy/http.

### CODE REVIEW

**Comment by JosiahWI** [comment]
[ci approve autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
Rebased on master.

**Review by masaori335 — APPROVED** [review]
Good cleanup 👍 I don't see any logical change.

**Pull request merged**
