### PR TITLE
Fixing copy paste error in SNI yaml parsing

### PR DESCRIPTION
**Pull request by pushkar2017**
This is a fix for https://github.com/apache/trafficserver/issues/4034

### CODE REVIEW

**Comment by shukitchan** [comment]
[approve ci]

**Comment by d2r** [comment]
@bryancall Looks like this is broken in for the upcoming 8.x branch.

Requesting "backport" to avoid regression in the new release.

**Comment by pushkar2017** [comment]
Why is backport not required to 8.0.x? 
Will someone do a bulk commit of the bugs on master branch to 8.0.x soon?

**Comment by d2r** [comment]
> Why is backport not required to 8.0.x?

We are requesting a backport for 8.x.
Project -> Backport release.
Milestone -> Target for this pull request.

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
