### PR TITLE
Add missing source file to CMake esi lib target

### PR DESCRIPTION
**Pull request by JosiahWI**
HandlerManager.cc was missing from the sources.

### CODE REVIEW

**Comment by cmcfarlen** [comment]
Did you intend to add the lua CMakeLists.txt file to this PR?

**Comment by JosiahWI** [comment]
Nope, that one isn't even working yet!

**Comment by JosiahWI** [comment]
[ci approve autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Review by cmcfarlen — APPROVED** [review]

**Pull request merged**
