### PR TITLE
TS-4548: Fix LogHost leak on config error path.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by jpeach** [comment]
Ping @zwoop

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/542/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/439/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
