### PR TITLE
slice port from master to 8.1.x -- self healing and throttle by default.

### PR DESCRIPTION
**Pull request by traeak**
better handling of TSVIO calls and TSVConnAbort (#6239)
Slice plugin: recover out of sync slices, better handling of non 206s (#6691)
slice: clean up of created 502 response header (#6919)
default to throttling and subsequently simplify the transfer code (#7257)

(cherry picked from commit a622cbeaf9b72b694d4cde5a845b6d99c207e53c)

slice/handleFirstServerHeader: return sooner on requested range errors (#7486)

(cherry picked from commit dfd4c7a0fee538b76926645fd79ce7f178ae1442)

### CODE REVIEW

**Comment by ezelkow1** [comment]
should the slice self healing autest fail? I know we do get random autest failures still on 8.1.x but since this is a slice backport figured it may be worth checking

**Comment by traeak** [comment]
I have to redo the cherry pick again.  Sorry I didn't mark this as draft.

**Comment by traeak** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci fedora]

**Comment by traeak** [comment]
[approve ci fedora]

**Pull request merged**
