### PR TITLE
Update s3auth test, removed cpp file and added the Catch main define in the unit test file

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by bryancall** [comment]
[approve freebsd]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci freebsd]

**Comment by zwoop** [comment]
Is this a candidate for 7.1.2 ?

**Comment by zwoop** [comment]
Cherry-picked to 7.1.x

**Pull request merged**
