### PR TITLE
TS-4672: Add lifecycle events to hook-trace example plugin.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/445/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/339/ for details.

**Comment by zwoop** [comment]
I wonder if we should move this out of the examples tree? It seems useful as a debugging tool, and most people probably don't look in examples for useful tools :).

**Comment by jpeach** [comment]
Yeh lets have a new JIRA for that.

**Pull request merged**
