### PR TITLE
log filter enhancement

### PR DESCRIPTION
**Pull request by whutwhu**
fix the bug if filter word included in param value

(cherry picked from commit d3ed0276545774d989d050fe57fdf7dd3877b49c)

fix the bug if filter word included in param value

(cherry picked from commit 601d090b07f64a90cbf11bf55d6c1fad83f34f2d)

fix typo issue

(cherry picked from commit 16ddd19307dc8a04a05bf5cbe8afedd00c538019)

move code to utility function to reduce the interface size

(cherry picked from commit 89bed7bcbc5b57652f9392b1905908d993483674)

code clean from review comments

(cherry picked from commit ca24696ab407f532cb090a0abd40c1a5edb99d40)

1) add autest for log filter; 2) support filter for duplicated param name in query parm of URL

(cherry picked from commit 87db2452595ccbc2498a5eecc31dc9d2a67be62c)

### CODE REVIEW

**Comment by whutwhu** [comment]
@zwoop @zizhong This PR is cherry-pick from master with one commit into 9.0.x for log filter fix.

**Comment by zizhong** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Thanks for playing by the rules, and making a PR that I can actually merge (cherry-picking etc. properly).

**Pull request merged**
