### PR TITLE
ISSUE 1283: Fix CID 1367526 and CID 1367525 in money_trace plugin.

### PR DESCRIPTION
**Pull request by jrushford**
Fixes the coverity scan issues CID 1367526 and CID 1367525 in money_trace plugin.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1287/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1181/ for details.

**Comment by jrushford** [comment]
This PR fixes issue #1283

**Comment by zwoop** [comment]
I think the Jenkins master was wedged, trying a new build [approve ci].

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1288/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1182/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1289/ for details.

**Pull request merged**
