### PR TITLE
Update jtest.cc

### PR DESCRIPTION
**Pull request by jamesbondless**
Removed drand48() #1907

### CODE REVIEW

**Comment by nikhil-khandelwal2** [comment]
private:
  uint64_t mt[312];
  int mti;

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
It seems you only remove the  `drand_seed` .

```
int
main(int argc __attribute__((unused)), const char *argv[])
{
  appVersionInfo.setup(PACKAGE_NAME, "jtest", PACKAGE_VERSION, __DATE__, __TIME__, BUILD_MACHINE, BUILD_PERSON, "");

  /* for QA -- we want to be able to tail an output file
   * during execution "nohup jtest -P pxy -p prt &"
   */
  setvbuf(stdout, (char *)nullptr, _IOLBF, 0);

  fd = (FD *)malloc(MAXFDS * sizeof(FD));
  memset(fd, 0, MAXFDS * sizeof(FD));
  process_args(&appVersionInfo, argument_descriptions, n_argument_descriptions, argv);

  if (!drand_seed) {
    // coverity[dont_call]
    srand48((long)time(nullptr));
  } else {
    // coverity[dont_call]
    srand48((long)drand_seed);
  }
  if (zipf != 0.0) {
```

**Comment by zwoop** [comment]
hmmm, this seems incomplete, it's just removing one of the command line options?

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
This PR is incomplete if you want to remove seeding drand48() it needs more than just the command line option.

Why would you want to remove the seeding in the first place?

**Pull request closed without merging**
