### PR TITLE
TS-4735: Fix race condition in traffic_server startup.

### PR DESCRIPTION
**Pull request by kshri23**
Set max_msgs_in_row to 1 temporarily during traffic_server startup to avoid a hitting race condition when we receive configurations continuously from traffic_manager while coming up. We will reset this limit back to 10,000 in reconfigure() once the initial synchronization is done.

### CODE REVIEW

**Comment by zwoop** [comment]
Curious, where do these messages come from? Is that related to  clustering? [approveci]

**Comment by kshri23** [comment]
These messages come from traffic_manager. It is due to https://issues.apache.org/jira/browse/TS-4646

**Comment by jpeach** [comment]
As mentioned on TS-4646, this is not very reproducible. Although the patch here makes the symptom go away, I'm not comfortable that we really understand why the initial message exchange takes so long.

**Comment by kshri23** [comment]
James, 
I believe that this patch doesn't address just a symptom, it addresses a fundamental flaw in the startup code. A race condition. As I mentioned in the bug description, this issue is not because of the time required for the initial message exchange, but it is because of TS-4646 where repeated and unnecessary messages are being sent with a frequency which is exactly the same as mgmt_read_timeout. Of course, by fixing TS-4646, we will not hit this, agreed. But this design of waiting for 10k messages before yielding is flawed. We cannot do that because traffic_cop expects a few things from traffic_server.

The only reason I decided to address the issue this way is because of the precedent set by 'timeout' in the same class. Initially, timeout is set to '0'. And once the startup is complete, it is set back to the configured value.

I am confused by your reference to TS-4646. As I mentioned there, TS-4646 should happen all the time and I think it does. It is easy to verify that by enabling debug logs. Its just that TS-4646 does not always result in TS-4735 in all cases. It is a race condition.

However, on our VM's it happened all the time. We used this patch to solve the issue and it seems to be working for past few months. Please let me know if you have any concerns.

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/568/ for details.

**Comment by jpeach** [comment]
@kshri23 I dig into the startup sequence a bit more and I'm now convinced that this is a reasonable approach. What do you think about just changing ``MAX_MSGS_IN_A_ROW`` to something sanely small (like 10)?

@kshri23 You need to run ``make -j clang-format``.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/569/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/673/ for details.

**Comment by zwoop** [comment]
This is failing on Linux because of clang-format. Please run "make clang-format" and push again.

**Comment by kshri23** [comment]
James, that is a good idea. I am not sure but I think it should be okay to do so. I will need to dig in  a bit though to understand why this value was fixed unless anyone recollects we chose 10k?

**Comment by jpeach** [comment]
The 10k is an arbitrary number chosen in [TS-4161](https://issues.apache.org/jira/browse/TS-4161).

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/681/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/577/ for details.

**Pull request merged**
