### PR TITLE
clang-analyzer: Fix dead nested assignment issues

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
Last autest fail due to

Running Test x_remap:Build timed out (after 90 minutes). Marking the build as aborted.

Will kick it again.

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
@bryancall If we want this on 8.x, we need a second PR, quite a lot of merge conflicts.

**Pull request merged**
