### PR TITLE
Made roadmap.en.srt more readable

### PR DESCRIPTION
**Pull request by Magmastorm3007**
Hi!I made some changes to the roadmap to make it more readable although it was concise enough before I thought this would help people getting started.Hope to contribute more in the future.

### CODE REVIEW

**Comment by shinrich** [comment]
I like the wording change.  However, I question if this section is still relevant.  Do we still deliver via tarballs?  I think the whole section probably needs to be rewritten to reflect our current process via git.

**Comment by jpeach** [comment]
[approve ci]

**Review by jpeach — APPROVED** [review]
The download page shows source tarballs, so this change looks like a nice improvement to me.

https://trafficserver.apache.org/downloads

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bneradt** [comment]
Looks like there's a trailing whitespace issue:

https://ci.trafficserver.apache.org/job/Github_Builds/job/clang-format/3365/console

```
+ git grep -IE ' +$'
+ fgrep -v lib/yamlcpp
+ fgrep -v .gold:
+ fgrep -v .test_input
doc/release-notes/roadmap.en.rst:When we upload a tarball (compressed archive) to VOTE for a 
doc/release-notes/roadmap.en.rst:the integrity of the process, maintaining that the released code matches 
doc/release-notes/roadmap.en.rst:For instance, if we initially have a release candidate named trafficserver-4.1.4-rc1.tar.bz2 
doc/release-notes/roadmap.en.rst:like trafficserver-4.1.4.tar.bz2. However, this change also affects the checksums (sha1 and md5) 
+ '[' 1 '!=' 0 ']'
+ echo 'Error: Trailing whitespaces are not allowed!'
Error: Trailing whitespaces are not allowed!
+ echo 'Error: Please run: git grep -IE '\'' +$'\'''
Error: Please run: git grep -IE ' +$'
+ exit 1
```

Please remove all trailing white spaces from the new text and recommit.

**Comment by bneradt** [comment]
Should this be closed then?
https://github.com/apache/trafficserver/pull/10654

**Comment by bneradt** [comment]
Merged via:
https://github.com/apache/trafficserver/pull/10654

**Pull request closed without merging**
