### PR TITLE
TS-4551: remove OS_TYPE restriction in gunzip and add unit test

### PR DESCRIPTION
**Pull request by shukitchan**
@zwoop can you please take a quick look and review? Thanks.

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/181/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/289/ for details.

**Comment by zwoop** [comment]
Git messed up again, starting manually [approve ci].

**Comment by zwoop** [comment]
I think it looks reasonable. Can you verify that the test programs are only built at "make check" time? We've had an issue with that with H2 tests, and want to make sure it doesn't happen here. :).

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/182/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/290/ for details.

**Comment by shukitchan** [comment]
yeah. just checked. it is only built at "make check" time. merging now

**Pull request merged**
