### PR TITLE
Simplification dir_init_done

### PR DESCRIPTION
**Pull request by cukiernik**

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
Looks nice, but as long as this is being cleaned up, the symbolic constant `ts::NO_FD` should be used instead of literal "-1". Could you tweak that for me?

**Comment by cukiernik** [comment]
It is compared to AIO_NOT_IN_PROGRESS, not to ts::NO_FD.

**Comment by cukiernik** [comment]
> Looks nice, but as long as this is being cleaned up, the symbolic constant `ts::NO_FD` should be used instead of literal "-1". Could you tweak that for me?
Yes, I could, but legal is -1 https://man7.org/linux/man-pages/man2/open.2.html#RETURN_VALUE
It is never compared to ts::NO_FD, but the copy is compared with AIO_NOT_IN_PROGRESS...

**Review by SolidWallOfCode — APPROVED** [review]
I'm aware -1 is technically valid (and is the value of `ts::NO_FD`) but as a general rule we try to avoid literal numeric (e.g., use of `nullptr` instead of `0`).

**Review by bryancall — APPROVED** [review]

**Pull request merged**
