### PR TITLE
Handle rescheduled transaction close event via tunnel.

### PR DESCRIPTION
**Pull request by shinrich**
Addressess issue #3143.

(cherry picked from commit 200a4fdc76427265de0339d81ecf05cab5fd7067)

Conflicts:
	proxy/http/HttpSM.cc

### CODE REVIEW

**Comment by shinrich** [comment]
Need PR #3308 to build.

**Comment by zwoop** [comment]
@shinrich Seems this has some build issues that needs to be resolved? We can probably ignore autest (sigh), but the others we have to fix.

**Comment by zwoop** [comment]
oooh, maybe these failed because of the other issue, that we just landed. Lets see how this goes now.

[approve ci]

**Comment by SolidWallOfCode** [comment]
AUTest is failing due to the `deny0` test failing because it is trying to make a DNS micro server and that's not been backported to 7.1.x.

**Pull request merged**
