### PR TITLE
7.0.x TS-5059: Fixes for building with OpenSSL 1.1

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1323/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1217/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1325/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1219/ for details.

**Comment by zwoop** [comment]
Mr (!) The Oil Rig,   ( :-) )

did you check with @bryancall if he's planning a 7.0.1 release? if not, this is a moot point, 7.1.x will hopefully be released in 4 weeks.

**Comment by bryancall** [comment]
We are plan to not make a 7.0.1 release and focus our energy on 7.1.0.  I am going to close this PR.

**Pull request closed without merging**
