### PR TITLE
Load the Socks configuration after the host state persistence data is loaded

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by oknet** [comment]
As the PR #5252 break the SocksProxy, this PR bring SocksProxy back.

Request @jrushford for review.

**Comment by jrushford** [comment]
@oknet this PR looks okay to me but, I'm not sure how the defaults socks server was set to down in HostStatus::loadHostStatusFromStats() unless it was previously marked down using traffic_ctl and the record was persisted.  were you marking down the socks proxy with traffic_ctl or do you have regression tests that mark it down?

**Comment by oknet** [comment]
The defaults socks server is set to UP (status: 2) during `loadSocksConfiguration()` which called by `netProcessor.init()`:
```
Traffic Server 9.0.0 Apr 29 2019 20:13:46 bogon
traffic_server: using root directory '/usr/local/ats'
[Apr 30 00:15:33.600]  DEBUG: <DNS.cc:1785 (ink_dns_init)> (dns) ink_dns_init: called with init_called = 0
[Apr 30 00:15:33.600]  DEBUG: <Socks.cc:474 (loadSocksConfiguration)> (Socks) Socks Version 5
[Apr 30 00:15:33.600]  DEBUG: <Socks.cc:484 (loadSocksConfiguration)> (Socks) server connect timeout: 10 socks respnonse timeout 15
[Apr 30 00:15:33.600]  DEBUG: <Socks.cc:495 (loadSocksConfiguration)> (SocksProxy) Read SocksProxy info: accept_enabled = 1 accept_port = 10800 http_port = 80
[Apr 30 00:15:33.600]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_manual, id: -1
[Apr 30 00:15:33.600]  DEBUG: <HostStatus.cc:249 (createHostStat)> (host_statuses) stat name: proxy.process.host_status.172.22.21.211_active, id: 1
[Apr 30 00:15:33.600]  DEBUG: <HostStatus.cc:249 (createHostStat)> (host_statuses) stat name: proxy.process.host_status.172.22.21.211_local, id: 2
[Apr 30 00:15:33.654]  DEBUG: <HostStatus.cc:249 (createHostStat)> (host_statuses) stat name: proxy.process.host_status.172.22.21.211_manual, id: 3
[Apr 30 00:15:33.654]  DEBUG: <HostStatus.cc:249 (createHostStat)> (host_statuses) stat name: proxy.process.host_status.172.22.21.211_self_detect, id: 4
[Apr 30 00:15:33.654]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_manual, id: 3
[Apr 30 00:15:33.654]  DEBUG: <HostStatus.cc:168 (setHostStatus)> (host_statuses) set status up for :  name: 172.22.21.211, status: 2, reason_stat: proxy.process.host_status.172.22.21.211_manual
[Apr 30 00:15:33.654]  DEBUG: <HostStatus.cc:177 (setHostStatus)> (host_statuses) name: 172.22.21.211, status: 2
[Apr 30 00:15:33.673]  DEBUG: <Socks.cc:502 (loadSocksConfiguration)> (Socks) Socks Config File: /usr/local/ats/etc/trafficserver/socks.config
[Apr 30 00:15:33.676]  DEBUG: <Socks.cc:530 (loadSocksConfiguration)> (Socks) Socks Turned on
```

The defaults socks server is set to DOWN (status: 1) by `HostStatus::instance().loadHostStatusFromStats()`.

```
[Apr 30 00:15:33.677]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_active, id: 1
[Apr 30 00:15:33.677]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_active, id: 1
[Apr 30 00:15:33.677]  DEBUG: <HostStatus.cc:172 (setHostStatus)> (host_statuses) set status down for :  name: 172.22.21.211, status: 1, reason_stat: proxy.process.host_status.172.22.21.211_active
[Apr 30 00:15:33.677]  DEBUG: <HostStatus.cc:177 (setHostStatus)> (host_statuses) name: 172.22.21.211, status: 1
[Apr 30 00:15:33.678]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_local, id: 2
[Apr 30 00:15:33.678]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_local, id: 2
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:172 (setHostStatus)> (host_statuses) set status down for :  name: 172.22.21.211, status: 1, reason_stat: proxy.process.host_status.172.22.21.211_local
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:177 (setHostStatus)> (host_statuses) name: 172.22.21.211, status: 1
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_manual, id: 3
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_manual, id: 3
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:172 (setHostStatus)> (host_statuses) set status down for :  name: 172.22.21.211, status: 1, reason_stat: proxy.process.host_status.172.22.21.211_manual
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:177 (setHostStatus)> (host_statuses) name: 172.22.21.211, status: 1
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_self_detect, id: 4
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:267 (getHostStatId)> (host_statuses) name: proxy.process.host_status.172.22.21.211_self_detect, id: 4
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:172 (setHostStatus)> (host_statuses) set status down for :  name: 172.22.21.211, status: 1, reason_stat: proxy.process.host_status.172.22.21.211_self_detect
[Apr 30 00:15:33.742]  DEBUG: <HostStatus.cc:177 (setHostStatus)> (host_statuses) name: 172.22.21.211, status: 1
```

```
1808   netProcessor.init();                     // ---> socks config loaded at here
1809   prep_HttpProxyServer();
...snip...
1862   } else {
1863     remapProcessor.start(num_remap_threads, stacksize);
1864     RecProcessStart();
1865     initCacheControl();
1866     IpAllow::startup();
1867     HostStatus::instance().loadHostStatusFromStats();    // ---> HostStatus persistent data loaded at here
1868     ParentConfig::startup();          // ---> parents proxy config loaded at here
1869 #ifdef SPLIT_DNS
1870     SplitDNSConfig::startup();
1871 #endif
```

By commenting out the L1867 line, the socks server is not set to down again.
IMO, the HostStatus persistent data have to be loaded before the records.

**Comment by oknet** [comment]
@jrushford 

I merged this to start woking on YAML support for the socks proxy.

**Pull request merged**
