### PR TITLE
Removed remnants of h2-14 identifier

### PR DESCRIPTION
**Pull request by cjqian**
This closes #TS-3407.

### CODE REVIEW

**Comment by PSUdaemon** [comment]
This has to wait until 7.0.0.

**Comment by bryancall** [comment]
This pull request is for https://issues.apache.org/jira/browse/TS-3407

**Comment by zwoop** [comment]
Taking a quick glance at this, it looks like it's also removing the registration of "h2" ? That doesn't seem right.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
I'm going to close this, it doesn't look right to me, not sure if we'll see a new PR soon?

**Pull request closed without merging**
