### PR TITLE
Make code compilable with BoringSSL

### PR DESCRIPTION
**Pull request by randall**
(cherry picked from commit 36ec10dd3ec03c7e59c4c5813f665704f5d62584)

Conflicts:
    iocore/net/SSLSessionTicket.h

### CODE REVIEW

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci fedora]
[approve ci ubuntu]

**Comment by bryancall** [comment]
I cherry-picked this from the master commit (36ec10dd3ec03c7e59c4c5813f665704f5d62584) and changed #5516 to have the milestone of 8.0.6

**Pull request closed without merging**
