### PR TITLE
TS-4717: Http2 stack explosion.

### PR DESCRIPTION
**Pull request by sekimura**
This is a backport PR of https://github.com/apache/trafficserver/pull/842

### CODE REVIEW

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
Can you follow [these steps](https://cwiki.apache.org/confluence/display/TS/Fall+2016+Summit?preview=/65866590/66849961/git_back_port_cherry_pick.pdf) when creating this PR? Specifically the `-x` option and uncommenting the conflicts. You can force push to update this PR.

Thanks.

**Comment by sekimura** [comment]
I've updated this PR with `cherry-pick -x`

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1165/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1058/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1167/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1060/ for details.

**Pull request merged**
