### PR TITLE
Fix problems with "Probe" option for X-Debug MIME header field.

### PR DESCRIPTION
**Pull request by ywkaras**
The first commit only adds exercise of "Probe" to the existing x_remap Au test.

### CODE REVIEW

**Comment by ywkaras** [comment]
x_remap, the modified Au test case, caused a core as expected.

Screen Shot 2019-11-18 at 4 51 49 PM

**Comment by ywkaras** [comment]
This now has a second commit that fixes the resource management issues in the xdebug plugin.  It adds general facilities that can be used in other plugin (include/tscpp/api/Cleanup.h).

**Comment by zwoop** [comment]
I'm not a consumer of the CPP APIs, but, assuming I see this right, this adds new public APIs to these APIs? As such, should they not go through the normal API "Review" process, e.g. discussed on mailing list / Issue etc. ?

**Comment by zwoop** [comment]
Is this a candidate for 9.0.x ? I.e. does it fix a crasher in the 9 branch ?

**Comment by ywkaras** [comment]
If it doesn't make it into open source 9, we'll have to put it into Vz-internal 9.  But  the crash only happens if you use the xdebug plugin and you use the probe capability.  The probe capability is currently undocumented.

**Comment by SolidWallOfCode** [comment]
I agree this PR shouldn't change the C++ API. For now, I'd recommend moving that code, if needed, to the plugin. If it looks valuable, it can be promoted later.

**Comment by ywkaras** [comment]
Good point std::unique_ptr has only been around for 8 years we wouldn't want to jump the gun.

**Comment by ywkaras** [comment]
This no longer changes the CPP API.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
