### PR TITLE
TS-4455: remove isEosRcvd() and eosRcvd

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by shinrich** [comment]
Looks reasonable to me.  The isEosRcvd was added as part of TS-3714.  Much of that buffer saving logic has already been removed because changes in handshake buffering in 5.3.x made it unnecessary.

**Comment by zwoop** [comment]
I think we should squash these three commits to one, right?

**Comment by zwoop** [comment]
.

**Pull request closed without merging**
