### PR TITLE
Add simple uri_signing autest and subsequent fixes

### PR DESCRIPTION
**Pull request by traeak**
Add autest for uri_signing plugin.

Code mods/fixes:
- Add override options to sample python signer.

Plugin
- update config file loading (absolute or relative from TSConfigDir)
- crash fix from extraneous jwt cleanup call
- fix token stripping from uri

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by traeak** [comment]
backport to 9.x?  This PR contains crash fix and important functional fixes.

**Comment by zwoop** [comment]
Looks like we need 3632eb748de4556dd87a66925ef2ace9a2b2c3fa too ?

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
This has merge conflicts, and we'll need a new 8.1.x PR. Also, feel free to recommend / suggest other PRs that this depends on, such that it makes the back porting easier.

**Pull request merged**
