### PR TITLE
Apple Silicon macOS support

### PR DESCRIPTION
**Pull request by randall**
Allows builds on Apple Silicon to complete and run

### CODE REVIEW

**Comment by randall** [comment]
[approve ci centos]

**Comment by randall** [comment]
[approve ci centos]

**Comment by randall** [comment]
[approve ci fedora]
[approve ci debian]
[approve ci centos]

**Comment by randall** [comment]
[approve ci debian]
[approve ci fedora]

**Comment by ywkaras** [comment]
I am confused that there are changes to catch.hpp but no change to the version, how is that possible?

https://github.com/apache/trafficserver/blob/a884cc1432015be1376896ff1bcd83f8ca34594e/tests/include/catch.hpp#L2

**Comment by randall** [comment]
[ci approve centos]
[ci approve debian]

**Comment by randall** [comment]
[approve ci centos]

**Comment by randall** [comment]
[approve ci ubuntu]

**Comment by randall** [comment]
> I am confused that there are changes to catch.hpp but no change to the version, how is that possible?
> 
> https://github.com/apache/trafficserver/blob/a884cc1432015be1376896ff1bcd83f8ca34594e/tests/include/catch.hpp#L2

I manually back ported the apple-related changes from catch.

Upgrading catch to it's latest version is an effort of it's own: https://github.com/apache/trafficserver/pull/7464

**Comment by bryancall** [comment]
@randall Can you have a better explanation of what is happening?  We did a code review today and had questions.

**Comment by randall** [comment]
originally, I back ported some macOS specific changes from catch.hpp's head to get macOS on AS to build. With #7464 merged I no longer need that (and this PR has been fixed up to reflect that)

**Comment by randall** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
I think we need to revert this for now, from all branches.

**Pull request merged**
