### PR TITLE
h2spec: The endpoint MUST ignore any flags that is undefined.

### PR DESCRIPTION
**Pull request by zizhong**
Currently, `h2spec` reports the issue as follows.
```
Hypertext Transfer Protocol Version 2 (HTTP/2)
  4. HTTP Frames
    4.1. Frame Format
           [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
           [recv] SETTINGS Frame (length:12, flags:0x00, stream_id:0)
           [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
           [recv] WINDOW_UPDATE Frame (length:4, flags:0x00, stream_id:0)
           [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
           [send] Raw Data (0x000008061600000000)
           [send] Raw Data (0x0000000000000000)
           [recv] Connection closed
      × 2: Sends a frame with undefined flag
        -> The endpoint MUST ignore any flags that is undefined.
           Expected: PING frame
             Actual: Connection closed

```

With this patch,
```  4. HTTP Frames
    4.1. Frame Format
           [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
           [recv] SETTINGS Frame (length:12, flags:0x00, stream_id:0)
           [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
           [recv] WINDOW_UPDATE Frame (length:4, flags:0x00, stream_id:0)
           [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
           [send] Raw Data (0x000008061600000000)
           [send] Raw Data (0x0000000000000000)
           [recv] PING Frame (length:8, flags:0x01, stream_id:0)
      ✔ 2: Sends a frame with undefined flag

Finished in 0.0529 seconds
1 tests, 1 passed, 0 skipped, 0 failed

```

### CODE REVIEW

**Comment by zizhong** [comment]
@masaori335 @maskit Would you review this? It's a small fix for one of the issues reported by `h2spec`.

**Comment by maskit** [comment]
I think we can simply remove the check and `current_hdr.flags` should be untouched. Because setting zero should be done on sender side and we have to ignore them even if some undefined flags are set.

**Comment by zizhong** [comment]
@maskit You're right. Updated.

**Comment by masaori335** [comment]
[approve ci]

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/343/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/357/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/470/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1931/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/341/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2039/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/603/

**Comment by zizhong** [comment]
@maskit fixed.

**Comment by maskit** [comment]
Thanks.

**Comment by zwoop** [comment]
@maskit Do we want this for 7.1.0?

**Comment by maskit** [comment]
@zwoop I think it's nice to have. It matters only if some clients violate the protocol.

**Comment by zwoop** [comment]
This doesn't cherry-pick cleanly to 7.1.x branch. If we want this back ported, I think someone will have to make a separate PR.

**Comment by zizhong** [comment]
@zwoop okay, I'll create one.

**Pull request merged**
