### PR TITLE
Test bad request behavior

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Review by bneradt — DISMISSED** [review]

**Review by ezelkow1 — COMMENTED** [review]
LGTM however I have one comment. While running this test seemed to take an awful long time (timing here puts it at 2min). So I wonder if this is depending on some default timeout value in order to hit the bad cases? If so it may be worth it to just modify the timeouts for this test so it runs a lot quicker

**Comment by shinrich** [comment]
Shouldn't be very slow.  I don't think it is relying on timeouts.   Let me look at it again.

**Comment by shinrich** [comment]
@ezelkow1 I don't know why you are seeing slow test times.  I just ran the test again locally after doing the latest rebase and it took 8.5 seconds.

```
[shinrich@atslab02 tests]$ time sh ./autest.sh --ats-bin=/opt/ts-clean/bin --sandbox=/home/shinrich/skh -f good_request_after_bad
Python 3.6 or newer detected!
python3-dev/devel detected!
pipenv detected!
Using the pre-existing virtual environment.
Environment config finished. Running AuTest...
Running Test good_request_after_bad:......... Passed

Generating Report: --------------
Total of 1 test
  Unknown: 0
  Exception: 0
  Failed: 0
  Warning: 0
  Skipped: 0
  Passed: 1

real	0m8.500s
user	0m5.819s
sys	0m1.951s
```

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
@ezelkow1 Can you please re-review it

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
Here's my run in my ubuntu VM
`ezelko260@ubuntu tests (7884) $ time ./autest.sh --ats-bin=/opt/ats/bin -f good_request_after_bad
Python 3.6 or newer detected!
python3-dev/devel detected!
pipenv detected!
Using the pre-existing virtual environment.
Environment config finished. Running AuTest...
Running Test good_request_after_bad:.......... Passed

Generating Report: --------------
Total of 1 test
  Unknown: 0
  Exception: 0
  Failed: 0
  Warning: 0
  Skipped: 0
  Passed: 1

real	4m6.439s
user	0m4.009s
sys	0m2.573s
`

however on a centos7 box
`real	0m11.043s
user	0m4.436s
sys	0m2.547s
`

So just seems to be an oddity either with running in a vm or the latest ubuntu/environment/etc. So I think its probably fine and just write it off as an oddity of the environment I was trying to run it in

**Review by ezelkow1 — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
