### PR TITLE
QUIC: Insert client selected connection id into ctable

### LINKED ISSUE #3158: Second packet (0-RTT protected) creates a new QuicNetVC
with quant
```
[Feb 22 15:29:51.199] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [8eb648c35c23b8] received packet from 127.0.0.1:55440, size=1200
[Feb 22 15:29:51.199] Server {0xb0018000} DEBUG: <QUICNetVConnection.cc:79 (init)> (quic_net) [21232f94db4fdbd8] Connection ID 8eb648c35c23b8 has been changed to 21232f94db4fdbd8
[Feb 22 15:29:51.265] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [8eb648c35c23b8] received packet from 127.0.0.1:55440, size=97
[Feb 22 15:29:51.265] Server {0xb0018000} DEBUG: <QUICNetVConnection.cc:79 (init)> (quic_net) [5ccd9a9c32d5545e] Connection ID 8eb648c35c23b8 has been changed to 5ccd9a9c32d5545e
```

### PR DESCRIPTION
**Pull request by scw00**
This pr try to fix #3158

### CODE REVIEW

**Comment by maskit** [comment]
I found a similar issue while I was testing with mozquic. Let me confirm this tomorrow if it works for both of them, it looks reasonable though.

**Comment by maskit** [comment]
Tested with quant. The assert fails :-)

```
[Feb 23 09:47:16.140] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [8f5b8b95239aeabe] received packet from 127.0.0.1:62356, size=1200
[Feb 23 09:47:16.146] Server {0xb0018000} DEBUG: <QUICNetVConnection.cc:80 (init)> (quic_net) [4ecaad1c30a5a8fa] Connection ID 8f5b8b95239aeabe has been changed to 4ecaad1c30a5a8fa
[Feb 23 09:47:16.147] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [8f5b8b95239aeabe] received packet from 127.0.0.1:62356, size=97
[Feb 23 09:47:16.266] Server {0xb0008000} DEBUG: <QUICNextProtocolAccept.cc:53 (mainEvent)> (quic) [QUICNextProtocolAccept:mainEvent] event 202 netvc 0xa489a80
[Feb 23 09:47:16.271] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1297 (_switch_to_handshake_state)> (quic_net) [4ecaad1c30a5a8fa] Enter state_handshake
[Feb 23 09:47:16.272] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1196 (_dequeue_recv_packet)> (quic_net) [4ecaad1c30a5a8fa] type=INITIAL pkt_num=3633460980 size=1200
[Feb 23 09:47:16.272] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:343 (_transmit_packet)> (quic_net) [4ecaad1c30a5a8fa] Packet Number=3633460980 Type=VERSION_NEGOTIATION Size=17
[Feb 23 09:47:16.272] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1210 (_schedule_packet_write_ready)> (quic_net) [4ecaad1c30a5a8fa] Schedule QUIC_EVENT_PACKET_WRITE_READY event
[Feb 23 09:47:16.272] Server {0xb0008000} DEBUG: <QUICHandshake.cc:137 (start)> (quic_handshake) [4ecaad1c30a5a8fa] Version negotiation failed: babababa
[Feb 23 09:47:16.272] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1198 (_dequeue_recv_packet)> (quic_net) [4ecaad1c30a5a8fa] Failed to decrypt the packet
[Feb 23 09:47:16.272] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1132 (_handle_error)> (quic_net) [4ecaad1c30a5a8fa] QUICError: TRANSPORT (1), TLS_FATAL_ALERT_GENERATED (0x514)
[Feb 23 09:47:16.286] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1321 (_switch_to_closing_state)> (quic_net) [4ecaad1c30a5a8fa] Switching state without handshake completion
[Feb 23 09:47:16.286] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1326 (_switch_to_closing_state)> (quic_net) [4ecaad1c30a5a8fa] Reason was not provided
[Feb 23 09:47:16.286] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:405 (_transmit_frame)> (quic_net) [4ecaad1c30a5a8fa] Frame Type=CONNECTION_CLOSE Size=4
[Feb 23 09:47:16.287] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1337 (_switch_to_closing_state)> (quic_net) [4ecaad1c30a5a8fa] Enter state_connection_closing
[Feb 23 09:47:16.287] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1237 (_schedule_closing_timeout)> (quic_net) [4ecaad1c30a5a8fa] Schedule QUIC_EVENT_CLOSING_TIMEOUT event
[Feb 23 09:47:16.392] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [8f5b8b95239aeabe] received packet from 127.0.0.1:62356, size=1200
[Feb 23 09:47:16.392] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [8f5b8b95239aeabe] received packet from 127.0.0.1:62356, size=97
[Feb 23 09:47:16.411] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1196 (_dequeue_recv_packet)> (quic_net) [4ecaad1c30a5a8fa] type=INITIAL pkt_num=3633460982 size=1200
[Feb 23 09:47:16.411] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:617 (state_connection_closing)> (quic_net) [4ecaad1c30a5a8fa] Unexpected event: UNKNOWN (1)
Fatal: QUICNetVConnection.cc:618: failed assertion `false`
2018-02-23 09:47:16.411197+0900 traffic_server[67955:4512866] Fatal: QUICNetVConnection.cc:618: failed assertion `false`
Process 67955 stopped
* thread #7, name = '[ET_NET 4]', stop reason = signal SIGABRT
    frame #0: 0x00007fff5ae12e3e libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff5ae12e3e <+10>: jae    0x7fff5ae12e48            ; <+20>
    0x7fff5ae12e40 <+12>: movq   %rax, %rdi
    0x7fff5ae12e43 <+15>: jmp    0x7fff5ae0a0b8            ; cerror_nocancel
    0x7fff5ae12e48 <+20>: retq   
Target 0: (traffic_server) stopped.
```

**Comment by scw00** [comment]
Yeah, we reset the inactive timeout in _dequeue_recv_packet. it should be fix

**Comment by scw00** [comment]
I've remembered the old code insert the client's connection id in the table. Why do we remove that ?

**Comment by maskit** [comment]
> I've remembered the old code insert the client's connection id in the table. Why do we remove that ?

Did you find the commit that removed it? I thought the same thing but I couldn't find it.

**Comment by maskit** [comment]
I still see a crash here. It seems like idle timeout happens immediately and it confuses state transition.

```
[Feb 23 16:50:58.381] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [6ca36031affbc2ec] received packet from 127.0.0.1:53372, size=1200
[Feb 23 16:50:58.387] Server {0xb0018000} DEBUG: <QUICNetVConnection.cc:80 (init)> (quic_net) [9aa53c878277ffcf] Connection ID 6ca36031affbc2ec has been changed to 9aa53c878277ffcf
[Feb 23 16:50:58.388] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [6ca36031affbc2ec] received packet from 127.0.0.1:53372, size=97
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICNextProtocolAccept.cc:53 (mainEvent)> (quic) [QUICNextProtocolAccept:mainEvent] event 202 netvc 0x7fc4a80
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1316 (_switch_to_handshake_state)> (quic_net) [9aa53c878277ffcf] Enter state_handshake
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1210 (_dequeue_recv_packet)> (quic_net) [9aa53c878277ffcf] Unsupported version
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:343 (_transmit_packet)> (quic_net) [9aa53c878277ffcf] Packet Number=1318708007 Type=VERSION_NEGOTIATION Size=17
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1229 (_schedule_packet_write_ready)> (quic_net) [9aa53c878277ffcf] Schedule QUIC_EVENT_PACKET_WRITE_READY event
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICHandshake.cc:137 (start)> (quic_handshake) [9aa53c878277ffcf] Version negotiation failed: babababa
[Feb 23 16:50:58.451] Server {0xb0008000} DEBUG: <QUICPacketHandler.cc:76 (_send_packet)> (quic_sec) [6ca36031affbc2ec] send VERSION_NEGOTIATION packet to 127.0.0.1:53372, size=17
[Feb 23 16:50:58.480] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [6ca36031affbc2ec] received packet from 127.0.0.1:53372, size=1200
[Feb 23 16:50:58.544] Server {0xb0018000} DEBUG: <QUICPacketHandler.cc:170 (_recv_packet)> (quic_sec) [6ca36031affbc2ec] received packet from 127.0.0.1:53372, size=97
[Feb 23 16:50:58.558] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1372 (_switch_to_draining_state)> (quic_net) [9aa53c878277ffcf] Switching state without handshake completion
[Feb 23 16:50:58.558] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1375 (_switch_to_draining_state)> (quic_net) [9aa53c878277ffcf] Reason: Idle Timeout
[Feb 23 16:50:58.558] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1383 (_switch_to_draining_state)> (quic_net) [9aa53c878277ffcf] Enter state_connection_draining
[Feb 23 16:50:58.558] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1256 (_schedule_closing_timeout)> (quic_net) [9aa53c878277ffcf] Schedule QUIC_EVENT_CLOSING_TIMEOUT event
[Feb 23 16:50:58.558] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1210 (_dequeue_recv_packet)> (quic_net) [9aa53c878277ffcf] Unsupported version
[Feb 23 16:50:58.568] Server {0xb0008000} DEBUG: <QUICNetVConnection.cc:1214 (_dequeue_recv_packet)> (quic_net) [9aa53c878277ffcf] type=INITIAL pkt_num=1318708009 size=1200
[Feb 23 16:50:58.568] Server {0xb0008000} DEBUG: <QUICFrameDispatcher.cc:61 (receive_frames)> (quic_frame_handler) Received STREAM frame, size 549
[Feb 23 16:50:58.569] Server {0xb0008000} DEBUG: <QUICStream.cc:75 (init_flow_control_params)> (quic_flow_ctrl) [9aa53c878277ffcf] [0] [IDLE] [LOCAL] 0/2048
[Feb 23 16:50:58.569] Server {0xb0008000} DEBUG: <QUICStream.cc:77 (init_flow_control_params)> (quic_flow_ctrl) [9aa53c878277ffcf] [0] [IDLE] [REMOTE] 0/0
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICStream.cc:318 (recv)> (quic_flow_ctrl) [9aa53c878277ffcf] [0] [IDLE] [LOCAL] 545/2048
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICStream.cc:293 (_write_to_read_vio)> (quic_flow_ctrl) [9aa53c878277ffcf] [0] [IDLE] [LOCAL] 545/2593
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICHandshake.cc:264 (state_initial)> (quic_handshake) [9aa53c878277ffcf] VC_EVENT_READ_READY (100)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:316 (_print)> (quic_handshake) INITIAL_MAX_STREAM_DATA: 0x2000 (8192)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:316 (_print)> (quic_handshake) INITIAL_MAX_DATA: 0x4000 (16384)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:316 (_print)> (quic_handshake) INITIAL_MAX_STREAM_ID_BIDI: 0x1 (1)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:316 (_print)> (quic_handshake) IDLE_TIMEOUT: 0xa (10)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:312 (_print)> (quic_handshake) OMIT_CONNECTION_ID: (no value)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:316 (_print)> (quic_handshake) MAX_PACKET_SIZE: 0x7e4 (2020)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICTransportParameters.cc:316 (_print)> (quic_handshake) ACK_DELAY_EXPONENT: 0x3 (3)
[Feb 23 16:50:58.571] Server {0xb0008000} DEBUG: <QUICHandshake.cc:212 (set_transport_parameters)> (quic_handshake) [9aa53c878277ffcf] Version negotiation validated: babababa
Process 25012 stopped
* thread #7, name = '[ET_NET 4]', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001003d64a5 traffic_server`QUICTransportParameters::store(this=0x0000000000000000, buf="", len=0x0000000004d78340) const at QUICTransportParameters.cc:280
   277    uint8_t *p = buf;
   278  
   279    // Write QUIC versions
-> 280    this->_store(p, len);
   281    p += *len;
   282  
   283    // Write parameters
Target 0: (traffic_server) stopped.
(lldb) 
```

**Comment by maskit** [comment]
The event was actually not idle timeout but arrival of INITIAL packet (4925d9af45ee240e73f725acad384e966a4e5720).

Now version negotiation seems fine but it aborts during completing handshake.

**Pull request merged**
