### PR TITLE
Issue_1943: get rid of ticket_key_name tag from ssl_multicert

### PR DESCRIPTION
**Pull request by persiaAziz**
ticket_key_name is removed.
Ticket key should be set in records.config like
CONFIG proxy.config.ssl.server.ticket_key.filename STRING ssl_ticket.key

### CODE REVIEW

**Comment by persiaAziz** [comment]
needs to be backported  to 7.1.x

**Comment by masaori335** [comment]
Is there anybody who want to use different keys ( for TLS Session Tickets ) to different dest_ip or cert?
In other words, should we override `proxy.config.ssl.server.ticket_key.filename` by `ticket_key_name`?

**Comment by persiaAziz** [comment]
I think what we are going for is to have one default keyblock per machine. The current code generates random keyblock is nothing is specified. I think we should post this question on the user email list

**Comment by shinrich** [comment]
We have had the discussion about whether we need different ticket keys for different domains at several different ATS summits.  The general agreement was that differentiating by domain was a historical accident.  The current logic for separating based on domain never really quite worked.  

If someone needs this finer granularity,  adding it to the SNI-based configuration would make sense.  Doing the override in the remap rules would be too late.

**Comment by masaori335** [comment]
@shinrich Thanks for remind and summarize the discussion. I got it.
I agree adding it to SNI-based configuration if someone needs it.

**Pull request merged**
