### PR TITLE
TS-4789: Remove READ_WHILE_WRITER build condition.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/514/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/618/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/619/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/515/ for details.

**Comment by SolidWallOfCode** [comment]
Is this clang formatted? Otherwise, ship it.

**Comment by zwoop** [comment]
Fwiw, if the Linux build succeeds, it means clang-format succeeded.

**Pull request merged**
