### PR TITLE
[7.1.x] Hostdb synchronization & asserts

### PR DESCRIPTION
**Pull request by danm-netlify**
patch to back-port HostDB fixes and asserts into 7.1.x

### CODE REVIEW

**Comment by zwoop** [comment]
I've reverted the patch that causes this, can you try current 7.1.x branch without this patch please?

**Comment by danm-netlify** [comment]
I think I've tested that in the past and things were great! I can confirm as soon as I have some bandwidth...

**Comment by zwoop** [comment]
If you can verify that would be great. Unless there’s a strong argument for rolling forward with this, I’d prefer to do the least risky/invasive changes to the 7.1.x branch (for stability).

**Comment by danm-netlify** [comment]
agreed with your judgment here @zwoop

**Pull request closed without merging**
