### PR TITLE
Remove BisonHeaderToC++.sed

### PR DESCRIPTION
**Pull request by jablko**
We can do without it, and less is more?

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1650/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1545/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/82/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/214/ for details.

**Comment by SolidWallOfCode** [comment]
I'm not sure we can do without this. I know I had problems which lead me to do this which may be related to older versions of Bison. Note that it works for 3.0.4 compared to 2.7. My experience is that Bison versions on old operating systems we support tend to be very old. I will need to check this on older OS versions we use here at Y!.

Additionally the plan going forward for this is to remove all the parsing from TSConfig and have it depend on Lua.

**Comment by jablko** [comment]
> I'm not sure we can do without this. I know I had problems which lead me to do this which may be related to older versions of Bison. Note that it works for 3.0.4 compared to 2.7. My experience is that Bison versions on old operating systems we support tend to be very old. I will need to check this on older OS versions we use here at Y!.

Thanks for taking a look! It should work with Bison 2.7, just based on the GitHub CI jobs (e.g. the FreeBSD job uses 2.7 [1]). The CentOS 6 machine uses 2.4 [2] -- but we don't run that for pull requests, I think.

I think the important difference between TsConfigGrammar.h and TsConfigGrammar.hpp is that TsConfigGrammar.h contains yyscan_t (the first tsconfigparse() parameter) and TsConfigGrammar.hpp doesn't -- but replacing `%parse-param { yyscan_t lexer }` with `%parse-param { void *lexer }` has the same effect?

[1] https://ci.trafficserver.apache.org/files/BuildMachines/FreeBSD10
[2] https://ci.trafficserver.apache.org/files/BuildMachines/CentOS6

> Additionally the plan going forward for this is to remove all the parsing from TSConfig and have it depend on Lua.

Nice!

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/RAT-github/5/ for details.

**Comment by zwoop** [comment]
Lets re-run this with the new Github builders: [approve ci]

**Comment by atsci** [comment]
clang-format check *successful*! See https://ci.trafficserver.apache.org/job/clang-format-github/9/ for details.

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/22/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/135/

**Comment by atsci** [comment]
FreeBSD11 build *failed*! https://ci.trafficserver.apache.org/job/freebsd-github/1704/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1599/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/267/

**Comment by zwoop** [comment]
Note that it has to succeed on CentOS6, which is indeed running 

```
[root@centos6 ~]# bison  --version
bison (GNU Bison) 2.4.1
```

**Comment by PSUdaemon** [comment]
@jablko can you rebase this?

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
Still feels like we  have to support the Bison that comes with CentOS6.

**Comment by bryancall** [comment]
Ran a build on this for Centos 6 to see if there is an issue.

**Comment by zwoop** [comment]
Part of the "trickiness" here is that the file is also checked into git, so many cases, we don't need bison at all. But it doesn't seem to be particularly deterministic.

**Comment by bryancall** [comment]
There hasn't been an update on this PR for over 60 days, so I am closing it for now.  Feel free to reopen the PR when you have updated it.

**Pull request closed without merging**
