### PR TITLE
Issue #1443 - Fix early or duplicate 404 error handling

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by zwoop** [comment]
What are the symptoms of this?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1544/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1437/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/109/ for details.

**Comment by shinrich** [comment]
An assert triggers.  A stack trace in the issue description.

https://github.com/apache/trafficserver/issues/1443

**Comment by SolidWallOfCode** [comment]
I looked at this as well and it definitely looks like it's an artifact of a remap plugin setting the transaction to be an error. You can see that this happens in a switch statement where `t_state.next_action` was `SM_ACTION_REMAP_REQUEST` on entry yet is `SM_ACTION_SEND_ERROR_CACHE_NOOP`. This could only have been updated via `do_remap_request()` and presumably via a remap plugin as `RemapProcessor` doesn't update that member. It also seems reasonable to check if a plugin has error'd out the transaction and give up on further transaction processing at that point.

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/86/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1654/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1550/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/218/ for details.

**Pull request merged**
