### PR TITLE
TS-4898: Switch proxy.config.hostdb.timeout from minutes to seconds.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by bryancall** [comment]
👍 - Looks good

**Comment by jpeach** [comment]
Note that this is an incompatible change. Anyone who uses this would now find their timeouts suddenly a lot shorter.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/876/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/773/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/878/ for details.

**Comment by PSUdaemon** [comment]
This is getting backported to 7.0.x?

**Pull request merged**
