### PR TITLE
YTS-614: Avoid crash due to error during POST request transform.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
If the user agent has an error during a POST transform ATS can either crash (by trying to write an error response to a dead user agent) or leave the request in an undead state waiting on events that won't happen.

(cherry picked from commit fad1f6ed353d332ce505306f462e9f90be00a6ad)

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1480/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1373/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1481/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1374/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/44/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/45/ for details.

**Comment by zwoop** [comment]
@SolidWallOfCode Is this something you feel comfortable with, and should be a 7.1.x back port?

**Comment by SolidWallOfCode** [comment]
We've been running this in production for months and it fixed a series of crashes in ATS for us. I think it should probably be backported to 7.1, Y! will be putting it in our 7.1 fork.

**Pull request merged**
