### PR TITLE
Test: Add validation for VIA test to not run if curl doesn't HTTP/2

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
The VIA test is failing on older systems because it depends on `curl` providing HTTP/2 connectivity. This disables the test if that's not true.

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/263/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/277/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/259/

**Comment by zwoop** [comment]
@SolidWallOfCode Please add Labels, Assignee, Reviewers and Milestone... I make a habit of doing so immediately when I file the PR.

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/388/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1958/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1850/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/521/

**Comment by SolidWallOfCode** [comment]
How did I break the clang analyzer by changing only python test code?

**Comment by zwoop** [comment]
You didn't, it's broken until Bryan or Phil fixes it :).

**Pull request merged**
