### PR TITLE
TS-4652: ASAN issue in logging with gcc 6.1.1

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/315/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/421/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/422/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/316/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/423/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/317/ for details.

**Comment by jpeach** [comment]
This looks alright to me. The one part I'm a little concerned about is the changes to the dirent allocation, but I don't think there will be any problems with too-long filenames in practice.

**Comment by bryancall** [comment]
The length of the file is 256 in the dirent structure.  All the OSes we support fall within that size.

**Comment by bryancall** [comment]
Here is a good list on the limits of filename sizes:
https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

**Pull request merged**
