### PR TITLE
ATS Lua could support shared dictionary just like nginx

### PR DESCRIPTION
**Pull request by scw00**
Notes:
-------

  These codes is based on nginx and openresty(by agentzh) 's codes.

config:
-----
```
#The first param must be the script path (or codes), the second could be state. 
regex_map http://www.scw.com http://www.scw.com @plugin=tslua.so @pparam=/root/test/ts_lua/example/test.lua @pparam=states:10 @pparam=shared_zone:scw=30000
```

lua code 
------
```
local scw = ts.shared.scw

function send_response()
		local data = scw:get("scw")
		ts.debug("scw" .. data) // debug output: "hello"
end

function do_remap()
		ts.debug("scw    create  \n\n")
		scw:set("scw", "hello")
		ts.hook(TS_LUA_HOOK_SEND_RESPONSE_HDR, send_response)

    return 0
end
```

### CODE REVIEW

**Comment by shukitchan** [comment]
will review in the next couple days. 
In this PR, can you also please update the document here ? https://github.com/apache/trafficserver/blob/master/doc/admin-guide/plugins/ts_lua.en.rst
Thanks.

**Comment by scw00** [comment]
updated！

**Comment by zwoop** [comment]
@shukitchan Ping? :)

**Comment by shukitchan** [comment]
yeah. i am still alive. just not feeling well for a few days. will post somethings here soon.

**Comment by shukitchan** [comment]
I have quite a few opinions here - 

1) it seems to be not a complete implementation? It seems that there are a lot of functions not yet implemented for the dictionary. I would suggest to break down the pull requests into much smaller pieces. e.g. Enough things to have get/set working. And then send in changes to add the other functions in a later pull request. That's easier for review. 
2) The document does not seem to include all the functions you are currently exposing. 
3) TSRemapNewInstance() is run for each line of the rules. And you move the lua state initialization into that. So if I have many remap rules using the plugin, what would happen? We will rerun the initialization many times?
4) We are using getopt_long() to get some inputs for the plugin. I think we should continue to use that. That helps us to keep the format of the parameters to be the same. 
5) The implementation seems to be overly complicated with lots of utilities such as queue, redblack tree, crc, slab(memory pool), etc. It seems to be overly complicated for just get/set. I understand that you might want such an implementation if you want to have a feature parity with nginx. But perhaps we can again break this checkin into smaller pieces and gradually add on more stuff for the extra functionality?
6) why is this only for remap plugin? why can't it be available for global plugin as well?
7) In general, I have doubt on these kinds of addition to the plugin. Would we be able to achieve similar results by packaging this as a module and thus the script can choose whether to include that or not? Are there open source lua module available to do  similar things?

**Comment by scw00** [comment]
I'll try to pack it as a lua package .

**Comment by shukitchan** [comment]
if you want to explore doing this as a lua module, i am not too sure if we should include this in the ats repository. 

I certainly would want you to open source that. But i don't know if this repository is the right home for it.

**Pull request closed without merging**
