### PR TITLE
TS-4883: Fix Thread::start call in EventProcessor::start

### PR DESCRIPTION
**Pull request by mgosui**
[TS-4883](https://issues.apache.org/jira/browse/TS-4883)

### CODE REVIEW

**Comment by masaori335** [comment]
Looks good to me

**Comment by masaori335** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/843/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/738/ for details.

**Comment by jpeach** [comment]
@PSUdaemon @masaori335 Let's get another Jira open to remove or refactor the thread startup options so that this kind of error can't happen. It looks to me like the thread function arguments are not ever used.

**Pull request merged**
