### PR TITLE
Coverity: Several Overflowed integer argument fixes

### PR DESCRIPTION
**Pull request by brbzull0**
[CID-1550434](https://scan6.scan.coverity.com/#/project-view/58063/10191?selectedIssue=1550434)
[CID-1550423](https://scan6.scan.coverity.com/#/project-view/58063/10191?selectedIssue=1550423)
[CID-1550429](https://scan6.scan.coverity.com/#/project-view/58063/10191?selectedIssue=1550429)

### CODE REVIEW

**Comment by brbzull0** [comment]
osx failing. Noted.

**Comment by traeak** [comment]
[approve ci osx]

**Comment by traeak** [comment]
[approve ci autest 1]

**Comment by traeak** [comment]
[approve ci autest 3]

**Comment by brbzull0** [comment]
[approve ci autest 3]

**Comment by traeak** [comment]
[approve ci clang-analyzer]

**Comment by traeak** [comment]
[approve ci autest 1]

**Comment by ezelkow1** [comment]
[approve ci freebsd]

**Comment by brbzull0** [comment]
[approve ci clang-analyzer]

**Review by cmcfarlen — APPROVED** [review]

**Pull request merged**
