### PR TITLE
TS-4240: fix coredump issues with esi plugin

### PR DESCRIPTION
**Pull request by shukitchan**
@jpeach @zwoop pls take a look and review

### CODE REVIEW

**Comment by zwoop** [comment]
@shukitchan  Can you address Jame's comments, and then commit.

**Comment by shukitchan** [comment]
@jpeach i thought that it was safe, too. Till i see the core dump reported in the jira. i am just being extra safe in this PR. What do you think?

**Comment by jpeach** [comment]
I'm -1 on this unless we know it actually fixes the problem. Looking at the [TS-4240](https://issues.apache.org/jira/browse/TS-4240), my guess is that ``data[i]`` is negative, so casting to a wider unsigned type gives you a very large index. The right fix would be to cast to ``uint8_t``.

**Comment by shukitchan** [comment]
@jpeach patch is updated. please take a look. 
I will test more tonight and if it is good, i will squash the commit before merge.

**Comment by shukitchan** [comment]
I can now reproduce the problem and the fix is working.
@jpeach pls take a look as well

**Comment by jpeach** [comment]
@shukitchan does it make sense to add something to the esi unit tests for this?

**Comment by shukitchan** [comment]
test added. @jpeach pls take a look.
again i will squash the commits before merging. Thanks.

**Comment by jpeach** [comment]
Ship it!

**Pull request merged**
