### PR TITLE
[TS-3714]: Summary of changes below:

### PR DESCRIPTION
**Pull request by sudheerv**
a) Issue a SSL_read right after SSL handshake to ensure
data already in the SSL buffers is not lost.
b) Add vc to net thread's read_ready_list immediately after
accept, to ensure data already in the socket buffers is not lost.
c) Add a timer for SSL handshake with default to no timer (as today).
d) Fix a bunch of error cases to correctly release resources.

### CODE REVIEW

**Comment by shinrich** [comment]
The timeout logic looks good.  And I agree with your comment to Brian that it could probably moved into a separate commit.  Not a lot of code, but this is all tricky logic, so separation might be worth it.

The main thing here seems to be the logic to ensure that any data sent along with the last handshake record is processed immediately.  What you have seems to do the trick.  

However, I wonder if we could get by with fewer additional mechanisms (buffers and bits) by using the trigger bit?  When the client session starts (all them them, Spdy, H2, and Http), we set read.vio.triggered to true.  The first non-zero do_io_read will add the vc to the read_ready_list and set read_vio.enabled to true.  The next event poll will have a timeout of 0 and return immediately.  The new VC will be processed when the read_ready_list is walked.   Since enabled and triggered will be true a READ_READY event will be sent.  At least that is my reading of things.

The downside is  that in many cases you would be issuing a useless READ_READY at the start of each session.  Perhaps one could do a pending check before setting the trigger bit.

Also due to the nesting of SPDY/H2 and Http clients, you might set the trigger bit unnecessarily on the nested Http clients.  Any lingering SSL data would have been dealt with in the SPDY/H2 client session.

**Comment by sudheerv** [comment]
The problem with that approach is that, if there was an EOS on the fd right after handshake (which I noticed seems to happen quite a bit), it is not caught immediately. I'm guessing it's coz, openSSL reuses the SSL context, a subsequent do_io_read on that ssl object (fd) seems to simply stall rather than read or return immediately with error. Also, fwiw, I did try playing with the triggered bit (even force adding the vc into the read_ready_list directly and calling net_read_io directly as well), but, somehow those didn't help. There are a bunch of disable reads enroute to the acceptor session, don't know if any of them are messing up with the read ready list.

**Comment by shinrich** [comment]
Did you do try on master?  Do you have a nice test program that sends data along with the last handshake message?  

I'm trying to get the stall to happen on master and failing.  I added debugs to show that there was extra information in the HandshakeBuffer, but I'm not entirely sure that is exercising what you are seeing. 

For the EOS case, is that a handshake followed immediately by an EOS?  Or is there data in the last handshake record and then an EOS?

**Comment by sudheerv** [comment]
No - I don't have the setup for that. I've tested it on y! prod 5.0.x.

For EOS, it's both.

**Comment by shinrich** [comment]
We also need to test on 5.3 or 6.0.  With 5.2 the SSL handshake logic changed to use a mem bio instead of the socket directly.  We will want to see if the issue is the same there.

**Comment by sudheerv** [comment]
The patch handles both cases - non-zero bytes received in SSL_read immediately after handshake and no bytes. Unless there are specific comments, I'm going to merge this in a little while.

**Comment by shinrich** [comment]
Sorry got distracted with other things today.  Did you get a chance to test against 5.3/6.0/master?  Were they showing the same problems without the patch?  I'm working on getting a little test program together to exercise the handshake/data tailgate scenario.  It looks like you need to have a session reuse scenario to get that case to happen.

**Pull request closed without merging**
