### PR TITLE
Changed some of the HTTP/2 enums to enum classes and found a bug

### PR DESCRIPTION
**Pull request by bryancall**
found a bug in is_client_state_writeable()

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/110/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/124/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/107/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1806/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1697/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/236/

**Comment by zwoop** [comment]
Moved to 7.1.0, I think this is a good patch + good fix!

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/368/

**Comment by maskit** [comment]
@bryancall Looks good to me, but I don't see which part was the bug.

**Comment by zwoop** [comment]
Cherry picked to 7.1.x

**Pull request merged**
