### PR TITLE
Clear server_entry in case of ERROR as well as NO_ACTIVITY_TIMEOUT

### PR DESCRIPTION
**Pull request by shinrich**
Related to the fix in PR #3033.  We had another crash recently where the failed server connection kept sending events that landed on the static error tunnel.  In addition to cleaning up on the NO_ACTIVITY case, we should clean up in the VC_ERROR case.

### CODE REVIEW

**Comment by zwoop** [comment]
Is this a candidate for v7.1.4 ?

**Comment by zwoop** [comment]
[approve ci clang-format]

**Comment by shinrich** [comment]
Forgot about this one.  Just tracked down another spate of errors that were solved with this fix.  Rebased against the current master.

**Comment by zwoop** [comment]
@shinrich This didn't cherry-pick cleanly to 7.1.x either. Would you mind making a PR against the 7.1.x branch please?

**Pull request merged**
