### PR TITLE
TS-4655: Remove SessionAccept pointer from SSLNetVConnection.

### PR DESCRIPTION
**Pull request by jpeach**
SSLNetVConnection never uses the SessionAccept pointer, so remove
it and the associated setter and getter. Tidy up the SSLNetVConnection
formatting a little.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/424/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/318/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/425/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/319/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
