### PR TITLE
gracefully handle TSReleaseAsserts in statichit and generator plugins

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Review by zwoop — DISMISSED** [review]
Love it, but lets get another pair of eyeballs on it.

**Review by ezelkow1 — COMMENTED** [review]
Looks good but do we also need a return check on the changes in statichit since that changed the return of WriteResponseHeader?

**Comment by randall** [comment]
> Looks good but do we also need a return check on the changes in statichit since that changed the return of WriteResponseHeader?

Good catch! I should've looked at statichit more closely.

**Review by ezelkow1 — APPROVED** [review]

**Review by bryancall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
