### PR TITLE
TS-3418: Second hash ring for consistently hashed parent selection

### PR DESCRIPTION
**Pull request by jrushf1239k**
This pull request is to add an optional secondary hash ring to parent selection and is based upon feedback from James Peach regarding pull request 321.  This branch only has the secondary hash ring feature and the refactor of Parent Selection to make it possible to add a secondary hash ring.

All unit and parent selection regression tests have been checked and testing has been completed in a QA environment.

### CODE REVIEW

**Comment by jpeach** [comment]
Hi John. First, let's clean up the commit history on this branch.

- please squash the "clang format" and "updated comments" commits into their respective previous commits.
- for each commit, the subject should be a short description like TS-3418: what this commit does"
- for each commit, add a longer description in the commit message for future generations. What are all the changes in this commit? Why are they necessary? Try to include enough description for someone to understand what is going on in the commit.

**Comment by jrushf1239k** [comment]
Hi James,

I've squashed several commits and cleaned up the history, I'll be more descriptive in the future.  Also, I found that I had left in some code for the multi-site origin feature.  I've removed this code and the branch only includes the refactor for the secondary hash ring and it's regression tests.  All re-testing in my QA environment and regression tests are good.

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by jpeach** [comment]
We are almost there. To get the commits in the right order we can squash commit 3 into commit 1 and remove the accidental changes to ```lib/tsconfig/TsConfigSyntax.c```. On your branch is would be something like this:

    $ git fetch --all
    $ git rebase -i origin/master
    $ # in the interactive rebase move commit 3 into 2nd place and change 'pick' to 'squash'

Now the commits are in the right order and squashed. We can get rid of the accidental changes now:

    $ git rebase -i origin/master
    $ # in the interactive rebase change 'pick' to 'edit' for commit 1
    $ # now you are paused in the middle of the rebase
    $ git show lib/tsconfig/TsConfigSyntax.c | patch -p1 -R
    $ git commit -a --amend
    $ git rebase --continue

And force push the result.

**Comment by jrushf1239k** [comment]
Done, Thanks for the git help!

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by jpeach** [comment]
Thanks @jrushf1239k. Now that we have a pretty clean commit on this branch, I think that it is OK to make any additional changes in new commits.

I think the big thing that I'm concerned about in this patch is the ownership model. AFAICT, the ParentRecord object owns a ParentSelectionStrategy (I don't see where this is deleted), but the ParentSelectionStrategy is passed and actually owns the pointer to its own parent which it deletes in its destructor. We should try to avoid parricide.

A better pattern, if you can manage it, is to pass in all the information that the ParentSelectionStrategy needs, rather than setting member variables. So in the strategy construction, just keep what you need from the ParentRecord (probably pointers to the pRecord list). It looks like you started down this path in ParentConsistentHash, so maybe you can take that further.

I think you can remove ParentRecord::round_robin because it is implied by the strategy. We would just have additional strategies ParentStrictRoundRobin, ParentHashRoundRobin and ParentNoRoundRobin. It's fine for them all to live in ParentRoundRobin.{c,hh}.

I think you can remove ParentResult::line_number.

ParentRecord::lookup_strategy should be named selection_strategy to match ParentSelectionStrategy.

I don't think you need ParentSelectionStrategy::numParents() since it is only ever used for assertions. Try to just eliminate that.

I think we can find better names for the ParentSelectionStrategy API. lookupParent should be selectParent, since it is making a selection from a match. I was going to suggest that recordRetrySuccess should be called markParentUp for symmetry, but then I noticed that its implementation is the same for both strategies. Can we just remove it?

In email I mentioned removing extApiRecord. I see now that you have preserved that from the current code, so don't worry about trying to remove it.

In the original code, ParentRecord had a FindParent() member function. I would prefer to keep that rather than having the caller traverse ParentRecord::lookup_strategy itself. It just hides the implementation a bit more nicely.

Note that FindParent() used to take a ParentConfigParams. Since the lookup policy is now spread over the ParentRecord and the the config_params structures, it would be cleaner to condense all this into a ParentSelectionPolicy object that is passed into FindParent. I think this would help you separate the ParentSelectionStrategy from owning a ParentRecord pointer too, since state that the strategy looks at would now be passed in.

**Comment by PSUdaemon** [comment]
Hey @jpeach, where do you feel this sits? @zwoop is branching 6.1.x soon and wondering if this can make it in or we should push it back to 6.2.x.

thanks.

**Comment by jpeach** [comment]
I haven't had time to review again,

**Comment by jpeach** [comment]
> Note that FindParent() used to take a ParentConfigParams. Since the lookup policy is now spread
> over the ParentRecord and the the config_params structures, it would be cleaner to condense all
> this into a ParentSelectionPolicy object that is passed into FindParent. I think this would help you
> separate the ParentSelectionStrategy from owning a ParentRecord pointer too, since state that the
> strategy looks at would now be passed in.

Basically this boils down to

1. rename ``config_params`` to ``ParentSelectionPolicy``.
2. The ownership of the ``ParentSelectionPolicy`` is ambiguous since all ``ParentSelectionStrategy`` object have a pointer to it, but it is actually only owned by the ``ParentConfigParams``. So keep it in ``ParentConfigParams`` (it doesn't need to me malloc'd), and pass it to ``ParentSelectionStrategy`` methods as an argument. ``ParentConfigParams `` now won't implement the ``ParentSelectionStrategy`1 interface, but it doesn't need to.

```
    class ParentConfigParams : public ConfigInfo
    {
          // implementation of functions from ParentSelectionStrategy.
         void selectParent(bool firstCall, ParentResult *result, RequestData *rdata) {
            return result->rec->selection_strategy->selectParent(policy, firstCall, result, rdata);
         }

    private:
      ParentSelectionPolicy policy;
    };
```

**Comment by jrushf1239k** [comment]
James,

I've made changes based upon your suggestions.  Please review....

**Comment by jrushf1239k** [comment]
Fixed function declarations and removed url_len argument from the consistent hash lookup functions.

**Pull request closed without merging**
