### PR TITLE
Runroot: pass runroot down from manager and error message update

### PR DESCRIPTION
**Pull request by chitianhao**
1. Previously, when `traffic_manager` uses runroot, the option is not passed down correctly to `traffic_server` in some cases.

2. Some better error messages support is included

3. Tests are also updated

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by chitianhao** [comment]
Will do. @dragon512

**Comment by dragon512** [comment]
[approve ci]

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
