### PR TITLE
Add <ts/debug.h> with debug / Test Mode types, constants, and use in ink_assert.h .

### PR DESCRIPTION
**Pull request by ywkaras**
This is a work in progress.

### CODE REVIEW

**Comment by bryancall** [comment]
@ywkaras What does this do for us?  Looks like the code is more complex now.

**Comment by ywkaras** [comment]
@SolidWallOfCode thought it would be good to reduce the use of preprocessor-based conditional compilation.

**Comment by bryancall** [comment]
@ywkaras What benefit does this have?  There is added complexity of the code, so there should be a benefit to offset this.

**Comment by ywkaras** [comment]
I did it because @SolidWallOfCode asked me to.  I think it's no worse than using #if directives.

**Comment by ywkaras** [comment]
Committer fight!   http://www.relatably.com/m/img/eating-popcorn-memes/55186417.jpg

**Comment by zwoop** [comment]
Looks to me like there are a lot *more* compile conditionals now?

**Comment by ywkaras** [comment]
Is it just a coincidence that @SolidWallOfCode left town right after he asked me to make this pull request?

**Comment by SolidWallOfCode** [comment]
I was hoping to (1) have you talk to me before putting up the PR and (2) reduce the number of pre-processor macros.  This is still exploratory stuff, certainly not ready for a PR yet.

The goal would be, if possible. to have the `DEBUG` and clang analyzer checks in only one `#if` and have everything use C++ mechanisms and dead code elimination. For instance, `ts_assert` would be
```
if (DebugIsEnabled) {
  assert(...);
}
```
Relying on the compiler to remove the entire clause if the `constexpr` `DebugIsEnabled` is `false`.

**Pull request closed without merging**
