### PR TITLE
Removes significant, but not all, code in Rollbacks

### PR DESCRIPTION
**Pull request by zwoop**
The remaining code is there, because the Rollback object also doubled as
the general structure holding all configurations. Granted, maybe we should
rename this, but that can be a separate PR if we want this.

I intentionally made this a large number of commits, for two reasons:

1. Easier to review / debug / test
2. If there turns out to be a problem, hopefully we can easier identify the commit breaking things

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Going to have to redo this, something went wrong on the first commit in this list, so going to make a new PR and try again. The fun never ends!

**Pull request closed without merging**
