### PR TITLE
XDebug: Always append to the X- header, rather than prepend

### PR DESCRIPTION
**Pull request by zwoop**
Related to #6332, and Miles' proposal to change our behavior.

### CODE REVIEW

**Comment by randall** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by mlibbey** [comment]
Think we need
- modify docs too (doc/admin-guide/plugins/xdebug.en.rst) to note the change in behavior.
- add this to the release notes.

**Comment by zwoop** [comment]
@mlibbey  Yep, I will update the docs, and this will definitely need to go into the Upgrade To release notes. The 9.0.x as so far behind on everything, once the dust settles, my plan is to go through *every* PR for 9.0.x, and update the release notes properly.

I've already marked this one as "incompatible", and I'm hoping others do that as well. That label is a really useful tool for the RM, to know about an incompatible change going into a release.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
