### PR TITLE
Fix HTTP/2 session receive window handling for small sizes (#9117)

### LINKED ISSUE #9115: Improper HTTP/2 enforcement of a reduced session window size
While adding test coverage for #9085, I noticed that we have issues handling multiplexed HTTP/2 DATA frames on the client side as we handle translating the transactions toward the origin. I forced the client to send DATA continuation frames by reducing the stream window to 10 bytes. The client (Proxy Verifier) multiplexes three transactions per this window. The client and ATS handle this fine. Toward the origin, I notice that ATS sends the first request headers and the first 10 byte body as a chunked body. This 10 byte body corresponds to the first DATA frame content. The problem is that ATS does not continue to stream this first request until chunk termination. Instead, ATS then sends the headers for the second request. This is, naturally, not acceptable for HTTP/1 since there is no concept of multiplexing like that for HTTP/1.

I have an AuTest that reproduces this. I'll attach to this issue:

1. The AuTest.
2. The Proxy Verifier replay file used by the test to generate the HTTP traffic.
3. A tcpdump I captured while running the test. Port 2007 is client-side HTTP/2, port 2002 is the client side HTTP/1.1 traffic.
4. A TLS keylog file to decrypt the tcpdump on the client side (the origin side is plaintext HTTP/1.1).

Looking at the pcap file:
* Note that the transaction has an initial GET request for path `/zero-request`. Ignore this.
* Frame 55 contains the headers for the first relevant POST request. Wireshark doesn't parse it because the stream is ultimately corrupted per the bug recorded in this issue.
* Frame 57 contains the 10 byte chunk for the first request. It correctly has no chunk terminator because further bytes should be forthcoming.
* Frame 61 incorrectly contains the header bytes for the second POST request. This is malformed HTTP/1.1 as an HTTP/1.1 parser would be expecting more chunk bytes, not header bytes of another request.

[tls_session_keys.txt](https://github.com/apache/trafficserver/files/9679637/tls_session_keys.txt)
[h2_to_h1_malformed.pcap.gz](https://github.com/apache/trafficserver/files/9679643/h2_to_h1_malformed.pcap.gz)
[http2_flow_control.replay.yaml.gz](https://github.com/apache/trafficserver/files/9679648/http2_flow_control.replay.yaml.gz)
[http2_flow_control.test.py.gz](https://github.com/apache/trafficserver/files/9679649/http2_flow_control.test.py.gz)

### PR DESCRIPTION
**Pull request by maskit**
Back porting  #9117 to 9.2.x. I had to make `server_rwnd_is_shrinking` public member to resolve conflicts.

----

This fixes the way we handle session window sizes if the user configures proxy.config.http2.initial_window_size_in to be smaller than the HTTP/2 protocol's default value of 65,535. For streams, we can communicate to the client a smaller stream size via a SETTINGS frame, but not so for smaller session window sizes. The way HTTP/2 hosts are expected to reduce their receive session window size is by receiving DATA frames without replying with WINDOW_UPDATE frames until the window falls to the desired value. ATS already handled this latter behavior correctly (letting the window size fall without sending WINDOW_UPDATE frames for the session until it reached the desired smaller value). However, it incorrectly reported an error and sent a GOAWAY frame when the user sent DATA content above the reduced window size before ATS gave the client a chance to reduce it via DATA frames. This fixes the receive session window check to allow for a shrinking session window.

Fixes #9115

(cherry picked from commit 4fcb9b47dbe549901141ebeedd09f389f55be6e1)

 Conflicts:
	proxy/http2/Http2ConnectionState.cc

### CODE REVIEW

**Review by bneradt — APPROVED** [review]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
Looks like the s3_auth test needs to be updated in 9.2.x:

```
Generating Report: --------------
1 Tests were skipped:
--------------------------------------------------------------------------------
 Test "conn_timeout" Skipped
    File: conn_timeout.test.py
    Directory: /home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/timeout
  Reason: Test requires privilege

 Test: s3_auth_config: Exception
    File: s3_auth_config.test.py
    Directory: /home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/pluginTest/s3_auth
     Reason: Traceback (most recent call last):
       File "/home/jenkins/.local/share/virtualenvs/tests-iiJvYDvR/lib/python3.8/site-packages/autest/core/runtesttask.py", line 34, in __call__
         tl = self.__logic.Run(self.__test)
       File "/home/jenkins/.local/share/virtualenvs/tests-iiJvYDvR/lib/python3.8/site-packages/autest/runlogic/runlogic.py", line 18, in Run
         if not tmp.Start(obj):
       File "/home/jenkins/.local/share/virtualenvs/tests-iiJvYDvR/lib/python3.8/site-packages/autest/runlogic/test.py", line 90, in Start
         loadTest(self.__test)
       File "/home/jenkins/.local/share/virtualenvs/tests-iiJvYDvR/lib/python3.8/site-packages/autest/core/test.py", line 292, in loadTest
         execFile(fileName, locals, locals)
       File "/home/jenkins/.local/share/virtualenvs/tests-iiJvYDvR/lib/python3.8/site-packages/autest/common/execfile.py", line 16, in execFile
         exec(safeCompile(f.read(), fname), globals, locals)
       File "/home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/pluginTest/s3_auth/s3_auth_config.test.py", line 65, in <module>
         ts.Disk.traffic_out.Content = "gold/s3_auth_parsing_ts.gold"
     AttributeError: 'Disk' object has no attribute 'traffic_out'
```

I can create a 9.2.x PR to fix that. Then hopefully the tests should work better.

**Review by zwoop — APPROVED** [review]

**Pull request merged**
