### PR TITLE
Add -lpthreads to traffic_cache_tool link.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by zwoop** [comment]
Hmmm, why isn't the CI builds failing without this? Which platform(s) is this needed on ?

**Comment by ywkaras** [comment]
For the CentOS CI build, when I look at the console output, -lpthread appears twice in the traffic_cache_tool link.  Hmmmm....

**Comment by ywkaras** [comment]
I added a hack work-around for this to my build configure scrpt ( https://gist.github.com/ywkaras/9eaaac5f110eece77b4528122035a44a ).  I'll let this sit for a while until someone else sees it or we get sick of it.

**Comment by ywkaras** [comment]
I install a newer RHEL7 VM image and oh lawdy trafficserver's HEALED so closing this I guess.

**Pull request closed without merging**
