### PR TITLE
url_sig: fix memory leak with urlParse and pristine flag

### PR DESCRIPTION
**Pull request by traeak**
This fixes a memory leak in url_sig when the pristine flag is set in the section of code that calls urlParse.  This PR further cleans up error messages to help with identifying malformed client requests.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci clang-analyzer]

**Comment by jrushford** [comment]
[approve ci clang]

**Comment by traeak** [comment]
[approve ci]

**Comment by zwoop** [comment]
Is this a 9.0.x candidate?

**Comment by traeak** [comment]
This one would have to include PR https://github.com/apache/trafficserver/pull/5219 as well.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
This has merge conflicts, and we'll need a new 8.1.x PR. Also, feel free to recommend / suggest other PRs that this depends on, such that it makes the back porting easier.

**Pull request merged**
