### PR TITLE
Add basic files to use Catch for unit testing

### PR DESCRIPTION
**Pull request by dragon512**
This is a pre-requirement for getting in the string_view.hpp file for c++17 basic_string_view support. I have this ready and works with c++11. I have tests for the basic_string_view class that need us to get the basic catch infra added. ( ie the catch.hpp header and a file to act as the main exe )

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
How would I integrate the Catch based unit tests from #2254 in to this framework?

**Comment by zwoop** [comment]
Since we did the same for the gtest proposal, I think we should make sure there's consensus on the mailing list that this is the direction we want to take, before landing this. I'm definitely not opposed to it, but we should all agree here such that we get one framework for unit testing, and not <n>.

**Comment by dragon512** [comment]
@SolidWallOfCode 

The easy way would be make a file under tests/unit_tests/<somedir>/<you testfile>.cpp

Add it to the Makefile.am to be added to unit_test program

your test file would look something like:


```
#include "catch.hpp"
#include "string_view.hpp"

TEST_CASE("constructor calls", "[string_view]") {
	

	SECTION("Literal look for NULL") {
		ts::string_view sv("hello");

		REQUIRE(sv.size() == 5);
		REQUIRE(sv.length() == 5);
		REQUIRE(sv.empty() == false);
		REQUIRE(sv == "hello");
		
	}
...

```

This should all compile in to the main test program.

**Comment by dragon512** [comment]
@zwoop I agree. I sent out notes on having people here make tests for gtest and Catch. I believe anyone else doing the same work will find Catch better than gtest.

We also need to make some BKM for writing tests with Catch.. but I think we need people to write tests before making a set of Best Known Method.

**Comment by jpeach** [comment]
@dragon512 I would prefer to keep the tests close to the code like they are now. That makes is easier to test internal functions without having to expose them just for testing. We should just establish a pattern like `foo.cc` and foo_test.cc` similar to Go.

**Comment by zizhong** [comment]
It would be great if you can include a demo that shows the pattern you suggest how to use Catch.

**Comment by dragon512** [comment]
@jpeach I would like to separate the file to a different location. I am not clear one what the concern is on "test internal" functions as this is all being linked on as a big .a file. If we want to call the test cpp file
xyz_test.cpp I am fine with that. I would like to separate the source files from the test files to avoid cases like Version.cc which has code and tests in the same file.

**Comment by dragon512** [comment]
@zizhong There is a basic example in the comments as well. 

If you look at the documentation for Catch https://github.com/philsquared/Catch 
you will see that the we have a number of features.. The one that I need to hit on with @SolidWallOfCode is that we probably want to have our tests use features as:


TEST_CASE("constructor calls", **"[string_view]"**) {

Where the "[string_view]" acts as in value we can filter on, so we have an easy way to reduce what test we want to run.

**Comment by jpeach** [comment]
@dragon512 That is exactly my point. Tests need to be close to the code. We should absolutely not separate them out and then link a big-ball-of-mud. Keeping `libts.a` tests close to `libts.a` helps focus the tests on just that component and in the long run will make it easier to reduce the dependency tangle.

**Comment by dragon512** [comment]
@jpeach I see pro and cons for different approaches. my concern with lib/ts/Version.cc as an example is that it is test code and production code in the same file. I think however that you are bring up a different and every important suggestion which is how we break up the tests. In this PR the idea is that I make one big test file that run all the tests ( however there is nothing really doing this). We can break this up to have one set of tests per file, or have a different break up. I believe you are suggesting we should have all the Tests for libts for example as one exe and the tests for iocore/net as a different file if I understand you correctly. In this case we can do that. I can add the test for basic_string_view in the TS directory as you suggest. The trick will be what do we add where as we have _test.cc files that use different test code. Ideally this should be easy to add. I might suggest that we make the "new" Catch based tests end with _test.cpp to make it clear this is not the "old" _test.cc files. Otherwise I was suggestion we make new unit tests in a different place such as {source-location}/tests/mytest.cpp or tests/unit_tests/ts/mytest.cpp. Both of these location would also allow us to break up tests with the correct .a file and reduce the "ball of mud".
quick review of options:
1) rename new catch based tests as _test.cpp ( instead of _test.cc) so we can migrate and not break existing test code
2) move test to a subdirectory of tests in the currents source location
3) move the test to tests/unit_tests/{module name}

My main concern is making sure we can migrate in stages, and not big bang this

**Comment by gtenev** [comment]
My preference would be to have **more locality** in the unit tests. 

I think (2) is a good compromise and hope we don't go with (3).

I personally would prefer to:
* store the tests close to the source code which they are testing
* build them and execute them per module (i.e. library or plugin)
* have a really light weight unit tests bootstrapping 

In more words…

**These are unit tests and not integration tests**, they are never testing the whole project or even a combination of modules together (in comparison with AuTest and TSQA), unit tests structure usually resembles the code structure and I am not sure if creating a separate test directory mirroring the code structure makes much sense.

**Having all pieces together that need to be updated** with a particular change is a practical approach for conscientious developers to keep tests and code in sync. From my experience it seems that trying to search somewhere else for the tests crosses a threshold for many 😉.

I tend to **consider the unit tests and the code as almost the same kind** and don’t believe they should be separated. Unit test are not clutter by any means, if the tests are not pleasant to look at we should write more elegant tests 😉. I am not advocating combining code and tests in the same file but they should be pretty close together. 

**Writing unit tests should be really light weight and quick** (it should not require much boot strapping) otherwise it will feel like a burden (it is especially important if practicing TDD).

Different developers have different styles but in general If I need to add a new feature (or class or a function) I usually sketch the code and write a small test to quickly test it and then I iterate over by adding more tests and then more code until I make the functionality as complete as needed. After I have some confidence that my new code really works I integrate it with the existing module.
 
In this flow I always try to keep the new code as modular (independent) as possible and have  just enough dependencies to complete its task. 

In general it feels like having all tests in one place and running them together (3) would encourage less discipline and would make code / dependencies harder to untangle when managing the code, it feels less light weight as well.

**Comment by dragon512** [comment]
I am not advocating combining code and tests in the same file but they should be pretty close together.
--

I just want to make sure we keep the source code and test code in separate files. The location is driven by a need a clean way to understand this is "old" testing code vs "new" testing code. Also that a well tested system will tend to have test code out size the production code being tested by 2-10 times. For that reason..
I am all for **(2)**

How we break up the tests to run has different value depending on how the testing is being used:

the plus side with frameworks such as catch building all these as one binary or many is a easy build config thing, **Catch support both models easily**. 

The value with running all the tests in 

- **one binary** is often with reporting results, as it is easier to do with one binary vs many. ( don't need extra script to gather data, etc) 
- **smaller - many binaries** is that for fixing a test or doing development work with TDD is much easier as you can focus on the problem. 

I don't believe anything in this patch prevents any case we are talking about. The PR add a catch.hpp file and a main.cpp file ( to have to link in to whatever combination of tests we want). I don't have anything in this yet as some high level logic to for easy building of the testing code at the moment.

**Comment by SolidWallOfCode** [comment]
I see @gtenev's point - it can get annoying, even for more sophisticated editors, to find test files a long directory path away. I think I'd go with a `test` subdirectory. E.g. for IpMap, the source file is `lib/ts/Ipmap.cc` and the unit tests are in `lib/ts/test/test_IpMap.cc`.

**Comment by dragon512** [comment]
I think we are all agreeing on option 2 then for test location.

Are we all agreed on Catch?

**Comment by zwoop** [comment]
+1 on a /test subdirectory where appropriate. I assume this will work for plugins too, e.g. header_rewrite/test/  to test various core functionality ?

**Comment by dragon512** [comment]
I have an example test in https://github.com/apache/trafficserver/pull/2259

**Comment by SolidWallOfCode** [comment]
I think we're ready to move forward. We'll put the unit test code in `test` subdirectories and have them pull the include files from where they are in this pull request. It may not be what we ultimately do but I think it's close enough.

**Comment by dragon512** [comment]
@jpeach I going to commit this as a starting point. I just want to check to make sure you have no major concerns first

**Comment by dragon512** [comment]
I am going forward with the commit. I believe we are all in agreement with the basic of catch. Future PR can deal with build tweaks

**Pull request merged**
