### PR TITLE
Update runroot to use yaml-cpp library

### PR DESCRIPTION
**Pull request by chitianhao**
This PR update the runroot to use the newly introduced yaml-cpp lib.
The library path is also included in ``.vscode/c_cpp_properties.json``

### CODE REVIEW

**Comment by chitianhao** [comment]
Do you know how do we include the yaml library inside lib/ts? @randall @bryancall

**Comment by randall** [comment]
What you are doing looks to be correct. But there's a build ordering issue. It looks like libyaml is built after libtsutil.

**Comment by chitianhao** [comment]
I see. Can you make a PR fixing that? @randall

**Comment by chitianhao** [comment]
Do you know what is causing these build errors? @randall

**Comment by chitianhao** [comment]
This CentOS build failed because there is a bug in the previous gcc-7.2.1 of redhat: https://bugzilla.redhat.com/show_bug.cgi?id=1519073. I think it should be updated to gcc-7.3.1. @zwoop .

**Comment by bryancall** [comment]
[approve ci centos]

**Pull request merged**
