### PR TITLE
Moves traffic_server to cmd/traffic_server

### PR DESCRIPTION
**Pull request by zwoop**
This got somewhat ugly, of course, since we have such odd dependencies across
libraries and files. This is a start at least, and we can cleanup more as we go along. I'd
really like to get rid of a lot of the -I<...>  that we do, which tend to flatten the include
name space arbitrarily.

### CODE REVIEW

**Comment by zwoop** [comment]
FWIW, I tried to move as much as possible from proxy to cmd/traffic_server/, but our dependencies made that rather tricky. Again, we can cleanup more as we go along, if we can decouple more of this, I think we can move more files out of proxy / libproxy.a, and into cmd/traffic_server. The sharing of code here is very artificial.

**Comment by SolidWallOfCode** [comment]
I'll endorse this in principle, but I want to check this specific PR in more detail.

**Comment by bryancall** [comment]
Why would we do this if only traffic_server links with libproxy.a?  libproxy.a and traffic_server are the application.

**Comment by zwoop** [comment]
I tried that, but that means significant portions of the code has to change, and/or use cmd/traffic_server for includes. iocore (cache etc.) uses things out of proxy/ :-/

**Comment by zwoop** [comment]
What should we do here? @bryancall @SolidWallOfCode  ?

**Comment by bryancall** [comment]
@zwoop I was looking at the circular dependencies and it is a mess.  We should make sure no new code introduces new circular dependencies (e.g. trace feature).

I am OK with doing this.

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
