### PR TITLE
lua: add ts.is_debug_tag_set function

### PR DESCRIPTION
**Pull request by traeak**
This exposes TSIsDebugTagSet to the lua plugin to allow for complex debug logic to only be calculated when debug is turned on.

### CODE REVIEW

**Comment by shukitchan** [comment]
[approve ci autest]

**Review by shukitchan — DISMISSED** [review]
It looks good. Thanks for the tests as well.

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by traeak** [comment]
> It looks good. Thanks for the tests as well.

the tests were a pain.  I had wanted to change the debug tags on the fly but that utterly failed.

**Comment by traeak** [comment]
[approve ci clang-analyzer]

**Review by shukitchan — APPROVED** [review]

**Pull request merged**
