### PR TITLE
Doc minor fixes.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Depends on #4539.

This cleans up some minor doc errors, and changes the map cleanup in `traffic-server.py` to be correct for dict modification during a loop in python 3.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci docs]

**Comment by SolidWallOfCode** [comment]
[approve ci docs]

**Comment by SolidWallOfCode** [comment]
[approve ci docs]

**Comment by SolidWallOfCode** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
I partially cherry-picked this to 8.0.x, since we need the Python fixes.

**Pull request merged**
