### PR TITLE
TS-1878: Add --as-needed to the linker flags

### PR DESCRIPTION
**Pull request by jablko**
Normally the linker will link to every -llibrary mentioned on the
command line. This option causes it to skip libraries that it doesn't in
fact use any symbols from.

The first commit in this PR belongs to #1411.

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1357/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1464/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/Github-Clang/29/ for details.

**Comment by jablko** [comment]
Merged. Thanks @zwoop!

**Pull request merged**
