### PR TITLE
Add a stub CONTRIBUTING file.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by jpeach** [comment]
I'm leaving this PR here so people can experiment with the GitHub review features. Feel free to merge or discard when you are done ;)

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/819/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/715/ for details.

**Comment by jpeach** [comment]
If everyone is done testing the review features, I'll merge this tomorrow.

**Pull request merged**
