### PR TITLE
Allow configurable body factory response max size

### PR DESCRIPTION
**Pull request by ibrezac**
New config: proxy.config.body_factory.response_max_size

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1317/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1424/ for details.

**Comment by bryancall** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1318/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1425/ for details.

**Comment by bryancall** [comment]
Please run clang-format on the code.  It is not passing CI.

**Comment by bryancall** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1326/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1433/ for details.

**Comment by bryancall** [comment]
Still needs a clang-format.  I will merge it and clang-format it once it is committed.

**Pull request merged**
