### PR TITLE
Add libswoc to ATS for core and plugins.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
libswoc, "Solid Wall of C++", is a library built on top of existing ATS C++ utilities and classes. It was intended as a platform for upgrading ATS core functinality from the start. It is now time to bring it back to ATS and begin replacing old legacy code with more robust, more powerful, and more performant versions. In addtion this will make the library available to plugins so that they too can use these improvements. In particular, this exports the IP networking support that's long been available in the core but plugins have been required to copy or re-implement.

While we will for a time run with both the old and libswoc versions, I will be working to replace and then KIWF the old versions.

In addition to code improvements, the documentation has been extensively revised (when not written from scratch). Unit test and examples should make it much easier for core and plugin developers to use these features.

libswoc repo - https://github.com/solidwallofcode/libswoc
libswoc documentation - http://docs.solidwallofcode.com/libswoc

### CODE REVIEW

**Review by bneradt — DISMISSED** [review]
Looks fine to me.

On my system building with and without this patch with j4, this added under 5 seconds of build time.

**Review by masaori335 — CHANGES_REQUESTED** [review]
Block to discuss more. ( I like additional features like `Lexicon` :) )

If we use this like other 3rd party libraries (- e.g. fastlz and yamlcpp), the whole code should be under the `/lib/`.

**Comment by bneradt** [comment]
[approve ci debian]

**Comment by bneradt** [comment]
Approved

**Review by bneradt — APPROVED** [review]
Thanks for adding this.

**Pull request merged**
