### PR TITLE
Remove ignore_keep_alive method entirely

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by shinrich** [comment]
Really?  I'll dig into that aspect then.  This is reverting a change from the graceful shutdown commit.  I'd really like to separate signaling of the graceful shutdown from the HTTP/1.x connection keep alive logic in the HttpSM since particularly in the post case this logic can be ugly.

**Comment by maskit** [comment]
Interesting. Since H2 has been returning `false` this removal shouldn't affect the graceful shutdown but let me double check.

**Comment by zwoop** [comment]
@shinrich This will need a new PR against the 7.1.x branch please.

**Comment by zwoop** [comment]
Looks like we'll want this at least for 9.0.x, and possibly 8.x ?

**Comment by zwoop** [comment]
Cherry-picked to 8.1.x

**Pull request merged**
