### PR TITLE
Term standardization: dead/down server -> down server

### LINKED ISSUE #7283: dead vs down server - standardize terminology
I find it a little confusing that dead and down are used interchangeably - can all setting names mention either dead OR down?

proxy.config.http.down_server.cache_time: 180
proxy.config.http.down_server.abort_threshold: 10
proxy.config.http.connect_attempts_max_retries_dead_server: 1

### PR DESCRIPTION
**Pull request by lzx404243**
#7283 records the issue of using `dead server` and `down server` in the configurations interchangeably, which has caused confusion in the field when inspecting issues(e.g. making one wonder the distinction between `dead` and `down`).  This PR standardizes those terms to `down server`. The following configuration and metric items(and their documentation) are updated: 
* `proxy.config.http.connect_attempts_max_retries_dead_server` becomes `proxy.config.http.connect_attempts_max_retries_down_server`
* `proxy.config.http.connect.dead.policy` becomes `proxy.config.http.connect.down.policy`
* `proxy.process.http.dead_server.no_requests` becomes `proxy.process.http.down_server.no_requests`

In addition to the above, other usage of the term "dead server" and the like has been updated (in hostDB and http).

This resolves #7283.

### CODE REVIEW

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci debian]

**Comment by shinrich** [comment]
Looks good to me.  On such setting name changes, do we historically do anything on upgrade?  I don't think we do.  ATS will generate warnings for bad setting names if the dead* version of the settings had been set.

**Review by SolidWallOfCode — APPROVED** [review]

**Comment by SolidWallOfCode** [comment]
@lzx404243 - we *MUST* have release notes for this.

**Comment by ezelkow1** [comment]
[approve ci centos]

**Review by SolidWallOfCode — APPROVED** [review]

**Pull request merged**
