### PR TITLE
update example directory structure and add examples for lua plugin

### PR DESCRIPTION
**Pull request by shukitchan**

### CODE REVIEW

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
seeing this now, I wonder if it'd be better to organize this slightly different? I'm thinking either:

```
    example/
        c-plugins/
        cpp-plugins/
        lua-plugins/
        configs/
            forward/
            reverse/
            transparent/
```

Or

```
    example/
        plugins/
            c-api/
                null-transform/
            cpp-api/
                ...
            lua-api/
                ...
        configs/
            forward/
            reverse/
            transparent/
```

It just feels that we made the example/plugins tree to generic, and important things, such as the "lua" directory, is hard to find / see. Essentially, it feels like we flattened the namespace too much?

Not super strong feelings here though, and I understand the amount of work / pain going into this effort. If I had a choice, between 1 - 3 (1 being this PR), I would pick 3) (my last example).

**Comment by zwoop** [comment]
One fourth option could be a hybrid of the two above:

```
```
    example/
        c-api/
            null-transform/
        cpp-api/
            ...
        lua-api/
            ...
    configs/
        forward/
        reverse/
        transparent/
```

I.e. in examples, it would look like this:

```
[root@cosmo trafficserver]# tree example
example
├── c-api
│   └── null_transform
├── configs
│   ├── cache
│   ├── forward
│   ├── proxy
│   ├── reverse
│   └── transparent
├── cpp-api
└── lua-api
```

**Comment by shukitchan** [comment]
I pick option 3 as well. 
Let me update the email and see if there's any objection to that.

**Comment by shukitchan** [comment]
@zwoop i made the updates. Please check it out.

**Comment by shukitchan** [comment]
I will squash after review.

**Comment by shukitchan** [comment]
@zwoop can you take a look at this again ?

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
It looks like I screwed up my branch. Will submit again in a day or two.

**Pull request closed without merging**
