### PR TITLE
Remove extra verify-callback

### PR DESCRIPTION
**Pull request by shinrich**
Plus exercising the CI autest to figure out test failures.

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by maskit** [comment]
```
$ git grep "set_verify("
iocore/net/SSLClientUtils.cc:  SSL_CTX_set_verify(client_ctx, SSL_VERIFY_PEER, verify_callback);
iocore/net/SSLNetVConnection.cc:      SSL_set_verify(this->ssl, SSL_VERIFY_PEER, verify_callback);
iocore/net/SSLUtils.cc:  SSL_set_verify(ssl, server_verify_client, ssl_verify_client_callback);
iocore/net/SSLUtils.cc:    SSL_CTX_set_verify(ctx, server_verify_client, ssl_verify_client_callback);
tools/http_load/http_load.c:      SSL_CTX_set_verify(ssl_ctx, SSL_VERIFY_NONE, cert_verify_callback);
```

I assume the other is the one in SSLNetVConnection.cc. Do we want to set the callback function to `SSL` rather than `SSL_CTX`?

**Comment by shinrich** [comment]
Good point. Should review the client side as well.  I noticed double prints from the server verify callback when looking at the debug statements from the autest failures.  I had figured that with multiple calls to SSL_*_set_verify, the last one in would be the only one called.  But for openssl at least, it appears that there is a slot for the SSL_CTX and a slot for the SSL object itself.

Originally we just had the SSL_CTX version.  I added the SSL object version to deal with dynamic updates I believe.  Need to review some git history.

**Comment by shinrich** [comment]
Perhaps we can go ahead and land this change, and track down additional potential redundant calls later.  I tried to do a quick fix that seemed to match on the other side, but several of the tls_client_verify* autests fail.  I doubt I will have much time to get back to this for some time.

**Review by maskit — APPROVED** [review]
Sure, that's not a blocker. I guessed SSL_CTX is better if possible because it's one time job at ATS initialization but not TLS session initialization.

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
