### PR TITLE
TS-4376: Support variable extension in set-header

### PR DESCRIPTION
**Pull request by petarpenkov**

### CODE REVIEW

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/617/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/513/ for details.

**Comment by jpeach** [comment]
This looks very reasonable to me. Since @zwoop is the ``header_rewrite`` guru I'd like him to ack as well.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
