### PR TITLE
have autest make hardlink or symlinks before doing a copy

### PR DESCRIPTION
**Pull request by dragon512**

### CODE REVIEW

**Comment by dragon512** [comment]
[ci approve autest]

**Comment by dragon512** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cheery-picked to 7.1.0 as well.

**Comment by jpeach** [comment]
> On Jun 21, 2017, at 8:28 AM, dragon512 <notifications@github.com> wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/apache/trafficserver/pull/2176
> 
> Commit Summary
> 
> 	• have autest make hardlink symlinks before doing a copy

@dragon512 Why do we need a copy? You should be able to use the existing PROXY_CONFIG_PLUGIN_PLUGIN_DIR just by setting the configuration to point to it.

J

**Comment by dragon512** [comment]
@jpeach So technically I would say that it could be done. I could do this with the bin as well. The reason to not do this was to make a reproducible sandbox for the test. This prevents the original directory being messed with for testing. It also allows one to package the directory easier, getting a full copy of the failed test to replay in a different location or system. The later case here given certain "abspath" issues with ATS would make this difficult. 

I was thinking this would also make it easier to have a copy plugin API added so we can plugins, copy it to the default location and have it load with others messing with original locations, or verifying that "default" load logic works we expected. For me this is mostly about separating the OS system install from the testing. Hard links allow us to save space for binaries we are testing against, while allowing us the separation provided by have a different directory "containing" item for a given test run

**Comment by d2r** [comment]
@dragon512 I am having trouble running my tests after this change. Maybe I need to change how I test:

1. Build ats with make && sudo make install 
1. Run autest.sh from the tests dir

The 204 plugin test fails now because it has no permission (running as me) to copy the plugin source file into the sandbox plugin directory, which is now a symlink to the plugins directory of the system installation (owned by root).

How did you run the tests with this change?

**Pull request merged**
