### PR TITLE
Promote cachekey to be a stable plugin

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by djcarlin** [comment]
cacheurl plugin was deprecated without its replacement being promoted from experimental to stable.

**Comment by djcarlin** [comment]
@gtenev @bryancall should this be backported to 7.1? 

https://github.com/apache/trafficserver/pull/2325

Any other cachekey PRs that should be backported?

**Comment by gtenev** [comment]
@djcarlin,

#2325 is the only commit that added new features since 7.1.x was branched.

```
$ git log --oneline origin/7.1.x..master plugins/experimental/cachekey
244288fab cachekey/cacheurl key string compatibility enhancements.  <--------------(#2325)
f5b9f53cc Method not implemented and constructor hiding not required
de2dcd452 Noncopyable update for C++11
ec2e2d2ab Ran autopep8 to python files
002d8ffe2 Ran clang-tidy with readability-braces-around-statements
0fb22ae2d Ran clang-tidy with modernize-loop-convert
9a5c1d5a5 Ran clang-tidy with modernize-deprecated-headers
c31f463f5 Ran clang-tidy with performance-faster-string-find
```

**Comment by bryancall** [comment]
This PR hasn't been updated in more then 2 months and I am closing out PRs that haven't had any updates.  Please feel free to reopen if want to update it.

**Pull request closed without merging**
