### PR TITLE
Broken sed caused layout problems

### PR DESCRIPTION
**Pull request by tcely**
See https://github.com/alpinelinux/aports/pull/10344

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
This patch isn't the same as the one to which you linked. Why is it different? I understand the original patch, but this one seems incorrect.

**Comment by tcely** [comment]
If you are happier also removing the backslash, then you should. As I understand the syntax, either way should work.

**Comment by SolidWallOfCode** [comment]
Yes, the shell escaping should remove the backslash before `sed` sees it. But given the original error was confusion between shell escaping and `sed` regular expression escaping, I'd rather have the simplest working form, or even `\\+` which should also work, although I like (as you seem to) to use brackets for escaping regular expression metasyntactic characters to be clearer in such situations as this.

**Comment by SolidWallOfCode** [comment]
This can be merged, the behavior is the same whether the backslash is present or not.

**Comment by bryancall** [comment]
@tcely Can you make this PR against master and then I will cherry-pick it to our 8.0.x branch?

**Comment by randall** [comment]
This was merged into 8.1.x:

**Pull request closed without merging**
