### PR TITLE
certifier.so: Convert to TSDbg

### LINKED ISSUE #9794: certifier plugin crash on master
I'm a part of the team that manages the ASF ATS CI images. I did a routine update of the ci.trafficserver.apache.org/ats/rockylinux:8 image to make it slimmer by cleaning up build artifacts. We noticed, however, that with that update, the certifier.test.py test started failing due to what looked like a shutdown crash from ATS. Through some investigation, I observed:

1. Start with the previous ci.trafficserver.apache.org/ats/rockylinux:8 docker image and run the certifier autest, it passes fine. The original image is available on docker1 in the CI system, which I have access to.
3. Now run `sudo yum update` and update the system packages.
4. Then rebuild ATS after a full git clean.
5. Then re-run the certifier autest. The test now fails due to the ATS crash.

@maskit and @bryancall both reproduced this crash on later Fedora versions, so this isn't a peculiarity of the docker image itself. It's just occasioned by some package update.

@maskit found that the crash could be avoided by commenting out the debug log from a destructor in the certifier.cc file, see: https://github.com/apache/trafficserver/pull/9792

We agreed to merge that in temporarily to keep CI green so that PRs can be merged. However, we need to prioritize figuring out why that log results in a crash with that certifier test.

### PR DESCRIPTION
**Pull request by bneradt**
The TSDbg works better in shutdown conditions. The certifier plugin with the old logging interface was experiencing a shutdown crash. Converting to TSDbg addresses this crash.

Fixes #9794

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Review by ywkaras — CHANGES_REQUESTED** [review]
We should not merge this until we decide what to do with:  https://github.com/apache/trafficserver/pull/9732

**Comment by bneradt** [comment]
[approve ci rat]

**Comment by jpeach** [comment]
Might as well take all the changes from #9975 as well.

**Review by jpeach — APPROVED** [review]

**Comment by bneradt** [comment]
The certifier plugin has been converted to DbgCtl via #10390:
https://github.com/apache/trafficserver/pull/10390/files#diff-14664431da891cb710c866874630968fad88531ac96f9e6e7b2558ee13988f7e

Closing this PR.

**Pull request closed without merging**
