### PR TITLE
libswoc: update to 1.4.4

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Update to libswoc 1.4.4. This contains a number of fixes, primarily for `MemSpan`.

Note: slight issue with 1.4.3 on Ubuntu, tweaked to deal with that and bumped the libswoc version to be safe.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci ubuntu]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
I don't have any objection to upgrading libswoc, but I'm wondering why this change doesn't have any change in unit tests.
We don't import any unit tests of libswoc?
https://github.com/SolidWallOfCode/libswoc/tree/1.4.4/unit_tests

**Comment by SolidWallOfCode** [comment]
What would be the benefit of that? Those are run before a libswoc release, and the results won't change for that release.

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
It seems we may need [this](https://github.com/apache/trafficserver/pull/9498) to fix the autest(actually fix the issues causing the fail on the autest)

**Comment by masaori335** [comment]
OK, the libswoc is tested well in the upstream repo before we import it. Hmm, it should be fine.
But what's the reason why we don't import the whole repo?

**Pull request merged**
