### PR TITLE
Make the rest of InkAPI allocators Proxy Allocated

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
The test_hooks Au test is causing a segment violation in TSContDestroy():  https://ci.trafficserver.apache.org/autest/ausb-8106.16267/test_hooks/_output/test_hooks-ts/stream.stderr.txt

I think what's happening is that INKContAllocator or it's proxy allocator is getting destroyed before `cleanup`:
https://github.com/apache/trafficserver/blob/c214c9f40096afbe580c0ee90647933ad8b21bcd/tests/tools/plugins/test_hooks.cc#L371

I think you should just delete the lines https://github.com/apache/trafficserver/blob/c214c9f40096afbe580c0ee90647933ad8b21bcd/tests/tools/plugins/test_hooks.cc#L348-L372 .

There are tricky ways to control the order of destruction at program exit, but I don't think it's worth it.  The only problem is that it will probably look like a memory leak to ASAN.

**Review by ywkaras — CHANGES_REQUESTED** [review]
Delete the indicated lines from test_tsapi.cc.

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
If this ever passes Au test regression without changing test_tsapi.cc, it will be a fluke, it will be flakey forever more.

**Comment by ywkaras** [comment]
[approve ci autest]

**Review by ywkaras — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
