### PR TITLE
C++ API: Add template for convenient continuations that call a member function for a class instance.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
[approve ci Ubuntu]

**Comment by randall** [comment]
[approve ci ubuntu]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
This PR hasn't been updated for over 2 months.  If you would like to work on this please reopen.  Make sure it passes CI and doesn't have any merge conflicts.

**Pull request closed without merging**
