### PR TITLE
require at least OpenSSL version 1.1.1

### PR DESCRIPTION
**Pull request by cmcfarlen**

### CODE REVIEW

**Comment by JosiahWI** [comment]
How does this work with openssl-quic and boringssl?

**Comment by cmcfarlen** [comment]
> How does this work with openssl-quic and boringssl?

It totally doesn't.  I just wanted to see what happens to CI! Looks like we will have to check this manually

**Review by maskit — DISMISSED** [review]
Making change request to wait for the consensus on the mailing list. I think we can proceed after thanksgiving.

**Comment by bneradt** [comment]
[approve ci autest format]

**Comment by bneradt** [comment]
[approve ci rocky]

**Comment by cmcfarlen** [comment]
Converted to draft until after consensus

**Comment by bneradt** [comment]
[approve ci osx]

**Review by bneradt — APPROVED** [review]

**Review by maskit — APPROVED** [review]

**Pull request merged**
