### PR TITLE
Move sni config (formerly ssl_server_name) under toplevel YAML tag 'sni'

### PR DESCRIPTION
**Pull request by randall**
This is for the work in issue #5245

### CODE REVIEW

**Comment by zwoop** [comment]
should we rename the configuration file to sni.yaml as well?

**Comment by zwoop** [comment]
Lets rename the file to sni.yaml IMO.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by randall** [comment]
I'll rebase this PR once #5599 is merged.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Pull request merged**
