### PR TITLE
Tsqa-- switch to using build that exist

### PR DESCRIPTION
**Pull request by jacksontj**
Now that trafficserver support exposing what features it has through `traffic_layout` we don't need to build ATS for every run of TSQA (yay!). Once the support is merged into apache/trafficserver-qa#5 we can merge this in and start running tests against `TS_ROOT`s that already exist. This changes the command from `make test` to something like `make test TSQA_ATS_ROOT=~/workspace/trafficserver/` (or wherever your env is).

Single tests can still be run, but tsqa will still require the `TSQA_ATS_ROOT` environment variable, so a one-liner to do that would look like: `TSQA_ATS_ROOT=~/workspace/trafficserver/ nosetests tests/test_example.py`

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1135/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1029/ for details.

**Comment by jacksontj** [comment]
@zwoop Hopefully all labelled correctly?

**Pull request merged**
