### PR TITLE
move TRANSACT_RETURN to Transaction.cc

### PR DESCRIPTION
**Pull request by scw00**
TRANSACT_RETURN is used only in Transaction.cc.

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci clang-format]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
```
[Sep 30 17:28:22.128] traffic_crashlog {0x2b49bf97efc0} NOTE: crashlog started, target=4967, debug=false syslog=true, uid=989 euid=989
[Sep 30 17:28:22.129] traffic_crashlog {0x2b49bf97efc0} WARNING: failed to intialize management API: [5] Error establishing socket connection.
[Sep 30 17:28:22.129] traffic_crashlog {0x2b49bf97efc0} NOTE: logging to 0x764b10
[Sep 30 17:28:22.130] traffic_crashlog {0x2b49bf97efc0} ERROR: wrote crash log to /var/jenkins/workspace/linux-github/3746/install/var/log/trafficserver/crash-2017-09-30-172822.log
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE: 
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0xc3)[0x508214]
/lib64/libpthread.so.0(+0xf370)[0x7f737a8ab370]
/lib64/libc.so.6(gsignal+0x37)[0x7f7379aeb1d7]
/lib64/libc.so.6(abort+0x148)[0x7f7379aec8c8]
/var/jenkins/workspace/linux-github/3746/install/lib/libtsutil.so.8(_Z11ink_warningPKcz+0x0)[0x7f737bf4686e]
/var/jenkins/workspace/linux-github/3746/install/lib/libtsutil.so.8(_Z17ats_base64_encodePKhmPcmPm+0x0)[0x7f737bf43a51]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server[0x554a89]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN15INKContInternal12handle_eventEiPv+0xd9)[0x5116a3]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN12Continuation11handleEventEiPv+0x72)[0x50b396]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN12PluginVCCore24state_send_accept_failedEiPv+0xe3)[0x5488c7]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN12PluginVCCore14attempt_deleteEv+0x60)[0x548b1c]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN8PluginVC13process_closeEv+0x2b1)[0x54775f]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN8PluginVC12main_handlerEiPv+0x497)[0x54532f]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN12Continuation11handleEventEiPv+0x72)[0x50b396]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x136)[0x788c8a]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server(_ZN7EThread7executeEv+0x44b)[0x789259]
/var/jenkins/workspace/linux-github/3746/install/bin/traffic_server[0x7880f5]
/lib64/libpthread.so.0(+0x7dc5)[0x7f737a8a3dc5]
/lib64/libc.so.6(clone+0x6d)[0x7f7379bad73d]
```

**Comment by scw00** [comment]
[approve ci autest linux]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci linux]

**Comment by PSUdaemon** [comment]
@scw00 The change looks good to me, but I don't understand the significance of the stack trace.

**Comment by zwoop** [comment]
Do we actually crash without this fix?

**Comment by scw00** [comment]
Sorry! My mistake, It is the backtrace for regression test ! I think I need to open a new issue for this backtrace.

**Comment by scw00** [comment]
[approve ci Fedora]

**Comment by scw00** [comment]
[approve ci Fedora]

**Comment by scw00** [comment]
[approve ci Fedora]

**Comment by scw00** [comment]
[approve ci Fedora]

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
[approve ci autest fedora]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci fedora]

**Pull request merged**
