### PR TITLE
TS-4987: Don't prefer loopback over API set origin server address.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/946/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1055/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/947/ for details.

**Comment by zwoop** [comment]
Looking back, it seems this is basically handled (but better) with #1079 ?

**Comment by jpeach** [comment]
@zwoop this is different; you need to check whether the API set an address *before* worrying about whether it is loopback.

**Comment by zwoop** [comment]
I see. The first portion of this patch is important, whereas the second portion is done (better?) in #1079.

**Comment by SolidWallOfCode** [comment]
WIth regard to #1079, this doesn't intersect with that change. This maintains the existing loopback only check, it just does it better by dropping the pointless yet fragile string comparisons.

**Pull request merged**
