### PR TITLE
Check for pthread_getname_np with configure

### PR DESCRIPTION
**Pull request by tcely**
See https://github.com/alpinelinux/aports/pull/10344

### CODE REVIEW

**Comment by maskit** [comment]
This reminded me my PR #4590. It seems like to be cherry-picked for 8.1.0 but it was not released.

Does backporting #4590 to 8.0.x solve the issue? We rarely make commits directly on release branches and cherry-pick commits on master instead.

**Comment by tcely** [comment]
Backporting #4950 would be fine for me. Would this be in `8.0.6`?

**Comment by maskit** [comment]
That's up to the release manager, but I personally think we can backport it as a sort of bug fix, so it would be in a 8.0.x release. I'm making sure how we do backports for 8.0.x.

**Comment by bryancall** [comment]
Cherry picked aee657da043fffe16eb5c71142b1dfda4a0b0dc6 from master and set #4590 milestone to be 8.0.6

**Pull request closed without merging**
