### PR TITLE
TS-4156: remove the traffic_sac, stand alone log collation server

### PR DESCRIPTION
**Pull request by mingzym**
TS-4156: remove the traffic_sac, stand alone log collation server

https://issues.apache.org/jira/browse/TS-4156

### CODE REVIEW

**Comment by jpeach** [comment]
Could you please remove these remaining references:
```
$ git grep traffic_sac
.gitignore:proxy/traffic_sac
doc/locale/ja/LC_MESSAGES/admin/working-log-files.en.po:"Copy the :program:`traffic_sac` binary from the Traffic Server ``bin`` "
doc/locale/ja/LC_MESSAGES/admin/working-log-files.en.po:"program:`traffic_sac` binary."
```

Otherwise, this looks OK, and no-one has stepped up in favor of ``traffic_sac``.

**Comment by jpeach** [comment]
@masaori335 ``doc/locale/ja/LC_MESSAGES/admin/working-log-files.en.po`` needs to be regenerated after this change. Can you document how to do that?

**Comment by masaori335** [comment]
Here is the docs : [Internationalize Documentation - Update PO files](https://cwiki.apache.org/confluence/display/TS/Internationalize+Documentation#InternationalizeDocumentation-UpdatePOfiles)
Please use `ja` as `<LANG>`.

**Comment by zwoop** [comment]
@mingzym  I think you are OK to make this change, but unless I missed it, I think you should also email dev@ and users@ saying that you plan on eliminating traffic_sac from v7.0.0.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux (CentOS7) build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-Linux/12/

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
.

**Comment by zwoop** [comment]
@mingzym Is this going to land? Needs a rebase before you can merge this too.

**Comment by masaori335** [comment]
@mingzym I'll update Japanese docs after this is merged if you want :)

**Comment by mingzym** [comment]
@masaori335 here we go :D

**Comment by masaori335** [comment]
I updated PO files in 0ebfab01d909bcd0d99cd2f8fb2f816916bc80f3.

**Pull request merged**
