### PR TITLE
Fix tunnel_route action in ssl_server_name and various test fixes for Fedora 28 and 29

### PR DESCRIPTION
**Pull request by shinrich**
A configuration parsing error.  Also a flaw introduced by one of the recent TLS hook clean up commits.

Also added an autest to catch future regressions

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
Hmmm still failing autest.

**Comment by shinrich** [comment]
Finally found a Fedora 28 machine.  Tracked down to an issue in autest.  Filed PR https://bitbucket.org/autestsuite/reusable-gold-testing-system/pull-requests/14/fix-portopen-dont-consider-active-ports/diff
Will nag Jason once he gets out of his meeting.

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
Just squashed my commits.  This PR has grown a bit.  The original intent of the PR was to fix the tunnel_route action in ssl_server_name.  There were two problems
1. Incorrect use of text_view caused the port to be included with the destination name in the TunnelMap data structure.  This caused the internal CONNECT method to have double ports and fail.
2. Missing checks on the TUNNEL action in the certificate selection callback.

As this PR went up, we moved to the CI machines to Fedora 28 and 29.  Fedora 28 revealed latent timing problems with the autest framework which were addressed with autest 1.7.2.  

Fedora 29 revealed a latent problem with the TLS hook state machine.  If Traffic Server receives a SYN which is immediately closed by the peer, the SNI plugin hook would still trigger.  We needed to update the hook state to _DONE when callHooks is called with the VCONN_CLOSE event.  This tripped up our tls_hook tests that were checking that the SNI handler was called at most once.

The openssl handling also sometimes caused the handshake failure to occur later.  A number of our tests were looking for connection failure messages in diags which were not being generated in that case.  The connections were still failing and the other tests for failure were occurring (e.g. the curl response was a 502).  It seems odd to add something diags on a connection failure, so I moved that message to a Debug message and took the extra checks out of the tests.  

At this point the tests are succeeding for me on Fedora 29 which the exception of double_h2 which fails sometimes.  I will take a look at that some more . That is one of the tests that had intermittent failures for us.

**Comment by shinrich** [comment]
[approve ci autest]

**Pull request merged**
