### PR TITLE
backport f71b75e and 734aa31 from master to 6.2.x

### PR DESCRIPTION
**Pull request by shenzhang920**

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1383/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1490/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/54/ for details.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1496/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1389/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/60/ for details.

**Comment by PSUdaemon** [comment]
@shenzhang920 can you rebase this?

**Comment by shenzhang920** [comment]
I merge upstream/6.2.x to my origin/6.2.x, please let me know if there's anything needed.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1402/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1509/ for details.

**Comment by PSUdaemon** [comment]
@shenzhang920 you need to rebase, not merge. I don't want to back port a merge commit. I think your mistake is that you did this directly on the 6.2.x branch. You really should use a feature branch off of 6.2.x.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/73/ for details.

**Comment by shenzhang920** [comment]
@PSUdaemon I reset my origin to the initial state (without my change), and do it all over again.

**Pull request closed without merging**
