### PR TITLE
Be less aggressive in calling SSL_shutdown.

### PR DESCRIPTION
**Pull request by shinrich**
Maybe helps avoid the crash described in issue #2212

### CODE REVIEW

**Comment by zwoop** [comment]
So this was a slight red-herring, in that the Via crasher added on to this as well. @vmamidi and I both think this is a good fix, but we can defer it for now, and consider a future back port after this has baked on master for a while. I.e. we don't need this for 7.1.0.

Thanks!

**Comment by zwoop** [comment]
I did test with this BTW, and it worked fine.

**Comment by oknet** [comment]
Althought the patch doesnt fix the crash ( #2212 ), it looks better anyway.

And I think @zwoop met a bug in libssl.
- https://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=3321
- http://seclists.org/oss-sec/2014/q2/233

**Comment by zwoop** [comment]
Cherry-picked to 7.1.x

**Pull request merged**
