### PR TITLE
Coverity CID #1241990 Resource leak

### PR DESCRIPTION
**Pull request by PSUdaemon**
Coverity thinks there is a case where `cert_names` may be empty which would cause `entry` to not be inserted and leak.

### CODE REVIEW

**Comment by PSUdaemon** [comment]
[approve ci]

re-running as I think AU failure is spurious.

**Comment by SolidWallOfCode** [comment]
I think it would be better to
```
ink_assert(cur_values.server_name.length() > 0 || cur_values.server_ips.size() > 0
```
or possibly return an error in that case, before allocating `entry`. If that assert is true, then `entry` will be stored in a table. Your patch here deletes `entry` even if it's been stored in the IP map.

**Comment by PSUdaemon** [comment]
Are you sure I am deleting it even if it's inserted? That was the intent with that bool, to make sure I only deleted if it wasn't inserted.

Let me consider that assert.

**Comment by shinrich** [comment]
+1

**Pull request merged**
