### PR TITLE
[TS-4457] Via header always reports http1

### PR DESCRIPTION
**Pull request by ericcarlschwartz**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/558/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/663/ for details.

**Comment by bryancall** [comment]
👍 - Looks good

**Comment by ericcarlschwartz** [comment]
A bit confused why the linux build here croaked and the FreeBSD one succeeded?

**Comment by zwoop** [comment]
@ericcarlschwartz It failed because of clang-format :-).

**Comment by jpeach** [comment]
Why can't you just slam in the result of ``get_protocol_string()`` in all cases?

**Comment by ericcarlschwartz** [comment]
@zwoop ah sorry! I must be doing something wrong, when I ran clang format on it just now I didn't get any changes?

**Comment by ericcarlschwartz** [comment]
@jpeach get_protocol_string() for http1.1/1.0 will just return "http". We could use that and then append the major/minor versions to that but I thought keeping the existing code would be clearer/minimize the difference for how it's done for the incoming request

**Comment by zwoop** [comment]
Hmmm, not sure. But if you look at the link, it clearly didn't like those lines.

**Comment by zwoop** [comment]
@ericcarlschwartz 

```C++
-  if (s->state_machine->ua_session && (!strncmp(s->state_machine->ua_session->get_protocol_string(), "http/2", 6))) { //if http/2
+  if (s->state_machine->ua_session && (!strncmp(s->state_machine->ua_session->get_protocol_string(), "http/2", 6))) { // if http/2
     memcpy(via_string, "http/2 ", 7);
     via_string += 7;
-  } else { //if http/1.1 or older
+  } else { // if http/1.1 or older
```

**Comment by ericcarlschwartz** [comment]
per IRC discussion on 9/1 looks like we want to rework this to rely entirely on result from get_protocol_string? Also @bryancall suggested maybe adding TLS info? How do others feel about that? Pretty sure we could do that with an old change from acacio

**Comment by shinrich** [comment]
You might want to leverage the populate_protocol() functions added for TS-4703 to create the protocol-specific via string.

**Comment by ericcarlschwartz** [comment]
@shinrich thanks for that info! That's definitely an interesting and useful way to do this using existing code

**Comment by ericcarlschwartz** [comment]
aaaah sorry this is bad i'm going to close it

**Pull request closed without merging**
