### PR TITLE
Send VC_EVENT_WRITE_READY/COMPLETE when write_vio is consumed

### LINKED ISSUE #3077: Larger downloads over H2 stalls with #2881 and priorities enabled
On Docs (with #2881 enabled, currently it is not) a command like this will hang every time, at exactly 55.8% (which is really, really close to 1MB).

```
curl  -D - -o /dev/null  https://ci.trafficserver.apache.org/bintray/clang-format-20170404.tar.bz2
```

This is with a "curl" client that supports H2. I tracked this down to the commit from #2881, which unfortunately is also back ported to 7.1.3. Reverting this change on master seems to fix the issue.

The remap rule for the above is

```
map https://ci.trafficserver.apache.org/bintray https://bintray.com/artifact/download/apache/trafficserver
```

### PR DESCRIPTION
**Pull request by masaori335**
- Add Http2Stream::signal_write_event(bool) to send VC_EVENT_WRITE_READY/COMPLETE event
- Add tests for HTTP/2 Stream Priority Feature

(cherry picked from commit a98021cb21ea2e180ba2664a80d9c154893b97af)

Conflicts:
	proxy/http2/Http2Stream.cc
	proxy/http2/Http2Stream.h
----
Backport #3091 and #3092 for fix #3077

### CODE REVIEW

**Comment by zwoop** [comment]
To be sure, I should wait merging this until you combine #3092 into this as well?

**Comment by masaori335** [comment]
Correct. I'm pretty sure #3092 will not be cherry-picked to 7.1.x cleanly.

**Comment by masaori335** [comment]
WIP: waiting #3092 is merged.

**Comment by masaori335** [comment]
#3092 is added. This is ready to backport.

**Comment by zwoop** [comment]
Is this ready go go into 7.1.x now? Or still need an update from 17f0e83620bf3ab2604e73fc7cd13d9e048513eb ? If so, should we make two separate PRs instead?

**Pull request merged**
