### PR TITLE
Send a 502 to the client when there is an invalid Transfer-Encoding header value from the origin

### PR DESCRIPTION
**Pull request by bryancall**
Did a git mv on chunked.replay.yaml to chunked_diabled.replay.yaml

Added proxy verifier tests to test:
Transfer-Encoding header not equal to chunked from origin
Transfer-Encoding and Content-Length headers missing from origin
valid Transfer-Encoding: chunked response from the origin

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Review by bneradt — CHANGES_REQUESTED** [review]
Looks great.

Rather than the _2 test, I'd just add your test class to the current chunked_encoding.test.py.

**Comment by ezelkow1** [comment]
[approve ci centos]

**Comment by serrislew** [comment]
If chunking is disabled but origin server responds with invalid Transfer-Encoding header, will it send 502 (from bad response) or 200 (since it is not even considered)?

**Comment by bryancall** [comment]
If any invalid Tranfer-Encoding header comes from the origin traffic server will respond with a 502, regardless if chunking is on or off.

**Review by serrislew — APPROVED** [review]

**Comment by bryancall** [comment]
[approve ci]

**Pull request closed without merging**
