### PR TITLE
Jtest post feature

### PR DESCRIPTION
**Pull request by scw00**
```
./jtest -h

  - , --post_support      int   0         POST Mode (0 disable(default), 1 random, 2 specified size by post_size)
  - , --post_size         int   0         POST SIZE
```

```
./jtest -s 12345 -p 8080 -c 1 --post_support 1   -X

Request to Proxy: {
POST http://ubuntu-linux:12345/0.2253550104/800 HTTP/1.0
Content-Length: 800
Proxy-Connection: Keep-Alive

}
Request from Proxy: {
POST /0.2253550104/800 HTTP/1.1
Content-Length: 800
Host: 127.0.0.1:12345
X-Forwarded-For: 127.0.0.1
Via: http/1.0-tcp-ipv4 ubuntu-linux[38ecdc23-daa5-42ca-bcfb-24ff40102cbe] (ApacheTrafficServer/8.0.0)

}
Response to Proxy: {
HTTP/1.0 200 OK
Content-Type: text/html
Cache-Control: max-age=630720000
Last-Modified: Mon, 05 Oct 2010 01:00:00 GMT
Connection: Keep-Alive
Content-Length: 800

/0.2253550104/800}
Response From Proxy: {
HTTP/1.0 200 OK
Content-Type: text/html
Cache-Control: max-age=630720000
Last-Modified: Mon, 05 Oct 2010 01:00:00 GMT
Content-Length: 800
Date: Mon, 15 May 2017 06:09:38 GMT
Age: 0
Proxy-Connection: keep-alive
Via: http/1.0-tcp-ipv4 ubuntu-linux (ApacheTrafficServer/8.0.0 [cMsSf ])
Server: ATS/8.0.0

}
```

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by scw00** [comment]
update! Please run ci again!

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
@scw00 sorry, I think we made a mistake with a config. Can you rebase this on master and remove that merge commit?

Thanks.

**Comment by scw00** [comment]
updated!

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by scw00** [comment]
updated! Please run again!

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
I'm good with this now. I'd still like @bryancall to weigh in as he is more familiar with jtest than I am.

**Pull request merged**
