### PR TITLE
Change connect_attempts_rr_retries test to match warning text

### LINKED ISSUE #1340: new warning running 7.1
On startup of 7.1.0, I now see this warning:

`
WARNING: connect_attempts_rr_retries (3) is greater than connect_attempts_max_retries (3), this means requests will never redispatch to another server
`

These are the values records.config.defaults to. Perhaps the default needs to change or the log  warning logic needs to change.

This warning was added in bc849813fc49986c5a600a24ce74cd2aa8c2bad8

### PR DESCRIPTION
**Pull request by randall**
Fixes #1340

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1353/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1245/ for details.

**Comment by zwoop** [comment]
Merged this to the 7.1.x branch as well

**Pull request merged**
