### PR TITLE
coverity 1022003 : add check for null value

### PR DESCRIPTION
**Pull request by dragon512**

### CODE REVIEW

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/529/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/519/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/516/

**Comment by atsci** [comment]
Intel CC build *failed*! https://ci.trafficserver.apache.org/job/icc-github/645/

**Comment by atsci** [comment]
FreeBSD11 build *failed*! https://ci.trafficserver.apache.org/job/freebsd-github/2212/

**Comment by atsci** [comment]
Linux build *failed*! https://ci.trafficserver.apache.org/job/linux-github/2108/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/773/

**Comment by PSUdaemon** [comment]
> CacheRead.cc: In member function 'int CacheVC::openReadMain(int, Event*)':
> CacheRead.cc:672:21: error: 'frag' was not declared in this scope
>      if (fragment && frag)

**Pull request merged**
