### PR TITLE
[TS-4443] regex_remap: fix $i substitution

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
[ci approve]

**Comment by zwoop** [comment]
Is there a Jira associated with this PR? Without a Jira, we can not commit this.

**Comment by yatsukhnenko** [comment]
I don't have a button to create issue. Yesterday it was, but I couldn't to select Traffic Server as a Project.

**Comment by yatsukhnenko** [comment]
screenshot_2016-05-13-20-27-58

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
I'm not sure I understand the full intent of this patch. It looks like it's always adding the Client-IP header, even if not enabled in records.config? Why is this necessary?

I understand that the $i here uses the value from the Client-IP, which again doesn't make a lot of sense. Why not just move out the logic that gets the client-ip (TSHttpTxnClientAddrGet), and use that in the RemapRegex::substitute()? I.e. why does it use the Client-IP header here at all?

Alternatively, maybe one of

1) Honor the request Client-IP in RemapRegex::substitute() if set.

2) Or add another directive,%I, which uses the Client-IP

But, in either case, I don't feel that the regex_remap plugin should set the Client-IP request header as done here.

**Comment by yatsukhnenko** [comment]
I didn't find a better way to pass the client-ip (TSHttpTxnClientAddrGet) to RemapRegex::substitute routine without changing of number of routine parameters so I used a workaround with headers.

**Comment by yatsukhnenko** [comment]
I'll open new pull request for this

**Comment by zwoop** [comment]
It's ok either way, but you don't have to close a PR if you plan on making a new, different change. Just force push the new changes up to the same PR if you like.

**Comment by yatsukhnenko** [comment]
Github closed this PR because I renamed a brunch in my repo

**Comment by zwoop** [comment]
Gotcha. Yeah, I saw #643 so we'll work there :).

**Pull request closed without merging**
