### PR TITLE
Move Sterror class from TsSharedMutex.h to its own include file.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Review by bneradt — COMMENTED** [review]
Looks fine to me.

**Comment by masaori335** [comment]
The change looks good. But what's the motivation? Just cleanup?

**Comment by SolidWallOfCode** [comment]
Once we have libswoc, we could do this with
```
class StrError {
  ts::LocalBufferWriter<256> _buff;
  StrError(int errno) {
    _buff.print("{::l}\0", ts::bwf::Errno(err)); // 'l' means "long" e.g. the string
  }
  char const* c_str() { return _buff.data(); }
};
```

**Comment by ywkaras** [comment]
There are many calls to strerror() in TS, most or all of them should be replaced with this I think.

**Review by SolidWallOfCode — APPROVED** [review]

**Pull request merged**
