### PR TITLE
rectify a minor error in file test_intercept.lua

### PR DESCRIPTION
**Pull request by taoyunxing**
line 34:
      return resp
should be modified as
     ts.say(resp)

### CODE REVIEW

**Comment by zwoop** [comment]
@shukitchan You ok with this?

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/55/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/58/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/71/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/184/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1753/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1647/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/316/

**Comment by shukitchan** [comment]
it looks good. 
👍

**Pull request merged**
