### PR TITLE
[TS-4129] Support TSContSchedule in ts_lua plugin

### PR DESCRIPTION
**Pull request by shukitchan**
@jpeach , pls help to take a look.

### CODE REVIEW

**Comment by shukitchan** [comment]
nice catch on both cases. let me update the PR over the weekend after some tests on the new code.

**Comment by shukitchan** [comment]
I just updated the pull request. @jpeach, pls take a look. Thanks.

**Comment by shukitchan** [comment]
A couple of functions will result in LUA_YIELD, such as sleep() and fetch(). And they all have schedule event to happen through their handler and those handler will eventually do the duty of TS_LUA_EVENT_COROUTINE_CONT.

**Comment by shukitchan** [comment]
@jpeach , any other advice?

**Comment by shukitchan** [comment]
before i merge?

**Comment by jpeach** [comment]
+1 merge it

**Pull request closed without merging**
