### PR TITLE
TS-4779: Remove SET_CLOSE_ON_EXEC #ifdef's from socket code and make …

### PR DESCRIPTION
**Pull request by PSUdaemon**
…CLOEXEC standard behavior.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/627/ for details.

**Comment by jpeach** [comment]
Should extend ``SocketManager::socket`` to handle non-block and cloexec like accept does?

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/523/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/525/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/629/ for details.

**Comment by jpeach** [comment]
👍

**Pull request merged**
