### PR TITLE
Correct the number of available disk shows in fatal message

### PR DESCRIPTION
**Pull request by oknet**
1. There is a copy&paste bug:

```
772        Fatal("Cache initialization failed - only %d of %d disks were available.", gndisks, theCacheStore.n_disks_in_config);
```

The ```gndisks``` did not updated.

2. Change the condition of if-statement:

from ```(n_init == gndisks - 1)``` to ```(n_init != gndisks - 1)```

It makes the codes more clearly.

3. Rewrite the logic of checking bad disk.

Line 757 to 796 of old Cache.cc, Line 762 to 786 of new Cache.cc.

### CODE REVIEW

**Comment by scw00** [comment]
Please add more information.

**Comment by SolidWallOfCode** [comment]
Nice work.

**Comment by zwoop** [comment]
Is this a candidate for 7.1.4 as well ?

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Comment by oknet** [comment]
@zwoop Yes, of cause if we will have 7.1.4. :-)

**Pull request merged**
