### PR TITLE
Removes the old expander feature of header_rewrite

### PR DESCRIPTION
**Pull request by zwoop**
The new string concatenations are just better, and faster.

### CODE REVIEW

**Comment by zwoop** [comment]
This still needs some testing as well.

**Comment by randall** [comment]
Looks like a legit autest failure. 

I think ./tests/gold_tests/headers/domain-blacklist-30x.test.py needs to be updated

**Comment by randall** [comment]
@zwoop can you hold off on merging this until I get #4568 in?

**Comment by zwoop** [comment]
I pushed an update to this, which resolves the merge conflicts, and also clarifies the semantics in values.cc.

**Pull request merged**
