### PR TITLE
remap test for secure communication with origin server

### PR DESCRIPTION
**Pull request by persiaAziz**

### CODE REVIEW

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/555/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/540/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/669/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/2132/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2236/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/798/

**Comment by PSUdaemon** [comment]
We should have @dragon512 review this once he gets set up as a committer properly.

**Comment by dragon512** [comment]
👍

**Comment by SolidWallOfCode** [comment]
@dragon512 - you need to officially review the PR. Under "reviewers" there should be a "request one" link. Click that, suggest yourself, refresh the page and add your review.

**Comment by persiaAziz** [comment]
I don't think his account is setup yet.

**Pull request merged**
