### PR TITLE
Fix check-unused-dependencies

### PR DESCRIPTION
**Pull request by duke8253**
Better support for python3, and fix problem with counting white space as an output.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Do we need this for 7.1.x too ?

**Comment by duke8253** [comment]
@zwoop I believe so, if python3 is used then it'll break so we better have them in 7.1.x as well.

**Comment by zwoop** [comment]
This script does not seem to exist on 7.x branch.

**Pull request merged**
