### PR TITLE
Make sure we core dump when we need to

### PR DESCRIPTION
**Pull request by duke8253**

### CODE REVIEW

**Comment by zwoop** [comment]
I'm somewhat concerned with this, and how it might interact with our crash logger, and possibly other external crash handlers. Are you positive we need this? What problem does this solve (it doesn't say anything about when / why this is needed). For example, I can most certainly force a core file from ATS without this patch:

```
[root@fedora leif]# gcore 11386
[root@fedora leif]# ls -lrt core.11386
-rw-r--r-- 1 root root 1156490600 May 18 10:24 core.11386
```

**Comment by randall** [comment]
@zwoop. fetching the core that way doesn't result with a core where the crash actually happened.

**Comment by duke8253** [comment]
Well, the comment says "make sure to drop a core for signals that normally would do so", but if we don't raise the signal again after setting the signal handler back to default, it will not core like it should have.

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
Tested:
`10:03:15 homer:~$ sudo /usr/local/bin/traffic_server
traffic_server: using root directory '/usr/local'
[May 18 10:04:45.800] {0x150927c35740} NOTE: crashlog started, target=32048, debug=false syslog=true, uid=0 euid=0
[May 18 10:04:45.800] {0x150927c35740} WARNING: failed to intialize management API: [5] Error establishing socket connection.
[May 18 10:04:45.800] {0x150927c35740} NOTE: logging to 0x1b67260
[May 18 10:04:45.801] {0x150927c35740} ERROR: wrote crash log to /usr/local/var/log/trafficserver/crash-2018-05-18-100445.log
traffic_server: received signal 11 (Segmentation fault)
traffic_server - STACK TRACE:
/usr/local/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x8e)[0x4aad3e]
/lib64/libpthread.so.0(+0x11fb0)[0x7efdf3055fb0]
/lib64/libc.so.6(nanosleep+0x40)[0x7efdf2209b80]
/lib64/libc.so.6(sleep+0x3a)[0x7efdf2209a5a]
/usr/local/bin/traffic_server(main+0x1ac2)[0x493e72]
/lib64/libc.so.6(__libc_start_main+0xeb)[0x7efdf21661bb]
/usr/local/bin/traffic_server(_start+0x2a)[0x49bc6a]
Segmentation fault
10:04:46 homer:~$ sudo tail /usr/local/var/log/trafficserver/crash-2018-05-18-100445.log
7efdf4eb6000-7efdf4eb8000 rw-p 00000000 00:00 0
7efdf4eb8000-7efdf4eb9000 r--p 00025000 08:01 10488763                   /usr/lib64/ld-2.27.so
7efdf4eb9000-7efdf4eba000 rw-p 00026000 08:01 10488763                   /usr/lib64/ld-2.27.so
7efdf4eba000-7efdf4ebb000 rw-p 00000000 00:00 0
7ffdd4edf000-7ffdd4f00000 rw-p 00000000 00:00 0                          [stack]
7ffdd4ff2000-7ffdd4ff5000 r--p 00000000 00:00 0                          [vvar]
7ffdd4ff5000-7ffdd4ff7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Unable to retrieve Traffic Server records: [5] Error establishing socket connection.
10:05:01 homer:~$  coredumpctl
TIME                            PID   UID   GID SIG COREFILE  EXE
Fri 2018-05-18 10:03:03 PDT   28511    99    99  11 error     /usr/local/bin/traffic_server
Fri 2018-05-18 10:04:46 PDT   32048    99    99  11 error     /usr/local/bin/traffic_server`

**Pull request merged**
