### PR TITLE
Set the block's m_water_level in Arena:free even if the block is not the last block

### PR DESCRIPTION
**Pull request by garfieldonly**
Link to issue #5155

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci autest]

**Comment by oknet** [comment]
Looks good to me.
It may reduce the use of memory.

**Comment by SolidWallOfCode** [comment]
I think this is wrong. The design in `Arena` is such that only memory in the last block can be freed. This change will have no effect on memory usage, as allocation in `Arena` only happens from that same last block. The current logic is correct - if the released memory isn't the most recently allocated memory, it's a noop.

**Comment by scw00** [comment]
I'm ok with that. But I prefer to adding tail pointer which point to the last block to speed up the traversing. 

IIUC, the arena's lifecycle is always bond with a transaction or in a stack. That means we don't need to strictly free the memory. And all blocks are freed by destructor just like a heap.  And it is mainly designed for string because the strings is not fixed size.

And We always use free where is very close to alloc. Otherwise you have no idea where the m_water_level is. And if you free the memory into the start - water_level. The block's water_level will never be shrank. But it is ok since because we have the gc in destructor.

**Comment by SolidWallOfCode** [comment]
There's no point in a tail pointer with this fix, since the list needs to be scanned for free memory. Without the fix, a tail pointer is a clear performance gain. In the larger picture, however, I think this is a dead end. As noted, I have been working on the `MemArena` class as a replacement for this class. If we think there are additional features, we should put the in that class, rather than patching old code. You can see the [documentation here](http://docs.solidwallofcode.com/libswoc/code/MemArena.en.html). In this regard, `MemArena` only supports memory freeing at the end. To improve memory usage, it searches back from the tail, but stops when it reaches a block with less than a threshold amount of free space, to limit search time. Blocks that drop below that threshold after an allocation are moved to the front so they don't get searched again.

**Comment by garfieldonly** [comment]
> I'm ok with that. But I prefer to adding tail pointer which point to the last block to speed up the traversing.
> 
> IIUC, the arena's lifecycle is always bond with a transaction or in a stack. That means we don't need to strictly free the memory. And all blocks are freed by destructor just like a heap. And it is mainly designed for string because the strings is not fixed size.
> 
> And We always use free where is very close to alloc. Otherwise you have no idea where the m_water_level is. And if you free the memory into the start - water_level. The block's water_level will never be shrank. So even include this change, it is still a problem. But it is ok since because we have the gc in destructor.

It's good idea to add a tail pointer due to free is very close to alloc

**Comment by garfieldonly** [comment]
> I'm ok with that. But I prefer to adding tail pointer which point to the last block to speed up the traversing.
> 
> IIUC, the arena's lifecycle is always bond with a transaction or in a stack. That means we don't need to strictly free the memory. And all blocks are freed by destructor just like a heap. And it is mainly designed for string because the strings is not fixed size.
> 
> And We always use free where is very close to alloc. Otherwise you have no idea where the m_water_level is. And if you free the memory into the start - water_level. The block's water_level will never be shrank. So even include this change, it is still a problem. But it is ok since because we have the gc in destructor.

The new arena block  is in the head of the list，tail pointer actually point to the block fisrt allocate. 
according to “And We always use free where is very close to alloc.” ,Scanning from header may be better.

**Pull request merged**
