### PR TITLE
Add function name to the HttpSM history.

### PR DESCRIPTION
**Pull request by jpeach**
Capture the state machine source location with SourceLocation so that
we now have the function in the history.

### CODE REVIEW

**Comment by zwoop** [comment]
Does this obsolete #1986 ? If so, why ?

**Comment by jpeach** [comment]
> On May 27, 2017, at 7:36 PM, Leif Hedstrom <notifications@github.com> wrote:
> 
> Does this obsolete #1986 ? If so, why ?
> 
Yes, because I can't commit without a PR and I wanted to touch up the change as it went in.

**Comment by jpeach** [comment]
@zwoop please approve

**Comment by zwoop** [comment]
I'm not a fan of this. IF we're going this route, the right approach is to branch off the original authors PR / branch, and work from there. Doing this, the original author is completely lost, which is definitely not the Apache way (and uncool from a legal perspective as well).

**Comment by jpeach** [comment]
@zwoop The author was correctly attributed.

**Comment by bryancall** [comment]
@zwoop 
I don't think James was trying to not have attribution to the original author, don't know if that was the meaning of the comment above.  I had to look to see who the author on the commit was myself. :)

@jpeach 
I think it would be good to have had 2 commits on the PR one for scw's original change and one for the the update to it.  This way both people get attribution and there is a clear history of who did what changes.

That or land scw's and then have a follow up PR.  I would be cool either way.

**Comment by zwoop** [comment]
Ok, I missread, and didn't see the attribution, it wasn't clear from the commit message that's on the main page for the PR. Sorry about that.

**Pull request closed without merging**
