### PR TITLE
Checking the retval of safe_getsockname() and safe_getpeername()

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by oknet** [comment]
@zwoop please backport to 7.1.x , thanks

**Comment by zwoop** [comment]
@oknet is this really critical for the v7.1.1 release ?

**Comment by zwoop** [comment]
I'm moving this to 8.0.0 for now, with a 7.1.x Project for future releases (unless you disagree, then please comment).

**Comment by oknet** [comment]
@zwoop 

We found an error returned from ```safe_getsockname()```.
SSL doesn't check the return value of safe_getsockname() while the others do.

**Comment by maskit** [comment]
@oknet I agree that we should check returned values, however, what will happen without the checks? Crash? Can clients or origin servers (incoming data) cause it intentionally?

If it is a serious problem, we should backport this for 7.1.1. But if not, we may postpone it to 7.1.2 or 8.0.0 because we are about to release 7.1.1 and 7.1.x branch seems stable right now. We need to assess the seriousness.

**Comment by oknet** [comment]
@zwoop @maskit 7.1.2 is acceptable since this pr is not critical for the v7.1.1.

**Comment by zwoop** [comment]
Why wasn't this merged to master before? ;-) [approve ci fedora]

**Comment by zwoop** [comment]
[approve ci fedora]

**Comment by zwoop** [comment]
This has some minor merge conflicts on 7.1.x, can you please make a PR against this branch too?

**Pull request merged**
