### PR TITLE
Address issues with python 3.10

### PR DESCRIPTION
**Pull request by dragon512**
This PR updates AuTest to 1.10.1 which has fixes to python 3.10
Also a fix to an extension to Trafficserver that

### CODE REVIEW

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci fedora]

**Review by randall — APPROVED** [review]

**Review by ezelkow1 — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
