### PR TITLE
Fixes issue #8807 nexthop failure threshold in ATS 9.1.x

### LINKED ISSUE #8807: ATS 9.1.2 - parent_select/nexthop - failure threshold
re branch - https://github.com/apache/trafficserver/tree/cb7eda60dc8c2068afd458fd20a8dd6232887f0d

I notice that the nexthop failure count upon a network timeout/event
never increments beyond 2.
With a failure threshold of 10, requests that land on this 'nexthop'
will always have to incur
a 2s timeout before moving onto the nexthop in the list. as the
threshold is never reached per nexthop's failure tracking.

Failure counts using parent_select works as expected, Thus the failing
parent is taken out of rotation per the parent retry timer/window(300)

Test case and other testing parameters found in the below comments.

See the below for a debug output comparison between next_hop and parent_select.
One increments failure count(parent_select) and one does not(next_hop).

**next_hop**

[Apr 23 01:49:27.883] [ET_NET 10] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [75] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:30.308] [ET_NET 11] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [76] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:32.366] [ET_NET 11] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [76] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:34.481] [ET_NET 12] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [77] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:37.474] [ET_NET 12] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [77] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:39.596] [ET_NET 13] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [78] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:41.599] [ET_NET 13] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [78] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:44.439] [ET_NET 14] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [79] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:47.434] [ET_NET 14] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [79] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:49.633] [ET_NET 15] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [80] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:52.639] [ET_NET 15] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [80] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:55.474] [ET_NET 16] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [81] Parent fail count increased to 2 for
192.168.72.208
[Apr 23 01:49:58.468] [ET_NET 16] DEBUG: <NextHopHealthStatus.cc:139
(markNextHop)> (next_hop) [81] Parent fail count increased to 2 for
192.168.72.208

**parent_select**

[Apr 23 02:11:12.507] [ET_NET 15] DEBUG:
<ParentSelectionStrategy.cc:86 (markParentDown)> (parent_select)
Parent fail count increased to 2 for [192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:14.595] [ET_NET 16] DEBUG:
<ParentSelectionStrategy.cc:86 (markParentDown)> (parent_select)
Parent fail count increased to 3 for [192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:17.589] [ET_NET 17] DEBUG:
<ParentSelectionStrategy.cc:86 (markParentDown)> (parent_select)
Parent fail count increased to 4 for [192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:20.435] [ET_NET 18] DEBUG:
<ParentSelectionStrategy.cc:86 (markParentDown)> (parent_select)
Parent fail count increased to 5 for [192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:22.602] [ET_NET 19] DEBUG:
<ParentSelectionStrategy.cc:86 (markParentDown)> (parent_select)
Parent fail count increased to 6 for [192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:25.587] [ET_NET 0] DEBUG: <ParentSelectionStrategy.cc:86
(markParentDown)> (parent_select) Parent fail count increased to 7 for
[192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:28.353] [ET_NET 1] DEBUG: <ParentSelectionStrategy.cc:86
(markParentDown)> (parent_select) Parent fail count increased to 8 for
[192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:30.795] [ET_NET 2] DEBUG: <ParentSelectionStrategy.cc:86
(markParentDown)> (parent_select) Parent fail count increased to 9 for
[192.168.72.208:80](http://192.168.72.208/)
[Apr 23 02:11:33.758] [ET_NET 3] DEBUG: <ParentSelectionStrategy.cc:86
(markParentDown)> (parent_select) Parent fail count increased to 10
for [192.168.72.208:80](http://192.168.72.208/)

### PR DESCRIPTION
**Pull request by jrushford**
Fixes #8807.  I've asked Jeremy Payne, jp557198, to test and comment here as he is the issue owner.

This was originally fixed in ATS 9.2.x with PR #8365 but #8365
was big and not backported to 9.1.x as it was a late PR and
zwoop did not want to bring it into 9.1.x at that time.

Anyway, this fixes the issue where the failure count on a parent
is not incremented properly.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci fedora]

**Comment by jrushford** [comment]
[approve ci rocky]

**Comment by jrushford** [comment]
[approve ci rocky]

**Comment by jrushford** [comment]
[approve ci fedora]

**Comment by jrushford** [comment]
[approve ci rocky]

**Comment by traeak** [comment]
[approve ci rocky]

**Comment by bneradt** [comment]
Both the Fedora and Rockylinux builds seem to be failing due to something introduced by this patch, not transient CI issues.

Fedora:
https://ci.trafficserver.apache.org/job/Github_Builds/job/fedora/881/console

```
In file included from /usr/include/signal.h:328,
                 from ../../../tests/include/catch.hpp:8034,
                 from unit_tests/unit_test_main.cc:25:
../../../tests/include/catch.hpp:10822:58: error: call to non-'constexpr' function 'long int sysconf(int)'
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from ../../../tests/include/catch.hpp:8034,
                 from unit_tests/unit_test_main.cc:25:
/usr/include/unistd.h:640:17: note: 'long int sysconf(int)' declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from unit_tests/unit_test_main.cc:25:
../../../tests/include/catch.hpp:10881:45: error: size of array 'altStackMem' is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [Makefile:974: unit_tests/test_tscpputil-unit_test_main.o] Error 1
make[2]: Leaving directory '/home/jenkins/workspace/Github_Builds/fedora/src/src/tscpp/util'
make[1]: *** [Makefile:1313: check-am] Error 2
make[1]: Leaving directory '/home/jenkins/workspace/Github_Builds/fedora/src/src/tscpp/util'
make: *** [Makefile:865: check-recursive] Error 1
```

RockyLinux:
https://ci.trafficserver.apache.org/job/Github_Builds/job/rocky/279/console

```
FAIL: test_librecords
=====================

/home/jenkins/workspace/Github_Builds/rocky/src/lib/records/.libs/test_librecords: error while loading shared libraries: libssl.so.81.1.1: cannot open shared object file: No such file or directory
FAIL test_librecords (exit status: 127)
```

**Comment by bneradt** [comment]
Through no fault of this PR, the 9.1.x branch needs a few PRs merged in before these unit tests will build and run with the fedora:35 and rockylinux compilers:

* #8231 
* #8683 
* #8814

Once those test-only changes are merged in, then the unit tests should finish successfully for this PR (they did for me locally).

**Comment by jp557198** [comment]
> Fixes #8807. I've asked Jeremy Payne, jp557198, to test and comment here as he is the issue owner.
> 
> This was originally fixed in ATS 9.2.x with PR #8365 but #8365 was big and not backported to 9.1.x as it was a late PR and zwoop did not want to bring it into 9.1.x at that time.
> 
> Anyway, this fixes the issue where the failure count on a parent is not incremented properly.

I tested your code changes against our internal branch. Failure threshold now increments as expected.
See below debug output confirming the same.

https://github.com/apache/trafficserver/issues/8807#issuecomment-1115427593

**Comment by ywkaras** [comment]
[approve ci fedora]

**Comment by randall** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci autest]

**Pull request closed without merging**
