### PR TITLE
Fix unused parameters in tscore

### PR DESCRIPTION
**Pull request by freak82**
Add `[[maybe_unused]]` to unused parameters in the `tscore` functionality

### CODE REVIEW

**Comment by JosiahWI** [comment]
The AuTest `http2_write_size_threshold` failed.

**Comment by JosiahWI** [comment]
[ci approve autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by freak82** [comment]
The same error happened before and [I was told that it's a `transient error`](https://github.com/apache/trafficserver/pull/11394#issuecomment-2133419606) and not related to the changes.

**Review by cmcfarlen — CHANGES_REQUESTED** [review]
For function parameters that are always unused, we should just remove the parameter name (or comment the name out with /* */).

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-unused

If conditionally unused due to constexpr or a macro we can use `[[maybe unused]]` to avoid the warning.

**Comment by freak82** [comment]
@cmcfarlen 
There was a discussion [here](https://github.com/apache/trafficserver/issues/11377) for the preferred way, that's why I'm doing it with `[[maybe_unused]]`.
I mean, I'm OK with any type as long as the final goal is achieved.

**Comment by maskit** [comment]
Some of the use may not be appropriate but I don't mind using `[[maybe_unused]]` for every place that compilers warn at this stage. This is just a step to enable the warning, and we should take another look more closely later. Some of the variables/arguments may be unnecessary at all. Then the caller side should be changed too. If we simply remove only the name, it'd be difficult to find parameter values that are unnecessarily passed.

Also, I don't like `ATS_UNUSED` macro. If some compiler supports `__attribute__((specialized_unused_attribute))` and we want to automatically switch to the special one, having the macro would make sense, but we don't have such a thing. It only costs time to check the implementation for nothing.

**Comment by cmcfarlen** [comment]
The current method in the code is to comment the name and add ATS_UNUSED.  This should be very easy to find later...

```
int
LogConfig::reconfigure(const char * /* name ATS_UNUSED */, RecDataT /* data_type ATS_UNUSED */, RecData /* data ATS_UNUSED */,
                       void * /* cookie ATS_UNUSED */)
{
```

This occurs a lot in the code already.  Shouldn't we stick to this?

**Comment by maskit** [comment]
The thing that would be hard to find is the caller side.

Let's say we have this function below. The second argument `bar` is obviously unused and it's not conditional.
```
int func(char *foo, char *bar) {
  return strlen(foo);
}
```

If we only look at the function definition, we may think we can change it like below
```
int func(char *foo, char *)
```

But then how do we find that this function call below passes the second parameter unnecessarily?
```
func("abc", generate_huge_data());
```

We should take a closer look and remove the second argument or stop calling the heavy function in this case if we can't remove the second argument.


What's the motivation to keep using ATS_UNUSED macro? It should be done in a constant way, but like I said, I don't see reasons to have the macro.

**Comment by cmcfarlen** [comment]
Just to be clear, I'm advocating for replacing `int [[maybe unused] parm` with `int /* parm ATS_UNUSED */` in this PR to match the existing notation for unused parameters.  I'm not advocating for using the `ATS_UNUSED` macro here.

**Comment by cmcfarlen** [comment]
Hello @freak82 , we discussed this at the review meeting and agreed that we should continue to use the `/* parm ATS_UNUSED */` style for unused parameters.  Could you update this PR to switch to that approach? Thank you for your help!

**Comment by freak82** [comment]
Hello @cmcfarlen,
Thank you for the update.
I'll update the pull request by the end of this week.

**Comment by freak82** [comment]
Updated this pull request with usage of `/* name ATS_UNUSED */` is it was suggested.
There is conditional compilation in the `ink_memory.cpp` and `ink_queue.cpp` and thus `[[maybe_unused]]` is used there.

**Comment by freak82** [comment]
Can't figure out why the Rocky build fails. Can somebody point me to the error because I can't find the reason.

**Comment by bneradt** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
It's the leak report from LSan. We are borrowing this to debug it.

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
We're finished messing with CI on this PR now. The leak is still showing up and our idea to clear the `ccache` data in case it was related had no effect.

**Review by cmcfarlen — APPROVED** [review]
Thank you for updating this!

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
