### PR TITLE
QUIC: sink path manager to stream manager

### PR DESCRIPTION
**Pull request by scw00**

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci Clang-Analyzer]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by maskit** [comment]
I think passing PathManager is too much. If we really needed to do so, I'd mark it as const.
How about introducing a context object?

**Comment by scw00** [comment]
Hi @maskit  I can not mark it as const, since `_check_verify_timeout` modify the member of QUICPathManager. It would be great to introduce the special interface for StreamManager to use.

**Comment by maskit** [comment]
[approve ci RAT]

**Pull request merged**
