### PR TITLE
Fix building without HWLOC

### LINKED ISSUE #11434: Build without hwloc broken on master
The build was broken by #11366, which used `#ifdef TS_USE_HWLOC` to check whether HWLOC was enabled. `TS_USE_HWLOC` is always defined to 0 or 1, so this will never evaluate to false when checked by the preprocessor. It should be `#if TS_USE_HWLOC`, as is done everywhere else in the codebase. I grepped for `#ifdef TS_USE` and found that this is is the only occurance in the codebase of this issue.

### PR DESCRIPTION
**Pull request by JosiahWI**
Fixes #11434.

### CODE REVIEW

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
The AuTest ja3_fingerprint failed. A PR to fix this already exists: #11432.

**Comment by JosiahWI** [comment]
Same failure was repeated.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
