### PR TITLE
Add better logging for origin_server_auth (#11885)

### PR DESCRIPTION
**Pull request by jasmine-nahrain**
Merge conflicts due to plugin rename in master

### CODE REVIEW

**Comment by jasmine-nahrain** [comment]
[approve ci freebsd]

**Comment by masaori335** [comment]
[approve ci freebsd]

**Comment by jasmine-nahrain** [comment]
[approve ci freebsd]

**Comment by jasmine-nahrain** [comment]
[approve ci osx]
[approve ci clang-analyzer]
[apprve ci autest1]
[apprve ci autest2]
[apprve ci autest3]
[apprve ci autest0]

**Comment by jasmine-nahrain** [comment]
[approvr ci osx]

**Comment by jasmine-nahrain** [comment]
[approve ci osx]

**Comment by jasmine-nahrain** [comment]
[approve ci clang-analyzer]

**Comment by jasmine-nahrain** [comment]
[approve ci autest]

**Pull request merged**
