### PR TITLE
Adding plugin to test transaction/session order

### PR DESCRIPTION
**Pull request by lbordowitz**

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
plugins tests should go under /tests/plugins/[plugin name]

**Comment by lbordowitz** [comment]
@zwoop Could you add `httpd-tools` package to the build containers? The test I wrote requires `ab`, the Apache Benchmark tool. This shouldn't be merged without the tests running.

**Comment by zwoop** [comment]
I think I like test/plugins better than test/tools/plugins, but I don't care strongly.

**Comment by lbordowitz** [comment]
Okay, I moved it to test/tools/plugins. This is a much more convenient directory, as there's an existing variable for compiling/adding plugins in qa tests.

**Comment by shinrich** [comment]
Same comment as for PR #2173, I think it would be useful to have a version of the test that just make some curl requests for installations without ab.  This would be in addition to your current test case no instead of.

Ultimately, we should do Http2 client requests as well, but that is probably another PR.

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by lbordowitz** [comment]
I'm a little uneasy about this PR and #2137, considering they have a "sleep so that stats are propagated" race condition built into them. Is there a better way to do this?

**Comment by bryancall** [comment]
@lbordowitz What should we do about this?

**Comment by lbordowitz** [comment]
I don't know! I feel like there should be a change on the traffic manager or something to give stat versioning by timestamp, just so there's no race condition. But that also feels like over-engineering...

**Comment by maskit** [comment]
Please run `make autopep8` if we are going to merge this.

**Comment by lbordowitz** [comment]
@maskit @bryancall Okay, done. The tests wait until the records.snap file exists. I plan on adding this to autest proper.

**Comment by maskit** [comment]
[approve ci]

**Comment by lbordowitz** [comment]
@maskit @bryancall in the latest commit, I have run `make autopep8`.

**Pull request merged**
