### PR TITLE
Fixed AuTests breaking when run outside a virtualenv

### PR DESCRIPTION
**Pull request by ocket8888**
I changed a bunch of subprocess that call `python` or `python3` to call `sys.executable` instead. I also added a little bit of type hinting in `autest-site/`.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by ocket8888** [comment]
The failed test output looks like capitalization issues to me, but I could be wrong.

**Comment by dragon512** [comment]
@ocket8888 Can you fix this up so it can merge again. I will try to review ASAP after that.

Thanks!

**Comment by bryancall** [comment]
It looks like this PR still needs some work and hasn't been updated for a few months.  Closing for now.  Please reopen if there are updates.

**Pull request closed without merging**
