### PR TITLE
Replace python with python3 in AuTest

### LINKED ISSUE #6386: Inconsistency use of python command in AuTest
Both of `python` and `python3` are used in AuTest. On platforms which `python` command refers to v2.x, AuTest mixing python versions.

- e.g.
`python`
https://github.com/apache/trafficserver/blob/b67060751ed8b62a437c14ff545f1bb71ef53ec7/tests/gold_tests/body_factory/http_with_origin.test.py#L76-L77
`python3`
https://github.com/apache/trafficserver/blob/b67060751ed8b62a437c14ff545f1bb71ef53ec7/tests/gold_tests/tls/tls_0rtt_server.test.py#L144

### PR DESCRIPTION
**Pull request by masaori335**
Fix #6386

Ran below command
```
find . -name "*.py" | xargs sed -i '' s/"python "/"python3 "/g
```

### CODE REVIEW

**Comment by ywkaras** [comment]
Maybe we should add this to the beginning of autest.sh?
```
if [[ $(which python) != "" ]]; then
  if [[ $(python --version) != Python?3*  ]]; then
    echo "Must use Python version 3 only" >&2
    exit 1
  fi
fi
```

**Comment by masaori335** [comment]
@ywkaras IIUC, `test-env-check.sh` is checking the version & requires 3.5+.

**Comment by masaori335** [comment]
I'm going to change to use `sys.executable` instead of `python` or `python3` as @dragon512 recommended on slack.

**Comment by ywkaras** [comment]
What I'm suggesting is different, that the Au test framework require that the python command run python version 3.x.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
Fwiw, I think a better approach would be to 1) enforce python3 by autest (as suggested above) and 2) make sure that any subsequent invocations of python to exec() the same python, which then properly enforces the same python version.

**Pull request merged**
