### PR TITLE
TS-5006: Fix CID 1306780

### PR DESCRIPTION
**Pull request by PSUdaemon**
Only release if not NULL.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1085/ for details.

**Comment by zwoop** [comment]
You should use the Jira number.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/977/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1092/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/984/ for details.

**Pull request merged**
