### PR TITLE
TS-4429: Adds a --concise (-C) option for logstats, excludes % metrics

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1117/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1224/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1118/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1225/ for details.

**Comment by gtenev** [comment]
👍 looks reasonable to me, it would reduce the amount of data to transfer/store without post-processing of the `traffic_logstats` output

**Pull request merged**
