### PR TITLE
Added (Estimated) Round Trip Time access log fields

### PR DESCRIPTION
**Pull request by acaciocenteno**
Possibility to add client and server RTT times to access log (configure flag --enable-rtt).

### CODE REVIEW

**Comment by bryancall** [comment]
The kernel's measured RTT times are inaccurate do to delayed ACKs.

**Comment by bryancall** [comment]
Talking at the github meeting on this.  This logs two fields from tcp_info and we would like to have access to log all the fields from tcp_info.

**Comment by zwoop** [comment]
@acaciocenteno Any chance you will work on this, and generalize this concept?

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
.

**Comment by zwoop** [comment]
Going to close this, since there's been no traction on this in a long time.

**Pull request closed without merging**
