### PR TITLE
TS-4498 Remap plugin initialization failure error messages (back-port).

### PR DESCRIPTION
**Pull request by pbchou**
@jpeach -- James, we would like to request a back-port of this commit to 6.2.x. Thanks.

### CODE REVIEW

**Comment by pbchou** [comment]
Confirmed no conflict on the cherry-picked commit. The second commit was due to clang-format differences between 7.0.x and 6.2.x.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1137/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1030/ for details.

**Pull request merged**
