### PR TITLE
NextHop Strategy Refactor and Fixes

### PR DESCRIPTION
**Pull request by rob05c**
This is a collaboration between @jrushford and me. This:
- Refactors the NextHopSelectionStrategy interface to simplify and prepare for Plugins (John's work)
- Refactors Strategy Markdown logic, to simplify, encapsulate, and also prepare for Plugin usage
- Fixes strategies.yaml parent errors with 4xx to not mark down and 5xx to mark down, matching parent.config behavior
- Fixes strategies.yaml markdown to include the port, to not mark down parents with the same hostname and different ports, matching parent.config behavior
- Fixes strategies.yaml ignore_self_detect 
- Fixes  strategies.yaml hash_string override

Includes unit tests for the above fixes.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by vmamidi** [comment]
Please squash the commits and resolve the conflicts.

**Comment by rob05c** [comment]
>Please squash the commits and resolve the conflicts.
Done

**Comment by jrushford** [comment]
[approve ci autest]

**Pull request merged**
