### PR TITLE
Optimize: randomized the purging operation by hrtime()

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by zwoop** [comment]
I understand what this does (random start point of n), but what's the net effect and gain from doing this? How is it a performance improvement?

**Comment by scw00** [comment]
That might cause infinite loop.

We should purge something here, right ? That means we need to purge at least one `Dir` to satisfy the `dir_insert`.

**Comment by scw00** [comment]
Close this pr since it increase the risk to fall into an infinite loop.

**Comment by scw00** [comment]
link to #5145

**Pull request closed without merging**
