### PR TITLE
Enhance Connection Collapse in ATS core - back port to 8.x

### PR DESCRIPTION
**Pull request by sudheerv**
Add an option to support cache open read retry on a write lock
failure. With this option, as long as read-while-writer is set
up following the guidelines in the docs, there should be no need
for any plugins to augment the core. Eventual plan is to deprecate
collapsed_forwarding plugin with this new support.

For more context on this, see
https://cwiki.apache.org/confluence/display/TS/Presentations+-+2019?preview=/112821251/132320653/Collapsed%20Forwarding%20.pdf

### CODE REVIEW

**Comment by sudheerv** [comment]
@zwoop @ezelkow1 @bryancall @vmamidi  - 8.x back port for collapsed fwd in core

**Comment by ezelkow1** [comment]
[approve clang-format]

**Comment by ezelkow1** [comment]
[approve ci clang-format]

**Comment by ezelkow1** [comment]
@sudheerv probably need a clang fixup

**Comment by randall** [comment]
[approve ci clang-format]

**Comment by sudheerv** [comment]
> @sudheerv probably need a clang fixup

@ezelkow1 apparently, clang is broken in 8.x.

**Comment by bryancall** [comment]
Original PR is: 180f723c869c5e999ea9785d47052ccb6acae9af

**Comment by bryancall** [comment]
I reverted this on the 8.0.x branch for now until the 8.0.6 release is out:
```
commit 6ed35bcb8e042cb383aeca79863bdaaa8e4a828d (HEAD -> 8.0.x)
Author: Bryan Call <bcall@apache.org>
Date:   Mon Feb 10 11:14:50 2020 -0800

    Revert "Enhance Connection Collapse in ATS core"

    This reverts commit f76c4c77b09ca0675a82c2a0b50b0699bad8a43f.
```

**Comment by zwoop** [comment]
I've reverted the revert, hence, this is now restored on the 8.1.x branch (but not 8.0.x!).

**Pull request merged**
