### PR TITLE
Removing inert code: LogFile::do_filesystem_checks()

### PR DESCRIPTION
**Pull request by a-canary**
This code has been disabled since 
   65477944 - Leif Hedstrom        2015-03-21
Now I kill it with fire.
I think it has been replaced with LogFile::check_fd().

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
"Inert"

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Yeh, this looks like dead code to me too. But please set Labels, assigned, Milestones etc. before merging.

**Pull request merged**
