### PR TITLE
TS-4579: Add hook-trace example plugin.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/335/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/229/ for details.

**Comment by zwoop** [comment]
Looks fine. Out of curiosity, why the "clang-format off"? Does it not format as you'd expect? I ask, because I'd definitely prefer that we avoid turning off clang unless it truly messes shit up badly. :-).

**Comment by jpeach** [comment]
clang-format arranges the array initializers across the page like this:

```C
foo array[] = {
    one, two, three,
    four, five
};
```

**Pull request merged**
