### PR TITLE
TS-1774 Moved gethrtime functions into Thread class

### PR DESCRIPTION
**Pull request by danobi**
Moved ink_get_hrtime() and ink_get_based_hrtime() into the Thread.cc class as opposed to them being an extern function in P_Thread.h. Also made them static functions. Fixed the rest of the code base to refer to new functions. 
Running 'make test' seemed to work. 

Please let me know if anything is wrong, I'd be happy to correct any errors. Also please let me know if this change actually makes sense, because with my limited knowledge this was the only solution I could come up with.

### CODE REVIEW

**Comment by jpeach** [comment]
Doe we even need the new Thread APIs? Can we just use Thread::cur_time directly?

**Comment by SolidWallOfCode** [comment]
Isolation and modularity? It seems better to discuss this on the original bug - it's not really a problem with the pull request.

**Comment by SolidWallOfCode** [comment]
Sorry for the delay, I got distracted. I think it's OK except the method name should be just "get_hrtime()", there's no need for the "ink_" prefix if it's a method.

**Comment by danobi** [comment]
Fixed. However, I am unsure how to handle all the merge conflicts.

**Comment by SolidWallOfCode** [comment]
I think the most likely cause is the code base was reformatted and you're being hit by that. You need to reformat you code base to match before trying to rebase. You can find them here - https://bintray.com/apache/trafficserver/clang-format-tools/view

**Comment by danobi** [comment]
Fixed the merge conflicts. Also updated any other uses of ink_get_hrtime() / ink_get_based_hrtime() that occurred during the life of this PR. 

There's quite a few commits now, let me know if this should all be squashed.

**Comment by bryancall** [comment]
https://issues.apache.org/jira/browse/TS-1774

**Pull request closed without merging**
