### PR TITLE
Add TSSslContextCreate method

### PR DESCRIPTION
**Pull request by biilmann**
TSSslContextCreate returns a new SSL Context that's configured according to
the settings in records.config

This is useful if an extension wants to use the TS_SSL_CERT_HOOK to
control loading of SNI certificates, and still want to respect the
cipher suite and related SSL settings.

The current experimental plugin for loading SSL certificates just use [SSL_CTX_new(SSLv23_client_method())](https://github.com/apache/trafficserver/blob/f54fbd5bf426c8ff42c16422e9b0708f79c3745e/plugins/experimental/ssl_cert_loader/ssl-cert-loader.cc#L156) to create a new context, and doesn't respect the cipher suite settings in records.config.

The meat of this implementation is in SSLCreateServerContext and could be cleaned up a lot, since there's a lot of repetition between this method and ssl_store_ssl_context. Ideally I would refactor that method to separate context initialization and configuration from inserting the context into the SSLCertLookup. Just wanted to check first to see if there is support for adding the new TSSslContextCreate API method...

### CODE REVIEW

**Comment by jpeach** [comment]
>  Ideally I would refactor that method to separate context initialization and configuration from
> inserting the context into the SSLCertLookup

Yeh that is the way it is supposed to work, but the separation has faded over time and it is a bit of a jumble now :(

**Comment by biilmann** [comment]
I've done a bit of cleanup to get anything not related to storing the ssl context moved from `ssl_store_ssl_context` and into `SSLInitServerContext`.

**Comment by jpeach** [comment]
This looks pretty reasonable to me. @shinrich, what do you think?

In ``ts/ts.h``, ``TSSslContextCreate()`` needs to be ``TSSslContextCreate(void)``.

Once a plugin calls ``TSSslContextCreate()``, does it make sense for it to have to call ``SSL_CTX_free()``? I'm probably OK with that as long as we document.

Does it make sense to also hoist the session ticket initialization up into ``SSLInitServerContext()``?

Since this is a change to the public API we need to do an [API review](https://cwiki.apache.org/confluence/display/TS/API+Review+Process) on the dev@ list.

**Comment by biilmann** [comment]
Changed the type signature to `TSSslContextCreate(void)` now.

It generally makes sense that a plugin that needs this method will want to handle the call to free the context as well. However, adding a `TSSslContextDestroy` function would probably make this more obvious and would mirror the semantics of other functions like `TSIOBufferCreate` and `TSIOBufferDestroy`...

**Comment by shinrich** [comment]
Looks good to me as well.  Seems like a good and necessary change.

I assume that the bulk of the diff'ed lines in SSLUtils are due to just moving functions ahead of use and the functions themselves are unchanged (e.g., asn1_strdup).

**Comment by biilmann** [comment]
> I assume that the bulk of the diff'ed lines in SSLUtils are due to just moving functions ahead of use and the functions themselves are unchanged (e.g., asn1_strdup).

Yes, the actual changes in SSLUtils is moving some setup related code from `ssl_store_ssl_context` into `SSLInitServerContext`, adding a new `SSLCreateServerContext` wrapper method and then moving `SSLInitServerContext` down below the functions it now depends on.

**Comment by shinrich** [comment]
I think this looks good, and I'd be willing to do the merge, but I think you still need to send around an API review notice to the dev mailing list as jpeach suggested.

**Comment by biilmann** [comment]
@shinrich I'll send out an API review notice. Before that, what's your thoughts on adding a `TSSslContextDestroy` method to clarify that it's up to the plugin to eventually free the context?

Another issue is what @jpeach mentioned around session ticket initialization. I've been digging into this a bit, and I think it would be best to expose some separate methods around session ticket handling. It's actually something it would be really valuable for plugins to hook into. An important use case would be to coordinate key creation and rotation amongst several ATS servers in a CDN PoP, etc..

**Comment by shinrich** [comment]
Yes, I agree that having a matching TSSslContextDestroy is a good idea even if it is just a wrapper for the openssl call at this point.

I also like the idea of adding hook points to aid in coordination of session ticket handling.  I had proposed something similar for coordinating ssl session state between servers (TS-3527).  I had initial code but met with resistance to the idea and got pulled into other things.  But I'd be very interested in coming back to that and making session restarts work better in a multi-server environment.

**Comment by jpeach** [comment]
To @jpeach to shepherd.

**Comment by jpeach** [comment]
@biilmann The next thing we need here is an [API review](https://cwiki.apache.org/confluence/display/TS/API+Review+Process) posted to the dev@ list. It would also are very helpful to add a simple API reference page to the documentation. There are a number of examples [here](https://github.com/apache/trafficserver/tree/master/doc/developer-guide/api/functions).

Once we have the API review done, I can get this integrated.

**Comment by zwoop** [comment]
@biilmann Can you email something to the dev@ mailing list with the API proposal, for a review? See the link above for the process.

**Comment by jpeach** [comment]
Closing in favor of #594.

**Pull request closed without merging**
