### PR TITLE
Doc: traffic_manager - Add documentation for exp backoff and config.

### PR DESCRIPTION
**Pull request by brbzull0**
Adding documentation for
- exponential backoff delay
- exponential backoff notes for `traffic_manager` program.

Logic change: [PR6481](https://github.com/apache/trafficserver/pull/6481)

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
[ci approve]

**Comment by randall** [comment]
[approve ci centos]

**Comment by bryancall** [comment]
[approve ci docs]

**Pull request merged**
