### PR TITLE
(TS-3961) open source Yahoo's ats-multiplexer plug-in

### PR DESCRIPTION
**Pull request by dmorilha**

### CODE REVIEW

**Comment by PSUdaemon** [comment]
This belongs under the experimental directory.

**Comment by PSUdaemon** [comment]
I should also add this looks very interesting and thanks for contributing it!

**Comment by zwoop** [comment]
This also must be run through clang-format first.

**Comment by dmorilha** [comment]
@zwoop will work on these items later, thanks

**Comment by zwoop** [comment]
Great, thanks!

**Comment by bgaff** [comment]
@dmorilha , thanks!

**Comment by dmorilha** [comment]
All comments addressed so far, please let me know if there is anything you guys want me to work on before merging. Thanks

**Comment by PSUdaemon** [comment]
@dmorilha, this looks pretty good. I am almost ready to commit it. Can you add one last change? Please update the NOTICES file. Then I will merge.

Thanks.

**Pull request closed without merging**
