### PR TITLE
TS-3977: Merge cache-key-genid plugin

### PR DESCRIPTION
**Pull request by ftarnell**

### CODE REVIEW

**Comment by ftarnell** [comment]
This replaces #308.

**Comment by bryancall** [comment]
@ftarnell Can you please rebase this?

**Comment by mlibbey** [comment]
Hopefully we can get some documentation for this?  Describe the problem its trying to solve; how to use it; how to configure; what configuration parameters exist and what they mean, etc.

**Comment by LionsAd** [comment]
If anyone else wonders what this does:

This plugin allows you to use a Kyoto database to increase genid per hostname, hence expiring the cache for a full domain using the zero cost mechanism to set the genid in the cache key.

The additional overhead for the plugin is:

- Parse hostname from given url
- Check kyoto DB for genid for the given host [DB lookup]
- Set genid for the cache key dynamically

This plugin takes just one argument:

- The path to the genid kyoto DB

I presume GoDaddy uses this in combination with a purge plugin like remap_purge to write values to the Kyoto DB to expire whole domains.

**Pull request closed without merging**
