### PR TITLE
UUID Proposal

### PR DESCRIPTION
**Pull request by acaciocenteno**
@SolidWallOfCode sorry for the delay. See if this is what you want. Let me know if you need me to change anything.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
Re: [trafficserver] UUID Proposal (#199)


I'll take a look. Can you close out PR 106, since this supercedes that? I don't want to close it out from under you. Thanks.

**Comment by zwoop** [comment]
I'll take a look at this. Is there a Jira for this?

**Comment by zwoop** [comment]
Ping. Can we get a Jira for this? I'm ready to start working on this, sorry for the delay.

**Comment by zwoop** [comment]
In addition to the proposals here, I think we should generalize this concept. There are many other use cases for this approach, such as replacing the IP in the Via header with he "machine" UUID. As such, we should make this generically available.

**Comment by bryancall** [comment]
Talking at the github meeting on this.  It shouldn't use boost and the code needs some cleanup.

**Comment by bryancall** [comment]
@zwoop volunteered to shepard this pull request.

**Comment by zwoop** [comment]
Ping @acaciocenteno Are you still working / interested in this? We all want this, just needs a little tweaking, and generalize the UUID functionality to be a core component.

**Comment by silentdai** [comment]
@zwoop 
I am working with @SolidWallOfCode and we need this feature. Would you mind if I take this work?

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
.

**Comment by zwoop** [comment]
I'm going to start doing some work on this, unless I here back, I'll close this PR once I've incorporated the changes we want to retain from here. I'll of course make sure to attribute the contributions accordingly.

**Comment by zwoop** [comment]
I'm going to close this one. I have landed the plumbing for UUID in various components. @acaciocenteno  if you want these changes on the HttpSM debug statements, can you open a Jira please?

**Pull request closed without merging**
