### PR TITLE
Parent selection 2.0

### PR DESCRIPTION
**Pull request by jrushf1239k**
This is a refactor of Parent Selection to add the following features:

1) multi-site origin - using parent selection, origin servers may be selected using round robin or consistent hash algorithms.

2) simple retry - if the parent is an origin server and a 404 response is received when this feature is enabled, the transaction will be retried using another parent.  The user may define a list of response codes for simple retry.  Both enabling and defining response codes may be done using header_rewrite on a delivery service basis.

3) dead server retry - if the parent is an origin server and a 503 response is received when this feature is enabled, the current parent is marked down for 5 minutes and the transaction will be retried using another parent.  The user may define a list of response codes for dead server retry.  Both enabling and defining response codes may be done using header_rewrite on a delivery service basis.

4) Added a secondary_parent list to parent.config when round_robin=consistent_hash.  The secondary parents are added to a secondary hash ring for parent selection when a primary parent is down.  In a cache hierarchy this would allow you to take advantage of another set of mid tier caches content affinity when a primary parent is down, see TS-3418.

I refactored Parent Selection using a Strategy design pattern where the Round robin and consistent hash implementations are in there own class.  These strategy implementations are created per row in parent.config when the traffic server starts and reads the parent.config file.  This refactor made it easier to add the secondary hash feature.

I plan on doing a presentation of all this at the ATS summit this month.

thanks

### CODE REVIEW

**Comment by jpeach** [comment]
I think that we really need to break this feature down into smaller commits before we can digest and merge it. Right now the only way I can see doing it is if we squash it all into one or two very large commits, which is risky and hard to review and test. I'm happy to help break it down, grab me on IRC or at the summit.

**Comment by SolidWallOfCode** [comment]
I am getting this compiler error when building -
{code}
../../proxy/ParentSelection.h:164:7: error: ‘class ParentSelectionStrategy’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class ParentSelectionStrategy
{code}

**Comment by jrushf1239k** [comment]
I fixed that, ParentSelectionStrategy now has a virtual destructor.

**Comment by jpeach** [comment]
John and I spoke about how we can get this merged. The plan we came up with is to make a separate pull request that contains just the major strategy pattern refactoring with no changes in behavior. We can review and QA this change and it should be fine. Once that is in, we can add the changes that implement the features, and this code should be easier to review.

**Pull request closed without merging**
