### PR TITLE
TS-4724: Added new server_request APIs to set/get host name and schem…

### PR DESCRIPTION
**Pull request by brkishore**
…e in ts-lua plugin.

(cherry picked from commit a6c7f3311895b1d342c32618638937626422fd04)

### CODE REVIEW

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1051/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1158/ for details.

**Comment by shukitchan** [comment]
looks good. 👍

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1055/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1162/ for details.

**Comment by PSUdaemon** [comment]
@brkishore Can you please check into that Linux build failure?

**Comment by shukitchan** [comment]
yeah... just one extra empty line that clang-format does not like.

**Comment by brkishore** [comment]
Yes. I have deleted the extra empty line and amended the commit. Please re-run the build. Hope this should be okay.

**Comment by shukitchan** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1176/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1069/ for details.

**Pull request merged**
