### PR TITLE
Ts 4309

### PR DESCRIPTION
**Pull request by shinrich**
Fixes for TS-4309.  Incomplete because the fixes depended on event loop code.  This is the part that cleaned up the ssl read/write loops.  This might fix the ASAN reported in TS-4424.  At least it should make the ASAN easier to debug by simplifying the relevant code.

### CODE REVIEW

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Build triggered. sha1 is merged.

**Comment by atsci** [comment]
Build started sha1 is merged.

**Comment by atsci** [comment]
Build finished.

**Comment by zwoop** [comment]
Hmmm, so, this build failed with wrong clang-format, I'll investigate how to get it to produce proper errors.

**Comment by atsci** [comment]
Build triggered. sha1 is merged.

**Comment by atsci** [comment]
This build failed, please check Jenkins for details.
 No test results found.

**Comment by shinrich** [comment]
I probably forgot to run clang format on it.  Will clang-format and push again.

**Comment by zwoop** [comment]
Yep, no problem. I just used this PR to test the new automated Jenkins builds :-).

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux (CentOS7) build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-Linux/15/

**Comment by shinrich** [comment]
Wasn't working on the latest greatest when creating this branch.  Closing this PR and opening a new one on a new branch.

**Pull request closed without merging**
