### PR TITLE
TS-4925: Manager pollMgmtProcessServer stuck with EBADF.

### PR DESCRIPTION
**Pull request by jpeach**
If the select in pollMgmtProcessServer fails with an actual error
(EBADF, for example), it just returned back into the select loop
and was unable to recover. This might happen if the server file
descriptor is -1, or otherwise stale.

The fix is to not put -1 into the select set, and to break the loop
if select returns an error.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/923/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/817/ for details.

**Comment by zwoop** [comment]
@gtenev  Can you review this please?

**Comment by zwoop** [comment]
I'd imagine this is a backport candidate for at least 7.0.0, maybe 6.2.x ?

**Comment by jpeach** [comment]
@zwoop It is a race that happens when ``traffic_server`` keeps failing to start. 7.0 would be good but not sure we need to bother with 6.2

**Pull request merged**
