### PR TITLE
Add tsapi Au test.  Initially just testing TSHttpTxnEffectiveUrlStringGet() function.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by zwoop** [comment]
I'm not -1 on this, but I'm a little dubious that it's reasonable to test a lot of InkAPI in an end-to-end test like this. The performance on autest is magnitudes worse than the existing "traffic_server -R" tests, and we already test other similar APIs to this one in there. Adding a test for TSHttpTxnEffectiveUrlStringGet() into InkAPITest.cc would not be difficult.

Fwiw, the problem is that autest currently takes 20 minutes to run, up over 300% compared to a year ago. It's a non scalable solution as is, and we're getting to the point where it's becoming a serious bottleneck.

**Comment by zwoop** [comment]
Fwiw, the autest for this particular PR took 22 minutes, up 10% over existing "master" runs :-/.

**Comment by zwoop** [comment]
@bryancall I think we have to have some design decisions/discussions over the future of autest, so I'm going to "-1" this for now, so we don't land this before such a discussions.

**Comment by ywkaras** [comment]
Running in a Fedora docker container on My MacBook the test takes about 5 seconds.

I have heard some talk that the regression tests are crufty and we should explore alternatives.

**Comment by ywkaras** [comment]
I ran autest with the -f option, listing every current existing test.  Seems to be working fine.  If the CI test is taking too long, maybe we should run an explicit list of selected Au tests, rather than blocking new tests from the repo.

**Comment by bryancall** [comment]
I talked to @zwoop about this yesterday and I agree that testing the APIs with autest is a bad idea for performance reasons.

We have a have regression tests already for testing the C APIs and it seems like it would be easy to add this test to the existing API test instead of creating an entirely new way of testing the C APIs.

**Comment by ywkaras** [comment]
In any case, if this particular (short) Au test takes 2 minutes in a test environment that will be use routinely used, I don't that's an issue that's resolved by rejecting this PR.

**Comment by ywkaras** [comment]
I'll wait a bit to see if @SolidWallOfCode or @dragon512 want to opine before I close this.

**Comment by SolidWallOfCode** [comment]
Every time I have presented on this at summits, I have stated that one of the main goals of the testing work is to get rid of the regression tests, which IMHO are unmaintainable and flaky, particularly anything involving the synthetic client / server code. Given the absence of any objections and acceptance of the overall plan, I have been directing this work toward eliminating the regression tests. There has been a series of PRs removing tests from the regression tests elsewhere. I wasn't aware there had been a change in this policy.

My view is that if the API is to be tested, it should be done either in a unit test style to focus on just the API, or in a full up style as in AuTest. The kind of half way, completely unlike any sort of actual run time environment that exists in the regression tests, I consider clearly inferior. One might also ask, when was the last time any new regression test was actually written?

**Comment by ywkaras** [comment]
@SolidWallOfCode So do you think this PR is a move in the right direction or do you suggest some third approach?

**Comment by SolidWallOfCode** [comment]
I think there is a real concern here about performance, but I think that would be better addressed in different ways.

*  One would be to use this as the base for extensive plugin API testing, to be more efficient, rather than separate tests for small subsets of the API.
*  One of the goals of the dormant RPC replacement work was to reduce the delays currently inherent in this testing, which are far more artifacts of TS than any thing in the testing framework. For instance, the ability to force log flushes would speed up a lot of tests, and faster interactions between `traffic_ctl` and the core would also help.

**Comment by ywkaras** [comment]
If this single short test adds 10% (~ 2 minutes) to @zwoop 's autest CI check, I think there's something about the environment that the check is running in that's inhospitable to autest as currently implemented.

**Comment by SolidWallOfCode** [comment]
Walt's doing some work for us on internal testing, should he perhaps look at the current ASF testing and see what can be combined? I've also been doing some work with better unit testing because I think overall unit tests are faster even than the old regression testing, if they can be made to work. That work is unfortunately not currently available because it depends on other precursor PRs.

I really do think if we upgraded the RPC to be bidirectional and more synchronous, and could do synchronous log flushing, we could eliminate most (or almost all) the timing delays currently in the tests. 5 or 10 seconds isn't much, but that's a minute per 12 or 6 tests, which adds up quite fast.

**Comment by ywkaras** [comment]
Can we configure log flushing to happen more frequently / quickly?

**Comment by ywkaras** [comment]
@mlibbey don't understand about the for loop.  @zwoop indicates he has managed to time the tests.  Why can't we use the 'time' command for more precise timing if necessary.

**Comment by ywkaras** [comment]
A possibility is to create a tool that in turn uses an existing code coverage tool.  It would run each Au test to identify the .cc and .c files it ran code from.  When a PR was submitted, the CI check would only run the Au tests that ran code in the .cc/.c files that were changed, or ran code in a .cc/.c file that included a header that was changed.

**Comment by zwoop** [comment]
No, I did time it, Jenkins times he completion of every job, it’s part of the job results

**Comment by ywkaras** [comment]
Does that mean you owe Jenkins sushi?

**Pull request merged**
