### PR TITLE
Remove configure option --max-api-stats which does not do anything. S…

### PR DESCRIPTION
**Pull request by 15ljindal**
…hould have been removed as part of commit ea1fb0c87261b1fbf375fa6ade26deda1d01995b

### CODE REVIEW

**Comment by shukitchan** [comment]
[approve ci]

**Comment by sudheerv** [comment]
change looks good to me, will give a +1 once CI is done.

**Comment by randall** [comment]
The change was removed as part of cba8b22ad53e62a9a08443330c74f5ccbd3f3f6d

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
