### PR TITLE
TS-4442: Fix code coverage.

### PR DESCRIPTION
**Pull request by jpeach**
This fixes the code coverage configuration and removes calls to ``_exit`` that prevent coverage data being emitted. Note that we assume the fix for [TS-4441](https://issues.apache.org/jira/browse/TS-4441) and replace a couple of manual exits with ``Fatal``.

### CODE REVIEW

**Comment by jpeach** [comment]
[approve ci]

**Comment by jpeach** [comment]
[ci approve]

**Comment by atsci** [comment]
Test from Jenkins

**Comment by zwoop** [comment]
@bryancall Wasn't there a reason why we changed to _exit() again?

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
Same here, did you really intend for these branches to get pushed into the main repo?

**Pull request merged**
