### PR TITLE
Test: add nameserver to proxy_serve_stale test

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Review by ywkaras — DISMISSED** [review]

**Comment by maskit** [comment]
[approve ci autest]

1post-early-return` faild.

**Comment by maskit** [comment]
[approve ci autest 1 of 4]

**Comment by maskit** [comment]
[approve ci autest]

`remap_load_missing_failure` failed.
```
Reason: Returned Value -2 != 33
     file /tmp/sandbox/remap_load_missing_failure/ts/log/diags.log : Diags log file diags.log should not contain errors - Failed
        Reason: Cannot read /tmp/sandbox/remap_load_missing_failure/ts/log/diags.log: [Errno 2] No such file or directory: '/tmp/sandbox/remap_load_missing_failure/ts/log/diags.log'
     file /tmp/sandbox/remap_load_missing_failure/ts/log/diags.log : Diags log file diags.log should not contain errors - Failed
```

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci autest]

**Review by ywkaras — APPROVED** [review]

**Comment by zwoop** [comment]
@maskit This has merge conflicts, like because of #8953. If you want this in 9.2.x, can you make a branch PR for 9.2.x please?

**Comment by maskit** [comment]
@zwoop I just made the PR for 9.2.x https://github.com/apache/trafficserver/pull/9070

**Pull request merged**
