### PR TITLE
TS-5107: init_customizations() isn't new in Docutils 0.13

### PR DESCRIPTION
**Pull request by jablko**
We can use it in 0.12 and 0.13.

@jsime Thanks for merging #1303. Sorry for the mistake! If you approve, can you please merge this correction?

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1395/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1289/ for details.

**Comment by jsime** [comment]
@jablko As much my fault as anything on #1303 for not testing against the same package versions as the doc server. This PR builds fine for me now with sphinx 1.4.8 and docutils 0.12.0. Thanks for the fixes!

**Comment by jablko** [comment]
@jsime Thank you!

**Pull request merged**
