### PR TITLE
Remove INKUDPXX api #6245

### PR DESCRIPTION
**Pull request by Jeffrin2005**

### CODE REVIEW

**Comment by bryancall** [comment]
The cleanup label is for us to describe what type of PR it is.  You don't have to do anything until someone reviews it and has feedback.

**Comment by ywkaras** [comment]
This isn't our usual procedure for deprecating parts of the plugin API.  For example, we are deprecating the C++ plugin API is ATS 10, and will remove it in ATS 11:  https://docs.trafficserver.apache.org/en/10.0.x/release-notes/whats-new.en.html#c-plugin-api-deprecated .

Also, for any changes to the plugin API, you should send a message on the developer mailing list describing them:  https://lists.apache.org/list.html?dev@trafficserver.apache.org

**Comment by ywkaras** [comment]
We discussed this in today's meeting about the ATS 10 release.  It was decided we should simply remove the INKUDPxxx function and types in release 10.  I think we should note the deletion in the "What's New" section of the Sphinx documentation.  The changes will have to go on three branches, 10.0.x, master, and 11-Dev, but I'm not sure in what order.  We should take care of this in the next few days, as release 10 is imminent.

**Comment by ywkaras** [comment]
Replaced by https://github.com/apache/trafficserver/pull/11171 .

**Pull request closed without merging**
