### PR TITLE
Fix for issue #7607 (efficient mapping between enum values and strings)

### PR DESCRIPTION
**Pull request by ywkaras**
https://github.com/apache/trafficserver/issues/7607

Provides utilities for handling values that can be represented as either a string or a number in
a 0-base range.

### CODE REVIEW

**Comment by ywkaras** [comment]
The CodeOrStr template may also be useful to efficiently handle sets of MIME headers.

**Comment by maskit** [comment]
Seems like overkill. To be honest, I don't want to maintain the utilities.

**Comment by ywkaras** [comment]
What do you propose as an alternative approach to resolve this issue?

**Comment by SolidWallOfCode** [comment]
I recommended bringing in `Lexicon` - http://docs.solidwallofcode.com/libswoc/code/Lexicon.en.html

**Comment by ywkaras** [comment]
I knew it was too good to be true that I'd get to overload the comma operator.

**Comment by ywkaras** [comment]
[approve ci Clang-Analyzer]

**Comment by ywkaras** [comment]
[approve ci Clang-Analyzer]

**Comment by maskit** [comment]
i"d just move the current strcmp logic into the callback function.

**Comment by ywkaras** [comment]
[approve ci]

**Comment by ywkaras** [comment]
https://i.gifer.com/HJ2q.gif

**Pull request closed without merging**
