### PR TITLE
Localized version of Boost.String_Ref.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1199/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1092/ for details.

**Comment by SolidWallOfCode** [comment]
A derivative of the Boost library has been adopted in to the standard library for C++17 making this forward compatible but ATS won't be able to depend on that for quite a while. Based on C++11 probably not until 2022 or so. Therefore I think it well worth the small effort to put this in now and clean it up later.

**Comment by SolidWallOfCode** [comment]
I've been working with this, because it was suggested as a replacement for `ts::ConstBuffer` which was standard (or would become so) rather than custom code. However, my experience so far is it is not a sufficiently rich API to be a reasonable replacement for `ts::ConstBuffer`. A primary use for the latter is token based parsing and that's noticeably more challenging with these variants of string references. Perhaps adding global overloaded functions to do the missing parts is the better approach?

**Comment by SolidWallOfCode** [comment]
Further work indicates that `string_ref` isn't going to be a suitable replacement for `ConstBuffer`. I will be taking a different approach.

**Pull request closed without merging**
