### PR TITLE
TS-3245: Allow multiple plugins to safely use getopt(3).

### PR DESCRIPTION
**Pull request by pbchou**
Request back-port to 6.2.x branch. This was cherry-picked from "master", and it was clean except for some spacing issues introduced by clang-format setting changes.

### CODE REVIEW

**Comment by zwoop** [comment]
For @PSUdaemon .

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/463/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/567/ for details.

**Comment by jpeach** [comment]
@pbchou Please add the version to the ``Backport`` field in the corresponding JIRA.

**Comment by PSUdaemon** [comment]
Please format this PR as outlined [here](https://cwiki.apache.org/confluence/display/TS/Fall+2016+Summit?preview=/65866590/66849961/git_back_port_cherry_pick.pdf).

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1136/ for details.

**Comment by pbchou** [comment]
@PSUdaemon - Resubmitted this PR branch as requested.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1141/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1034/ for details.

**Pull request merged**
