### PR TITLE
Coverity:  trying fixing some of the issues related to an unitialized variant member.

### PR DESCRIPTION
**Pull request by brbzull0**
Trying to fix some of the following CID issues:

1534738
1534732
1534699
1534727
1534717

not sure if this will work, but let's try.

### CODE REVIEW

**Comment by ywkaras** [comment]
I will be mean to Damiam about this.

**Comment by brbzull0** [comment]
> I will be mean to Damiam about this.

well, got used to already! this is sort of a shoot in the Dark! the issue seems to be inside the `std::variant` intialization. If this does not work, then I'll dig deeper.

**Comment by ywkaras** [comment]
None of there Coverity issues look valid.  If this doesn't work, we could just use the `#ifdef __COVERITY__`.

**Comment by cmcfarlen** [comment]
@brbzull0 Should we merge this?

**Comment by brbzull0** [comment]
> @brbzull0 Should we merge this?

@cmcfarlen done! Thanks

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
