### PR TITLE
Cache:ttl-in-cache should always override never-cache

### PR DESCRIPTION
**Pull request by garfieldonly**
link to #5200

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci autest]

**Comment by oknet** [comment]
@zwoop 

I can't find any documents to describe the priority of these settings.

Is the override correct ?

**Comment by oknet** [comment]
@garfieldonly please also update the document.

**Comment by oknet** [comment]
[approve ci]

**Pull request merged**
