### PR TITLE
Fixed issue with macOS Catalina and pcre 8.43 enabling pcre-jit

### PR DESCRIPTION
**Pull request by bryancall**
Created issue #6192 to look at this in the future if it is working again.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Potentially a 9.0.x candidate

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by masaori335** [comment]
It looks like this fixed #5243.

**Pull request merged**
