### PR TITLE
Issue #1367: HdrHeap potential corruption

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1375/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1268/ for details.

**Comment by zwoop** [comment]
@shinrich Should we cherry-pick this back to 7.1.x ?

**Comment by zwoop** [comment]
@maskit @shinrich ping? Should we back port to 7.1.x ?

**Comment by maskit** [comment]
I'm +1 on backporting to 7.1.x.
I took a quick look and it seems to be easy,  `git apply` fails though.

**Pull request merged**
