### PR TITLE
Doc: Add config file for Transifex Client

### PR DESCRIPTION
**Pull request by masaori335**
I created a new project on Transifex to internationalize documents.

- https://www.transifex.com/trafficserver/apache-traffic-server-6x/dashboard/

Transifex Client is a command line tool that enables to easily manage translation files.

- http://docs.transifex.com/client/

This is a configuration file for it and assume making 'pot' files with below.

```
$ sphinx-build -b gettext . _build/locale/pot
```

### CODE REVIEW

**Comment by maskit** [comment]
What is the reason why we need new project? Will we need new projects for 7.x?

**Comment by masaori335** [comment]
Yes, we need a project on transifex for each major version.
Transifex doesn't have any bench or versioning features.

**Comment by masaori335** [comment]
I'm going to write a docs about "I18N Documentation Flow" on Wiki

**Comment by masaori335** [comment]
I wrote about GitHub, ReadTheDocs and Transifex.
https://cwiki.apache.org/confluence/display/TS/Internationalize+Documentation

**Pull request closed without merging**
