### PR TITLE
Move Cleanup.h from plugins/xdebug to include/tscpp/api .

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
PRs that are dependent on this PR:
https://github.com/apache/trafficserver/pull/9063
https://github.com/apache/trafficserver/pull/9044
https://github.com/apache/trafficserver/pull/8790

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
[approve ubuntu]

**Comment by ezelkow1** [comment]
[approve ci ubuntu]

**Comment by serrislew** [comment]
Should Cleanup.h also be removed from `/plugins/xdebug/Makefile.inc`?

To confirm, this CPP API addition is to make these standard deleter/ptr definitions accessible for other plugins?

**Comment by ywkaras** [comment]
> Should Cleanup.h also be removed from `/plugins/xdebug/Makefile.inc`?
yes
> 
> To confirm, this CPP API addition is to make these standard deleter/ptr definitions accessible for other plugins?
yes

**Comment by ywkaras** [comment]
[approve ci autest]

**Review by serrislew — APPROVED** [review]

**Comment by randall** [comment]
I haven't seen this proposed to the mailing list yet. Did I miss the email?

**Comment by serrislew** [comment]
@randall there was an email titled "Proposed change to CPP API" a few weeks ago!

**Review by SolidWallOfCode — APPROVED** [review]

**Pull request merged**
