### PR TITLE
Allow for regex_remap of pristine URL.

### PR DESCRIPTION
**Pull request by ywkaras**
Adds a new optional pparam "pristine" to the regex_remap core plugin.  When present, this pparam causes
regex_remap to match on the pristine URL, and to use the pristine URL for $ substitutions.

### CODE REVIEW

**Comment by ywkaras** [comment]
Doc changes pending.

**Review by traeak — COMMENTED** [review]
for args would be better to use --pristine with optional arg?
--pristine the same as --pristine=true  OR --pristine=false to explicitly state default behavior?
Do we have any conventions for these args?

Otherwise the changes themselves look good.

**Comment by ywkaras** [comment]
> for args would be better to use --pristine with optional arg?
> --pristine the same as --pristine=true OR --pristine=false to explicitly state default behavior?
> Do we have any conventions for these args?
> 
> Otherwise the changes themselves look good.

Hmm do you mean @param=--pristine , or does the remap.config syntax allow for using -- before a parameter instead of @param?  None of the current regex_remap parameters us -- as a prefix.  The boolean parameters all use a "no-" prefix for false.  https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/regex_remap.en.html

**Review by traeak — APPROVED** [review]
It's consistent for this plugin.  When we start to yaml-ize all the configs we could visit plugin consistency across the board.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
