### PR TITLE
check if any of client cert path or file is null

### PR DESCRIPTION
**Pull request by persiaAziz**
fix for client cert loading problem

### CODE REVIEW

**Comment by persiaAziz** [comment]
please review @zwoop @SolidWallOfCode

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1430/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1323/ for details.

**Pull request merged**
