### PR TITLE
Backport f71b75e and 734aa31 from master to 6.2.x

### PR DESCRIPTION
**Pull request by shenzhang920**

### CODE REVIEW

**Comment by shenzhang920** [comment]
@maskit @PSUdaemon This is the new pull request (I did a merge instead of rebase last time, sorry about that).  Let me know if this is OK. Thanks!

**Comment by maskit** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1511/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1404/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/75/ for details.

**Pull request merged**
