### PR TITLE
Add config to disable http/0.9 over QUIC by default

### LINKED ISSUE #9749: Add a setting to disable HTTP/0.9 over QUIC
Have a configuration option to disable HTTP/0.9 support.  Disabled by default.

### PR DESCRIPTION
**Pull request by duke8253**
this resolves #9749

### CODE REVIEW

**Comment by maskit** [comment]
Is it too tricky to exclude "hq" from the protocol list for ALPN?

**Comment by duke8253** [comment]
Hmm, I guess can move the config check to `negotiated_application_name()` .

**Comment by maskit** [comment]
The list is set by `quiche_config_set_application_protos`. I'd rather remove "hq" from the list so it won't be negotiated in the first place.

**Comment by duke8253** [comment]
Ahh gotcha.

**Review by maskit — APPROVED** [review]
Thanks.

**Pull request merged**
