### PR TITLE
TS-4466: Add links to other versions of the documentation (back-port)

### PR DESCRIPTION
**Pull request by masaori335**
Backport https://github.com/apache/trafficserver/pull/654

### CODE REVIEW

**Comment by masaori335** [comment]
@PSUdaemon Should I rebase and squash those commits to one commit?

**Comment by PSUdaemon** [comment]
Up to you, but make sure you don't lose any info from all the commit messages. I'm fine leaving it as three though. Simpler that way too.

**Comment by masaori335** [comment]
OK, let's leave it.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1059/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1166/ for details.

**Pull request merged**
