### PR TITLE
TS-4709: Separate LogFilter expression parsing.

### PR DESCRIPTION
**Pull request by jpeach**
Separate LogFilter expression parsing from the configuration file
parser so that it can be tested and reused in other contexts.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/496/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/393/ for details.

**Comment by maskit** [comment]
👍

**Comment by zwoop** [comment]
Seems clean, ship it.

**Pull request merged**
