### PR TITLE
Autest for ATS test support all configuration layout

### PR DESCRIPTION
**Pull request by chitianhao**
Fixed the extension file for autest of ATS. Changed variables and directories in trafficserver.test.ext and copy_config.test.ext. Support all kinds of config.layout during build to guarantee the test run in the sandbox without side effects.

### CODE REVIEW

**Comment by dragon512** [comment]
Try to cleanup the code a little and add comments on what is being setup
Also please try to apply formatting with yapf with the setting here:

https://github.com/apache/trafficserver/pull/2097

I am still testing this formatting out, but seems like a good start

**Comment by dragon512** [comment]
I need to review this more detail myself.

However this is only a partial fix. There other part of this fix is a tweak to traffic_ctrl. That fix is more complex as the build depends are a utter mess. It will be trick to fix that without the simple copy paste of some code to get around a depends in libs/records and mgnt.api

**Comment by dragon512** [comment]
This depends on https://github.com/apache/trafficserver/pull/2110#pullrequestreview-43556516 getting merged

**Comment by chitianhao** [comment]
The test code beautiful and clean. Description is in the comments.

**Comment by dragon512** [comment]
@jpeach Can you unblock this?

The fixes should fix the layout for all variables.. given the fixes you made in traffic_ctrl. this code should be simpler than before.

**Comment by jpeach** [comment]
@dragon512 I still think the actually commits should be cleaned up. This seems like 1 commit to me, and the commit message should have a short, descriptive subject and a longer body that describes the changes and provides context for subsequent archaeologists.

**Comment by dragon512** [comment]
@jpeach  I see what you are talking about. I will talk to him tomorrow and have him squash this and clean up the message

**Comment by zwoop** [comment]
Yeh, +1 on squashing.

**Comment by dragon512** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Pull request closed without merging**
