### PR TITLE
Create clean exit path for traffic_manager on SIGTERM

### PR DESCRIPTION
**Pull request by jeredfloyd**
Since the removal of traffic_cop, it appears that there is no way to cause traffic_manager to exit cleanly.  SIGTERM causes the cleanup of child processes and a graceful shutdown, however still exits with code 15.  We can ignore this in the systemd unit file, but it's cleaner to have some path to a clean exit of traffic_manager.

### CODE REVIEW

**Comment by jeredfloyd** [comment]
It might also be desirable to add a "--manager" option to `traffic_ctl server stop`, to be parallel with `restart`?  I'm not entirely clear on the intended operation, however both the init.d file and the systemd unit use signals today, so a clean way to exit traffic_manager via signal is always valuable.

**Comment by randall** [comment]
[approve ci fedora]

**Review by bryancall — APPROVED** [review]

**Comment by bryancall** [comment]
@jeredfloyd We do plan to get rid of traffic_manager in the next major release (10.0.0).

**Comment by bneradt** [comment]
[approve ci fedora]

**Comment by jeredfloyd** [comment]
@bryancall Thanks! Once I have 9.x in Fedora I will try to follow future plans a little more closely.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
