### PR TITLE
Test: add nameserver to regex_remap test.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This test uses "localhost" and therefore should have a local nameserver.

### CODE REVIEW

**Review by ywkaras — CHANGES_REQUESTED** [review]
Test run #2 is deleted but I can't see any testing added that covers the same functionality.

**Comment by SolidWallOfCode** [comment]
Looks like a bad cherry pick.

**Comment by SolidWallOfCode** [comment]
Fixed.

**Review by ywkaras — DISMISSED** [review]

**Review by randall — APPROVED** [review]

**Comment by randall** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
Gah. How can this fail -
```
Running Test traffic_dump_sni_filter:.. Failed
```

**Pull request merged**
