### PR TITLE
Fix code to eliminate warning and enable feature

### PR DESCRIPTION
**Pull request by AD5GB**
##########Signed-off-by: Randy DuCharme <radio.ad5gb@gmail.com>

Edit: I inadvertently force pushed my own "max_req_pr" branch after rebasing.  I realized it, reset it to the appropriate commit and force pushed again.  I hope this doesn't mess up anything automated.  The head of this branch is the commit that fixes the issue.

### CODE REVIEW

**Comment by jvgutierrez** [comment]
As mentioned on #7030, `proxy.config.net.max_connections_in` is the config setting you're looking for, assuming that you're running ATS 8 or 7.

**Comment by AD5GB** [comment]
> 
> 
> As mentioned on #7030, `proxy.config.net.max_connections_in` is the config setting you're looking for, assuming that you're running ATS 8 or 7.

It is not.  It is 10.  I've updated the issue to reflect same.

**Comment by randall** [comment]
[approve ci]

**Comment by sudheerv** [comment]
This fixes #7030

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by AD5GB** [comment]
> 
> 
> Welcome and Congrats (yay!) on your first PR :)
> 
> Thanks for fixing the bug.

Thank you!  It was fun actually.  Yeah, first time with the Github workflow in a long long time.  I thought I'd linked the issue to this PR but it appears that I didn't.  I'll see if I can close that issue.

**Pull request merged**
