### PR TITLE
Add test and doc for proxy config cache select alternate

### PR DESCRIPTION
**Pull request by hnakamur**
I created this pull request after the discussion in the users mailing list.
- [Why is proxy.config.cache.select_alternate undocumented?](https://mail-archives.apache.org/mod_mbox/trafficserver-users/201608.mbox/%3cCAN-DUMSfygPs1eMAnGjvf-WsHhN2zPkt2k6_eUusQ8hWfsBmgw@mail.gmail.com%3e)
- [Re: Why is proxy.config.cache.select_alternate undocumented?](https://mail-archives.apache.org/mod_mbox/trafficserver-users/201608.mbox/%3cDE7328A3-E91A-48FA-842E-8B7F9EC0AF79@gmail.com%3e)

Could you review this?
Thanks!

### CODE REVIEW

**Comment by mingzym** [comment]
great job!

from your test case, the alternates vary from User-Agent, there is a dedicated config proxy.config.cache.vary_on_user_agent that will control whether we should vary on different User-Agent headers, and I think the cache.select_alternate may result in completely disable the alternate, so as all the 'vary' and 'alts' config options. while vary_on_user_agent may help you vary on AE header and the 'Vary' headers, but not UA. outline here just incase you need it.

well done.

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/623/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/519/ for details.

**Comment by hnakamur** [comment]
@mingzym Thanks for your comment.
I searched vary_on_user_agent  in the trafficserver source code, but I couldn't find it.
It turned out that proxy.config.cache.vary_on_user_agent was deleted at version 5.3.0: [\[TS-3232\] Remove obsolete proxy.config.vary_on_user_agent configuration - ASF JIRA](https://issues.apache.org/jira/browse/TS-3232)

**Comment by mingzym** [comment]
yeah, sorry for that, forget vary_on_user_agent. :(

**Comment by zwoop** [comment]
@jsime  Thoughts?

**Comment by zwoop** [comment]
@jacksontj Can you review the tsqa test portion please?

**Comment by bryancall** [comment]
Please reimplement using autest.  We have changed our testing framework and it now is under tests/

**Pull request closed without merging**
