### PR TITLE
Reworks yaml-cpp build flags

### PR DESCRIPTION
**Pull request by randall**
This includes renaming and localizing usage of them

### CODE REVIEW

**Comment by bryancall** [comment]
[ci approve autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by randall** [comment]
Something with my patch is breaking autest (loading xdebug.so):

`[Jun 21 16:35:17.059] {0x2b9763a70b60} FATAL: unable to load '/home/rmeyer/trafficserver/tests/_sandbox/cache-generation-clear/ts/plugin/xdebug.so': /home/rmeyer/trafficserver/tests/_sandbox/cache-generation-clear/ts/plugin/xdebug.so: undefined symbol: TSHttpTxnReenable
`

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
