### PR TITLE
Fix for imagemagick 7

### PR DESCRIPTION
**Pull request by cmcfarlen**
This fixes an issue with imagemagick 7 and osx.

### CODE REVIEW

**Review by JosiahWI — APPROVED** [review]
Cleaner fix than I expected, very nice.

**Comment by JosiahWI** [comment]
[approve ci freebsd]

**Comment by JosiahWI** [comment]
[approve ci freebsd]

**Review by ywkaras — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
