### PR TITLE
Add missing #include directive

### PR DESCRIPTION
**Pull request by AD5GB**
Signed-off-by: Randy DuCharme <radio.ad5gb@gmail.com>

Fixes the following compile failure:
```
 CXX      experimental/tls_bridge/regex.lo
  CC       experimental/url_sig/url_sig.lo
In file included from ../../trafficserver/plugins/experimental/traffic_dump/traffic_dump.cc:29:
../../trafficserver/plugins/experimental/traffic_dump/session_data.h:110:15: error: ‘optional’ in namespace ‘std’ does not name a template type
  110 |   static std::optional<IpAddr> client_ip_filter;
      |               ^~~~~~~~
../../trafficserver/plugins/experimental/traffic_dump/session_data.h:36:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   35 | #include "tscore/ts_file.h"
  +++ |+#include <optional>
   36 |
In file included from ../../trafficserver/plugins/experimental/traffic_dump/transaction_data.cc:29:
../../trafficserver/plugins/experimental/traffic_dump/session_data.h:110:15: error: ‘optional’ in namespace ‘std’ does not name a template type
  110 |   static std::optional<IpAddr> client_ip_filter;
      |               ^~~~~~~~
../../trafficserver/plugins/experimental/traffic_dump/session_data.h:36:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   35 | #include "tscore/ts_file.h"
  +++ |+#include <optional>
   36 |
```

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci]

**Review by randall — APPROVED** [review]

**Comment by bneradt** [comment]
Thanks for adding this.

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
