### PR TITLE
Noncopyable update for C++11

### PR DESCRIPTION
**Pull request by lbordowitz**

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci]

**Comment by zwoop** [comment]
There are merge conflicts here. Please resolve, push and we'll review.

**Comment by bryancall** [comment]
[approve ci]

**Comment by lbordowitz** [comment]
@zwoop @SolidWallOfCode Okay, I think it's ready for review again

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by shinrich** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
I don't understand why this hasn't been a problem before, but testing locally with `clang` the solution seems to be to remove `m_pDir` - it really isn't used and won't be missed.

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
You need to remove `m_pDir` in the constructor member initializer list in `LogConfig.cc` in addition to removing the member declaration.

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Pull request merged**
