### PR TITLE
Add check for config existence before cont creation

### LINKED ISSUE #10658: stats_over_http always registers a config reload continuation, even without a config file
There's no reason, as far as I can tell, for this code if the plugin has not been given a YAML configuration (to reload).

```
  /* Create continuation for management updates to re-read config file */
  config_cont = TSContCreate(config_handler, TSMutexCreate());
  TSContDataSet(config_cont, (void *)config_holder);
  TSMgmtUpdateRegister(config_cont, PLUGIN_NAME);
```

The easy fix here is to just not call this if there's no config file. However, with #10642, we may also want to clean up the configuration reload, such that we let the core deal with the file timestamps etc. If the file name is given to TSMgmtUpdateRegister(), that continuation will only be called if the file has actually changed.

### PR DESCRIPTION
**Pull request by ezelkow1**
Checks if a config path is set to monitor for a config file, if not set dont create the mgmt cont

closes #10658

### CODE REVIEW

**Comment by JosiahWI** [comment]
HostDBProcessor regression test and regexcookie AuTest failed.

**Comment by JosiahWI** [comment]
AuTests psubstitute and matchuri failed.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
[approve ci autest]

**Review by ywkaras — APPROVED** [review]

**Pull request merged**
