### PR TITLE
Restore private key passphrase behavior

### PR DESCRIPTION
**Pull request by moonchen**
We accidentally removed the callbacks for private key passphrases. This patch restores the old behavior.

### CODE REVIEW

**Comment by moonchen** [comment]
Fixes #11197

**Comment by brbzull0** [comment]
[approve ci rocky]

**Comment by moonchen** [comment]
> What testing was done of this? Would be nice to have Au test coverage.

Good call.  I added an autest and found out that the old code was broken.

**Review by ywkaras — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
