### PR TITLE
isuue #1399 add back partial code of tcp_congestion_control erased by…

### PR DESCRIPTION
**Pull request by shenzhang920**
Add the missing code of tcp_congestion_control erased by push of TS-3612

### CODE REVIEW

**Comment by maskit** [comment]
@shenzhang920 I understand why you put the blocks there because the logic was originally in `new_connection()`. However, I'm not a big fun of putting the same code into two (or more) places. Is it possible to put the block into only one place?

**Comment by shenzhang920** [comment]
@maskit Right, since there're 3 caller now, I moved some of the repeated code inside set_tcp_congestion_control()

**Comment by maskit** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1366/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1473/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/37/ for details.

**Comment by shenzhang920** [comment]
@maskit I made another commit to fix the clang failure, can you trigger the build again?  Thanks!

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1378/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1485/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/49/ for details.

**Comment by zwoop** [comment]
You can ignore the clang-analyzer build failures, since 6.2.x branch is busted.

**Comment by maskit** [comment]
@shenzhang920 This should be fixed on master too, right? If there's the same issue on master, we should fix it on master first, and then we can cherry-pick the commit for 6.2.x.
Could you make another pull-request for master? Sorry, I should have asked earlier.

**Comment by zwoop** [comment]
Oh yeah, if this is not a back port from master, then this should be changed / closed, and replaced with a PR against master. We always commit on master, and then suggest back ports to the RMs if needed.

**Comment by shenzhang920** [comment]
@maskit @zwoop   Got it!  I made the change on master and create another pull request.  How do I discard this pull request?

**Comment by maskit** [comment]
@shenzhang920 Thank you for the new pull-request. You can just close this pull request.
After merging the new pull request, you can open a new one for 6.2.x with cherry-picked commit, or I can do it for you.

**Comment by shenzhang920** [comment]
@maskit Thanks for the guidance, just create a new pull request in 6.2.x to cherry-pick the one merged in master

**Pull request closed without merging**
