### PR TITLE
Enable origin server session cache by default

### PR DESCRIPTION
**Pull request by duke8253**
As mentioned in #7479 , a separate PR for enabling origin server session cache by default for the 10.0.0 branch.

### CODE REVIEW

**Comment by duke8253** [comment]
[approve ci autest]

**Review by bryancall — DISMISSED** [review]

**Review by maskit — DISMISSED** [review]

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by maskit** [comment]
The errors are concerning, but it doesn't look like because of this change.
[approve ci autest]

```
Running Test tls_client_cert_override:.F Failed
Running Test tls_verify_override:...F Failed
Running Test tls_verify_override_base:......F Failed
Running Test tls_verify_override_sni:..F Failed
Running Test traffic_dump:..........F Failed
```

```
file /var/tmp/ausb-7537.14930/tls_verify_override_base/ts/log/diags.log : Failure on missing name for bar.com - Failed
        Reason: Contents of /var/tmp/ausb-7537.14930/tls_verify_override_base/ts/log/diags.log did not contains expression: "WARNING: SNI \(bar.com\) not in certificate. Action=Terminate server=bar.com\(127.0.0.1\)"
```

**Comment by maskit** [comment]
Same tests failed. Seems like something happened on TLS layer.

https://ci.trafficserver.apache.org/autest/ausb-7537.14932/tls_verify_override_sni/_output/tls_verify_override_sni-server_foo/stream.all.txt
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45144)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/microserver/servers.py", line 95, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 968, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2334)
----------------------------------------
size 2
Dropped 0 sessions for being malformed
Starting server on port ('127.0.0.1', 61270) over TLS
Serving GET /ruok... injecting content-length header.. Finished
Serving GET /ruok... injecting content-length header.. Finished

=== ^C received, shutting down microservers ===
```

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
So I figured out why these are failing, it's caused by the way I'm recording the sessions. Let's say there's a autest with multiple test runs. The first tr does a request to `https://127.0.0.1:9090/success` and is supposed to success, the second tr does a request to `https://127.0.0.1:9090/fail` and is supposed to fail. The problem now is since both of these requests are for the same remote address, it'll try to reuse the session on the one that is supposed to fail, causing it succeed.

**Comment by randall** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
Well looks like it's still not enough, the verify policy still messes things up a bit, looking into it.

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
Just spent a few hours trying to figure out what is going on here, since this only happens on ci. Turns out it's a bug in older OpenSSL versions:

https://www.openssl.org/docs/man1.1.1/man3/SSL_get_servername.html
> SSL_get_servername() historically provided some unexpected results in certain corner cases. This has been fixed from OpenSSL 1.1.1e.

Testing with version 1.1.1d shows that some times, the `SSL_get_servername` just returns NULL for no reason.

**Comment by bneradt** [comment]
[approve ci autest]

**Review by maskit — APPROVED** [review]

**Pull request merged**
