### PR TITLE
TS-4650: cachekey: not thread safe

### PR DESCRIPTION
**Pull request by gtenev**
(cherry picked from commit f4a97a9d573867441c5dd711b54ff66117fcd057)
(cherry picked from commit 15b2ab08a30a0df8c2223e05c7bfc4cb530ea243)

### CODE REVIEW

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1144/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1037/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1145/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1038/ for details.

**Pull request merged**
