### PR TITLE
TS API -- replace TSMLoc with more specific types for greater type safety

### PR DESCRIPTION
**Pull request by ywkaras**
Work in progress.

This is just a preliminary PR with the changes to ts.h only.  I replaces TSMLoc with more specific types.  This will make run time or memory corruption errors compile time errors instead.

Changes to documentation pending.

### CODE REVIEW

**Comment by ywkaras** [comment]
I think 9.0.0 probably makes more sense.  It may be a fair amount of work for plugin maintainers.

**Comment by SolidWallOfCode** [comment]
I like the approach. The only thing I'd want is updates to the Developer Guide.

**Comment by ywkaras** [comment]
Yes major doc changes pending.

**Comment by ywkaras** [comment]
I'm going to have to abandon this idea, at least for now.  It turns out the TS API is implementing its own little perverted runtime polymorphism.  There are cases where a TSMLoc actual parameter can be either a pointer to HTTPHdrImpl or to MIMEHdrImpl.

**Pull request closed without merging**
