### PR TITLE
Remove unused macros defined on ink_apidefs.h

### PR DESCRIPTION
**Pull request by nekomachi-touge**
The following macros on `include/tscore/ink_apidefs.h` expand to empty string.

```cpp
#define inkliapi
#define inkcoreapi
#define ink_undoc_liapi
#define ink_undoc_coreapi inkcoreapi
```

This PR removes them and their references.

No mention about the macros is found on GitHub/JIRA/ML/docs.

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Review by shinrich — DISMISSED** [review]
Good clutter removal

**Comment by shinrich** [comment]
[approve ci]

**Review by shinrich — APPROVED** [review]

**Comment by nekomachi-touge** [comment]
Thanks!

**Pull request merged**
