### PR TITLE
Fixes memory leaks in header_rewrite

### PR DESCRIPTION
**Pull request by randall**
(cherry picked from commit 8949c05368b3d1160da727d387a264c6ac3bf491)

Conflicts:
	plugins/header_rewrite/value.cc
	plugins/header_rewrite/value.h

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
Reverted for now, we should revisit this for 8.0.2

**Comment by zwoop** [comment]
Unreverted this, false alarm.

**Comment by bryancall** [comment]
I reverted this and applied the original PR/commit to the 8.1.x branch.  I was able to do that after pulling in the string concatenation

**Pull request merged**
