### PR TITLE
Update -with-profile and add some profiling documentation

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Review by shukitchan — DISMISSED** [review]
This looks good.

**Comment by maskit** [comment]
Why was heap profiler removed? If we are going to remove it, can we remove the include line as well?
```
$ git grep gperftools
src/traffic_server/traffic_server.cc:#include <gperftools/profiler.h>
src/traffic_server/traffic_server.cc:#include <gperftools/heap-profiler.h>
```

**Comment by bryancall** [comment]
I would like to know why the heap profiler was remove also.

**Comment by shinrich** [comment]
The symbols did not exist with the new header files.   Probably different symbols.  Since I was concentrating on CPU performance, I didn't track it down..

**Comment by maskit** [comment]
It seems like the three functions exist one the latest header file. Am I looking at an old version or a different file?
https://github.com/gperftools/gperftools/blob/master/src/gperftools/heap-profiler.h

**Comment by shinrich** [comment]
Pushed another commit that added back the heap profiling calls.  Built for me now.  Don't now what was my problem before.

**Review by maskit — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
