### PR TITLE
Add cross references between server session sharing match and upstream connection tracking match.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
* Fix various documentation build errors.
* Add the cross referencing.

### CODE REVIEW

**Comment by bneradt** [comment]
Thanks for keeping the docs building.

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by randall** [comment]
@SolidWallOfCode Can you rebase this PR?

**Comment by SolidWallOfCode** [comment]
[ci approve clang-analyzer]

**Comment by SolidWallOfCode** [comment]
[approve ci clang-analyzer]

**Comment by SolidWallOfCode** [comment]
[approve ci docs]

**Pull request merged**
