### PR TITLE
Trivial Autoconf cleanup

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1421/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1314/ for details.

**Comment by zwoop** [comment]
Nice catch on AC_SEARCH_LIBS! Question, i wonder if we do this wrong in other places? Are we adding things to LIBS when we shouldn't?

There are several places where we do things like:

```
  AC_SEARCH_LIBS([lzma_code], [lzma], [lzma_have_libs=1])
  if test "$lzma_have_libs" != "0"; then
    AC_CHECK_HEADERS(lzma.h, [lzma_have_headers=1])
  fi
  if test "$lzma_have_headers" != "0"; then
    AC_SUBST(LIBLZMA, [-llzma])
  else
    enable_lzma=no
    CPPFLAGS=$saved_cppflags
    LDFLAGS=$saved_ldflags
  fi
```

**Comment by zwoop** [comment]
In fact, taking a quick look, tools like traffic_top is getting all the "optional" libraries, even though they are highly unlikely to use 'em? Like, libhwloc.

**Comment by jablko** [comment]
Thanks for reviewing this @zwoop! I'm going to land it and see about fixing the issue you spotted in a separate PR.

**Pull request merged**
