### PR TITLE
s3_auth: Fix hash calculation

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Comment by bryancall** [comment]
/
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci autest]

**Review by bryancall — APPROVED** [review]

**Pull request merged**
