### PR TITLE
7.1.x TS-5107: Changes to autolinking in Docutils 0.13

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1396/ for details.

**Comment by zwoop** [comment]
Why are there 4 commits on this? Can you squash those?

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1290/ for details.

**Comment by zwoop** [comment]
Also, please remember to add Milestone, Label's etc. on each Issue / PR, otherwise @bryancall  gets all pissy. :)

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1398/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1292/ for details.

**Comment by jablko** [comment]
> Also, please remember to add Milestone, Label's etc. on each Issue / PR, otherwise @bryancall gets all pissy. :)

Will do! :-)

> Why are there 4 commits on this? Can you squash those? Or do we actually need these reverts as well?

Make that 5 ... I just added #1377 to this PR because this is broken without it. Whoops.

I think we need the reverts, this doesn't apply without them, and I think it makes most sense to maintain the parallel between the commits we're backporting and master -- so apply them as individual commits. That said, I'm happy to do it differently! I'm happy to squash any combination of them.

**Comment by zwoop** [comment]
I saw what happened, the reverts makes sense now.

**Pull request merged**
