### PR TITLE
Convert a test for UDPNet to AUTest from TestBox

### PR DESCRIPTION
**Pull request by masaori335**
This is another approach of tests of #2150 using AUTest.

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
Where is the code for `proxy/traffic_udp_echo_server`? Is it already in the build?

**Comment by masaori335** [comment]
a) Code for `traffic_udp_echo_server`
The source code is `iocore/net/test_I_UDPNet.cc`. I should rename and move to somewhere.

b) Install `traffic_udp_echo_server`
To be honest, I don't want to install this program. Can TSQA test binaries not installed in bin directory?

> if it would be better to have it in tests/tools and have some code in our setup build the binary as part of a setup of a test of as part of the setup of all the tests

What do you mean by `setup build`? Is that same way to build `ssl-post.c` in TLS tests?

**Comment by dragon512** [comment]
What

What do you mean by setup build? Is that same way to build ssl-post.c in TLS tests?
--

Yes and no. In the case of ssl-post.c it make plugin that is then used in an instance of a ATS server. What I am suggesting here is that:
1) we copy and build the test_I_UDPNet.cc as some TestRun() code. We can make an extension to redo these steps easily for each test.
2) OR as Part of the start code we see if we already built this binary and if not, we rebuild it to be used in the tests

1) is easiest to do. 2) might need some tweaks in the core to allow us to share and reuse a process object. I think at first we should move the code and give it a better name under test/tools. 





 we might want to have some that would build test_I_UDPNet.cc

**Comment by bryancall** [comment]
[approve ci autest]

**Pull request closed without merging**
