### PR TITLE
TS-4804: Add r into total_written only if r > 0

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by zwoop** [comment]
Interesting. How does this manifest itself? Is it possible that r is < 0, and we go negative?

**Comment by zwoop** [comment]
Also, is a value of r < 0 an expected behavior, or is that some sort of error case that is not handled properly ?

**Comment by oknet** [comment]
@zwoop negative means error. man 2 writev:

RETURN VALUES
     Upon successful completion the number of bytes which were written is returned.  Otherwise, a -1 is returned and the global variable errno is set to indicate the error.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/665/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/560/ for details.

**Pull request merged**
