### PR TITLE
Check for SO_MARK in CMake build

### PR DESCRIPTION
**Pull request by JosiahWI**
This sets the CMake variable TS_HAS_SO_MARK appropriately.

### CODE REVIEW

**Comment by JosiahWI** [comment]
[approve ci cmake fedora]

**Comment by JosiahWI** [comment]
[approve ci cmake]

**Review by cmcfarlen — COMMENTED** [review]
This seem unnecessary.  Maybe we should just use `#if SO_MARK` instead of making a new definition for this?  afaict this is used in one place in the code.

**Comment by JosiahWI** [comment]
I think it's a good idea to look into which options we don't need anymore, but the autotools build supports this option and it's documented as being available. Maybe we should do that separately?

**Comment by JosiahWI** [comment]
Rebased on master.

**Review by cmcfarlen — APPROVED** [review]

**Pull request merged**
