### PR TITLE
TS-4195: double free on exit

### PR DESCRIPTION
**Pull request by zizhong**
(cherry picked from commit 1a7c0fc8cdf5ed48870e1507bf337fb2e711226f)

### CODE REVIEW

**Comment by zwoop** [comment]
@PSUdaemon Ping?

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/177/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/172/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/192/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/302/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1873/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1762/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/435/

**Comment by PSUdaemon** [comment]
So everything checks out OK on this PR, but I feel like we merged something similar recently and then reverted it. How is this one different? Also, I think it was @bryancall or @SolidWallOfCode who was saying that `volatile` is used wrong very often in the code. Is this the proper use case?

**Comment by zizhong** [comment]
Yes, the commit we reverted includes calling `_exit` in the signal handler which can disable generating ASAN reports.

**Comment by zizhong** [comment]
And about the `volatile`, 

>If your handler needs to access any global variables from your program, declare those variables volatile. This tells the compiler that the value of the variable might change asynchronously, and inhibits certain optimizations that would be invalidated by such modifications.

from https://www.gnu.org/software/libc/manual/html_node/Nonreentrancy.html

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/462/

**Comment by zizhong** [comment]
@PSUdaemon Could you take a look at this one, again?

**Comment by bryancall** [comment]
[approve ci]

**Pull request merged**
