### PR TITLE
slice plugin, intercept handler that uses cache_range_request

### PR DESCRIPTION
**Pull request by traeak**
Redid the squash.  Deleting and repushing the branch closed the previous PR.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci]

**Comment by shinrich** [comment]
[approve ci]

**Comment by traeak** [comment]
We've had this on one production machine for almost a month and a half, currently its at ~450cpu hours.

**Comment by bryancall** [comment]
[approve ci]

**Pull request merged**
