### PR TITLE
fixing spelled enumeration

### PR DESCRIPTION
**Pull request by dmorilha**

### CODE REVIEW

**Comment by shukitchan** [comment]
[approve ci]

**Comment by maskit** [comment]
@zwoop I think this is subject to API change since the enum is public, right? (so I didn't add it to 7.x project)

**Comment by scw00** [comment]
@dmorilha  Please squash your pr.

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
[whitelist dmorilha]

**Pull request merged**
