### PR TITLE
Remove HAVE_MALLOC_H and HAVE_MCHECK_H build vars

### PR DESCRIPTION
**Pull request by phongn**
Replace automake-style `HAVE_INCLUDE_H` compile flags with `#if __has_include` preprocessor directives.

This PR does so for `malloc.h` and `mcheck.h`. In addition, the search path for `malloc.h` is extended to add `<malloc/malloc.h>` (for macOS) and the symbol flag `HAVE_MALLOC_USABLE_SIZE` now looks for `malloc_np.h` (commonly used on FreeBSD). 

Addendum: More recent version of macOS include a `malloc_size` call similar to `malloc_usable_size` on other architectures. I believe that jemalloc also exports this as well, so long as `JEMALLOC_MANGLE` is set.

### CODE REVIEW

**Comment by phongn** [comment]
[approve ci ubuntu]

**Review by cmcfarlen — DISMISSED** [review]

**Comment by ywkaras** [comment]
[approve ci]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci]

**Comment by ywkaras** [comment]
@cmcfarlen this had to be rebased, your approval got tossed.

**Pull request closed without merging**
