### PR TITLE
QUIC: Mem leaking with QUICPacketHeader

### PR DESCRIPTION
**Pull request by scw00**

### CODE REVIEW

**Comment by maskit** [comment]
Hmm, I'd rather use unique_ptr with a custom deleter. Having own `free()`, `destroy()`, `release()` is always confusing.

**Comment by maskit** [comment]
Because `QUICPacketLongHeader::free()` is only available if the instance was allocated with the class allocator.

**Comment by scw00** [comment]
got it

**Comment by scw00** [comment]
updated .

**Pull request merged**
