### PR TITLE
TS-4432: TSVConnFdCreate, double free on connectUp failure

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by bryancall** [comment]
How are you seeing the double free?  The original code looks good.

**Comment by oknet** [comment]
int
UnixNetVConnection::connectUp(EThread *t, int fd)
{
  int res;

  thread = t;
  if (check_net_throttle(CONNECT, submit_time)) {
    check_throttle_warning();
    action_.continuation->handleEvent(NET_EVENT_OPEN_FAILED, (void *)-ENET_THROTTLING);
    free(t);   ------> free(t) has been called before the connectUp() return CONNECT_FAILURE to TSVConnFdCreate
    return CONNECT_FAILURE;
  }

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Build triggered. sha1 is merged.

**Comment by atsci** [comment]
Build finished successfully.
 No test results found.

**Comment by jpeach** [comment]
Thanks @oknet

**Pull request merged**
