### PR TITLE
Ignore if_modified_since when if_none_match is present

### PR DESCRIPTION
**Pull request by constreference**
Addresses https://github.com/apache/trafficserver/issues/5702
https://datatracker.ietf.org/doc/html/rfc7232#section-3.3

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
Look like this was fixed in #5701 and merged - It looks like this PR is just cleaning up initialization?

**Comment by constreference** [comment]
@bryancall, That PR addresses If-Match and If-Unmodified-Since priority, while this looks at If-None-Match and If-Modified, Currently if an etag is not present, we move to check the If-Modified-Since presence

**Comment by bryancall** [comment]
[approve ci]

**Pull request closed without merging**
