### PR TITLE
TS-4336: Rename MIMEParseResult values for better readability.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/499/ for details.

**Comment by bryancall** [comment]
Looking at the change I think it would be better to have a generically named parse result codes since we are using them for everything including URL parsing too.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/603/ for details.

**Comment by jpeach** [comment]
@bryancall Renamed to ``ParseResult``.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/506/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/610/ for details.

**Comment by bryancall** [comment]
👍 - Looks good

**Pull request merged**
