### PR TITLE
Cleanup: Get rid of HTTP2_SESSION_EVENT_RECV

### PR DESCRIPTION
**Pull request by masaori335**
Part of #7852. The definition will be removed by #7845 with other deprecated events.

### CODE REVIEW

**Comment by maskit** [comment]
I appreciate making small changes, but is it safe to land these separately? The logic is not completely equivalent - zombie event stuff won't be processed and `recursion` is not counted.

**Comment by masaori335** [comment]
I agree this is not completely equivalent. As you pointed out `recursion` of `Http2ConnectionState` is not incremented. But this change is safe because the `rcv_frame()` call is guarded by `recursion` of Http2ClientSession.

Could you give me a pointer where the zombi event is checking the `recursion`?

**Comment by maskit** [comment]
I don't thinks the two are related. I just pointed out two separated things that are currently done in `main_event_handler`.

`ready_to_free()` is checked at the bottom of `main_event_handler` when `recursion` is 0, and `ua_session->free()` is called. Is a similar thing done in somewhere else, or we don't need to do it when we call `rcv_frame`?

**Comment by masaori335** [comment]
https://github.com/apache/trafficserver/blob/050b2dfe9a89348b4105183a2b31e7cc59fc389d/proxy/http2/Http2ConnectionState.cc#L1253-L1254

It looks like when the `main_event_handler` handles `HTTP2_SESSION_EVENT_RECV`, `ua_session->is_recursing()` is always true. Because it only comes from Http2ClientSession SessionHandler.

**Comment by masaori335** [comment]
I'm fine with keeping this (and #7878) as a draft and merge with #7845 if reviewers want. This is separated out from it to minimize the change.

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by maskit** [comment]
> I'm fine with keeping this (and #7878) as a draft and merge with #7845 if reviewers want.

I'm not requesting that, it's an option if other reviews want it though. I was just not sure the points above.

**Review by shinrich — APPROVED** [review]

**Comment by shinrich** [comment]
Looks good.  Code more clear.

**Pull request merged**
