### PR TITLE
TS-4187: Fix connections_currently_open stat.

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
I presume this is a fix related to the VC migration patch.

**Comment by zwoop** [comment]
If this breaks throttling , should we back port to v6.1.2?

**Comment by shinrich** [comment]
Yes, the fix is related to the VC migration.   Probably would be reasonable to backport.

**Comment by zwoop** [comment]
+1

**Pull request closed without merging**
