### PR TITLE
Backport TS-4537, TS-4605, TS-4953, and TS-4915

### PR DESCRIPTION
**Pull request by masaori335**
Backport several tickets around PriorityQueue and Http2DependencyTree.
Main purpose is TS-4554. It requires TS-4537, TS-4605, TS-4953, and TS-4915.

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1057/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1164/ for details.

**Comment by masaori335** [comment]
`PriorityQueue<T, Comp>::erase` is added by TS-4537, so we need backport this too.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1171/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1064/ for details.

**Pull request merged**
