### PR TITLE
Removed hardcoded logging.yaml filename in logs

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by randall** [comment]
Conceptually, this seems fine. Though the builds look to be super busted.

**Comment by zizhong** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
@randall Yes, I messed up the code and I wasn't calling the get() method.  It is fixed now.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
