### PR TITLE
Reset inactivity timeout in SSL read loop.

### PR DESCRIPTION
**Pull request by shinrich**
Reset inactivity timeout after every successful SSL_read.  Hopefully avoids timeouts during POST.

### CODE REVIEW

**Comment by realpdm** [comment]
I applied this patch and still see timeouts happening that match the timeout timer, even though data is flowing up with POST

**Comment by shinrich** [comment]
I am able to reproduce the effect that @realpdm is seeing by setting up a remap rule to httpbin

```
map https://mytestmachine.com/post http://httpbin.org/post
```

I set the timeouts to 3 and 4 seconds.
```
CONFIG proxy.config.http.transaction_no_activity_timeout_in INT 3
CONFIG proxy.config.http.transaction_no_activity_timeout_out INT 4
```
Then I issue a curl request with a 10MB post body.  

```
curl -H 'Expect:' -v  -k --data-binary @trafficserver-TS-4180.zip https://mytestmachine.com/post -o /tmp/out
```

Curl returns "curl: (52) Empty reply from server" and I see ERR_CLIENT_ABORT in our access log.

I added warning messages when we update the next_inactivity_timeout_at in the ssl_read_from_net and when we trigger the inactivity event.  The logs show lots and lots of timeout updates (1 every ms or so).  Then 3 seconds and the timeout event is sent.

Then I did a tcpdump on the client side and server side.  It shows that both sides are busy for quite a while uploading the post body.  Then evidently the origin thinks about things for 3-4 seconds.  Then ATS shuts down the connection to the client. 

Is it possible that your origin is just a bit overwhelmed with the large upload and is taking a couple seconds to process before responding?

**Comment by realpdm** [comment]
I don't think it is related to the origin because I can make it fail at particular times by adjusting the timeout. Ie, with the same file. It seems to be a total time on the transaction. If a file is small enough to upload within the timer, it works fine. If it is large enough it will fail at the value the timer is set to as the total transaction time (ttms).  

Example, I upload a 256MB file and set timer to 30s it will fail at 
"ttms":34745 with ERR_CLIENT_ABORT

Change timer to 5 seconds..
"ttms":9554 with ERR_CLIENT_ABORT

"ttms":6411 with same error

**Comment by maskit** [comment]
I thought moving `netActivity()` into the loop is sufficient but it wasn't

Even if we update `next_inactivity_timeout_at ` in the loop, we are still in the loop. This means that read data from the client isn't send to the origin server at all. Also, the inactivity timeout will be canceled when ATS has received a response header from the origin server.
https://github.com/apache/trafficserver/blob/7.0.x/proxy/http/HttpSM.cc#L1856

Therefore, the inactive timeout is still active while ATS is sending data to the origin server (red allow in the figure), and it won't be done within `transaction_inactive_timeout_in`.

image-44

So, I think we have to get out of the loop at times, and should send the received data to the origin server, and probably the timeout should be canceled when ATS received the last part of POST data.

**Comment by maskit** [comment]
@realpdm Can you try #2247?

**Comment by shinrich** [comment]
@maskit I see your point.  If the client is super aggressive and never leaves the loop, we will suck the entire 10MB post body into a buffer (which is bad on several levels).  That isn't what I was seeing from my packet traces for a curl off-box.

**Comment by shinrich** [comment]
Bleah.  Tried to update with my latest experiment.  Forgot that I was working against 7.1.x.  Close and will reopen.

**Pull request closed without merging**
