### PR TITLE
ProxyTxn Refactor move code to cc

### PR DESCRIPTION
**Pull request by a-canary**
Organizing header files into something readable. 
Code moved from .h to .cc. No functional changes.

### CODE REVIEW

**Comment by maskit** [comment]
Looks good to me. We may want to have this on 9.0 too to make future backports easy.

**Comment by maskit** [comment]
We might need to backport #5908 too, if we backport this, because this could degrade performance.

**Comment by zwoop** [comment]
@a-canary This has merge conflicts (also see the comment re: #5908) above. It feels like there's maybe other things missing from the list of back ports.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
