### PR TITLE
Add static type checking to configuration override API implementation.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**

### CODE REVIEW

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/29/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1490/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1596/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/161/ for details.

**Comment by jpeach** [comment]
I don't get how this is better than the previous version. That was purely compile time and this compares the global `typeid` constants at runtime. It doesn't seem better.

**Comment by SolidWallOfCode** [comment]
I think the implementation is significantly simpler, avoids more advanced template techniques, and eliminates a type. It is also more easily expandable in that the converters can check for any type easily, rather than depending on the set of values in the enum.

**Comment by zwoop** [comment]
I like the elimination of that additional enum type, but I don't know enough about the details in C++11 here to know what the impact are on performance.

**Comment by SolidWallOfCode** [comment]
Using `typeid` on built in types and variables of built in types compiles to a single constant load instruction. Comparison is not as efficient, however. That does a pointer check first and if not successful does a name string compare which in our particular case only checks the first character.

**Comment by zwoop** [comment]
@SolidWallOfCode If you fix the merge conflicts now, I'll +1 this against my better judgement :-).

**Comment by SolidWallOfCode** [comment]
I guess. I don't really think this is all that much better than the template logic, except that it's easier to understand for non template people.

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/48/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/freebsd-github/1615/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1510/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/180/ for details.

**Comment by SolidWallOfCode** [comment]
Gah, what a tarpit. The conflict resolution collided with another override update and that caused the regression test failure. Should be fixed now.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1620/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1515/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/53/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/185/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/RAT-github/7/ for details.

**Pull request merged**
