### PR TITLE
http3: Propagate events from QUICNetVC

### PR DESCRIPTION
**Pull request by maskit**
This is for #9392 and #9783. The crash (assertion failure) happens because transactions are not deleted due to lack of event propagation. This PR add a mechanism to propagate events such as INACTIVE_TIMEOUT from QUICNetVC to Http3Transaction through Http3Session.

The event handlers may need to handle other events and may also need to do different things for each event, but this change should prevent the crash at least.

### CODE REVIEW

**Review by brbzull0 — COMMENTED** [review]
Even though this is defintelly needed, have you try to run the `via` test with quiche enabled?

I am running this patch and getting the same assert as in one of the [issues](https://github.com/apache/trafficserver/issues/9783#issuecomment-1841599316).

```
Fatal: ../src/proxy/http3/Http3Session.cc:43: failed assertion `this->_transaction_list.head == nullptr`
traffic_server: received signal 6 (Aborted)
```

**Comment by maskit** [comment]
I guess I thought it's done when I fixed one case, but it was obviously incomplete. The events were propagated to Http3Transaction but not HttpSM. The last commit added code for it.

Also, while testing the via test, I found another issue and fixed it on another PR (#11080). With the both changes, the via test passes on my box.

**Review by brbzull0 — APPROVED** [review]
Looks good!
Thanks!!

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
