### PR TITLE
Fixed clang-analyzer issue with null pointer in BufferWriter

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
That change won't work because a `BufferWriter` with a `nullptr` for `_buf` is used in multiple places. It enables the two-pass sizing algorithm more efficiently. That's why the original assert was at it was - if `_buf` is `nullptr` then `_capacity` must be 0.

**Comment by SolidWallOfCode** [comment]
I would try
```
if (length > 0) {
  ink_assert(_capacity > 0 || _buf != nullptr);
  size_t newSize = _attempted + length;
  ...
```
That is, wrap the function contents in a check of `length > 0`. This prevents a call to `memcpy` if `length == 0` which should work correctly but maybe the analyzer doesn't like that.

**Comment by bryancall** [comment]
It still aborts with length > 0:
```
#14 0x0000000000635695 in ____C_A_T_C_H____T_E_S_T____6 () at unit-tests/test_BufferWriterFormat.cc:268
...
(gdb) frame 4
#4  0x000000000062ac35 in ts::FixedBufferWriter::write (this=0x7fffffffc4c0, data=0x7fffffffc3ee, length=3) at ../../lib/ts/BufferWriter.h:260
260	      ink_assert(_buf != nullptr); // make clang-analyzer happy.
(gdb) p length
$1 = 3
(gdb) p _buf
$2 = 0x0
(gdb) p _capacity
$3 = 0
```

**Comment by SolidWallOfCode** [comment]
That crash is on `ink_assert(_buf != nullptr);` which doesn't appear at all in my suggested version.

This change creates a potential crash if a zero length object is written to a null buffer BufferWriter, a legitimate operation. The result is fixing the clang analyzer issue made the code _less_ stable. I can't say I'm terribly impressed with clang 6 analyzer so far.

**Comment by SolidWallOfCode** [comment]
This passes `make check` for me on master
```
  /// Write @a data to the buffer, up to @a length bytes.
  FixedBufferWriter &
  write(const void *data, size_t length) override
  {
    if (length > 0) {
      ink_assert(_capacity == 0 || _buf != nullptr); // make clang-analyzer happy.
      size_t newSize = _attempted + length;

      if (newSize <= _capacity) { 
        std::memcpy(_buf + _attempted, data, length);
      } else if (_attempted < _capacity) { 
        std::memcpy(_buf + _attempted, data, _capacity - _attempted);
      }
      _attempted = newSize;
    }
    return *this;
  }
```
I also tested this code to verify the expected behavior of `memcpy`:
```
  void* np{nullptr};
  std::memcpy(np, bw20.data(), 0); // should be OK, copying 0 bytes.
```
That compiles and runs successfully, even though apparently clang analyzer would choke. At this point I'm tempted to `#if defined()` out the entire function from clang analyzer's view because (IMHO) it's simply wrong.

**Pull request merged**
