### PR TITLE
Add missing experimental plugins to build

### PR DESCRIPTION
**Pull request by JosiahWI**
The stale_response plugin had no auto_option, and http_stats did but its add_subdirectory call was missing. These were missed in #10967.

### CODE REVIEW

**Comment by JosiahWI** [comment]
The AuTest bad_chunked_encoding failed.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Review by masaori335 — APPROVED** [review]
Nice catch!

**Comment by JosiahWI** [comment]
It was reported by @leontion.

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
