### PR TITLE
Add current active SNI Routing Tunnel stats

### PR DESCRIPTION
**Pull request by masaori335**
# Motivation

Part of #7241. All [SNI Routing](https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/layer-4-routing.en.html) tunnels are counted as "active" connections because we don't know the state of the protocol on the tunnel. However, these tunnels are actually "inactive" in some cases and we want to count only "active" tunnels.

# New stats
```
proxy.process.tunnel.current_active_connections
```

A gauge of current active SNI Routing Tunnels.

# New config
```
proxy.config.tunnel.activity_check_period
```

Frequency of checking the activity of SNI Routing Tunnel.

### CODE REVIEW

**Review by bneradt — CHANGES_REQUESTED** [review]
Looks good @masaori335 . I just have a few minor suggestions.

**Comment by masaori335** [comment]
@bneradt Thanks for the review. I followed your suggestions. Please take another look.

**Comment by masaori335** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]
Looks great. Thank you Masaori.

**Pull request merged**
