### PR TITLE
TS-4700: Change the default timeout for HTTP/2

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/582/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/478/ for details.

**Comment by zwoop** [comment]
I'm ok with this, but it's slightly misleading that we are changing both the HTTP/1 and the H2 timeouts. Perhaps considering mentioning this in the commit message body, or the Summary? It'll help writing the release notes for 7.0.0 I think.

But,  :+1:

**Comment by maskit** [comment]
I'm on the same page with @zwoop . But the change seems reasonable. 👍

**Comment by masaori335** [comment]
Looks good 👍

**Pull request merged**
