### PR TITLE
Unfolds request headers that are using obs continuations

### PR DESCRIPTION
**Pull request by zwoop**
This also removes a duplicated test file, that's not used / necessary. This reopens the old PR #1078.

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/158/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/173/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1854/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/155/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/284/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1744/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/417/

**Comment by zwoop** [comment]
@bryancall Do we want this back ported to 7.1.x ?

**Comment by bryancall** [comment]
@zwoop Yes, I think it should be backported.

**Pull request merged**
