### PR TITLE
Add Example URI Signer Python Script

### PR DESCRIPTION
**Pull request by dsouza93**
Provide an example script to be used in conjunction with the uri signing
plugin. This script is meant to serve as an example of how to get started
with uri signing and could be useful in testing various configs.

### CODE REVIEW

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve autest]

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Nice job setting Milestones / Labels etc. ...

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
