### PR TITLE
Mark TSHashTable non-copyable.

### PR DESCRIPTION
**Pull request by jpeach**
Ping @SolidWallOfCode @jacksontj

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/253/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/151/ for details.

**Comment by zwoop** [comment]
[approve ci] Starting another build, FreeBSD git repo was wedged.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/154/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/256/ for details.

**Pull request merged**
