### PR TITLE
TS-4728: Remove invalid LogHost assertion.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by jpeach** [comment]
Ping @zwoop @pbchou

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/516/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/413/ for details.

**Comment by zwoop** [comment]
:+1:

**Comment by zwoop** [comment]
This is likely a back port candidate for 6.2.1 as well.

**Comment by oknet** [comment]
Should we define LogFile::free() first ?
The Ptr::clear() need free() to dealloc the LogFile.

**Comment by jpeach** [comment]
> On Sep 2, 2016, at 6:45 AM, Oknet <notifications@github.com> wrote:
> 
> Should we define LogFile::free() first ?
> The Ptr::clear() need free() to dealloc the LogFile.

LogFile inherits RefCountObj, which implements free() as "delete this", so it just needs a valid destructor.

**Pull request merged**
