### PR TITLE
Fix #2533: ATS doesn't have an active timeout for http2 connection

### LINKED ISSUE #2533: ATS doesn't have an active timeout for http2 connection
We have a `proxy.config.http2.active_timeout_in` which works per stream, but we don't have an `active timeout` works per session.

### PR DESCRIPTION
**Pull request by zizhong**
Trying to fix #2533: ATS doesn't have an active timeout for http2 connection
IMHO, `Http2::active_timeout_in` needs to be timeout for a connection. For each transaction, we've already got `proxy.config.http.transaction_active_timeout_in`.

Perhaps, we can increase the default value of `proxy.config.http2.active_timeout_in`.

@bryancall @maskit @masaori335 @scw00 
cc @sidhuagarwal

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci].

**Comment by bryancall** [comment]
It looks like you are removing the active timeout on the client connection.  Currently it should create a new active timeout 900 seconds in the future every time a stream is created.  Which I think is good.

**Comment by zwoop** [comment]
I don't think we should do this change; Either set it to 0, which disables this active timeout, or set it to a higher value. 900 is inline with other defaults, but I know of several use cases where setting it to 0 (disabled0 is the right thing to do.

**Comment by zizhong** [comment]
No, I'm not removing active timeout on client connection. It's set at `state_read_connection_preface`.
In the current implementation, however, ATS sets the timeout every `create_stream` and resets the timeout when no streams active. Then the connection can end up with opening forever when the client keeps creating new streams.
What's the definition of `Http2::active_timeout_in`? Should it be the timeout no matter whether the client is active or not?

**Comment by zizhong** [comment]
@maskit @masaori335 what're your guy's thoughts on this issue?

> What's the definition of Http2::active_timeout_in? Should it be the timeout no matter whether the client is active or not?

**Comment by maskit** [comment]
Though I'm not sure whether it works correctly now, from my understanding, `Http2::active_timeout_in` is an active timeout for H2 connections. And I would have to say the change doesn't make sense. Creating a new stream is an activity on a connection, and stream count 0 means there's no activity on the connection. Connections keep open if a client keep creating new streams, so it might be used for abuse, but I think it should be prevented with other protections (e.g. maximum count of streams on  a session).

**Comment by zizhong** [comment]
> I'm not sure whether it works correctly now

It seems to be a serious security issue. Could you please confirm if it works or not when you have a chance. Thanks!

> from my understanding, Http2::active_timeout_in is an active timeout for H2 connections. 

which makes it more suspicious that ATS keeps set the active_timeout again and again when creating new streams.
(By `H2 connections`, you mean the connections instead of streams, right?)

> but I think it should be prevented with other protections (e.g. maximum count of streams on a session)

No, currently it can not. Consider this, the stream limit is 3. A client creates stream 1, 2, 3, and then the stream 1 goes down, and then the client creates stream 4 ...

**Comment by maskit** [comment]
@zizhong 

> It seems to be a serious security issue. Could you please confirm if it works or not when you have a chance. Thanks!

I'm going to check it later.

> No, currently it can not. Consider this, the stream limit is 3. A client creates stream 1, 2, 3, and then the stream 1 goes down, and then the client creates stream 4 ...

Correct, it can not. I wanted to say that we need something else (if we really need it). Because stream creation is a valid activity on a connection even if it was suspicious activity, active timeout have to be reset when new stream has been created.

**Comment by maskit** [comment]
Aha, Sorry I may be wrong. Active timeout timer need to be enabled if it's disabled when creating a stream but the timer shouldn't be reset on every stream creation.

**Comment by maskit** [comment]
@zizhong `Http2::active_timeout_in` doesn't work like I thought. Please forget I wrote above.

 I'd like to confirm what you are trying to do.
timeout

I think you are making `Http2::active_timeout_in` to X on the figure above, and the reason is that a session can keep sitting there without any limitations. Is this correct?

I talked @masaori335 and we think timeout X would not be so effective. Even if we had timeout X, client can initiate a new connection right after the timeout, and this timeout can close legitimate long standing connection. The same thing (long standing sessions) happen on HTTP/1.1 with keep-alive. QUIC sessions may need this timeout for silent close but it would be few hours at least.

Why do you want to close long standing active sessions?

**Comment by zizhong** [comment]
@maskit Yes, what I want to do is set it to X exactly. Thanks for the nice graph you drew.
In the graph, you mentioned three types of timeouts, `TxnActiveTimeout`, `K-A Inactive timeout`, and `X`.
`K-A Inactive timeout` is done by `proxy.config.http2.no_activity_timeout_in`.
`TxnActiveTimout`, However, it is done by `proxy.config.http.transaction_active_timeout_in` instead of `Http2::active_timeout_in`.
`Http2::active_timeout_in` today is like a pure bug.  In your email, you mentioned that It is trying to timeout a transaction. But the VC it takes effect on is a connection instead of a transaction. So it can't correctly timeout a transaction. The timeout will reset when creating streams so a long stream cannot be timeout if there're other new streams incoming. Not to mention that, we've already got the `proxy.config.http.transaction_active_timeout_in` to be the `TxnActiveTimout`.

What I suggest to do is to make the buggy `Http2::active_timeout_in` to X. I understand it's not ideal but it's definitely needed. It can be set to several hours, several days or even set to be forever, and that should be a judgement call by the users instead of us. For us, we need to provide such a config to the users and let them choose for their best practice.

**Comment by maskit** [comment]
> Http2::active_timeout_in today is like a pure bug. In your email, you mentioned that It is trying to timeout a transaction. But the VC it takes effect on is a connection instead of a transaction. So it can't correctly timeout a transaction. The timeout will reset when creating streams so a long stream cannot be timeout if there're other new streams incoming.

Right. I guess the behavior came from H1 logic. Because H1 transactions run one by one, resetting timeout at the beginning of every transaction makes sense (for H1). On the other hand, H2 transactions run concurrently, so the same logic doesn't work.

> What I suggest to do is to make the buggy Http2::active_timeout_in to X. I understand it's not ideal but it's definitely needed. It can be set to several hours, several days or even set to be forever, and that should be a judgement call by the users instead of us. For us, we need to provide such a config to the users and let them choose for their best practice.

Well, I agree that we should do something against `Http2::active_timeout_in`. However, since `Http2::active_timeout_in` haven't worked as expected, it seems like we are introducing session active timeout actually. In that case, it would be great if it is available regardless of HTTP versions.

How about introducing `proxy.config.http.session_active_timeout_in` instead of reusing `proxy.config.http2.active_timeout_in`.

Also, I still don't understand why calls for `cancel_active_timeout()` need to be removed. I think it need to be cancelled when the connection gets inactive and be reenabled when it get active.

**Comment by zizhong** [comment]
Thank @maskit for the suggestion! I'll try to introduce a `session_active_time` and make it generic.
I'm under the impression that `active_timeout` is the total timeout regardless of activity, so I removed the `cancel_active_timeout()`. Is this understanding correct?

**Comment by maskit** [comment]
> I'm under the impression that active_timeout is the total timeout regardless of activity, so I removed the cancel_active_timeout(). Is this understanding correct?

Hmm, I see. Well, your understanding is probably correct.

I thought the timer need to be enabled during the session is actually active (txn count >= 1), but it's not consistent with transaction active timeout because transaction active timeout simply starts at the beginning of a transaction and keep ticking until timeout or end of transaction.

However, `cancel_active_timeout()` still need to be called from somewhere when the session ends. It seems that you removed all the calls.


@bryancall @zwoop I think we misunderstood the change. Can you check if we are heading to a right direction?

**Comment by zizhong** [comment]
@maskit the generic session timeout is not as straightforward as I thought. HTTP1 transaction timeout is the same thing as session timeout, while for HTTP2 they're not. Putting them together is not as ideal.
I added `cancel_active_timeout` back as you suggested. Now it begins timeout when starting a new connection and ends the timeout when no active streams.
Is this PR good to go for now? @maskit any ideas?

**Comment by maskit** [comment]
> HTTP1 transaction timeout is the same thing as session timeout, while for HTTP2 they're not.

Well, I guess "the same thing" means that the session will be closed when transaction has been timeout. However, we can start new transactions on a session before KA inactive timeout (or session timeout) occurs if the connection is keep-alived and all the transactions are done within transaction timeout. In this case, having separated timeout configuration for session timeout makes sense.

Since we are confused by what `proxy.config.http2.active_timeout_in` is, it would be great if you could add a description on the documentation, and it would be awesome if you could add autest test cases for this. I think making general session timeout can be separated change.

**Comment by maskit** [comment]
[approve ci]

**Comment by zizhong** [comment]
@maskit 

Docs and tests are added. Please check it again.

For HTTP1, in `Http1ClientTransaction.h`,
```
  void
  set_active_timeout(ink_hrtime timeout_in) override
  {
    if (parent)
      parent->set_active_timeout(timeout_in);
  }
```
makes the timeout is set the session instead of the transaction. That's why I called them `the same thing`.

**Comment by zizhong** [comment]
ping on this. @maskit

**Comment by maskit** [comment]
It doesn't look like the timeout X.

> However, cancel_active_timeout() still need to be called from somewhere when the session ends. It seems that you removed all the calls.

I didn't mean that the timer should be canceled when the session gets inactive. If you remove all calls for `cancel_active_timeout()`, the timeout event can be processed after closing the session. We should avoid it.

**Comment by zizhong** [comment]
I see. Sorry for misunderstanding your point.
I'll fix it accordingly.

**Comment by zizhong** [comment]
@maskit When session gets closed, we call `client_vc->do_io_close()` which will clear all the timeouts.

**Comment by maskit** [comment]
> When session gets closed, we call client_vc->do_io_close() which will clear all the timeouts.

OK, then we can remove the others as your first change request.

**Comment by zizhong** [comment]
@maskit updated

**Comment by maskit** [comment]
[approve ci]

**Comment by maskit** [comment]
@bryancall @zwoop I think this is a reasonable fix for H2 session active timeout. Can you double check?

**Comment by zizhong** [comment]
Again probably we need to increase the default value or disable it by default.

**Comment by zizhong** [comment]
@maskit the default value changed.
@zwoop commits squashed.

**Comment by maskit** [comment]
[approve ci]

**Comment by zizhong** [comment]
looking into the autest issue

**Comment by zizhong** [comment]
rebased. Can I get a [approve ci] again? @bryancall @zwoop @maskit @scw00

**Comment by maskit** [comment]
[approve ci]

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
Sorry, I removed a wrong message !

**Comment by maskit** [comment]
[approve ci autest]

@scw00 never mind. thanks for cleaning.

**Comment by zizhong** [comment]
@zwoop I don't understand this. Seems Jenkins ran against an older version of ATS?
I run `autest` against the latest master multiple times. It is always successful.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Looks like it's consistently failing the timeout tests in autest.

**Comment by zizhong** [comment]
Thanks @zwoop and @maskit !
I updated the rb. It's all about timing.
Can I get another [approve ci autest]?

**Comment by maskit** [comment]
[approve ci]

**Comment by zizhong** [comment]
@maskit Great! Thanks! This PR is good to go now, I think.

**Comment by maskit** [comment]
`proxy.config.http2.active_timeout_in` has been working strangely and the correct behavior has been unclear. We may be able to call this bugfix but I'm not sure whether we should backport this to 7.1.x. It may be a kind of incompatible change, and if so, we shouldn't make it between patch releases. Only users who changed the setting would be affected.

@zizhong @masaori335 What do you think?

**Comment by zwoop** [comment]
Are we sure this shouldn't go into the 7.1.2 release? I see that it's incompatible technically, but it also seems it was way broken before? If so, breaking "compatibility" of a broken feature is probably ok (unless this is at risk of making things worse).

**Comment by bryancall** [comment]
I don't think the commit is the correct logic.  The connection will be added to the keep alive queue even if there are active connections.

**Comment by zizhong** [comment]
@bryancall I don't fully understand your comment. When a VC is added into keep_alive_queue, it will be removed from active_queue, active_timeout is then not working.

**Comment by maskit** [comment]
@zwoop I understand your point but what would be the definition of "broken feature" in this case? Since it was not documented, nobody can tell its correct behavior. This is the reason I used "strangely" instead of "incorrectly". Honestly, I don't think somebody will complain about changing the behavior. I'm fine with backporting it if we can justify the incompatible change.

**Comment by masaori335** [comment]
I agree current behavior is "strange", so we can say this is a kind of bugfix. But if we backport this change to 7.1.2, when some people upgrade to 7.1.2 ( who have this config in their records.config ), they will get in trouble. Because they will see active connection is closed in shorter time than before.
I'm slightly -1 to backport to 7.1.x for compatibility.

**Pull request merged**
