### PR TITLE
Host status refactor 8.0.x backport

### PR DESCRIPTION
**Pull request by jrushford**
This PR back ports the HostStatus refactor that uses one stat per host and serializes the host status struct so that host status stats may be persisted and reloaded following an ATS restart.

In addition to the HostStatus refactor, the following prerequisite commits are also cherry-picked to resolve conflicts.

b09ac09 - fix self detection issue.
f22b06f - Use optionally provided hash string for hashing
58734d3 - Fix a regression in the traffic_ctl host status subcommand
05dd0fd - Fixes a segfault that may occur when the debug and a lookup fails to find an entry in the hoststatus hash table.
b3dbff1 - add a reason tag to traffic_control host subcommand.

### CODE REVIEW

**Comment by zwoop** [comment]
I don't think this should go into 8.0.4, but possibly 8.1.0.

**Comment by jrushford** [comment]
@vmamidi I squashed the commits.

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by dragon512** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci ubuntu]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
We can ignore the Ubuntu failure here

**Comment by randall** [comment]
Ultimately, is this for 8.0.x or 8.1.x?

**Comment by jrushford** [comment]
@randall it's for 8.0.x

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci ubuntu]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci ubuntu]

**Comment by zwoop** [comment]
No, this should not merge to 8.0.x. As commented above, and the Milestone was changed, this is going to 8.1.x.

**Pull request merged**
