### PR TITLE
TS-4916: Fix for an H2-infinite-loop deadlock

### PR DESCRIPTION
**Pull request by gtenev**
This is a fix to prevent destroying of the ``DLL<>`` structure and the following iteration over ``Http2ConnectionState::stream_list`` to fall into an infinite loop while holding a lock, which leads to cache updates to start failing.

### CODE REVIEW

**Comment by zwoop** [comment]
@gtenev This looks very strange, did you pull/rebase your tree first?

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/875/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/983/ for details.

**Comment by gtenev** [comment]
@zwoop I did, my fork looks OK. it seems to me that later in the github GUI I may have submitted the PR against base:master (which was the default), should have been against 6.2.x. Closing.

**Pull request closed without merging**
