### PR TITLE
cookie remap plugin

### PR DESCRIPTION
**Pull request by pushkar2017**
Cherry picked from the master with fixes for compiling in 7.1.x

### CODE REVIEW

**Comment by zwoop** [comment]
I'm pretty torn on this in general. I understand the reasoning, but we have (afaik) two options:

1. Install YAML CPP on some of the CI.
2. Pull the YAML CPP source tree.

Neither are awesome, and in fact, I worry about 1) because now we pull in some upstream YAML CPP version, which is unlikely to work for 8.0.0 and forward. Yes, in theory things should just be kosher, but then there's reality, and it becomes a shitshow. As such, my preference is *probably* to not install / require the YAML CPP library from the distros.

My real preference would be to not cherry-pick this into 7.1.x, but I'll leave it to @bryancall to decide, since he's made a valid argument for it.

**Comment by SolidWallOfCode** [comment]
I think it's reasonable to

*  Tweak this backport so that building the plugin is conditional on having YAMLCPP installed.
*  Require users of this in 7.1.x to install the 0.6.2 version of YAMLCPP.

**Comment by pushkar2017** [comment]
[approve clang-format]

**Comment by pushkar2017** [comment]
[approve ci clang-format]

**Comment by pushkar2017** [comment]
[approve ci autest]

**Comment by pushkar2017** [comment]
[approve clang-format]

**Comment by pushkar2017** [comment]
[approve ci clang-format]

**Comment by SolidWallOfCode** [comment]
The clang format test is one that isn't going to get better if you redo it. Note that the clang-format changed between 7 and 9, so it may be necessary to get the 7 version. I'm not sure what the CI runs.

**Comment by zwoop** [comment]
make clan-format will run the appropriate version automatically

**Comment by SolidWallOfCode** [comment]
Why is this a 9.0 milestone when it's a backport to 7.x?

**Comment by zwoop** [comment]
I think if we are going to land this into 7, it needs to use an external YAML CPP, and look for it using normal detection like pkgconfig and a —with-yaml-cpp=... option. I can maybe install such a library on the latest Fedora VM for the CI, it’s be a good tea that we can build with a “conflicting” installation of the YAML packages.

**Comment by pushkar2017** [comment]
@zwoop That is what I have done. I detect an external yaml-cpp using --with-yaml-cpp:
./configure --enable-experimental-plugins --with-yaml-cpp=/home/ppradhan/yaml-cpp-master

**Comment by SolidWallOfCode** [comment]
I think Pushkar has dealt with the various issues with the backport, this should be a clean commit that won't break things for anyone not using the plugin.

**Pull request merged**
