### PR TITLE
Replace time_t with std::chrono 

### LINKED ISSUE #10207: CID 1508971: Use of 32-bit time_t
```
359  while (!plugin_threads.shutdown) {
360    try {
361      if (!stek_initialized && ssl_param.pub) {
362        // Launch a request for the master to resend you the ticket key
363        std::string redis_channel = ssl_param.cluster_name + "." + STEK_ID_RESEND;
364        ssl_param.pub->publish(redis_channel, ""); // send it
365        TSDebug(PLUGIN, "Request for ticket.");
366      }
367      time(&currentTime);
368      time_t sleepUntil;
369      if (stek_initialized) {
370        // Sleep until we are overdue for a key update
371        sleepUntil       = 2 * STEK_MAX_LIFETIME - (currentTime - lastChangeTime);
372        stek_initialized = false;
373        check_count      = 0;
374      } else {
375        // Wait for a while in hopes that the server gets back to us
376        sleepUntil = 30;
377        ++check_count;
378      }
   	
CID 1508971 (#1 of 1): Use of 32-bit time_t (Y2K38_SAFETY)
1. store_truncates_time_t: A time_t value is stored in an integer with too few bits to accommodate it. The expression sleepUntil is cast to unsigned int.
379      ::sleep(sleepUntil);
380
381      if (check_count == 0) {
382        continue;
383      }
```

### PR DESCRIPTION
**Pull request by duke8253**
This resolves #10207

### CODE REVIEW

**Comment by duke8253** [comment]
> This looks like an awful lot of almost identical code duplication. Can we not make a common converter here, which takes some parameters ?

Yeah, I can do that. It's just that this plugin is now obsolete and is been replaced by the `stek_share` plugin. We can probably just deprecate this one imho.

**Comment by duke8253** [comment]
[approve ci]

**Comment by maskit** [comment]
> We can probably just deprecate this one imho.

Don't feel obligated to **fix** coverity issues assigned. I just want assignees to take care of those issues. However, the plugin does not seem like deprecated at the moment. Please make the consensus first, and then you can close the coveirty issue (maybe Classification: Bug, and Action: Ignore, with a comment about deprecation).

And I don't think deprecation is always a valid get-out-of-jail card. For example, if the code was part of TS API and we had to have the code on 10.0, we would probably want to fix the code even if we were going to remove it on 11.0. For this plugin, I'm not going to be that strict as it's an experimental plugin

**Comment by duke8253** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Review by jpeach — COMMENTED** [review]
time_t is 8 byes for 64bit builds. IIRC traffic server doesn't support 32bit any more.

**Comment by duke8253** [comment]
> time_t is 8 byes for 64bit builds. IIRC traffic server doesn't support 32bit any more.

This is just for this session reuse plugin. I'm not sure who is still using this one though, Yahoo has completely replaced this with the `stek_share` plugin already.

**Comment by SolidWallOfCode** [comment]
Perhaps we should look at promoting "ink_time.h" to something with a better name while making it accessible to plugins.

**Comment by jpeach** [comment]
> > time_t is 8 byes for 64bit builds. IIRC traffic server doesn't support 32bit any more.
> 
> This is just for this `session reuse` plugin. I'm not sure who is still using this one though, Yahoo has completely replaced this with the `stek_share` plugin already. Which is why I brought up maybe we should consider deprecating this one.

Sure, but my point is that there is not 32-bit time_t usage here, because time_t is 64-bit.

**Comment by duke8253** [comment]
> > > time_t is 8 byes for 64bit builds. IIRC traffic server doesn't support 32bit any more.
> > 
> > 
> > This is just for this `session reuse` plugin. I'm not sure who is still using this one though, Yahoo has completely replaced this with the `stek_share` plugin already. Which is why I brought up maybe we should consider deprecating this one.
> 
> Sure, but my point is that there is not 32-bit time_t usage here, because time_t is 64-bit.

Yeah, I think the problem is with the `sleep()` taking an `unsigned int` and coverity doesn't like that a 64bit value was provided.

**Review by zwoop — APPROVED** [review]

**Pull request merged**
