### PR TITLE
Document that = can be used between ESI param and value.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Review by maskit — APPROVED** [review]

**Comment by maskit** [comment]
Unrelated, but

> There are four optional arguments that can be passed to the above ``esi.so`` entry:

There are 5 arguments described right after the line. And there's one more on next step...

**Comment by ywkaras** [comment]
[approve ci freebsd]

**Comment by JosiahWI** [comment]
```
Caused by: hudson.plugins.git.GitException: Command "git init /home/jenkins/workspace/Github_Builds/autest" returned status code 1:
stdout: 
stderr: /home/jenkins/workspace/Github_Builds/autest/.git: Permission denied
```

**Comment by JosiahWI** [comment]
[approve ci autest]

**Pull request merged**
