### PR TITLE
DEBUG DNS fail 

### PR DESCRIPTION
**Pull request by scw00**
Debug used. will close after debugging.

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by oknet** [comment]
[approve ci autest]

**Comment by oknet** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[aaprove ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
[approve ci autest]

**Comment by scw00** [comment]
failed in https://ci.trafficserver.apache.org/job/autest-github/10893/console

**Pull request closed without merging**
