### PR TITLE
Add release procedures doc

### PR DESCRIPTION
**Pull request by ezelkow1**
Some basic steps for creating a new release, so I dont have to refer to old slack messages that may disappear

### CODE REVIEW

**Review by maskit — COMMENTED** [review]
Looks good, but I leave just a few comments because I've never done a release.

We need to make an announce on the lists. Not only the dev@ and users@ but also announce@t.a.o and announce@a.o at last.

It might be nice to have an email template for the vote and the release announce.

**Comment by ezelkow1** [comment]
Sure Im looking for input right now. This was just my initial list of steps that I had written down that are like the bare minimum procedures

**Review by bryancall — APPROVED** [review]
I am good with this, we can add stuff later

**Comment by ezelkow1** [comment]
ok sounds good, will just merge this in now and we can keep adding to it

**Pull request merged**
