### PR TITLE
Collapsed forwarding support in ATS core

### PR DESCRIPTION
**Pull request by ezelkow1**
This adds a new write fail action, CACHE_WL_FAIL_ACTION_COLLAPSED_FORWARDING. If it fails to obtain a write lock then it will loop for open_write_retries*open_read_retry_time, each time doing a DecideCacheLookup.  In the end if it fails to ever either obtain a
write lock or find the object to read then it does the default write fail action of going to the origin.

In testing using duplicated requests I can see multiple simultaneous requests end up in this read loop and eventually get a hit in cache while the original request gets written.  Occaisonally there is still an extra hit or two to the origin which I believe is
state machine dependant, so sort of unavoidable, sometimes you can have the original request finish the write while a duplicated request ends up obtaining the write lock directly afterwards and so it hits the origin as well. This may be unavoidable unless cache
lookups are done everywhere before a write.

On an origin fail it will do the default of sending back an ERR_CONNECT_FAIL

So far this has been tested with synthetic traffic. I am still working on testing with production traffic but wanted to get any feedback

### CODE REVIEW

**Comment by ezelkow1** [comment]
Will need a bit more debugging, looks like Im getting double increments on the write retries,
[Jun  4 16:54:42.603] Server {0x2b8193f0c700} DEBUG: <HttpTransact.cc:3046 (handle_cache_write_lock)> (http_error) [641366] cache_open_write_fail_action 5, cache miss, retry read with collapsed forwarding try #2
[Jun  4 16:54:42.603] Server {0x2b8193f0c700} DEBUG: <HttpTransact.cc:3112 (handle_cache_write_lock)> (http_error) [641366] calling DecideCacheLookup for collapsed forwarding
[Jun  4 16:54:43.511] Server {0x2b8193f0c700} DEBUG: <HttpTransact.cc:3046 (handle_cache_write_lock)> (http_error) [641366] cache_open_write_fail_action 5, cache miss, retry read with collapsed forwarding try #4
[Jun  4 16:54:43.511] Server {0x2b8193f0c700} DEBUG: <HttpTransact.cc:3112 (handle_cache_write_lock)> (http_error) [641366] calling DecideCacheLookup for collapsed forwarding
[Jun  4 16:54:44.445] Server {0x2b8193f0c700} DEBUG: <HttpTransact.cc:3056 (handle_cache_write_lock)> (http_error) [641366] cache_open_write_fail_action 5, miss, ran out of write retries, doing default

Would still appreciate any feedback though

**Comment by zwoop** [comment]
[approve ci]
[add to whitelist]

**Comment by ezelkow1** [comment]
So I am hitting a core with this in production, though the output is less than helpful. Ill attach it later, hopefully someone may have an idea. I havent seen it yet testing with synthetic traffic though, only seeing it during heavy load times

**Comment by ezelkow1** [comment]
Getting stuck on this core (its a 7x build with similar changes as here). Also updated my changes here to reflect using the transact state instead of calling decidecachelookup directly.

[ 0  ] libpthread-2.17.so  __libc_waitpid                                               ( :undefined             ) 
[ 1  ] traffic_server      crash_logger_invoke                                          ( Crash.cc:164           ) 
[ 2  ] libpthread-2.17.so  0x2b291d9435e0                                               ( :undefined             ) 
[ 3  ] libc-2.17.so        raise                                                        ( :undefined             ) 
[ 4  ] libc-2.17.so        __GI_abort                                                   ( :undefined             ) 
[ 5  ] libtsutil.so.7.1.3  ink_abort                                                    ( ink_error.cc:99        ) 
[ 6  ] libtsutil.so.7.1.3  _ink_assert                                                  ( ink_assert.cc:37       ) 
[ 7  ] traffic_server      _TSReleaseAssert                                             ( InkAPI.cc:402          ) 
[ 8  ] traffic_server      TSHttpTxnCachedRespGet                                       ( InkAPI.cc:4865         ) 
[ 9  ] regex_revalidate.so get_date_from_cached_hdr                                     ( regex_revalidate.c:393 ) 
[ 10 ] regex_revalidate.so main_handler                                                 ( regex_revalidate.c:425 ) 
[ 11 ] traffic_server      INKContInternal::handle_event(int, void*)                    ( InkAPI.cc:1050         ) 
[ 12 ] traffic_server      HttpSM::state_api_callout(int, void*)                        ( HttpSM.cc:1425         ) 
[ 13 ] traffic_server      HttpSM::set_next_state()                                     ( HttpSM.cc:7245         ) 
[ 14 ] traffic_server      HttpSM::call_transact_and_set_next_state(void (*)(HttpTra... ( HttpSM.cc:7212         ) 
[ 15 ] traffic_server      HttpSM::handle_api_return()                                  ( HttpSM.cc:1563         ) 
[ 16 ] traffic_server      HttpSM::state_api_callout(int, void*)                        ( HttpSM.cc:1498         ) 
[ 17 ] traffic_server      HttpSM::set_next_state()                                     ( HttpSM.cc:7245         )
 [ 18 ] traffic_server      HttpSM::call_transact_and_set_next_state(void (*)(HttpTra... ( HttpSM.cc:7212         ) 
[ 19 ] traffic_server      HttpSM::state_cache_open_read(int, void*)                    ( HttpSM.cc:2568         )
 [ 20 ] traffic_server      HttpSM::main_handler(int, void*)                             ( HttpSM.cc:2630         ) 
[ 21 ] traffic_server      handleEvent                                                  ( I_Continuation.h:153   ) 
[ 22 ] traffic_server      HttpCacheSM::state_cache_open_read(int, void*)               ( HttpCacheSM.cc:132     ) 
[ 23 ] traffic_server      handleEvent                                                  ( I_Continuation.h:153   ) 
[ 24 ] traffic_server      CacheVC::callcont(int)                                       ( P_CacheInternal.h:653  ) 
[ 25 ] traffic_server      CacheVC::openReadStartEarliest(int, Event*)                  ( CacheRead.cc:914       ) 
[ 26 ] traffic_server      handleEvent                                                  ( I_Continuation.h:153   ) 
[ 27 ] traffic_server      CacheVC::handleReadDone(int, Event*)                         ( Cache.cc:2463          ) 
[ 28 ] traffic_server      handleEvent                                                  ( I_Continuation.h:153   ) 
[ 29 ] traffic_server      AIOCallbackInternal::io_complete(int, void*)                 ( P_AIO.h:117            ) 
[ 30 ] traffic_server      handleEvent                                                  ( I_Continuation.h:153   ) 
[ 31 ] traffic_server      EThread::process_event(Event*, int)                          ( UnixEThread.cc:140     ) 
[ 32 ] traffic_server      EThread::process_queue(Queue<Event, Event::Link_link>*)      ( UnixEThread.cc:175     ) 
[ 33 ] traffic_server      EThread::execute_regular()                                   ( UnixEThread.cc:207     ) 
[ 34 ] traffic_server      spawn_thread_internal                                        ( Thread.cc:84           ) 
[ 35 ] libpthread-2.17.so  start_thread                                                 ( :undefined             )

**Comment by ezelkow1** [comment]
Also here is the history at the latest point I can get it
`         history = array
            [0] = 
               fileline = 0x7810cf
                  *0x7810cf = string(0x7810cf, [HttpSM.cc:627])
               event = 100
               reentrancy = 2
            [1] = 
               fileline = 0x7816d0
                  *0x7816d0 = string(0x7816d0, [HttpSM.cc:1296])
               event = 60000
               reentrancy = 3
            [2] = 
               fileline = 0x7813dc
                  *0x7813dc = string(0x7813dc, [HttpSM.cc:1336])
               event = 60000
               reentrancy = 3
            [3] = 
               fileline = 0x7816d0
                  *0x7816d0 = string(0x7816d0, [HttpSM.cc:1296])
               event = 60000
               reentrancy = 4
            [4] = 
               fileline = 0x7813dc
                  *0x7813dc = string(0x7813dc, [HttpSM.cc:1336])
               event = 60000
               reentrancy = 4
            [5] = 
               fileline = 0x7816d0
                  *0x7816d0 = string(0x7816d0, [HttpSM.cc:1296])
               event = 60000
               reentrancy = 5
            [6] = 
               fileline = 0x7813dc
                  *0x7813dc = string(0x7813dc, [HttpSM.cc:1336])
               event = 60000
               reentrancy = 5
            [7] = 
               fileline = 0x7816d0
                  *0x7816d0 = string(0x7816d0, [HttpSM.cc:1296])
               event = 60000
               reentrancy = 6
            [8] = 
               fileline = 0x7813dc
                  *0x7813dc = string(0x7813dc, [HttpSM.cc:1336])
               event = 60000
               reentrancy = 6
            [9] = 
               fileline = 0x78177c
                  *0x78177c = string(0x78177c, [HttpSM.cc:7393])
               event = 65535
               reentrancy = 6
            [10] = 
               fileline = 0x780d72
                  *0x780d72 = string(0x780d72, [HttpSM.cc:4543])
               event = 48640
               reentrancy = 6
            [11] = 
               fileline = 0x7794af
                  *0x7794af = string(0x7794af, [HttpCacheSM.cc:118])
               event = 1102
               reentrancy = -1
            [12] = 
               fileline = 0x78143e
                  *0x78143e = string(0x78143e, [HttpSM.cc:2541])
               event = 1102
               reentrancy = 1
            [13] = 
               fileline = 0x7816d0
                  *0x7816d0 = string(0x7816d0, [HttpSM.cc:1296])
               event = 60000
               reentrancy = 2
            [14] = 
               fileline = 0x7813dc
                  *0x7813dc = string(0x7813dc, [HttpSM.cc:1336])
               event = 60000
               reentrancy = 2
            [15] = 
               fileline = 0x78175e
                  *0x78175e = string(0x78175e, [HttpSM.cc:7353])
               event = 65535
               reentrancy = 2
            [16] = 
               fileline = 0x78175e
                  *0x78175e = string(0x78175e, [HttpSM.cc:7353])
               event = 65535
               reentrancy = 2
            [17] = 
               fileline = 0x7817a9
                  *0x7817a9 = string(0x7817a9, [HttpSM.cc:7510])
               event = 65535
               reentrancy = 2
            [18] = 
               fileline = 0x7794eb
                  *0x7794eb = string(0x7794eb, [HttpCacheSM.cc:177])
               event = 1109
               reentrancy = -1
            [19] = 
               fileline = 0x7794eb
                  *0x7794eb = string(0x7794eb, [HttpCacheSM.cc:177])
               event = 2
               reentrancy = -1
            [20] = 
               fileline = 0x7810a3
                  *0x7810a3 = string(0x7810a3, [HttpSM.cc:2419])
               event = 1109
               reentrancy = 1
            [21] = 
               fileline = 0x78177c
                  *0x78177c = string(0x78177c, [HttpSM.cc:7393])
               event = 65535
               reentrancy = 1
            [22] = 
               fileline = 0x780d72
                  *0x780d72 = string(0x780d72, [HttpSM.cc:4543])
               event = 48640
               reentrancy = 1
            [23] = 
               fileline = 0x7794af
                  *0x7794af = string(0x7794af, [HttpCacheSM.cc:118])
               event = 1102
               reentrancy = -1
            [24] = 
               fileline = 0x78143e
                  *0x78143e = string(0x78143e, [HttpSM.cc:2541])
               event = 1102
               reentrancy = 1
            [25] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [26] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [27] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [28] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [29] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [30] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [31] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [32] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [33] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [34] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [35] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [36] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [37] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [38] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [39] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [40] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [41] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [42] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [43] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [44] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [45] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [46] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [47] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [48] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [49] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [50] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [51] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [52] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [53] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [54] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [55] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [56] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [57] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [58] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [59] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [60] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [61] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [62] = 
               fileline = 0
               event = 0
               reentrancy = 0
            [63] = 
               fileline = 0
               event = 0
               reentrancy = 0
         history_pos = 25
`

**Comment by bryancall** [comment]
It looks like this PR still needs some work and hasn't been updated for a few months.  Closing for now.  Please reopen if there are updates.

**Pull request closed without merging**
