### PR TITLE
Clear all pointers in API Hooks clear function.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
This should be merged into ATS9.

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
Note that, for @a-canary 's Session object refactoring, this change causes Au test regression to run clean by eliminating many test case failures:  https://github.com/apache/trafficserver/pull/6272 .

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
