### PR TITLE
TS-4713: Remove obsolete TSFetchClientProtoStackSet/Get

### PR DESCRIPTION
**Pull request by masaori335**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/502/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/399/ for details.

**Comment by jpeach** [comment]
+1

**Comment by zwoop** [comment]
Do it.

**Pull request merged**
