### PR TITLE
Modify TSHttpTxnHookAdd to add hook only once

### PR DESCRIPTION
**Pull request by meeramn**
Change-Id: I45c9cdbe305e8b3d186beafb87ab5f8c5b03b757

### CODE REVIEW

**Comment by zwoop** [comment]
Marking this for 7.1.0, we really need this in.

**Comment by zwoop** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
Ship it.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1231/ for details.

**Comment by zwoop** [comment]
@meeramn Can you re-run clang-format and update the PR please?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1337/ for details.

**Comment by zwoop** [comment]
[approve ci]

**Comment by meeramn** [comment]
Ran clang-format and pushed the change.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1349/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1242/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1350/ for details.

**Comment by zwoop** [comment]
Well, dammit, I screwed up, this really shouldn't have been merged, you really must squash multiple commits like this into one commit (now I landed one commit that is not correct). :-/

**Comment by zwoop** [comment]
Not going to do the reverts here, but please be careful going forward with squashing commits that are fixes / review comments.

**Pull request merged**
