### PR TITLE
Add 5xx's to be allowed to be used for simple retries

### PR DESCRIPTION
**Pull request by ezelkow1**
Adding support for 5xx in the simple retry parent scenario. This also removes redundant functions that existed in http transact that replicated PS functionality.

Simple retry will always take precedence if there is a conflict in the codes list between simple and unavailable retries so that there is not a run through of simple retries followed by unavailable retries

### CODE REVIEW

**Review by jrushford — DISMISSED** [review]
looks good to me.

**Comment by bryancall** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by bneradt** [comment]
@SolidWallOfCode will review this.

**Review by SolidWallOfCode — APPROVED** [review]

**Comment by bryancall** [comment]
Comcast is running this in production.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
