### PR TITLE
Removes unused raft library

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Before we land this, hopefully @jplevyak can chime in? He added this some time ago, but not sure why :-). It's definitely not used though, but maybe the intent was to use it ?

**Comment by randall** [comment]
The jira this was originally committed under mentioned adding it for clustering use.

https://issues.apache.org/jira/browse/TS-3786

I assumed(I know) since we removed clustering, this could go also.

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
