### PR TITLE
Make volume.config YAML-based configuration

### PR DESCRIPTION
**Pull request by masaori335**
Address #10766. 

Updating Docs are excluded. I'll update it if the schema is concreted.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
I've looked at this in the past and think we should combine "storage.config" and "volume.config". A suggested format would be
```
cache:
  spans:
  - id: # identifier / name of the span.
    path: # path to storage.
    size: # size in bytes, required for file system storage, optional for raw device.
    hash_seed: # optional. Used to isolate lookup from path changes.
  volumes:
  - id: # name of the volume.
    size: # optional cross check of size.
    scheme: # optional, default to "http"
    ram-cache: # auto/enable |  size | disable
    spans:
    - id: # match span ID
      size: # bytes or %

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci osx]

**Comment by masaori335** [comment]
Combining `storage.config` and `volume.config` is reasonable. Both of them are un-reloadable and configs are closely related.

1. What we should call this combined config? `storage.yaml`? Because we can say "the `storage.yaml` defines spans and volumes".

2. For the format, what's your motivation of flipping volume and span mapping? Currently, span config in the storage.config has volume tag. Below is much smoother to convert from current configs?

```
cache:
  spans:
  - path: # path to storage.
    size: # size in bytes, required for file system storage, optional for raw device.
    hash_seed: # optional. Used to isolate lookup from path changes.
    volume: id # match volume ID
  volumes:
  - id: # name of the volume.
    size: # optional cross check of size.
    scheme: # optional, default to "http"
    ram-cache: # auto/enable |  size | disable
```

**Comment by bneradt** [comment]
[approve ci autest format]

**Comment by SolidWallOfCode** [comment]
1. I would like "cache.yaml" although that potentially collides with "cache.config". The latter, IMHO, should be eliminated and that configuration done by plugins.
2. Because the volume ID in the span description is a hack that should be eliminated. The spans are the base storage, they should have nothing about volumes because that creates a cyclic dependency. Volumes are made up of spans and so should do all specifying about which spans are used. Again, otherwise you have the volume -> span mapping in two different places, rather than in a single place, the volume description.
3. No, unfortunately. We may need to have other schemes. If we default it to "HTTP" then it's not required to be in the configuration and can be used only in future special cases.

The one thing we might want to change is `volume:size`. For better compatibility this should support a "%" size and in that case not require `volume:spans`.

**Comment by masaori335** [comment]
Close in favor of #11010

**Pull request closed without merging**
