### PR TITLE
Add lib/tsconfig to clang formatting.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
For some reason `lib/tsconfig` wasn't being clang formatted. This corrects that along with doing the formatting.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci centos]

**Comment by SolidWallOfCode** [comment]
[ci approve centos]

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by maskit** [comment]
```
TsBuilder.cc:33:1: error: expected identifier before 'namespace'
 namespace
 ^
TsBuilder.cc:33:1: error: expected '}' before 'namespace'
TsBuilder.cc:33:1: error: expected unqualified-id before 'namespace'
TsBuilder.cc:257:1: error: expected '}' at end of input
 } // namespace ts::config
 ^
TsBuilder.cc:257:1: error: expected '}' at end of input
```

```
TsBuilder.cc:33:1: error: expected identifier
namespace
^
TsBuilder.cc:257:26: error: expected '}'
} // namespace ts::config
                         ^
./TsConfigGrammar.hpp:2:18: note: to match this '{'
  enum TokenType {
                 ^
TsBuilder.cc:257:2: error: expected ';' after enum
} // namespace ts::config
 ^
 ;
TsBuilder.cc:257:26: error: expected '}'
} // namespace ts::config
                         ^
./TsConfigGrammar.hpp:1:33: note: to match this '{'
namespace ts { namespace config {
                                ^
TsBuilder.cc:257:26: error: expected '}'
} // namespace ts::config
                         ^
./TsConfigGrammar.hpp:1:14: note: to match this '{'
namespace ts { namespace config {
             ^
5 errors generated.
```

**Comment by zwoop** [comment]
Yeh, as discussed over dinner, we excluded this directory intentionally, because there are generated files here that do not adhere to our standards.

**Comment by maskit** [comment]
> Yeh, as discussed over dinner, we excluded this directory intentionally, because there are generated files here that do not adhere to our standards.

That's fine, but I don't understand why compilers complain about the syntax.

**Comment by SolidWallOfCode** [comment]
Yeah, I'd forgotten that. I'll see if I can fix it to exclude the generated files.

**Comment by zwoop** [comment]
Don't know why the compiler fails, perhaps this generated code throws a wrench into clang-format's wheels.

**Comment by SolidWallOfCode** [comment]
Going to pull this for now, because the generated files mess this up. Once I have TsLuaConfig running I'll revisit this.

**Pull request closed without merging**
