### PR TITLE
Update references in configuration variable implementation

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
# PR Summary
Commit updates the references in `doc/developer-guide/config-vars.en.rst`.

### CODE REVIEW

**Review by masaori335 — APPROVED** [review]
Thank you for fixing links!

**Comment by masaori335** [comment]
[approve ci]

**Review by bneradt — APPROVED** [review]

**Comment by masaori335** [comment]
[approve ci]

**Comment by masaori335** [comment]
[approve ci]

**Comment by masaori335** [comment]
[approve ci]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
