### PR TITLE
Add auto options for all experimental plugins

### PR DESCRIPTION
**Pull request by JosiahWI**
Auto options were added for the experimental plugins with special dependencies in #10741. This adds options for the remaining experimental plugins.

### CODE REVIEW

**Comment by bneradt** [comment]
In case it's helpful:
https://ci.trafficserver.apache.org/job/Github_Builds/job/ubuntu/3647/console

```
INFO: YAML_CPP version 0.8.0
CMake Error at cmake/AutoOptionHelpers.cmake:142 (add_subdirectory):
  add_subdirectory given source "plugins/experimental/hook_trace" which is
  not an existing directory.
Call Stack (most recent call first):
  cmake/ExperimentalPlugins.cmake:111 (auto_option)
  CMakeLists.txt:604 (include)
```

Thanks for working on this.

**Comment by JosiahWI** [comment]
Blocking on #10968.

**Comment by bryancall** [comment]
[approve ci osx]

**Comment by JosiahWI** [comment]
The OSX failure is due to a CMake issue present in master. I discussed it with @cmcfarlen and am working on a fix. Marking this as a draft until then.

**Comment by bryancall** [comment]
[approve ci osx]

**Comment by JosiahWI** [comment]
This is about ready, but I still have to solve the problem of ImageMagick being used both in both the webp_transform and magick plugins.

**Comment by JosiahWI** [comment]
It was discussed that it is clearer to have auto_options just set the `USE_XXX` variables, and put the logic to add the subdirectories in `experimental/CMakeLists.txt`. I will update the PR with this change at some point.

**Comment by JosiahWI** [comment]
A CMake issue that caused the necessity for a workaround for ImageMagick is being tracked here: https://gitlab.kitware.com/cmake/cmake/-/issues/25970.

**Review by cmcfarlen — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Comment by leontian** [comment]
@cmcfarlen auto options for stale_response plugin was not added when cherry-picked to v10.0.x, also missing add_subdirectory(http_stats). These 2 plugins are not built with latest 10.0.x and BUILD_EXPERIMENTAL_PLUGINS=ON

**Comment by JosiahWI** [comment]
Thank you for reporting, @leontian, those two were indeed missed. I will PR a fix.

**Pull request merged**
