### PR TITLE
Add support for header_table for lua plugin

### PR DESCRIPTION
**Pull request by shukitchan**
Adding support for header_table in lua plugin

### CODE REVIEW

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
Updated the gold test with suggestions from @traeak

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci autest]

**Review by traeak — APPROVED** [review]

**Pull request merged**
