### PR TITLE
Replaces "smart" quotes with ASCII equivalents

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by randall** [comment]
[approve ci docs]

**Comment by maskit** [comment]
I'm curious what this is for. I guess non-ascii characters don't make problems in this day and age. Smart quotes are not good even in docs?

**Comment by randall** [comment]
I was working in another codebase and had hit issues with smart quotes (json files using them). I was curious what we had and this was the result of that. 

In the docs, it's probably less important. But something that's a shell command
```
--define “release 12"
```
would fail if I copied/pasted.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
