### PR TITLE
Fixes for building with OpenSSL 1.1

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1307/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1414/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1415/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1308/ for details.

**Comment by zwoop** [comment]
[approve ci] to get the clang-analyzer build

**Comment by zwoop** [comment]
@jablko do we need two commits here? Or can they be squashed?

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1339/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1446/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/Github-Clang/11/ for details.

**Comment by jablko** [comment]
@zwoop I separated the commits because they each address a different issue -- #1384 and #1385. I think that makes the most sense ... but I'm happy to squash them if you prefer!

**Comment by jablko** [comment]
Merged. Thanks @zwoop!

**Comment by zwoop** [comment]
I'm going to cherry-pick this to 7.1.x as well. Done! :)

**Pull request merged**
