### PR TITLE
Correctly deal with the ssl.client.sni_policy if not set via conf_remap

### PR DESCRIPTION
**Pull request by shinrich**
Turns out I was dealing with the conf_remap case for sni_policy but not the simple set it in records.config case.  Augmented a test to exercise this case.

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Pull request merged**
