### PR TITLE
TS-4067: Memory leaks in parent selection regression tests.

### PR DESCRIPTION
**Pull request by jrushford**
Fixed all of the memory leaks in the ParentSelection regression tests.

### CODE REVIEW

**Comment by jrushford** [comment]
@jpeach and @zwoop I modified the regression test REBUILD and REINIT macros and added code to free allocated memory.  This eliminated all the parent selection regression test memory leaks identified using libgmalloc and leaks.

**Comment by jpeach** [comment]
This looks better. @jrushford can you please wrap these macros in a ```do { ... } while (0)``` block? They are giving me the heebie-jeebies.

Could you consider rewriting these tests to be more structured and maintainable?

**Comment by jrushford** [comment]
@jpeach, I'll wrap these macros in the do {...} while(0) block, good idea.  I'll think about the re-write in the future but, I have some other things that are higher priority.  Are you +1 on landing this after the do {} while(0) changes?

**Comment by jpeach** [comment]
Yes that sounds fine, thanks @jrushford

**Pull request merged**
