### PR TITLE
Converts remaining header files to #pragma once

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
I'm not sure how to check, but I though I had seen in a place or two code that checked the include guard for file A.h in a different file, to detect if A.h has been included. I suppose, though if it builds, that's not a problem.

**Comment by randall** [comment]
@SolidWallOfCode I look for those, but couldn't find any myself (not to say there aren't any still there).

**Comment by maskit** [comment]
The check @SolidWallOfCode mentioned is probably this:
https://github.com/apache/trafficserver/blob/master/iocore/eventsystem/I_Thread.h#L61-L63

**Comment by maskit** [comment]
Since few other commits for this conversion is backported, this should be backported too.

**Pull request merged**
