### PR TITLE
Ts 3534

### PR DESCRIPTION
**Pull request by ericcarlschwartz**
Initial pull request for wiretracing v0. Please leave me your comments and I'll make changes as necessary.

Looking into this now: Making sure we turn tracing off for all connections when we return them to the pool Sudheer pointed this out to me.

Any other input would be greatly appreciated. Some of the feedback from the summit was passed on to me but would always be happy to hear more again. I know there was discussion of refactoring some of this. I also know there was discussion of outputting pcap files instead of traces to a log. <- this one might be hard because the traces are based on what's read from the buffers and not on the individual packets. if someone could point me to code where i could get that kind of granularity that would be a cool enhancement.

### CODE REVIEW

**Comment by ericcarlschwartz** [comment]
Right now this PR is multiple commits. I'll probably be adding to it as people have suggestions for improvement. I can squash stuff down before anything gets merged :)

**Comment by ushachar** [comment]
It would be better to move all the 'when to debug' logic into plugin space -- you can extend the TSHttpSsnDebugSet API, hook a plugin on the SNI callback and do whatever you want from there instead of adding more code to the already overcomplicated VConn layer.

This will also allow you to turn on debugging for specific requests (based on full URLs/headers/whatever) sort of like the xdebug plugin.

**Comment by jpeach** [comment]
I only looked quickly, but just a couple of points. The use of ``TCP_INFO`` is non-portable so this feature will need to be conditional. Why would we have our own tracing framework? There's already dtrace, systemtap and probably others. We should integrate with them rather than invent something that is less complete.

**Comment by sudheerv** [comment]
I agree with @jpeach on the TCP_INFO usage. Are the TCP_INFO traces even part of the wire trace feature? Besides being non-portable, isn't there also (significant?) cost associated with having to call getsockopt on every read/write operation?

FWIR, they were at one point added to debug some post failure issue, and not originally meant to be part of the wire tracing?

**Comment by jpeach** [comment]
Wireshark decrypts SSL, https://wiki.wireshark.org/SSL.

**Comment by sudheerv** [comment]
Yes, but, you would need to know/use the cert to do that, which is not always straightforward - as I said, "the problem with existing tools is that they can not (easily) decrypt the SSL traffic. "

**Comment by jpeach** [comment]
Well if you can configure logging on the ATS server, then it seems reasonable that you would have access to the SSL keys.

**Comment by RolandZink** [comment]
With perfect forward secrecy getting the necessary keys becomes more difficult. I made some better experience by getting the session keys from the browsers. Some (Chrome and Firefox) support storing the session keys into a file and Wireshark can read the file. What needs to be done is setting the SSLKEYLOGFILE environment variable, see for example https://jimshaver.net/2015/02/11/decrypting-tls-browser-traffic-with-wireshark-the-easy-way/.

Maybe ATS can write a similar file?

**Comment by ericcarlschwartz** [comment]
@sudheerv: the TCP_INFO usage can definitely be dropped because of the associated cost/its only situational usefulness. i will prepare a patch with it removed.

**Comment by ericcarlschwartz** [comment]
I've dropped the tcp_info traces.

My understanding was in line with @sudheerv's that this was never intended as a total replacement to using wireshark, but rather an easier to use method that could cover many cases.

I'll look more into Roland's proposal. I haven't worked with chrome or firefox SSL key log files before. Do you only feed wireshark only the key for the corresponding client session or does the log contain all the symmetric keys generated for each client?

**Comment by RolandZink** [comment]
The log contains more than one key. When the browser writes it then there is only one client but more than one server and wireshark can decrypt all the connections. Not sure if wireshark will be happy to have all keys for all ATS clients in one file.

**Comment by ericcarlschwartz** [comment]
@RolandZink, yeah that's what I was thinking. I will do some searching and see if something like that's been done before and how wireshark will behave with all the ATS clients' keys.

**Comment by shinrich** [comment]
I'm afraid I'm being a bit dense, but where is sslServerName ever set to a non-null value?

**Comment by bryancall** [comment]
https://issues.apache.org/jira/browse/TS-3534

**Comment by ericcarlschwartz** [comment]
@shinrich I think this is ready for another look if you or someone else has some time.

**Comment by shinrich** [comment]
The SNI name check looks better.  A couple comments remaining.

computeSSLTrace() might be getting called more than once per transaction.  You are probably better off pull the block that calls computeSSLTrace() and setSSLTrace() into the if(this->ssl == NULL) block and call that after the make_ssl_connection call.  Save a bit of unnecessary work.

The other comment is about the client_vc and server_vc manipulations in HttpSM.  Your casts are not going to work in the H2 and SPDY cases.  The server_vc will be ok, but the client_vc is a PluginVC in those cases.  Fortunately, you don't de-reference the client_vc only dynamic_cast it, so the code is safe, but your tracing will be off for SPDY/H2.  I know that you are working on those issues for another project, so the SPDY/H2 wiretracing support can be updated later.

**Comment by ericcarlschwartz** [comment]
@shinrich ah ok thanks for the comments. I'll make that first change today.

w.r.t. the second comment will have to think more about it. because we only do the cast on the client_vc which is where H2 and SPDY are I think there might be a way to refactor since PluginVC and SSLNetVC both share the NetVC base class. A fun project for later you're right.

Just for some clarification, if a PluginVC is not an SSLNetVC, how is the SSLHandshake handled in SPDY/H2 cases?

**Comment by shinrich** [comment]
For SPDY and H2 the underlying SSLNetVConnection is stored with the SPDYClient and the Http2Client respectively.  Multiple faux Http1.1 transactions are created and sent via FetchSM/PluginVC.  I think you were working this this issue with the logging changes you are doing.

**Comment by ericcarlschwartz** [comment]
Ah yes I remember that part of things in terms of what's stored where, was just wondering how that worked exactly since the ssl_vc is in the faux transaction and (for spdy at least) the protocol selection is part of the handshake w/ NPN. I just ran a test w/ spdycat and see what's happening now a little better

**Comment by ericcarlschwartz** [comment]
@shinrich: did some testing there. the problem w/ putting it right in that particular spot is that the return value from SSL_get_servername call will always be null. Looks like we don't have that information from the SSL object yet.  

I could move the call into SSLUtils where we're getting the cert for SNI anyway?

**Comment by ericcarlschwartz** [comment]
and for the non SNI-enabled case I can put it in the equivalent function in the corresponding #else block

**Comment by ericcarlschwartz** [comment]
@shinrich here's a proposed solution:

if TS_USE_TLS_SNI isn't set then we put the logic where you'd suggested. if it is, we set the trace right after we lookup the servername

**Comment by shinrich** [comment]
@ericcarlschwartz that sounds like a reasonable solution.  I see that you've done half of it by adding the if !(TS_USE_TLS_SNI) in the handshake code.

You'll need to add the SNI case to ssl_servername_callback and the ssl_cert_callback to cover openssl 1.0.1 and 1.0.2+

**Comment by ericcarlschwartz** [comment]
@shinrich I added it to set_context_cert because it looks like both the ssl_servername_callback and ssl_cert_callback will call that and it saves some code duplication. is that ok? or should I move it to each?

**Comment by shinrich** [comment]
@ericcarlschwartz Nevermind.  I just missed it the first time.  Looks good.

**Comment by ushachar** [comment]
I still think all the SSLNetVConnection::computeSSLTrace() logic should be moved into plugin space - even if not extending TSHttpSsnDebugSet and keeping this as a standalone option.
Also - how about a macro to unify lines like these:
"""
Debug("ssl.error", "SSLNetVConnection::sslClientHandShakeEvent, SSL_ERROR_WANT_READ");
TraceIn(trace, get_remote_addr(), get_remote_port(),  "SSL client handshake ERROR_WANT_READ");
"""

**Comment by shinrich** [comment]
@ushachar I agree with your comment about making the computeSSLTrace decision accessible from the plugin.  I read your earlier comment too quickly and thought you wanted to put all the trace logic into a plugin. 

Having some simple controls in records.config seems reasonable (like the current single name, single IP, and percentage).   But then we can give control to a plugin to make more elaborate decisions.  Perhaps we could file another bug to track a new PluginAPI or an extension to the TSHttpSsnDebugSet API.

Also agree that a macro might eliminate some code redundancy.

**Comment by jpeach** [comment]
I think @ushachar is suggesting that this whole feature should be in a plugin?

**Comment by ushachar** [comment]
I think moving the entire "when to debug" logic to plugin space would be a better idea -- yes.
Mostly in order to simplify the core code, but also to allow someone to easily extend it without treading into the 'here be dragons' area of the NetVCs :-)
There's already a hookpoint in the handshake phase -- all we'd need to do would be to add the plugin + API to set the flag....

**Comment by ericcarlschwartz** [comment]
@ushachar @shinrich I tend to agree that having some simple stuff available as records.config settings for those who don't want to write a new plugin each time they want to enable traces is a good call. 

But being able to enable tracing via a plugin also seems valuable and it shouldn't be hard to extend or modify computeSSLTrace to that effect. If someone wants to open a JIRA for doing that and assign it to me, that's work I'd be happy to take on.

**Comment by ericcarlschwartz** [comment]
@shinrich rebased off apache/master and opened a new PR for this here. this one had some weirdness because of issues w/ apache/master and yahoo/master being out of sync

New PR is here for all to look at/comment on: https://github.com/apache/trafficserver/pull/246

**Pull request closed without merging**
