### PR TITLE
Remove dependencies on include/tscore

### PR DESCRIPTION
**Pull request by edhall**
Plugins shouldn't have dependencies on internal header files.

### CODE REVIEW

**Comment by randall** [comment]
[approve ci]

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
It looks fine. Please squash the commits into one.

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
It looks good. thanks.

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
[approve ci autest]

**Comment by a-canary** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
