### PR TITLE
setup pre-commit hook at cmake generation time

### PR DESCRIPTION
**Pull request by cmcfarlen**
Also add target to run autopep8 to satisfy the hook

### CODE REVIEW

**Comment by cmcfarlen** [comment]
[approve ci rocky]

**Review by brbzull0 — APPROVED** [review]
great!! thanks.

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]

**Pull request merged**
