### PR TITLE
Force using C++17 as the default standard

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci centos]

**Comment by zwoop** [comment]
[approve ci debian]

**Comment by zwoop** [comment]
[approve ci freebsd]

**Comment by zwoop** [comment]
[approve ci debian]

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Pull request merged**
