### PR TITLE
Fix rare H2 Start/Close Hook misses

### PR DESCRIPTION
**Pull request by a-canary**
I was seeing rare failures on autest/openclose_h2, which lead to a number of fixes mostly performed by @shinrich 

Changes include:
Delay transactions on lock failures, so the open hook happens before the close hook, and before the destroy.
Fixes to preserver VCONN_CLOSE and SSN_CLOSE orderings
Fix threading issues verification code. 
Inflated number of requests to test with higher thread contention.

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
The `tls_tunnel` test failure might be a serious issue.

**Comment by shinrich** [comment]
Yes, failed two of 3 times (random java failure the other time).  Will dig in.

**Comment by a-canary** [comment]
replaced with #6364

**Pull request closed without merging**
