### PR TITLE
[TS-4488] fix Segmentation fault at HttpSM::tunnel_handler_ua

### PR DESCRIPTION
**Pull request by yatsukhnenko**
```
#0  get_netvc (this=0x2ad0834fbc00, event=104, c=0x2ad0834fd8a8) at HttpServerSession.h:113
#1  HttpSM::tunnel_handler_ua (this=0x2ad0834fbc00, event=104, c=0x2ad0834fd8a8) at HttpSM.cc:3067
#2  0x000000000056c16e in HttpTunnel::consumer_handler (this=0x2ad0834fd800, event=104, c=0x2ad0834fd8a8) at HttpTunnel.cc:1261
#3  0x000000000056d16d in HttpTunnel::main_handler (this=0x2ad0834fd800, event=<value optimized out>, data=<value optimized out>) at HttpTunnel.cc:1492
#4  0x0000000000687961 in handleEvent (event=<value optimized out>, nh=0x2ad051aa8c00, vc=0x2ad060800000) at ../../iocore/eventsystem/I_Continuation.h:146
#5  write_signal_and_update (event=<value optimized out>, nh=0x2ad051aa8c00, vc=0x2ad060800000) at UnixNetVConnection.cc:153
#6  write_signal_done (event=<value optimized out>, nh=0x2ad051aa8c00, vc=0x2ad060800000) at UnixNetVConnection.cc:180
#7  0x000000000068acf5 in write_to_net_io (nh=0x2ad051aa8c00, vc=0x2ad060800000, thread=0x2ad051aa5000) at UnixNetVConnection.cc:472
#8  0x000000000067ed43 in NetHandler::mainNetEvent (this=0x2ad051aa8c00, event=<value optimized out>, e=<value optimized out>) at UnixNet.cc:400
#9  0x00000000006ab4cf in handleEvent (this=0x2ad051aa5000, e=0x2ad054a16e40, calling_code=5) at I_Continuation.h:146
#10 EThread::process_event (this=0x2ad051aa5000, e=0x2ad054a16e40, calling_code=5) at UnixEThread.cc:145
#11 0x00000000006abd0b in EThread::execute (this=0x2ad051aa5000) at UnixEThread.cc:269
#12 0x00000000004c46fb in main (argv=<value optimized out>) at Main.cc:1659
```

### CODE REVIEW

**Comment by shinrich** [comment]
Looks reasonable to me.

**Comment by atsci** [comment]
This is a test message.

**Comment by zwoop** [comment]
Note that this fails the unit checks, please see details on

https://ci.trafficserver.apache.org/job/Github-Linux/42/console

**Comment by yatsukhnenko** [comment]
Moved variable declaration to top of function, try to build again, pls

**Comment by zwoop** [comment]
Failed clang-format this time :)

https://ci.trafficserver.apache.org/job/Github-Linux/43/console

**Comment by yatsukhnenko** [comment]
fixed

**Comment by jpeach** [comment]
What's the trigger for this bug? Is it reproducible? Can we add a regression test?

**Comment by yatsukhnenko** [comment]
Sorry, I don't know how to reproduce this bug :( It happens when I use [plugin](https://github.com/apache/trafficserver/pull/644) which uses vconnections. But there is some additional info in traffic.out which may be helpful
```
DEBUG: (http_redirect) [HttpTunnel::producer_handler] enable_redirection: [1 0 1] event: 100
DEBUG: (http_tunnel) [833] consumer_handler [cache write t VC_EVENT_WRITE_READY]
DEBUG: (http_tunnel) [833] consumer_handler [user agent VC_EVENT_WRITE_READY]
DEBUG: (http_tunnel) [833] producer_handler [cache read VC_EVENT_READ_READY]
DEBUG: (http_redirect) [HttpTunnel::producer_handler] enable_redirection: [1 0 0] event: 100
DIAG: (limit_rate) TSEventImmediate
DEBUG: (http_tunnel) [833] consumer_handler [user agent VC_EVENT_WRITE_READY]
DEBUG: (http_tunnel) [833] consumer_handler [user agent VC_EVENT_ERROR]
DEBUG: (http) [833] [&HttpSM::tunnel_handler_ua, VC_EVENT_ERROR]
DEBUG: (http) [833] Initiating background fill
NOTE: Traffic Server received Sig 11: Segmentation fault
```
I lost debug info for VC_EVENT_EOS event

**Comment by yatsukhnenko** [comment]
Yet another trace
```
#0  0x0000000000503cb4 in HttpServerSession::get_netvc (this=0x0) at ./http/HttpServerSession.h:113
#1  0x00000000005653e9 in HttpSM::tunnel_handler_ua (this=0x2b29ed800000, event=3, c=0x2b29ed801ca8) at HttpSM.cc:3067
#2  0x00000000005a9356 in HttpTunnel::consumer_handler (this=0x2b29ed801c00, event=3, c=0x2b29ed801ca8) at HttpTunnel.cc:1261
#3  0x00000000005a9a56 in HttpTunnel::main_handler (this=0x2b29ed801c00, event=3, data=0x2b29d14146f0) at HttpTunnel.cc:1492
#4  0x00000000004e5a9c in Continuation::handleEvent (this=0x2b29ed801c00, event=3, data=0x2b29d14146f0) at ../iocore/eventsystem/I_Continuation.h:146
#5  0x00000000006b0224 in write_signal_and_update (event=3, vc=0x2b29d1414580) at UnixNetVConnection.cc:153
#6  0x00000000006b0322 in write_signal_done (event=3, nh=0x2b29c3009c00, vc=0x2b29d1414580) at UnixNetVConnection.cc:180
#7  0x00000000006b03b2 in write_signal_error (nh=0x2b29c3009c00, vc=0x2b29d1414580, lerrno=32) at UnixNetVConnection.cc:199
#8  0x00000000006b117b in write_to_net_io (nh=0x2b29c3009c00, vc=0x2b29d1414580, thread=0x2b29c3006000) at UnixNetVConnection.cc:476
#9  0x00000000006b0afb in write_to_net (nh=0x2b29c3009c00, vc=0x2b29d1414580, thread=0x2b29c3006000) at UnixNetVConnection.cc:351
#10 0x00000000006aa5a8 in NetHandler::mainNetEvent (this=0x2b29c3009c00, event=5, e=0x2b29c5216d80) at UnixNet.cc:400
#11 0x00000000004e5a9c in Continuation::handleEvent (this=0x2b29c3009c00, event=5, data=0x2b29c5216d80) at ../iocore/eventsystem/I_Continuation.h:146
#12 0x00000000006d11ce in EThread::process_event (this=0x2b29c3006000, e=0x2b29c5216d80, calling_code=5) at UnixEThread.cc:145
#13 0x00000000006d16d8 in EThread::execute (this=0x2b29c3006000) at UnixEThread.cc:269
#14 0x00000000006d07b8 in spawn_thread_internal (a=0x2b29c22854c0) at Thread.cc:88
#15 0x00002b29c12109d1 in start_thread () from /lib64/libpthread.so.0
#16 0x000000318a6e88fd in clone () from /lib64/libc.so.6
```
It seems I do something wrong in plugin

**Pull request closed without merging**
