### PR TITLE
Add utility for printing string_view with printf-like functions.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by maskit** [comment]
I guess it'd be slower than current because of memcpy, right? I'm not keen on using the non-standard utility just to shorten lines calling printf-like functions a little. I hope a new format specifier for string_view will be introduced in the future though. Any pros I'm missing?

**Comment by ywkaras** [comment]
C++ supports printf() only as  legacy function, so I'd be surprised if a specifier were added in the standard lib.

If we add a string_view format specifier in our functions, we might not be able to declare them "printf-like" using the GCC extension, and we can't loose that compile time checking.

**Comment by ywkaras** [comment]
Me personally, I still prefer:  https://github.com/apache/trafficserver/pull/7711

**Comment by maskit** [comment]
I'd say #7711 is better, but still not my cup of tea.

**Comment by ywkaras** [comment]
> What do you think about using fmtlib? Seems like it supports string_view.
> 
> #7296

Looks good except for one apparent, huge flaw, when you print to a buffer, you don't pass in the buffer length it seems:  https://github.com/bryancall/format-benchmark/commit/0fc372058e7db96de3423a989173a9bc0fe68533#diff-a7cd0eba35fcc2bae863d4093c81bac869812eb9017cbf152308481c80af9716R430

So presumably that means you can corrupt memory potentially.

**Comment by rob05c** [comment]
> Looks good except for one apparent, huge flaw, when you print to a buffer, you don't pass in the buffer length it seems: > https://github.com/bryancall/format-benchmark/commit/0fc372058e7db96de3423a989173a9bc0fe68533#diff-a7cd0eba35fcc2bae863d4093c81bac869812eb9017cbf152308481c80af9716R430

> So presumably that means you can corrupt memory potentially.

You can pass the buffer length with `format_to_n`

https://en.cppreference.com/w/cpp/utility/format/format_to_n
https://fmt.dev/latest/api.html#_CPPv4I0DpEN3fmt11format_to_nE18format_to_n_resultI8OutputItE8OutputIt6size_t13format_stringIDp1TEDpRR1T

**Pull request closed without merging**
