### PR TITLE
TS-4172: Cleanup debug logs of Http2ConnectionState

### PR DESCRIPTION
**Pull request by masaori335**
[TS-4172](https://issues.apache.org/jira/browse/TS-4172)

### CODE REVIEW

**Comment by masaori335** [comment]
I agree with we should keep consistency. So, I'm going to keep current names and debug tag in Http2ClientSession.

The problem is same name (DebugHttp2Ssn) and tag (http2_cs) are used in both Http2ClientSession and Http2ConnectionState.
As you know, thoes two are different classes completely. Http2ClientSession is low level class to handle VConnection to client and Http2ConnectionState is high level class to handle HTTP/2 frames and streams.

When I'm debugging HTTP/2 component, I want to see debug logs from only Http2ConnectionState to check what frame is received or sent in which stream in many times.

**Comment by masaori335** [comment]
@jpeach Please take a look

**Comment by bryancall** [comment]
I think it would make sense to have a DebugHttp2Stream that would be used at the stream level and format both ids, which is most of the debugging.

**Comment by masaori335** [comment]
@bryancall It looks good. But it totally needs 3 macros like below as far as I tried.

```
#define DebugHttp2Con(ua_session, fmt, ...) \
  DebugSsn(ua_session, "http2_con", "[%" PRId64 "] " fmt, ua_session->connection_id(), __VA_ARGS__);

#define DebugHttp2StreamMsg(ua_session, stream_id, msg) \
  DebugSsn(ua_session, "http2_stream", "[%" PRId64 "] [%u]" msg, ua_session->connection_id(), stream_id);

#define DebugHttp2StreamFmt(ua_session, stream_id, fmt, ...) \
  DebugSsn(ua_session, "http2_stream", "[%" PRId64 "] [%u]" fmt, ua_session->connection_id(), stream_id, __VA_ARGS__);
```

Actually this is what we're doing in Http2ClientSession. See [Http2ClientSession.cc#L34-L36](https://github.com/apache/trafficserver/blob/master/proxy/http2/Http2ClientSession.cc#L34-L36).
Is there better macros technics? Or is this just fine?

**Comment by masaori335** [comment]
(Because of I force pushed, James's comment is disappeared:\ )

**Comment by jpeach** [comment]
You should not need both ``DebugHttp2StreamMsg`` and ``DebugHttp2StreamFmt``, since is it valid (widely implemented GCC extension) to not pass any format arguments with ``__VA_ARGS__``.

**Comment by masaori335** [comment]
@jpeach I thought that too, but it has error in my box (CentOS7, gcc-4.8)
Diff: https://paste.apache.org/4tlm
Result: https://paste.apache.org/gnEb

**Comment by jpeach** [comment]
Sorry, you need to use [##__VA_ARGS__](https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html).

**Comment by masaori335** [comment]
I didn't know this one. Thanks!
I'll fix with this.

**Comment by masaori335** [comment]
Please take another look

**Comment by bryancall** [comment]
+1 - Debugging code looks better now

**Comment by jpeach** [comment]
+1

**Pull request closed without merging**
