### PR TITLE
clean up body factory tests

### PR DESCRIPTION
**Pull request by dragon512**
The goal here is to clean up some tests that have this awful ( subjective) piping that takes time. The gold files have been cleaned up as a few have a extra /n in them that don't report well currently in AuTest

### CODE REVIEW

**Comment by dragon512** [comment]
Just as a note for the reviewers...   sys.executable allow us to use the same version of python we are using with autest.

**Review by bneradt — APPROVED** [review]
Looks good to me.

**Comment by dragon512** [comment]
@masaori335 I hope this PR clean up help shows that a lot of what is going on is not needed. I do however need to have the gold file tester show \n better as that is a utter pain to understand this is the issue today with the autest report

**Review by masaori335 — APPROVED** [review]
Cool, we don't need these pipes. Changing gold files seems reasonable :+1:

**Comment by dragon512** [comment]
I agree. However the from the user point of view is it obvious in many of the ats cases why the file is different I have to address this better in AuTest. The main issue seems to be that ATS is sensitive to whitespace and the gold tester is not showing this well

**Pull request merged**
