### PR TITLE
cache_range_request autests: make more robust and clean up.

### PR DESCRIPTION
**Pull request by traeak**
More fixes to deal with header reordering and incorrect xdebug key comparison.

### CODE REVIEW

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
