### PR TITLE
Remove freelist from ClassAllocator

### PR DESCRIPTION
**Pull request by duke8253**
Remove freelist from ClassAllocator, and change the `-f` flag to disable freelist in ProxyAllocator, based on comments from #2988.

### CODE REVIEW

**Comment by zwoop** [comment]
Nice! I wonder if we should have an email sent to the mailing list for this change before we land?

**Comment by duke8253** [comment]
I think we probably should send one.

**Comment by shinrich** [comment]
Should probably update docs on the -f option too.

**Comment by duke8253** [comment]
I couldn't find anything in the documentation related to the -f option.

**Comment by duke8253** [comment]
Closing this for now.

**Pull request closed without merging**
