### PR TITLE
Do not change stream state from HALF_CLOSED_REMOTE with CONTINUATION frame

### PR DESCRIPTION
**Pull request by masaori335**
Backport #5585 to 8.0.x with autest cleanups (#4300 & #5921)

----

This is a combination of 3 commits.

1. Expand the post chunked tests.

(cherry picked from commit a523a62e2f309694bd6811f8b35eecbc678c24fb)

2. Do not change stream state from HALF_CLOSED_REMOTE with CONTINUATION frame

(cherry picked from commit d765d1a33328b43ca83ecc9d0ae39ac01a307a88)

3. Cleanup AuTest for HTTP/2

(cherry picked from commit 76cadf55ece2253c0ddf01a172c57c346f8cd89a)

Conflicts:
	tests/gold_tests/h2/http2.test.py

### CODE REVIEW

**Comment by randall** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
[approve ci clang-format]

**Comment by randall** [comment]
[approve ci clang-format]

**Comment by randall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
I'll reopen against 8.1.x branch.

**Pull request closed without merging**
