### PR TITLE
Update Proxy Verifier to v2.10.0

### PR DESCRIPTION
**Pull request by bneradt**
This includes the ability to specify separate DATA frames for a stream as well as a way to keep a session open after the final transaction.

### CODE REVIEW

**Review by randall — APPROVED** [review]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
This had an issue with one of the autests. @duke8253 created a fix for Proxy Verifier that is now in v2.10.1. I'm replacing this PR with #10322 that updates to the latter release.

**Pull request closed without merging**
