### PR TITLE
header_rewrite: Add INBOUND condition.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Add the `INBOUND` condition for access to information about the inbound connection.

### CODE REVIEW

**Comment by zwoop** [comment]
Btw, do we really need 6 commits here? It might be better to squash this down to two at least?

**Comment by SolidWallOfCode** [comment]
I was waiting to squash until after you bikeshedded. One of the things I wanted you to comment on is that this makes your `IP` condition obsolete eventually. Clearly the natural thing to do next is to add `OUTBOUND` after which would come `INBOUND:LOCAL-ADDR`, `INBOUND:REMOTE-ADDR`, `OUTBOUND:LOCAL-ADDR` and `OUTBOUND:REMOTE-ADDR`. I wasn't sure how you felt about that. If you still think that's OK, let me know and I'll squash it and commit.

Yes, the expansion is ugly. I pondered how to do that non-ugly but it's more invasive than I was ready for in this PR. I have plans, though, to build some other infrastructure that could be used in this situation to make it well structured.

**Comment by zwoop** [comment]
Yeh, I'm ok with marking that obsolete. I prefer one single way to do things.

Now that you are asking for it (I didn't want to do this yesterday), but I think I'd prefer the expansion patterns for these conditions to be in upper case, as they are in all conditions. That's more consistent.

**Comment by SolidWallOfCode** [comment]
Consistent with what? The other expansion variables are in lower case :-). And of course you waited until I'd squashed...but what choice do I really have? Give me a bit.

**Comment by zwoop** [comment]
Consistent with how we spell those strings in conditions. At some point, I'm gonna clean that up I think, and make all conditions / operators available as substation strings.

And yes, of course I waited! :-P

**Comment by zwoop** [comment]
My thinking is that since we're mixing operators and log tags, we keep the upper case for the operator strings, and lower case for the log tags (which is consistent with how they are used in logging.config).

**Pull request merged**
