### PR TITLE
Fix race condition in thread startup.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
When a thread is actually created/started there is a race condition. The thread start up logic uses data in the `Thread` instance. This is updated as an assignment from the return value of `ink_thread_create`. It can happen the new thread starts before the assignment complete so the `tid` member in the `Thread` instance is the default value, which breaks. This introduces a mutex that holds the thread start until the `Thread` instance is fully initialized. This can't be done earlier because the final value, as noted, isn't available until after thread start.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci icc]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Milestones, Labels etc. ...

**Pull request merged**
