### PR TITLE
Removes disabled test; case is covered elsewhere

### PR DESCRIPTION
**Pull request by d2r**
This test was disabled. Its case is now covered by [http204_response.test.py](https://github.com/apache/trafficserver/blob/e35c5a9240c868554295a8945146bfa75dbd466b/tests/gold_tests/body_factory/http204_response.test.py).

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by d2r** [comment]
@bryancall @dragon512 
Rebased this change since updates were made to this skipped test since I removed it.

The change is still the same: remove the test file.

**Comment by d2r** [comment]
@dragon512 Does CI need to be restarted or is it stuck?

**Comment by dragon512** [comment]
[approve ci autest]

**Comment by dragon512** [comment]
[approve ci]

**Comment by d2r** [comment]
The FreeBSD build has failed, and it seems to be an assert in an unrelated piece of code:
Here is the context:

```
[SDK_API_HttpTxnTransform] TSTransformCreate : [TestCase1] <<PASS>> { ok }
[SDK_API_HttpTxnTransform] TSHttpTxnTransformRespGet : [TestCase] <<PASS>> { ok }
Fatal: ../../proxy/InkIOCoreAPI.cc:600: failed assertion `sdk_sanity_check_iocore_structure(bufp) == TS_SUCCESS`
 183
Tests Failed: 0
```

I doubt this could have been caused by removing a test. What is the next step?

**Comment by d2r** [comment]
[approve ci]

**Comment by d2r** [comment]
[approve ci autest]

**Pull request merged**
