### PR TITLE
Adding clangd language server files to .gitignore

### PR DESCRIPTION
**Pull request by bneradt**
Adding some ignore entries for files generated by the clangd language
server for editors that use it.

### CODE REVIEW

**Comment by bneradt** [comment]
Marking for the various supported releases since this is could be helpful for anyone editing files in those releases while it is low risk since it's not a product-impacting change.

**Review by masaori335 — APPROVED** [review]
Actually, I have this in my local git config :)

**Comment by ezelkow1** [comment]
If we want this for 8.x can we get a backport?

**Comment by bneradt** [comment]
> If we want this for 8.x can we get a backport?

Sure thing:
https://github.com/apache/trafficserver/pull/8652

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
