### PR TITLE
Use thread_local to speed things up in JeAllocator

### PR DESCRIPTION
**Pull request by duke8253**
As mentioned in #7501 , testing whether `thread_local` helps with performance. @bryancall will help with benchmarking.

### CODE REVIEW

**Comment by bryancall** [comment]
I ran benchmarks on this PR on our AMD Epyc 64/128 servers and the rps went from 35K rps to 98K rps with this change.  This PR removes the reader/writer locks to fetch the arenas.

**Review by bryancall — APPROVED** [review]

**Review by zwoop — APPROVED** [review]
Yeh, this is good!

This is why I want that "ScheduleOnEveryThread()" function, so a plugin can use thread local, but (re)initialize its local thread data on demand :-).

**Comment by zwoop** [comment]
I believe (please correct me if I'm wrong) that this fixes the locking issues introduced via #7501 , which is not in 9.1.x. Do we really want to pull in #7501 for 9.1.x ?

**Comment by duke8253** [comment]
#7501 sill has some performance improvements over the original versions actually, mainly creating a seperate arena for each thread, and it cleaned up some unnecessary code as well, so it might be a cleaner cherry pick with it.

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
