### PR TITLE
TS-4929: No loading of HostDB disk file if sync_frequency=0

### PR DESCRIPTION
**Pull request by zwoop**
This has two benefit (2) is most important I think:

1) We avoid warnings on startup about not being able to load the HostDB.

2) Since in 7.0.0, turning off syncing (sync_frequency=0) completely disables writing to HostDB, it's now possible to end up loading a potentially stale HostDB from a previous upgrade.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/928/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/822/ for details.

**Comment by jpeach** [comment]
@zwoop (1) and (2) sound like they are in conflict? I'm confused about whether it loads or not? If it does load, do you really have a stale record problem, since each record has a TTL?

**Comment by zwoop** [comment]
Yes, they would have TTLs, but if I turned off syncing, I certainly wouldn't expect it to load something old. What if I had bad entries? What if I had a corruption of some sort? Since it will never update it, you are stuck with loading old (possibly stale or more likely expired) entries for the remaining of life? That just makes no sense.

**Comment by jpeach** [comment]
OK that sounds reasonable.

**Pull request merged**
