### PR TITLE
TS-3123 Make proxy.config.http.transaction_active_timeout_in overridable

### PR DESCRIPTION
**Pull request by zwoop**
This does set the timeout twice though, which is necessary assuming
that we want to retain backward compatibility where the activity
timeout is set way early.

### CODE REVIEW

**Comment by zwoop** [comment]
I'm going to land this tomorrow, unless there are objections to this?

**Comment by zwoop** [comment]
Testing a little, so be nice. [approve ci]

**Comment by atsci** [comment]
Build triggered. sha1 is merged.

**Comment by atsci** [comment]
Build started sha1 is merged.

**Comment by atsci** [comment]
Build finished.

**Pull request closed without merging**
