### PR TITLE
libswoc: Remove legacy TextView

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Remove legacy `TextView`.

The changes that required code updates are

* The `char` overloads for `prefix` / `suffix` were renamed to `prefix_at` / `suffix_at`. Although it sounds good in theory, the flexibility of integral conversion makes the overload fraught.
* `char` based prefix / suffix operators would return all of the view if the target wasn't found. That was changed to return an empty view

### CODE REVIEW

**Review by bneradt — DISMISSED** [review]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci cmake]

**Review by bneradt — APPROVED** [review]

**Pull request merged**
