### PR TITLE
Make FileManager ctor private. 

### PR DESCRIPTION
**Pull request by brbzull0**
Fix singleton class by making his ctor private and also explicitly add code to avoid any copies.

### CODE REVIEW

**Review by ywkaras — COMMENTED** [review]
Looks good.

**Review by bneradt — COMMENTED** [review]
Looks good.

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Review by masaori335 — APPROVED** [review]
Looks good and the freaky autest is gone.

**Pull request merged**
