### PR TITLE
TS-4425: Make Ptr<T> pointer value private.

### PR DESCRIPTION
**Pull request by jpeach**
Make the actual pointer value of Ptr<T> private so that code reaching
in to do unsafe direct manipulate has to do it explicitly. Also
remove the implicit conversions to the raw pointer value.

Ping @amc, @bgaff, @zwoop. There are a lot of changes here and I need to do some more testing. I *think* that this is worth doing, but would appreciate any early feedback.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
I'm not sure we need to prevent the implicit conversion to a pointer. What's important is the inability to touch the member variable in `Ptr` that holds the raw pointer. Our `Ptr` is equivalent to `std::instrusive_ptr` and one key advantage of that over `std::shared_ptr` is the ability to safely access the raw pointer.

**Comment by jpeach** [comment]
Do you mean ``boost::intrusive_ptr``? That doesn't have any implicit conversions.

If we keel OK about keeping the implicit conversion, then most of this diff goes away. I'm OK with that.

**Comment by jpeach** [comment]
This has been running on docs.trafficserver.a.org for a couple of days, passes regressions and jtest load. I'll land it later today.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
[approve ci]

**Comment by jpeach** [comment]
Merged.

**Pull request closed without merging**
