### PR TITLE
Fixed 2707, assign server_session to nullptr after do `chain_abort_all`

### LINKED ISSUE #2707: Crash HttpTransactHeaders::insert_via_header_in_response (bad session?)
Saw this with current 7.1.x (as of yesterday's 7.1.x branch):

```
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x000055e996aee1f4 in HttpTransactHeaders::insert_via_header_in_response (s=0x2b1c120513b0, header=0x2b1c12051b10)
    at HttpTransactHeaders.cc:882
        new_via_string = "\220\243\260Q\033+\000\000\326N\276\226\351U\000\000\060\243\260Q\033+\000\000\021,\252\226\351U\000\000\070BN\210\326\062?\214\336\305Ȗ\351U", '\000' <repeats 18 times>, "\004", '\000' <repeats 15 times>, "\060\017\000\000\000\000\000\000\000\225\270L\033+\000\000pn\363\226\351U\000\000\070\347J\227\351U\000\000\360՜]V+\000\000Xs\002\022\034+\000\000\220\243\260Q\033+\000\000oz\251\226\351U\000\000HPP\363!+\000\000\000PP\363!+\000\000\360֜]V+\000\000\360՜]V+\000\000\001\b\237\306\030\023ӄ\360՜]V+\000\000\025\000\000\000\000\000\000\000\360՜]V+\000\000"...
        n_proto = 1
        ss = 0x2b1bf9ff7c40
        proto_buf = <optimized out>
        via_string = <optimized out>
        via_limit = <optimized out>
        incoming_via = <optimized out>
#2  0x000055e996ad8f96 in HttpTransact::build_response (s=<optimized out>, base_response=<optimized out>, outgoing_response=<optimized out>,
    outgoing_version=..., status_code=<optimized out>, reason_phrase=<optimized out>) at HttpTransact.cc:8082
        fields = {{name = 0x2b1b4cbaa328 "Etag", len = 4, presence = 2097152}, {name = 0x2b1b4cba9fa8 "Content-Location", len = 16,
            presence = 32768}, {name = 0x2b1b4cbaa408 "Expires", len = 7, presence = 4194304}, {name = 0x2b1b4cba9c98 "Cache-Control",
            len = 13, presence = 512}, {name = 0x2b1b4cbab4a8 "Vary", len = 4, presence = 4503599627370496}}
#3  0x000055e996ac552b in HttpTransact::build_response (s=0x2b1c120513b0, outgoing_response=0x9, outgoing_version=...,
    status_code=HTTP_STATUS_REQUEST_TIMEOUT, reason_phrase=0x55e996c62c98 "Inactive Timeout") at HttpTransact.cc:7974
No locals.
#4  HttpTransact::build_error_response (s=0x2b1c120513b0, status_code=HTTP_STATUS_REQUEST_TIMEOUT, reason_phrase_or_null=<optimized out>,
    error_body_type=<optimized out>, format=0x0) at HttpTransact.cc:8230
        ap = {{gp_offset = 2738120704, fp_offset = 11095, overflow_arg_area = 0x2b1bb0efc710, reg_save_area = 0x2b57a3346800}}
        body_language = "\020Z\002\022\034+\000\000\070\347J\227\351U\000\000\000[\242L\033+\000\000K\027\374H\033+\000\000Pދ\330\033+\000\000\000\225\270L\033+\000\000ະQ\033+\000\000\301P\252\226\351U\000\000 \000\360\226\351U\000\000\000z\301\226\351U\000\000\020Z\002\022\034+\000\000\000\000\000\000\000\000\000\000\240a\002\022\034+\000\000\340a\002\022\034+\000\000\325\036", '\000' <repeats 14 times>, "\300\353Ȗ\351U\000\000\000\000\000\000\000\000\000\000\300\353Ȗ\351U\000\000\066\374Ȗ\351U", '\000' <repeats 18 times>, "\024\213\006i\035+\000\000\026\213\006i\035+\000\000\000\000\000\000\033+\000\000\300۠N\033+\000\000"...
        body_type = "\300\270\260Q\033+\000\000\302P\263\226\351U\000\000\000\340\273L\033+\000\000K\027\374H\033+\000\000\000\345J\227\351U\000\000\360\260\177d\034+\000\000ะQ\033+\000\000^\037\270\226\351U\000\000H\307\360\226\351U\000\000\360\260\177d\034+\000\000\360\260\177d\034+\000\000\335\037\270\226\351U\000\000P\324\371\266\033+\000\000\000\225\270L\033+\000\000P\324\371\266\033+\000\000\257&\270\226\351U\000\000\370\305\360\226\351U\000\000P\324\371\266\033+\000\000\000\225\270L\033+\000\000@|\377\371\033+\000\000P\324\371\266\033+\000\000\034I\270\226\351U\000\000@|\377\371\033+\000\000\000\225\270L\033+\000\000@|\377\371\033+\000\000\r\022"...
        url_string = <optimized out>
        reason_phrase = <optimized out>
        len = <optimized out>
        new_msg = <optimized out>
#5  0x000055e996ac5fc1 in HttpTransact::PostInactiveTimeoutResponse (s=0x2b1c120513b0) at HttpTransact.cc:594
No locals.
#6  0x000055e996aa909e in HttpSM::call_transact_and_set_next_state (this=0x2b1c12051340, f=<optimized out>) at HttpSM.cc:7231
No locals.
#7  HttpSM::tunnel_handler_post (this=0x2b1c12051340, event=2301, data=<optimized out>) at HttpSM.cc:2793
        p_handler_state = <optimized out>
#8  0x000055e996aa2c11 in HttpSM::main_handler (this=0x2b1c12051340, event=2301, data=0x2b1c120526a0) at HttpSM.cc:2696
        jump_point = <optimized out>
#9  0x000055e996af0d86 in Continuation::handleEvent (this=<optimized out>, event=2301, data=<optimized out>)
    at /usr/src/debug/bazinga-trafficserver-7.1.2/iocore/eventsystem/I_Continuation.h:153
No locals.
#10 HttpTunnel::main_handler (this=0x2b1c120526a0, event=<optimized out>, data=<optimized out>) at HttpTunnel.cc:1665
        p = <optimized out>
        c = <optimized out>
#11 0x000055e996c22e33 in Continuation::handleEvent (this=<optimized out>, event=1, data=<optimized out>)
    at /usr/src/debug/bazinga-trafficserver-7.1.2/iocore/eventsystem/I_Continuation.h:153
No locals.
#12 read_signal_and_update (event=1, vc=0x2b4881bdaef0) at UnixNetVConnection.cc:144
No locals.
#13 0x000055e996c23aea in UnixNetVConnection::mainEvent (this=<optimized out>, event=1, e=0x2b1c120526a0) at UnixNetVConnection.cc:1257
        signal_timeout_at = <optimized out>
        writer_cont = <optimized out>
        reader_cont = 0x2b1c120526a0
#14 0x000055e996c1848d in Continuation::handleEvent (event=1, this=<optimized out>, data=<optimized out>)
    at /usr/src/debug/bazinga-trafficserver-7.1.2/iocore/eventsystem/I_Continuation.h:153
No locals.
#15 InactivityCop::check_inactivity (this=<optimized out>, event=<optimized out>, e=0x2b1b4d9fe700) at UnixNet.cc:77
        now = 1508884633786338709
#16 0x000055e996c3eae0 in Continuation::handleEvent (this=<optimized out>, event=2, data=<optimized out>) at ./I_Continuation.h:153
No locals.
#17 EThread::process_event (this=0x2b1b4ea0dbc0, e=0x2b1b4d9fe700, calling_code=2) at UnixEThread.cc:143
        c_temp = <optimized out>
#18 0x000055e996c3f0e0 in EThread::execute (this=<optimized out>) at UnixEThread.cc:225
        done_one = true
        next_time = <optimized out>
#19 0x000055e996c3e2d7 in spawn_thread_internal (a=0x2b1b4cbb3930) at Thread.cc:84
No locals.
#20 0x00002b1b4bc27aa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#21 0x00002b1b4b974bcd in clone () from /lib64/libc.so.6
No symbol table info available.
```

### PR DESCRIPTION
**Pull request by scw00**
this closes #2707 !

### CODE REVIEW

**Comment by oknet** [comment]
@zwoop This is a 7.1.x candidate.

**Comment by zwoop** [comment]
I tested this on Docs, but it still crashed in the same assertion. The way I reproduce this is on Docs, and it seems to happen primarily with the Chrome client after I enable 'proxy.config.ssl.max_record_size'  with a -1 setting.

**Comment by oknet** [comment]
@zwoop Is the last comment for PR #2709 ?

**Comment by masaori335** [comment]
I could reproduce exactly same trace of #2707 ( https://paste.apache.org/ziVE ). And I confirmed this changes fix it.

**Comment by masaori335** [comment]
@scw00 `chain_abort_all` is called in many places of HttpSM. Are you sure these 2 are the only places need to set nullptr ?
```
proxy/http/HttpSM.cc:3721:12: tunnel.chain_abort_all(c->producer);
proxy/http/HttpSM.cc:3410:12: tunnel.chain_abort_all(p);
proxy/http/HttpSM.cc:3389:14: tunnel.chain_abort_all(p);
proxy/http/HttpSM.cc:3344:14: tunnel.chain_abort_all(c->producer);
proxy/http/HttpSM.cc:3298:14: tunnel.chain_abort_all(p);
proxy/http/HttpSM.cc:3261:12: tunnel.chain_abort_all(p);
proxy/http/HttpSM.cc:3157:18: tunnel.chain_abort_all(p);
proxy/http/HttpSM.cc:3148:14: tunnel.chain_abort_all(c->producer);
proxy/http/HttpSM.cc:2893:14: tunnel.chain_abort_all(p);
```

**Comment by scw00** [comment]
Actually, we need to check every `abort` in tunnel which fall into `setup_internal_transfer`. It only happens before we send the header to client.

So when we close the server session,  we need to clean `HttpSM::server_session` to nullptr. Otherwise, we will get the `BAD ACCESS`.

**Comment by scw00** [comment]
The tunnel will hold the vc and close it directly ,  but the HttpSM is difficult to know whether vc is closed. It is unreasonable !  we need to fix it .

**Comment by masaori335** [comment]
It sounds like we need to work in another PR.
I'm pretty sure this covers #2707 case. Let's land this for workaround.

**Comment by zwoop** [comment]
Fwiw, I did test this on docs, and it still crashed, but only when using the Chrome client. I've landed this though, I'll test again on Docs momentarily.

**Comment by zwoop** [comment]
Cherry-picked to 7.1.2

**Pull request merged**
