### PR TITLE
TS-5021: Separate parent_is_proxy from other parent configuration options.

### PR DESCRIPTION
**Pull request by jrushford**
simple retry and unavailable_server retry are no-longer tied to parent_is_proxy.

@zwoop - please review.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1270/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1165/ for details.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/43/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1505/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1610/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/175/ for details.

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/25/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/12/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/11/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1707/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1602/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/138/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/270/

**Comment by jrushford** [comment]
@zwoop - forgot about this one but,  i rebased this and it's ready to go if you're +1.

**Comment by zwoop** [comment]
@jrushford Question: do we want this into 7.1.x ?

**Comment by jrushford** [comment]
7.2.0 is fine


Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Pull request merged**
