### PR TITLE
Add --with-mimalloc option to build

### PR DESCRIPTION
**Pull request by duke8253**
Add `--with-mimalloc` option, this will override the standard malloc/free and other related functions to use mimalloc's version.

### CODE REVIEW

**Review by bneradt — COMMENTED** [review]
Looks reasonable.

**Comment by bryancall** [comment]
[approve ci]

**Review by maskit — DISMISSED** [review]

**Comment by bneradt** [comment]
@serrislew volunteered to take a look at this.

**Review by vmamidi — APPROVED** [review]
Approving based on @serrislew review.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
