### PR TITLE
Content-type lost when sent after duplicate headers

### LINKED ISSUE #11784: Content-Type is lost after TCP_REFRESH_HIT/200 of cached response with duplicated headers from origin
Initially the backend replies with response like:

```
HTTP/1.1 200 OK
Date: Mon, 23 Sep 2024 14:22:14 GMT
X-Reveal-Duplicate: same
Cache-Control: max-age=30, stale-if-error=604800, stale-while-revalidate=15, public
Content-Length: 14475
Content-Type: application/javascript
Expires: Mon, 23 Sep 2024 14:22:44 GMT
Last-Modified: Mon, 23 Sep 2024 14:22:14 GMT
X-Reveal-Duplicate: other
```

For the `TCP_MISS/200` trafficserver query, the reply from traffic server has all expected headers:

```
HTTP/1.1 200 OK                                                                                                                                      
Date: Mon, 23 Sep 2024 14:22:14 GMT
X-Reveal-Duplicate: same
Cache-Control: max-age=30, stale-if-error=604800, stale-while-revalidate=15, public
Content-Length: 14475
Content-Type: application/javascript
Expires: Mon, 23 Sep 2024 14:22:44 GMT
Last-Modified: Mon, 23 Sep 2024 14:22:14 GMT
X-Reveal-Duplicate: other
Age: 0
```

All queries until max-age is reached are the same and correct.

After the max-age time passes trafficserver is doing `TCP_REFRESH_HIT/200` to the backend with If-Modified-Since, which replies:

```
HTTP/1.1 304 Not Modified
Date: Mon, 23 Sep 2024 14:25:16 GMT
X-Reveal-Duplicate: same
Cache-Control: max-age=30, stale-if-error=604800, stale-while-revalidate=15, public
Content-Type: application/javascript
Expires: Mon, 23 Sep 2024 14:25:46 GMT
Last-Modified: Mon, 23 Sep 2024 14:25:16 GMT
X-Reveal-Duplicate: other
```

But then the Trafficserver replies to the client with headers:

```
HTTP/1.1 200 OK
Date: Mon, 23 Sep 2024 14:25:16 GMT
Content-length: 14475
X-Reveal-Duplicate: same
Cache-Control: max-age=30, stale-if-error=604800, stale-while-revalidate=15, public
Expires: Mon, 23 Sep 2024 14:25:46 GMT
Last-Modified: Mon, 23 Sep 2024 14:25:16 GMT
X-Reveal-Duplicate: other
Age: 0
```

Please see, that it replies without `Content-Type` header, which can be seen also in the `squid.log`, as the line is logged like:

`1727101089.801 2 127.0.0.1 TCP_REFRESH_HIT/200 14933 GET http://example.com - DIRECT/127.0.0.1 -
`
When the duplicated header `X-Reveal-Duplicate` has the same value, it results with same problem not transmitting Content-Type.

When the backend replies instead with 200 response to the If-Modified-Since then the Content-Type header is correctly transmitted.

Seems like dropping the Content-Type header there is a bug.

Reproduced on trafficserver 9.2.5, configure options:

```
  --with-openssl=provided-openssl
  --with-pcre=provided-pcre
  --with-ncurses=provided-ncurses
  --with-tcl=provided-tcl
  --with-luajit=provided-luajit
  --with-lzma=provided-xzutils
  --with-zlib=provided-zlib
  --disable-curl
  --disable-hwloc
  --enable-experimental-plugins
  --disable-posix-cap
```

### PR DESCRIPTION
**Pull request by jasmine-nahrain**
Prior to issue #9527, content-type header was being deleted and readded in `merge_response_header_with_cached_header` despite line [5005](https://github.com/apache/trafficserver/blob/master/src/proxy/http/HttpTransact.cc#L5005) specificaly stating that it should not be overwritten.

Once the issue was fixed, if duplicate headers were found and content-type was being sent after one of the duplicate headers, it would be deleted in the for loop at line [5038](https://github.com/apache/trafficserver/blob/master/src/proxy/http/HttpTransact.cc#L5038).
E.g.
```
HTTP/1.1 200 OK
x-reveal-duplicate: same
content-type: text/plain
x-reveal-duplicate: same
```

once the duplicate header is found, all headers subsequent to the dup are deleted. The intended course of this code is to then have those headers readded in the greater for loop. This works fine for most cases but because content-type is specified to not follow this behaviour, it is getting deleted but never readded.

This adds a secondary check for content-type to not be altered.

This fixes #11784

### CODE REVIEW

**Comment by jasmine-nahrain** [comment]
[approve ci Format]

**Comment by jasmine-nahrain** [comment]
[approve ci format]

**Comment by jasmine-nahrain** [comment]
[approve ci rat]

**Comment by jasmine-nahrain** [comment]
[approve ci autest]

**Comment by jasmine-nahrain** [comment]
[approve ci format]

**Comment by jasmine-nahrain** [comment]
[approve ci rat]

**Comment by jasmine-nahrain** [comment]
[approve ci centos]

**Review by bryancall — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
