### PR TITLE
Add support for webdav methods in ip_allow

### PR DESCRIPTION
**Pull request by meeramn**
Add support for webdav methods in ip_allow - COPY, MOVE, LOCK, UNLOCK, PROPFIND, PROPPATCH, MKCOL, REPORT, CHECKOUT

### CODE REVIEW

**Comment by ushachar** [comment]
I'm not too sure about this -- It's one thing to allow/block unknown methods that parse properly (TS-1232/TS-1407), but adding non-HTTP methods to the HTTP method list just for the ip-allow functionlity seems like another thing that can be best accomplished in plugin space....

Some technical comments:
1) Maybe rename HTTP_WKSIDX_... -> WEBDAV_WKSIDX_...
2) Some WebDAV methods should be treated like POST in that they are required to have payload (I don't think there's any method that's explicitly forbidden from having payload).
3) Should we support the "If" header? (http://www.webdav.org/specs/rfc4918.html#rfc.section.10.4.5)

**Comment by meeramn** [comment]
ushachar: I made changes to support webdav methods in ip_allow.config. I haven't implemented these methods - it just look for list of list of methods to allow or deny. Hence I'm not sure about supporting "If" header.

src_ip=::1 action=ip_allow method=<Webdav methods>

Can you please give me more information about doing this in plugin space?

I can rename it to WEBDAV as suggested.

**Comment by sudheerv** [comment]
@meeramn : I agree with the comments that this change seems like something that can (and should?) be done in a plugin rather than in the core. It should be fairly simple to write a plugin that reads a config file with the methods that need to be filtered and be used for any method (including webdav). We have a similar internal plugin that overrides ip_allow (we basically allow everything from ip_allow and control them from the plugin) for restricting methods based on ip type (internal, external etc).

**Comment by bgaff** [comment]
I'm in agreement with @ushachar and @sudheerv  on this one, I do not believe webdav methods should land in the core.

**Comment by jpeach** [comment]
I don't really see why ```ip_filter``` should not be able to deal with webdav methods. It seems reasonable to me that you should be able to filter any layered methods.

**Comment by zwoop** [comment]
That seems draconian to rule out these methods only because they are not in the main HTTP RFCs. Since ATS is a general forward (and transparent) proxy, it seems reasonable to me to support not just HTTP, but any HTTP extension. We do that for other things, like ICP.

**Comment by zwoop** [comment]
I should say, if there was a reasonable way to add functionality to ip_allow.config via plugins, that would make a lot of sense. But, I don't think there is.

**Comment by ushachar** [comment]
I'm not advocating rejecting all non-standard methods out of hand -- I'm just saying they don't belong in our recognized method list.
As a general approach, I'd do this sort of thing in plugin space - but if needed it can already be done in IPAllow via isNonstandardMethodAllowed (which can be configured using raw strings) - somewhat slower, but much more generic.

**Comment by SolidWallOfCode** [comment]
I'm going to side with Uri on this one as well. Adding those to the core HTTP method list seems wrong to me. As I understand, the real goal here is just for IPAllow to handle those methods. I like Uri's suggestion that we add a WEBDAV set of header tokens, e.g. `HDRTOKEN_TYPE_WEBDAV` and `HTTP_WEBDAV_XXX`. I don't see it as a big deal to have the strings in the header token heap per se.

**Comment by zwoop** [comment]
@ushachar Ah, so the argument is to not add special handling for this, but still allow them to be used in ip_allow.config? If so, that seems fine.

**Comment by ushachar** [comment]
@zwoop  - Yes, it should already be possible to do this using the existing code.

**Comment by bryancall** [comment]
I am for putting these methods into ipallow.config.  You are able to expand on the set of common methods as defined in section 9 of RFC2616.  Also, we already support methods that are not listed in RFC2616 (DELETE, PURGE, and PUSH).

**Comment by bryancall** [comment]
Looking at isNonstandardMethodAllowed I am OK with just using that.  However it should be modified without using std::string.  Also, there should be documentation added, bot the docs and ip_allow.config file.

**Comment by zwoop** [comment]
Ok, I think the consensus is that we don't change anything. Sorry Meera, but thanks for all the work. And I whole heartedly agree that we should eliminate the std:: ugliness from this code.

**Pull request closed without merging**
