### PR TITLE
TS-4598 : Coverity Null-Check after deref in NetworkUtilsRemote.cc

### PR DESCRIPTION
**Pull request by strotyl**
This is fixing Coverity issue CID 1237320.

### CODE REVIEW

**Comment by jpeach** [comment]
s/NetworkUtilisRemote/NetworkUtilsRemote/ ;)

**Comment by zwoop** [comment]
Yeah, this seems right, TSEventDestroy() checks its argument, and we use it like this in several other places (which is likely why coverity gets confused). Consistency is good!

**Comment by zwoop** [comment]
It seems there are merge conflicts here though, Tyler, can you please rebase your tree (which probably means pushing up the main master into your fork first) ?

**Comment by strotyl** [comment]
Will do.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/399/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/295/ for details.

**Pull request merged**
