### PR TITLE
Syntax Error fixed in URI sig Plugin

### PR DESCRIPTION
**Pull request by dsouza93**

### CODE REVIEW

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by zwoop** [comment]
Should this go into 9.0.x ? marking it as such, but please confirm.

**Comment by ezelkow1** [comment]
> Should this go into 9.0.x ? marking it as such, but please confirm.

This depends on the commit right before it, was a build issue that we didnt see since uri_signing doesnt usually get built.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
This has merge conflicts, and we'll need a new 8.1.x PR. Also, feel free to recommend / suggest other PRs that this depends on, such that it makes the back porting easier.

**Pull request merged**
