### PR TITLE
Fix for Ubuntu 16 and Clang 5

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by bryancall** [comment]
This change is only needed on master in 9.0.x.  This is the change that broke Ubuntu 16 and Clang 5 (2c7c15d02).

**Comment by hongthong2** [comment]
good

**Comment by brbzull0** [comment]
@bryancall which  Standard C++ Library version did you use to have this issue? Default one wont even build TS.

**Pull request merged**
