### PR TITLE
TS-4595: TSRuntimeDirGet

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by zwoop** [comment]
Cool. Can you add a documentation to this too? Either just add a new file, e.g.

    doc/developer-guide/api/functions/TSRuntimeDirGet.en.rst

Or, my personal preference, merge all TS*DirGet() functions into one file, and document all those related functions in that one file. See for example doc/developer-guide/api/functions/TSUuidCreate.en.rst, and how we put all related functions in that one file.

**Comment by zwoop** [comment]
Also, please add some tests to proxy/InkAPITest.cc, see how the existing tests are done for e.g. TSInstallDirGet.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/332/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/438/ for details.

**Comment by yatsukhnenko** [comment]
I added tests and created empty doc file(writing documentation is not a good idia considering my English level :shame:)

**Comment by jpeach** [comment]
The documentation for this API family is in {{doc/developer-guide/api/functions/TSInstallDirGet.en.rst}}, Just mention the new API there.

**Comment by jpeach** [comment]
This follows the pattern of the other APIs, but I notice the initialization is not thread safe. Shall we file a separate JIRA for that?

**Comment by zwoop** [comment]
Unless @yatsukhnenko also wants to fix the thread safety issue on this, and all APIs? If not, file another Jira IMO.

**Comment by yatsukhnenko** [comment]
I'll try to fix it a bit letter if it's not urgent

**Comment by zwoop** [comment]
Sounds good, can you file a new Jira for these issues?

**Comment by yatsukhnenko** [comment]
[TS-4680](https://issues.apache.org/jira/browse/TS-4680)

**Comment by zwoop** [comment]
@yatsukhnenko  As James suggested, can you just add a line or two to doc/developer-guide/api/functions/TSInstallDirGet.en.rst instead of creating a new file? This would be my preference as well.

**Comment by yatsukhnenko** [comment]
@zwoop, I chaneged `Synopsis` and `Description` sections

**Comment by zwoop** [comment]
Great, thanks! [approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/454/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/350/ for details.

**Pull request merged**
