### PR TITLE
Added tests for different thread configurations

### PR DESCRIPTION
**Pull request by duke8253**
needs #2441 to fix event thread names

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci].

**Comment by bryancall** [comment]
How do you plan for this to work on systems like MacOS that don't have gdb installed?  I haven't been able to get gdb to work well on MacOS when I have tried to install and use it.

**Comment by duke8253** [comment]
For mac I guess I'll use lldb, haven't really thought about how to implement this in windows yet.

**Comment by bryancall** [comment]
@duke8253 We don't support Windows, so you don't have to worry about it.

**Comment by zwoop** [comment]
Rather than using the gdb / lldb (and other complexities), can't we use whatever tools are available on the various platforms? E.g. on linux, this produces the proper thread names:

```
$ ps -eL -q $(pidof traffic_server)
```

**Comment by duke8253** [comment]
@zwoop that looks pretty neat, I used gdb because I'm also making some other changes and was using gdb at the moment. I'll make the changes today.

**Comment by duke8253** [comment]
@bryancall cool. :-)

**Comment by zwoop** [comment]
Note that that command is linux specific, other platforms likely has other ways to do something similar.  :-) We currently only support Linux (CentOS6 and later), FreeBSD (10 and up) and macOS. No  need to support anything else at this time.

**Comment by duke8253** [comment]
Yeah, I'll check the command on macOS, will need to find a FreeBSD system to see what they have. Thanks!

**Comment by zwoop** [comment]
Spoke with @jpeach , and we both agree that the hack around lldb is rather ugly. I think we both would prefer that you restrict this test to platform(s) where you can use something simple like "ps -eL". @jpeach suggested you can use a construct like

```
Test.SkipUnless(Condition.IsPlatform(‘linux’))
```

**Comment by duke8253** [comment]
I talked with @SolidWallOfCode and @dragon512, they suggested to add a debug tag to the code. This seems like the cleanest way to do this test with minimal modifications to the core code, and cross platforms support is a lot easier.

**Comment by dragon512** [comment]
[approve ci]

**Comment by duke8253** [comment]
I believe the previous failed test was related to this #2540, I've seen similar output when testing something else.

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Pull request merged**
