### PR TITLE
Fix HttpTunnel flow_control to work with http2

### PR DESCRIPTION
**Pull request by shinrich**
Changes I made a while back to enable the HttpTunnel flow control to work with Http/2 and from cache.

Had to fix the cache to not serve if the vio was disabled.

Also added a backlog virtual method to compute the total amount of buffer used by the Http2 client.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
Closing this out . I think this was resolved in a different way.

**Pull request closed without merging**
