### PR TITLE
Propagate proxy.config.net.sock_option_flag_in to accepted connections

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by randall** [comment]
[approve ci centos]
[approve ci fedora]

**Comment by randall** [comment]
[approve ci debian]
[approve ci ubuntu]
[approve ci autest]

**Review by shinrich — APPROVED** [review]

**Comment by bryancall** [comment]
[approve ci]

**Comment by randall** [comment]
This breaks the regression tests. It comes down to SO_LINGER being set/propagated during the tests.

I think, without this change, setting DSCP will be broken due to e65cf23015fd743cd790d9f7868a3731d62fc2a8 (which requires PACKET_TOS to be configured in `proxy.config.net.sock_option_flag_in`)

**Comment by randall** [comment]
This was superseded by #8463

**Pull request closed without merging**
