### PR TITLE
disable address sanitizer for our own CompileParseRules binary

### PR DESCRIPTION
**Pull request by dmorilha**

### CODE REVIEW

**Comment by duke8253** [comment]
Why do we need this exactly?

**Comment by duke8253** [comment]
[approve ci]

**Comment by dmorilha** [comment]
build does not work if running inside docker

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
[ci whitelist dmorilha]

**Comment by SolidWallOfCode** [comment]
[whitelist add dmorilha]

**Comment by zwoop** [comment]
Remember to mark the Milestone when merging.

**Comment by bryancall** [comment]
Cherry picked to 8.1.0

**Comment by dmorilha** [comment]
thanks

**Pull request merged**
