### PR TITLE
TS-4152: Build failure when curses is not available

### PR DESCRIPTION
**Pull request by dragon512**

### CODE REVIEW

**Comment by jpeach** [comment]
The commit subject should be formatted like the title of this PR.

I notice that we don't have the latest version of ``ax_with_curses.m4``. Is this bug fixed in the lated version?

**Comment by dragon512** [comment]
I am not sure. I understand from what I found online that there are breaking changes in the latest version. They seem to be wanting to remove this long  in favor of a different macro.

**Comment by jpeach** [comment]
Do you mind testing the [latest](https://www.gnu.org/software/autoconf-archive/ax_with_curses.html#ax_with_curses)?

**Comment by dragon512** [comment]
so I tried the latest and I get an error of

autoreconf -if
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build/_aux'.
libtoolize: copying file `build/_aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build'.
libtoolize: copying file `build/libtool.m4'
libtoolize: copying file `build/ltoptions.m4'
libtoolize: copying file `build/ltsugar.m4'
libtoolize: copying file `build/ltversion.m4'
libtoolize: copying file `build/lt~obsolete.m4'
configure:21883: error: possibly undefined macro: PKG_CHECK_EXISTS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by jpeach** [comment]
The ``PKG_CHECK_EXISTS`` probably means you don't have ``pkg-config`` installed correctly (ie. ``pkgconfig.m4`` isn't there.

**Comment by dragon512** [comment]
Maybe... but this is about fixing the issue at hand. Keep in mind this is RHEL 6 and CentOS 6. They are old out of date systems in the first place.

**Comment by jpeach** [comment]
@dragon512 We should prefer to take the latest m4 if that fixes the problem. I'd much rather not carry around this patch is we can avoid it.

**Comment by SolidWallOfCode** [comment]
I'm going to commit this. I spoke with @dragon512 and ultimately this is just a patch to deal with old yet supported operating systems (RHEL 6 and CentOS 6) which are not going to be updated to the newer version of the curses autotools macro. It's a simple change that shouldn't impact other platforms.

**Comment by jpeach** [comment]
@SolidWallOfCode We bundle the macro, it doesn't come from the OS.

**Comment by dragon512** [comment]
@jpeach I understand the "lets get the latest m4 script". I would normally be on board with this myself. However I think that is more complex. The issue here is that the new script needs other scripts.

also not this work https://github.com/peti/autoconf-archive/commit/6dc6cc55a1f3248c8bc39b0abcd5aeb4a3e34a06

Which says to me that we are going to have more issues trying to update this script vs just taking the hack. I agree I don't like this myself. But the tests seems to be a safe and does not break our logic. That is more important I think at the moment so we can get a 7.0 drop out. You are better at autoconf, so if you can setup a centos/rhel6 setup with dts3 easily, I am sure you could make a better solution once you see some of the headache I found.

**Comment by jpeach** [comment]
Looks like you need ``ax_require_defined.m4`` as well. I sent you a commit to try. If that doesn't work then let's just go ahead and commit this PR.

**Comment by dragon512** [comment]
Jpeach

I tested your branch https://github.com/jpeach/trafficserver/commit/b7ddaae3444e5cf1316b551b4dbde018e1ff29a9

It did work for me on rhel6.

**Comment by dragon512** [comment]
closing my pull request as James has a better fix

**Pull request closed without merging**
