### PR TITLE
Add diagram for header_rewrite Hooks

### PR DESCRIPTION
**Pull request by mlibbey**
The header_rewrite hooks are confusing. Perhaps a diagram will help people grok them?
webgraphviz

### CODE REVIEW

**Comment by zwoop** [comment]
Very nice! One suggestion (but not sure how it would look), how about splitting the box such that the pre-remap hook is clearly in front of the read-request / pseudo hook ? But because of the string lengths, it probably would make the graph too wide ?

**Comment by mlibbey** [comment]
do you mean just switching the order of those hooks in the diagram? Or putting the remap one into its own box?
webgraphviz-2
I'm kind of hacking graphviz to get it to do sequence diagrams...

**Comment by SolidWallOfCode** [comment]
I'm not sure why a diagram like the current ones wouldn't be better.  If you want more clarity, you could have the arrows start from "Client" and go through the hook nodes to "Server", then have a separate chane back.

**Comment by mlibbey** [comment]
Latest version:
webgraphviz-5

**Comment by zwoop** [comment]
Yeh, I like this, makes it clear that pre-remap is a special hook, and that pseudo hook and read-request header hook are basically the same (but different, depending on if it's a remap rule or a global rule).

**Comment by zwoop** [comment]
[approve ci docs]

**Comment by zwoop** [comment]
@mlibbey  Purely educational, but I made a Jenkins build job for docs that can be manually triggered (see above). I did it this way such that we don't necessarily break PR builds just because of docs (as per amc's wishes if I recall).

**Comment by mlibbey** [comment]
cherry-picked to 7.1.x

**Pull request merged**
