### PR TITLE
issue-1323: fix RecDataset

### PR DESCRIPTION
**Pull request by persiaAziz**
set nullptr if a config specified to be NULL in records.config

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1329/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1223/ for details.

**Comment by zwoop** [comment]
Albeit reasonable, I don't think we should land this. There's a number of places from ced4da13279f834c381925f2ecd1649bfb459e8b which changes "NULL" to "nullptr" accidentally, and we should investigate each of those, and revert where appropriate.

**Comment by persiaAziz** [comment]
yah no need to merge this since the actual problem is somewhere else. I just didn't want to master to be unstable, that is why I made this

**Pull request closed without merging**
