### PR TITLE
fixing memory leak when ATS serves stale records

### PR DESCRIPTION
**Pull request by zizhong**
freeing allocated memory before assign it to a new raw ptr value.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
Needs clang-format it seems. Do we want this into 7.1.1 ? 7.1.2 ?

**Comment by zizhong** [comment]
clang-format issue is fixed. Yes, it is good to have this in 7.1.x.

**Comment by maskit** [comment]
[approve ci]

**Pull request merged**
