### PR TITLE
Do not reschedule the periodic inactive_event and cancel it after signal timeout event to SM

### PR DESCRIPTION
**Pull request by oknet**
this resolve issue 1333

### CODE REVIEW

**Comment by oknet** [comment]
The inactive_event is a periodic event that is create by eventProcessor.schedule_every().
We should not reschedule it by schedule_in().

We cancelled it by call_event->cancel() even it is rescheduled by schedule_in() in process_timeout().

It cause a crash on process_close() due to we cancel a event but not set the inactive_event to NULL.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1345/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1238/ for details.

**Comment by oknet** [comment]
Link it to https://issues.apache.org/jira/browse/TS-3235

**Comment by zwoop** [comment]
Merged this to the 7.1.x branch as well.

**Pull request merged**
