### PR TITLE
Demote SSL log line to debug and remove key printing

### PR DESCRIPTION
**Pull request by randall**
Fixes issue #10040

### CODE REVIEW

**Comment by randall** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]
Looks fine to me. @serrislew was going to review this as well since she has worked with this code in the past.

**Comment by serrislew** [comment]
I thought I added this line but it wasn't me. LGTM

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
