### PR TITLE
Autest for ATS test support all configuration layout

### PR DESCRIPTION
**Pull request by chitianhao**
Fixed the extension file for autest of ATS. Changed variables and directories in trafficserver.test.ext and copy_config.test.ext. Support all kinds of config.layout during build to guarantee the test run in the sandbox without side effects.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Comment by chitianhao** [comment]
should be good now @dragon512

**Comment by dragon512** [comment]
[approve ci]

**Comment by persiaAziz** [comment]
[approve ci]

**Comment by persiaAziz** [comment]
squash please @chitianhao

**Comment by persiaAziz** [comment]
[approve ci autest]

**Comment by persiaAziz** [comment]
[approve ci]

**Comment by persiaAziz** [comment]
[approve ci autest]

**Pull request merged**
