### PR TITLE
Misc hostdb cleanups

### PR DESCRIPTION
**Pull request by jacksontj**
While looking into hostdb serialization out to disk, I found a couple things: (1) rr is a very confusing name, and its overloaded-- so a patch for that. (2) hostdb.sync_frequency isn't documented at all-- and its a fairly important configuration option.

### CODE REVIEW

**Comment by jacksontj** [comment]
ping: @bgaff and @SolidWallOfCode since I think you two are probably best for vetting this hostdb stuff.

**Comment by zwoop** [comment]
Love the docs, good idea :). About rr: why not just use the is_rr() function consistently, it was added a while ago.

Also, we're having some pretty serious issues around round-robin (we think), which is a definite regression since 5.3.x.  We have a very hacky solution right now, but overall, a lot of this HostDB stuff either has to be cleaned up / fixed, or ripped out. As such, how important is the persistent cache storage to your use case? Seeing that you updated the docs for it, I'm guessing it's important? In my setup, we basically clear the HostDB on startup every time, since the on-disk storage is pretty much useless to us.

**Comment by SolidWallOfCode** [comment]
+1 from me.

**Comment by jacksontj** [comment]
@zwoop hostdb persistance is important as a failback mechanism. We are in the progress of moving all of our load balancing to a dynamic dns service we wrote (and will be open sourcing soon-ish). Since we'll be relying on DNS responses so heavily, we have hostdb cache old responses and serve them stale for a time in the event that the DNS infrastructure has issues.

As for hostdb issues, we're on 5.2.x and AFAIK we aren't seeing any issues. Are the issues you are seeing reproducible?

**Comment by zwoop** [comment]
It's a regression between 5.x and 6.x, it crashes infrequently in production. The "fix" I put in indicates there is some issues going on with the round-robin changes that were made.

As for the persistence, we'll have to discuss this at the Summit, odds are that we'll agree to get rid of such persistence at some point. :)

**Comment by jacksontj** [comment]
I committed this morning, not sure why it didn't autoclose ;)

**Pull request closed without merging**
