### PR TITLE
Collapses the cmd/ build into one single build unit

### PR DESCRIPTION
**Pull request by zwoop**
This allows make -j to build all of these things much efficiently,
since it's seen as a single build unit. This is similar to how we
already build the plugins/ directory.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Would like to get some input on this from @SolidWallOfCode and @dragon512 . I think this is a better model going forward, with several benefits:

1. Improved parallelism
2. Yet, retains the modularity of one Makefile per "module"
3. Doesn't change much (i.e. we're keeping the baby)

**Comment by SolidWallOfCode** [comment]
One question is, if I'm working on Cache Tool (could happen...) and I have a terminal open in that directory, does "make" still build the Cache Tool for me? Or do I have to `(cd ..;make)` instead?

**Comment by zwoop** [comment]
Right, there is no makefile in the traffic_cache_tool, so you would need to be in st least the cmd/ directory when doing make. Same as with all plugins.

**Comment by SolidWallOfCode** [comment]
That's kind of annoying. I wonder you should put a non-generated `Makefile` in each directory that just does
```
all:
        cd ..
        make
```

**Comment by zwoop** [comment]
@SolidWallOfCode Yeh, I think you could do that, future exercise ?

**Comment by SolidWallOfCode** [comment]
Fine, as long as you don't ding that PR when I add it.

**Pull request merged**
