### PR TITLE
TS-4184 Makes -std=c++11 mandatory

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/422/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/525/ for details.

**Comment by jpeach** [comment]
👍 

We could also just pass the ``mandatory`` flag to the checking macro, which would produce better warning messages, but this is OK too. Consider adding a check for the minimum required gcc version.

**Comment by bryancall** [comment]
Looks good

**Pull request merged**
