### PR TITLE
TS-3984: CID 1328817: multiplexer patch to use std::auto_ptr

### PR DESCRIPTION
**Pull request by dmorilha**
@bcall @sc0ttbeardsley @zwoop a fix for multiplexer, I am not sure how coverity flags it... please let me know your thoughts...

### CODE REVIEW

**Comment by bryancall** [comment]
I got a bunch of errors applying this patch:
dispatch.cc:46:26: error: comparison between NULL and non-pointer ('std::auto_ptr<ats::io::IO>' and NULL) [-Werror,-Wnull-arithmetic]
  (__builtin_expect(!(io != __null), 0) ? __assert_rtn(__func__, "dispatch.cc", 46, "io != NULL") : (void)0);
                      ~~ ^  ~~~~~~
dispatch.cc:46:26: error: invalid operands to binary expression ('std::auto_ptr<ats::io::IO>' and 'long')
  (__builtin_expect(!(io != __null), 0) ? __assert_rtn(__func__, "dispatch.cc", 46, "io != NULL") : (void)0);
                      ~~ ^  ~~~~~~
dispatch.cc:221:38: error: comparison between NULL and non-pointer ('std::auto_ptr<ats::io::IO>' and NULL) [-Werror,-Wnull-arithmetic]
    (__builtin_expect(!(iterator->io != __null), 0) ? __assert_rtn(__func__, "dispatch.cc", 221, "iterator->io != NULL") : (void)0);
                        ~~~~~~~~~~~~ ^  ~~~~~~
dispatch.cc:221:38: error: invalid operands to binary expression ('std::auto_ptr<ats::io::IO>' and 'long')
    (__builtin_expect(!(iterator->io != __null), 0) ? __assert_rtn(__func__, "dispatch.cc", 221, "iterator->io != NULL") : (void)0);
                        ~~~~~~~~~~~~ ^  ~~~~~~
dispatch.cc:234:38: error: comparison between NULL and non-pointer ('std::auto_ptr<ats::io::IO>' and NULL) [-Werror,-Wnull-arithmetic]
    (__builtin_expect(!(iterator->io != __null), 0) ? __assert_rtn(__func__, "dispatch.cc", 234, "iterator->io != NULL") : (void)0);
                        ~~~~~~~~~~~~ ^  ~~~~~~
dispatch.cc:234:38: error: invalid operands to binary expression ('std::auto_ptr<ats::io::IO>' and 'long')
    (__builtin_expect(!(iterator->io != __null), 0) ? __assert_rtn(__func__, "dispatch.cc", 234, "iterator->io != NULL") : (void)0);
                        ~~~~~~~~~~~~ ^  ~~~~~~
In file included from dispatch.cc:26:
In file included from ./dispatch.h:27:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1673:31: error: no matching constructor for initialization of 'Request'
            ::new((void*)__p) _Up(std::__1::forward<_Args>(__args)...);
                              ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1600:18: note: in instantiation of function template specialization 'std::__1::allocator<Request>::construct<Request, Request>' requested here
            {__a.construct(__p, std::__1::forward<_Args>(__args)...);}
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1453:14: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<Request> >::__construct<Request, Request>' requested here
            {__construct(__has_construct<allocator_type, _Tp*, _Args...>(),
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:1609:25: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<Request> >::construct<Request, Request>' requested here
        __alloc_traits::construct(this->__alloc(),
                        ^
dispatch.cc:205:7: note: in instantiation of member function 'std::__1::vector<Request, std::__1::allocator<Request> >::push_back' requested here
    r.push_back(Request(host, buffer, location));
      ^
./dispatch.h:51:8: note: candidate constructor (the implicit copy constructor) not viable: expects an l-value for 1st argument
struct Request {
       ^
dispatch.cc:38:10: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
Request::Request(const std::string &h, const TSMBuffer b, const TSMLoc l)

**Comment by dmorilha** [comment]
In our internal version everything worked fine. I will check it tomorrow. Thanks for reporting.

**Comment by bryancall** [comment]
Compile with -Werror or look at the warnings.

**Comment by dmorilha** [comment]
I think I got it all fixed now.

**Pull request closed without merging**
