### PR TITLE
Kill unused .c file which contains code in a language invented by a Danish guy.

### PR DESCRIPTION
**Pull request by ywkaras**
If ATS committers were in charge of the Catholic Church probably that gospel where Jesus is married would never have been deleted from the Bible.

### CODE REVIEW

**Comment by shinrich** [comment]
The reference in the Makefile is commented out.  I guess you might as well just get rid of the commented out test_UNUSED_SOURCES.  Otherwise this looks good to me.

**Comment by PSUdaemon** [comment]
[approve ci centos]

**Comment by PSUdaemon** [comment]
[approve ci ubuntu]

**Comment by ywkaras** [comment]
OK the makefile is changed.

**Comment by ywkaras** [comment]
[approve ci ubuntu]

**Comment by shinrich** [comment]
Hey @bryancall can you remove your objections?  Looks like @ywkaras address your concerns.

**Pull request merged**
