### PR TITLE
Fix some minor issues with loading the self identifying data.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Some minor bugs in the `Machine` class when loading self information.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Review by jrushford — DISMISSED** [review]
looks good.

**Comment by SolidWallOfCode** [comment]
Still not quite right. Need one little tweak more.

**Review by bneradt — COMMENTED** [review]
Looks good.

**Comment by bneradt** [comment]
[approve ci autest]

**Review by jrushford — APPROVED** [review]
looks good all testing passes.

**Pull request merged**
