### PR TITLE
TS-4413: Fix potential consistent hash iterator race.

### PR DESCRIPTION
**Pull request by jrushford**
Fixes a potential consistent hash iterator race.

### CODE REVIEW

**Comment by zwoop** [comment]
@gtenev Can you take a quick look at this please?

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Started Linux (CentOS7) build.

**Comment by atsci** [comment]
Linux (CentOS7) build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-Linux/10/

**Pull request merged**
