### PR TITLE
Elevate access when reading client cert

### PR DESCRIPTION
**Pull request by duke8253**

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by mlibbey** [comment]
I think I'm -1 on this with the current blank commit message description -- for instance, what problems arise without this?

**Comment by shinrich** [comment]
Agreed.  @duke8253 you need to add some description in the commit.  And the autest failure is probably legitimate since it is so consistent.

**Comment by duke8253** [comment]
The autest failures are caused by old gold files, waiting for #5276 to fix them, I'll update description later.

**Comment by shinrich** [comment]
Oh, I didn't catch the first time around that this was an 8.1.x backport.

**Pull request closed without merging**
