### PR TITLE
Fix a NXDOMAIN related issue

### PR DESCRIPTION
**Pull request by duke8253**
The action cancelled check was causing issues because it relies on `lock` to be held. But since we have two try locks but not checking individually, this cannot be guaranteed. This was found when we had a bad remap rule.

### CODE REVIEW

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by zizhong** [comment]
@duke8253 Could you elaborate more about the issue this PR addresses in the commit message and also under this PR?
A few lines of explanation will help us understand the issue and the change better, hence coming along with better maintainability of ATS.

**Comment by SolidWallOfCode** [comment]
@duke8253, don't make me come over there and beat you. The commit can be traced back to this PR which makes a good place to put more detail than can fit in a commit message.

**Comment by SolidWallOfCode** [comment]
Some additional comments in the code would not be amiss, either.

**Comment by bryancall** [comment]
Cherry picked to 8.1.0

**Pull request merged**
