### PR TITLE
Remove unused HttpUpdate mechanism

### PR DESCRIPTION
**Pull request by shinrich**
It appears that the HttpUpdateSM is only called from the HttpUpdateTester.  And the HttpUpdateTester is only invoked when traffic_server is started with the http_update_test action tag.  In addition, the test only does things if there is a file called "urls" in the current directory of the traffic_server process.

I assume this is an old testing infrastructure that is no longer used.  autest should be used to exercise requests against traffic server.

### CODE REVIEW

**Review by bryancall — APPROVED** [review]

**Comment by ywkaras** [comment]
As you KWF this kruft, it looks like the controlled burn should also include the HttpSM members kill_this_async_done and kill_this_sync_hook.  ( https://github.com/apache/trafficserver/blob/39c7be57e453fe92b20f769d7b9a70f1d21d2ece/proxy/http/HttpSM.h#L594 )  They've been scaring me for years, make it stop!

**Comment by shinrich** [comment]
Yeah, kill_this is a two phase thing that I don't fully understand.

**Comment by ywkaras** [comment]
It looks potentially risky to remove kill_this_async_done.  But kill_this_async_hook is ONLY overridden by HttpUpdateSM.  When HttpUpdateSM is removed, it just obfuscates to keep kill_this_async_hook.  The last think the state machine needs is more obfuscation.

**Review by ywkaras — APPROVED** [review]

**Comment by ywkaras** [comment]
If you prefer go ahead and merge this as is and I'll create a 2nd PR that whacks out the kill_this_async_hook().

**Comment by shinrich** [comment]
Yes.  Better to file distinct clean ups separately.

**Pull request merged**
