### PR TITLE
Removes all WCCP code and utilities, updates docs

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by JosiahWI** [comment]
Resolves #9847.

**Review by JosiahWI — CHANGES_REQUESTED** [review]
There seem to be some fixes to the autest.sh script that are not directly related to the WCCP removal. Can we do these separately?

**Review by JosiahWI — COMMENTED** [review]
What was the change to `jobs.yaml`? The whole file was reformatted and has a large diff.

**Comment by zwoop** [comment]
> There seem to be some fixes to the autest.sh script that are not directly related to the WCCP removal. Can we do these separately?

It "fixes" the b0rken indentation :).

**Comment by zwoop** [comment]
> What was the change to `jobs.yaml`? The whole file was reformatted and has a large diff.

Because we don't have a standard YAML format :). I fixed it.

**Review by randall — APPROVED** [review]

**Review by JosiahWI — APPROVED** [review]
Looks good. I could not find anything that was missed. I checked whether there were any other configuration definitions that we could remove, but I did not find any.

**Pull request merged**
