### PR TITLE
proxy.config.http.drop_chunked_trailers (9.2.x)

### PR DESCRIPTION
**Pull request by bneradt**
This adds the proxy.config.http.drop_chunked_trailers configuration that allows dropping of chunked trailers.

This is a 9.2.x backport of #11603.

### CODE REVIEW

**Review by zwoop — APPROVED** [review]

**Comment by bryancall** [comment]
[approve ci ubuntu]

**Comment by bryancall** [comment]
[approve ci rocky]

**Comment by bryancall** [comment]
[approve ci fedora]

**Comment by bryancall** [comment]
[approve ci debian]

**Comment by bryancall** [comment]
[approve ci centos]

**Comment by bryancall** [comment]
[approve ci centos]

**Review by maskit — APPROVED** [review]

**Pull request merged**
