### PR TITLE
Create a tool to list files changed since a tag

### PR DESCRIPTION
**Pull request by danobi**
As requested by @dragon512

The default (no args) is to ouput all files changed since the
most recent tag (lexicographically speaking) to stdout.

Run it with -h or --help to see a full description.

### CODE REVIEW

**Comment by danobi** [comment]
I'm less convinced this works than when I opened the PR. Testing some more.

**Comment by zwoop** [comment]
Can we put this into tools/reports ? There's one other similar tool in there.

**Comment by dragon512** [comment]
Hey Dan, 
Sorry i had to take off for personal issue at home. I wanted a script that would:
1) get changes since last tag or a certain format
2) filter out messages 
3) possible reformat of certain strings ( such as jira or issues)
4) format the output to some template

for example we would want to have something like:

Version 7.0.2 (09/15/16, solidwallofcode, jkenny)
  * change one
  * change two

i.e. the reason for the template input as others might want to have a different format.

I was thinking python and jinga would be your friends here.

**Comment by jpeach** [comment]
Sounds like a git alias, or [git shortlog](https://git-scm.com/docs/git-shortlog).

**Comment by danobi** [comment]
Forget about this for now

**Pull request closed without merging**
