### PR TITLE
Replace ACTION_RESULT_NONE with nullptr

### PR DESCRIPTION
**Pull request by shinrich**
This closes issue #7127

I attached another stack trace on issue #7128 which was due to an action pointer being 1.  This also corresponds to the value ACTION_RESULT_NONE.  This value is only returned in 2 places.  There are many places that check for action pointer nullptr, but none that check against 1 or ACTION_RESULT_NONE.  Therefore, it seems better to just have those functions return nullptr if there is no relevant action.

While I was in there ACTION_RESULT_INLINE does not seem to be used anywhere, so this PR removes that too.

### CODE REVIEW

**Comment by randall** [comment]
[approve ci docs]

**Comment by shinrich** [comment]
Looking back through my backtraceio stack traces, I see this stack going back to November 2019 (with our ATS7 build).  Just not very often compared to other issues we were debugging.

Digging through a stack from today by looking at history, I can see the path which through a server connection retry ends up at a failed connect_re which would result in a returned action of 1.

**Comment by randall** [comment]
> This closes issue #7128
> 
> I attached another stack trace on issue #7128 which was due to an action pointer being 1. This also corresponds to the value ACTION_RESULT_NONE. This value is only returned in 2 places. There are many places that check for action pointer nullptr, but none that check against 1 or ACTION_RESULT_NONE. Therefore, it seems better to just have those functions return nullptr if there is no relevant action.
> 
> While I was in there ACTION_RESULT_INLINE does not seem to be used anywhere, so this PR removes that too.

Is this supposed to point to #7127 ?

**Comment by shinrich** [comment]
@randall I think you are correct.  Updated the issue #

**Review by masaori335 — APPROVED** [review]
Looks reasonable.

> There are many places that check for action pointer nullptr, but none that check against 1 or ACTION_RESULT_NONE.

Probably, `ACTION_RESULT_NONE` had some meanings in the past, but this is what we have now. 
- e.g. 
https://github.com/apache/trafficserver/blob/157be26c9872d55a0fde91da1986c69eb89cb5b8/proxy/http/HttpSM.cc#L5219-L5222
https://github.com/apache/trafficserver/blob/157be26c9872d55a0fde91da1986c69eb89cb5b8/proxy/http/HttpSM.cc#L6948-L6949

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
