### PR TITLE
Remove unused and never to be used classes from Map.h.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1190/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1083/ for details.

**Comment by zwoop** [comment]
@SolidWallOfCode You have to fix the unit tests too, in lib/ts/test_Map.cc.

**Comment by zwoop** [comment]
@SolidWallOfCode Did you make the fixes to the unit tests ?

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1361/ for details.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/45/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1507/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/freebsd-github/1612/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/177/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1516/ for details.

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/54/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1621/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/186/ for details.

**Comment by zwoop** [comment]
Time to land this yet?

**Pull request merged**
