### PR TITLE
CID 1508887 fix parent_select plugin stat Time of check.

### PR DESCRIPTION
**Pull request by traeak**
Fixes: #10209 

Refactor parent_select/consistenthash_config.cc loadConfigFile to use std::filesystem and std::string_view to remove coverity warn about stat() check independent of file open.

Plugin is defective and will be deprecated.

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Comment by traeak** [comment]
[approve ci]

**Comment by maskit** [comment]
[approve ci]

**Comment by traeak** [comment]
[approve ci]

**Comment by traeak** [comment]
[approve ci]

**Comment by traeak** [comment]
[approve ci]

**Comment by moonchen** [comment]
Plan is to merge this to fix the issue, then get rid of this plugin in the future.

**Review by moonchen — APPROVED** [review]

**Pull request merged**
