### PR TITLE
TS-4752 Changes CFLAGS from -std=gnu99 to -std=c11

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/666/ for details.

**Comment by zwoop** [comment]
It's a bummer, but seems devtoolset-3 on CentOS6 does not agree with -std=c11.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/770/ for details.

**Comment by PSUdaemon** [comment]
Aww, we could have switched to `threads.h`!

**Pull request closed without merging**
