### PR TITLE
TS-2237: Add unit tests for escapify_url and pure_escapify_url

### PR DESCRIPTION
**Pull request by maskit**
Unit tests for #866

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/600/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/496/ for details.

**Comment by maskit** [comment]
CI builds fail because the functions are not in the code yet.

**Comment by shinrich** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/619/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/723/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/744/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/640/ for details.

**Comment by maskit** [comment]
Rebased to obtain the functions from master.

**Comment by shinrich** [comment]
Looks good to me.

**Pull request merged**
