### PR TITLE
QUIC: Send close frame packet when we are in close period

### PR DESCRIPTION
**Pull request by scw00**

### CODE REVIEW

**Comment by scw00** [comment]
Try to fix #3159

**Comment by maskit** [comment]
Do we really able to ignore frames? Some retransmitted frames might arrive after switching to these states.

**Comment by scw00** [comment]
We should handle some frame like close frame to transition from the closing period to the draining period

**Comment by maskit** [comment]
So we need to call `_recv_and_ack` somewhere on these states, we don't send ack frame though.

**Comment by scw00** [comment]
updated !

**Comment by maskit** [comment]
Did you push??

**Comment by scw00** [comment]
Pushed !

**Comment by maskit** [comment]
We need to call `_recv_and_ack`. Otherwise frames won't be processed.

Also, closing state and draining state is basically the same except we can't send any packets on draining state.

> The draining state is entered once an endpoint receives a signal that
   its peer is closing or draining.  While otherwise identical to the
   closing state, an endpoint in the draining state MUST NOT send any
   packets.  Retaining packet protection keys is unnecessary once a
   connection is in the draining state.

**Comment by scw00** [comment]
updated !

**Pull request merged**
