### PR TITLE
Reuse TSMutex for ts_lua_http_intercept_handler

### PR DESCRIPTION
**Pull request by oknet**
Fix lua http intercept issue, more detail please refer to issue #8635

### CODE REVIEW

**Comment by oknet** [comment]
[approve ci]

**Comment by pbchou** [comment]
The assertion failure core dump no longer happens with this patch. Tested with ATS master, 9.1.x, and 9.1.1 (custom). Thanks.

**Review by shukitchan — APPROVED** [review]
I tested the code change. It worked fine.

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
