### PR TITLE
TS-4048: Broken Vagrantfile in a lot of ways

### PR DESCRIPTION
**Pull request by christoph-k86**
- removed some broken boxes
- added some boxes
- changed from puppet-provisioning to shell-provisioning

### CODE REVIEW

**Comment by jpeach** [comment]
This looks generally reasonable.

I'd like the patch series to be a bit cleaner; maybe fix the vagrant box URLs in the first commit, then switch over to the shell provisioner.

We need to retain the additional build packages (``libcap-devel``, etc) so that optional components are always detected and built. It looks like you dropped FreeBSD, was that deliberate?

**Comment by christoph-k86** [comment]
Yeah i know what you mean about that patch series... working on it

I just checked for configure to run in default configuration when looking for those dependencies trying to keep the images small. 

I can add those optional dependencies as well. Would be great if they were documented as optional though ([doclink] (https://docs.trafficserver.apache.org/en/stable/getting-started/index.en.html#installation)).

What do you think about dependencies for plugins? Shall they be added as well?

That FreeBSD image is gone and there wasn't any provisioning at all so that probably never worked ootb anyways. If that's still needed i'll try to add it as well but i'd prefer to do that after all the other stuff is working again.

**Comment by jpeach** [comment]
> Yeah i know what you mean about that patch series... working on it

thanks :)

> I just checked for configure to run in default configuration when looking for those dependencies
> trying to keep the images small.
> 
> I can add those optional dependencies as well. Would be great if they were documented as optional
> though (doclink).
>
> What do you think about dependencies for plugins? Shall they be added as well?

The original goal of these was so that dev could spin up build environments for configurations they didn't have easy access to, which meant that I installed all the dependencies to build all the optional components. If you can get all the dependencies in, that would be great. On RHEL-based systems I remember it was a bit tedious to get the right dependencies out of EPEL though. 

> That FreeBSD image is gone and there wasn't any provisioning at all so that probably never worked
> ootb anyways. If that's still needed i'll try to add it as well but i'd prefer to do that after all the other stuff
> is working again.

No that's fine; I just wanted to check whether this was a deliberate decision. A FreeBSD image will just bitrot again unless there's someone to take care of it.

**Comment by bryancall** [comment]
@jpeach will shepard.

**Comment by christoph-k86** [comment]
I just added those optional dependencies. 

Cleaning up that patch series is pretty hard though. Looks more like a complete rewrite than a couple of fixes. I'm still thinking about how to split all those changes without leaving it in an even worse state. Those commits work alltogether... applying only some of them does'nt really make any sense. Maybe just squash em?

**Comment by jpeach** [comment]
Thanks @christoph-k86!

**Pull request closed without merging**
