### PR TITLE
Normalize loopback usage in session_match autest

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by bneradt** [comment]
Looks good. 127.0.1 was a typo. Thanks for fixing it.

**Comment by zwoop** [comment]
@randall  Ok with adding this to 9.0.x? It's a test, so should be safe? :)

**Comment by randall** [comment]
If the parent commit (1d5089243f0dcdf0d9b39379dea47f3c14f383ab)  is in 9, then this is good to go in as well.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
