### PR TITLE
Adds logging around various config file loads

### PR DESCRIPTION
**Pull request by randall**
Also changes the messaging of over config file loads to be consistent

Addresses issue #1348

### CODE REVIEW

**Comment by randall** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
I'd prefer to have a bit more consistency in the messages, in particular lead with the configuration file name every time. E.g. "hosting.config loading ...", "hosting.config finished loading", "hosting.config failed to load", etc. This would make grepping or even just visual inspection easier.

**Comment by randall** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
I think you have a real AuTest problem, in that this is changing logging output expected by the tests. A quick glance seems to indicate that some sort of error message is being generated that wasn't before and this is confusing the result checks.

**Comment by randall** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
You may want to rebase your PR.  The last run hung up because two of the TLS tests didn't complete within 10 seconds.  I've removed the timeout limits.  Seems like the tls tests were the only ones doing them.  And that was committed to master a week or so back.

**Comment by randall** [comment]
I believe I've addressed the code issues that tests were complaining about. And the 2 tests that fail do seem to pass locally.

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
rebased and trying again.

**Comment by randall** [comment]
hurray! It works!

**Pull request merged**
