### PR TITLE
Fixes leak in SNIAction name globbing

### PR DESCRIPTION
**Pull request by randall**
pcre_compile allocated object is never pcre_free-ed

### CODE REVIEW

**Comment by randall** [comment]
This goes back to at least ATS 9.

This probably also effects whatever is using `NextHopItem` as it is derived from `namedElement`

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Pull request closed without merging**
