### PR TITLE
TS-4970: Crash in INKVConnInternal when handle_event is called after destroy()

### PR DESCRIPTION
**Pull request by jacksontj**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/899/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1007/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1009/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/901/ for details.

**Comment by jpeach** [comment]
Are we using github for backports? I thought the process was to mark the JIRA?

**Comment by jacksontj** [comment]
@jpeach TBH I'm not sure, I figured the PR would be good at least to get the CI to run on it-- I'm not sure what our official process is now that we do github for *some* things

**Comment by SolidWallOfCode** [comment]
Does the `destroy` method also clear `m_deletable`?

**Comment by shinrich** [comment]
Would it be easier to just back port the fix from TS-4590?  I'm a bit concerned about the proposed fix in this PR.  I don't think is correctly using the m_deleted/m_deletable parameters?

**Comment by jacksontj** [comment]
@shinrich we could-- this patch seems to be working fine for our build though-- seemed like a less intrusive patch to an LTS release.

**Comment by jacksontj** [comment]
@shinrich I did look a bit more into the other backport-- and it seems that the outcome would be quite similar-- as the `handle_event` method is still using this `m_deleted` flag to determine if the struct was deleted, so it ends up being a superset of this change.

**Comment by jacksontj** [comment]
After doing some more looking, the `m_deleted` flag is just marking the VConn as "we should delete this" and that combined with `m_deletable` lets it reschedule the delete in the future when it can. The fundamental problem I'm seeing is it is double freed under some conditions-- since all events trigger a delete. This is fixed in 7.x with  TS-4590 -- so I've updated this PR to workaround the issue in a simpler mechanism that more closely mirrors what is happening on 7.x

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1035/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/927/ for details.

**Comment by zwoop** [comment]
Is this a duplicate PR?

**Comment by shinrich** [comment]
Not a complete solution as Thomas noted, but may be sufficient to keep 6.2.x moving.  Alternatively, we may just want to back port TS-4590.

**Comment by jacksontj** [comment]
Closing the PR-- as we'll take care of this in Jira.

**Pull request closed without merging**
