### PR TITLE
Revert "spawn_thread with atomic operation"

### PR DESCRIPTION
**Pull request by bryancall**
This reverts commit 05cc3df86672cbb16f17e8909c8b471fac618d4a.

### CODE REVIEW

**Comment by bryancall** [comment]
Checking to see if autest passes by reverting this commit.

**Comment by oknet** [comment]
latent issues here ? or just autest script issue ?

**Comment by SolidWallOfCode** [comment]
Yes, it's quite mysterious why this would break AUTest.

**Comment by mingzym** [comment]
is the autest from scratch with no storage data etc? and is stats data cleared before the run?

- Yongming Zhao 赵永明

**Comment by SolidWallOfCode** [comment]
Hey, Emperor Ming! Yes, AUTest creates a sandbox directory for each run which should be created on the fly, so no history effects. My observations are that the proxy port isn't get set but why this change should affect that is unclear to me.

**Comment by bryancall** [comment]
It is unclear to me, but it seems like autest started having issues after this commit.  I decided to do a revert and test it in our CI system to see if it would resolve the issue.

Looks like CI passed.  I am going to rerun CI a few times and see if it passes each time.

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

One more time...

**Comment by bryancall** [comment]
[approve ci]

au test succeeded 2x and failed 1x - running again...

**Comment by bryancall** [comment]
[approve ci]

**Comment by oknet** [comment]
```
--- a/lib/records/RecRawStats.cc
+++ b/lib/records/RecRawStats.cc
@@ -47,7 +47,14 @@ raw_stat_get_total(RecRawStatBlock *rsb, int id, RecRawStat *total)
     total->count += tlp->count;
   }
 
-  for (i = 0; i < eventProcessor.n_dthreads; i++) {
+  // The DEDICATED EThread can be created during ATS running.
+  // In the eventProcessor.spawn_thread(), the n_dthreads is incremented first
+  // then create the EThread object and put it into the array all_dthreads[]
+  // Therefore, the all_dthreads[eventProcessor.n_dthreads] maybe nullptr.
+  int n = eventProcessor.n_dthreads;
+  if (eventProcessor.all_dthreads[n] == nullptr)
+    n--;
+  for (i = 0; i < n; i++) {
     tlp = ((RecRawStat *)((char *)(eventProcessor.all_dthreads[i]) + rsb->ethr_stat_offset)) + id;
     total->sum += tlp->sum;
     total->count += tlp->count;
```

**Comment by oknet** [comment]
PR #1989 is created to resolve this issue.

**Comment by bryancall** [comment]
Not needed anymore

**Pull request closed without merging**
