### PR TITLE
Adding STL Allocator which uses io bufs

### PR DESCRIPTION
**Pull request by bgaff**
This is something that seems to come up at every summit and I always promise to prototype it. Ahead of the next summit I'd like to begin discussions around the idea of actually making this happen. This pull request (while not yet referencing a TS ticket) adds an STL allocator which uses io bufs if possible falling back to std::allocator for large allocations. As an example I also modified the SPDY code to use this new allocator instead of the default allocator. So I'd love thoughts on this, should we go forward?

This approach might be the best balance between wanting to use standard library containers and not killing things with allocations.

cc. @jpeach @SolidWallOfCode @zwoop @jacksontj @PSUdaemon 

The result below is from just switching out the SPDY code and with only ONE request, needless-to-say a large number of allocations happen that can be deferred to an io buf.
```
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 30 at location 0x7fffd404bf80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 34 at location 0x7fffd404bf00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 16 at location 0x7fffd404be80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 32 at location 0x7fffd404be00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 28 at location 0x7fffd404bd80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 32 at location 0x7fffd404bd00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 16 at location 0x7fffd404be80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 30 at location 0x7fffd404be80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 26 at location 0x7fffd404bc80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 64 at location 0x7fffd404bc00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 32 at location 0x7fffd404bd00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 32 at location 0x7fffd404bd00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 30 at location 0x7fffd404bb80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 33 at location 0x7fffd404bb00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 33 at location 0x7fffd404ba80
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 128 at location 0x7fffd404ba00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 64 at location 0x7fffd404bc00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 31 at location 0x7fffd404bc00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 28 at location 0x7fffd404b980
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 40 at location 0x7fffd404b900
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 38 at location 0x7fffd404b880
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 57 at location 0x7fffd404b800
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 1 (block size 256), alloc size = 202 at location 0x7fffd4054f00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 35 at location 0x7fffd404b780
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 42 at location 0x7fffd404b700
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 1 (block size 256), alloc size = 256 at location 0x7fffd4054e00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 128 at location 0x7fffd404ba00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 48 at location 0x7fffd404ba00
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 35 at location 0x7fffd404b680
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 45 at location 0x7fffd404b600
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Allocating a block from iobuf index 0 (block size 128), alloc size = 43 at location 0x7fffd404b580
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 45 at location 0x7fffd404b600
[Mar  2 00:19:04.642] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 35 at location 0x7fffd404b680
[Mar  2 00:19:05.201] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 30 at location 0x7fffd404bf80
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 32 at location 0x7fffd404be00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 30 at location 0x7fffd404be80
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 32 at location 0x7fffd404bd00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 33 at location 0x7fffd404bb00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 28 at location 0x7fffd404b980
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 31 at location 0x7fffd404bc00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 38 at location 0x7fffd404b880
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 40 at location 0x7fffd404b900
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 1 (block size 256), alloc size = 202 at location 0x7fffd4054f00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 57 at location 0x7fffd404b800
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 42 at location 0x7fffd404b700
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 35 at location 0x7fffd404b780
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 1 (block size 256), alloc size = 256 at location 0x7fffd4054e00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 43 at location 0x7fffd404b580
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 34 at location 0x7fffd404bf00
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 26 at location 0x7fffd404bc80
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 30 at location 0x7fffd404bb80
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 28 at location 0x7fffd404bd80
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 33 at location 0x7fffd404ba80
[Mar  2 00:19:05.202] Server {0x7fffee0fc700} DIAG: (allocator) Deallocating a block to iobuf index 0 (block size 128), alloc size = 48 at location 0x7fffd404ba00
```

### CODE REVIEW

**Comment by zwoop** [comment]
Nice. Can you try it with the H2 code instead? SPDY is going away for 7.0, and is rather irrelevant, but it'd be super interesting to see what it does for H2, which in my benchmarks, is about 50% more CPU intensive than a plain HTTPS request.

**Comment by bryancall** [comment]
I agree with @zwoop, we have turned off spdy in prod and would rather see this in h2.

**Comment by jpeach** [comment]
There's a number of style issued here (use of ``TSDebug``) and I really think we can come up with better names than ``ts_stl_iobuf_allocator`` :)

The idea is sound, implementation looks straightforward. Nice work @bgaff! I think it would be interesting to micro-benchmark this approach against jemalloc?

**Comment by bgaff** [comment]
@zwoop @bcall no problem I'll update this with h2 as the example use case. @jpeach removing the TSDebug is no problem and I'm very open to naming suggestions...I really didn't put much thought into it.

**Comment by sudheerv** [comment]
Wait, I thought Spdy was the only odd case that wasn't using iobufs already (due to the history of starting it out as a plugin and merging with the core later). I'm probably missing something, but, last I looked there weren't any STL usages in the h2 code?

In any case, @bgaff - great work! As soon as you finialize the changes, we should think of making API available for these so plugins can benefit (which is where I think this will be heavily required and used).

**Comment by dragon512** [comment]
Looks good to me. However can we use namespaces? I mean ts_stl_iobuf_allocator!!

it would better in my view to have 

namespace ts{
template <...>
 class iobuf_allocator{
   }
}

vs having really_long_class_names_that_have_namespaces_built_into_them.

**Comment by bgaff** [comment]
@zwoop / @bryancall , @sudheerv was right there isn't much standard library usage in the h2 code. But i'll work on exposing similar logic for plugins.

**Comment by jpeach** [comment]
In general, I'd like to avoid namespaces, but I like the ``iobuf_allocator`` nomenclature; just need to make it consistent with existing iocore style using IOCamelCase.

**Comment by dragon512** [comment]
Why do you want to avoid namespaces? They are a good thing

**Comment by jpeach** [comment]
They can be a good thing. It's not namespaces so much as the difficulty of code browsing the names within them. If you end up with very generic names in different namespaces, you need to keep a lot of mental context to know which one is being used, and many code browsing tools won't help to disambiguate. In general, I have found they can (though not always) hinder readability and maintenance. For C++ library APIs, it's a different story.

**Comment by dragon512** [comment]
Sure, I think the point of the namespace it to define a concept or domain. This makes it easy to deal with class with the same name in different namespaces. For me this is not much different of why we make directories for the source. This is also a driving reason for why I would like to relay out the source code. It is currently to hard to keep the current structure and relationships in ones head. Thanks for sharing your concerns on the namespaces

**Comment by bgaff** [comment]
I'll open a new PR with feedback soon

**Pull request closed without merging**
