### PR TITLE
uri_signing plugin: Fix missing payload validation for the iss field.

### PR DESCRIPTION
**Pull request by brbzull0**
Should fix the crash for https://github.com/apache/trafficserver/issues/8874

Also adding some error messages that would eventually help for debugging.

### CODE REVIEW

**Comment by dsouza93** [comment]
I am taking a look at this today @brbzull0! Thanks a ton for posting this up.

It may take me just a little more time. I have a bunch of fixes for this plugin that are in our internal repos that I though I pushed to the open source repo here. I want to just go through them and ensure that this is not one of those and that I didn't miss anything else.

That being said, I'll definitely get around to testing this and approving by Wednesday next week!

Also thank you so much for adding that unit test as well! 🙏

**Review by dsouza93 — APPROVED** [review]
This looks good!

**Review by ezelkow1 — APPROVED** [review]
lgtm (and I trust Dylan's review :) )

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
