### PR TITLE
Fix reason tag of traffic_ctl host

### PR DESCRIPTION
**Pull request by chitianhao**
This should fix this issue: https://github.com/apache/trafficserver/issues/5256

### CODE REVIEW

**Comment by chitianhao** [comment]
Can you give it a test? @jrushford

**Comment by jrushford** [comment]
Okay,  I’ll test it tomorrow and let you know.

Thanks
John

**Comment by jrushford** [comment]
Thanks @chitianhao his fixed it, The PR is merged and I closed the issue.

**Comment by zwoop** [comment]
Remember to mark the PRs for the appropriate project. In this case, since we are backporting so much of this to the 8.x branch, this also needs to go to 8.x

**Comment by jrushford** [comment]
@zwoop, thanks for the reminder.

**Pull request merged**
