### PR TITLE
Don't include headers in proxy/http from iocore/cache

### PR DESCRIPTION
**Pull request by maskit**
#10711 removed the necessity of linking libhttp, but I found header files are still included and inline functions make some magic.

To not include the header files, this PR moves `calculate_document_age` from `HttpTransactHeaders` to `HttpTransactCache` which has other calculation functions.

There is actually one more place that includes a header file in proxy/http
```
$ git grep "#include" src/iocore/cache | grep "proxy/http"
src/iocore/cache/CacheRead.cc:#include "proxy/http/HttpCacheSM.h" //Added to get the scope of HttpCacheSM object.
```
And it's used here
https://github.com/apache/trafficserver/blob/48333c8bc13102b4d3b570bfb25e8d1109f373e9/src/iocore/cache/CacheRead.cc#L171-L172
I'll try to remove this on another PR to make this one simple. -> Made it #10721

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci rocky]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by maskit** [comment]
[approve ci rocky]

**Comment by maskit** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]
Pretty straightforward. Thanks for the cleanup.

**Pull request merged**
