### PR TITLE
HPack: Use StringView to avoid calling strlen().

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Related to #2179 - same change but using `StringView` to accommodate @zwoop 's suggestion of using a macro (blech!).

### CODE REVIEW

**Comment by bryancall** [comment]
It is not using a macro to initialize.  This is more complex and error prone than using const char* in a struct.

**Comment by jpeach** [comment]
@SolidWallOfCode Can you try to get `clang-format` to do a better job on `STATIC_TABLE`? Maybe add a trailing comma, or even just disable it for that block.

**Comment by SolidWallOfCode** [comment]
Reformatted the table and added a constructor to make it cleaner.

**Comment by maskit** [comment]
Does this improve runtime performance? It will create many StringView instances not only at startup but also runtime. Since we don't use substrings here and MIMEField has lengths, I don't see reasons to use StringView, it makes code (of MIMEField user side) a bit short though. It looks like syntax sugar with overhead to me.

**Comment by SolidWallOfCode** [comment]
It would be interesting to know if the performance is affected. I think it's a wash on that count because having looked at other assembler output, copying / constructing a `StringView` is identical to using the raw pointer and length. That is the reason I tend to pass them by value because
```
StringView x;
func(x);
```
is the same as
```
const char* x_ptr;
int length x_len;
func(x_ptr, x_len);
```

**Comment by bryancall** [comment]
-1 with this change.

I agree with @maskit, this is performance critical code and need to be benchmarked before accepting changes to it.   I see this code as being more complex than what it is now and less maintainable.

**Comment by maskit** [comment]
I ran iprofiler against test_HPACK.

const char*
image

StringView
image

**Comment by SolidWallOfCode** [comment]
I need to look at the performance data, there are some odd things in it. For instance, the calls to `ts::ConstBuffer` - that class isn't even used, it's unclear why there a lot of time spent on it.

**Pull request closed without merging**
