### PR TITLE
Via: revert change to protocol element of VIA string.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
The protocol stack changes to the VIA string are broken and can't really be fixed. Such support will have to be provided by a plugin. This reverts the VIA string changes from #1534. This replaces #1988.

### CODE REVIEW

**Comment by shukitchan** [comment]
When you said, "the changes to the VIA string are broken", do you mean the ipv6 and response via problem you mentioned in #1988 ?
I think we should fix those problems instead of reverting it back.

**Comment by SolidWallOfCode** [comment]
That was one aspect. #2024 fixes that. The more significant issues are

* Without format flexibility this change cannot actually be deployed in a real CDN. The CDN clients will never upgrade in synchronization. Therefore without the additional configuration support from #1998 it basically breaks ATS for CDN use.
* Everyone seemed to agree this should be done with a plugin, and not in the core. This PR removes it from the core so it can be done by a plugin.

**Comment by shukitchan** [comment]
I see your point. can you close this and reopen #1988 ?

**Comment by zwoop** [comment]
Well, fwiw, being the primary whiner on #1988, I'll leave it to amc and shukitchan to decide. I'm ok with #1988.

**Comment by SolidWallOfCode** [comment]
#1988 was chosen instead of this.

**Pull request closed without merging**
