### PR TITLE
TS-4725: Remove proxy.config.http.enable_url_expandomatic

### PR DESCRIPTION
**Pull request by reveller**
Removed all references to proxy.config.http.enable_url_expandomatic in code and documentation.

### CODE REVIEW

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/609/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/505/ for details.

**Comment by jpeach** [comment]
It looks like we can go futher and remove ``HttpTransact::try_to_expand_host_name``. Maybe an extra commit or follow-on Jira?

**Comment by zwoop** [comment]
Be careful when eliminating try_to_expand_host_name(), I recently discovered that this function also deals with DNS failures in parent selection. I'm +1 on removing (or renaming) this method, but it can't just be blindly removed.

**Comment by jpeach** [comment]
OK I filed [TS-4792](https://issues.apache.org/jira/browse/TS-4792).

**Comment by bryancall** [comment]
👍

**Pull request merged**
