### PR TITLE
AuTest for server_push_preload plugin

### PR DESCRIPTION
**Pull request by masaori335**
Test server_push_preload plugin using [EXAMPLE 3](https://www.w3.org/TR/preload/#example-3) on https://www.w3.org/TR/preload/.

```
Link: </app/style.css>; rel=preload; as=style; nopush
Link: </app/script.js>; rel=preload; as=script
```

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
Installed `nghttp` command to run this AuTest...and we discovered a new crash!
```
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x7ffff5870679]
/opt/ats/bin/traffic_server(_ZN9__gnu_cxx13new_allocatorIPNSt8__detail15_Hash_node_baseEE10deallocateEPS3_m+0x20)[0x652f38]
/opt/ats/bin/traffic_server(_ZNSt16allocator_traitsISaIPNSt8__detail15_Hash_node_baseEEE10deallocateERS3_PS2_m+0x2b)[0x652a28]
/opt/ats/bin/traffic_server(_ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISsLb1EEEEE21_M_deallocate_bucketsEPPNS_15_Hash_node_baseEm+0x5a)[0x77db4e]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE21_M_deallocate_bucketsEPPNS1_15_Hash_node_baseEm+0x42)[0x77ccb4]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE21_M_deallocate_bucketsEv+0x2a)[0x77c158]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE13_M_rehash_auxEmSt17integral_constantIbLb1EE+0x15b)[0x77ffd7]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE9_M_rehashEmRKm+0x2d)[0x77f235]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE21_M_insert_unique_nodeEmmPNS1_10_Hash_nodeISsLb1EEE+0x85)[0x77e601]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE10_M_emplaceIJRSsEEESt4pairINS1_14_Node_iteratorISsLb1ELb1EEEbESt17integral_consta
ntIbLb1EEDpOT_+0x10d)[0x7938cf]
/opt/ats/bin/traffic_server(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE7emplaceIJRSsEEESt4pairINS1_14_Node_iteratorISsLb1ELb1EEEbEDpOT_+0x34)[0x792f66]
/opt/ats/bin/traffic_server(_ZNSt13unordered_setISsSt4hashISsESt8equal_toISsESaISsEE7emplaceIJRSsEEESt4pairINSt8__detail14_Node_iteratorISsLb1ELb1EEEbEDpOT_+0x2c)[0x7927f0]
/opt/ats/bin/traffic_server(_ZN18Http2ClientSession23add_url_to_pushed_tableEPKci+0x88)[0x79093c]
/opt/ats/bin/traffic_server(TSHttpTxnServerPush+0x245)[0x6679dc]
```

It looks like replacing `TCLHashTable` with `std::unordered_map` introduced this.
https://github.com/apache/trafficserver/commit/b95a38f7c98304c198fefbaf437632b2471cd52d#diff-68f975021d4ed3eb1a329dbe89828f0cL348-R342

**Comment by masaori335** [comment]
```
(gdb) frame 4
#4  0x0000000000652f38 in __gnu_cxx::new_allocator<std::__detail::_Hash_node_base*>::deallocate (this=0x7ffff1ffc277, __p=0xd0b558 <http2ClientSessionAllocator+3640>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/new_allocator.h:125
125             ::operator delete(__p);
(gdb) p sizeof(http2ClientSessionAllocator)
$3 = 3688
```
It looks like we can't make`std::unordered_map` as a member of a class which is allocated by ClassAllocator.

**Comment by randall** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
```
Running Test server_push_preload:. Passed
```

**Comment by calavera** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
