### PR TITLE
Add prr proxy_request_retries log field

### PR DESCRIPTION
**Pull request by jacksontj**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/896/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1004/ for details.

**Comment by jpeach** [comment]
Also, we should have a Jira for this :)

**Comment by jacksontj** [comment]
I'm not sure about the name (currently `prr`), anyone have opinions on the name?

**Comment by jacksontj** [comment]
Seems that this does already exists from TS-4148, just couldn't find it ;)

**Pull request closed without merging**
