### PR TITLE
TS-3540: Remove the channel_stats plugin.

### PR DESCRIPTION
**Pull request by PSUdaemon**

### CODE REVIEW

**Comment by shukitchan** [comment]
👍

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/471/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/575/ for details.

**Comment by bryancall** [comment]
👍 - Looks good

**Pull request merged**
