### PR TITLE
Test: Update micro-server to have hooks for observers.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
For testing the VIA logic I need to observe the request that arrives at the micro-server. This patch creates a generic hook capability in the micro-server and updates the AU extensions to enable that to be passed to the micro-server.  I have a working test that uses this that I will submit once it's cleaned up.

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/142/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/157/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1838/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/140/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/268/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1729/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/400/

**Comment by SolidWallOfCode** [comment]
@dragon512 @persiaAziz please review.

**Comment by persiaAziz** [comment]
+1

**Comment by dragon512** [comment]
+1 you're the man @SolidWallOfCode

**Pull request merged**
