### PR TITLE
[TS 4437] Add new limit rate example plugin

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
The unfortunately fails the clang-format test: https://ci.trafficserver.apache.org/view/github/job/Github-Linux/78/console

**Comment by zwoop** [comment]
Also, when you fix clang-format, can you squash the two commits into one? No reason to retain the one without the license blurb.

**Comment by yatsukhnenko** [comment]
done

**Comment by zwoop** [comment]
.

**Comment by yatsukhnenko** [comment]
I need some help for fixing unexpected Segmentation fault.
```
NOTE: Traffic Server received Sig 11: Segmentation fault
/opt/trafficserver-4.2.3/bin/traffic_server - STACK TRACE:
/lib64/libpthread.so.0(+0x318aa0f710)[0x2b804a60f710]
/opt/trafficserver-4.2.3/bin/traffic_server(_ZN6HttpSM17tunnel_handler_uaEiP18HttpTunnelConsumer+0x32e)[0x51bd0e]
/opt/trafficserver-4.2.3/bin/traffic_server(_ZN10HttpTunnel16consumer_handlerEiP18HttpTunnelConsumer+0x9e)[0x56c16e]
/opt/trafficserver-4.2.3/bin/traffic_server(_ZN10HttpTunnel12main_handlerEiPv+0x10d)[0x56d16d]
/opt/trafficserver-4.2.3/bin/traffic_server[0x687961]
/opt/trafficserver-4.2.3/bin/traffic_server(_Z15write_to_net_ioP10NetHandlerP18UnixNetVConnectionP7EThread+0x8b5)[0x68acf5]
/opt/trafficserver-4.2.3/bin/traffic_server(_ZN10NetHandler12mainNetEventEiP5Event+0x283)[0x67ed43]
/opt/trafficserver-4.2.3/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x8f)[0x6ab4cf]
/opt/trafficserver-4.2.3/bin/traffic_server(_ZN7EThread7executeEv+0x44b)[0x6abd0b]
/opt/trafficserver-4.2.3/bin/traffic_server[0x6aa85a]
/lib64/libpthread.so.0(+0x318aa079d1)[0x2b804a6079d1]
/lib64/libc.so.6(clone+0x6d)[0x318a6e88fd]
```

```
#0  get_netvc (this=0x2b8078a00000, event=104, c=0x2b8078a01ca8) at HttpServerSession.h:113
#1  HttpSM::tunnel_handler_ua (this=0x2b8078a00000, event=104, c=0x2b8078a01ca8) at HttpSM.cc:3067
#2  0x000000000056c16e in HttpTunnel::consumer_handler (this=0x2b8078a01c00, event=104, c=0x2b8078a01ca8) at HttpTunnel.cc:1261
#3  0x000000000056d16d in HttpTunnel::main_handler (this=0x2b8078a01c00, event=<value optimized out>, data=<value optimized out>) at HttpTunnel.cc:1492
#4  0x0000000000687961 in handleEvent (event=<value optimized out>, nh=0x2b804c50ac00, vc=0x2b805a415a80) at ../../iocore/eventsystem/I_Continuation.h:146
#5  write_signal_and_update (event=<value optimized out>, nh=0x2b804c50ac00, vc=0x2b805a415a80) at UnixNetVConnection.cc:153
#6  write_signal_done (event=<value optimized out>, nh=0x2b804c50ac00, vc=0x2b805a415a80) at UnixNetVConnection.cc:180
#7  0x000000000068acf5 in write_to_net_io (nh=0x2b804c50ac00, vc=0x2b805a415a80, thread=0x2b804c507000) at UnixNetVConnection.cc:472
#8  0x000000000067ed43 in NetHandler::mainNetEvent (this=0x2b804c50ac00, event=<value optimized out>, e=<value optimized out>) at UnixNet.cc:400
#9  0x00000000006ab4cf in handleEvent (this=0x2b804c507000, e=0x2b804e616cc0, calling_code=5) at I_Continuation.h:146
#10 EThread::process_event (this=0x2b804c507000, e=0x2b804e616cc0, calling_code=5) at UnixEThread.cc:145
#11 0x00000000006abd0b in EThread::execute (this=0x2b804c507000) at UnixEThread.cc:269
#12 0x00000000006aa85a in spawn_thread_internal (a=0x2b804b6854f0) at Thread.cc:88
#13 0x00002b804a6079d1 in start_thread () from /lib64/libpthread.so.0
#14 0x000000318a6e88fd in clone () from /lib64/libc.so.6
```
@zwoop, would you have a time to look closer at this PR?

**Comment by yatsukhnenko** [comment]
@zwoop, could you have a time to look closer at this PR?

**Comment by zwoop** [comment]
[approve ci] Doing a fresh build.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/179/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/287/ for details.

**Comment by zwoop** [comment]
Sorry for the delay. Would you mind squashing this down to just one commit as well please?

**Comment by yatsukhnenko** [comment]
OK, I will do, but could you first look at the first two commits separately?
There are various operation logic and I have some concerns about it.
At first one I calculate time which should elapsed before next write operation may be executed an SD I used TSContSchedule for delaying operations and I don't know what minimum value of delay can I use and how large number of delayed tasks will impact on server.
At second one I calculate a number of bytes for elapsed time and just reenable operation until there will be ability to make write operation.
Another problem is that server writes data to cache after transformation and I don't know how to change this behavior.
I can do some improvement in plugin like separate limits per url or limit rate after some amount of bytes transferred but I don't want to do that before reviewing.

**Comment by yatsukhnenko** [comment]
@zwoop, did you review the code? Is it absolutely wrong and I should throw it out and close this PR? can you give any feedback?

**Comment by zwoop** [comment]
Aww, don't close it. I don't think anything absolutely wrong here, we should land this. There are things that needs to be fixed, but they are pretty minor (like, squashing, clang-format, typos like "avial" which likely should be "avail" etc.

I think you should reopen this.

**Comment by yatsukhnenko** [comment]
Closing PR is the only way to attract your attention :smile:
If serious, I think you shouldn't land this as is (even after squashing and fixing spelling typos) because it sometimes crashes and repeatedly writes data to cache and, in my opinion, rate limiting should by implemented somewhere in iocore(thats why I closed this PR)

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/328/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/435/ for details.

**Comment by zwoop** [comment]
Hmmm, well, if it doesn't work, then it's a moot point. I know people have implemented rate limiting in plugins, it was just never open sourced. If you don't feel strongly about it, closing it is fine.

**Comment by yatsukhnenko** [comment]
It does what it should. If somebody will help to solve the problem with multiple writing to cache this will fine open source example :-)

**Comment by yatsukhnenko** [comment]
@zwoop, I did squashing and fixing clang-format and spelling typos. Review please :)

**Comment by zwoop** [comment]
I'm not sure if anyone has had the cycles to help debug this :-/ It might be worth emailing dev@ with a concrete question / request for help.

**Pull request closed without merging**
