### PR TITLE
Use correct default value for verify.server.policy

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by randall** [comment]
Running master (before this change) I see this on startup:

```
[Mar 26 17:22:28.037]  WARNING: STRICT is invalid for proxy.config.ssl.client.verify.server.policy.  Should be one of DISABLED, PERMISSIVE, or ENFORCED
```

**Comment by randall** [comment]
[approve ci autest]

**Review by bneradt — DISMISSED** [review]

**Comment by bneradt** [comment]
Oh, interesting. Good fix, but it looks like this will require test changes since I suppose the previous default must have been DISABLED or PERMISSIVE.

**Review by shinrich — APPROVED** [review]

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]

**Pull request merged**
