### PR TITLE
CID 1375916 Missing break in TSHttpTxnConfigStringSet

### PR DESCRIPTION
**Pull request by scw00**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
Haha, just like #2044. But you missed the double `break`.

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
This looks good to like #2044

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Pull request closed without merging**
