### PR TITLE
Skip dns lookup and connect to os directly when proxies all failed

### LINKED ISSUE #3398: 6.2.2 crash - crash on revalidation, when all proxies fail and failover to origin
When doing a revalidate for a stale case, if all parent proxies failed, ATS will crash.

FATAL: HttpTransact.cc:2397: failed assert `(s->request_sent_time == UNDEFINED_TIME) && (s->response_received_time == UNDEFINED_TIME)`

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffef58c700 (LWP 6549)]
0x00007ffff4fc95f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install astats_over_http-1.3-1.el7.centos.3.6.1.b1.x86_64 glibc-2.17-105.el7.x86_64 hwloc-libs-1.7-5.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 k
rb5-libs-1.13.2-10.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libpciaccess-0.13.4-2.el7.x86_64 libselinux-2.2.2
-6.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 libxml2-2.9.1-5.el7_1.2.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 numactl-libs-2.0.9-5.el7_1.x86_64 openssl-libs-1.0.1e-42.el7.9.x86_64 pc
re-8.32-15.el7.x86_64 tcl-8.5.13-8.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00007ffff4fc95f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff4fcace8 in abort () from /lib64/libc.so.6
#2  0x00007ffff7bc2488 in ink_die_die_die () at ink_error.cc:43
#3  ink_fatal_va (fmt=0x7ffff7bce73f "%s:%d: failed assert `%s`", ap=ap@entry=0x7fffef58b6f8)
    at ink_error.cc:65
#4  0x00007ffff7bc251c in ink_fatal (
    message_format=message_format@entry=0x7ffff7bce73f "%s:%d: failed assert `%s`")
    at ink_error.cc:73
#5  0x00007ffff7bc07f5 in _ink_assert (expression=<optimized out>, file=<optimized out>,
    line=<optimized out>) at ink_assert.cc:37
#6  0x00000000005d57a4 in HttpTransact::HandleCacheOpenReadHitFreshness (s=0x7fffab271270)
    at HttpTransact.cc:2397
#7  0x000000000059f226 in HttpSM::call_transact_and_set_next_state (this=0x7fffab271200,
    f=<optimized out>) at HttpSM.cc:7069
#8  0x00000000005aa35b in HttpSM::state_api_callout (this=0x7fffab271200, event=0, data=0x0)
    at HttpSM.cc:1534
#9  0x00000000005aeecb in HttpSM::set_next_state (this=0x7fffab271200) at HttpSM.cc:7110
#10 0x00000000005aa35b in HttpSM::state_api_callout (this=this@entry=0x7fffab271200,
    event=event@entry=60000, data=data@entry=0x0) at HttpSM.cc:1534
#11 0x00000000005b0665 in HttpSM::state_api_callback (this=this@entry=0x7fffab271200,
    event=event@entry=60000, data=data@entry=0x0) at HttpSM.cc:1331
#12 0x00000000004d54b9 in TSHttpTxnReenable (txnp=txnp@entry=0x7fffab271200,
    event=event@entry=TS_EVENT_HTTP_CONTINUE) at InkAPI.cc:5651
#13 0x00007fffe2aec77e in main_handler (cont=<optimized out>, event=<optimized out>,
    edata=0x7fffab271200) at regex_revalidate.c:428
#14 0x00000000004c16bc in INKContInternal::handle_event (this=0x1721ee0, event=60015,
    edata=0x7fffab271200) at InkAPI.cc:1005
#15 0x00000000005aa0ff in HttpSM::state_api_callout (this=0x7fffab271200,
    event=<optimized out>, data=<optimized out>) at HttpSM.cc:1452
#16 0x00000000005aafe8 in do_api_callout (this=0x7fffab271200) at HttpSM.cc:433
#17 setup_cache_lookup_complete_api (this=0x7fffab271200) at HttpSM.cc:2555
#18 HttpSM::state_cache_open_read (this=0x7fffab271200, event=1103, data=0xffffffffffffb04f)
    at HttpSM.cc:2616
#19 0x00000000005b081d in HttpSM::main_handler (this=0x7fffab271200, event=1103,
    data=0xffffffffffffb04f) at HttpSM.cc:2658
#20 0x0000000000589c09 in handleEvent (data=0xffffffffffffb04f, event=1103,
    this=<optimized out>) at ../../iocore/eventsystem/I_Continuation.h:153
#21 HttpCacheSM::state_cache_open_read (this=0x7fffab272b10, event=1103,
    data=0xffffffffffffb04f) at HttpCacheSM.cc:145
#22 0x00000000006f20f4 in handleEvent (data=0xffffffffffffb04f, event=1103,
    this=<optimized out>) at ../../iocore/eventsystem/I_Continuation.h:153
#23 CacheVC::openReadFromWriterFailure (this=this@entry=0x18cdcf0, event=event@entry=1103,
    e=e@entry=0xffffffffffffb04f) at CacheRead.cc:187
#24 0x00000000006f957d in CacheVC::openReadFromWriter (this=0x18cdcf0, event=<optimized out>,
    e=0x7fffb01cbae0) at CacheRead.cc:374
#25 0x00000000007647f0 in handleEvent (data=0x7fffb01cbae0, event=2, this=<optimized out>)
    at I_Continuation.h:153
#26 EThread::process_event (this=0x7ffff13ab010, e=0x7fffb01cbae0, calling_code=2)
    at UnixEThread.cc:148
#27 0x00000000007654c1 in EThread::execute (this=0x7ffff13ab010) at UnixEThread.cc:230
---Type <return> to continue, or q <return> to quit---
#28 0x000000000076429a in spawn_thread_internal (a=0x10ac860) at Thread.cc:86
#29 0x00007ffff60e9dc5 in start_thread () from /lib64/libpthread.so.0
#30 0x00007ffff508a21d in clone () from /lib64/libc.so.6

### PR DESCRIPTION
**Pull request by zhilhuan**
fix #3398

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci clang-format]

**Comment by shinrich** [comment]
I'm not familiar with the parent logic at all.  So even though the code change is simple, I'd feel better with @jrushford  or @vmamidi taking a look since they are familiar with handling parent requests.

**Comment by a-canary** [comment]
-1
I don't see where this code path would have gone through `OSDNSLookup()`.  It definitely when through `PPDNSLookup()` but that doesn't set the `server_info.dst_addr`.

**Comment by vmamidi** [comment]
DNS being done in earlier states depends on various configuration parameters.

**Comment by a-canary** [comment]
Should we verify that the `DNSLookup` was attempted (or successful) before skipping directly to `SM_ACTION_ORIGIN_SERVER_OPEN`?

**Comment by bryancall** [comment]
It looks like this PR still needs some work and hasn't been updated for a few months.  Closing for now.  Please reopen if there are updates.

**Pull request closed without merging**
