### PR TITLE
lua plugin: fix for incorrectly injecting global plugin stats

### PR DESCRIPTION
**Pull request by traeak**
Fixes a bug where the global lua plugin stats are incorrectly assigned causing a collision with remap plugins.

### CODE REVIEW

**Comment by jvgutierrez** [comment]
I've tested this on top of our 8.x branch + #6802 + #4924 (to get a clean patch applied) and it solves the issues I've commented on #6802

**Comment by traeak** [comment]
with the autest the traffic_ctl metric match is what's causing trouble.  How to ensure it runs until the metrics show up?

**Comment by shukitchan** [comment]
It looks good. thanks.

**Comment by traeak** [comment]
I hope I got it.  My global lua script was an invalid global lua script.  Fixing that seems to have fixed the autest.

**Comment by traeak** [comment]
[approve ci autest]

**Comment by traeak** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
