### PR TITLE
QUIC: Hidden more pp_key_info detail in QUICContext

### PR DESCRIPTION
**Pull request by scw00**
It is not necessary to explore all pp_key_info to context. So hidden it into context.

### CODE REVIEW

**Comment by maskit** [comment]
I may want to call it QUICPacketProtectionKey*State*Provider, if we only provide the two functions but not actual key information (keys, lengths, etc.).

**Comment by maskit** [comment]
Also, I'm still not sure if the two are enough. After we implement key update, we might need something else.

**Comment by scw00** [comment]
Hi @maskit

> I'm still not sure if the two are enough. After we implement key update, we might need something else.

Adds more read only method into QUICPacketProtectionProvider.
 
>I may want to call it QUICPacketProtectionKeyStateProvider, if we only provide the two functions but not actual key information (keys, lengths, etc.).

Not sure I need to change name or not.

**Comment by maskit** [comment]
I'm ok with this change but I don't understand the motivation.

For access control, we could also return `const QUICPacketProtectionKeyInfo *` from `QUICContextImpl::key_info() const`.

I remember you were talking about abstraction, but what issue does it solve?

**Comment by maskit** [comment]
>> I may want to call it QUICPacketProtectionKeyStateProvider, if we only provide the two functions but not actual key information (keys, lengths, etc.).

> Not sure whether I need to change name or not.

I'm fine with the current name is it also provides actual keys.

**Comment by scw00** [comment]
> For access control, we could also return const QUICPacketProtectionKeyInfo * from QUICContextImpl::key_info() const.

It is also fine to me .  I just want to make all params in context are read only. So when I use it as the QUICFrameGenerator's base params. It will not break anything up but only provide information. Also add an abstraction is clearer for someone which method can be used in this class.

The reason I need to  add context into QUICFrameGenerator is reenable the QUIC write event. I tested the quic performance recently. It seems the quic always blocked by flow control. So the max_xxx_data frame must be blocked by some reason.

**Pull request merged**
