### PR TITLE
Add back in length check to fail H2 headers with no name.

### PR DESCRIPTION
**Pull request by shinrich**
Fix I am testing for issue #2051

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to 7.1.x as well.

**Comment by shinrich** [comment]
Just adding a note, that we finally got to run this 24 hours in productions successfully without crash.

**Pull request merged**
