### PR TITLE
Fix compile warnings in Catch checks for TextView

### PR DESCRIPTION
**Pull request by zwoop**
This is a pre-req for #6185

### CODE REVIEW

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by SolidWallOfCode** [comment]
Sigh. Those tests  existed precisely to check compilation correctness. If there are compilation errors, those need to be fixed, not the tests removed.

**Comment by ywkaras** [comment]
If you get unused variable warnings, there's an easy fix, a statement casting to void.
```
wkaras /tmp/argh
M$ cat xx.cc
void foo()
{
  int i;
}
wkaras /tmp/argh
M$ clang -c -Wall -Wextra xx.cc
xx.cc:3:7: warning: unused variable 'i' [-Wunused-variable]
  int i;
      ^
1 warning generated.
wkaras /tmp/argh
M$ cat yy.cc
void foo()
{
  int i;
  static_cast<void>(i);
}
wkaras /tmp/argh
M$ clang -c -Wall -Wextra yy.cc
wkaras /tmp/argh
M$ 
```

**Comment by SolidWallOfCode** [comment]
I think official mechanism is now `[[maybe_unused]]` - see [here](https://en.cppreference.com/w/cpp/language/attributes/maybe_unused).

**Pull request merged**
