### PR TITLE
	Add support for TSIpAddrParse as a conveninent function to parse IP address

### PR DESCRIPTION
**Pull request by shukitchan**

### CODE REVIEW

**Comment by zwoop** [comment]
I'm fine with the naming, but looking at existing APIs, two things comes to mind:

1 We don't generally seem to put "IP" into the API names.

2 Maybe the API should be clear about what it parses?


So, possibly:

```
TSStringAddrParse()
```

or just

```
TSAddrParse()
```

? @SolidWallOfCode thoughts?

**Comment by SolidWallOfCode** [comment]
I think we want the "Ip" because "address" is a rather broad term. Maybe "TSIpStringToAddr"?

I understand what Kit wants here but it does bring up a bigger issue, which is that almost all of `ink_inet.h` should be made accessible from a plugin. I was think of making the file itself available for better names, but on reflection "ats_ip..." isn't any better than "TSIp...". It's just less code. Maybe Kit's correct, we should port these over as we can and not try for a "big bang" of availability. While I'm mixed on this _specific_ approach, I strongly support doing _something_ like this.

**Comment by zwoop** [comment]
TSIpStringToAddr() seems descriptive too.

**Comment by shukitchan** [comment]
I am ok with that function name as well. Want me to make the change?

**Comment by shukitchan** [comment]
@zwoop @SolidWallOfCode made the change. pls take a look. thanks.

**Comment by shukitchan** [comment]
@zwoop @SolidWallOfCode any more comments before I squash and merge?
I want to finish this before i move ts_lua to stable.

**Comment by shukitchan** [comment]
@zwoop @SolidWallOfCode  ping !

**Comment by shukitchan** [comment]
[approve ci fedora]

**Comment by shukitchan** [comment]
oh. i need to use stringview now.

**Comment by shukitchan** [comment]
[approve ci]

**Pull request merged**
