### PR TITLE
Parent Selection - Consistent Hash - secondary_mode

### PR DESCRIPTION
**Pull request by pbchou**
Add new 'parent.config' option 'secondary_mode' that can be used to
modify the fail-to behavior of the 'secondary_parent' parent list.

Option 1 (default) fails to secondary then primary (same as before).
The secondary parents are used as primary backups. This also helps to
prevent cache pollution of other caches in the primary list.

Option 2 fails to primary first then secondary.
If the secondary parents are non-optimal in some way, e.g., capacity,
bandwidth, or latency (distance), then the secondary may be used as
secondary backups instead of as primary backups.

Option 3 fails to primary first then secondary unless the first choice
parent is marked down using the host marking function. In that case,
the selection fails to the secondary first then primary. This can
be used to "forward" traffic destined for the marked-down host
to the secondary parents.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
@pbchou There is a problem with the tertiary on line 199 of ParentConsistentHash.cc

ParentConsistentHash.cc:199:44: error: address of array 'pRec->hostname' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
      result->first_choice_status = (pRec->hostname) ? pStatus.getHostStatus(pRec->hostname) : HostStatus_t::HOST_STATUS_INIT;
                                     ~~~~~~^~~~~~~~  ~
1 error generated.

**Comment by pbchou** [comment]
Thanks. The expression should have been just (pRec). I will update my PR branch later today.

**Comment by pbchou** [comment]
I re-pushed the branch. Thanks.

**Comment by vmamidi** [comment]
[approve ci]

**Pull request merged**
