### PR TITLE
Fix ssl hook state logic.

### PR DESCRIPTION
**Pull request by shinrich**
Was not correctly resetting the ssl hook state after the servername hooks.

### CODE REVIEW

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/122/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1690/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1586/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/254/ for details.

**Comment by atsci** [comment]
AU check *successful*! See https://ci.trafficserver.apache.org/job/autest-github/2/ for details.

**Comment by persiaAziz** [comment]
+1 
Looks good

**Comment by zwoop** [comment]
@persiaAziz This does not cherry-pick cleanly to 7.1.0, so if we want this for 7.1.x branch, can you please make another PR, against the 7.1.x branch?

**Comment by persiaAziz** [comment]
@zwoop this does not cherry-pick cleanly because #1446  is not backported .. 
#1610 backports both to 7.1.x

**Pull request merged**
