### PR TITLE
Fix LIBTCL and HWLOC_LIBS linking for traffic_top for Ubuntu.

### PR DESCRIPTION
**Pull request by pbchou**
Based on prior patch TS-3109.

### CODE REVIEW

**Comment by bryancall** [comment]
@pbchou What errors are you getting without linking with tcl and hwloc?  traffic_top shouldn't require these libs.

**Comment by bryancall** [comment]
[approve ci]

**Comment by pbchou** [comment]
FYI Ubuntu Server 64-bit 14.04 LTS --
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(UnixEventProcessor.o): undefined reference to symbol 'hwloc_bitmap_iszero'
//usr/lib/x86_64-linux-gnu/libhwloc.so.5: error adding symbols: DSO missing from command line

/usr/bin/ld: ../../mgmt/.libs/libmgmt_p.a(BaseManager.o): undefined reference to symbol 'Tcl_NextHashEntry'
//usr/lib/x86_64-linux-gnu/libtcl8.6.so: error adding symbols: DSO missing from command line

**Comment by zwoop** [comment]
[approve ci autest]

**Pull request merged**
