### PR TITLE
Remove remaining use of obsolete debug output functions.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci osx]

**Comment by ywkaras** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
[approve ci osx]

**Comment by ywkaras** [comment]
I pass the rebase lackey baton for this PR to @zwoop .

**Comment by ywkaras** [comment]
@bryancall maybe discuss getting this reviewed in the meeting tonight?  It's prone to need rebasing the longer it sits.

**Comment by ywkaras** [comment]
This isn't really a blocker for 10.1.0 .  The performance impact is negligible, and there is no user visibility of it otherwise.  Milestone could be Sometime (until it is reaped by the Stale label).

**Comment by ywkaras** [comment]
Since I don't work for Yahoo anymore, does that mean I can approve my own PR?  Note this is one lawsuit my severance package agreement does not preclude me from bringing.

**Comment by zwoop** [comment]
Fix the damn conflicts!

**Comment by bryancall** [comment]
@zwoop is slacking and we reminded him in the meeting today.

**Comment by ywkaras** [comment]
I rebased this again, because @zwoop is really going to review it this time.  https://makeagif.com/i/5ztSvz

**Comment by ywkaras** [comment]
If anybody approves this, please merge it immediately afterward.  It might get new merge conflicts before I come up for air from bingwatching *Preacher*.

**Review by cmcfarlen — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
