### PR TITLE
TS-4691 Removes a bogus assertion which can cause failure

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/528/ for details.

**Comment by JamesPeach** [comment]
👍 

Maybe file a Jira to remove expandomatic? It seems like a relic.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/425/ for details.

**Comment by zwoop** [comment]
I already did a while ago ( can't see the Jira right now). 😀

**Pull request merged**
