### PR TITLE
8.1.x backport code and documentation for lua states configuration and stats printing

### PR DESCRIPTION
**Pull request by traeak**
Original PR (#6571)

(cherry picked from commit 8369634bdff95d6e6a0fcdd04cd81d183e8e675a)

### CODE REVIEW

**Comment by jvgutierrez** [comment]
After applying this PR we get two different issues in our instances, on the backend one:
```
May 20 15:14:34 cp5012 traffic_server[26855]: Fatal: attempted to register plugin.lua.remap.states twice
```

and on the TLS one:
```
May 20 15:15:24 cp5012 traffic_manager[25612]: NOTE: using cwd as TS_RUNROOT
May 20 15:15:24 cp5012 traffic_crashlog[27326]: NOTE: using cwd as TS_RUNROOT
May 20 15:15:24 cp5012 traffic_manager[25612]: [May 20 15:15:24.799] traffic_crashlo NOTE: crashlog started, target=27318, debug=false syslog=true, uid=116 euid=0
May 20 15:15:24 cp5012 traffic_crashlog[27326]: traffic_crashlo NOTE: crashlog started, target=27318, debug=false syslog=true, uid=116 euid=0
May 20 15:15:24 cp5012 traffic_manager[25612]: [May 20 15:15:24.800] traffic_crashlo NOTE: logging to 0x55b826dad260
May 20 15:15:24 cp5012 traffic_crashlog[27326]: traffic_crashlo NOTE: logging to 0x55b826dad260
May 20 15:15:25 cp5012 traffic_manager[25612]: [May 20 15:15:25.229] traffic_crashlo ERROR: wrote crash log to /srv/trafficserver/tls/var/log/crash-2020-05-20-151524.log
May 20 15:15:25 cp5012 traffic_crashlog[27326]: traffic_crashlo ERROR: wrote crash log to /srv/trafficserver/tls/var/log/crash-2020-05-20-151524.log
May 20 15:15:25 cp5012 traffic_manager[25612]: traffic_server: received signal 11 (Segmentation fault)
May 20 15:15:25 cp5012 traffic_manager[25612]: traffic_server - STACK TRACE:
May 20 15:15:25 cp5012 traffic_manager[25612]: /srv/trafficserver/tls/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0xa0)[0x5568cf3500c0]
May 20 15:15:25 cp5012 traffic_manager[25612]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f0c9c249730]
May 20 15:15:25 cp5012 traffic_manager[25612]: /usr/lib/trafficserver/modules/tslua.so(+0x8321)[0x7f0c8a2cd321]
May 20 15:15:25 cp5012 traffic_manager[25612]: /srv/trafficserver/tls/bin/traffic_server(_ZN15INKContInternal12handle_eventEiPv+0x9b)[0x5568cf35a96b]
May 20 15:15:25 cp5012 traffic_manager[25612]: /srv/trafficserver/tls/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x92)[0x5568cf636a22]
May 20 15:15:25 cp5012 traffic_manager[25612]: /srv/trafficserver/tls/bin/traffic_server(_ZN7EThread15execute_regularEv+0x2a2)[0x5568cf637a22]
May 20 15:15:25 cp5012 traffic_manager[25612]: /srv/trafficserver/tls/bin/traffic_server(+0x3b030a)[0x5568cf63630a]
May 20 15:15:25 cp5012 traffic_manager[25612]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7f0c9c23efa3]
May 20 15:15:25 cp5012 traffic_manager[25612]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f0c9be474cf]
```

**Comment by traeak** [comment]
Thanks for the feedback.  Rebasing this plugin in the 8.1.x branch so I can test it locally.  This has seen a lot of synthetic testing.

**Comment by traeak** [comment]
[approve ci autest]

**Comment by jvgutierrez** [comment]
we've been running this for a while on production without major issues

**Pull request merged**
