### PR TITLE
Modified the plugin to add back the Range request header at the TS_HT…

### PR DESCRIPTION
**Pull request by jrushf1239k**
…TP_SEND_RESPONSE_HDR_HOOK

so that custom logging of range requests works properly.

### CODE REVIEW

**Comment by sudheerv** [comment]
@jrushf1239k : lgtm - pls run clang format on the patch, so, I can merge it.

**Comment by jrushf1239k** [comment]
Sudheer,

I ran clang format and pushed it.

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by sudheerv** [comment]
thanks, @jrushf1239k - merging it.

**Comment by jrushf1239k** [comment]
thanks

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by jpeach** [comment]
You should use ```__func__``` in debug messages rather than typing the function name all the tine :)

**Comment by jrushf1239k** [comment]
You’re right, I should have.  Will do next time ;)

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Comment by jpeach** [comment]
As a separate ticket, if you just rename the original ```Range``` header to ```@Range```, you can remove the per-transaction data, saving yourself the copying and allocations.

**Comment by sudheerv** [comment]
@jpeach : I agree - but, one issue I could see in renaming Range to @Range, is that, it's not transparent to custom logging configuration (the operators need to know to log @Range instead of Range). Whereas,  re-adding the Range header back makes it seamlessly work for operators wanting to log Range header.

**Comment by jpeach** [comment]
You would still re-add, but renaming means you don't need to do a bunch of copies. I agree that restoring ```Range``` is the right thing.

**Comment by sudheerv** [comment]
Ah, I see - you are basically suggesting to rename Range to @Range temporarily and re-add @Range as Range. Of the top of my head, I don't know if these operations also involve a bunch of copying stuff around, but, if they don't, then yes, that's more efficient.

**Comment by jrushf1239k** [comment]
That’s why I added it back as ‘Range’, so that it would be seamless for those using custom logs.  Otherwise they’d have to read the source code and/or it’s documentation to know to use @Range.

Thanks
--
John J. Rushford
IPCDN Engineering
1400 Wewatta Street, Denver Colorado 80202
John_Rushford@cable.comcast.com

**Pull request merged**
