### PR TITLE
TS-4324: Buffer responses to not send small size DATA frames

### PR DESCRIPTION
**Pull request by masaori335**
[TS-4324](https://issues.apache.org/jira/browse/TS-4324)
If body_done flag is not marked and read available size is smaller
than 16KB in Http2ConnectionState::send_a_data_frame(), wait until
body_done flag is marked or read available size is over 16KB.

### CODE REVIEW

**Comment by masaori335** [comment]
## before
```
$ nghttp --no-dep -vn "https://127.0.0.1:4443/stream-bytes/163840?chunk_size=16284"
...
[  0.130] recv DATA frame <length=7946, flags=0x00, stream_id=1>
[  0.130] recv DATA frame <length=8438, flags=0x00, stream_id=1>
[  0.169] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.169] recv DATA frame <length=9, flags=0x00, stream_id=1>
[  0.206] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.206] recv DATA frame <length=9, flags=0x00, stream_id=1>
[  0.242] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.242] recv DATA frame <length=9, flags=0x00, stream_id=1>
[  0.279] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.279] recv DATA frame <length=9, flags=0x00, stream_id=1>
[  0.316] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.316] recv DATA frame <length=9, flags=0x00, stream_id=1>
[  0.325] recv DATA frame <length=4096, flags=0x00, stream_id=1>
[  0.325] recv DATA frame <length=0, flags=0x01, stream_id=1>
          ; END_STREAM
...
```

## after
```
$ nghttp --no-dep -vn "https://127.0.0.1:4443/stream-bytes/163840?chunk_size=16284"
...
[  0.135] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.168] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.205] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.241] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.277] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.288] recv DATA frame <length=16375, flags=0x00, stream_id=1>
[  0.288] recv DATA frame <length=4150, flags=0x01, stream_id=1>
          ; END_STREAM
...
```

**Comment by bgaff** [comment]
This is undesirable for content such as HTML where it's a common pattern for pages to "early flush" so that clients can begin downloading static resources earlier (such as js/css/images).

**Comment by masaori335** [comment]
Yes, this could increase time to first byte. We should send the first chunk in anyway.

**Comment by bgaff** [comment]
I actually don't think we should do buffering at all. I believe the TCP implementation should be responsible for determining how the data goes over the wire.

**Comment by zwoop** [comment]
I'm not saying buffering, I'm saying, use as much from what's already buffered before you send a frame. There's zero reason to send a 9 byte frame, which could theoretically become TCP packet with 9 byte body, right ?

**Comment by bgaff** [comment]
Agree. If we have N bytes available we should send N bytes immediately, we should never wait for more than N bytes if only N are available.

**Comment by masaori335** [comment]
OK, I'll close this and think this issue again.

**Pull request closed without merging**
