### PR TITLE
TS-3650: Track configuration variable source.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**

### CODE REVIEW

**Comment by sudheerv** [comment]
A config set via traffic_line gets added to records.config as well, so the source of the config changes after a TS restart. Depending on how that info is used, the behavior may be affected after a restart. Note that the config file doesn't get updated when set via a plugin API, so, this looks very inconsistent and unreliable to me and may result in more bugs.

**Comment by zwoop** [comment]
I don't have any particular thoughts on this, other than if we do this, we also add an API to query into this "source" of a particular config. E.g. TSMgmtSourceGet(). I'd be curious as to what @jpeach thinks about this, since he's knee deep in all this lib records stuff.

**Comment by jpeach** [comment]
The ``REC_SRC`` constants scan poorly, I think I'd prefer ``REC_SOURCE``. ``REC_SRC_NONE`` should be called ``REC_SOURCE_NULL`` to be consistent with other naming. There's some semantic confusion about what ``REC_SRC_DEFAULT`` means. When ``traffic_manager`` sets variables, I don't think they should be considered defaults.

I am sympathetic to @sudheerv's concerns about how useful this is. The distinction between "hard-coded default" and "everything else" is clear, but this change is attempting to track various nuances that are much murkier.

Does ``DiagsConfig::RegisterDiagConfig`` really have to register everything? I expect that that superfluous now?

**Comment by SolidWallOfCode** [comment]
The chat concensus seemed to be to change this to NULL, DEFAULT, EXPLICIT, ENV. I'll change "SRC" to "SOURCE" as well - I was tempted to have "RECS" which would be more consistent with the other REC values but that seemed even worse scanning.

**Comment by jpeach** [comment]
Yes, I had the same conflict about ``RECS`` ;)

**Comment by sudheerv** [comment]
I don't think there was a consensus yet (at least, not from my side). AFAIK, my question above on persisting the source as traffic_line was not addressed and without making that information consistent, I am -1 on this PR.

**Comment by jpeach** [comment]
There's no way to know whether a metric was set by ``traffic_line``. The best you can do is to say whether a metric was set by a specific API, but that's complex and low value IMHO, and as you pointed out above, that information is lost when the configuration is persisted.

**Pull request closed without merging**
