### PR TITLE
added tests for different thread configurations

### PR DESCRIPTION
**Pull request by duke8253**

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
@duke8253 Please fix the autest!

**Comment by scw00** [comment]
@dragon512 @PSUdaemon There is a problem. Why can I merge this pr without test. That's strange.

**Comment by scw00** [comment]
[approve ci autest]

**Comment by dragon512** [comment]
@SolidWallOfCode I see that I can merge the PR. Is your login scw00 and not solidwallofcode?

**Comment by scw00** [comment]
No I'm not AMC :-) !

**Comment by dragon512** [comment]
sorry my bad

**Comment by shinrich** [comment]
You could use pstack and parse the output to count the number of threads with stacks.

**Comment by duke8253** [comment]
Changed the tests to use gdb to verify thread information.

**Pull request closed without merging**
