### PR TITLE
TS-4835: Stale while revalidate should only ignore itself.

### PR DESCRIPTION
**Pull request by jpeach**
Currently the stale_while_revalidate plugin ignores all internal
requests, which makes it a no-op for protocol plugins.  It should
use the TSHttpTxnPluginTagGet to only ignore requests that it issues
itself.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/758/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/654/ for details.

**Comment by bryancall** [comment]
👍 - Looks good

**Comment by PSUdaemon** [comment]
👍

**Pull request merged**
