### PR TITLE
Fix slow leak in traffic_manager caused by un-freed capabilities.

### PR DESCRIPTION
**Pull request by alficles**

### CODE REVIEW

**Comment by PSUdaemon** [comment]
@zwoop we should back port this.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/540/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/553/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/538/

**Comment by atsci** [comment]
FreeBSD11 build *failed*! https://ci.trafficserver.apache.org/job/freebsd-github/2234/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/667/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/2130/

**Comment by alficles** [comment]
Is FreeBSD succeeding against master or did I break it somehow?

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/796/

**Comment by PSUdaemon** [comment]
@zwoop it's consistently inconsistent. I think we should do a different PR to normalize `this` usage.

**Pull request merged**
