### PR TITLE
TS-5105: Do vc->con.setRemote(target) before socksEntry->init()

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1281/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1176/ for details.

**Comment by bryancall** [comment]
Please make sure pull requests are reviewed before merging.

**Comment by oknet** [comment]
Got it.

**Pull request merged**
