### PR TITLE
Plugin intercept memleak

### PR DESCRIPTION
**Pull request by traeak**
This attempts to fix a general memory leak for plugins that use TSHttpTxnIntercept and TSHttpTxnServerIntercept.  The memory leak is caused when the intercepted continuation is created using TSMutexCreate() instead of being passed the intercepted transaction's mutex.

### CODE REVIEW

**Comment by sudheerv** [comment]
Can you share more info on the leak - Is the leak from the mutex that's created? Is the leak specific to master or is it a previously existing issue? Curious, because we've had our plugins run like this for years and presumably haven't noticed memory leak/growth due to this.

**Comment by zwoop** [comment]
pasting from the Slack channel comments:

```
Also, looking at the code for the continuation, the ::free() does
void
INKContInternal::free()
{
 clear();
 this->mutex.clear();
and the mutex is ref-counted
so for this to leak, the continuation would need to leak, wouldn’t it ?
```

**Comment by traeak** [comment]
This looks more like a regression in master, not a general bug.  Will close and deal with that properly.

**Comment by randall** [comment]
@traeak Do you have valgrind or some other output showing the leak trace? I'm trying to determine if what you are seeing is the same thing

**Comment by traeak** [comment]
I wrote up this issue:  https://github.com/apache/trafficserver/issues/5777

**Pull request closed without merging**
