### PR TITLE
Do not do DNS if there is a matching parent and object is HIT-STALE 

### PR DESCRIPTION
**Pull request by vmamidi**
This fixes https://github.com/apache/trafficserver/issues/2376

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
What happens if there is no parent selection? Does the child not get the address for the upstream?

**Comment by vmamidi** [comment]
Child will get upstream address if there are no parents or go_direct is true and all the parents are down.
HandleCacheOpenReadHit handles all the possible scenarios.

**Comment by SolidWallOfCode** [comment]
I wonder why that code was put there in the first place. It does look like `HandleCacheOpenReadHit` will do address resolution if the address for the server isn't valid. I also wonder why it checks `force_dns` rather than checking the `server.dst_addr` directly.

**Comment by vmamidi** [comment]
I cleaned up most of the code while working on fixing the HostDB deadlocks #1756 .

**Comment by zwoop** [comment]
I've reverted this, we observed a crasher, outlined in #4009.

**Pull request merged**
