### PR TITLE
Fixes misc. spelling and whitespace

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by randall** [comment]
[approve ci ubuntu]

**Comment by zwoop** [comment]
@randall  This has a few merge conflicts, would you mind making a 9.0.x PR  with this cherry-pick ?

**Comment by zwoop** [comment]
maybe this depends on #6130 too ? Which in turn depends on the slice commit, and the system tap commit :)

**Comment by zwoop** [comment]
@randall  do we still want / need to CP things from this? If so, I think we'll need a new PR for 9.o0.x branch

**Pull request merged**
