### PR TITLE
Cleanup: Http2ConnectionState

### PR DESCRIPTION
**Pull request by masaori335**
Cosmetic changes.
- Replace C-style cast
- Fix & adjust debug logs

### CODE REVIEW

**Review by brbzull0 — APPROVED** [review]
Thanks.

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci freebsd]

**Comment by masaori335** [comment]
Please take another look. AuTest was fixed.

**Review by bneradt — APPROVED** [review]

**Pull request merged**
