### PR TITLE
TS-4589: Coalesce CPP API examples build.

### PR DESCRIPTION
**Pull request by jpeach**
The CPP API examples all have trivial, identical makefiles.  Coalesce
these like we did to the TSAPI examples to parallelize the build,
remove duplication and support the --enable-example-plugins build
option.

### CODE REVIEW

**Comment by jpeach** [comment]
One of the motivations for this is to reduce the number of sub-makefiles so that adding a ``tidy`` target for ``clang-tidy`` is more tractable.

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/344/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/238/ for details.

**Comment by bgaff** [comment]
Lgtm

**Pull request merged**
