### PR TITLE
TS-3235: fix crash problem caused by sync problem in PluginVC.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This is an updated version of PR 164 that has been tested in production. It attempts to fix the related issue in the C++ API.

### CODE REVIEW

**Comment by jpeach** [comment]
What is ```ScopedContinuationLock``` for?

**Comment by SolidWallOfCode** [comment]
It lets the C++ API lock a mutex that is contained in a continuation in a scoped fashion. The already existing mutex locking mechanisms handle mutexes via the POSIX interface ({{pthread_mutex}} via {{pthread_mutex_lock}} and {{pthread_mutex_unlock}}). Those mutexes are completely independent of ATS provided mutexes. This makes mutual locking difficult. {{ScopedContinuationLock}} makes it possible for the C++ API to lock a continuation in a way that is detectable by core ATS.

**Comment by jpeach** [comment]
I just meant that I didn't see it used in this patch. Did I look in the right place?

**Comment by SolidWallOfCode** [comment]
Hmmm. I did use it at one point during development of this patch but it appears that code was removed. I'd prefer to leave it in for future use, although it's not actually needed for this change.

**Comment by jpeach** [comment]
Ah. Yep that seems fair enough.

**Pull request closed without merging**
