### PR TITLE
iocore/dns: switch data-type to unsigned

### PR DESCRIPTION
**Pull request by jbergstroem**
While passing buffers to `ns_put16`, make sure they are unsigned. Instead of adding additional typecasting, consistently use unsigned char.

Fixes: https://github.com/apache/trafficserver/issues/2625

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by jbergstroem** [comment]
(as a parenthesis: I'd say theres ~5-6 smaller build fixes in order for Trafficserver to fully build on alpine linux)

**Comment by jbergstroem** [comment]
Fixed the formatting error.

**Comment by scw00** [comment]
[approve ci]

**Comment by zwoop** [comment]
This might be a 7.1.x candidate, it seems safe enough. @bryancall what do you think?

**Comment by zwoop** [comment]
This does not cherry-pick cleanly to the 7.1.x branch. @jbergstroem Can you please make another PR, against the 7.1.x branch? Assuming you want this in 7.1.x  that is.

**Comment by zwoop** [comment]
@jbergstroem Ping?

**Comment by jbergstroem** [comment]
Apologies -- sure, I'll tack a look.

**Comment by zwoop** [comment]
We still want this for 7.1.x? :-) If not, I'll remove the 7 Project from this.

**Comment by zwoop** [comment]
Removing from 7.x for now, since no traction here.

**Pull request merged**
