### PR TITLE
Conversion of logging.config and sni.config to YAML-based files

### PR DESCRIPTION
**Pull request by randall**
There's a few things that still need to be done (eg docs/samples) here. And decision on wether we should include yams-cpp in the tree or not.

### CODE REVIEW

**Comment by randall** [comment]
And builds will definitely fail here.

**Comment by SolidWallOfCode** [comment]
Which version of YAML-CPP did you use?

**Comment by zwoop** [comment]
[approve ci clang-analyzer]

**Comment by persiaAziz** [comment]
What is the status of this PR? I need to opensource another feature of ssl_server_name.config :). Also a test

@randall @zwoop @SolidWallOfCode

**Comment by SolidWallOfCode** [comment]
I've been looking at this and various options and unfortunately this seems the least worst. We really do not want to create Boost dependencies and I was unable to find any better C++ YAML library.

**Pull request merged**
