### PR TITLE
libswoc: Replace ts::file with swoc::file

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
This is a draft because it requires an update to libswoc.

Gancho added quite a bit of functionality I was unaware of that had to be ported to libswoc.

### CODE REVIEW

**Review by bneradt — APPROVED** [review]
A lot of files, but pretty straightforward.

**Comment by SolidWallOfCode** [comment]
The biggest pain not related to OSX was Gancho implemented `remove_all` but named it `remove`, which is also in `std::filesystem` but does something different (i.e. recursive vs. regular file only). There were many places where `remove` was used to clean a directory, which no longer works. I changed the names for `std::filesystem` compliance. I'm not sure why Gancho used slightly different names.

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest 1of4]

**Comment by bneradt** [comment]
[approve ci cmake]

**Review by bneradt — APPROVED** [review]
Looks straightforward.

**Pull request merged**
