### PR TITLE
QUIC: Clean the inactive timeout in closing and draining state

### PR DESCRIPTION
**Pull request by scw00**
This tries to fix unexpected event in #3160 .

### CODE REVIEW

**Comment by maskit** [comment]
I'm not sure this is an appropriate fix. Can you tell me detail?

**Comment by scw00** [comment]
We will reset the inactive timeout (in _dequeue_recv_packet) when we receive packet. But if we are in closing and draining state, the inactive timeout is useless. It may cause the IMMXXX_EVENT in state_closing_xxxx or state_draining_xxxx.

**Comment by maskit** [comment]
OK, I got your point.

One more question. With this change, only processable packets will update the timer. Shouldn't we update the time if packets were not processable?

**Comment by scw00** [comment]
IMO, we shouldn't handle the packet which can't be processed. Because the attacker may always send the unprocessed packet, and the QVC will never timeout.

But spec says 
>A connection that remains idle for longer than the idle timeout.
It seems we should update the timeout for every packet we received .

**Comment by scw00** [comment]
Now, Updated for every QUIC_EVENT_PACKET_READ_READY event.

**Comment by maskit** [comment]
> Because the attacker may always send the unprocessed packet, and the QVC will never timeout.

I understand your concern but I don't think using inactive timer for the both purpose is a good idea. Because that would hide the reason of closing (everything would look like inactive timeout). I'd suggest another mechanism for security purposes.

**Pull request merged**
