### PR TITLE
Override delete in Extendible

### LINKED ISSUE #5090: ASAN alloc-dealloc-mismatch in Extendible
```
16:03:50 homer:(master)~/dev/apache/trafficserver$ ./src/tscore/test_tscore
=================================================================
==20537==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete) on 0x603000058b40
    #0 0x7fd535367a50 in operator delete(void*, unsigned long) (/lib64/libasan.so.5+0xf2a50)
    #1 0x71663a in ____C_A_T_C_H____T_E_S_T____0 unit_tests/test_Extendible.cc:78
    #2 0x4e801c in Catch::TestInvokerAsFunction::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:10067
    #3 0x4e801c in Catch::TestCase::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9968
    #4 0x4e801c in Catch::RunContext::invokeActiveTestCase() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:8832
    #5 0x5429b2 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:8806
    #6 0x56e679 in Catch::RunContext::runTest(Catch::TestCase const&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:8595
    #7 0x57096a in runTests /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9135
    #8 0x57f299 in Catch::Session::runInternal() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9333
    #9 0x57f54c in Catch::Session::run() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9290
    #10 0x4bfc56 in Catch::Session::run(int, char**) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9258
    #11 0x4bfc56 in Catch::Session::run(int, char**) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9253
    #12 0x4bfc56 in main /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12750
    #13 0x7fd534bf7412 in __libc_start_main (/lib64/libc.so.6+0x24412)
    #14 0x4cef8d in _start (/home/bcall/dev/apache/trafficserver/src/tscore/.libs/lt-test_tscore+0x4cef8d)

0x603000058b40 is located 0 bytes inside of 32-byte region [0x603000058b40,0x603000058b60)
allocated by thread T0 here:
    #0 0x7fd535364848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
    #1 0x7fd535067c75 in ats_malloc /home/bcall/dev/apache/trafficserver/src/tscore/ink_memory.cc:59
    #2 0x7fd535067dbb in ats_memalign /home/bcall/dev/apache/trafficserver/src/tscore/ink_memory.cc:94
    #3 0x7117fa in MT::Extendible<Derived>::operator new(unsigned long) ../../include/tscore/Extendible.h:548
    #4 0x715d51 in ____C_A_T_C_H____T_E_S_T____0 unit_tests/test_Extendible.cc:71
    #5 0x4e801c in Catch::TestInvokerAsFunction::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:10067
    #6 0x4e801c in Catch::TestCase::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9968
    #7 0x4e801c in Catch::RunContext::invokeActiveTestCase() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:8832
    #8 0x5429b2 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:8806
    #9 0x56e679 in Catch::RunContext::runTest(Catch::TestCase const&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:8595
    #10 0x57096a in runTests /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9135
    #11 0x57f299 in Catch::Session::runInternal() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9333
    #12 0x57f54c in Catch::Session::run() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9290
    #13 0x4bfc56 in Catch::Session::run(int, char**) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9258
    #14 0x4bfc56 in Catch::Session::run(int, char**) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:9253
    #15 0x4bfc56 in main /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12750
    #16 0x7fd534bf7412 in __libc_start_main (/lib64/libc.so.6+0x24412)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/lib64/libasan.so.5+0xf2a50) in operator delete(void*, unsigned long)
==20537==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==20537==ABORTING
```

### PR DESCRIPTION
**Pull request by bryancall**
Fixes #5090

### CODE REVIEW

**Comment by bryancall** [comment]
@a-canary can you take a look at this

**Comment by SolidWallOfCode** [comment]
Seems reasonable.

**Comment by a-canary** [comment]
This is fine, but I'd rather merge #4240
(not that I've tested it in asan)

**Comment by bryancall** [comment]
@a-canary I would much rather get this in now so we can start testing with ASAN.

We should have another discussion about Extendible and its viability.  It seems like a lot of work and complexity when you could just have a pointer and set() and get() methods.

@zwoop What are your thoughts?

**Pull request merged**
