### PR TITLE
Add pkg-config fallback to --enable-system-luajit

### PR DESCRIPTION
**Pull request by linnaea**
This addresses issue #1507

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci].

**Comment by shukitchan** [comment]
will find time to review this in the next couple of days

**Comment by shukitchan** [comment]
Try it a couple times with different setup. Looks good. will merge tomorrow.

**Comment by zwoop** [comment]
This might be a candidate for a 7.1.3 backport, please let me know if it's not.

**Comment by shukitchan** [comment]
that's absolutely right! I forgot that. 
@zwoop, this option is somehow missed in 7.1.x

**Comment by zwoop** [comment]
@shukitchan Ah, gotcha. So this is not a candidate as is. If someone cares, they can propose back porting all the necessary changes.

**Pull request merged**
