### PR TITLE
TS-4569: New Coverity issues found in updated scan

### PR DESCRIPTION
**Pull request by bryancall**
Fixed issues: 1356977

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/211/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/317/ for details.

**Comment by zwoop** [comment]
:+1:

**Comment by jpeach** [comment]
👍

**Pull request merged**
