### PR TITLE
Do not change stream state from HALF_CLOSED_REMOTE with CONTINUATION frame

### LINKED ISSUE #5584: Stuck on sending huge response header
ATS is stuck on sending over 16KB response header on HTTP/2 connection. It looks like sending CONTINUATION frame makes the HTTP/2 stream state closed.

```
[May 28 14:27:29.829] {0x70000127a000} DEBUG: <Http2ConnectionState.cc:1517 (send_headers_frame)> (http2_con) [0] [1] Send HEADERS frame
[May 28 14:27:29.833] {0x70000127a000} DEBUG: <Http2ConnectionState.cc:1573 (send_headers_frame)> (http2_con) [0] [1] Send CONTINUATION frame
[May 28 14:27:29.833] {0x70000127a000} DEBUG: <Http2ConnectionState.cc:1482 (send_data_frames)> (http2_con) [0] [1] Shutdown half closed local stream
```

### PR DESCRIPTION
**Pull request by masaori335**
Fix #5584. This should be backported to 7.1.x and 8.0.x.

~~Marking draft PR while working with autest.~~

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
The http2 autest core dumped.

**Comment by masaori335** [comment]
@shinrich Right. It's #5587.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
This is ready for review, the autest crash is fixed.

**Comment by maskit** [comment]
Looks good to me. Did you run h2spec?

**Comment by masaori335** [comment]
I got same result to h2spec against to latest master. Some tests for section 6 are failed and should be fixed, but these are not related to this change.

-  h2spec: 2.3.0
- master: e18bb8b26ea3e130f874407b96cb22bea938dc43

**Pull request merged**
