### PR TITLE
fix: memory leak when using modsecurity

### PR DESCRIPTION
**Pull request by bxlxx**

### CODE REVIEW

**Review by shukitchan — APPROVED** [review]

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
[approve ci]

**Comment by shukitchan** [comment]
@bxlxx can you pls fix the format error ?

**Comment by bxlxx** [comment]
image

It doesn't seem like the format error.

**Comment by bxlxx** [comment]
I modified the Lua code, but I don't know why there is a clang-format error.

**Comment by shukitchan** [comment]
There is a trailing white space somewhere. 

here is the error message

```
example/plugins/lua-api/modsecurity/ats-luajit-modsecurity.lua:    
+ '[' 1 '!=' 0 ']'
+ echo 'Error: Trailing whitespaces are not allowed!'
Error: Trailing whitespaces are not allowed!
+ echo 'Error: Please run: git grep -IE '\'' +$'\'''
Error: Please run: git grep -IE ' +$'

```

**Pull request merged**
