### PR TITLE
TS-5011: Fixes memory leak in CLFUS compression

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1103/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/995/ for details.

**Comment by SolidWallOfCode** [comment]
It looks OK. I really do think we should do a more thorough fix, such as with `std::unique_ptr` or `ats_scoped_str` or even using `_alloca`.

**Comment by zwoop** [comment]
@SolidWallOfCode I agree, file a lira :).

**Pull request merged**
