### PR TITLE
Updating to Proxy Verifier v2.0.0

### PR DESCRIPTION
**Pull request by bneradt**
We will want to use Proxy Verifier v2.0.0 for it's delayed transaction
and HTTP/2 to server capabilities. This updates the AuTest extensions to
properly handle the new version.

### CODE REVIEW

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
I can't set the verbosity level to "info" anymore?

**Comment by SolidWallOfCode** [comment]
Is there a way to not have the PV version explicitly defined in different files?

**Comment by bneradt** [comment]
> I can't set the verbosity level to "info" anymore?

You can. "info" will be what the user gets if they pass `verbose=False`. Currently all tests want debug, and that will almost certainly be the case for the majority of tests moving forward. If an arbitrary level is desired, they can combine `verbose=False` and `other_args="--verbose <level>"`.

The interface in this PR makes the common debug case easy (it's the default) and the rarer case in which just info is wanted easy. The extremely rare case where an arbitrary level is desired (not sure why we'd ever want that in an autest) is also possible.

**Review by SolidWallOfCode — APPROVED** [review]

**Review by randall — APPROVED** [review]

**Comment by bneradt** [comment]
> Is there a way to not have the PV version explicitly defined in different files?

Yes, good point. I'll create a `tests/proxy-verifier-version.txt` file with the version and use that in the `prepare_proxy_verifier.sh`, in the `setup.cli.ext` extension, and in the `ci/jenkins/bin/autest.sh` script.

**Review by randall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

I also had to include all changes from master in ci/jenkins/bin, because it got maddening with merge conflicts.

**Pull request merged**
