### PR TITLE
TS-4697: Free MIOBuffer if the ipallow check fails. (backport for 6.2.x)

### PR DESCRIPTION
**Pull request by oknet**
(cherry picked from commit 40b7b484869c1876d7f82953828524c393e650ca)

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1179/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1072/ for details.

**Comment by PSUdaemon** [comment]
When you do the backports can you leave the commit messages the same except for the cherry pick comment and the conflicts?

**Comment by oknet** [comment]
Do you means “This closes #823.“ ？

2016-11-06 12:27 GMT+08:00 Phil Sorber <notifications@github.com>:

**Comment by PSUdaemon** [comment]
I mean don't add `(backport for 6.2.x)` to the existing commit message. It's superfluous.

**Comment by oknet** [comment]
@PSUdaemon I'm just leave the same commit message and the change log only for 6.2.x branch. please check the new commit message, please leave you advice, thanks.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1076/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1183/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1184/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1077/ for details.

**Pull request merged**
