### PR TITLE
CLEANUP:  change URL.cc to use BufferWriter.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by zwoop** [comment]
Pretty sure we shouldn't do this, we don't want to "throw" in our code afaik, ever.

**Comment by SolidWallOfCode** [comment]
Yes, `throw` is not currently valid in the project. I'm not sure much is gained from it here, the logic could just as easily check the capacity vs. the amount of memory rather than using `throw`/`catch`.

**Comment by ywkaras** [comment]
./lib/wccp/WccpMsg.cc:    throw ts::Exception(BUFFER_TOO_SMALL_FOR_COMP_TEXT);
./lib/ts/string_view.h:      throw std::out_of_range("invalid string_view position");

**Comment by ywkaras** [comment]
Quote from my code comments:
"The purpose of this utility is to help with transitioning to the use of MIOBufferWriters, rather than writing to MIOBuffers directly. Eventually, there should be little or no use of it."

Here is a sample of current code, from Http2Stream.cc:
```
  int dumpoffset = 0;
  int done, tmp;
  IOBufferBlock *block;
  do {
    bufindex = 0;
    tmp      = dumpoffset;
    block    = request_buffer.get_current_block();
    if (!block) {
      request_buffer.add_block();
      block = request_buffer.get_current_block();
    }
    done = _req_header.print(block->start(), block->write_avail(), &bufindex, &tmp);
    dumpoffset += bufindex;
    request_buffer.fill(bufindex);
    if (!done) {
      request_buffer.add_block();
    }
  } while (!done);
```
Do you consider this to be "easily checking"?

This is what I am working to change to:
```
MIOBufferWriter bw(request_buffer);
_req_header.print(bw);
```

What is the reason to prohibit exceptions in all cases?  In most cases, if preferred, we can probably use setjmp()/longjmp() instead of exceptions for this purpose.  I haven't seen a case where there are real destructor calls that need to be made in the stack unwind.  I realize that TS is not exception-safe generally, but in this case, it's not hard to evaluate the stack frames that will be unwound to ensure exception (or setjmp()/longjmp()) safety.

**Comment by ywkaras** [comment]
http://www.worldoflongmire.com/features/apes/planet5/PAPERWAD.JPG

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
This issue, https://github.com/apache/trafficserver/issues/2743 , argues in favor of switching from exceptions to setjmp() / longjmp().  But, if this is irredeemably outside the bounds of Ape Law, no point in investing more effort in it.

**Comment by ywkaras** [comment]
Closing to remove clutter from open PR list.

**Pull request closed without merging**
