### PR TITLE
Make ms options for outbound timeouts and remove redundant API

### PR DESCRIPTION
**Pull request by shinrich**
Resurrecting and extending PR #4130 to address issue #5810.

@shukitchan ran into a bug were the timeout set by the TSHttpTxnNoActivityTimeoutSet was not being honored.  Currently there are parallel data structures to track these timeouts, and for the inactivity timeout in particular the version set by the TSHttpTxn\*TimeoutSet is not used in many places.  Getting rid of the parallel data structure seemed best, and since the relevant timeouts are overridable just moving to TSHttpTxnConfigIntSet seemed like a good solution.  However, @shukitchan needed to be able to specify sub-second timeouts in some cases which is provided by the TSHttpTxn*TimeoutSet APIs.

So we revisited PR #4130 where @ezelkow1 worked out a way to have a millisecond name for a records.config entry that feeds into the same transaction variable as the regular version.  I took his PR and added the active and inactivity timeous, removed the TSHttpTxn*TimeoutSet API's and updated them with TSHttpTxnConfigIntSet where necessary.

### CODE REVIEW

**Comment by bryancall** [comment]
What is the use case for sub-second timeouts?  Having redundant configuration options, one for seconds and one for ms, and understanding what one takes precedence seems like it would be confusing for end users.

**Comment by zwoop** [comment]
I'm pretty -1 on this as well.  IF we really need such fine granularity, let's change the existing configurations and APIs to all be in milliSeconds. Having this duplication is really damn confusing (like, which takes precedence etc.). yes, it's incompatible, but avoid living with complexity and confusion for the foreseeable future.

**Comment by randall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Another option is to change the existing configs to float. 

Or, unless this urgent, postpone this until we have records.yaml and can have semantic values easier , e.g “1500ms” (I.e let yaml deal with parsing).

The option of turning the existing configs into strings is less appealing,   because of overridable configs.

**Comment by shukitchan** [comment]
> What is the use case for sub-second timeouts? 

We have some internal requests made through TSFetchUrl or TSConnect and we have been using those TSHttpTxn*TimeoutSet APIs to lower the timouts to subsecond or have a finer-grained values. (e.g. 1.5 seconds)

**Comment by shinrich** [comment]
Agreed with a more expressive alternatively for records.config could solve this better.  Put up PR $5814 with a more immediate fix to the problem that @shukitchan ran into.

**Comment by bryancall** [comment]
@zwoop Floats seems like a good idea for the current records.config and we can move to something better when we have YAML (1s or 1500ms, and maybe 1.5s).

From reading the documentation on Envoy they have the notion of a "Duration" were you can use 1s or 1000ms.  I don't know if they allow decimal points too or not.

**Comment by shinrich** [comment]
Closing this in preference to short term fix in PR #5816.  Can return to this issue post 9.x branch to come to a more agreeable solution on the varying setting resolution problem.

**Pull request closed without merging**
