### PR TITLE
Delete .gitmodules

### PR DESCRIPTION
**Pull request by danobi**
The file is empty so I don't think we need it.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
This fails on linux for some reason, with 

```
PASS: test_Event
../../build/_aux/test-driver: line 114: test_Event.trs: No such file or directory
../../build/_aux/test-driver: line 115: test_Event.trs: No such file or directory
../../build/_aux/test-driver: line 116: test_Event.trs: No such file or directory
../../build/_aux/test-driver: line 117: test_Event.trs: No such file or directory
make[4]: *** [test_Event.log] Error 1
```

**Comment by zwoop** [comment]
[approve ci]

**Comment by danobi** [comment]
[approve ci]

**Pull request merged**
