### PR TITLE
TS-4115:  add multi  origin feature to parent selection.

### PR DESCRIPTION
**Pull request by jrushf1239k**
Updates to parent selection for multi origin features.

### CODE REVIEW

**Comment by jpeach** [comment]
It's better to rebase your branch than to merge master into it. Rebating keeps the history cleaner and makes it easier to see what happened on a branch.

**Comment by jpeach** [comment]
> Actually you can have simple retry and dead server retry enabled at the same time

Sure, but not in the same transaction. The transaction override would be to set the policy. For example, it is not obvious to an operator what the behavior should be if *both* policies were enabled at the same time. If there is a single configuration setting this situation cannot arise.

> The parsing of the response code string is because all the settings are overridable by delivery service.

Sure, but in the common case, the settings can be parsed once and reused for many transactions. You don't even need to parse them in the context of the HTTP transaction, you can do the parsing in the configuration override API.

**Comment by jpeach** [comment]
Thanks @jrushf1239k, I'll review over the weekend.

**Comment by bryancall** [comment]
Talking at the github meeting.  The consensus is that we should split the pull request into two pull requests.  One for multi origin and the other for retry logic.

We should also have the configuration in parent.config instead of records.config.

**Comment by jrushf1239k** [comment]
Submitting another pull request with only changes for multi-site origin.

**Pull request closed without merging**
