### PR TITLE
TS-4995: Consolidate C++ API example plugins.

### PR DESCRIPTION
**Pull request by jpeach**
Move all the C++ example plugins into the 'example' directory so
that there is only one place to look for plugin examples.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1066/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/958/ for details.

**Comment by bryancall** [comment]
👍  - I think this is a better location

**Comment by bgaff** [comment]
Sounds good to me

**Pull request merged**
