### PR TITLE
7.1.x Avoid sending duplicate push promise on same client session 

### PR DESCRIPTION
**Pull request by maskit**
Backporting #2330 and a following fix #2553.

### CODE REVIEW

**Comment by zwoop** [comment]
Looks like clang-format issues :-)

**Comment by maskit** [comment]
[approve ci clang-format]

**Comment by maskit** [comment]
@zwoop I made a separated commit to fix clang-format issue because it seems like it was made by some other cherry-picks (the two commits doesn't touch the unformatted file).

**Comment by zwoop** [comment]
It could have been because 8.0 and 7.x uses different versions of clang-format itself.

**Pull request merged**
