### PR TITLE
Upgrade yaml-cpp version to 0.8.0

### PR DESCRIPTION
**Pull request by lzx404243**
Currently we are using `yaml-cpp` version 0.7.0. This PR bumps our `yaml-cpp` version to the just-released `0.8.0`. Specifically, the following changes are made
* Fixed the pre-commit hook to properly ignore yaml-cpp source files for formatting check
* Updated `lib/yamlcpp` source to 0.8.0
* Updated yaml version in the jsonrpc test and documentation

### CODE REVIEW

**Comment by bneradt** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Review by bneradt — COMMENTED** [review]
Looks good to me. Thanks for working on this @lzx404243 . I'll let a non-Yahoo committer approve.

**Review by randall — APPROVED** [review]

**Pull request merged**
