### PR TITLE
cmake: Install include files

### PR DESCRIPTION
**Pull request by cmcfarlen**
This installs the include files based on what is installed from autotools.

I moved the install target for libswoc into libswoc's CMakeLists.txt.  That file has deviated from libswoc upstream substantially, so I also ran cmake-format on it.

There doesn't seem to be consensus on the best way to setup header files for installation, so I just picked one that wasn't overly complicated.  The bare minimum is to set a PUBLIC_HEADER property on the target and then specify a destination for the same on the install target.  There is a target_include_directories component, but it has more to do with exporting cmake scripts for other projects to consume.  That task will be a different PR so that aspect will likely need adjustment.

Edit: I added `tscpp/api` as well

### CODE REVIEW

**Comment by cmcfarlen** [comment]
[approve ci ubuntu]

**Comment by bneradt** [comment]
[approve ci fedora autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Review by JosiahWI — CHANGES_REQUESTED** [review]
Could we use `PROJECT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR`? I don't think it's all that likely that ATS won't be the top-level project, but I'm kind of paranoid about it.

**Review by bneradt — APPROVED** [review]

**Pull request merged**
