### PR TITLE
Make proxy.config.http.request_buffer_enabled configurable and bug fix

### PR DESCRIPTION
**Pull request by zizhong**
This PR fixes issue #6021, #6022, #6023

### CODE REVIEW

**Comment by jvgutierrez** [comment]
I can confirm that #6022 is fixed, but I'm still seeing a non desired behaviour when `proxy.config.http.request_buffer_enabled` is set to 1. Aborted requests are no longer being logged in the slow log, this is reproducible with these requests:
```
# http/1.1
timeout 5 curl --http1.1 -X POST -d "test" -H "Content-Length: 10" http://127.0.0.1:3128/post
# http/2
curl -X POST -d "test" -H "Content-Length: 10" http://127.0.0.1:3128/post
```

**Comment by maskit** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Pull request merged**
