### PR TITLE
Remove unused assignment to satisfy clang-analyzer

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
Original clang-analzyer report at https://ci.trafficserver.apache.org/clang-analyzer/github/5774/2019-08-09-070811-23489-1/

**Comment by bryancall** [comment]
Seeing the issue on master too:
https://ci.trafficserver.apache.org/clang-analyzer/master/2019-08-09-094933-32000-1/

**Pull request merged**
