### PR TITLE
Fixes padding byte being part of the POST/PUT data

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
Intel CC build *failed*! https://ci.trafficserver.apache.org/job/icc-github/344/

**Comment by zwoop** [comment]
This issue was initially identified and diagnosed by Andreas G.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/219/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/233/

**Comment by atsci** [comment]
FreeBSD11 build *failed*! https://ci.trafficserver.apache.org/job/freebsd-github/1914/

**Comment by atsci** [comment]
Linux build *failed*! https://ci.trafficserver.apache.org/job/linux-github/1806/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/477/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/215/

**Comment by zwoop** [comment]
CI is in shambles, [approve ci]

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/220/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/234/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1915/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/216/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1807/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/345/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/478/

**Comment by bryancall** [comment]
Test php script:
```
[bcall@homer html]$ cat post.php
<?php
$tmp_name = $_FILES["shit"]["tmp_name"];
$name = $_FILES["shit"]["name"];
$rval = move_uploaded_file($tmp_name, "data/$name");
if ($rval == 1) {
  echo "It worked!\n";
}
?>
```

Verify the setup is good:
```
[bcall@homer html]$ md5sum index.html
564b50f6204554e57d5805795586f319  index.html
[bcall@homer html]$ nghttp -d index.html https://127.0.0.1:4443/post_md5.php
MD5 Hash: 564b50f6204554e57d5805795586f319
Body Length: 531

```
Without patch:
```
[bcall@homer html]$ nghttp -b 11 -d index.html https://127.0.0.1:4443/post_md5.php
MD5 Hash: b7cad6be2aba6342ed640d8cf96b97c3
Body Length: 531
```

With the patch:
```
[bcall@homer html]$ nghttp -b 11 -d index.html https://127.0.0.1:4443/post_md5.php
MD5 Hash: 564b50f6204554e57d5805795586f319
Body Length: 531
```

**Pull request merged**
