### PR TITLE
Expanding the cases where the server_entry gets cleared on error.

### PR DESCRIPTION
**Pull request by shinrich**
Trying to address crashes identified in issue #2996

### CODE REVIEW

**Comment by shinrich** [comment]
Hmm.  Based on our early testing, it looks like we are clearing the server_session too soon for the inactive_timeout case.  The retry_logic wants to reach through the server_session to determine whether any bytes were delivered.

**Comment by scw00** [comment]
I think it is better than my fix.

Add more detail

It is also impact the normal write logic if timeout happened. 
For example:  If we got a timeout event from server side, and decide to writing an internal error msg to client. We will call do_io_write to write the msg. But we don't clean up the server entry until the sm finished. That means if server send something again, we will return to `state_read_server_response` and got last crash in #2996 .

**Comment by ezelkow1** [comment]
So do you two think we should just be using this fix only? Or is it good to have this +https://github.com/apache/trafficserver/pull/3031

**Comment by scw00** [comment]
Just this one Please!

**Comment by ezelkow1** [comment]
Posted update in https://github.com/apache/trafficserver/issues/2996

We still got a crash, although slightly different this time

**Comment by shinrich** [comment]
Yes, we are still getting crashes as well.  So I don't think this one is quite right.  Closing for now.

**Comment by shinrich** [comment]
Updated the fix by only cleaning up the server_entry and server_session in the CONNECTION_ERROR case.  This should avoid the crash we were seeing referenced in the issue.  

Still need to check in our environment.

**Comment by shinrich** [comment]
Based on the discussion in the associated issue,  I made another update on the PR.  Make the server_entry cleanup broad again and reworked the test in is_retryable to be ok if the server_session has been cleared.

**Comment by zwoop** [comment]
Cherry-picked to 7.1.x

**Comment by zwoop** [comment]
I've reverted this from 7.1.x, since we were seeing a rare crasher with it.

**Pull request merged**
