### PR TITLE
autoconf: Add lib flags for the quiche build test.

### PR DESCRIPTION
**Pull request by brbzull0**
More likely we need this to get the test build passing and have quiche properly detected.

### CODE REVIEW

**Comment by maskit** [comment]
I faced the issue on one of my boxes, and forgot to fix it. I think I did the same thing at that time and it worked, but don't we have two `-lssl -lcrypto` as the final `LIBS` output (i.e. ones from quiche.m4 and ones from crypto.m4)?

**Comment by brbzull0** [comment]
> I faced the issue on one of my boxes, and forgot to fix it. I think I did the same thing at that time and it worked, but don't we have two `-lssl -lcrypto` as the final `LIBS` output (i.e. ones from quiche.m4 and ones from crypto.m4)?

That I don't know, with this we end up with a line like this:
`config.log`
```
configure:23648: checking for quiche_connect in -lquiche
configure:23673: cc -o conftest  -D_GNU_SOURCE -I/opt/boringssl/include -DOPENSSL_NO_SSL_INTERN -I/opt/quiche/include -L/opt/boringssl/lib -L/opt/quiche/lib conftest.c -lquiche  -lpthread -ldl  -lquiche -lssl -lcrypto >&5
```
so `-lquiche  -lpthread -ldl  -lquiche -lssl -lcrypto`, I can probably remove the first quiche flag from `quiche_test_libs` which will be added after anyway.
```
... conftest.c -lquiche  -lpthread -ldl  -lssl -lcrypto 
```

**Comment by maskit** [comment]
Not a big deal, but with this change I see this (look at the last part).
> /bin/sh ../libtool  --tag=CXX   --mode=link ccache c++ -std=c++17 -g -pipe -Wall -Qunused-arguments -Wextra -Wno-unused-parameter -Werror -Wno-invalid-offsetof -fno-omit-frame-pointer -fsanitize=address  -R/Users/mkitajo/opt/boringssl/lib -R/opt/homebrew/Cellar/pcre/8.45/lib -R/Users/mkitajo/opt/quiche/lib -L/Users/mkitajo/src/github.com/trafficserver/lib/swoc -L/Users/mkitajo/opt/boringssl/lib -L/opt/homebrew/Cellar/pcre/8.45/lib -L/Users/mkitajo/opt/quiche/lib -o traffic_cache_tool/traffic_cache_tool traffic_cache_tool/traffic_cache_tool-CacheDefs.o traffic_cache_tool/traffic_cache_tool-CacheTool.o traffic_cache_tool/traffic_cache_tool-CacheScan.o ../src/tscore/.libs/ArgParser.o ../src/tscore/.libs/ink_assert.o ../src/tscore/.libs/ink_error.o ../src/tscore/.libs/ink_file.o ../src/tscore/.libs/ink_memory.o ../src/tscore/.libs/ink_mutex.o ../src/tscore/.libs/ink_string.o ../src/tscore/.libs/BufferWriterFormat.o ../src/tscore/.libs/InkErrno.o ../src/tscore/.libs/Errata.o ../src/tscpp/util/.libs/TextView.o ../src/tscore/.libs/Regex.o ../src/tscore/.libs/CryptoHash.o ../src/tscore/.libs/MMH.o ../src/tscore/.libs/Version.o ../src/tscore/.libs/Regression.o ../src/tscore/.libs/ink_args.o ../src/tscore/.libs/ParseRules.o ../src/tscore/.libs/SourceLocation.o -ltsswoc -lssl -lcrypto -lpcre -lquiche -lssl -lcrypto

**Comment by brbzull0** [comment]
> Not a big deal, but with this change I see this (look at the last part).
> 
> > /bin/sh ../libtool  --tag=CXX   --mode=link ccache c++ -std=c++17 -g -pipe -Wall -Qunused-arguments -Wextra -Wno-unused-parameter -Werror -Wno-invalid-offsetof -fno-omit-frame-pointer -fsanitize=address  -R/Users/mkitajo/opt/boringssl/lib -R/opt/homebrew/Cellar/pcre/8.45/lib -R/Users/mkitajo/opt/quiche/lib -L/Users/mkitajo/src/github.com/trafficserver/lib/swoc -L/Users/mkitajo/opt/boringssl/lib -L/opt/homebrew/Cellar/pcre/8.45/lib -L/Users/mkitajo/opt/quiche/lib -o traffic_cache_tool/traffic_cache_tool traffic_cache_tool/traffic_cache_tool-CacheDefs.o traffic_cache_tool/traffic_cache_tool-CacheTool.o traffic_cache_tool/traffic_cache_tool-CacheScan.o ../src/tscore/.libs/ArgParser.o ../src/tscore/.libs/ink_assert.o ../src/tscore/.libs/ink_error.o ../src/tscore/.libs/ink_file.o ../src/tscore/.libs/ink_memory.o ../src/tscore/.libs/ink_mutex.o ../src/tscore/.libs/ink_string.o ../src/tscore/.libs/BufferWriterFormat.o ../src/tscore/.libs/InkErrno.o ../src/tscore/.libs/Errata.o ../src/tscpp/util/.libs/TextView.o ../src/tscore/.libs/Regex.o ../src/tscore/.libs/CryptoHash.o ../src/tscore/.libs/MMH.o ../src/tscore/.libs/Version.o ../src/tscore/.libs/Regression.o ../src/tscore/.libs/ink_args.o ../src/tscore/.libs/ParseRules.o ../src/tscore/.libs/SourceLocation.o -ltsswoc -lssl -lcrypto -lpcre -lquiche -lssl -lcrypto

I fixed this.  I was wrong adding the flags to `LIBS` which will be used everywhere. Now should be fine.


[Docs](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Libraries.html) always help :P 

```
AC_CHECK_LIB (library, function, [action-if-found], [action-if-not-found], [other-libraries])
... 
The other-libraries argument should be limited to cases where it is desirable to
test for one library in the presence of another that is not already in LIBS.
```
Better not pullulate the `LIBS` as we also have `QUICHE_LIB` and `OPENSSL_LIBS` for this needs.

**Comment by brbzull0** [comment]
[approve ci rocky]

**Comment by brbzull0** [comment]
I'll add an update here.

To get this working and have libquiche.so linked with the right Borinssl library you have to ad the bss lib path to the `LD_LIBRARY_PATH`  as it seems quiche is not including the rpath into the lib info. 
Trying to figure this out and make some fixes somewhere.

**Comment by bneradt** [comment]
[approve ci]

**Review by maskit — APPROVED** [review]

**Pull request merged**
