### PR TITLE
Fix #7164 Changing Warning to Debug and creating a stat

### LINKED ISSUE #7164: Warning in HostDBContinuation::set_check_pending_dns
This should be changed to Debug and possibly create a stat around this.  Make updates to the PR #7117

### PR DESCRIPTION
**Pull request by zizhong**
This closes #7166

### CODE REVIEW

**Review by sudheerv — COMMENTED** [review]
The stat name seems too long. I'm not good at naming myself so can't suggest a better name, but perhaps, can we make it shorter pls :) ?

**Comment by zizhong** [comment]
@sudheerv Looking it closer, I found I included the hostdb prefix in the stat name. Fixed in the latest change.

**Comment by sudheerv** [comment]
> @sudheerv Looking it closer, I found I included the hostdb prefix in the stat name. Fixed in the latest change.

LGTM 👍 

I’ll let @zwoop @bryancall review/approve (non LI) :)

**Review by zwoop — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
