### PR TITLE
chore: refactored InkAPIPrivateIOCore.h

### PR DESCRIPTION
**Pull request by shikharvashistha**
This commit refactors the header to remove API's mentioned in #6245

Signed-off-by: Shikhar Vashistha <51105234+shikharvashistha@users.noreply.github.com>

Duplicate #8993

### CODE REVIEW

**Comment by bryancall** [comment]
@shikharvashistha Can you please send an email to dev@traffficserver.apache.org asking if anyone is using these APIs.  Also, if we are going to remove this APIs we should also remove the definitions of the functions.

**Comment by shikharvashistha** [comment]
> @shikharvashistha Can you please send an email to [dev@traffficserver.apache.org](mailto:dev@traffficserver.apache.org) asking if anyone is using these APIs. Also, if we are going to remove this APIs we should also remove the definitions of the functions.

I'm subscribed to mailing list but still getting address not found, what could be the issue

**Comment by bneradt** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci autest]

**Pull request closed without merging**
