### PR TITLE
edits to remove compiler warnings/errors for the osx build

### PR DESCRIPTION
**Pull request by traeak**
Fixes for warnings/errors generated by the osx compiler during a CI build.

### CODE REVIEW

**Review by SolidWallOfCode — APPROVED** [review]
I wonder what `disk_full` used to do. I suspect it was checked at some point.

**Comment by SolidWallOfCode** [comment]
Hmmm, something weird with the build, I'll see what I can find out.

**Comment by SolidWallOfCode** [comment]
This is build in 9.1.x which has some compiler issues with newer compilers due to increasing strictness. In this case you need to add
```
#include <cstdint>
```
to "src/tscpp/util/TextView.h"

There may be other compiler issues, @bneradt can provide more details.

**Comment by bryancall** [comment]
@traeak We are not going to be doing anymore 9.1.x releases.  Do you need this change on the 9.1.x branch for any reason?

**Pull request closed without merging**
