### PR TITLE
Make parent proxy per parent connect attempts and connect attempts timeout overridable.

### PR DESCRIPTION
**Pull request by jrushford**
Make "proxy.config.http.parent_proxy.per_parent_connect_attempts" and "proxy.config.http.parent_proxy.connect_attempts_timeout" overridable per remap.

Having these configuration variables overridable per remap has proven helpful with tuning abr video delivery.

### CODE REVIEW

**Comment by vmamidi** [comment]
I am okay with this code change but, I think these variables should be carefully used as it may lead to undesirable results as ATS connect time is "first-byte" time, as a result,   proxy.config.http.parent_proxy.connect_attempts_timeout will be based on origin server behavior, not the parent itself. so, proxy.config.http.parent_proxy.fail_threshold is counted differently by two properties if they have two different timeouts as proxy.config.http.parent_proxy.fail_threshold is not overridable. @zwoop @mlibbey do you have any comment on this?

**Comment by jrushford** [comment]
@vmamidi I understand your concern but we think it's valuable to change this parameter on a per remap because one global config doesn't fit all situations.  Since you mention proxy.config.http.parent_proxy.fail_threshold, we override that too along with proxy.config.http.parent_proxy.retry_time.  i am working on a pr for both of those to.

**Comment by jrushford** [comment]
@vmamidi, @zwoop, @mlibbey are you ok with making these overridable?

**Comment by vmamidi** [comment]
@jrushford I do agree that making these variables overridable is useful. I thought that whoever is using the variables should be aware of the impact on the overriding the variables on proxy.config.http.parent_proxy.fail_threshold.  I am not sure how we can easily override proxy.config.http.parent_proxy.fail_threshold? where are we going to store the per remap based failures per parent?

**Comment by jrushford** [comment]
@vmamidi per our conversation, i updated this pr to include overriding proxy.config.http.parent_proxy.fail_threshold and proxy.config.http.parent_proxy.retry_time.

**Comment by bryancall** [comment]
@vmamidi Please review.

**Comment by zwoop** [comment]
[approve ci docs]

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
@vmamidi I squashed the three commits and github removed your approval of this pr.  Could you re-review/approve.  thanks

**Comment by jrushford** [comment]
[approve ci]

**Comment by zwoop** [comment]
This does not cherry-pick cleanly into 7.1.0. If we want this for 7.1.0, please make a new PR against 7.1.x branch and reference to it from here as well please.

**Comment by jrushford** [comment]
Oh no, I’ll take a look.  Thanks zwoop


Thanks
--
John J. Rushford

**Comment by jrushford** [comment]
@zwoop Please have a look at this backport pr for 7.1.x,   https://github.com/apache/trafficserver/pull/2193

Thanks
--
John J. Rushford
jrushford@apache.org

**Pull request merged**
