### PR TITLE
Log IP address in case servername is not present

### PR DESCRIPTION
**Pull request by persiaAziz**
needs to be backported to 7.1

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
This looks like a real failure in AUTest. You need to run it locally to see or try rebasing to master.

**Comment by persiaAziz** [comment]
[approve ci autest]

**Comment by persiaAziz** [comment]
It passed this time.. :/

**Pull request merged**
