### PR TITLE
Allow transparent pass through for SSL port

### PR DESCRIPTION
**Pull request by stipa**
If the parsing of ClientHello fails and first byte does not indicate SSL
packet, start a blind tunnel if tr-pass is set.

This feature allows to blind-tunnel non-SSL traffic and use SNI hook for
SSL traffic.

### CODE REVIEW

**Comment by shinrich** [comment]
Looks good to me. Originally concerned that the transparent_passthrough state was being needlessly duplicated, but the HttpSM is not here yet at this point.  And you are following the pattern of the HttpSessionAccept.  One minor nit, is that I would "and" in port.m_inbound_transparent_p when setting the transparent allowed flag in SSLNextProtocolAccept.  It is just a bit of extra error checking.  If the connection is not at least inbound transparent, transparent passthrough makes no sense.  This is checked via the HttpSM method is_transparent_passthrough_allowed on the Http path.

The check for the CLIENT_HELLO handshake operator in the SSL error case seems fine.  You may get unlucky and have non SSL traffic with a first byte of 0x16, and not blind tunnel it.  But checking for more bytes gets complicated (e.g. checking that the next byte is not any valid SSL version).  In practice the simple check is likely fine, and it is highly unlikely that you will suck in legitimate SSL handshake exchanges into the blind tunnel.

I'm going to take it for a spin on my dev box, and then merge it up.

**Comment by sudheerv** [comment]
Isn't there a "NetVConnection::is_transparent" already in the netvc?

**Comment by stipa** [comment]
shinrich: added check you've mentioned

sudheerv: right, but that one is about inbound transparency:
https://github.com/apache/trafficserver/blob/master/iocore/net/UnixNetAccept.cc#L124

**Comment by sudheerv** [comment]
hmm, can it not be used as a bit-map for other kinds of transparency?

**Comment by shinrich** [comment]
As it turns, out the records.config processing already checks that tr-in is set if you are trying to set tr-pass.  

I filled TS-3293 to track the issue of cleaning up the propagation for flags through various accept and netvc.  Will pull Lev's latest patch, and get it merged up.

**Pull request closed without merging**
