### PR TITLE
Backport PR3069

### PR DESCRIPTION
**Pull request by duke8253**
Backporting PR #3069 to 7.1.x

### CODE REVIEW

**Comment by bryancall** [comment]
If you are going to create a PR to add something into the 7.1.x branch.  Please do a cherry-pick with -x.

**Comment by zwoop** [comment]
Hmmm, was this done with a "git cherry-picks -x"? It doesn't seem like it is, so please redo this, using the pattern of

1. Make a branch off 7.1.x
2. git cherry-pick -x ...
3. Fix merge conflicts, and commit
4. Push to GitHub
5. Make a PR.

**Comment by duke8253** [comment]
I thought @zwoop  said it won't cherry pick cleaning back to 7.1.x, so I just did it this way?

**Comment by bryancall** [comment]
You can cherry-pick -x and then fix the conflict

**Comment by duke8253** [comment]
k, will do.

**Pull request closed without merging**
