### PR TITLE
Remove HAVE_POSIX_MEMALIGN related code

### PR DESCRIPTION
**Pull request by duke8253**
Clean up unnecessary code related to HAVE_POSIX_MEMALIGN #3151.

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci]

**Comment by shinrich** [comment]
[approve ci]

**Comment by shinrich** [comment]
I see the "Unused direct dependencies" failure on my Rhel 6 build without this memalign change too.

```
[shinrich@spellhotel os-trafficserver]$ tools/check-unused-dependencies cmd/traffic_layout/traffic_layout
cmd/traffic_cop/traffic_cop
Unused direct dependencies:
	
cmd/traffic_crashlog/traffic_crashlog
Unused direct dependencies:
	
cmd/traffic_ctl/traffic_ctl
Unused direct dependencies:
	
cmd/traffic_layout/traffic_layout
Unused direct dependencies:
	
cmd/traffic_manager/traffic_manager
Unused direct dependencies:
	
cmd/traffic_top/traffic_top
Unused direct dependencies:
	
cmd/traffic_via/traffic_via
Unused direct dependencies:
	
proxy/traffic_server
Unused direct dependencies:
	
proxy/traffic_logcat
Unused direct dependencies:
	
proxy/traffic_logstats
Unused direct dependencies:
	
tools/jtest/jtest
Unused direct dependencies:
	
tools/http_load/http_load
Unused direct dependencies:
```

**Comment by zwoop** [comment]
Yeh, but it didn't fail :-/.

**Comment by zwoop** [comment]
[approve ci debian]

**Comment by zwoop** [comment]
[approve ci debian]

**Comment by zwoop** [comment]
Is this really critical to have in 7.1.x? @bryancall  ?

**Comment by bryancall** [comment]
@zwoop It looks like a code cleanup issue.  It is not necessary

**Comment by zwoop** [comment]
Ok, I yield, cherry-picked to 7.1.x

**Pull request merged**
