### PR TITLE
client cert should be added to netvcoptions only when needed

### PR DESCRIPTION
**Pull request by persiaAziz**
backport to 7.1.x

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1625/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1520/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/58/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/190/ for details.

**Comment by zwoop** [comment]
Not sure I follow here, does this land on master? Or was the intent here to make a backport PR against 7.1.x branch?

**Comment by shinrich** [comment]
Something that should be considered moving forward is how (or whether) server session sharing needs to be augmented to take the client cert requirements into account.

**Comment by zwoop** [comment]
What's the word on this PR? 1) Should we land it? 2) Do we still want this to 7.1.x? Note sure why it's been sitting for so long.

**Comment by persiaAziz** [comment]
7.1.x has good amount of works on client certs, so yes this should go in 7.1.x too :) . Like I said, it is unnecessary to check for client cert in the remap function when the cert is only needed when ATS actually creates an HTTPS connection with the origin

**Pull request merged**
