### PR TITLE
issue #1399 add code of tcp_congestion_control erased by TS-3612

### PR DESCRIPTION
**Pull request by shenzhang920**
this pull request change is on master branch

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1488/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1381/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/52/ for details.

**Comment by zwoop** [comment]
@maskit should we backport this to 7.1.0 ?

**Comment by maskit** [comment]
@zwoop Yes, we should. I wrote the reason on #1399.

**Comment by zwoop** [comment]
This is now back ported to 7.1.0.

**Comment by maskit** [comment]
Closed the issue.

**Pull request merged**
