### PR TITLE
Add a dependency that is gone from master for these checks

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
@SolidWallOfCode Nope, not your fault. [approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Pull request merged**
