### PR TITLE
Make code buildable with AWS-LC

### PR DESCRIPTION
**Pull request by maskit**
Nothing is tested with AWS-LC, but it builds.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by maskit** [comment]
It's not 10.0 blocker, but I'd like to merge this before it gets conflicts.

**Review by bryancall — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Comment by JosiahWI** [comment]
This PR accidentally removed ENGINE support because the `HAVE_ENGINE_XXX` CMake variables do not become preprocessor macros. Do not backport to 9.x or earlier without an accompanying fix to re-enable it. This change happened to first last in 10.0.0, but we likely did not document removing ENGINE support because it was an accident.

**Pull request merged**
