### PR TITLE
Cleanup: Move Vol implementations into Vol.cc

### PR DESCRIPTION
**Pull request by masaori335**
No logic change. 

1. Move implementations of Vol functions to Vol.cc from Cache.cc and CacheDir.cc
2. Move static variables and functions into unnamed namespace in Vol.cc
3. Remove unused included headers.

Note: Many Vol implementations are left in CacheWrite.cc as is. Because we need to figure out CacheRead and CacheWrite code layout.

### CODE REVIEW

**Review by brbzull0 — DISMISSED** [review]
Looks good!
Thanks.

**Review by JosiahWI — APPROVED** [review]
Thanks Masaori, this looks good!

**Comment by masaori335** [comment]
Conflicts are resolved. Please take another look.

**Review by randall — APPROVED** [review]

**Comment by masaori335** [comment]
I'm merging this with Randall's approval because no big change after Damian approved this.

**Pull request merged**
