### PR TITLE
retry safe requests

### PR DESCRIPTION
**Pull request by jrushford**
Back port of Vijays pr to make safe requests retryable.  This fixes an increase in 502's seen in 6.2.x.

(cherry picked from commit a57f6609644752b8a2e81bcd4872f64575331c1e)

Conflicts:
	doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
	proxy/InkAPI.cc
	proxy/http/HttpConfig.cc
	proxy/http/HttpConfig.h
	proxy/http/HttpSM.cc
	proxy/http/HttpTransact.cc

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/freebsd-github/1678/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1574/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/110/ for details.

**Comment by zwoop** [comment]
The FreeBSD builds are in a bit of distress, [approve ci]

**Comment by jrushford** [comment]
I'd like Vijay to review but was unable to assign him for some reason.

**Comment by zwoop** [comment]
He probably didn't reconnect his account after the Infra changes last week.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/111/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1575/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1679/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/242/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/243/ for details.

**Comment by PSUdaemon** [comment]
@vmamidi

**Pull request merged**
