### PR TITLE
Test modifications for new microserver extension compatibility

### PR DESCRIPTION
**Pull request by macisasandwich**
Cherrypick of https://github.com/apache/trafficserver/pull/4796

This should fix most gold file related test failures seen on 8.1.x that aren't on master

### CODE REVIEW

**Comment by bryancall** [comment]
Still seeing this on CI:
```
Total of 101 test
  Unknown: 0
  Exception: 0
  Failed: 13
  Warning: 0
  Skipped: 4
  Passed: 84
```

**Comment by bryancall** [comment]
Please use cherry-pick -x when doing a cherry pick the comments for the commit are incorrect.

**Comment by duke8253** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Pull request closed without merging**
