### PR TITLE
Use Persistent Memory as storage for disk cache

### PR DESCRIPTION
**Pull request by cukiernik**
Allows use the [Intel Optane Persistent Memory](https://www.intel.com/content/www/us/en/architecture-and-technology/optane-dc-persistent-memory.html)  as a storage for cache. It map storage directly into user space memory, so reads and writes  are doing by a memcpy (without calls an io).

For configure use script _tools/ipm-configure_. It be need restart system probably, and run again. It configure _PMem_ into _AppDirect_ mode, and configure _nemespaces_ to _devdax_ mode. Data stored in them, be able after restart.

### CODE REVIEW

**Comment by cukiernik** [comment]
https://github.com/apache/trafficserver/issues/8693

**Comment by bryancall** [comment]
@SolidWallOfCode is going to review this

**Comment by bryancall** [comment]
@moonchen will review this

**Comment by cukiernik** [comment]
Can You help mi about **RAT fail**? It be ok, if I put [Intel Open Source License](https://en.wikipedia.org/wiki/Intel_Open_Source_License) into headers?

**Comment by bneradt** [comment]
> Can You help mi about **RAT fail**? It be ok, if I put [Intel Open Source License](https://en.wikipedia.org/wiki/Intel_Open_Source_License) into headers?

It's just alerting that some of the new files do not have valid license headers:

- ./tools/ipm-configure
- ./tools/ipm-performance

You can just copy and paste the license from one of the other tools files into those files. For example:

https://github.com/apache/trafficserver/blob/1c038e512103c4c1b32e335c980f9fae51f45f9d/tools/build_h3_tools.sh#L6-L20

**Comment by moonchen** [comment]
This has been in draft for a while.  Is it ready for review?

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
[approve ci centos cmake]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
@cukiernik is this change relevant since Intel stopped supporting Optane?

**Pull request closed without merging**
