### PR TITLE
Allow number of settings per H2 session to be configurable

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci Clang-Analyzer]
[approve ci FreeBSD]
[approve ci clang-format]

**Comment by bryancall** [comment]
Change the Milestone to 9.0.0 - #5531 is already on 8.0.4

**Comment by zwoop** [comment]
This has merge conflicts, and we'll need a new 8.1.x PR. Also, feel free to recommend / suggest other PRs that this depends on, such that it makes the back porting easier.

**Comment by masaori335** [comment]
8.1.x branch already has this by #5531 (5d238f8c32695990142bfcc8a9dac7e2dc870af0).

**Pull request merged**
