### PR TITLE
Reverts the changes from TS-3054

### PR DESCRIPTION
**Pull request by zwoop**
Also see the discussion on #2699, for a more complete fix. This fix is the same as the one from #2865 by @scw00.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by dragon512** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to 7.1.2

**Pull request merged**
