### PR TITLE
Add TS_HAS_QUICHE feature variable.

### PR DESCRIPTION
**Pull request by brbzull0**
Some of the quic features may only work with the quiche implementation. Having this will make easy in particular for unit tests to opt out depending of the variable value.

Exmaple:
```python
Test.SkipUnless(
   Condition.HasATSFeature('TS_HAS_QUICHE')
)
```
This also makes the variable available for all binaries.

```bash
/opt/ats/bin/traffic_layout info --features | grep QUICHE
#define TS_HAS_QUICHE 1
```

### CODE REVIEW

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by maskit** [comment]
`HAVE_QUICHE_H` is used at some places. We might want to consistently use `TS_HAS_QUICHE` if we add it.

**Comment by brbzull0** [comment]
> `HAVE_QUICHE_H` is used at some places. We might want to consistently use `TS_HAS_QUICHE` if we add it.

you mean change all the `HAVE_QUICHE_H` usage and use `TS_HAS_QUICHE` instead?

**Comment by maskit** [comment]
> you mean change all the HAVE_QUICHE_H usage and use TS_HAS_QUICHE instead?

Yes, I'm fine with either one but using the both may cause confusion.

**Comment by brbzull0** [comment]
[approve ci rocky]

**Comment by brbzull0** [comment]
convert to draft, I'm not happy with this, will re-open once I'm satisfied.

**Review by maskit — APPROVED** [review]
Thanks!

**Pull request merged**
