### PR TITLE
CLEANUP:  Simplify / clarify interface to BodyFactory.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
It would good to add an au test to specifically exercise the URL redirect message code that I diddled with.  I could use some pointers from someone who is wise in the ways of the micro-DNS server.

**Comment by bryancall** [comment]
This is a huge change without any testing.  I would like to test some tests written to make sure all the changes are correct.

**Comment by ywkaras** [comment]
@bryancall There seem to be some au tests for body factory.

A diff tool that's good at detecting moved lines (with changed white space) would be good to look at this.  When you consider how much I just moved code for better encapsulation, it's not such a big change.

**Comment by ywkaras** [comment]
wkaras /tmp
$ cat /tmp/xx
killComments ()
{
sed 's|//.*$||' | sed 's|/\*.*\*/||g' | sed '/^ *\/\*/,/\*\/ *$/d'
}

cd /tmp
rm -rf cmp
mkdir cmp
cd ~/TS
git diff --name-only BodyFactoryRefactor master > /tmp/cmp/lst
git checkout BodyFactoryRefactor > /dev/null
cat $( cat /tmp/cmp/lst) | killComments | sed 's/^ *//' | sort > /tmp/cmp/new
git checkout master > /dev/null
cat $( cat /tmp/cmp/lst) | killComments | sed 's/^ *//' | sort > /tmp/cmp/old
echo 'deleted code lines ' $( diff /tmp/cmp/old /tmp/cmp/new | grep '^<' | wc -l )
echo 'added code lines ' $( diff /tmp/cmp/old /tmp/cmp/new | grep '^>' | wc -l )
wkaras /tmp
$ /tmp/xx
Switched to branch 'BodyFactoryRefactor'
Switched to branch 'master'
deleted code lines  178
added code lines  78

**Comment by shinrich** [comment]
Yes, it looks like a lot of the changes were moving unnecessary classes out of the header file into the only cc file that used them. 

Looks like @d2r wrote the body factory autests.  @d2r how complete do you think those tests are?  

Also @ywkaras you need to rebase your branch.

**Comment by d2r** [comment]
> Looks like @d2r wrote the body factory autests. @d2r how complete do you think those tests are?

I did not exhaustively cover every use case. Generally wrote tests covering use cases that were required or affected by the changes I made at the time.

**Comment by ywkaras** [comment]
Closing to remove clutter from open PR list.

**Pull request closed without merging**
