### PR TITLE
regex_reval: delete remap continuation, fix remap hook setup

### PR DESCRIPTION
**Pull request by traeak**
Fixed remap continuation memory leak, did a full audit of the plugin to make sure leaking doesn't grow.  Also added in cleanup code for cleaning up the config continuation when unloading a remap plugin, even though this code is never run due to the way plugins curerntly work.

### CODE REVIEW

**Comment by traeak** [comment]
still testing this fix.  Also figured out that the free_cont/free_handler *REALLY NEEDS* to be reference counted.  It may be responsible for some very sporadic crashes we've seen.

**Comment by zwoop** [comment]
I think this is a candidate for 8.x, but do we also want it for 7.1.x?

**Comment by zwoop** [comment]
[approve ci]
[add to whitelist]

**Comment by traeak** [comment]
this is actually a fix to the regex_revalidate remap upgrades.  This fix wouldn't apply to 7.1.x unless you bring in the regex_revalidate remap enhancment.

**Comment by traeak** [comment]
PR https://github.com/apache/trafficserver/pull/4533 includes this fix.

**Comment by traeak** [comment]
Closing this as there are bugs in this version fixed in https://github.com/apache/trafficserver/pull/4578

**Comment by traeak** [comment]
PR has https://github.com/apache/trafficserver/pull/4578 more bug fixes (both for global and remap plugins) not addressed by this fix.

**Pull request closed without merging**
