### PR TITLE
Fix protocol version in request Via header

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Review by bneradt — CHANGES_REQUESTED** [review]
Looks reasonable.

We have a via.test.py. Can a test for this be added there?

**Comment by maskit** [comment]
I added a test case for H3, and I realized HTTP version is correct but it says TCP is used. I'll try to fix that part.

**Comment by maskit** [comment]
> I added a test case for H3, and I realized HTTP version is correct but it says TCP is used. I'll try to fix that part.

I didn't need to fix it. I thought there is a bug because autest passed where the gold file says QUIC uses TCP, but it was just the test is skipped. I updated the gold file.

**Review by brbzull0 — APPROVED** [review]
Looks good. Thanks.

**Comment by ezelkow1** [comment]
[approve ci centos]

**Review by bneradt — APPROVED** [review]

**Pull request merged**
