### PR TITLE
TS-4791: Move stale_while_revalidate back into the build.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/621/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/517/ for details.

**Comment by jpeach** [comment]
@PSUdaemon didn't NACK this on IRC, so moving forward. If anyone else wants to NACK this we can discuss :)

**Comment by zwoop** [comment]
It's a shame, because this plugin works poorly (only one request is "saved").

**Pull request merged**
