### PR TITLE
slice plugin to break up large requests into cacheable sub blocks

### PR DESCRIPTION
**Pull request by traeak**

### CODE REVIEW

**Comment by bryancall** [comment]
[ci approve]

**Comment by bryancall** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci]

**Comment by traeak** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by traeak** [comment]
considering that there is only a 1 line addition to the plugins Makefile.am there should be no reason why autest is failiing.

**Comment by zwoop** [comment]
[approve ci].

**Comment by scw00** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci]

**Comment by traeak** [comment]
Where is this error coming from?

cc1plus: error: unrecognized command line option '-Wno-cast-function-type' [-Werror]
cc1plus: all warnings being treated as errors

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci]

**Pull request closed without merging**
