### PR TITLE
Move to blocklists and allowlists

### PR DESCRIPTION
**Pull request by mlibbey**
The words blocklist and allowlist are equally descriptive as their racially
charged alternatives and gaining industry-wide acceptance.

Still need to go through the Japanese docs to do the same.

### CODE REVIEW

**Comment by maskit** [comment]
> Still need to go through the Japanese docs to do the same.

Do we want to completely remove the words from the repo or is it ok if those words and the translations will not be on actual docs?

**Comment by mlibbey** [comment]
Chatting with maskit and masaori335 about the Japanese translations -- with the translation process, sounds like they are better for a distinct PR.

**Comment by randall** [comment]
If you're renaming plugins, you'll also have to update the appropriate Makefiles. Also the plugins contents contain blacklist.

**Comment by randall** [comment]
I thought this was a doc only PR so I created https://github.com/apache/trafficserver/pull/6918

There's also the sni_whitelist plugin that needs to be renamed

**Comment by randall** [comment]
I merged #6918, you'll need to rebase your change.

**Comment by zwoop** [comment]
Closing this since @randall  is going to take this, and make a new, cleaned up PR.

**Comment by randall** [comment]
This is now #7034

**Pull request closed without merging**
