### PR TITLE
TS-5015: Convert storage configuration file to Lua

### PR DESCRIPTION
**Pull request by shukitchan**
documentation is TBD. Also I want to clean up a bit since it is messy.
@jpeach, pls take a look and review.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1112/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1005/ for details.

**Comment by shukitchan** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1006/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1113/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1007/ for details.

**Comment by zwoop** [comment]
Neat! I wonder, maybe we should start naming these new config files with a .lua extension? That makes editors much happier, and it makes logical sense too. So, this could be named storage.lua instead of "store.config".

In retrospect, we then should have named them metrics.lua and logging.lua, but we can retrofit that later (or, support both naming for the 7.x lifetime).

Thoughts?

**Comment by zwoop** [comment]
Before committing this, I think we should at least squash the build fixes such that there are not intermediate commit steps that are failing.

**Comment by shukitchan** [comment]
After the summit, here are the things I learn I should do

1) Add a flag to allow backward compatibility. 
2) combine volume.config and hosting.config as well in this new lua format. 
3) Some clean up and resolve conflicts
4) squash before commit, of course

And then we should have a separate JIRA to remove the legacy code and make this change mandatory for 8.0.0

@jpeach any other comments you have?

**Comment by zwoop** [comment]
I still think we need to have a discussion on what these new "Lua" style configs should be named, such that we don't have to come up with contrived renaming. I'm ok with a prefix of any of

* .cfg
* .conf
* .lua
* .luacfg
* .luaconf

etc. @shukitchan Can you take this to the mailing list for consensus? Also, if we do change this, we should change metrics.config and logging.config accordingly, however, for 7.x both names would need to be support for compatibility.

**Comment by shukitchan** [comment]
it looks like .luaconf is the winner. 
I will be updating this accordingly. Also will create new issue to make sure metrics.config and logging.config are changed accordingly as well.

**Comment by zwoop** [comment]
What's the status on this PR? Discussion item for the Summit?

**Comment by shukitchan** [comment]
I don't think we need more discussions. I just need to find time to clean this up and continue the works.

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
Lets decide on a name here:

- storage.config  -- Lets just not care
- storage.luaconfig

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
Ok, lets do something here: I'm ok with .luaconfig as discussed, but I really would have preferred .lua (since all editors would identify those properly and put in correct editing modes).

But regardless, @shukitchan Please make the appropriate changes here as you see fit, and make it happen. Once that is done, we should IMO rename the two existing Lua style configurations to the same postfix such that we are consistent (and we can support both of those files old and new config names for 8.0.0)

**Comment by shukitchan** [comment]
I will resume the work in August.

**Comment by bryancall** [comment]
Please reopen when work has resumed.

**Pull request closed without merging**
