### PR TITLE
New TSQA

### PR DESCRIPTION
**Pull request by jacksontj**
This is integration with the new TSQA I've been working on over the past couple weeks. We are now using this same framework internally on one plugin, and this PR includes "ports" of the old TSQA tests.

I still need to finish documentation for all of this, but we are planning on meeting up next week to chat about this. So I figured I should at least open the PR to let people see what it looks like.

### CODE REVIEW

**Comment by bgaff** [comment]
Thanks @jacksontj , we'll walk through this at our meetup next week.

**Comment by jacksontj** [comment]
And before we merge this I can squash if we want a cleaner commit log :)

**Comment by jacksontj** [comment]
@bgaff I squashed all of the commits into one. I've also changed it from traffic_cop to traffic_server while we wait for @jpeach 's commit to land.

**Comment by jacksontj** [comment]
A point @bgaff brought up was that tsqa (the harness/framework) lives outside this source tree. This is intentional as the *tests* are tied to the trafficserver source, but not necessarily the harness. The intent is for tsqa to be used not only for the core but for plugin and/or internal testing as well. Because of that we want the flexibility to release tsqa (the framework) independently of trafficserver. I'm not tied to having the code on my personal github, but I do think it should remain in a separate repo from trafficserver.

**Comment by jacksontj** [comment]
Also, do we need the Apache file headers on all test cases as well?  (@zwoop would probably be the one to answer)

**Comment by zwoop** [comment]
Yes.

**Comment by bretep** [comment]
@jacksontj how about adding it as a git submodule?

**Comment by zwoop** [comment]
Not sure why you would prefer not to just merge it in, but I can with 99% certainty say that we would not include it as a git submodule. We would consider it as a git subtree though, if that's what it takes. We have one git submodule right now, and it's been terrible, we'll hopefully modify that to a git subtree in 5.3 -> 6.0 timeframe.

**Comment by bretep** [comment]
@zwoop I can get behind that. I'd much rather have it merged myself.

**Comment by jacksontj** [comment]
I still don't understand the want/need to include this in the base source tree... The tests basically require a bunch of python deps (requests, flask, tsqa, etc.) None of the other deps live in the source tree-- they are pulled in at test run-time to build the python-virtual env that is needed to run the tests. Unless we also plan on submoduling the rest of the python deps I think a separate repo should be fine.

**Comment by jpeach** [comment]
How do you deal with versioning? ie. when a test requires a specific commit to pass?

**Comment by jacksontj** [comment]
@jpeach and I chatted on IRC. I think the main source of confusion is that the tests are *not* going to live outside the source tree-- just the tsqa library.

**Comment by zwoop** [comment]
Hmmm so I can't run tsqa without going to another repository? That doesn't make any sense. Having dependencies libraries that are easily installed via eg pip or yum is fine. But clearly all our own developed software should go into our repo?

**Comment by jacksontj** [comment]
The dep can and is easily installed using pip into a virtual env (the makefile does all the work for you). Basically the tsqa library is treated as any other python dep-- meaning we have to install some specific version from somewhere else.

I do think the tsqa library needs to be a separate repo under the trafficserver project.

**Comment by zwoop** [comment]
Hmmm that's a hurdle. Why does it need its own git repo? Or are you suggesting you will incubate his as a new apache project?

Confused.

**Comment by jacksontj** [comment]
TSQA, although used by these tests, aren't only useful in this setting. For example, we use them already for testing our internal plugins and some internal builds. Since that is the case I need to install specific versions of TSQA that are dictated by my set of tests-- not necessarily the version of the TSQA that is tied to the version of ATS that I am running.

We could work around this by creating a separate tagging scheme in the trafficserver source code, but that still gets messy since people who want to install the dep would have to not only know this other tagging scheme, but would also have to know which subdir to install from.

As a separate repo we can iterate on tsqa (the library code) independently of the ATS source tree, while still keeping it a part of the project. Its basically the same reason that we don't pull in the source for "python requests" just because its used by the tests.

**Comment by jacksontj** [comment]
@jpeach fixed the typo (and squashed)

**Comment by jacksontj** [comment]
This was merged :)

**Pull request closed without merging**
