### PR TITLE
CacheTool: Cleanup TS_INLINE.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
`inline` is part of the language now.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Comment by maskit** [comment]
This doesn't look like Cache Tool specific issue. Why didn't you remove / replace TS_INLINE from other places?

**Comment by SolidWallOfCode** [comment]
Because I only need this cleaned up in CacheTool for the YAML work, and because this is a dependent PR rather than stand alone, I wanted to keep it at a minimal scope.

**Pull request merged**
