### PR TITLE
TS-4362 Removed cacheurl plugin

### PR DESCRIPTION
**Pull request by gtenev**
Removed the cacheurl plugin and its documentation (including the Japanese version)

### CODE REVIEW

**Comment by zwoop** [comment]
Did we send an email to users@ making this announcement already? If not, please do so, and specify that we've moved this functionality to the cachekey plugin. [approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/561/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/457/ for details.

**Comment by gtenev** [comment]
@zwoop, announcement sent to users@

**Comment by jpeach** [comment]
👍

**Comment by PSUdaemon** [comment]
Was this deprecated, or are we just removing and replacing with the cache_key plugin?

**Comment by zwoop** [comment]
Deprecated as of 6.2.0, removed for 7.0.0:

This plugin is deprecated as of v6.2.0 and will be removed as of v7.0.0. It is replaced by a new Cache Key Manipulation Plugin and you should change your configurations to use the new plugin instead. Please find some examples below

**Pull request merged**
