### PR TITLE
Test two continuations for HTTP_*_CLOSE

### PR DESCRIPTION
**Pull request by lbordowitz**

### CODE REVIEW

**Comment by jpeach** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by lbordowitz** [comment]
@zwoop Could you add `httpd-tools` package to the build containers? The test I wrote requires `ab`, the Apache Benchmark tool. This shouldn't be merged without the tests running.

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by lbordowitz** [comment]
Okay, once the build containers have the apache benchmark tool (through package httpd-tools) this plugin test (and #2136 ) should be ready to run ci.

**Comment by shinrich** [comment]
It would probably be valuable to another test case that just makes a few curl requests in a loop for the installations that don't have ab handy.

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
@lbordowitz What should we do about this?

**Comment by lbordowitz** [comment]
@maskit okay, done. Additionally, I have the tests waiting until the records.snap file exists, to ensure that statistics properly make it to traffic_ctl process.

**Comment by maskit** [comment]
[approve ci]

**Comment by lbordowitz** [comment]
@maskit in the latest commit, I have run `make autopep8`.

**Pull request merged**
