### PR TITLE
[IO_URING] Change submit_and_wait to take ink_hrtime. Fix test_AIO for io_uring.

### PR DESCRIPTION
**Pull request by cmcfarlen**

### CODE REVIEW

**Comment by cmcfarlen** [comment]
[approve ci]

**Comment by cmcfarlen** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci fedora]

**Comment by cmcfarlen** [comment]
[approve ci freebsd]

**Review by bryancall — APPROVED** [review]

**Pull request merged**
