### PR TITLE
TS-4785: Stale while revalidate plugin memory corruption.

### PR DESCRIPTION
**Pull request by jpeach**
This fixes a couple of memory corruption bugs in the stale_while_revalidate
plugin.

First, when copying the client sockaddr, we need to copy the specific
address family structure, not the untyped struct sockaddr.

Next, we zero when allocating to make initialization more reliable.

Finally, we deal with receiving TS_EVENT_HTTP_CACHE_LOOKUP_COMPLETE
multiple times, which otherwise leads to a double free.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/614/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/510/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/512/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/616/ for details.

**Comment by PSUdaemon** [comment]
👍

**Pull request merged**
