### PR TITLE
Enhancements for compress plugin

### PR DESCRIPTION
**Pull request by shukitchan**
1. Support POST method 
2. Add a mutex for the configuration reload handler. This prevents some race conditions when multiple reloads are happening

### CODE REVIEW

**Comment by shukitchan** [comment]
@bryancall , we touched upon this enhancement in some old slack conversations. These are our patches to make the compress plugin work for us. Please take a look.

**Comment by ywkaras** [comment]
Would it be possible to add to the "compress" test case to test POST?

**Comment by shukitchan** [comment]
[approve ci freebsd]

**Comment by shukitchan** [comment]
@ywkaras i added a test.

**Comment by ywkaras** [comment]
Good but we have to get a non-Verizon person to review in order to get this merged.

**Comment by shukitchan** [comment]
@randall can you check this out? it is a simple PR.

**Review by randall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
