### PR TITLE
TS-4997: Move the C++ API to lib/cppapi.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/960/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1068/ for details.

**Comment by zwoop** [comment]
Hmmm, are we sure this makes sense? The CPP APIs aren't plugins, and we certainly don't put the TS API's into plugins. I could perhaps see this go into proxy somewhere.

**Comment by bryancall** [comment]
I agree with Leif.  Looking at the patch again I think it is good to move the plugins to example/, but not all cppapi under plugins/.

**Comment by jpeach** [comment]
As I mentioned, from a build and dependencies point of view, ``cppapi`` is a plugin. It depends on the TS API layer and is constrained (currently) from using any internal APIs. So the build is basically the same as a plugin.

It certainly does not belong in `lib` because it is not an internal library and is a consumer of the low layers. ``plugins`` is not the ideal home, but it seems like the best option for now.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1069/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/961/ for details.

**Comment by jpeach** [comment]
I'll make a new PR that moves it to ``lib/cppapi``. This isn't ideal, but it removes the unnecessary ``src`` directory and we can probably agree on it :)

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1073/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/965/ for details.

**Pull request merged**
