### PR TITLE
TS-4808: General diagnostics cleanup.

### PR DESCRIPTION
**Pull request by jpeach**
- Clean up the Diags class to remove code duplication.
  - Switch all the diagnostic formatters over to using SourceLocation.
  - Remove useless mgmt_log functions which sometimes take stderr paramets.
  - Remove TSDiags() because it is awkward to pass a SourceLocation down.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/676/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/572/ for details.

**Comment by zwoop** [comment]
```C++
../../iocore/utils/diags.i: In function 'void reconfigure_diags()':
../../iocore/utils/diags.i:50:24: error: invalid conversion from 'int' to 'DiagsShowLocation' [-fpermissive]
   diags->show_location = 1;
```

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/677/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/573/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/679/ for details.

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/575/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/682/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/578/ for details.

**Comment by zwoop** [comment]
I've tested this on OmniOS, and it compiled without problems. The changes seems reasonable to me, but they are also massive so real difficult to know if everything is correct :).

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/692/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/588/ for details.

**Comment by shinrich** [comment]
Looks like a reasonable tidy up.

**Pull request merged**
