### PR TITLE
[9.2.x] Terminate H2 connection by COMPRESSION_ERROR (#11222)

### PR DESCRIPTION
**Pull request by masaori335**
(cherry picked from commit 14d5b2ce401446a13b2fef4ab8dbc7cf890acf25)

Conflicts:
	proxy/http2/Http2ConnectionState.cc

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci fedora]
[approve ci freebsd]

**Comment by masaori335** [comment]
[approve ci freebsd]

**Comment by masaori335** [comment]
[approve ci fedora]

**Comment by masaori335** [comment]
Fedora build needs #11268.

**Comment by masaori335** [comment]
[approve ci fedora freebsd]

**Comment by masaori335** [comment]
This PR is ready. https://github.com/apache/trafficserver/pull/11268 fixed the issue as expected.

**Review by bryancall — APPROVED** [review]

**Pull request merged**
