### PR TITLE
TS-3921: Fix MASKs of Frames

### PR DESCRIPTION
**Pull request by masaori335**
- [TS-3921](https://issues.apache.org/jira/browse/TS-3921)
- [TS-3827](https://issues.apache.org/jira/browse/TS-3827)

### CODE REVIEW

**Comment by masaori335** [comment]
@maskit Could you take a look?

**Comment by jpeach** [comment]
This looks reasonable. Could you add a unit test for ```http2_are_frame_flags_valid()```, which should be straightforward now the masks are correct.

I see that ```http2_frame_header_is_valid()``` does't raise an error on invalid flags. Should we restore the check?

**Comment by masaori335** [comment]
@jpeach OK, I'll add unit tests. 
IMO, we should restore the check.

**Comment by maskit** [comment]
@masaori335 LGTM.

We should restore the check only about flags. Other part in the commit looks reasonable.

**Comment by jpeach** [comment]
Merged under TS-3827. Let's restore the flags check under a separate JIRA. Thanks!

**Pull request closed without merging**
