### PR TITLE
Build tslua plugin in CMake build

### PR DESCRIPTION
**Pull request by JosiahWI**
This also adds a Find script for LuaJIT, which uses pkg-config to find the LuaJIT library.

### CODE REVIEW

**Review by shukitchan — DISMISSED** [review]
It looks good.

**Comment by JosiahWI** [comment]
@shukitchan Somewhat related to this PR, I'm getting an interesting Lua panic in all the lua plugin AuTests with this PR.

traffic.out:
```
[Jul 11 13:19:19.135] traffic_crashlo ERROR: missing password database entry for ''
... (more content ommitted)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```

I've included an error from traffic_crashlog here as well, in case the panic is a symptom of that.

**Comment by shukitchan** [comment]
What is the version of luajit? 
It looks like a problem with luajit version. 

I think it won't work with anything below 2.0.5

**Comment by JosiahWI** [comment]
Version 2.1 I believe. @bneradt can run the AuTests just fine on the fedora38 image; so it's not an issue with the build configuration.

**Comment by shukitchan** [comment]
I see that the PR build autests all passed now?

**Comment by JosiahWI** [comment]
Those were built with automake. There's nothing in CI that tests that the CMake build is correct, only that it compiles.

**Comment by bneradt** [comment]
> What is the version of luajit? It looks like a problem with luajit version.
> 
> I think it won't work with anything below 2.0.5

Huh, yeah. This could likely be the difference. I bet fedora:38 has a more recent luajit.

**Pull request merged**
