### PR TITLE
TS-4523 - Add pause functionality to the TransformationPlugin interface.

### PR DESCRIPTION
**Pull request by davidbz**
Adding the pause functionality to the TransformationPlugin.

Api changes:
Added the pause() method to the TransformationPlugin, the return value is a TSCont which you can schedule whenever you wish to resume the transformation.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/165/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/271/ for details.

**Comment by zwoop** [comment]
Remember to run clang-format on any contribution :) It's easiest done with a simple

    make clang-format

**Comment by ushachar** [comment]
A couple of comments:
1) You should add a description to the sample plugin
2) Since it's an API change, let's send out the email to the dev mailing list...

**Comment by davidbz** [comment]
@zwoop - Thanks! it seems to work just fine on my machine.. still trying to figure it out
@ushachar - Done! thanks..

**Comment by ushachar** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/185/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/293/ for details.

**Comment by zwoop** [comment]
Some minor details here:

1) Update the commit subject message please.
2) It now has marge conflicts, so please rebase, and re-run clang-format as well.

@ushachar  Can you help land this?

**Comment by ushachar** [comment]
Yep. Getting back to this asap....

**Comment by ushachar** [comment]
The reason for wanting this feature is to support prolonged content related actions -- in @davidbz  case out-of-process content malware analysis.

When acting as a forward proxy and handling a request for a very large file, he needs to support an initial analysis on the first N MBs of the file in order to decide if he must analyze the full file or can release it to the client.
This analysis can take a significant amount of time and continuing to buffer the contents can lead to resource exhaustion.
(When combined with turning on flow control to make sure that we throttle the proxy<->upstream tcp connection)

@bgaff - I know you had some concerns regarding this - does this use case seem reasonable to you?

**Comment by ushachar** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/929/ for details.

**Comment by davidbz** [comment]
@ushachar Done. Thanks

**Comment by ushachar** [comment]
@jpeach / @SolidWallOfCode  - Since there were a couple of concerns about this API in the beginning could one of you ack this as well?

**Comment by bryancall** [comment]
@davidbz 
Can you please rebase so we can merge it?  Please make sure the commit is squashed.

**Comment by bryancall** [comment]
[approve ci]

**Comment by davidbz** [comment]
@bryancall Sure! Thanks

**Comment by davidbz** [comment]
@bryancall Done.

**Comment by ushachar** [comment]
[approve ci]

**Comment by ushachar** [comment]
[approve ci]

**Comment by davidbz** [comment]
@bryancall Hi, commit is squashed and ready for merge :)

**Pull request merged**
