### PR TITLE
[TS-4408] Make volume.config not order sensitive.

### PR DESCRIPTION
**Pull request by calavera**
I added a couple of additional checks:

1. Fail with a format error if there are duplicated tokens, for instance:

	volume=1 size=50% size=25%

2. Ignore everything else if there are other unknown tokens after parsing size and scheme:

	volume=1 size=50% scheme=https foo=bar

Please, let me know if this is correct.

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by zwoop** [comment]
Assigning to @PSUdaemon  for review.

**Comment by jpeach** [comment]
I haven't had time to look at this properly, but ``volume.config`` is not (only) parsed by the management routines, it is parsed by ``ConfigVolumes::BuildListFromString``. I am pretty sure that there are generic parsing routines for the key=value line format. I like the used of ``ink_atoi`` that you did here ... that's more convenient for the size field.

**Comment by calavera** [comment]
Thanks @jpeach. I'll look into that.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
.

**Comment by calavera** [comment]
@jpeach I made some changes in ConfigVolumes::BuildListFromString to handle the un-ordered options too. I could not find those generic parsing routines but I can make the change if you point me to them

**Comment by jpeach** [comment]
I did an initial review and some light testing of this.

@calavera the API I was referring to is ``parseConfigLine`` from ``MatcherUtils.cc``. It is not quite a generic parser but it will do the job here and tidy up a lot. I'm probably going to merge this as it, so we can make another PR for  ``parseConfigLine``.

**Comment by calavera** [comment]
@jpeach sounds good to me. I can open a new pull request using that api.

**Pull request closed without merging**
