### PR TITLE
For 7.1.x: move http 408 response logic into transaction

### PR DESCRIPTION
**Pull request by scw00**

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci fedora]

**Comment by scw00** [comment]
[approve ci fedora]

**Comment by masaori335** [comment]
[approve ci fedora-github]

**Comment by masaori335** [comment]
Could you append commit id and uncomment the conflicted files in commit message? :)

https://cwiki.apache.org/confluence/display/TS/Git#Git-Cherry-Pick

**Comment by scw00** [comment]
@masaori335 updated!

**Comment by masaori335** [comment]
Looks good. The Release Manager will merge this :)

**Comment by zwoop** [comment]
[approve ci fedora]

**Pull request merged**
