### PR TITLE
TCL: Rmove TCL dependency from HostStatus

### PR DESCRIPTION
**Pull request by chitianhao**

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
We should get @jrushford to review this.

**Comment by jrushford** [comment]
Thanks @amc.  Yes, I’d like to review it.  I’ll take a look this evening.

**Comment by jrushford** [comment]
@chitianhao and @shinrich  I've built / tested this and it looks good to me.  I'll merge it

**Comment by zwoop** [comment]
This has merge conflicts, and we'll need a new 8.1.x PR. Also, feel free to recommend / suggest other PRs that this depends on, such that it makes the back porting easier.

**Pull request merged**
