### PR TITLE
Cleanup Http2Stream

### PR DESCRIPTION
**Pull request by masaori335**
~~This PR includes commit for #3091. I'm going to rebase this PR when #3091 is merged.
Please review b9b2961 for this PR.~~

### CODE REVIEW

**Comment by masaori335** [comment]
Rebased on latest master branch.

**Comment by zwoop** [comment]
Hmmm, slightly confused now, does this go to master, or 7.1.x, or both ?

**Comment by masaori335** [comment]
Both. For 7.1.x, I'll add this to #3096 (back port request of #3091)

**Comment by masaori335** [comment]
This has 3 changes. Description is added.

> - Remove return value of Http2Stream::update_write_request(). Because return value is not used in most cases. And Http2Stream::do_io_write() can always return &write_vio where only the return value is used.
> - Http2Stream::update_write_request() returns immediately if there're no data to proceed
> - Make Http2Stream::send_response_body() private

**Pull request merged**
