### PR TITLE
Corrects the wording of the usage messages for traffic_ctl host subcommand

### PR DESCRIPTION
**Pull request by jrushford**
Minor change to fix the wording on the traffic_ctl host subcommand.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
You need to rebase this, because it depends on `ink_hash_table` which is going away.

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
Cherry picked to 8.1.0

**Pull request merged**
