### PR TITLE
Remove Congestion Control Feature

### PR DESCRIPTION
**Pull request by shinrich**
This feature has been gathering dust.  I don't believe anyone is using the feature, and the feedback I received when poking about in this area about 2 years ago is that it doesn't really work.  Based on git blame I see that no one has made functional changes in this area since we moved to git in 2009.  It does have tendrils in the state machine, and looking at our code coverage reports we are not testing those tendrils.   I think either someone should step up and take ownership to make this a usable feature or we should remove it (this PR).

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by shukitchan** [comment]
just a question. how do people do rate limiting now on ATS?
I do see that (if this feature works) it can be made to provide some primitive form of rate limiting on top of ATS. 
If we are removing this feature, i just want to know if anyone is doing their own plugins or something to provide rate limiting.

**Comment by SolidWallOfCode** [comment]
In practice, as far as I can tell, people use the total number of connections, or the total inbound/outbound connections (connection throttling). Some deployments use the max connections per upstream to rate limit. @bryancall did some work with keep alive which should help in this regard.

**Comment by shinrich** [comment]
For our purposes we ended up using connection throttling as @solidwallofcode noted.  @jacksontj was also working in this area around the same time. I looked at the congestion control stuff, and the basic connection throttling appeared to work there, but the fancier features did not and no one was claiming ownership.  We have used the following configuration settings.

- proxy.config.net.connections_throttle - Limits the combination of incoming and outgoing connections.  Will immediately abort the connection if overlimit. 
- proxy.config.http.origin_max_connections - Per origin connection limits.  Will fail immediately or retry in a bit of origin_max_connections_queue is set to a non-negative value
- proxy.config.http.server_max_connections - Total limit on connections to origin.

@bryancall has also added logic to be more aggressive about dumping connections in keep-alive state when we are running into resource limits.
{code}
proxy.config.http.origin_min_keep_alive_connections
proxy.config.net.max_connections_in
proxy.config.net.max_connections_active_in
{code}

**Pull request merged**
