### PR TITLE
Update git-versions figure

### PR DESCRIPTION
**Pull request by maskit**
Because release plans are changed, I updated the figure that describe how we make & update branches for each releases.

Also, I changed the image format from png to svg, and added a source file for draw.io so that anybody can update the figure (draw.io only requires web browser, no need to register).

### CODE REVIEW

**Comment by maskit** [comment]
If you render the svg the output is like below:
image

**Comment by maskit** [comment]
I added AL2 comment to the xml file but it doesn't pass RAT test :/

**Comment by randall** [comment]
[approve ci rat]

**Comment by randall** [comment]
[apprive ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Pull request merged**
