### PR TITLE
Via: Last chance VIA updates related to #1534

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
See #1534 #1988 #2018 #2024
See also [TS-4457](https://issues.apache.org/jira/browse/TS-4457).

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by shukitchan** [comment]
what is the reason in doing that? i must have missed some conversation?

**Comment by zwoop** [comment]
Still showing the protocol stack (as we discussed).

**Comment by zwoop** [comment]
Kit: The reason is that adding this (like we are) to the Via header breaks the protocol / RFC. This logic should go in a separate header, as I've discussed with others, it should likely go with with the Forwarded header (https://tools.ietf.org/html/rfc7239)

**Comment by zwoop** [comment]
This still looks odd to me:

```
Via: ATS (ApacheTrafficServer/8.0.0 [uScHs f p eN:t cCHp s ]), http/1.1 tls/1.2 tcp ipv6
```

The second string, after the comma, would be interpreted as another hop in the Via chain (which is clearly not right).

**Comment by SolidWallOfCode** [comment]
@zwoop  - That's because you have your ATS misconfigured.

**Comment by zwoop** [comment]
Ok, how about we do this:

1. Revert these new configurations.
1. Add a new state to the existing configuration, "4", which means also include the protocol stack.
1. Fix the strings such that they are always RFC compliant (even in the "4" state).

**Comment by SolidWallOfCode** [comment]
Like this, I presume
```
Via: 1.1 vegur, http/1.1 tidus (ApacheTrafficServer/8.0.0 http/1.1 tcp ipv6)
```

**Comment by zwoop** [comment]
Right.

**Comment by SolidWallOfCode** [comment]
At verbosity 4, it is
```
Via: 1.1 vegur, https/1.1 tidus (ApacheTrafficServer/8.0.0 [uScMsSf pSeN:t cCMp sS] [http/1.1 tls/1.2 tcp ipv4]
```

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Pull request merged**
