### PR TITLE
TS-4402: Fixes some config "Int" types to "Byte" types.

### PR DESCRIPTION
**Pull request by zwoop**
This also makes some reordering of the Byte types to be consistent.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/662/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/557/ for details.

**Comment by zwoop** [comment]
I have an update to this coming momentarily. :)

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/666/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/561/ for details.

**Comment by jpeach** [comment]
This looks OK to me. Consider your commit subjects read ```TS-4402: ...```.

👍

**Comment by zwoop** [comment]
@jpeach what do you mean ? The : ?

**Comment by zwoop** [comment]
Fwiw, I did compare before and after, and things definitely improved. Not a ton, but noticeable, I think we got rid of 3 cache lines in total across both structs.

**Comment by jpeach** [comment]
Yep the ```:```.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/671/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/566/ for details.

**Pull request merged**
