### PR TITLE
TS-4177: Memory leak in LogFieldAliasTable

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by zwoop** [comment]
+1. Btw, is that really how clang-format indented it?

**Comment by bryancall** [comment]
No, I didn't run clang-format on the pull request before pushing it to github.  I have a script that automates committing pull requests and it will format it before it is pushed to master.

**Comment by SolidWallOfCode** [comment]
Too late but this is the kind of thing {{ats_scoped_str}} is for.

**Comment by bryancall** [comment]
If we want to go down the path of managed pointers then unique_ptr would be the way to go.

I don't see a benefit of ats_scopted_str.  It not a generic class and has limited usability.

**Comment by SolidWallOfCode** [comment]
As far as I know, we can't depend on `std::unique_ptr` being available. If that's changed then yes, we could replace `ats_scoped_str` with `unique_ptr`. The former is limited basically for this reason, that it is just a stop gap until we can use the standard mechanism.

**Pull request closed without merging**
