### PR TITLE
back port to 7.1.x to make additional parent proxy parameters overridable.

### PR DESCRIPTION
**Pull request by jrushford**
This is a backport pr for 7.1.x after fixing the indicated conflicts.

Make proxy.config.http.parent_proxy.per_parent_connect_attempts,
proxy.config.http.parent_proxy.connect_attempts_timeout,
proxy.config.http.parent_proxy.fail_threshold, and
proxy.config.http.parent_proxy.retry_time overridable.

(cherry picked from commit 401ffbef1a7b25d6c1dfc48a2a81d70c4bb1764d)

Conflicts:
	doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
	iocore/net/Socks.cc
	lib/ts/apidefs.h.in
	plugins/experimental/ts_lua/ts_lua_http_config.c
	proxy/InkAPI.cc
	proxy/InkAPITest.cc
	proxy/http/HttpConfig.h

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by d2r** [comment]
@zwoop: solution to fix 7.1.x is to cherry-pick #1419 && REVERT commit d91350f4 from #2038.

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Pull request merged**
