### PR TITLE
Remove unused functions of IOBuffer

### PR DESCRIPTION
**Pull request by masaori335**

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
Rerunning CI to test Github CI.

**Comment by zwoop** [comment]
This does not cherry-pick cleanly to 9.0.x, if you want this, please make a new PR against the 9.0.x branch, and link back to this one as well in the comment.

**Comment by masaori335** [comment]
@zwoop Could you cherry-pick 5e639715a52c6e0c09bdf8842989fbd83850c81a (#6118) first?
After that this should be cherry-pick cleanly.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
