### PR TITLE
Skipping tests if a plugin doesn't exist

### PR DESCRIPTION
**Pull request by macisasandwich**
In multiplexer and header_rewrite

### CODE REVIEW

**Comment by zwoop** [comment]
Hmmm, under what conditions would header_rewrite not build? That seems odd.

**Comment by SolidWallOfCode** [comment]
Not so important for `header_rewrite` but we have a test for `multiplexer` which makes this useful.

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by macisasandwich** [comment]
I added the skip to header_rewrite just for the sake of it at the moment since I was adding it to multiplexer. But I suppose I will remove it since it's a bigger problem if header_rewrite doesn't build.

**Comment by dragon512** [comment]
[approve ci]

**Pull request merged**
