### PR TITLE
Improve logging documentation

### PR DESCRIPTION
**Pull request by danobi**
A couple of things happened in this patch:

1. Overhaul of comments in `Log.h` as well as fast path code in `LogObject` & `LogBuffer`. See commit message for more details.
2. Initial draft for logging internals document. This is supposed to be the canonical entry point for understanding logging code.

### CODE REVIEW

**Comment by danobi** [comment]
@zwoop, as promised in  #1623, here's the new documentation.

**Comment by persiaAziz** [comment]
squash please

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/207/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/192/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/189/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1888/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1779/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/318/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/451/

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/230/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/244/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1925/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/226/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1817/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/355/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/488/

**Comment by danobi** [comment]
Still want a squash? I think the commits make a lot of sense separately.

**Comment by persiaAziz** [comment]
I think it is better if you squash the commits, since these are related. The first commit is removing a lot of stuffs while the second commit is adding new. It will be easier to track in a single commit

**Comment by SolidWallOfCode** [comment]
I'll agree with @persiaAziz - it's probably better as a single commit.

**Comment by danobi** [comment]
#1679 needs to be landed first. I'll squash + update this PR afterwards. 

#1679 creates `doc/developer-guide/architecture`, which this should fall under.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/364/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/376/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/360/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2059/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1952/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/489/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/622/

**Pull request merged**
