### PR TITLE
TS-4387 Add enforcement of TSCont having MUTEX for TSContSchedule()

### PR DESCRIPTION
**Pull request by shenzhang920**
https://issues.apache.org/jira/browse/TS-4387

### CODE REVIEW

**Comment by zwoop** [comment]
This basically restores previous behavior right? If so, +1. Also, this should get back ported to 6.2.x IMO.

**Comment by bgaff** [comment]
Yep I'm 👍  on this too

**Comment by jpeach** [comment]
s/enforement/enforcement/

**Comment by jpeach** [comment]
+1 with the explanation from the Jira summarized in the commit message.

**Comment by shenzhang920** [comment]
Description:

When calling TSContSchedule()/TSContScheduleEvery(), the passed in parameter TSCont have to have MUTEX; otherwise if we call TSContSchedule()/TSContScheduleEvery() more than once using same TSCont, only the first call will take effect; all the following schedule are ignored due to MUTEX issue.

Root casue:

The first time calling TSHttpSchedule() with TSCont A (and TSCont A doesn't have a mutex), it creates Event A, assign thread A; while calling EThread::schedule(), e->continuation->mutex is NULL, so "e->mutex = e->continuation->mutex = e->ethread->mutex;" is executed.
Now Event A's mutex = TSCont A's mutex = thread A's mutex

The second time calling TSHttpSchedule() with TSCont A, it creates Event B, assign thread B;
while calling EThread::schedule(), e->continuation->mutex is NOT NULL, so "e->mutex = e->continuation->mutex;" is executed.
Now Event B's mutex = TSCont A's mutex (which actually is Event A's mutex)

Eventually, EventA and EventB use a same mutex which causes the second scheduling get ignored.

**Comment by bgaff** [comment]
@jpeach I'll clean up the commit message / clang-format before landing.

**Comment by jpeach** [comment]
OK thanks @bgaff

**Pull request closed without merging**
