### PR TITLE
TS-4657: SNI hook sends hook ID for events

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/719/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/615/ for details.

**Comment by zwoop** [comment]
Looks good, but fails on FreeBSD for some reason:

{code}
../../../iocore/net/SSLUtils.cc:384:27: error: use of undeclared identifier 'TS_SSL_CERT_EVENT'; did you mean 'TS_SSL_CERT_HOOK'?
  if (!netvc->calledHooks(TS_SSL_CERT_EVENT)) {
                          ^~~~~~~~~~~~~~~~~
                          TS_SSL_CERT_HOOK
../../lib/ts/apidefs.h:290:3: note: 'TS_SSL_CERT_HOOK' declared here
  TS_SSL_CERT_HOOK = TS_SSL_SNI_HOOK,
  ^
../../../iocore/net/SSLUtils.cc:384:27: error: cannot initialize a parameter of type 'TSEvent' with an rvalue of type 'TSHttpHookID'
  if (!netvc->calledHooks(TS_SSL_CERT_EVENT)) {
                          ^~~~~~~~~~~~~~~~~
../../../iocore/net/P_SSLNetVConnection.h:221:41: note: passing argument to parameter here
  bool calledHooks(TSEvent /* eventId */) const { return (this->sslHandshakeHookState != HANDSHAKE_HOOKS_PRE); }
                                        ^
{code}

**Comment by shinrich** [comment]
It looks like I had an error in the "compile against openssl 1.0.2" case.  FreeBSD must use openssl 1.0.2 and linux must use openssl 1.0.1.  Fixing.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/646/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/750/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
