### PR TITLE
back port "fix TS-4195: double free when stop trafficserver" to 6.2.x

### PR DESCRIPTION
**Pull request by zizhong**
Conflicts:
	proxy/Main.cc

### CODE REVIEW

**Comment by maskit** [comment]
@zizhong Could you include a reference for the original commit in your commit message?
https://cwiki.apache.org/confluence/display/TS/Git#Git-Cherry-Pick

**Comment by zizhong** [comment]
@maskit Thanks! Fixed.

**Comment by maskit** [comment]
[approve ci]

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/40/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1502/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1608/ for details.

**Comment by zizhong** [comment]
The build issue is fixed by this commit https://github.com/apache/trafficserver/commit/6bdc94e2747594e17161d3ed6a4c691d0fd49670

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/172/ for details.

**Comment by zizhong** [comment]
backport 6bdc94e to fix the build issue.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
Is the double free related to ICC build issues too?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1669/ for details.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/101/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1565/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/233/ for details.

**Comment by zizhong** [comment]
@PSUdaemon No. It's not related. When it got built, there were some ICC build issues, so I backport zwoop's fix too.

**Comment by zwoop** [comment]
So, my bad, but we reverted this on master, because of issues raised on the use of _exit(). Also, not sure I agree that the ICC changes should be rolled into this (if we were to back port this).

**Pull request merged**
