### PR TITLE
support full range of unsigned char for hex conversion.  

### PR DESCRIPTION
**Pull request by cmcfarlen**
Also, install tsutil/StringConvert.h

### CODE REVIEW

**Review by zwoop — DISMISSED** [review]
Awesome, thanks!

**Comment by JosiahWI** [comment]
The AuTest txn_box_multi-ramp-2 failed.

```
   Run: Multi bucketing 2: Failed
     Starting TestRun 0-tr : No Issues found - Passed
        Reason: Started!
     Process: Default: Passed
       Setting up : Copying '/home/jenkins/workspace/Github_Builds/autest/src/build/proxy-verifier-v2.10.1/linux-amd64' to '/tmp/sandbox/txn_box_multi-ramp-2/pv-client/bin' - Passed
       Setting up : Copying 'multi-ramp.replay.yaml' to '/tmp/sandbox/txn_box_multi-ramp-2/pv-client/multi-ramp.replay.yaml' - Passed
       Setting up : Copying '/home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/autest-site/../../tools/proxy-verifier/ssl/client.pem' to '/tmp/sandbox/txn_box_multi-ramp-2/pv-client/client.pem' - Passed
       Setting up : Copying '/home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/autest-site/../../tools/proxy-verifier/ssl/ca.pem' to '/tmp/sandbox/txn_box_multi-ramp-2/pv-client/ca.pem' - Passed
       Test : Checking that ReturnCode == 0 - Passed
          Reason: Returned Value: 0 == 0
       Time-Out : Process finishes within expected time - Passed
          Reason: Returned value: 2.0009992122650146 < 600.0
       file /tmp/sandbox/txn_box_multi-ramp-2/_output/0-tr-Default/stream.stdout.txt : There should be no Proxy Verifier violation errors. - Passed
          Reason: Contents of /tmp/sandbox/txn_box_multi-ramp-2/_output/0-tr-Default/stream.stdout.txt excludes expression
     Process: trailer: Skipped
        Reason: Was not started
     Process: log-watch: Failed
       Time-Out : Process finishes within expected time - Passed
          Reason: Returned value: 10.085412740707397 < 600.0
       file /tmp/sandbox/txn_box_multi-ramp-2/_output/0-tr-log-watch/stream.all.txt : Checking count. - Failed
          Reason: 'v1/video/alias' failed with 357 not in 250..350
```

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
