### PR TITLE
Fixes memory leaks in header_rewrite

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by randall** [comment]
This will not cleanly apply to 7.1.x or 8.0.x. I'll need to create separate pull requests for them if this is accepted.

**Comment by zwoop** [comment]
This has merge conflicts into 8.0.x, so we'll need a separate PR for this please.

**Comment by randall** [comment]
8.0.x PR https://github.com/apache/trafficserver/pull/4484

**Comment by randall** [comment]
7.1.x PR #4485

**Comment by bryancall** [comment]
I was able to apply this commit to the 8.1.x branch after reverting #4484 and applying ed1ded2623674bf6957a0faeb68a8ca10cb0725f / #4242

**Pull request merged**
