### PR TITLE
@OPENSSL_LIBS@ added into automake file

### PR DESCRIPTION
**Pull request by webdriverrr**
Re-opening PR regarding #2524

### CODE REVIEW

**Comment by webdriverrr** [comment]
This is required prior https://github.com/apache/trafficserver/issues/1560 task which is started by me recently.

**Comment by zwoop** [comment]
Is this related to the QUIC work? @masaori335 Do we want this on the QUIC branch, or master? Both?

**Comment by zwoop** [comment]
[approve ci].

**Comment by webdriverrr** [comment]
@zwoop not really related to QUIC but impacts overall build and codebase quality since doesn't allow to build 'test' target. What does it impact is _std::vector_ support all across the code (instead of custom _Vec_ implementation).

**Comment by zwoop** [comment]
Hmmm, but we run the "make check" on all builds in the CI, and aren't running into this. I'm not saying your fix is wrong, just curious as to why it's not causing problems on the CI.

**Comment by webdriverrr** [comment]
@zwoop that is very strange indeed. I've just checked 'make check' target on newly cloned repo from upstream and got the same error

`
/usr/bin/ld: libinknet.a(SSLNetVConnection.o): undefined reference to symbol 'X509_free@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:966: recipe for target 'test_UDPNet' failed
`

**Comment by webdriverrr** [comment]
Could it be due to some different way how does project got configured on different platforms (Ubuntu vs FreeBSD)?

**Comment by webdriverrr** [comment]
Checked CI target build log for Linux - it is OK except one thing - not enough verbosity to see how does _test_I_UDPNet.cc_ does build.
Can we enable verbosity with V=1 for _make check_

**Comment by masaori335** [comment]
@zwoop I want this on both branch to run the "make check". But quic branch is going to be rebased on master branch. So I don't want to cherry-pick this on quic branch right now.

**Comment by bryancall** [comment]
Why are tests building and working without this change?  Is this change necessary?

**Comment by webdriverrr** [comment]
@bryancall have no idea why they are building & working w/o these changes. But I am 100% confident that introducing these changes won't break anything.
BTW this is in regards of ^ - https://github.com/apache/trafficserver/pull/2547

**Pull request merged**
