### PR TITLE
TS-4068: Changes default for server_ports to include IPv6

### PR DESCRIPTION
**Pull request by zwoop**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/647/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/751/ for details.

**Comment by SolidWallOfCode** [comment]
Hmmm. This means the default ATS config will not work on the default CentOS 7 config because it doesn't by default configure IPv6 addresses.

**Comment by bryancall** [comment]
👍 - Looks good, yay ipv6!

**Comment by zwoop** [comment]
Alan, no, it'll work afaik. It'll only fail if you go out of the way and remove the IPv6 kernel module.

**Pull request merged**
