### PR TITLE
Small fix to regex_remap PR # 7347.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci clang-format]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by vmamidi** [comment]
#7347 reverses pristine behavior. This PR fixes the issue.

**Review by vmamidi — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
