### PR TITLE
Calling setrlimit() twice is redundant

### PR DESCRIPTION
**Pull request by jablko**
Set .rlim_cur to either .rlim_max or RLIM_INFINITY.
Doing both is redundant.

This is a follow-up to #1362. The first commit belongs to that PR.

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1273/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1380/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1382/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1275/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1383/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1276/ for details.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/57/

**Comment by atsci** [comment]
Intel CC build *failed*! https://ci.trafficserver.apache.org/job/icc-github/186/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/60/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/73/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1755/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1649/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/318/

**Comment by zwoop** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
Can you please fix the merge and build failures?

**Comment by oknet** [comment]
In the linux, the command ```ulimit -Ha``` shows the max value of limit and the command ```ulimit -Sa``` shows the current value of limit and these current values are always less or equal their max value.

There is a special value ```unlimited``` but the max values are not always ```unlimited```.
If ATS is running from ```root``` privileges, it can set current value to max and ```unlimited```.
If ATS is not, it can only set current value to max (we can check it by ```ulimit -Ha```).

the ```ink_max_out_rlimit(int which, bool max_it, bool unlim_it)``` is designed to:
1. set current value to max value
2. or set current value to unlimited.

**Comment by bryancall** [comment]
There hasn't been an update on this PR for over 60 days, so I am closing it for now.  Feel free to reopen the PR when you have updated it.

**Pull request closed without merging**
