### PR TITLE
Update http2.test.py

### PR DESCRIPTION
**Pull request by dragon512**
Change test to use python3 ( as h2client needs to use python3)

### CODE REVIEW

**Comment by dragon512** [comment]
I should not the we probably need to clean up the h2client to be used in general. @persiaAziz  will be able to help with this.

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
Please file an Issue on the cleanup task, so we know about it, and it gets assigned.

**Comment by dragon512** [comment]
https://github.com/apache/trafficserver/issues/1579 added to remind us about h2client.py clean up

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/50/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/53/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/179/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/66/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1748/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1642/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/311/

**Comment by zwoop** [comment]
I think we need to make the AU check succeed, right ?

**Comment by dragon512** [comment]
Something is messed up.. closing this and reopening it as https://github.com/apache/trafficserver/pull/1580

**Pull request closed without merging**
