### PR TITLE
ConectionTracker: remove include dep in proxy/http

### PR DESCRIPTION
**Pull request by bneradt**
I moved ConnectionTracker to iocore/net, but I missed that I accidentally brought in a dependency upon proxh/http to iocore through the extern Enable_Config_Var. This patch removes the explicit include dependency and updates the unit tests that had a link time undefined symbol error for Enable_Config_Var.

### CODE REVIEW

**Review by cmcfarlen — DISMISSED** [review]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci autest rocky debian]

**Comment by bneradt** [comment]
[approve ci autest rocky]

**Comment by bneradt** [comment]
[approve ci rocky autest]

**Review by cmcfarlen — APPROVED** [review]
Looks good.  Thanks!

**Pull request merged**
