### PR TITLE
Perf: Replace casecmp with memcmp in HPACK static table lookup

### PR DESCRIPTION
**Pull request by masaori335**
On HPACK encoding, `ptr_len_casecmp(const char *p1, int l1, const char *p2, int l2)` is used multiple times. It call `ParseRules::ink_tolower()` for both of given strings.
We can reduce these function calls by converting name in lower case at the beginning of the encoding.
https://github.com/apache/trafficserver/blob/26887c088c15287a2b159b29dacae7f0b79d5ce7/include/tscore/ink_string.h#L102-L103

The `ptr_len_casecmp()` in dynamic table lookup is still remaining. It should be dealing with another PR.

This depends on #6520.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by masaori335** [comment]
Rebased on the last master.

**Comment by masaori335** [comment]
[approve ci autest]
[approve ci clang-analyzer]

**Review by shinrich — APPROVED** [review]

**Review by maskit — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
