### PR TITLE
Add Base64 encoding/decoding to encryption/decryption.

### PR DESCRIPTION
**Pull request by duke8253**
When calling `EVP_Encrypt` related functions and their decryption counterparts, it is not guaranteed to have no null bytes in the middle of the whole output, so we need to encode it with Base64 to avoid redis sending partial data.

Also made some general cleanup to the code, mostly to the debug outputs. Code changes are mostly made in the following files:
```
common.cc
common.h
publish.cc:243
session_process.cc
ssl_key_utils.cc
```

### CODE REVIEW

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
Weird that autest is using the old version of code after force push kicked it off, trying manual trigger.

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
[approve ci clang-analyzer]

**Comment by duke8253** [comment]
[approve ci]

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
