### PR TITLE
Backport 2219 to 7.1.x: Fix protocol stack to not skip TLS tag on error.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Backport of #2219.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
Looking at the AUTest failure, there is no way this can pass. I tried fixing it with another PR, #2227, but that was unsuccessful. I don't have any suggestions on how to work past this.

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Pull request merged**
