### PR TITLE
Adding autopep8 as a pre-commit hook.

### PR DESCRIPTION
**Pull request by bneradt**
This works locally. Feel free to leave feedback, but in the meantime I'll send an email to the dev mailing list to confirm that the community feels comfortable adding this to our pre-commit hook.

### CODE REVIEW

**Comment by bneradt** [comment]
I removed the draft status on this since the community seems interested in getting this hook integrated.

**Comment by bryancall** [comment]
[approve ci]

**Comment by randall** [comment]
[approve ci docs]

**Comment by bneradt** [comment]
This would be helpful to backport to 9.0.x.

### Backport Rationale

If we do not backport, people will face an annoyance if they transition from master branch back to 9.0.x branch locally. Until they perform a make or make install, they will have the master's version of the .git/hooks/pre-commit hook which will try to reference tools/autopep8.sh which will no longer exist in the 9.0.x branch. The solution will be to perform a make install which will correct the .git/hooks/pre-commit hook, but if they don't they'll be confused as to why their pre-commit hook doesn't work when it says it cannot access tools/autopep8.sh.

I assume this happened when we first introduced tools/clang-format.sh as well.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
