### PR TITLE
Autest: Test revalidating cached objects

### PR DESCRIPTION
**Pull request by mlibbey**
- Chunked object with Range request and 304 (for #3413)
- INM, IMS validations

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by dragon512** [comment]
I need to run this locally to see why the report is saying there is a difference, but not showing anything different in the gold file

**Comment by mlibbey** [comment]
I believe there's a whitespace difference at the end of the file. But. It passes on my machine and not the CI. So, that last newline sometimes works and sometimes doesn't depending on "something."

**Comment by randall** [comment]
[approve ci autest]

**Comment by mlibbey** [comment]
Finally passing CI tests.

**Comment by zwoop** [comment]
This is looking good, but we probably need to merge #4780 before we land this.

@dragon512 What do you think? Does this look good to you?

**Comment by zwoop** [comment]
[approve ci autest]

**Pull request merged**
