### PR TITLE
TS-4088: Add support for BoringSSL

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by zwoop** [comment]
Looks good to me, ship it!

**Comment by shinrich** [comment]
Looks good to me as well.

**Comment by jpeach** [comment]
+1 after fixing review comments. We should aim to not have to use ```OPENSSL_IS_BORINGSSL```.

**Comment by zwoop** [comment]
James, the problem is that if you do what you suggest, it likely will fail. It will still find that OpenSSL include file (because it's likely to be on the system), and it conflicts with BoringSSL. This is what I recall from testing this before.

**Comment by jpeach** [comment]
Oh that's a bit nasty, we should add a comment to that effect. I think it would be best to consolidate the openssl includes in one header so we can capture this kind of weirdness in just one place.

**Comment by zwoop** [comment]
Yeah, that's a good idea (putting all SSL library weirdness in one file).

**Pull request closed without merging**
