### PR TITLE
Don't call next next dup on destroyed mime field mloc.

### PR DESCRIPTION
**Pull request by ywkaras**
plugins/background_fetch/headers.cc
plugins/cache_range_requests/cache_range_requests.cc
plugins/experimental/access_control/headers.cc
plugins/experimental/cache_fill/background_fetch.cc
plugins/header_rewrite/operators.cc
plugins/prefetch/headers.cc

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci Clang-Analyzer]

**Review by randall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
Cherry-picked to v9.1.x branch.

**Comment by zwoop** [comment]
@ezelkow1 This may be a candidate for 8.1.x as well ?

**Comment by ezelkow1** [comment]
> 
> 
> @ezelkow1 This may be a candidate for 8.1.x as well ?

Agreed, @ywkaras you mind doing a backport PR for 8.1?

**Comment by ywkaras** [comment]
OK.  I assume we need to backport https://github.com/apache/trafficserver/pull/7825 also.

**Pull request merged**
