### PR TITLE
TS-3938: Add hardening (fortify) as an option to configure

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by zwoop** [comment]
Does any of these flags change with the choice of compiler? LLVM / clang? Also, FORTIFY_SOURCE is good, we've had it trip in prod at least once (which is a good thing :).

**Comment by jpeach** [comment]
FWIW https://wiki.debian.org/Hardening

**Comment by dragon512** [comment]
The sed command seems hacky to me. It would be clearer if we have a SHCXXFLAGS, etc ( ie Shared library flags or we can do the other way and make a PROGCXXFLAGS) so we can build them without the pie.

**Comment by dragon512** [comment]
The other question I would have is why would we not want -fPie enable for any compiler that supports it.

**Comment by bryancall** [comment]
I updated to remove `-fno-omit-frame-pointer`.

@dragon512
Most distributions do hardening themselves.  I think it would be better have an option for it.

Yes, it is a little hacky, but less lines and simpler than creating additional variables that would only be used for tsxs.

**Comment by jpeach** [comment]
> I think it would be better have an option for it.

I agree it should be an option, but let's consider defaulting it to "on" for 7.0

**Comment by bryancall** [comment]
@dragon512 
One benefit of doing the sed at the end of the process is that the FLAGS are in sync.  Adding addition variables would require that we don't modify the FLAGS in configure.ac after they are copied.

**Comment by bryancall** [comment]
@jpeach 
Do you foresee any issues with doing a double hardening (distributions doing it and having it on by default)?

**Pull request closed without merging**
