### PR TITLE
TS-4588: Require braces around statements.

### PR DESCRIPTION
**Pull request by jpeach**
Require bodies of if statements and loops (for, range-for, do-while,
and while) to be inside braces.

This is a automated change made with clang-tidy and clang-format.
Header files are not included because they are not emitted into the
compilation database.

### CODE REVIEW

**Comment by jpeach** [comment]
Ping @zwoop @PSUdaemon

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/343/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/237/ for details.

**Comment by PSUdaemon** [comment]
Is there a `.clang-tidy` config we can add and run with `make` like `make clang-tidy`?

Also, is this an alternative proposal to #739, or in addition to?

**Comment by jpeach** [comment]
This would be in addition to #739. We should be able to implement ``make tidy`` but it is not there yet.

**Comment by zwoop** [comment]
@PSUdaemon Please review.

**Comment by jpeach** [comment]
Abandoning this PR for now. Will go back and look into getting ``clang-tidy`` support into the build system.

**Pull request closed without merging**
