### PR TITLE
More cripts

### PR DESCRIPTION
**Pull request by zwoop**
This also reruns clang-tidy over the entire code, and a number of related cleanup.

### CODE REVIEW

**Comment by JosiahWI** [comment]
The AuTest proxy_protocol failed.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Review by cmcfarlen — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
