### PR TITLE
TS-4132 Open source Yahoo's ats-inliner plug-in

### PR DESCRIPTION
**Pull request by dmorilha**
@bryancall for your considerations,

there are still `README` file pending

### CODE REVIEW

**Comment by dmorilha** [comment]
@sc0ttbeardsley do you think this `README` files explains it well? https://github.com/dmorilha/trafficserver/blob/28456734fbc604b0115d1582dd2bf1b230263cdf/plugins/experimental/inliner/README

**Comment by jpeach** [comment]
Let's squash this branch a bit to improve clarity. All the code changes should go into the first commit, then the build integration and documentation in the second.

WRT  ``printf`` formats, please use ``PRId64``.

**Comment by dmorilha** [comment]
@jpeach all done

**Comment by jpeach** [comment]
@dmorilha You mean ```"%" PRId64 ""```

**Comment by dmorilha** [comment]
good point!

**Comment by mlibbey** [comment]
Re: doc. I think the read me is a great start. Is the plugin a global or remap plugin?

**Comment by sc0ttbeardsley** [comment]
@dmorilha ya, looks pretty good. We should add some details about adding the remaps for image asset urls since that is a bit tricky. Also we should add in this image?

ats image inliner 1

**Comment by dmorilha** [comment]
I will make sure to squash it again once we reach an agreement here.

**Comment by bryancall** [comment]
I reviewed this before in our work repository and I am happy with it.

**Comment by sc0ttbeardsley** [comment]
@mlibbey it is a global plugin. @dmorilha we should add a "how to configure and use" section in the readme. I'll send you a PR if I get a chance

**Pull request closed without merging**
