### PR TITLE
TS-2470: Remove PCT metrics

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/599/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/495/ for details.

**Comment by zwoop** [comment]
I applied the patch, and could not see any remnants of _pct metrics.

:+1:

**Comment by reveller** [comment]
I reviewed the change.  After applying the patch, I ran `grep -rIi _pct --exclude=\*.{Po,Plo} * | grep -v -E 'file_max_pct|bytes_pct'`.  The output was insignificant and showed no signs of any remaining calculated percentage statistics.

**Pull request merged**
