### PR TITLE
Fix spelling errors reported by lintian

### PR DESCRIPTION
**Pull request by jbfavre**
While packaging trafficserver for Debian, lintian reported spelling errors which I decided to fix.

### CODE REVIEW

**Comment by jbfavre** [comment]
done !

**Comment by scw00** [comment]
thanks

**Comment by scw00** [comment]
[approve ci]

**Comment by scw00** [comment]
You may need to run “make clang-format” to make clang-format check happy.

**Comment by jbfavre** [comment]
Didn't knew (or forgot) about clang-format.
I've updated the PR.
Should be good now

**Comment by scw00** [comment]
[approve ci]

**Pull request merged**
