### PR TITLE
[TS-4443] regex_remap: fix $i substitution

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by zwoop** [comment]
Yep, this looks much better. I'll do another round of reviews in a little bit.

Thanks!

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
I ran the CI on this, unfortunately the patch does not format with clang-format. See e.g. https://ci.trafficserver.apache.org/view/github/job/Github-Linux/74/console

**Comment by zwoop** [comment]
One more thing: This seems to only be for IPv4. I think we should support both v4 and v6, so in addition to the code that is here to be modified for IPv6, we also have to bump up the max length accordingly.

I'd be fine with just bumping it up to 39, or 46, or perhaps INET6_ADDRSTRLEN (is that cross platform) ?). E.g.

    diff --git a/plugins/regex_remap/regex_remap.cc b/plugins/regex_remap/regex_remap.cc
    index ad973ce..4ef0daf 100644
    --- a/plugins/regex_remap/regex_remap.cc
    +++ b/plugins/regex_remap/regex_remap.cc
    @@ -532,7 +532,7 @@ RemapRegex::get_lengths(const int ovector[], int lengths[], TSRemapRequestInfo *
             len += req_url->matrix_len;
             break;
           case SUB_CLIENT_IP:
    -        len += 15; // Allow for 255.255.255.255
    +        len += INET6_ADDRSTRLEN; /* is this cross platform? */
             break;
           default:
             break;

**Comment by yatsukhnenko** [comment]
In addition to INET6_ADDRSTRLEN I think we should use inet_ntop instead of inet_ntoa

**Comment by zwoop** [comment]
Yep, that was the first portion of my reply :).

**Comment by jpeach** [comment]
If you don't mind using internal APIs, use ``ats_ip_ntop`` from ``ink_inet.h``.

**Comment by zwoop** [comment]
Since this is a "core" plugin, ats_ip_ntop() ought to be fine. It doesn't require anything other than C++ and the #include file, right? @jpeach We probably need to document these things somewhere, explaining that using lib/ts from plugins is fine ?

**Comment by yatsukhnenko** [comment]
done

**Comment by zwoop** [comment]
.

**Comment by yatsukhnenko** [comment]
You had to say [approve ci] 😉

**Comment by zwoop** [comment]
looks good to me, passes CI build tests on Linux/FBSD.

**Pull request merged**
