### PR TITLE
TS-4482: To freely output to custom log

### PR DESCRIPTION
**Pull request by yishimur**
Modify the contents are as follows:
* add note field on logging
* add CPP API functions named noteStringSet / Get
* add StringHashMap on lib/ts/Map.h in order to store note fields data

note field format is same as each of header
```
%<{key name}note>
```

### CODE REVIEW

**Comment by zwoop** [comment]
Testing again, this will blow up and I'm blaming @PSUdaemon [approve ci]

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/202/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/309/ for details.

**Comment by zwoop** [comment]
@jpeach you had some concerns on this concept ?

**Pull request closed without merging**
