### PR TITLE
Add diags log message when cache wraps.

### PR DESCRIPTION
**Pull request by shinrich**
Requested by our operations guys  to better track wraps.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1411/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1304/ for details.

**Comment by SolidWallOfCode** [comment]
I put this in to Y!'s fork but I have mixed feelings about it. It has been handy for our operations team but I'm not sure it is of sufficient general utility. One outstanding request which might obviate the utility of this is making the wrap stat persistent, which it is not currently.

**Comment by SolidWallOfCode** [comment]
Approved by the PMC chair, shipping it.

**Pull request merged**
