### PR TITLE
Select lua context per thread

### PR DESCRIPTION
**Pull request by shukitchan**
This should reduce chances for thread to use the same lua context to handle requests. 
And that should help to lower cpu load

### CODE REVIEW

**Comment by shukitchan** [comment]
Still testing in production environment

**Comment by shukitchan** [comment]
This change is actually suggested by @shinrich and she has been testing an earlier version of this fix.

**Comment by shukitchan** [comment]
I have tested this out in our production environment. It looks good.

**Comment by shinrich** [comment]
Looks good to me

**Comment by bryancall** [comment]
@traeak is going to look at it.

**Comment by SolidWallOfCode** [comment]
Probably OK, but I think it should use `thread_local`  ([documentation](https://en.cppreference.com/w/cpp/language/storage_duration)). That is potentially faster and avoids the key management logic.

**Comment by shukitchan** [comment]
lua plugin is C, not C++

**Comment by traeak** [comment]
We might want to change how the lua states are configured since a context ends up being sticky per thread.  Perhaps we should change things so that we configure number of threads per context (default to 1 thread per context).

**Comment by shukitchan** [comment]
It may be useful to have less context than thread for limiting the memory used. 
I don't think it makes sense to have more context than thread. 

So that's why i still have the configuration for the total number of context.

**Comment by traeak** [comment]
before i think transactions would just grab the next context on the list.  So lua script context usage would cycle through the whole list regardless of cpus
With  the new configuration each thread grabs a context and holds onto it.
So instead of configuring a global pool then the configuration might be better applied to the number of per thread lua context pools (defaulting to one context per thread, technically one for remap and one for global).

**Review by traeak — APPROVED** [review]
These changes are fine and will work for us.  I will generate issue tickets if I have any ideas on improvements.  We do need to make it clear to end users that luajit 2.10. beta3 with default 64bit GC is the one that should be used.

**Comment by zwoop** [comment]
@shukitchan I'm ok with this for 9.1.x, but unless you feel super strongly, I don't think we should get this in for 9.0.x (it's a performance optimization as I understand this).

**Pull request merged**
