### PR TITLE
Issue #1359: Flaw in TS-2157 port in server address may be unset

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by zwoop** [comment]
Is this a 7.1.0 back port candidate?

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1371/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1264/ for details.

**Comment by shinrich** [comment]
Would be reasonable to backport.  We will be pulling it back into our version of 7.1

**Comment by bryancall** [comment]
TS-2157 pull request: #182

**Comment by bryancall** [comment]
👍 - Looks good

**Pull request merged**
