### PR TITLE
TS-4483: NetAccept & SSLNetAccept Optimize, replace getEtype() with member etype.

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by zwoop** [comment]
What's the Jira # for this?

**Comment by oknet** [comment]
Sorry, forget to create it, please link to TS-4483.

**Comment by zwoop** [comment]
Cool. Can you rename Subject line for this PR to include the Jira # please?

**Comment by shinrich** [comment]
I thought we were getting rid of the SSL threads (and thus ET_SSL).  If so, we could probably do some more simplification here.

**Comment by oknet** [comment]
@shinrich ET_SSL is still here. SSLNetAccept::etype is set to ET_SSL by sslNetProcessor::upgradeEtype().

**Comment by shinrich** [comment]
Yes, I know it is still there.  Just bringing up the broader issue since you are working in that area anyway.  @zwoop and @SolidWallOfCode am I remembering correctly that ultimately we are looking at getting rid of the SSL threads?

**Comment by zwoop** [comment]
Ya, I believe the idea was to eliminate ET_SSL for 7.0.0. See https://issues.apache.org/jira/browse/TS-3046.

**Comment by jpeach** [comment]
This looks very reasonable to me. @oknet can you please rebase onto master?

**Comment by oknet** [comment]
@jpeach create a new PR#734 base on master.

**Pull request closed without merging**
