### PR TITLE
TS-5095: IOBufferReader::read_avail adds to CPU utilization

### PR DESCRIPTION
**Pull request by shinrich**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1260/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1155/ for details.

**Comment by zwoop** [comment]
Nice! Any details on what the impact / symptoms for this is?

**Comment by shinrich** [comment]
Some details in the jira description.  We noticed this when we moved to a newer compiler and started building against openssl 1.0.2.  Somewhere in that change, the communication patterns must have resulted in more, smaller reads which created longer io block chains.  We saw a very noticeable increase in CPU utilization, and perf top pointed the finger at read_avail.

**Pull request merged**
