### PR TITLE
remove example/plugins/cpp-api

### PR DESCRIPTION
**Pull request by cmcfarlen**

### CODE REVIEW

**Review by bneradt — APPROVED** [review]

**Comment by bneradt** [comment]
[approve ci rocky]

**Comment by bneradt** [comment]
[approve ci rocky]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci osx]

**Comment by cmcfarlen** [comment]
[approve ci osx]

**Comment by traeak** [comment]
[approve ci freebsd]

**Pull request merged**
