### PR TITLE
Remove unnecessary cast from ReverseProxy.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Review by masaori335 — APPROVED** [review]
Looks reasonable

**Comment by masaori335** [comment]
[approve ci autest clang-analyzer]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
[approve ci autest clang-analyzer]

**Comment by ywkaras** [comment]
[approve ci clang-analyzer]

**Comment by ywkaras** [comment]
This doesn't change run-time behavior, so not strictly necessary in 9.0.x.  But it would be very safe to back-merge it, if that helps prevent conflicts for later back-merges.

**Pull request merged**
