### PR TITLE
TS-5105: Do vc->con.setRemote(target) before socksEntry->init()

### PR DESCRIPTION
**Pull request by oknet**
(cherry picked from commit 25140ce7b2d2d8214bbc22dde6a2db9144ff2693)

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1177/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1282/ for details.

**Comment by zwoop** [comment]
Marking this for 6.2.2 for now, unless we need to respond 6.2.1? Also, this has build issues I think?

**Comment by oknet** [comment]
@zwoop the build failed on regression test and I think it is not caused by this patch. could you please check the build log for details ?

**Comment by zwoop** [comment]
Trying a new  build [approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1204/ for details.

**Comment by oknet** [comment]
It is crash in ats_base64_encode during regression test.

```
traffic_server: Aborted (Signal sent by tkill() 2585 989)
traffic_server - STACK TRACE: 
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server(crash_logger_invoke(int, siginfo_t*, void*)+0xc3)[0x5096f4]
/lib64/libpthread.so.0(+0xf370)[0x7f601e88f370]
/lib64/libc.so.6(gsignal+0x37)[0x7f601d7651d7]
/lib64/libc.so.6(abort+0x148)[0x7f601d7668c8]
/var/jenkins/workspace/Github-Linux/1204/install/lib/libtsutil.so.6(ink_fatal_va(char const*, __va_list_tag*)+0x0)[0x7f60203891fd]
/var/jenkins/workspace/Github-Linux/1204/install/lib/libtsutil.so.6(ink_fatal(char const*, ...)+0x0)[0x7f60203892b6]
/var/jenkins/workspace/Github-Linux/1204/install/lib/libtsutil.so.6(ink_pfatal(char const*, ...)+0x0)[0x7f6020389355]
/var/jenkins/workspace/Github-Linux/1204/install/lib/libtsutil.so.6(ats_base64_encode(unsigned char const*, unsigned long, char*, unsigned long, unsigned long*)+0x0)[0x7f6020386d96]
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server[0x56ce19]
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server(INKContInternal::handle_event(int, void*)+0xe5)[0x520b83]
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server(Continuation::handleEvent(int, void*)+0x72)[0x50c662]
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server(EThread::process_event(Event*, int)+0x136)[0x79e4dc]
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server(EThread::execute()+0x288)[0x79e8e8]
/var/jenkins/workspace/Github-Linux/1204/install/bin/traffic_server[0x79dabd]
/lib64/libpthread.so.0(+0x7dc5)[0x7f601e887dc5]
/lib64/libc.so.6(clone+0x6d)[0x7f601d82773d]
```

**Comment by oknet** [comment]
Sorry, it is my fault, the commit 724f7cb5cc2c689d618ad306b5ca5795aec88b11 did not merge into 6.2.x. I should rewrite the patch working with vc->server_addr.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1310/ for details.

**Comment by PSUdaemon** [comment]
@oknet What is the plan with this PR?

**Comment by oknet** [comment]
Sorry, I'm busy on our product release. I will update this PR recently.

2017-02-11 11:02 GMT+08:00 Phil Sorber <notifications@github.com>:

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/64/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1527/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1631/ for details.

**Comment by oknet** [comment]
There is another bug that related to "proxy.config.socks.default_servers", I will make a backport for TS-5106 to fix it.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/196/ for details.

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/65/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/linux-github/1528/ for details.

**Comment by atsci** [comment]
Intel CC build *failed*! See https://ci.trafficserver.apache.org/job/icc-github/66/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1632/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1633/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1529/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/197/ for details.

**Comment by atsci** [comment]
clang-analyzer build *failed*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/198/ for details.

**Comment by oknet** [comment]
clang-analyzer failed due to:

TS-4729: Fix dead assignment. (29bc28a713463eb815524a91e03be95fe3aeedb1)
Remove dead store. (67efb389b890919237248ed437c7af1d01559bf1)
TS-4367: Failed clang-analyzer, memory leak in mgmt/api (1cff52240584e5e6dccee63a02ab70ce61a961a2)
TS-4479: Clang-analyzer failure, Potential memory leak (87d1fc5d17d82ebb8f06f4138ca82b6e3b57179c)
TS-4366 Uninitialized stack value used in mp4 plugin (77bd40ba19f29b11873c1709485b64840d137dde)

**Comment by PSUdaemon** [comment]
@oknet I think these have been fixed in 6.2.x upstream and you need to rebase.

**Comment by atsci** [comment]
Intel CC build *successful*! See https://ci.trafficserver.apache.org/job/icc-github/104/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/linux-github/1569/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/freebsd-github/1673/ for details.

**Comment by atsci** [comment]
clang-analyzer build *successful*! See https://ci.trafficserver.apache.org/job/clang-analyzer-github/236/ for details.

**Pull request merged**
