### PR TITLE
fix log_rolling bug

### PR DESCRIPTION
**Pull request by phonehold**
This patch will be fix https://github.com/apache/trafficserver/issues/2544

### CODE REVIEW

**Comment by scw00** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
Slightly concerned about this, just adding a "close" to this. I worry that there might now be a race condition, where something might still try / want to write to the now closed file?

**Comment by bryancall** [comment]
This PR hasn't been updated in more then 2 months and I am closing out PRs that haven't had any updates.  Please feel free to reopen if want to update it.

**Pull request closed without merging**
