### PR TITLE
Add dockerfile for building h3 tools for testing

### PR DESCRIPTION
**Pull request by cmcfarlen**

### CODE REVIEW

**Comment by zwoop** [comment]
Wonder if it'd nicer to do something like

```
tools/http3/Dockerfile
```

**Comment by zwoop** [comment]
@cmcfarlen remember to set labels, Milsetone etc.

**Comment by bryancall** [comment]
The build_h3_tools.sh script uses tags for each of the tools.

**Comment by zwoop** [comment]
[approve ci autest]

**Review by zwoop — CHANGES_REQUESTED** [review]
Couple of suggestions:

1. As Bryan pointed out, we should "freeze" the versions of each of these. If you do, maybe also update the build_h3_tools.sh script accordingly so we have the same versions consistently?
2. Instead of -j20, maybe something like ```-j$(nproc)```  ?

**Comment by cmcfarlen** [comment]
[approve ci autest]

**Review by zwoop — APPROVED** [review]

**Pull request merged**
