### PR TITLE
test with microDNS

### PR DESCRIPTION
**Pull request by persiaAziz**
@zwoop this requires dnslib package

### CODE REVIEW

**Comment by maskit** [comment]
Please run `make autopep8`.

**Comment by persiaAziz** [comment]
for some reason 'make autopep8' is getting stuck in my machine

**Comment by persiaAziz** [comment]
I manually ran autopep8, that worked. We need to remove the env-test directory from the list of directories 'make autopep8' runs on

**Comment by dragon512** [comment]
@zwoop We need to update the CI VM to have the new python package

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Boom!

**Pull request merged**
