### PR TITLE
Issue #2183 Fix openssl 1.1 hang

### PR DESCRIPTION
**Pull request by shinrich**
Add node iteration to fix the openssl hanging.

### CODE REVIEW

**Comment by shinrich** [comment]
Updated.  Silly error.  I don't have an openssl 1.1 test system up yet, so I haven't actually run this yet.

**Comment by zwoop** [comment]
This is probably correct, but unfortunately does not fix the issues in #2183 (completely).

**Comment by shinrich** [comment]
@zwoop if you disable TLS session reuse, do the problems go away on docs?  Would be good to confirm, so I'm looking in the right area.

**Comment by zwoop** [comment]
Ship it!

**Comment by zwoop** [comment]
Cherry picked to 7.1.x

**Pull request merged**
