### PR TITLE
Coverity 1022187: remove test_passed_mime_hdr_clone

### PR DESCRIPTION
**Pull request by persiaAziz**

### CODE REVIEW

**Comment by dragon512** [comment]
This is the standard.

Coverity #number : info

**Comment by persiaAziz** [comment]
@jpeach please review

**Comment by jpeach** [comment]
@persiaAziz This looks like it fixes the Coverity report, but it would be great if you could take a look at improving this test. It seems to signal failures with `SDK_RPRINT`, which doesn't actually set a failed test status.

**Comment by persiaAziz** [comment]
[approve ci]

**Comment by zwoop** [comment]
[approve ci]

**Pull request merged**
