### PR TITLE
coverity 1021940, 1021941 fix: using invalid iterator in esi plugin

### PR DESCRIPTION
**Pull request by shukitchan**
coverity 1021940, 1021941 fix: using invalid iterator in esi plugin

### CODE REVIEW

**Comment by shukitchan** [comment]
forgot clang-format. updating now

**Comment by shukitchan** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
Please squash (we prefer not to have clang-format commits separate).

**Comment by shukitchan** [comment]
@zwoop commit squashed!

**Pull request merged**
