### PR TITLE
Doc: Update plugin stats documentation.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
I wanted to tell a co-worked to use the plugin stats but noticed they were not in fact well documented.

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/113/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/127/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/110/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1809/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/239/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1700/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/371/

**Comment by SolidWallOfCode** [comment]
I'll see what I can do, @jpeach. This already includes code from the `example/statistic` plugin. In practice double registering is normally done by avoiding the double register path but I'll see if I can make an example for that. I presume that otherwise you think the update looks good.

**Comment by jpeach** [comment]
> On Mar 28, 2017, at 2:08 PM, Alan M. Carroll <notifications@github.com> wrote:
> 
> I'll see what I can do, @jpeach. This already includes code from the example/statistic plugin. In practice double registering is normally done by avoiding the double register path but I'll see if I can make an example for that. I presume that otherwise you think the update looks good.

Oh I see. Yeh that's nice.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/148/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/163/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/146/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1735/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/274/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1844/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/406/

**Pull request merged**
