### PR TITLE
Doc: Fix up TSOverridable config values. Copied directly from source.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Also changed from member to macro because I think macro overall works better in this aspect.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by SolidWallOfCode** [comment]
[ci approve autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Pull request merged**
