### PR TITLE
Fixes minor memory leak in configure_net

### PR DESCRIPTION
**Pull request by randall**
This was introduced in 58b154bb6f253ac8660bd778dd2bf43cb7b60687

### CODE REVIEW

**Comment by zwoop** [comment]
I assume this is an 8.1.x candidate too ?

**Comment by randall** [comment]
> I assume this is an 8.1.x candidate too ?

I think so. It applies cleanly.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Comment by zwoop** [comment]
Cherry-picked to 8.1.x

**Pull request merged**
