### PR TITLE
Plugin debugging feature

### PR DESCRIPTION
**Pull request by chenglongwei**
1. Add http plugin hook library path configuration in records.config:
   "CONFIG proxy.config.http.plugin_hook_library_path STRING [path_of_httpdebugger.so]"
  2. Add http debug interfaces in ts.h
  3. Init the four interfaces in Main.cc
  4. Modify Http state machine to call debug interfaces.
  5. Add an example to implement http debug shared library.

### CODE REVIEW

**Comment by chenglongwei** [comment]
#1624

**Comment by bryancall** [comment]
It would be better to make these normal transaction hooks and use the TSHttpHookAdd() function to  add the hook.  Then you can use the normal plugin.config to load the plugin.

**Comment by zwoop** [comment]
Yes, I'm very much -1 on adding new plugin APIs and specially the loading of a .so via records.config.

**Comment by chenglongwei** [comment]
This debugging feature is mainly used to debug plugins. I also modified the title to avoid confusedness.
This debugging requires to know 'before or after' 'what hook id', 'what plugin' modifies 'what contents' of request/response headers. The plugin-like debugging method you mentioned might not work for this requirements.
1. Use this plugin-like method, we could not get the idea about which debugged plugin is executing. Because using this method, we could only get current TSCont, event and edata. ```plugin_handler(TSCont contp, TSEvent event, void *edata)``` We would lose clues about the debugged plugin.
2. Generally plugin interested events are one-to-one relationship to http hooks. And in plugins, event is used to decide which hook id current transaction is executing. Using this plugin-like method, we only get event "TS_EVENT_HTTP_PLUGIN_CALL_BEFORE" or "TS_EVENT_HTTP_PLUGIN_CALL_AFTER". Our debugger would not know current debugged hook id.
3. Original TS_EVENT_XXX would happen sequently just as TS_HTTP_XXX hooks. This idea would be very complex because "TS_EVENT_HTTP_PLUGIN_CALL_BEFORE" and "TS_EVENT_HTTP_PLUGIN_CALL_AFTER" would happen every now and then with normal TS_HTTP_XXX hooks as well as "TS_HTTP_PLUGIN_CALL". Fire events "TS_EVENT_HTTP_PLUGIN_CALL_BEFORE", "TS_EVENT_HTTP_PLUGIN_CALL_AFTER" to triger hook "TS_HTTP_PLUGIN_CALL" is not easy to implement.

**Comment by bryancall** [comment]
[approve ci]

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/126/

**Comment by atsci** [comment]
Linux build *failed*! https://ci.trafficserver.apache.org/job/linux-github/1716/

**Comment by atsci** [comment]
clang format *failed*! https://ci.trafficserver.apache.org/job/clang-format-github/129/

**Comment by atsci** [comment]
RAT check *failed*! https://ci.trafficserver.apache.org/job/RAT-github/143/

**Comment by atsci** [comment]
FreeBSD11 build *failed*! https://ci.trafficserver.apache.org/job/freebsd-github/1825/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/387/

**Comment by atsci** [comment]
Intel CC build *failed*! https://ci.trafficserver.apache.org/job/icc-github/255/

**Comment by chenglongwei** [comment]
@bryancall Last time you approved CI, but the CI system had some issues. "ERROR: Error cloning remote repo 'origin'". It seems this error is not related with my code. Could you please approve CI again?

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
I don't know if this was the intent, but this PR is against 6.2.x.

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/176/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/173/

**Comment by atsci** [comment]
RAT check *failed*! https://ci.trafficserver.apache.org/job/RAT-github/191/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1872/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1763/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/303/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/436/

**Comment by PSUdaemon** [comment]
Looks like the `HttpPluginHook.*` files do not have an appropriate license at the top. Also, the commit message does not have a note about the commit this is being cherry picked from.

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/218/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/232/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/214/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1805/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/343/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1913/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/476/

**Comment by bryancall** [comment]
@chenglongwei 
Are you wanting to get timing information on the execution of the plugin?

**Comment by chenglongwei** [comment]
@bryancall Not really, currently we mainly focus on the functionality of plugin. We want to know for one request, what headers are changed by plugins at each registered hook. 
This will allow engineers to identify issues due to plugin bugs and help them make sense of various changes happening throughout the request/response pipe.

**Comment by bryancall** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
It seems like this is *not* a backport and is in fact a new feature. I am going to close this as I don't think it is a candidate for 6.2.x.

**Pull request closed without merging**
