### PR TITLE
clarifies traffic_ctl dependency on traffic_manager

### PR DESCRIPTION
**Pull request by d2r**
I did not update the Japanese [localized text](https://github.com/apache/trafficserver/blob/a7be6ec083dc3d7aafd6f392b7dc841957d3a26a/doc/locale/ja/LC_MESSAGES/admin-guide/introduction.en.po#L435-L440) because it seems out of date, and also because I don't know Japanese.

### CODE REVIEW

**Comment by maskit** [comment]
Don't worry about the localized text. There's no need to touch `*.po` files when you update docs. The updated paragraph will be shown in English, which is more helpful than obsolete localized text.

**Comment by d2r** [comment]
> Describing the relationship between traffic_ctl and traffic_manager here seems a bit abrupt to me. Where did the idea come from? The background maybe helpful for who experienced the same issue.

The idea came to me when I tried to reproduce a possible bug in `traffic_ctl`. According to the [docs](https://docs.trafficserver.apache.org/en/latest/appendices/command-line/traffic_ctl.en.html) can be used to control and configure Traffic Server. So I started the `traffic_server` daemon and ran `traffic_ctl`. However, this errored because it failed to connect to an unspecific socket. Others suggested to me that I might start the `traffic_manager` daemon as well, and pointed me to the [admin doc](https://docs.trafficserver.apache.org/en/latest/admin-guide/introduction.en.html#traffic-server-processes) describing the Traffic Server processes. Except nothing points out the run-time dependency that `traffic_ctl` has on `traffic_manager`.  If the latter is not up and running, then `traffic_ctl` commands will fail.

So the idea is to communicate that `traffic_manager` needs to be running before `traffic_ctl` will work. I am open to suggestions.

**Comment by maskit** [comment]
I see. In that case, I'd write like "To use traffic_ctl, traffic_manager need to be running...", as you explained on the comment. It looks more clear to me.

It may be more better if it was explained on [Interacting with Traffic Server](https://docs.trafficserver.apache.org/en/latest/admin-guide/interaction/index.en.html). Because I think that users would find the page rather than introduction page when `traffic_ctl` doesn't work.

**Comment by d2r** [comment]
OK, I can revise it.

> It may be more better if it was explained on Interacting with Traffic Server. Because I think that users would find the page rather than introduction page when traffic_ctl doesn't work.

This doc seems empty. What about adding the details to the existing page for [traffic_ctl](https://docs.trafficserver.apache.org/en/latest/appendices/command-line/traffic_ctl.en.html)?

**Comment by maskit** [comment]
> This doc seems empty. What about adding the details to the existing page for traffic_ctl?

That sounds like a good idea so we can read it on `man` as well. However, I'd like to keep the page focused on the command itself. Maybe just a note about the requirement is enough for the page. If we describe *details*, I still think "Interacting with Traffic Server" is the best page.

**Comment by d2r** [comment]
> That sounds like a good idea so we can read it on man as well. However, I'd like to keep the page focused on the command itself. Maybe just a note about the requirement is enough for the page.

OK, updated.

**Pull request merged**
