### PR TITLE
Redirect - Make TS to honour the number_of_redirections configuration.

### PR DESCRIPTION
**Pull request by brbzull0**
This fix includes a unit test to validate the expected behavior.
This fixes https://github.com/apache/trafficserver/issues/7800 and will help to validate https://github.com/apache/trafficserver/issues/2742 

I would appreciate if you can review it carefully, I did test this but I may be missing some scenarios, I'll be happy to add them to another unit test if necesary.

~~This PR depends on the following https://github.com/apache/trafficserver/pull/7866  to work.~~_done_

### CODE REVIEW

**Comment by brbzull0** [comment]
Autest needs https://github.com/apache/trafficserver/pull/7866 to work, as includes a new feature which is vital for this PR's unit test to work.

**Comment by brbzull0** [comment]
[appove ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Review by randall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
