### PR TITLE
Hoststatus and dependency back ports to 8.1.x

### PR DESCRIPTION
**Pull request by jrushford**
This is a back port of Hoststatus changes and dependencies to 8.1.x

Backports:

#3899 - Add a reason tag option to the host subcommand 
#4217 - Fix a regression in the traffic_ctl host status subcommand
#4441 - Corrects the wording of the usage messages for traffic_ctl host subcommand
#4422 - TCL: Remove TCL dependency from HostStatus.   (Hoststatus back port dependency).
#4664 - Use hash string when it is provided for hashing  (Hoststatus back port dependency).
#5143 - Fix a self detection issue where parents are not marked down during ATS startup.
#5248 - parent host status is not persistent across restarts.
#5252 - Make host status persistent across restarts
#4253 - Add the capability to mark origins down with traffic_ctl
#5417 - Change HostStatus to use only one stat per host
#6518 - Fixes a bug where HostStatus::getHostStatus() creates too many stats

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci clang-format]

**Comment by jrushford** [comment]
[approve autest]

**Comment by jrushford** [comment]
[approve ci clang-format]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci]

**Comment by jrushford** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by jrushford** [comment]
[approve ci autest]

**Pull request merged**
