### PR TITLE
cleanup: Resolve some of dependencies on private headers

### PR DESCRIPTION
**Pull request by maskit**
Resolved some of the dependencies on private headers from public headers (ones in include/).

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]
It's satisfying to see more of the P_ get removed from headers.

**Pull request merged**
