### PR TITLE
Clean up lua plugin doc for overridable configurations

### PR DESCRIPTION
**Pull request by shukitchan**
add TS_LUA_CONFIG_HTTP_PROXY_PROTOCOL_OUT (#7446)
add TS_LUA_CONFIG_HTTP_SERVER_MIN_KEEP_ALIVE_CONNS (#5830)
add TS_LUA_CONFIG_HTTP_HOST_RESOLUTION_PREFERENCE (#6769)

These are PRs included in 9.1.x but did not update lua plugin document

### CODE REVIEW

**Review by zwoop — APPROVED** [review]

**Comment by zwoop** [comment]
Make sure to set Milestone and appropriate Projects requirement (this should go into 9.1.x I believe, since those fixes are also in 9.1.x).

**Comment by bryancall** [comment]
@zwoop are you going to merge this?

**Comment by ywkaras** [comment]
> @zwoop are you going to merge this?

?

**Comment by ywkaras** [comment]
Actual @shukitchan you're a committer it looks like, why haven't you merged this?

**Comment by shukitchan** [comment]
this is for 9.1.0, not master

**Comment by zwoop** [comment]
Remember to remove Milestones etc. when closing a PR

**Pull request closed without merging**
