### PR TITLE
Add log field for line number of used URL remap rule in config file.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by bryancall** [comment]
Can you explain why this is needed?

**Comment by mlibbey** [comment]
How does this work for includes? 

Hard to imagine enough use of this to be in the core -- Seems like this might be better suited for a plugin (though, admittedly I've no clue if that'd be easy or terribly difficult).

**Comment by zwoop** [comment]
A line number into some unversioned / unidentified configuration file seems fairly useless. Two thoughts:

1. If you are looking for better debugging, I'd suggest more Diagnostic tags.
2. If you are looking to identify "services", I'd say use something like header_rewrite to set an @-header which identifies the service.

#2 is what we use to identify services (which maps more or less directly to the right remap line(s).

**Comment by ywkaras** [comment]
@bryancall because Dave Carlin asked for it (Oath internal TS issue/defect).

**Comment by ywkaras** [comment]
Closing to remove clutter from open PR list.

**Pull request closed without merging**
