### PR TITLE
cmake out of source doc build support

### LINKED ISSUE #10238: ☂ cmake: build docs

### PR DESCRIPTION
**Pull request by cmcfarlen**
I ended up copying the python config scripts for sphinx to support out of source builds.  After we move to cmake, the other set can be removed along with the support scripts that perform the same tasks that the cmake files do.  This could also probably do with some refactoring at some point and have the substituted config in a single module that the other files import, but this way stays as close as possible to the existing scripts for now.

Fixes  #10238

### CODE REVIEW

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Review by bneradt — APPROVED** [review]
Awesome. Once this lands, I can switch the CI to building the docs with this.

**Pull request merged**
