### PR TITLE
Track thread changes during origin connect and cache open write

### PR DESCRIPTION
**Pull request by sudheerv**
Also make adjust_thread() inline as an optimization

### CODE REVIEW

**Comment by sudheerv** [comment]
[approve ci]

**Comment by maskit** [comment]
[approve ci autest]

Rerunning autest because actual tests were skipped.
https://ci.trafficserver.apache.org/job/autest-github/13451/console

**Comment by sudheerv** [comment]
[approve ci autest]

**Comment by sudheerv** [comment]
[approve ci autest]

**Comment by shinrich** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
