### PR TITLE
traffic_manager: Fix error, clean up argument handling.

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
It looks like `--tsArgs` was broken by the log rotation changes. This restores that to a working state and does some other cleanup on the argument processing for `traffic_manager`. I added a format wrapper to Buffer Writer for this and updated the related documentation.

Waiting on #3908.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by SolidWallOfCode** [comment]
It's a no win situation for me. If I need any sort of additional support for a fix and put it in the fix, I get complaints like yours. If I pull that support out and put as a separate PR, then I get complaints that I'm adding features that aren't used. I suppose this is the best path - do the PR and split it if someone complains.

**Comment by maskit** [comment]
Separating the commit into two commits should solve the situation. Then people can see the fix on a commit and cleanups on the other commit. You don't have to have only one commit on a PR. It depends on cases.

**Comment by SolidWallOfCode** [comment]
Well, I get complaints about having multiple commits on a PR too, even if they are distinct as in this case.

**Comment by SolidWallOfCode** [comment]
It is separated, it's in #3908. Once that's merged, I'll rebase this one and all the extra bits will drop out.

**Comment by SolidWallOfCode** [comment]
Rebased after #3908 was merged.

**Comment by maskit** [comment]
It seems like `args` have to be appended to `lmgmt->proxy_options` instead of replacing it entirely. Is my understanding correct?

If so, you could fix the bug by just using `strcat`. Use of BufferWriter made code more readable but it also made the point of this PR unclear. And this kind of things make backporting hard, I'm not sure whether this fix have to be backported to old versions though.

**Comment by SolidWallOfCode** [comment]
I think it's good to take opportunities like this to do more general code cleanup. I'm on vacation this week, I will look at splitting it in to two commits when I get  back.

**Comment by maskit** [comment]
Don't get me wrong. I'm not saying "Don't cleanup". I would let you off the hook if it was a really trivial tiny obvious cleanup (, or it was a big change that can be considered as an overhaul). I just requested you to split the commit so that I can see the fix and the cleanup separately because it was hard to find the fix part. It would be a double handling but I think it worth to do in this case.

**Comment by SolidWallOfCode** [comment]
Where did my comment go? I split out the simpler fix for 8.0 in to #3938 leaving this purely as cleanup. I could have put the other changes here, but they would have just been overwritten anyway.

**Comment by maskit** [comment]
Why is #3938 for 8.0? I think it would probably cause conflicts if we backported this cleanup to 8.x branches in the future. I'd suggest splitting fad898c into two commits and backporting one of them to 8.0.

**Comment by SolidWallOfCode** [comment]
#3938 is for 8.0 because it's the simple fix you wanted separated out.  The change in that PR is how `TextBuffer` is called, but in this PR there is no `TextBuffer`. Therefore there's no change in this PR that could be separated from commit fad898c4517b28faf7597c3726f2b7f37ba231ee in a useful way. The equivalent change in this PR is completely dependent on the other changes in the PR. The result is #3938 can't be brought back in to this PR, and would be pointless to merge in to master if we're also going to commit this PR.

**Comment by SolidWallOfCode** [comment]
Well, anyway, I decided to do as requested and put the 8.0 fix in as a pre-commit to the cleanup commit.

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x, I cherry-picked all of this because we need it later.

**Pull request merged**
