### PR TITLE
Rewrite the assert statement to avoid Socks Proxy triggering the assertions

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by oknet** [comment]
The assert statement is introduced by PR #4166.

Request @shinrich for review.

**Comment by oknet** [comment]
Since PR#4166 has been ported back to 7.1.x and 8.0.x, this PR is a candidate for them to fix the SocksProxy.

**Comment by zwoop** [comment]
@ezelkow1 Lets put this on the radar for v7.1.7 as well.

**Comment by ezelkow1** [comment]
👍 We've seen this crash in 8.1.x at least, so if the issue is on 7 it should definitely go in

**Comment by jrushford** [comment]
@shinrich and @oknet we've see crashes here on 8.1.  this looks like it will fix the crashes we've seen

**Comment by ezelkow1** [comment]
We pulled this in to a test 8.1.x build yesterday and were still seeing this assert hit

**Comment by oknet** [comment]
@ezelkow1 Have your filed an issue ? Please show me your assert and result of gdb `backtrace full` command.

**Comment by ezelkow1** [comment]
@oknet I have not filed an issue since I was just pulling this change in before it was merged. I cant really get a full backtrace, only what bits we have stored from BT since the only way to get this is to run it in production for a while and wait to hit it. 

From BT I can see that pending_action is not null, so it must be failing on the second part of the statement, so the pending's cont is different from the vc's.  I dont have any insight into the contents of 'vc' during the crashes either so I cant personally do a comparison of the continuation values

**Comment by zwoop** [comment]
This has merge conflicts in 8.1.x

**Pull request merged**
