### PR TITLE
Adds test for Expect: 100-continue

### PR DESCRIPTION
**Pull request by d2r**
Created this PR on @shinrich advice to get some feedback on the approach.

This will introduce a new kind of test specification in which a JSON file is used to both:
* prescribe data that is sent to the traffic server
* describe the data that is expected from the traffic server

The test in this case is of the behavior of of ATS when it receives an `Expect: 100-continue` field and the client indicates more content to follow.

Fields I don't have permission to edit:
* Milestone: v8.0.0
* Labels: Tests, HTTP
* Projects: 8.x releases

### CODE REVIEW

**Comment by d2r** [comment]
This is unfinished work, and needs some clean-up. I wanted to put it up for discussion.

**Comment by d2r** [comment]
[approve ci-rat]

**Comment by d2r** [comment]
[approve-ci autest]

**Comment by zwoop** [comment]
Well, lets rephrase, only keep multiple commits if they make logical sense. But in many cases, if that's the case, you might want two PRs. But, as an example of where it might makes sense to have two commits is if there's a "core" code change and some docs or test changes that might not be easily back ported to an earlier version of ATS. Then at least we can cherry-pick the code changes to an LTS release.

**Comment by shinrich** [comment]
Looks like there is a python environment problem.

```
File "json_runner.py", line 34
    async def readuntil(reader, delim):
            ^
SyntaxError: invalid syntax
```

**Comment by shinrich** [comment]
About the multiple commits.  I agree that the first pass should be a single commit.  If there is considerable discussion and back and forth updates, delaying the squash until consensus has been reached seems reasonable.  It keeps code history around for people following the discussion which squashing removes.

**Comment by d2r** [comment]
> Squash your commits. Please don't create PRs with multiple commits, since people will merge without noticing.

> Well, lets rephrase, only keep multiple commits if they make logical sense. But in many cases, if that's the case, you might want two PRs. But, as an example of where it might makes sense to have two commits is if there's a "core" code change and some docs or test changes that might not be easily back ported to an earlier version of ATS. Then at least we can cherry-pick the code changes to an LTS release.

Ack to both points. In this case it was just an oversight. I need to do a better job squashing commits on my PR branch.

**Comment by d2r** [comment]
> Looks like there is a python environment problem.

I will look into this. I did not see this happen in my local environment.

**Comment by SolidWallOfCode** [comment]
[approve ci autest]

**Comment by d2r** [comment]
We should move this discussion to a private branch. Closing this PR for now.

**Pull request closed without merging**
