### PR TITLE
add redirection test

### PR DESCRIPTION
**Pull request by ffcai**

### CODE REVIEW

**Comment by ffcai** [comment]
Hi @jacksontj ,
I hope to discuss with you about [httpbin](http://httpbin.org/) before the merge.
It's a HTTP Request & Response Service, implemented by python, on the base of Flask. Some endpoints would be useful for our tests, e.g. /get, /post, /redirect, /delay, /drip... with these hands-on endpoints, we can focus our tests on ats configurations and E2E tests, without spending too much time on origin server's implementation and detail. And we can install it as a library from PyPI and run it as a local WSGI app. What do you think of it?

**Comment by jacksontj** [comment]
Ooo, that sounds awesome! The main reason for having the origins within the framework is so we can see request/response headers on the origin side (since we may have modified headers etc.). If this is just a regular wsgi thing we can just wrap it with the correct code to capture request/response header we can drop the default one that exists there.

**Comment by jacksontj** [comment]
I've added the wrapper stuff (for tracking) to tqsa (https://git-wip-us.apache.org/repos/asf?p=trafficserver-qa.git;a=commit;h=9e99c096d7147b4253f3ba210b079d3ea265573b)

**Comment by jacksontj** [comment]
@ffcai Do you mind updating your tests to use the in-build httpbin? If not I can do it, but I'd rather you get the karma for the awesome find :)

**Comment by ffcai** [comment]
Thanks @jacksontj I'll really glad that you add it to the framework. I'll update my tests as soon.

**Comment by ffcai** [comment]
I just find that the local httpbin (start with like `gunicorn httpbin:app`) acts different with http://httpbin.org. And, this test case fails for local httpbin :( . I guess it's because the local httpbin does not use keep-alive connections by default. I'm trying to find out the root cause and make it pass. I will commit the update after it get passed.

**Comment by jacksontj** [comment]
Can you try applying 5a367b6 to your tsqa? I think the wsgiserver I'm using right now only supports a single connection-- this should make it multithreaded and happy with the KA stuff ;)

**Comment by ffcai** [comment]
Hi @jacksontj ,
I find that it's not related to httpbin. I happen to find a trivial bug which would cause redirection fails. I send out another pull request (https://github.com/apache/trafficserver/pull/188) for it. After it is merged, this test would pass.
As we have seen here, your TSQA framework is proved to be really, really useful! :+1:

**Pull request closed without merging**
