### PR TITLE
Defer deletion of reloadable remap plugins

### PR DESCRIPTION
**Pull request by zwoop**
The point of this exercise is to keep the "copied" plugins on the filesystem, for the lifetime of their use. This makes it possible to get full backtrace from a crash / core file, before this patch all debug info is lost with the .so being removed immediately on load / reload.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci].

**Comment by zwoop** [comment]
[approve ci autest]

**Review by bryancall — APPROVED** [review]

**Pull request merged**
