### PR TITLE
JSONRPC Client - Fix OSX/FreeBSD write socket issue.

### PR DESCRIPTION
**Pull request by brbzull0**
Tested on FreeBSD as I don't have OSX

### CODE REVIEW

**Comment by maskit** [comment]
I assume it actually called `safe_write` in ink_sock.h. This is why I use `this->`.

**Comment by maskit** [comment]
This implies that we cannot use safe_write in ink_sock.cc for other use cases either. That would be a trap.

Could you provide the detail of the issue? I feel like we should fix the one in ink_sock.cc (maybe with ifdef if needed).

**Review by maskit — APPROVED** [review]
I have a concern but approve this not to block other PRs

**Comment by JosiahWI** [comment]
Merging with Damian's permission.

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
