### PR TITLE
Convert RamCache auxkey from 2 uint32_t to 1 uint64_t.

### PR DESCRIPTION
**Pull request by jplevyak**
Signed-off-by: John Plevyak <jplevyak@apache.org>

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
Looks reasonable. IIRC the main reason the ram cache key is 32 bits is because no one was willing to change it when we moved to 64 bit support. I would like, however, to not use "uint64_t" but put in a `using` like `using RamCacheKey = uint64_t;`. I think this will make the code clearer and make it easier to tweak later.

**Comment by ywkaras** [comment]
[approve ci Debian]

**Comment by ywkaras** [comment]
> Looks reasonable. IIRC the main reason the ram cache key is 32 bits is because no one was willing to change it when we moved to 64 bit support. I would like, however, to not use "uint64_t" but put in a `using` like `using RamCacheKey = uint64_t;`. I think this will make the code clearer and make it easier to tweak later.

Is there a reason you didn't approve this?

**Comment by SolidWallOfCode** [comment]
I was hoping for the `using` fix but I suppose I can just do that myself.

**Review by SolidWallOfCode — APPROVED** [review]

**Pull request merged**
