### PR TITLE
TS-4410 : Fixed compiler warning on i386 builds for unsigned-vs-signe…

### PR DESCRIPTION
**Pull request by pbchou**
…d int comparison.

### CODE REVIEW

**Comment by jpeach** [comment]
Looks good. Will merge.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux (CentOS7) build failed! Details on https://ci.trafficserver.apache.org/job/Github-Linux/11/

**Comment by zwoop** [comment]
Try another build: [approve ci]

**Comment by atsci** [comment]
Linux (CentOS7) build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-Linux/13/

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux (CentOS7) build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-Linux/32/

**Comment by atsci** [comment]
FreeBSD v10 build finished successfully. Details on https://ci.trafficserver.apache.org/job/Github-FreeBSD/15/

**Comment by zwoop** [comment]
I think this is ready to land.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
[approve ci]

**Comment by zwoop** [comment]
These built without problem on the CI:

Linux: https://ci.trafficserver.apache.org/view/github/job/Github-Linux/66/
FreeBSD: https://ci.trafficserver.apache.org/view/github/job/Github-FreeBSD/161/

**Pull request closed without merging**
