### PR TITLE
TS-4304: implementation of ConditionUrl::append_value

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by zwoop** [comment]
This is a good start, but it's missing a few things (I think at least, been a while since I looked at this). Look at how the eval() function is handling the different cases. But at least I think you need to

1) Support the remap vs transaction hook cases

2) Support the various qualifiers for each of those cases.


Now, while briefly looking at the eval() function, I see that it does not handle all qualifiers properly. I'm not sure what exactly happen here, but it's likely related to https://issues.apache.org/jira/browse/TS-4146 . Somewhere something went wrong, and instead of implementing the proper qualifiers, we added new operators for e.g. PATH etc. :-/.

I'm if you only make ::append_value() support the same features and qualifiers as the eval() method does today. And if so, just make a comment on TS-4146, reminding us that we also have to support more qualifiers (path etc.) in the append_value() method as well.

Cheers!

**Comment by yatsukhnenko** [comment]
@zwoop, I added the same features as in eval method

**Comment by zwoop** [comment]
I'll look again later, but I don't think so. At least it should work on more than just the pristine request URL. The intent of these is to support various types of the URLs for different types of usage (remap vs global etc.).

**Comment by yatsukhnenko** [comment]
@zwoop, did you look at this? What's wrong?

**Comment by sudheerv** [comment]
This is an automatically generated message.

sudheerv@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Pull request closed without merging**
