### PR TITLE
TS-3036: Added the 'chm' logging field

### PR DESCRIPTION
**Pull request by RyanFrantz**
The 'chm' logging field notes, in the case of a cache hit, if the medium the hit was served from was RAM.

### CODE REVIEW

**Comment by jacksontj** [comment]
Is it possible to log the volume that served the cache response? Right now it seems that you log "-" when it hits disk, but it would be nice if we could know which disk.

**Comment by zwoop** [comment]
Hmmm that feels like it'd be a different log tag, no? The intent with this field is to show which cache level we are serving out of, e.g RAM vs rotational disk vs SSD vs cache cluster etc

Not sure why it's logging - when you get a disk hit, that sounds like a big. It should log HIT_DISK. Please reopen the bug if this is not working.

-- Leif

**Comment by jacksontj** [comment]
That would make sense too, I'm just going off the docs:

```
with a ``chm`` value of
+    ``-`` the medium was disk cache.
```

Seems odd for it to say "ram" and "-"

**Comment by jacksontj** [comment]
@zwoop

**Pull request closed without merging**
