### PR TITLE
Tests: Update oss-fuzz script to use the updated H3 build tools folder.

### PR DESCRIPTION
**Pull request by brbzull0**

### CODE REVIEW

**Comment by bneradt** [comment]
[approve ci rocky]

**Comment by bneradt** [comment]
[approve ci rocky]

**Review by zwoop — APPROVED** [review]

**Comment by cmcfarlen** [comment]
This doesn't pick into 10.0.x due to (at least) these PRs that were not picked into 10.0.x:

#11128
#11221

**Comment by cmcfarlen** [comment]
This PR will not be picked in to 10.0.x

**Pull request merged**
