### PR TITLE
Cleans up various bits of old code

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by zwoop** [comment]
@randall Would you mind squashing this into one commit? It makes it easier for cherry-picking to the LTS branches, and it's generally how we do things (unless you have strong reasons why you need the commits broken up).

**Comment by randall** [comment]
@zwoop Done.

This is safe for 8.0.x (not sure if we want these sort of changes brought over)

**Comment by zwoop** [comment]
I think we should cherry pick as much as possible of cleanup changes that are safe. The point of branching early is to stabilize things, and avoid dangerous commmits to sneak in. This one is not dangerous IMO.

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Pull request merged**
