### PR TITLE
TS-3792: Crash with non-existant or missing resolve_conf

### PR DESCRIPTION
**Pull request by zizhong**
Fix the bug issue TS-3792: Pointing proxy.config.dns.resolv_conf at an empty (or nonexistant) file causes segmentation faults on first DNS query. If the user specified resolve conf doesn't work, use the default resolve conf instead. If the default resolve conf doesn't work neither, abort the traffic server.

### CODE REVIEW

**Comment by bgaff** [comment]
Hey @zwoop , mind taking a look? This current iteration was my suggestion as the easiest way to handle this edge case. @jacksontj has also created a test case for this and obviously this current implementation passes that test case.

**Comment by SolidWallOfCode** [comment]
Looks fine to me.

**Comment by sudheerv** [comment]
@bgaff : How does this work when I have a set up that terminates all connections locally (i.e. no origins to talk to)? We do have some use cases (w/ and w/o intercept plugins), where, origin communication is not involved. There's probably always something in the /etc/resolv.conf for those setup, but, I wonder, if that should be "enforced" the way this patch does, when there's no "need" for them?

**Comment by jpeach** [comment]
I'm not sure that always falling back to a default is desirable. If the operator specified an empty ```resolv.conf```, then why wouldn't we use what they configured? It is valid for ```/etc/resolv.conf``` to be empty; there's no reason we should crash on it.

**Comment by bgaff** [comment]
@jpeach , what are you supposed to do without any resolvers?

**Comment by jpeach** [comment]
Nothing? Use the resolvers in ```records.config```? Assume every name is in ```/etc/hosts```? Never use DNS names?

**Comment by sudheerv** [comment]
@bgaff : Also, pls see my comment above - we do have some use cases, where there's no origin communication involved.

**Comment by SolidWallOfCode** [comment]
Perhaps what we should do is allow the configuration to specify the empty string for revolv.conf to mean "don't use resolv.conf". I think it's reasonable to think that almost all the time if you specify a file you expect something to be in it. If you really don't want to use resolv.conf or its equivalent, specify that explicitly with an empty or NULL string.

**Comment by jpeach** [comment]
That seems reasonable, and WARNing on an empty file also seems reasonable. Crashing, less so.

**Comment by sudheerv** [comment]
As long as it's a WARNING (and doesn't block TS from coming up), I'm fine with that as well.

OTOH if a crash/abort is involved, it sounds like a compatibility change with existing deployments and require an explicit config change (e.g. to change resolv.conf to NULL or whatever). So, IMHO, it should probably be in a new major release.

**Comment by zizhong** [comment]
Thanks for the useful information. I updated the pull request. Now it would not crash when it doesn't have a DNS resolver. Looking forward to new feedbacks.

**Comment by bgaff** [comment]
I'm happy with this implementation, if the user does something stupid like specify a resolv conf that is nonexistent or doesn't contain any resolvers the behavior will be as expected: DNS resolutions fail :+1:

**Comment by zwoop** [comment]
I haven't had a chance to review all this, but reading the last few comments, makes me wonder: If a user ends up in such a situation (no resolvers available), do we at least produce some very loud and obvious error messages / warnings ?

**Comment by bgaff** [comment]
@SolidWallOfCode @jpeach are you guys okay with this current iteration? If we don't have any objections I'll get this merged.

**Comment by jpeach** [comment]
To @zwoop's comment, I can't see any obvious warning. This patch adds a warning ``There is no name server found in the resolv.conf`` sometime after it fails to load the resolver config. It seems like it would be better to add the warning in ``ink_res_init`` where we know the name of the file and can construct a more helpful message.

**Comment by bgaff** [comment]
@zizhong yah an Error might be more appropriate.

**Comment by jpeach** [comment]
@bgaff I'm suggesting that the error should be emitted at the point where we detect the failure.

**Comment by bgaff** [comment]
@jpeach what "failure" are you referring to when we load resolve.conf?

**Comment by jpeach** [comment]
I don't see any code that logs when the specified ``resolve.conf`` fails to load. Is there anything?

**Comment by zwoop** [comment]
@bgaff  Should we land this? Assigning to you for final reviews / commit.

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
Can this be squashed into one commit? Or does it need to be split up like this?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
@zizhong This now unfortunately fails on clang-format as well. See

https://ci.trafficserver.apache.org/view/github/job/Github-Linux/69/

Please rebase, squash and make sure you run clang-format again (make clang-format).

**Comment by zizhong** [comment]
@zwoop , I noticed the code has been merged while this request is still open.
About the clang-format failure, I checked the URL above and couldn't find this patch showed in console output. I ran clang-format against my branch but no code diff generated.

**Pull request closed without merging**
