### PR TITLE
Set the default thread count factor to 1x the number of logical cores

### PR DESCRIPTION
**Pull request by bryancall**
This was talked about at the ATS Spring Summit and makes sense for modern day hardware.

### CODE REVIEW

**Comment by ywkaras** [comment]
Under a pure event-driven design, there would be no reason to have more threads than cores.  But we don't really have that.  In olugins, and I think in a significant number of places in the core, we do blocking syscalls.  If we had a single continuation queue feeding all the threads (my suggestion that was already shot down), having more threads than cores would be an effective work-around for continuations whose functions blocked.  But we have per-thread continuation queues.  However, having more threads means that, on average, there are fewer continuations queued ahead of yours, and thus fewer continuations whose inappropriate blocking syscalls can block your continuation.  So having more threads than cores may reduce latency and increase throughput.

**Comment by vmamidi** [comment]
> Under a pure event-driven design, there would be no reason to have more threads than cores. But we don't really have that. In olugins, and I think in a significant number of places in the core, we do blocking syscalls. If we had a single continuation queue feeding all the threads (my suggestion that was already shot down), having more threads than cores would be an effective work-around for continuations whose functions blocked. But we have per-thread continuation queues. However, having more threads means that, on average, there are fewer continuations queued ahead of yours, and thus fewer continuations whose inappropriate blocking syscalls can block your continuation. So having more threads than cores may reduce latency and increase throughput.

can you give me an example of inappropriate blocking syscalls?

**Comment by ywkaras** [comment]
https://github.com/apache/trafficserver/blob/8d74203ff7829766f3c18c2ec11fa8d35af40368/plugins/cache_promote/lru_policy.cc#L105

**Comment by ywkaras** [comment]
Inappropriate in the sense of deviating from a pure event-driven approach.

**Comment by bryancall** [comment]
On the other side of the argument for lowering threads is lock contention.  Both blocking calls and lock contention needs to be balanced.  I have done a lot of benchmarking and 1x seems to be a better default setting given the number or local cores on a modern server.  People can still change the default on their own if they are going to have more blocking calls in their plugins.

**Comment by ywkaras** [comment]
OK yes it's better to make performance tradeoffs based on testing rather than speculation.  I realize it's a lot of work, but we should aspire to having performance tests reviewable, for similar reasons to why code review is desirable.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
