### PR TITLE
Require use of 'override' keyword when valid.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci fedora]

**Comment by ywkaras** [comment]
https://www.fluentcpp.com/2020/02/21/virtual-final-and-override-in-cpp/

**Comment by ywkaras** [comment]
Hmm looks like clang doesn't support -Wsuggest-override .

**Comment by ywkaras** [comment]
https://reviews.llvm.org/D82728

**Review by masaori335 — APPROVED** [review]
Looks reasonable.

**Pull request merged**
