### PR TITLE
Add new testing infra to ATS to 7.1

### PR DESCRIPTION
**Pull request by dragon512**
Added new testing code
Added Apache license header
Add some getting started documentation
Doc for microserver in AuTest

update document

add execute permission to boostrap.py script

address bootstrap issue with rhel and centos

better fix for RHEL and CentOS systems

change -x to -r as 'enable' is not executable

more clean up to bootstrap.py

tweak typo

tweak test to be more stable

Update getting_started.md

Fix path to / to ./
Fix custom log test
Added 10 second delay to get AST to write out the log file
Added a verbose message to help clarify a conf file was written as expected

tweak gold files to not look for proxy-connection
Curl adds Proxy-connection on it own in some cases, and or duplicates it more than once

fix issue with virtualenv on Fedora 25

Force use of python3 for microserver

Add option to choose interface

python format clean up
create directory for TS_ROOT to allow symlinks to work. This saves space on disk

Fix the default storage config for the tests so the storage config
file is openable by nobody.  Otherwise, the cachedb is not accessible
by the traffic_server user.

Big H2 file download test for issue 1646.

Add port wait on micro server startup

Fix http2 big client test

Traffic-replay client

fix testing issue with traffic_cop

Add test to see if we are shutting down
If we are, don't print message about EOL

### CODE REVIEW

**Comment by dragon512** [comment]
Hopefully I have all the cherry pick here correct merged

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/328/

**Comment by atsci** [comment]
RAT check *failed*! https://ci.trafficserver.apache.org/job/RAT-github/341/

**Comment by dragon512** [comment]
@zwoop  Do I need to add the cherry pick for the rat test?

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1916/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/325/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/454/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2023/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/587/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/329/

**Comment by atsci** [comment]
RAT check *failed*! https://ci.trafficserver.apache.org/job/RAT-github/342/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2024/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/455/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1917/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/326/

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/330/

**Comment by atsci** [comment]
RAT check *failed*! https://ci.trafficserver.apache.org/job/RAT-github/343/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/327/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/588/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2025/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/456/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1918/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/589/

**Comment by SolidWallOfCode** [comment]
@dragon512 the RAT test is failing because you haven't rebased this in a long time. Leif put in a fix to exclude the `.gold` files back in early March but that fix isn't in your branch. You should probably rebase this on `ats/master` first.

**Comment by dragon512** [comment]
@amc this is the 7.1 branch. I made a fresh copy of 7.1 and cherry picked changes to it. I will go and cherry pick in the master change for this into PR

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/332/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/345/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/2027/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/458/

**Comment by atsci** [comment]
AU check *successful*! https://ci.trafficserver.apache.org/job/autest-github/329/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1920/

**Comment by atsci** [comment]
clang-analyzer build *failed*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/591/

**Comment by SolidWallOfCode** [comment]
Looks reasonable. I presume all of this is already on master.

**Comment by dragon512** [comment]
Yes... I cherry picked it from master. This should be everything for testing on master except the via test. This one seemed to have code changes with it that I think should be a different PR. This does contain the traffic_cop fix to suppress the "Fatal" error message on shutdown

**Comment by zwoop** [comment]
Nice, I'll merge this in a little bit, thanks.

**Pull request merged**
