### PR TITLE
TS-4096: ts.now() should return subsecond info for ts_lua plugin

### PR DESCRIPTION
**Pull request by shukitchan**
@bgaff and @zwoop , pls review

### CODE REVIEW

**Comment by shukitchan** [comment]
@jpeach , can you take a quick look on this as well?

**Comment by jpeach** [comment]
This still returns time in seconds, since the arithmetic is the same. If you change the time units should you add a new API to preserve compatibility?

**Comment by shukitchan** [comment]
@jpeach 
Yes. the time is still in seconds. But instead of returning an integer all the time, it is now a "lua_Number", which is like a "double". 

In some sense, the data type returned is still the same ("lua_Number"). The unit is also not changed. 
should I still add a new API instead? since all the operations on the return value will still work the same way.

**Comment by jpeach** [comment]
I guess I still don't get it. This API already returned a Lua number, so the only semantic change I can see is that there is no longer any potential issue with truncation due to ``time_t``. That doesn't sound like the issue you are describing and I don't see anything about sub-second timestamps here?

**Comment by shukitchan** [comment]
@jpeach 
Before the change the lua number is always an integer (e.g. 1451970346). Now after the change the lua number will contain the fraction of the second as well. (e.g. 1451970346.123)

**Comment by jpeach** [comment]
Oh I see, that makes sense. +1

**Comment by shukitchan** [comment]
ha. my bad english

**Pull request closed without merging**
