### PR TITLE
HostLookup: replace TCL hash with IntrusiveHashMap, refresh for C++ eleventy

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Depends on #3955.

This started as an effort to replace a use of TCL hash with `IntrusiveHashMap` but to make that work well I had to do a major refresh to bring the base code up to C++ eleventy standards. Overall `IntrusiveHashMap` worked well, although I did end up adding the `apply` method and doing an overhaul of the documentation (both of those now blended in to #3955).

### CODE REVIEW

**Comment by zwoop** [comment]
Is there something that still needs TCL after this? If no, we should nuke TCL from the build dependencies too.

**Comment by zwoop** [comment]
I also think this is worthy of a 8.0.0 back port, but maybe it's a little risky?

**Comment by SolidWallOfCode** [comment]
It's just a first step. It eliminates it from the HostLookup matcher logic, but the TCL hash table is still in use elsewhere. Primarily this is a trial run to validate the approach. Next step is to replace `TSHashTable` with this, which should be simpler. That eliminates `TSHashTable`. Then start replacing other uses of ink_hash_table. I suppose I could look at rewriting ink_hash_table using this and then converting, because no small part of the win is having a much nicer interface.

**Comment by SolidWallOfCode** [comment]
Going to have this redone using STL containers.

**Pull request closed without merging**
