### PR TITLE
TS-4744: ParentConsistentHash::selectParent may select the unavailable parent.

### PR DESCRIPTION
**Pull request by jrushford**
I've created this pull request on behalf of @keith2008 who found the issue and opened the JIRA.  His pull request had merge conflicts and he has asked me to resolve them and submit this new PR for TS-4744.

### CODE REVIEW

**Comment by jrushford** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/635/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/531/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/636/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/532/ for details.

**Comment by keith2008** [comment]
good job.

**Pull request merged**
