### PR TITLE
Fix H2 internal counters

### LINKED ISSUE #5832: Possibly PING frame rate limiting error due to ping_frame_count not cleared
After applying HTTP/2 rate limiting for HTTP/2 DoS protection, we have observed several PING rate limits errors as
```
 ERROR: HTTP/2 connection error client_ip=xxx.xxx.xxx.xxx session_id=xxxxxxxxxx recv ping too frequent PING frame
```
Our `max_ping_frames_per_minute` is a default value of 60. 

The errors were occurred from Chrome accesses. Chrome seems to send PING frame after some idle time as https://chromium.googlesource.com/chromium/src/+/refs/heads/master/net/spdy/spdy_session.cc#2615. 

We could not identified if this is a real PING flood. Possibly,  the error might be caused by the `ping_frame_count` not to be cleared when PING is received in 60 secs without changing `counter_index` like  
```
setInterval(function() {
  let now = Math.floor(Date.now()/1000) % 60;
  let index = (now >= 30) - 0;
  if (index == 0) {
    doPing();
  }
}, 1000);
```

### PR DESCRIPTION
**Pull request by maskit**
This fixes #5832

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci RAT]

**Comment by masaori335** [comment]
Build error on Ubuntu
```
/bin/bash ../../libtool  --tag=CXX   --mode=link clang++ -std=c++17 -g -pipe -Wall -Wno-deprecated-declarations -Qunused-arguments -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -O3 -fno-strict-aliasing -Werror -Wno-invalid-offsetof -mcx16 -Qunused-arguments -rdynamic -Wl,--as-needed -R/usr/lib64 -L/usr/lib64 -o test_Http2FrequencyCounter unit_tests/test_Http2FrequencyCounter-test_Http2FrequencyCounter.o test_Http2FrequencyCounter-Http2FrequencyCounter.o ../../src/tscore/libtscore.la ../../src/tscpp/util/libtscpputil.la ../../iocore/eventsystem/libinkevent.a -lpthread -ldl 
libtool: link: clang++ -std=c++17 -g -pipe -Wall -Wno-deprecated-declarations -Qunused-arguments -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -O3 -fno-strict-aliasing -Werror -Wno-invalid-offsetof -mcx16 -Qunused-arguments -rdynamic -Wl,--as-needed -o .libs/test_Http2FrequencyCounter unit_tests/test_Http2FrequencyCounter-test_Http2FrequencyCounter.o test_Http2FrequencyCounter-Http2FrequencyCounter.o  -L/usr/lib64 ../../src/tscore/.libs/libtscore.so ../../src/tscpp/util/.libs/libtscpputil.so ../../iocore/eventsystem/libinkevent.a -lpthread -ldl -Wl,-rpath -Wl,/var/jenkins/workspace/ubuntu-github/6772/install/lib -Wl,-rpath -Wl,/usr/lib64
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `ClassAllocator<ProxyMutex>::alloc()':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Allocator.h:131: undefined reference to `ink_freelist_new'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `ProxyMutex::init(char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/./I_Lock.h:233: undefined reference to `ink_mutex_init(pthread_mutex_t*)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `ink_mutex_acquire(pthread_mutex_t*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/ink_mutex.h:50: undefined reference to `ink_abort(char const*, ...)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `~Thread':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Thread.cc:59: undefined reference to `_ink_assert'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `ink_mutex_release(pthread_mutex_t*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/ink_mutex.h:59: undefined reference to `ink_abort(char const*, ...)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `Thread::start(char const*, void*, unsigned long, std::function<void ()> const&)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Thread.cc:105: undefined reference to `ink_strlcpy(char*, char const*, unsigned long)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Thread.o): in function `ink_thread_create(unsigned long*, void* (*)(void*), void*, int, unsigned long, void*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/ink_thread.h:161: undefined reference to `ink_abort(char const*, ...)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `lock_waiting(SourceLocation const&, char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Lock.cc:39: undefined reference to `diags'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::on(DiagsTagType) const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:146: undefined reference to `DiagsConfigState::enabled'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::get_override() const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:134: undefined reference to `get_cont_flag(ContFlags::flags)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::on(char const*, DiagsTagType) const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:152: undefined reference to `Diags::tag_activated(char const*, DiagsTagType) const'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `lock_waiting(SourceLocation const&, char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Lock.cc:41: undefined reference to `SourceLocation::str(char*, int) const'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `lock_holding(SourceLocation const&, char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Lock.cc:48: undefined reference to `diags'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::on(DiagsTagType) const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:146: undefined reference to `DiagsConfigState::enabled'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::get_override() const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:134: undefined reference to `get_cont_flag(ContFlags::flags)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::on(char const*, DiagsTagType) const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:152: undefined reference to `Diags::tag_activated(char const*, DiagsTagType) const'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `lock_holding(SourceLocation const&, char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Lock.cc:50: undefined reference to `SourceLocation::str(char*, int) const'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `lock_taken(SourceLocation const&, char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Lock.cc:57: undefined reference to `diags'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::on(DiagsTagType) const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:146: undefined reference to `DiagsConfigState::enabled'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::get_override() const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:134: undefined reference to `get_cont_flag(ContFlags::flags)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `Diags::on(char const*, DiagsTagType) const':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Diags.h:152: undefined reference to `Diags::tag_activated(char const*, DiagsTagType) const'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `lock_taken(SourceLocation const&, char const*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/Lock.cc:59: undefined reference to `SourceLocation::str(char*, int) const'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `ProxyMutex::free()':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/./I_Lock.h:450: undefined reference to `ink_mutex_destroy(pthread_mutex_t*)'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `ClassAllocator<ProxyMutex>::free(ProxyMutex*)':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Allocator.h:145: undefined reference to `ink_freelist_free'
/usr/bin/ld: ../../iocore/eventsystem/libinkevent.a(Lock.o): in function `ClassAllocator':
/var/jenkins/workspace/ubuntu-github/src/iocore/eventsystem/../../include/tscore/Allocator.h:207: undefined reference to `ink_freelist_init'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:966: test_Http2FrequencyCounter] Error 1
make[3]: Leaving directory '/var/jenkins/workspace/ubuntu-github/src/proxy/http2'
make[2]: *** [Makefile:1331: check-am] Error 2
make[2]: Leaving directory '/var/jenkins/workspace/ubuntu-github/src/proxy/http2'
make[1]: *** [Makefile:857: check-recursive] Error 1
make[1]: Leaving directory '/var/jenkins/workspace/ubuntu-github/src/proxy'
make: *** [Makefile:851: check-recursive] Error 1
```

**Comment by masaori335** [comment]
[approve ci ubuntu]

**Comment by masaori335** [comment]
Logic & tests looks good.

**Comment by maskit** [comment]
[approve ci autest]

**Pull request merged**
