### PR TITLE
TS-4716: OpenBSD mandir should be ${prefix}/man

### LINKED ISSUE #1353: [openbsd] wrong mandir for OpenBSD layout
```
$ sed -n '/<Layout OpenBSD>/,/<\/Layout>/p' trafficserver-87ca6b40999b13562aff0efce5a1cd76eab5c306/config.layout  | grep man
    mandir:        ${prefix}/share/man
```

But 3rd party apps on OpenBSD put their man pages into ```${prefix}/man```.

### PR DESCRIPTION
**Pull request by jablko**
Fixes #1353

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1362/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1255/ for details.

**Comment by zwoop** [comment]
I'm marking this for 7.1.0, since it's mostly benign, and generally useful.

**Comment by zwoop** [comment]
Question: Why is this PR also modifying the Debian layout? That seems slightly non-intuitive considering the Summary from the PR (OpenBSD).

**Comment by jablko** [comment]
> I'm marking this for 7.1.0, since it's mostly benign, and generally useful.

Sounds good, thanks! Merged.

> Update: I think I see, it's merely a cleanup (no change in actual path). Still +1.

Yes, exactly. I noticed it while I was editing config.layout, so I put it in the same PR, but it has nothing to do with OpenBSD, so I made it a separate commit. What I should've done was also mention it in the PR description, and point out that it's just a cleanup. Next time!

**Pull request merged**
