### PR TITLE
Fix proxy.process.http.current_client_transactions

### LINKED ISSUE #7163: 9.0: proxy.process.http.current_client_transactions metric is broken
Feels similar to: https://github.com/apache/trafficserver/issues/7054 (fix for #7054 was #7056).

In ATS 9.0, the proxy.process.http.current_client_transactions metric is busted, and functions much more like a counter than a gauge.

image

### PR DESCRIPTION
**Pull request by shinrich**
This closes #7163

### CODE REVIEW

**Comment by maskit** [comment]
I think adding another line that calls `decrement_client_transactions_stat` is not a good idea. Having multiple paths would make things complicated.

`ProxyTransaction::decrement_client_transactions_stat` is only called from `ProxyTransaction::release`.
`Http1ClientSession::release_transaction()`, which is the one you added the line, is only called from `Http1Transaction::transaction_done`.

If adding the line into `release_transaction` solves the issue, doesn't it mean `ProxyTransaction::release` is not called for the transaction? I think that is the root cause.

This code looks suspicious. When subclass's `release` is called, it should always call superclass's `release`.
https://github.com/apache/trafficserver/blob/718bef406aacdb14564cb111c3ad14cb9bc1466d/proxy/http/Http1Transaction.cc#L42-L46

Even if this works for the stat issue, a risk for not running common processes on releasing transaction would be left. Since it's a blocker for 9.0, I didn't make a change request. However, I'm not so happy with this approach.

**Comment by shinrich** [comment]
Yes, I agree that the fact that the Http/1.1 case is not calling release() is unsettling.  However, given the nearness of the 9.0.x release, this seemed like a safer (less broadly impacting) change.  Let me take another look at see if I can work the release back in without a broader impact.

**Comment by shinrich** [comment]
Hmm.  if r != _reader all the time, that is indeed disturbing.

**Comment by shinrich** [comment]
We do need an autest here to track these metrics.

**Comment by maskit** [comment]
For the HTTP/3 question, I think everything related to the metrics should be done in `HQTransaction` and/or `HQSession`. We currently support HTTP/3 and HTTP/0.9 on QUIC, and you can think like the HTTP/0.9 support is a variation of HTTP/3. One transaction runs on one stream. Basically the same approach should work for both HTTP/2 and HTTP/3 (and HTTP/0.9 on QUIC).

If you are still no sure, you can just file an issue for it. The metrics are not implemented for H3 anyway. I'm ok as long as it doesn't crash. I think H3 issues should not block 9.0.0 release.

> Ultimately ProxyTransaction::release() should probably be renamed to something else. Calling super_type::release() seems somewhat obscure.

I'm not sure what you are trying to solve with the renaming. If it's just for clear naming I'm fine with it, but if you are not a big fun of calling super type's function we may be able to do something like this:
```cpp
virtual void ProxyTransaction::_release() = 0;
void
ProxyTransaction::release() {
  this->decrement_client_transactions_stat();
  this->_release()
}

Http1Transaction::_release() {

}
```
I understand the code above is impossible because `super_type::release()` is called from different places. However, I wonder why we can't call the decrement function from the same place on all HTTP versions. If we have a function that will be called at the end of a transaction regardless of how it ends, like TXN_CLOSE hook, we should be able to call the decrement function from there.

**Comment by shinrich** [comment]
Pushed another commit.  After running the previous box overnight, the http2 current stream count was stuck again at 0 which implies that path was still over decrementing.  I assume that destroy is being called in cases were the stream object created but new_transaction is never called.  So moved that logic into transaction_done as it is for http1.  That kind of lines up with your suggestion @maskit that we push this logic up into the same place for all versions.  So a super class transaction_done method might do it.

Will go ahead and push up another commit with HTTP/3 addressed.

**Review by maskit — APPROVED** [review]
Looks great, I like the symmetricity.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
