### PR TITLE
Change Au test openssl lib version condition to use version traffic_server was built with.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
@dragon512 @shinrich @zwoop please review.

**Comment by ywkaras** [comment]
@zwoop A concern I have about this change is whether objdump (a GNU binutil I think) is present and works the same on FreeBSD and OSX.  (Au test works on OSX doesn't it?)

**Comment by ywkaras** [comment]
@randall I changed it to use the nm utility instead of objdump, can you try it again please?

**Comment by zwoop** [comment]
I forgot to comment, I tried this on my mac, and it didn't show anything? Is that expected?

```
munin (11:58) 284/0 $ nm /opt/ats/bin/traffic_server | grep -F 'OPENSSL_' | tr ' \t@' '\n' | grep '^OPENSSL_[0-9]' | sort -u | tail -1
munin (11:58) 284/0 $
```

**Comment by zwoop** [comment]
The more I think about this, I think a much better approach would be to augment traffic_layout. Something like

```
$ traffic_layout info --versions
source: /home/leif/apache/trafficserver
build: 8.0.4-78
openssl: 1.0.1a
brotli: 0.1.2
...
```

**Comment by zwoop** [comment]
I've started hacking something up:

```
munin (17:44) 426/0 $ ./src/traffic_layout/.libs/traffic_layout info --versions
openssl: 0x1010102f
```

**Comment by zwoop** [comment]
See proposal in https://github.com/apache/trafficserver/pull/5239

**Comment by SolidWallOfCode** [comment]
I have to agree with @zwoop - `traffic_layout` should provide this information. That will be more reliable across multiple platforms.

**Comment by ywkaras** [comment]
This is replaced by https://github.com/apache/trafficserver/pull/5239 .

**Pull request closed without merging**
