### PR TITLE
TS-4862: Unable to clear metrics.

### PR DESCRIPTION
**Pull request by jpeach**
Fix ``traffic_ctl metrics clear``.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/801/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/696/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/802/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/697/ for details.

**Comment by bryancall** [comment]
👍 - Looks good

**Pull request merged**
