### PR TITLE
TS-5040: Forward CONNECT without parent proxying.

### PR DESCRIPTION
**Pull request by jpeach**
Unless parent proxy is enabled, CONNECT methods always result in
setting up a direct tunnel to the origin server. Parent proxy,
however, has the option of forwarding the CONNECT to the next hop
and allowing it to set up the tunnel.  This change adds the
proxy.config.http.forward_connect_method configuration parameter
that can be enabled to forward CONNECT methods even if we are not
parent proxying.

### CODE REVIEW

**Comment by jpeach** [comment]
Sending early for review. Will add another commit with documentation.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1182/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1075/ for details.

**Comment by zwoop** [comment]
No docs for the new setting?

**Comment by jpeach** [comment]
@zwoop Added docs.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1085/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1192/ for details.

**Pull request merged**
