### PR TITLE
Modified uDNS AuTest extension

### PR DESCRIPTION
**Pull request by macisasandwich**
addRecords to uDNS extension
Documentation for uDNS, Condition.PluginExists and other minor fixes
Got rid of an unnecessary print statement

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci].

**Comment by persiaAziz** [comment]
Did you run autopep on the python files? I think there is a requirement now for doing that.

**Comment by macisasandwich** [comment]
Seems like microserver.test.ext was merged in without running autopep. But now all the files have been autopep'd.

**Comment by persiaAziz** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Comment by dragon512** [comment]
[approve ci]

**Pull request merged**
