### PR TITLE
Destroy threads after job done

### PR DESCRIPTION
**Pull request by duke8253**
This fixes the memory leak described in issue #7082.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by bryancall** [comment]
@duke8253 If you want this in ATS 9.0.x you should make the Project for 9.0.x

**Comment by duke8253** [comment]
@bryancall Thanks for the reminder, totally forgot to add that.

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
