### PR TITLE
Replace gethostbyname_r() with getaddrinfo()

### LINKED ISSUE #1312: [openbsd] build fails as openbsd doesn't have gethostbyname_r
OpenBSD doesn't have gethostbyname_r, see https://github.com/openbsd/src/blob/master/include/netdb.h

```
c++ -DHAVE_CONFIG_H -I. -I../../lib -I/home/jirib/openbsd/pobj/trafficserver-20170106/trafficserver-24347df553e91660b794af1079fbf69f986dc5b4/lib -I/usr/local/include -I/usr/local/include/lua-5.1/ -Dopenbsd -D_LARGEFILE64_SOURCE=1 -D_COMPILE64BIT_SOURCE=1 -D_GNU_SOURCE -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D_FORTIFY_SOURCE=2 -I/usr/include -DOPENSSL_NO_SSL_INTERN -I/usr/local/include/tcl8.5 -O2 -pipe -O0 -g -std=c++11 -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -fstack-protector -mcx16 -MT ink_inet.lo -MD -MP -MF .deps/ink_inet.Tpo -c ink_inet.cc -fPIC -DPIC -o .libs/ink_inet.o
ink_inet.cc: In function 'hostent* ink_gethostbyname_r(char*, ink_gethostbyname_r_data*)':
ink_inet.cc:62:116: error: 'gethostbyname_r' was not declared in this scope
   struct hostent *r = gethostbyname_r(hostname, &data->ent, data->buf, INK_GETHOSTBYNAME_R_DATA_SIZE, &data->herrno);
                                                                                                                    ^
ink_inet.cc: In function 'hostent* ink_gethostbyaddr_r(char*, int, int, ink_gethostbyaddr_r_data*)':
ink_inet.cc:82:129: error: 'gethostbyaddr_r' was not declared in this scope
   struct hostent *r = gethostbyaddr_r((char *)ip, len, type, &data->ent, data->buf, INK_GETHOSTBYNAME_R_DATA_SIZE, &data->herrno);
                                                                                                                                 ^
Error while executing c++ -DHAVE_CONFIG_H -I. -I../../lib -I/home/jirib/openbsd/pobj/trafficserver-20170106/trafficserver-24347df553e91660b794af1079fbf69f986dc5b4/lib -I/usr/local/include -I/usr/local/include/lua-5.1/ -Dopenbsd -D_LARGEFILE64_SOURCE=1 -D_COMPILE64BIT_SOURCE=1 -D_GNU_SOURCE -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D_FORTIFY_SOURCE=2 -I/usr/include -DOPENSSL_NO_SSL_INTERN -I/usr/local/include/tcl8.5 -O2 -pipe -O0 -g -std=c++11 -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -fstack-protector -mcx16 -MT ink_inet.lo -MD -MP -MF .deps/ink_inet.Tpo -c ink_inet.cc -fPIC -DPIC -o .libs/ink_inet.o
```

### PR DESCRIPTION
**Pull request by jablko**
Fixes #1312

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1334/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1228/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1335/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1229/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1230/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1336/ for details.

**Comment by bgaff** [comment]
Sure I'll review this very soon. Was this the final dependency for openbsd? I know when I was looking into it way back when it looked like this was only going to be one piece of it.

**Comment by jablko** [comment]
@bgaff Thanks! I messaged @jirib to see if building Traffic Server works for him now. This is the last of the four issues he reported, but yeah, I suspect there'll be more once his build gets past this point.

Either way, I think this change is productive, since 1) it moves a step closer to building on this platform -- OpenBSD doesn't implement gethostbyname_r(), 2) "The gethostbyname*() and gethostbyaddr*() functions are obsolete." at least according to [1]. "Applications should use getaddrinfo(3) and getnameinfo(3) instead.", and 3) this is the only occurrence of gethostbyname_r(), whereas we already depend on getaddrinfo() -- it's used elsewhere in the code.

[1] https://linux.die.net/man/3/gethostbyname_r

**Comment by bgaff** [comment]
This looks good to me! :+1:  

Thanks Jack

**Comment by bgaff** [comment]
Shall I merge it?

**Comment by jirib** [comment]
OpenBSD amd64 build passes this stage.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1253/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1360/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1361/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1254/ for details.

**Comment by jablko** [comment]
Thanks @bgaff  and @jirib! Merged.

**Comment by zwoop** [comment]
Are you guys comfortable with cherry-picking this to 7.1.0?

**Comment by bgaff** [comment]
I dont think it's a good idea personally. The patch is trivial to backport and the only known benefit is openbsd support. IMO risk isn't worth the reward, just my two cents.

**Comment by jablko** [comment]
I agree with @bgaff.

**Pull request merged**
