### PR TITLE
TS-4710 make srv_enabled transaction overrideable

### PR DESCRIPTION
**Pull request by jacksontj**
As I'm finishing up testing and cleanup of SRV records, I am getting ready to turn them on. When thinking through a ramp-up plan I noticed that there is no way to turn srv records on for just a single request/path etc. This moves the `srv_enabled` flag into the transaction configs so you can override it as you please.

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/394/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/497/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/498/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/395/ for details.

**Comment by zwoop** [comment]
Weird:


    REGRESSION TEST SDK_API_OVERRIDABLE_CONFIGS started
    FATAL: InkAPI.cc:8354: failed assertion `sdk_sanity_check_null_ptr((void *)name) == TS_SUCCESS`

**Comment by jacksontj** [comment]
@zwoop fixed, i forgot to add the new string to that test case. Added, and the test is passing locally. Its a bit of a pain to add overrideable config-- as it has to be added in ~5 places :/

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/504/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/401/ for details.

**Comment by jacksontj** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/505/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/402/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
