### PR TITLE
TS-4065: Change metrics to counters in RecordsConfig

### PR DESCRIPTION
**Pull request by meeramn**
I have fixed some metrics which have counter semantics by changing them from RECD_INT to RECD_COUNTER. Please review.

### CODE REVIEW

**Comment by bryancall** [comment]
@zwoop will shepard.

**Comment by zwoop** [comment]
The latest patch looks good to me, +1.

Meera: In addition, can you make another PR to fix the documentation for the metrics you found that are marked wrongly in the documentations?

**Comment by meeramn** [comment]
zwoop: This PR addressed those documentation changes already.

**Comment by zwoop** [comment]
Ah good, I must have missed it. Thanks!

**Pull request closed without merging**
