### PR TITLE
TS-4809 header_rewrite "hook" conditions checks

### PR DESCRIPTION
**Pull request by gtenev**
Added a check to make sure "hook" conditions are first in the rule set
and there is only one "hook" condition per rule set.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/684/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/580/ for details.

**Comment by zwoop** [comment]
Build again, VMs rebooted [approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/685/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/581/ for details.

**Comment by zwoop** [comment]
:+1:

**Pull request merged**
