### PR TITLE
TS-4746: ParentRecord *secondary_parents malloc, but no place free,which will cause memery leak

### PR DESCRIPTION
**Pull request by keith2008**
ParentRecord *secondary_parents malloc, but no place free,which will cause memery leak

### CODE REVIEW

**Comment by zwoop** [comment]
Just to be picky, but we should avoid typos in the commit messages (memory, not memory). I also think this could be simplified to just e.g.

4746 Fixes ParentRecord *secondary_parents memory leak

**Comment by zwoop** [comment]
Also, I'm pretty sure this would fail the CI build, please run "make clang-format" on the code, and push this again with the updated commit message.

Thanks!

**Comment by jrushford** [comment]
I don't think the NULL check on the pointer is required as ats_free does that under the hood.

**Comment by jrushford** [comment]
Closing this PR on behalf of keith2008 due to merge conflicts.  I am creating a new PR for this.

**Pull request closed without merging**
