### PR TITLE
TS_API for Note,Status,Warning,Alert,Fatal

### PR DESCRIPTION
**Pull request by a-canary**
Adding API calls for each level of syslog.

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Review by bneradt — APPROVED** [review]
Thanks for doing this. It will be helpful for plugins to have access to these other log types.

**Comment by randall** [comment]
Should this go into 9.0? It looks to be low risk.

**Comment by SolidWallOfCode** [comment]
This should definitely go in 9.1.

**Comment by zwoop** [comment]
It's already in 9.1.x.

**Comment by zwoop** [comment]
This was missed for 9.0.0, so adding it to 9.0.3.

**Pull request merged**
