### PR TITLE
Ts 4693

### PR DESCRIPTION
**Pull request by jacksontj**

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/383/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/486/ for details.

**Comment by zwoop** [comment]
Seems the commit message here is sort of missing?

**Comment by zwoop** [comment]
Ah I see, it's because of the multiple commits. Probably should squash this before push.

**Comment by jacksontj** [comment]
I can squash the 2 test commits, I like to keep tests in separate commits from the code-- easier to backport :)

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/488/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/385/ for details.

**Pull request merged**
