### PR TITLE
Add dead server policy control and metric. Improve messages.

### PR DESCRIPTION
**Pull request by bneradt**
(cherry picked from commit 01b91f348a919fa69ccd9727e39aae11bfca2a38)

---

This cherry-picks #7757 into 9.1.x.  These were the conflicts:

>         both modified:   mgmt/RecordsConfig.cc     
>         both modified:   proxy/http/HttpConfig.cc
>         both modified:   proxy/http/HttpTransact.cc 

One of the changes made here was to convert the dead server message to debug.

### CODE REVIEW

**Review by zwoop — APPROVED** [review]

**Review by shinrich — APPROVED** [review]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci autest]

**Pull request merged**
