### PR TITLE
TS-5084 Make logcat follow file rotation

### PR DESCRIPTION
**Pull request by danobi**
This patch makes `traffic_logcat -f` follow squid.blog even when
squid.blog is rotated. Previously, the tool did not do this at all.

This is implemented by keeping track of the _most_previous_ inode #
of squid.blog and comparing it with the most up to date value of
the inode # every now and then. If there is ever a difference, then
we close and reopen the log file.

### CODE REVIEW

**Comment by shinrich** [comment]
[approve ci]

**Comment by shinrich** [comment]
Logic looks good to me.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1264/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1159/ for details.

**Comment by shinrich** [comment]
@danobi can you squash?

**Comment by danobi** [comment]
@shinrich Done

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1298/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1192/ for details.

**Pull request merged**
