### PR TITLE
TS-5037: Fix LogFormat object leak.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1170/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1063/ for details.

**Comment by zwoop** [comment]
How does this leak? If the constructor of LogObject fails?

**Comment by jpeach** [comment]
The `LogObject` constructor copies the format.

**Pull request merged**
