### PR TITLE
TS-5076: Test and set the in_enabled_list by atomic function

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1240/ for details.

**Comment by zwoop** [comment]
This might honestly be a back port candidate? Does this apply to 7.0.x as well as 6.2.x ?

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1135/ for details.

**Comment by oknet** [comment]
agreed to backport to 7.0.x，6.2.x and 5.3.x too ?

**Comment by zwoop** [comment]
5.3.x is end-of-lifed, we're not doing any more releases of that.

**Pull request merged**
