### PR TITLE
Run cmake-format on .cmake files

### PR DESCRIPTION
**Pull request by bneradt**
I updated our format scripts earlier to run cmake-format on
CMakeLists.txt files, but forgot to add in our .cmake files. This
fixes that oversight.

---
# For the Reviewer

Note that I've separated this PR into two commits:
1. The script updates to run cmake-format.
2. The formatting changes from these updates.

### CODE REVIEW

**Review by JosiahWI — CHANGES_REQUESTED** [review]
We should format `.cmake.in` files as well. Right now this is only the configuration file for definitions, but we will probably have one for a CMake config export as well at some point.

**Comment by bneradt** [comment]
> We should format `.cmake.in` files as well. Right now this is only the configuration file for definitions, but we will probably have one for a CMake config export as well at some point.

Interestingly, the cmake-format script chokes on `.cmake.in` files (or, at least it chokes on the one that we have):

```
╰─➤  cmake-format -i include/tscore/ink_config.h.cmake.in  
WARNING __main__.py:530: While processing include/tscore/ink_config.h.cmake.in
ERROR __main__.py:638: Unexpected UNQUOTED_LITERAL token at 1:0
Traceback (most recent call last):
  File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 633, in main
    return inner_main()
           ^^^^^^^^^^^^
  File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 616, in inner_main
    onefile_main(infile_path, args, argparse_dict)
  File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 526, in onefile_main
    outtext, reflow_valid = process_file(cfg, intext, args.dump)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 158, in process_file
    parse_tree = parse.parse(tokens, ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/parse/__init__.py", line 68, in parse
    return BodyNode.consume(ctx, tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/parse/body_nodes.py", line 75, in consume
    raise InternalError(
cmakelang.common.InternalError
```

**Comment by JosiahWI** [comment]
> > We should format `.cmake.in` files as well. Right now this is only the configuration file for definitions, but we will probably have one for a CMake config export as well at some point.
> 
> Interestingly, the cmake-format script chokes on `.cmake.in` files (or, at least it chokes on the one that we have):
> 
> ```
> ╰─➤  cmake-format -i include/tscore/ink_config.h.cmake.in  
> WARNING __main__.py:530: While processing include/tscore/ink_config.h.cmake.in
> ERROR __main__.py:638: Unexpected UNQUOTED_LITERAL token at 1:0
> Traceback (most recent call last):
>   File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 633, in main
>     return inner_main()
>            ^^^^^^^^^^^^
>   File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 616, in inner_main
>     onefile_main(infile_path, args, argparse_dict)
>   File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 526, in onefile_main
>     outtext, reflow_valid = process_file(cfg, intext, args.dump)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/format/__main__.py", line 158, in process_file
>     parse_tree = parse.parse(tokens, ctx)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/parse/__init__.py", line 68, in parse
>     return BodyNode.consume(ctx, tokens)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/bneradt/src/ts_asf_master_format_dot_cmake_files/.git/fmt/cmake_format_v0.6.13_venv/lib/python3.11/site-packages/cmakelang/parse/body_nodes.py", line 75, in consume
>     raise InternalError(
> cmakelang.common.InternalError
> ```

Looks like they did not intend for `cmake-format` to work on CMake's various `.cmake.in` DSLs. Let's leave that alone for now, then.

**Review by JosiahWI — APPROVED** [review]
Looks good.

**Review by JosiahWI — APPROVED** [review]

**Comment by bneradt** [comment]
[approve ci]

**Review by cmcfarlen — APPROVED** [review]

**Pull request merged**
