### PR TITLE
Fixed issue where somaxconn was being set to 0 on OSX and preventing

### PR DESCRIPTION
**Pull request by bryancall**
ATS to work

### CODE REVIEW

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/1293/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1399/ for details.

**Comment by zwoop** [comment]
ink_inet.cc:613:10: error: unused variable 'value_size' [-Werror=unused-variable]
   size_t value_size = sizeof(value);

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1400/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1294/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1401/ for details.

**Pull request merged**
