### PR TITLE
Fix bug in IP matching for session pools where IP matching didn't work

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Although the code correctly finds the range of matching sessions, it doesn't actually pick one out for
the IP address matching case. This lead to a large growth in sessions when using IP address matching.

### CODE REVIEW

**Comment by bryancall** [comment]
@SolidWallOfCode Can we make a test for this?

**Comment by SolidWallOfCode** [comment]
Neu Brie is working on that. That might be a bit of a challenge as from an external view, things work fine without this fix, it is only by monitoring the internal stats that the problem can be observed. A real test might be resource intensive. Possibly you could set the number of `ET_NET` threads down low and not need as many simultaneous connections.

**Comment by shinrich** [comment]
Will also need to update microserver (or find some other origin) that doesn't close connections.

**Comment by bryancall** [comment]
Looks like this was fixed with #6066.  Please reopen if need be.

**Comment by SolidWallOfCode** [comment]
Might have been nice to have actual comments on the code, explaining what is going on, but I guess that's just not our thing.

**Pull request closed without merging**
