### PR TITLE
Add dead server policy control and metric. Improve messages.

### PR DESCRIPTION
**Pull request by shinrich**
This should help debug #7638.  Also addresses some issues in #7290

We are running with this changes in production.  I have exercised the new proxy.config.http.connect.dead.policy setting in production on a box, but @djcarlin needs to exercise it more widely.

This PR adds a setting proxy.config.http.connect.dead.policy to add some control over what kind of failures should count towards a dead server.  In our deployment, we want to only mark a server dead it if is failing the TCP level connection.  TLS failures like bad certificates may just be applicable to certain traffic to the server, so failures there should not mark the entire server dead.

The PR also adds a metric proxy.process.http.dead_server.no_requests to track how many client requests are returned immediately because the server is dead and retries is set to 0.

With this changes and dead.policy set to 1, we should be able to take advantage of PR #7142 and set the dead server retries to 0.

### CODE REVIEW

**Comment by shinrich** [comment]
[ci approve clang-format]

**Comment by shinrich** [comment]
[approve ci clang-format]

**Review by vmamidi — DISMISSED** [review]

**Review by vmamidi — APPROVED** [review]

**Comment by zwoop** [comment]
I would prefer this in 9.2., but willing to listen to arguments :-).

**Comment by maskit** [comment]
I'm curious how `proxy.config.http.connect.dead.policy` would work for QUIC connections. The current description explicitly says "TCP handshake failures", but it's not limited to the "handshake", right? I assume it includes connection failures due to DNS issue and packet routing issue as well.

If so, we might want to generalize the description (or clarifying the border) before we make a release with this to avoid incompatible changes in the future. That would also help implementing this for QUIC connections. If I read current description literally, QUIC connection failures would never be counted.

**Comment by zwoop** [comment]
@bneradt This has some merge conflicts, and as discussed, we'd like to change those Errors() for now for the 9.1.0 branch.

**Comment by zwoop** [comment]
Backported in #8213

**Pull request merged**
