### PR TITLE
Unify H2 log format

### PR DESCRIPTION
**Pull request by maskit**
All H2 log will contain connection id, and also stream id if available, with unified format.

### CODE REVIEW

**Comment by zwoop** [comment]
Hmmm, I'm slightly torn on this, for the simple reason that I think the way we do the same in other places is also somewhat broken. I much rather *not* have this type of indirection, because I really want to do "git grep 'Debug('" to find all places where we do debug. Extra abstractions like this make that a lot more difficult IMO. If anything, we should get rid of all other macros like this, and consistently use Debug() instead. :-).

That much said, I have no real technical arguments against this PR, and if this is what everyone else think we should do, I won't stand in the way.

**Comment by maskit** [comment]
A motivation of this change is that I want to grep logs too. I was looking into #2795 and I was annoyed with the inconsistent log format because I couldn't grep logs for a specific stream. I'm fine with other ways if it makes log format consistent.

How about renaming the macros like Http2StreamDebug. Then we can grep all places we do debug with the same pattern. Does it make this better?

Another options is using pure `Debug()` with predefined prefix strings, but it doesn't look like a right way.
```
Debug(LOG_PREFIX_HTTP2_STREAM"stream state %s", parent, parent->connection_id(), this->get_id(), Http2DebugNames::get_state_name(_state));
```

**Comment by zwoop** [comment]
Yes, that would be fine, and is more consistent with other similar macros. As long as the verb is <soemthing>Debug(), it's still greppable. Later, we should retrofit any other existing macros to adhere to this naming scheme as well.

**Comment by maskit** [comment]
Renamed all DebugHttp2Stream to Http2StreamDebug.

Http2DebugSsn and Http2DebugCon are still remained. Those and other "Debug*" macros should be renamed with the consistent naming convention. #2802.

**Comment by zwoop** [comment]
Need this for 7.1.2, to make cherry-picking other H2 changes less intrusive.

**Pull request merged**
