### PR TITLE
rate_limit: convert to using TSVConnSslSniGet

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by randall** [comment]
Requires https://github.com/apache/trafficserver/pull/8313

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci ubuntu]

**Comment by ywkaras** [comment]
[approve ci Ubuntu]

**Comment by ywkaras** [comment]
@bryancall can you kick the Ubuntu ci check on this PR?

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
