### PR TITLE
Fix certs used in tls related autests

### PR DESCRIPTION
**Pull request by duke8253**
Have been seeing some weird failures due to old certs, generated some new ones with 4096 bits.

### CODE REVIEW

**Comment by duke8253** [comment]
[approve ci clang-analyzer]

**Comment by randall** [comment]
is this needed if https://github.com/apache/trafficserver/pull/7451 is merged?

**Comment by brbzull0** [comment]
> is this needed if #7451 is merged?

they complement each other. I think they should go in together.
thanks.

**Review by bneradt — APPROVED** [review]

**Review by randall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
