### PR TITLE
Converted Apache::TS::AdminClient to use Dist::Zilla

### PR DESCRIPTION
**Pull request by bvierra**
Converted the perl module to use Dist::Zilla in preparation for updated release on CPAN. The current version is 0.03 which I figure is a little old.

The removal of some of the files is because Dist::Zilla automagically recreates them on release.

'# VERSION' is also replaced by 'our $VERSION = X.X.X' on Dist::Zilla build.

### CODE REVIEW

**Comment by PSUdaemon** [comment]
Sorry we've taken so long to get back to you. We haven't been paying much attention to pull requests not associated with JIRA's, but we are trying to.

Can you explain further what you are trying to accomplish with this patch?

**Comment by bryancall** [comment]
Can you please rebase this?  Besides that it looks good.

**Comment by bvierra** [comment]
Will have it up in a few hours

**Comment by zwoop** [comment]
Did this get updated?

**Comment by zwoop** [comment]
@bvierra  Ping?

**Comment by atsci** [comment]
Can one of the admins verify this patch?

**Comment by atsci** [comment]
Can one of the admins verify this patch? Only approve PRs which have been reviewed.

**Comment by zwoop** [comment]
Should we close this PR for now ?

**Pull request closed without merging**
