### PR TITLE
update build files with @LIBCAP@ to fix ubuntu build failures

### PR DESCRIPTION
**Pull request by dragon512**

### CODE REVIEW

**Comment by PSUdaemon** [comment]
The inconsistent spacing on the line continuation is setting off my OCD.

**Comment by zwoop** [comment]
It seems really unfortunate that we have to add libcap to like every binary... Is there no way to move out the offending commit / code that adds this to some library, and put it back into the one binary that needs this (traffic_manager) ?

**Comment by zwoop** [comment]
I wonder, does a patch like this address the same problem?

```
diff --git a/mgmt/utils/MgmtSocket.cc b/mgmt/utils/MgmtSocket.cc
index 9c372a890..bbb0c697d 100644
--- a/mgmt/utils/MgmtSocket.cc
+++ b/mgmt/utils/MgmtSocket.cc
@@ -23,7 +23,7 @@

 #include "ts/ink_platform.h"
 #include "ts/ink_assert.h"
-#include <ts/ink_cap.cc>
+#include "ts/ink_cap.h"
 #include "MgmtSocket.h"

 #if HAVE_UCRED_H
```

**Comment by dragon512** [comment]
This seems to address the real problem. I closing it. @zwoop said he is making a PR with the header change

**Pull request closed without merging**
