### PR TITLE
Fix tunnel routing documentation

### PR DESCRIPTION
**Pull request by pushkar2017**
Issue: https://github.com/apache/trafficserver/issues/4056

Documenting some missing settings that are required to get the tunnel routing working.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
[approve ci docs]

**Comment by zwoop** [comment]
Cherry-picked to 8.0.x

**Comment by zwoop** [comment]
If we want this into 7.1.x, please make a new PR against that branch.

**Comment by zwoop** [comment]
I'm going to remove the 7.1.5 Project on this, since going forward, we will need to make a second PR against the 7.1.x for proposed back ports.

**Pull request merged**
