### PR TITLE
TS-4503: Cause MachineFatal to terminate process without attempting m…

### PR DESCRIPTION
**Pull request by shinrich**
…emory cleanup.

### CODE REVIEW

**Comment by jpeach** [comment]
This somewhat defeats the fix in TS-4441. Rather than making fatal errors inconsistent, I think it is better to have the place that generates the error call ``ink_release_assert``.

We should also look into removing ``MachineFatal``.

**Comment by shinrich** [comment]
In our most recent fire drill, the core was very useful.  The particular problem only happens under very heavy load.  By poking around the core, we got some idea of the underlying cause and were able to add additional checks to attempt to catch the problem next time around.  

The problem was that the reported stack was showing secondary errors from the memory cleanup.  So we were looking in the wrong area for several days until we got access to the machine and core.  Then staring at the core for a while until it occurred to me to do "info thread" and find the real problem.

**Comment by jpeach** [comment]
But ``Fatal`` doesn't drop a core and it shouldn't so this should behave the same. I'm all for adding asserts near the root cause but I don't think we should drop core on managed errors, and really this whole ``Machine`` API adds little value.

**Comment by shinrich** [comment]
Ok, I see you point.  I have no love lost for MachineFatal.  This is my first encounter with it.  I'll try replacing it's use in ProtocolProbeSessionAccept with Fatal and add a ink_release_assert there.

Actually it just looks like it is used in the various Accept classes.  I'll look at replacing all 5 instances and removing MachineFatal.

**Comment by jpeach** [comment]
If you need to explicitly dump core from somewhere you can use ``ink_abort``.

**Comment by atsci** [comment]
Testing

**Comment by zwoop** [comment]
Testing, this will blow up and I'm blaming @PSUdaemon  [approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/308/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/201/ for details.

**Comment by zwoop** [comment]
Testing again, this will blow up and I'm blaming @PSUdaemon [approve ci]

**Comment by shinrich** [comment]
Closing this PR.  Will create a new one that replaces the use of MachineFatal with Fatal.  I started this a couple weeks and it looks like we can remove all the *Fatal() functions with little effort.  Unfortunately got distracted before I got that finished.

**Pull request closed without merging**
