### PR TITLE
[TS-4098]Fix remap filtering for nonstandard methods

### PR DESCRIPTION
**Pull request by kawaiirice**

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/682/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/786/ for details.

**Comment by zwoop** [comment]
Clang-forma, trailing white spaces here:

```C++
-        } else {  
+        } else {
```

**Comment by jpeach** [comment]
@kawaiirice Can you please take a look at [this}(https://cwiki.apache.org/confluence/display/TS/CommitPolicies) and update the commit message accordingly? thanks

**Comment by SolidWallOfCode** [comment]
I'll take care of it.

**Comment by kawaiirice** [comment]
I was going to update the commit message now but thanks, Alan!

**Pull request closed without merging**
