### PR TITLE
TS autest extension can now auto select both ssl and nonssl port

### PR DESCRIPTION
**Pull request by macisasandwich**
Along with relevant test modifications

### CODE REVIEW

**Comment by macisasandwich** [comment]
Autest is failing due to an out of date version of Autest used in the image.

**Comment by shinrich** [comment]
We have been running with these changes internally for a while.  By not hardcoding the SSL ports (which was previously required) should avoid transient port collision errors.

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
[approve ci autest]

**Comment by randall** [comment]
@macisasandwich Is this still needed? If so, can you rebase?

**Comment by macisasandwich** [comment]
@randall Yeah I will rebase this PR and fix the 2 test errors once I come back to America from vacation.

**Pull request closed without merging**
