### PR TITLE
Add thread yield to avoid busy waiting in LogObject::_checkout_write().

### LINKED ISSUE #7546: LogObject::_checkout_write using a lot of CPU on many core servers
When running benchmarking on large AMD servers (128 core servers) I am seeing a large amount of CPU being used in `LogObject::_checkout_write`.  Here are the results from the benchmark:

https://github.com/bryancall/benchmark/blob/main/reports/amd_epic_7742_rhel7_aocc_rpms_no-freelist_jemalloc_openss111/http2_benchmark.report

### PR DESCRIPTION
**Pull request by ywkaras**
This closes #7546

### CODE REVIEW

**Comment by ywkaras** [comment]
See associated issue for description of performance testing that supports this change.

**Comment by bryancall** [comment]
Screen Shot 2021-03-26 at 5 45 19 PM

**Review by bryancall — APPROVED** [review]

**Comment by bryancall** [comment]
```
**http2load**
finished in 33.10s, 181277.48 req/s, 2.77GB/s
requests: 6000000 total, 6000000 started, 6000000 done, 6000000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 6000000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 91.75GB (98514111221) total, 45.88MB (48105141) headers (space savings 96.66%), 91.55GB (98304000000) data
                     min         max         mean         sd        +/- sd
time for request:       83us     54.32ms      1.04ms       690us    93.72%
time for connect:    10.70ms    307.99ms     94.83ms     79.36ms    75.00%
time to 1st byte:    40.72ms    310.73ms    114.99ms     71.51ms    76.00%
req/s           :     864.28     1073.49      934.15       70.05    70.00%

**dstat**
You did not select any stats, using -cdngy by default.
ESC[7l----total-cpu-usage---- -dsk/total- ---net/lo-- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send: recv  send|  in   out | int   csw
  1   0  99   0   0   0|2813B  243k|   0     0 :   0     0 |   0     0 |  21k   60k
 16  20  62   0   0   1| 296k   18M|2777M 2777M:1542B  817B|   0     0 | 745k 1163k
 16  22  61   0   0   1| 410B   48M|2977M 2977M:2846B 1507B|   0     0 | 769k 1162k
 15  21  62   0   0   1|   0    63k|2965M 2965M:4500B   12k|   0     0 | 763k 1194k
**perf report**
# Total Lost Samples: 0
#
# Samples: 9M of event 'cycles'
# Event count (approx.): 5588002519667
#
#   Overhead  Shared Object         Symbol
# ..........  ....................  ..................................................
#
      31.33%  [kernel.vmlinux]      [k] native_queued_spin_lock_slowpath
       3.22%  [kernel.vmlinux]      [k] copy_user_generic_string
       2.08%  [kernel.vmlinux]      [k] acpi_processor_ffh_cstate_enter
       1.88%  libc-2.17.so          [.] __memcpy_ssse3
       1.88%  libcrypto.so.1.1      [.] _aesni_ctr32_ghash_6x
       1.61%  libtscore.so.9.0.1    [.] malloc_new
       1.12%  libtscore.so.9.0.1    [.] malloc_free
       0.89%  libtscore.so.9.0.1    [.] ink_freelist_new
       0.87%  libpthread-2.17.so    [.] pthread_mutex_lock
       0.86%  traffic_server        [.] LogObject::_checkout_write
       0.86%  libc-2.17.so          [.] _int_malloc
       0.72%  [kernel.vmlinux]      [k] futex_wait_setup
       0.70%  [kernel.vmlinux]      [k] __switch_to
       0.66%  [kernel.vmlinux]      [k] try_to_wake_up
```

**Comment by bryancall** [comment]
This is a benchmark without this patch:
```
**http2load**
finished in 39.84s, 150593.28 req/s, 2.30GB/s
requests: 6000000 total, 6000000 started, 6000000 done, 6000000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 6000000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 91.75GB (98514116221) total, 45.88MB (48110201) headers (space savings 96.66%), 91.55GB (98304000000) data
                     min         max         mean         sd        +/- sd
time for request:       83us    141.08ms      1.49ms      3.72ms    97.67%
time for connect:    12.27ms    104.40ms     64.96ms     32.66ms    53.00%
time to 1st byte:    45.25ms    144.74ms     89.74ms     29.68ms    57.50%
req/s           :     717.27      891.58      773.08       61.00    70.00%

**dstat**
You did not select any stats, using -cdngy by default.
----total-cpu-usage---- -dsk/total- ---net/lo-- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send: recv  send|  in   out | int   csw
  1   0  99   0   0   0|2815B  243k|   0     0 :   0     0 |   0     0 |  21k   60k
 40  10  48   0   0   1| 156k   10M|1371M 1371M:2936B 5027B|   0     0 | 761k  611k
 20  20  59   0   0   1|   0  2361k|2633M 2633M:1438B  876B|   0     0 | 779k 1064k
 16  22  61   0   0   1|   0    48M|2778M 2778M:4512B 2669B|   0     0 | 766k 1099k
**perf report**
# Total Lost Samples: 0
#
# Samples: 11M of event 'cycles'
# Event count (approx.): 7473451538675
#
#   Overhead  Shared Object         Symbol
# ..........  ....................  ..................................................
#
      25.24%  [kernel.vmlinux]      [k] native_queued_spin_lock_slowpath
      22.04%  traffic_server        [.] LogObject::_checkout_write        <------------
       2.43%  [kernel.vmlinux]      [k] copy_user_generic_string
       1.62%  [kernel.vmlinux]      [k] acpi_processor_ffh_cstate_enter
       1.44%  libc-2.17.so          [.] __memcpy_ssse3
       1.41%  libcrypto.so.1.1      [.] _aesni_ctr32_ghash_6x
       1.19%  libtscore.so.9.0.1    [.] malloc_new
       0.83%  libtscore.so.9.0.1    [.] malloc_free
       0.68%  libpthread-2.17.so    [.] pthread_mutex_lock
       0.65%  libtscore.so.9.0.1    [.] ink_freelist_new
       0.63%  libc-2.17.so          [.] _int_malloc
       0.55%  [kernel.vmlinux]      [k] futex_wait_setup
       0.53%  [kernel.vmlinux]      [k] try_to_wake_up
       0.53%  [kernel.vmlinux]      [k] __switch_to
       0.51%  traffic_server        [.] HpackIndexingTable::lookup
```

**Comment by ywkaras** [comment]
C'mon @zwoop , it's only one line of code, wha-fur thin, approve it.

**Review by zwoop — APPROVED** [review]
so magic happens here, and std::this_thread::yield will give Linux a hint to stop fucking around, and let someone else do something?

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.
Cherry-picked to v9.1.x branch.

**Comment by ezelkow1** [comment]
Can we get a back port PR for 8.1.x for this?

**Comment by zwoop** [comment]
@ezelkow1 You may have to ping Walt directly if you want him to make a back port, or, just do it yourself :-).

**Comment by ywkaras** [comment]
https://github.com/apache/trafficserver/pull/7906 zwoop there it is.

**Pull request merged**
