### PR TITLE
Removes non-FS ciphers to make SSLLabs not warn on weak ciphers

### PR DESCRIPTION
**Pull request by zwoop**
This is as reported by SSLLabs, and doing this change eliminates
their warnings about weak non-FS ciphers.

### CODE REVIEW

**Comment by zwoop** [comment]
Before patch: before patch

After patch: 
after patch

**Comment by maskit** [comment]
It seems fine but probably not. #4007

**Comment by zwoop** [comment]
Ok, so probably we should remove the TLS v1.3 portion out of this patch then, and just fix the weak ciphers that are in TLS  < v1.3 ?

We probably should make sure we can get the TLS v1.3 ciphers in v8.0.x of ATS as well IMO, particularly if we need to add a new configuration (I'm hoping we can avoid a new config).

**Comment by zwoop** [comment]
I removed the TLS13_ portion from this PR. The Weak ciphers change is still as above (same effect on the SSLLabs checks).

**Comment by zwoop** [comment]
@masaori335 @maskit Please confirm that you think this is a good change for 8.0.0 or not.

**Comment by masaori335** [comment]
I'm pretty sure that this is a good change for 8.0.0. According to "Handshake Simulation" on SSLLabs, no client selects these ciphers. It looks no critical side effect of removing them.

**Pull request merged**
