### PR TITLE
access_control: Remove unused dumpHeaders

### PR DESCRIPTION
**Pull request by bneradt**
dumpHeaders is unused, so removing it.

### CODE REVIEW

**Comment by JosiahWI** [comment]
LSan detected a memory leak in the magick plugin.

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Comment by JosiahWI** [comment]
The same failure was repeated.

**Comment by JosiahWI** [comment]
[approve ci rocky]

**Review by maskit — APPROVED** [review]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
