### PR TITLE
Fix lost pending_actions causing actions on stale objects.

### PR DESCRIPTION
**Pull request by shinrich**
(cherry picked from commit 493803c4e26348a9c707320a134709d832f9a182)

Conflicts:
	proxy/http/HttpSM.cc

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by zwoop** [comment]
Cherry-picked to 8.1.x

**Comment by zwoop** [comment]
Reverting again on 8.1.x :-/ @ezelkow1 Can you provide some details here how the crashes happens, so we can maybe figure out what is going wrong.

**Comment by ezelkow1** [comment]
This is the crash dump from the 4 autests that would trigger this (syntax, http408, tls, redirect_post):

Fatal: HttpSM.cc:1740: failed assertion `pending_action == nullptr || pending_action == vc->get_action()`
Traffic Server 8.1.044.c351e20.el7 Mar 25 2020 16:00:20 66252f8ebcb4
traffic_server: using root directory '/home/tester/tests/_sandbox/syntax/ts'
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE:
traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x8e)[0x49aafe]
/lib64/libpthread.so.0(+0xf5f0)[0x7f01e06305f0]
/lib64/libc.so.6(gsignal+0x37)[0x7f01df866337]
/lib64/libc.so.6(abort+0x148)[0x7f01df867a28]
/opt/trafficserver/lib/libtscore.so.8(+0x575cb)[0x7f01e202a5cb]
/opt/trafficserver/lib/libtscore.so.8(+0x54625)[0x7f01e2027625]
traffic_server(_ZN6HttpSM22state_http_server_openEiPv+0x3da)[0x508a5a]
traffic_server(_ZN6HttpSM12main_handlerEiPv+0x100)[0x505730]
traffic_server(_ZN12CheckConnect14handle_connectEiP5Event+0x616)[0x7110a6]
traffic_server[0x7132a2]
traffic_server(_Z15write_to_net_ioP10NetHandlerP18UnixNetVConnectionP7EThread+0xce0)[0x71b530]
traffic_server(_ZN10NetHandler18process_ready_listEv+0x27f)[0x70477f]
traffic_server(_ZN10NetHandler15waitForActivityEl+0x26d)[0x704a3d]
traffic_server(_ZN7EThread15execute_regularEv+0x6e9)[0x7518e9]
traffic_server[0x74feea]
/lib64/libpthread.so.0(+0x7e65)[0x7f01e0628e65]
/lib64/libc.so.6(clone+0x6d)[0x7f01df92e88d]

We also tried porting in the more up to date version which changes the assert but it would still occur at the same location with the new line:
 ink_release_assert(pending_action == nullptr || pending_action->continuation == vc->get_action()->continuation);

**Pull request merged**
