### PR TITLE
TS-4932: Add a passthru example plugin.

### PR DESCRIPTION
**Pull request by jpeach**
This is a protocol plugin example that demonstrates how to proxy
traffic from a custom port to an internal request using
TSHttpConnectWithPluginId().

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/921/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/815/ for details.

**Comment by jpeach** [comment]
Tested with ``http_load`` and large POSTS against [httpbin](http://httpbin.org/).

**Comment by bryancall** [comment]
I didn't see any issues, but it would be good to test with a large POST body and response.

**Comment by jpeach** [comment]
@bryancall Tested large POST w/ httpbin.

**Comment by bryancall** [comment]
More comments would be helpful since this is an example plugin.

**Comment by jpeach** [comment]
OK, will add more comments later in the week.

**Pull request merged**
