### PR TITLE
Proxy txn cleanup 9

### PR DESCRIPTION
**Pull request by a-canary**
Proving to Leif that my code merges into 9.

### CODE REVIEW

**Comment by zwoop** [comment]
Can you redo this, with "git cherry-pick -x" commands, such that the commit message above clearly shows which commits have been cherry picked?

**Comment by zwoop** [comment]
Or, tell me in what order all the different PRs needs to be applied ...

**Comment by a-canary** [comment]
All the original PRs are marked for the 9.0.x Branch Project. But here they are:
#5852 #5864 #5869 #5880 #5892 #5908

**Comment by zwoop** [comment]
Thanks! CP'ed the relevant PRs, so closing this.

**Pull request closed without merging**
