### PR TITLE
TS-4584: Resource leak, CID 1254818 and 1254809

### PR DESCRIPTION
**Pull request by alhonen**
Coverity issues CID 1254818 and 1254809, a resource leak on file descriptor
and allocated memory.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/330/ for details.

**Comment by zwoop** [comment]
This fails on clang-format, please re-run and push --force.

**Comment by zwoop** [comment]
add to whitelist

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/331/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/437/ for details.

**Comment by zwoop** [comment]
Could we use the ats_scoped_obj here? Or some other smart ptr? I'm ok either way,  but maybe we should encourage these smart pointer patterns?

This might change memory management though (malloc/free vs new/delete) ? Don't go out of your way though if it's going to be really complex.

**Comment by alhonen** [comment]
I'm testing the scoped pointer approach now.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/481/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/378/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/434/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/537/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/538/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/435/ for details.

**Comment by alhonen** [comment]
Scoped pointer approach posted.

**Pull request merged**
