### PR TITLE
Clean up some leftovers from the alarms removal.

### PR DESCRIPTION
**Pull request by brbzull0**
Removes some unused records and their respective documentation.

### CODE REVIEW

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci fedora]

**Review by randall — APPROVED** [review]

**Pull request merged**
