### PR TITLE
Fix build for 32bits armhf arch. Partialy closes #4361

### LINKED ISSUE #4361: Build fails on Debian for architecture armel, amrhf, mips & mipsel with "error: template-id 'ink_atomic_swap<int64_t>' used as a declarator" error
All theses architecture fail with same error:
```Making all in records
make[3]: Entering directory '/<<PKGBUILDDIR>>/lib/records'
c++ -DHAVE_CONFIG_H -I. -I../../include  -Dlinux -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/<<PKGBUILDDIR>>/iocore/eventsystem -I/<<PKGBUILDDIR>>/iocore/utils -I/<<PKGBUILDDIR>>/mgmt -I/<<PKGBUILDDIR>>/mgmt/api/include -I/<<PKGBUILDDIR>>/mgmt/utils -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/lib -I/usr/include/tcl8.6 -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -std=c++17 -g -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -Wno-noexcept-type -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -O3 -c -o P_RecCore.o P_RecCore.cc
c++ -DHAVE_CONFIG_H -I. -I../../include  -Dlinux -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/<<PKGBUILDDIR>>/iocore/eventsystem -I/<<PKGBUILDDIR>>/iocore/utils -I/<<PKGBUILDDIR>>/mgmt -I/<<PKGBUILDDIR>>/mgmt/api/include -I/<<PKGBUILDDIR>>/mgmt/utils -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/lib -I/usr/include/tcl8.6 -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -std=c++17 -g -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -Wno-noexcept-type -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -O3 -c -o RecConfigParse.o RecConfigParse.cc
c++ -DHAVE_CONFIG_H -I. -I../../include  -Dlinux -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/<<PKGBUILDDIR>>/iocore/eventsystem -I/<<PKGBUILDDIR>>/iocore/utils -I/<<PKGBUILDDIR>>/mgmt -I/<<PKGBUILDDIR>>/mgmt/api/include -I/<<PKGBUILDDIR>>/mgmt/utils -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/lib -I/usr/include/tcl8.6 -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -std=c++17 -g -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -Wno-noexcept-type -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -O3 -c -o RecCore.o RecCore.cc
c++ -DHAVE_CONFIG_H -I. -I../../include  -Dlinux -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D__STDC_LIMIT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -I/<<PKGBUILDDIR>>/iocore/eventsystem -I/<<PKGBUILDDIR>>/iocore/utils -I/<<PKGBUILDDIR>>/mgmt -I/<<PKGBUILDDIR>>/mgmt/api/include -I/<<PKGBUILDDIR>>/mgmt/utils -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/lib -I/usr/include/tcl8.6 -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -DOPENSSL_NO_SSL_INTERN -std=c++17 -g -pipe -Wall -Wextra -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-format-truncation -Wno-cast-function-type -Wno-stringop-overflow -feliminate-unused-debug-symbols -fno-strict-aliasing -Wno-invalid-offsetof -Wno-noexcept-type -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -O3 -c -o RecDebug.o RecDebug.cc
In file included from P_RecUtils.h:27,
                 from RecDebug.cc:24:
../../include/tscore/ink_atomic.h:96:26: error: template-id 'ink_atomic_swap<int64_t>' used as a declarator
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
                          ^~~~~~~
../../include/tscore/ink_atomic.h:96:26: error: 'pvint64' was not declared in this scope
In file included from P_RecUtils.h:27,
                 from P_RecCore.cc:33:
../../include/tscore/ink_atomic.h:96:26: error: template-id 'ink_atomic_swap<int64_t>' used as a declarator
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
                          ^~~~~~~
../../include/tscore/ink_atomic.h:96:26: note: suggested alternative: 'printf'
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
                          ^~~~~~~
                          printf
../../include/tscore/ink_atomic.h:96:47: error: expected primary-expression before 'value'
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
                                               ^~~~~
../../include/tscore/ink_atomic.h:96:52: error: expression list treated as compound expression in initializer [-fpermissive]
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
                                                    ^
../../include/tscore/ink_atomic.h:96:1: warning: too many template headers for 'ink_atomic_swap' (should be 0)
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
 ^~~~~~~~~~~~~~~~~~~~~~~~
../../include/tscore/ink_atomic.h:96:53: error: expected ';' before '{' token
 ink_atomic_swap<int64_t>(pvint64 mem, int64_t value)
                                                     ^
                                                     ;
 {
 ~                                                    ```

### PR DESCRIPTION
**Pull request by jbfavre**
Had also to update links for traffic_cache_tool

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by jbfavre** [comment]
Build is not OK for armel & mips. We got other errors.
Should be OK on armhf since I tested it on this architecture

**Comment by maskit** [comment]
Since `pvint64` is no longer available and this fixes build on one platform at least, I'm fine with merging this.
Should we land this for now or wait for updates?

**Comment by jbfavre** [comment]
Closed by error.
Sorry

**Comment by jbfavre** [comment]
@SolidWallOfCode thanks for trusting me, but I'm afraid I'm far for being able to work on that.
I only have basic c++ knowledge which allow me to manage small patches like this one. but honestly, you don't want me to do more for now ;)

**Comment by maskit** [comment]
[approve ci]

**Pull request merged**
