### PR TITLE
Cleans up duplicated TSOutboundConnectionMatchType definition

### PR DESCRIPTION
**Pull request by randall**

### CODE REVIEW

**Comment by maskit** [comment]
Can you tell me why you chose to keep the one in apidefs.h.in ?

A comment in HttpProxyAPIEnums.h says "Traffic Server SDK API - HTTP related enumerations". I'm not sure which file I should edit when I want to add some enumeration.

**Comment by randall** [comment]
I threw the dice and chose that one. Really it seems better that it should be in HttpProxyAPIEnums.h. 

I threw up this PR because I ran across this yesterday and thought it was kind of a WTF and was hoping the community had a better idea what's going on here (since it's the only struct/typedef like this)

**Comment by maskit** [comment]
@SolidWallOfCode @shinrich I'd like to hear opinions from people who added this file and the guard.

**Comment by bryancall** [comment]
[approve ci docs]

**Comment by zizhong** [comment]
I guess this way the plugin, like conf-remap, can use the same definition.

**Comment by SolidWallOfCode** [comment]
I'm trying to remember. Clearly the enum is in "apidefs.h" so it is available to plugins. I think it was elsewhere both because of legacy (it had always been there) and to avoid additional dependencies (e.g., any core code that needs to use those values must include all of "apidefs.h"). Maybe things have changed elsewhere, but I know I tried doing this earlier and it didn't compile for lack of that include, but I don't see such a change in your PR. If this works without such a change it seems reasonable.

**Comment by ywkaras** [comment]
Everyone agree now this is good?  Don't want to jump the gun by approving.

**Review by maskit — APPROVED** [review]
I'm still not sure where to add new enums. I only agree to removing the duplicated definition, but not keeping two places to have enums.

**Comment by bryancall** [comment]
[approve ci]

**Review by bryancall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.1.x branch.

**Pull request merged**
