### PR TITLE
Handy tool to decode via header

### PR DESCRIPTION
**Pull request by meeramn**
Handy tool developed in perl few years ago to easily decode via header.

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
[approve ci]

**Comment by SolidWallOfCode** [comment]
How is this different / better than `cmd/traffic_via`?

**Comment by zwoop** [comment]
Once we land this, I'll take care of moving and replacing the existing cmd/traffic_server code. 

@SolidWallOfCode @bryancall I'd like to get this in for 8.0.0 as well. The issue is that the C++ version of traffic_via requires a full ATS installation, because it uses the mgmt APIs / port. That makes the tool much less useful IMO, and in retrospect, it was a mistake asking for the rewrite from Perl to C++.

**Comment by SolidWallOfCode** [comment]
OK.

**Comment by bryancall** [comment]
Tested and I like the option to take stdin.

```
09:37:56 homer:/tmp$ curl -s -D - -o /dev/null http://s.yimg.com/ | ./via_decoder.pl
Via Header is [c s f ]
Via Header details:
Request headers received from client:                  unknown?
Result of Traffic Server cache lookup for URL:         unknown?
Response information received from origin server:      no server connection needed
```

**Comment by bryancall** [comment]
[approve ci]

**Comment by mlibbey** [comment]
This is for #3809

**Comment by bryancall** [comment]
[approve ci]

**Comment by bryancall** [comment]
[approve ci whitelist]

**Pull request merged**
