### PR TITLE
Allow number of settings per H2 session to be configurable

### PR DESCRIPTION
**Pull request by maskit**
(cherry picked from commit d91a8ca17bb17b08ce7f040b868e3c286a7bb0a6)

 Conflicts:
	doc/admin-guide/files/records.config.en.rst
	mgmt/RecordsConfig.cc
	proxy/http2/HTTP2.cc
	proxy/http2/HTTP2.h
	proxy/http2/Http2ConnectionState.h

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci ubuntu]

**Comment by zwoop** [comment]
We can ignore these two failed builds, for now.

**Comment by bryancall** [comment]
This went into the 8.0.4 release.

**Pull request merged**
