### PR TITLE
Remove incompatible changes for 9.2.0

### PR DESCRIPTION
**Pull request by bneradt**
We are preparing to branch 9.2.0 from master. In order to do this we need to remove all the incompatible changes currently in master. Our plan is this:

* Remove the incompatible changes from master using this PR. This PR contains all of the commits in the PRs currently marked with the "Incompatible" label reverted.
* Merge this PR via a squash merge (as usual) into master.
* Branch 9.2.0 from the point of this commit. It will not have these changes which are being reverted.
* Revert this single squashed commit on master so it has them again.

### CODE REVIEW

**Comment by shinrich** [comment]
For the abort_threshold PR, part of that did go into 9.x 0bc810f0c2991e97a8ea4ff94deb6f248be694fd).  The additional PR on master was just removing the enums, but it looks like this revert commit is adding back the documentation.

**Comment by shinrich** [comment]
Aside from the abort_threshold commits, the rest of the changes that I'm familiar with looked fine.

**Comment by bneradt** [comment]
> Aside from the abort_threshold commits, the rest of the changes that I'm familiar with looked fine.

Thanks Susan! I'll put the other commit in and only leave the one that reverts the enums.

**Comment by maskit** [comment]
I'm fine with the plan, but I wonder why we want to revert incompatible changes on master first. I guess we can revert incompatible changes only on 9.2.x after branching 9.2.x. Commit history wise there would be no difference on 9.2.x branch. It would be just that there's no incompatible changes at the branching point. Although it sounds ideal, it implies that we have to redo whole this process if we find another incompatible change later.

**Comment by bneradt** [comment]
> I'm fine with the plan, but I wonder why we want to revert incompatible changes on master first. I guess we can revert incompatible changes only on 9.2.x after branching 9.2.x. Commit history wise there would be no difference on 9.2.x branch. It would be just that there's no incompatible changes at the branching point. Although it sounds ideal, it implies that we have to redo whole this process if we find another incompatible change later.

Thanks for the thoughts. We shouldn't have to redo the whole process. If we find other incompatible changes after branching 9.2.x, we can just revert those on the 9.2.x branch. Master won't need any commits.

**Comment by zwoop** [comment]
Yeh, the reason for these steps was to having to redo these types of revert every time we make a branch off master. Maybe 9.2.x will be the last 9 branch, but if we do a 9.3.x and 9.4.x, it'll be nice to have "master" in a shape that's 100% 9.x compatible, and the 10-Dev branch with all the incompatible (and bigger) changes.

**Comment by zwoop** [comment]
@bneradt Can you add a comment here, listing all the PR #'s one by one, so we have a nice, clickable list of links of the PRs that are reverted ?

**Comment by bneradt** [comment]
> @bneradt Can you add a comment here, listing all the PR #'s one by one, so we have a nice, clickable list of links of the PRs that are reverted ?

Sure thing: 

1. https://github.com/apache/trafficserver/pull/8077
2. https://github.com/apache/trafficserver/pull/8066
3. https://github.com/apache/trafficserver/pull/7901
4. https://github.com/apache/trafficserver/pull/7693
5. https://github.com/apache/trafficserver/pull/7587
6. https://github.com/apache/trafficserver/pull/7547
7. https://github.com/apache/trafficserver/pull/7756
8. https://github.com/apache/trafficserver/pull/7335
9. https://github.com/apache/trafficserver/pull/7302
10. https://github.com/apache/trafficserver/pull/6602

**Review by zwoop — APPROVED** [review]
Love it

**Review by maskit — COMMENTED** [review]
Thank you for clarification. I think I understand.

**Comment by zwoop** [comment]
I've changed Milestone and Project for all these PRs to "10-Dev".

**Pull request merged**
