### PR TITLE
Weak mutex locking macros

### PR DESCRIPTION
**Pull request by duke8253**
This deals with the problem brought up in the discussions under PRs #5855 and #5857. And also makes the change such that #4926 still works as intended.

### CODE REVIEW

**Comment by scw00** [comment]
Should this pr revert ? https://github.com/apache/trafficserver/pull/5857

**Comment by scw00** [comment]
It seems this pr is duplicated with  #5857. So why do we still need #5857 .

**Comment by duke8253** [comment]
Not sure why it's failing on systems other than Ubuntu, I'll get some vms to test.

**Comment by duke8253** [comment]
[approve ci autest]

**Comment by duke8253** [comment]
[approve ci clang-analyzer]

**Comment by bryancall** [comment]
This PR is to fix this core dump:
```
[ 0 ] traffic_server      Mutex_lock                            ( I_Lock.h:295 )
[ 1 ] traffic_server      MutexLock                             ( I_Lock.h:363 )
[ 2 ] traffic_server      AutoStopCont::mainEvent(int, Event*)  ( traffic_server.cc:233 )
[ 3 ] traffic_server      EThread::process_event(Event*, int)   ( I_Continuation.h:167 )
[ 4 ] traffic_server      EThread::execute_regular()            ( UnixEThread.cc:249 )
[ 5 ] traffic_server      execute                               ( UnixEThread.cc:338 )
[ 6 ] traffic_server      EThread::execute()                    ( UnixEThread.cc:316 )
[ 7 ] traffic_server      spawn_thread_internal                 ( Thread.cc:92 )
[ 8 ] libpthread-2.17.so  start_thread                          
```

**Comment by bryancall** [comment]
This PR is to fix this core dump (supplied by @duke8253):
```
[ 0 ] traffic_server      Mutex_lock                            ( I_Lock.h:295 )
[ 1 ] traffic_server      MutexLock                             ( I_Lock.h:363 )
[ 2 ] traffic_server      AutoStopCont::mainEvent(int, Event*)  ( traffic_server.cc:233 )
[ 3 ] traffic_server      EThread::process_event(Event*, int)   ( I_Continuation.h:167 )
[ 4 ] traffic_server      EThread::execute_regular()            ( UnixEThread.cc:249 )
[ 5 ] traffic_server      execute                               ( UnixEThread.cc:338 )
[ 6 ] traffic_server      EThread::execute()                    ( UnixEThread.cc:316 )
[ 7 ] traffic_server      spawn_thread_internal                 ( Thread.cc:92 )
[ 8 ] libpthread-2.17.so  start_thread                          
```

**Comment by bryancall** [comment]
Cherry picked to the 9.0.x branch.

**Pull request merged**
