### PR TITLE
Remove duplicate setup in http3 tests

### PR DESCRIPTION
**Pull request by JosiahWI**
There was a lot of unnecessary duplication. As more tests are added the current pattern will worsen if not remediated.

### CODE REVIEW

**Comment by JosiahWI** [comment]
[approve ci autest]

**Review by cmcfarlen — APPROVED** [review]
neat

**Review by maskit — APPROVED** [review]

**Comment by JosiahWI** [comment]
The AuTest prefetch_bignum failed. I saved a copy of the build artifacts to start debugging it.

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x (to resolve conflicts)

**Pull request merged**
