### PR TITLE
Cleanup/Flatten out some headers inclusion

### PR DESCRIPTION
**Pull request by lzx404243**
Streamlining some sources files by removing unused includes and flatten out includes. This cleanup follows a 'random walk' approach, selectively adopting the 'include-what-you-use' tool's suggestions.

More such cleanups are done in coming PRs.

### CODE REVIEW

**Comment by lzx404243** [comment]
[ci approve autest]

**Comment by lzx404243** [comment]
[approve ci autest]

**Comment by bneradt** [comment]
[approve ci osx]

**Comment by bneradt** [comment]
[approve ci format]

**Pull request merged**
