### PR TITLE
Update the HTTP/3 library dependencies

### PR DESCRIPTION
**Pull request by bneradt**
This updates boringssl with a fix for the toolset that comes with fedora:39:

https://bugs.chromium.org/p/boringssl/issues/detail?id=642

This also updates to the latest curl release, 8.2.1, and updates its ng* dependencies.

---

I ran all the autests locally with these libraries, building against quiche, and the tests all passed except for the `via` test which is a known issue due to #9783.

### CODE REVIEW

**Comment by maskit** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by ezelkow1** [comment]
[approve ci]

**Review by maskit — APPROVED** [review]

**Pull request merged**
