### PR TITLE
Add transform TSIOBuffer watermark APIs.

### PR DESCRIPTION
**Pull request by ezelkow1**
(cherry picked from commit 5a2c6acd23321092552516dc8f6599e42d986f18)

### CODE REVIEW

**Comment by ezelkow1** [comment]
This change had previously been picked in to the 8.1.0 branch, but never landed on 8.0

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by ezelkow1** [comment]
[approve ci autest]

**Comment by zwoop** [comment]
@Bryan you want this for 8.0.6?

**Comment by bryancall** [comment]
Cherry picked 5a2c6acd23321092552516dc8f6599e42d986f18 from master and set #4117 milestone to be 8.0.6

**Pull request closed without merging**
