### PR TITLE
Cleanup: Get rid of afterpoll net stats

### PR DESCRIPTION
**Pull request by masaori335**
Fix half of #7214.

### CODE REVIEW

**Comment by masaori335** [comment]
[approve ci]

**Comment by masaori335** [comment]
[approve ci]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by brbzull0** [comment]
[approve ci]

**Comment by brbzull0** [comment]
[approve ci]

**Comment by brbzull0** [comment]
[approve ci]

**Review by brbzull0 — APPROVED** [review]
looks good. 
Thanks

**Pull request merged**
