### PR TITLE
TS-4825: Add the TSVConnInternalSet() API.

### PR DESCRIPTION
**Pull request by jpeach**
If you have a protocol plugin that generates HTTP requests, you
typically want those to be treated as external client requests not
as internal requests.

The TSVConnInternalSet() allows a plugin to mark a TSVConn as either
internal or external. It should be called immediately after the
TSVConn is created in order to avoid any race conditions with
any consumers.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/736/ for details.

**Comment by jpeach** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/737/ for details.

**Comment by jpeach** [comment]
Abandoning this PR in light of the dev@ list discussion (see references on [TS-4825](https://issues.apache.org/jira/browse/TS-4825)).

**Pull request closed without merging**
