### PR TITLE
Weird characters in debug message

### PR DESCRIPTION
**Pull request by bryancall**
old text:
11:40:15 bart:(master)~/dev/apache/trafficserver$ echo mоdification | hexdump -C
00000000  6d d0 be 64 69 66 69 63  61 74 69 6f 6e 0a        |m..dification.|
0000000e

new text:
11:40:09 bart:(master)~/dev/apache/trafficserver$ echo modification | hexdump -C
00000000  6d 6f 64 69 66 69 63 61  74 69 6f 6e 0a           |modification.|
0000000d

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci clang-analyzer]

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by bryancall** [comment]
[approve ci clang-analyzer]

**Comment by zwoop** [comment]
Cherry-picked to v9.0.x branch.

**Pull request merged**
