### PR TITLE
Backport of Forwarded header feature from master.

### PR DESCRIPTION
**Pull request by ywkaras**

### CODE REVIEW

**Comment by ywkaras** [comment]
[approve ci clang-format]

**Comment by zwoop** [comment]
This is too big of a feature change to go into 7.1.x. It's a candidate for 7.2.0, IF we decide to make such a release.

**Comment by ywkaras** [comment]
Is there a 7.2.x branch?

**Comment by ywkaras** [comment]
[approve ci icc]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
[approve ci autest]

**Comment by ywkaras** [comment]
Closing this for now, will revisit in the unlikely even that we do a 7.2.1 .

**Pull request closed without merging**
