### PR TITLE
TS-4466: Add links to other versions of the documentation

### PR DESCRIPTION
**Pull request by maskit**
https://issues.apache.org/jira/browse/TS-4466
image

### CODE REVIEW

**Comment by maskit** [comment]
The template file could be considered as a derivative of this file. It's licensed under MIT.
https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/versions.html

But I think the structure of tags and class names are sort of APIs to use this area.
Should I put original copyright and license to our LICENSE file?

**Comment by zwoop** [comment]
Great! I've asked Jon to take a look at this as well, since he's our Docs guru :).

**Comment by jsime** [comment]
This looks really good, except for one issue I've noticed. If you happen to be on a page which is nested pretty far down into the ToC (e.g. any of the experimental plugin docs in the Admin guide), and the chapter navigation in the left sidebar is pretty long, the language/version switcher can obscure the last couple entries in the expanded ToC list. Collapsing the new switcher with the arrow link just to the right of the currently selected version helps, but can still block the last entry in the ToC list (plus it may not be obvious for newcomers to the docs that there are any list items obscured at all).

Hopefully this image comes through clearly enough:

ats-docs-switcher-obscuring

The screenshots left and center show left-hand ToC navigation entries being obscured by both the expanded and collapsed language/version switcher - the right hand shot shows the collapsed switcher with a shorter ToC list in which nothing is covered up.

My CSS chops aren't good enough to know right away how to correct that, but I'll see if I can come up with something. I can reproduce this issue in both Firefox and Chrome, fwiw.

**Comment by maskit** [comment]
Thank you for pointing out the issue. I found a fix for it on RTD's repository.
https://github.com/rtfd/readthedocs.org/commit/b15d50bc200677053c04f6ede6c72fd1055525dd

Also, I modified the template so that the switcher is collapsed until a reader clicks the current version at the bottom right.

**Pull request merged**
