### PR TITLE
Ran clang-tidy with google-readability-casting

### PR DESCRIPTION
**Pull request by bryancall**

### CODE REVIEW

**Comment by masaori335** [comment]
I suggest that adding the rule to the `.clang-tidy` file.

**Comment by bryancall** [comment]
Reran since it was stopped earlier from a bad Makefile.

@masaori335 Yes, I plan to add it to the .clang-tidy file

**Comment by masaori335** [comment]
FreeBSD build is failed with this change
```
SSLDiags.cc:163:8: error: static_cast from 'pthread_t' (aka 'pthread *') to 'unsigned long' is not allowed
  es = static_cast<unsigned long>(pthread_self());
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by masaori335** [comment]
[approve ci autest]

**Pull request merged**
