### PR TITLE
Adds an IP reputation system to the SNI rate limiter

### PR DESCRIPTION
**Pull request by zwoop**
This concept is simple, yet allows for the rate limit plugin to chose an IP to block based on previous events, rather than just randomly blocking users. It intentionally only works as a global plugin right now, and it also requires a notion of "pressure" to be functional.

### CODE REVIEW

**Comment by zwoop** [comment]
[approve ci]

**Comment by ywkaras** [comment]
Needs a rebase.

**Comment by ezelkow1** [comment]
[approve ci rocky]

**Comment by zwoop** [comment]
Rebased on current master.

**Comment by zwoop** [comment]
[approve ci fedora]

**Comment by bneradt** [comment]
[approve ci]

**Review by randall — APPROVED** [review]

**Comment by zwoop** [comment]
Cherry-picked to v9.2.x

**Pull request merged**
