### PR TITLE
TS-4026: Remove Clustering

### PR DESCRIPTION
**Pull request by PSUdaemon**
This is a first rough cut. I haven't removed the actual clustering dirs to keep the diff readable, but I am sure something important got ripped out here. Please take a look and lets figure this out.

We might also just want to disable clustering with no way to enable, but I really wanted to take a crack at this and see if we can remove it now instead of leaving that code in there to compile all the time.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/705/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/600/ for details.

**Comment by zwoop** [comment]
[approve ci]

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/706/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/601/ for details.

**Comment by atsci** [comment]
FreeBSD build *failed*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/708/ for details.

**Comment by atsci** [comment]
Linux build *failed*! See https://ci.trafficserver.apache.org/job/Github-Linux/603/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/604/ for details.

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/709/ for details.

**Comment by bryancall** [comment]
Looked over the code and I didn't see a problem.  I applied the patches and it passed unit tests and regression.

**Pull request closed without merging**
