### PR TITLE
Ts 3559

### PR DESCRIPTION
**Pull request by repodude**
TLS session ticket cache support for ATS (TS-3559)

### CODE REVIEW

**Comment by repodude** [comment]
Session re-use with TLS session tickets requires TLS-extensions which comes into being at TLSv1.0+.  As this must be turned on at the client hello,the connect TLS version is set prior.

Currently ATS only connect with the old SSLv23_client_method(), and does not have configuration for TLS version.  Without this, session ticket will be a compiled mutually exclusive relationship with SSLv2.0 and SSLv3.0.   Many security guys would think this is a good thing because of many known security compromises  ...regardless, will make it configurable so the control is in the configuration. I've created ticket TS-3716 to address this.

**Comment by jpeach** [comment]
I made couple of specific comments on ae455eb.

Some more general comments on 1d38e70 .... needs license headers, header guards should use the existing convention, no C++11 yet.

Is it possible to generalize the implementation of the session cache so we can reuse it for the ticket cache?  Maybe template it on the key and value types, or use a siphash of the hostname as the ticket cache key?

**Comment by shinrich** [comment]
Two comments.  One is a minor style comment about the functions you added to SSLInternal.c.  Ideally the API for the functions in there should be the same as the API for the functions that will be in openssl 1.1.  So when you do the autoconf testing, they just swap out for the real ones.

The other comment is about the ticket cache map.  I agree with James, that sharing the cache table implementation would be nice.  Given the size of things, maybe not worth the effort.  My bigger concern is making sure that the table is thread safe.  In a caching environment, transient errors are ok, but structural errors from multiple writers are concerning.

**Comment by jpeach** [comment]
Sorry for dropping the ball on this one @repodude. If you are coming to the ATS summit, I'd like to sit with you and get this merged. There's a few style changes I'd like to see, but the main change is to use the internal containers rather than ```unordered_map```. I'm OK with leaving the ticket/session cache convergence to a separate effort.

**Comment by repodude** [comment]
Yeah, bummer we weren't able to sync up at ATS summit as I think it might be helpful to clarify some of this application's requirements and/or divulging the run-time profile vetting done prior to selection of this particular container.  I'm not sure that either of the two latest alternative suggestions are ideal for this application.  Further it would be good for me to better understand where your concerns are coming from.  Will try explaining in this PR....

The session-tickets contain the previously negotiated TLS parameters, an expiration timestamp, are encrypted using a key known only to server, and have the ability to tell whether a ticket came from itself.  Prior to SSLConnect(), our client does a look up in it's origin server side session ticket cache to see if it has a non-expired ticket for the particular SNI.   If so, then it includes it in it's Client-Hello.

On completion of a handshake, if server sends back a session-ticket, it is stored in the origin server side session ticket cache with SNI as the index key.   In a continuously running production system, one of the required constraints on this cache is mem size and of course speed.  Some TLS protocol related details about this application that may be helpful here for picking a container:

1) Session tickets expiration times are max bound by server and possibly
further constrained by client.  24 hours is common though based on 
server's trust of AES128 and key rotations schedule.
2) Protocol is completely tolerant of delivery of wrong or expired tickets.
3) Failure of session-ticket re-use simply results in fallback to session-ID
   re-use or worst case, full-handshake.

We can use these constraints to optimize to our hard production speed and space system requirements.  Namely, hash collisions are fine, i.e.  buckets never grow past a size of 1.  We overwrite in our bucket because in the case of collision, the cost in the vast majority of cases will be non-consequential, and in worse case amortize  into nothing.  Overwriting of already allocated buckets is fastest reclamation.  In patch, even the hostname key (small fixed size to 32), is re-used, so no alloc/free, but rather overwrite of previous allocated space.

While, I'm not necessarily advocating for standard unordered_map because I'm not sure what the other concerns are, I will say relevant to the above, the max_load_factor is set to 1.0 for no-growth bucket overwrite case, and I did run independent tests to profile bucket number growth characteristics.  A possible alternative unordered_map that I discussed with Alan would be just to use a non-growth hash indexed array.

Thoughts?

**Comment by repodude** [comment]
Closing out, as re-base made many changes

**Pull request closed without merging**
