### PR TITLE
Add some AuTest plugins that I missed to CMake

### PR DESCRIPTION
**Pull request by JosiahWI**
I missed one. Here it is.

### CODE REVIEW

**Review by cmcfarlen — DISMISSED** [review]

**Comment by JosiahWI** [comment]
[approve ci cmake]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Comment by JosiahWI** [comment]
[approve ci autest]

**Review by cmcfarlen — APPROVED** [review]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci]

**Comment by bneradt** [comment]
[approve ci clang-format docs rat rocky

**Comment by bneradt** [comment]
[approve ci clang-format docs rat rocky]

**Pull request merged**
