### PR TITLE
Fix mysql-remap compilation error

### PR DESCRIPTION
**Pull request by jvgutierrez**
It looks like d77cd73166c1b27cde61ffb3c8a1545c437fad83 partially messed with the fix applied in 6e35780e43d7313d18b7ee260e3e0c239d917104

### CODE REVIEW

**Comment by bryancall** [comment]
[approve ci]

**Comment by jvgutierrez** [comment]
Sure @masaori335. It's already done

**Comment by jvgutierrez** [comment]
@masaori335 I believe that dictionary.h could benefit from the same NOLINT comment on the following headers:
https://github.com/apache/trafficserver/blob/master/plugins/experimental/mysql_remap/lib/dictionary.h#L51-L53

Should I add them as part of this PR?

**Comment by randall** [comment]
[approve ci]

**Comment by jvgutierrez** [comment]
maybe I'm missing something but... how a linter comment can mess up with autest?

**Comment by randall** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
For `dictionary.h`, we don't need the suppression magic, because it is only included by `dictionary.c`. 
Our tidy-up script using clang-tidy distinguish C or C++ by `*.c` or `*.cc`. So we need the  `NOLINT(modernize-deprecated-headers)` guard when C header file is included by C++ source file - e.g. `iniparser.h` is included by `mysql_remap.cc`.

For autest, sometimes it's unstable :(

**Pull request merged**
