### PR TITLE
TS-4976: Regularize plugins - hello

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Incremental work on #1114.

### CODE REVIEW

**Comment by atsci** [comment]
clang format *successful*! https://ci.trafficserver.apache.org/job/clang-format-github/81/

**Comment by atsci** [comment]
RAT check *successful*! https://ci.trafficserver.apache.org/job/RAT-github/94/

**Comment by atsci** [comment]
FreeBSD11 build *successful*! https://ci.trafficserver.apache.org/job/freebsd-github/1776/

**Comment by atsci** [comment]
AU check *failed*! https://ci.trafficserver.apache.org/job/autest-github/78/

**Comment by atsci** [comment]
Intel CC build *successful*! https://ci.trafficserver.apache.org/job/icc-github/207/

**Comment by atsci** [comment]
Linux build *successful*! https://ci.trafficserver.apache.org/job/linux-github/1669/

**Comment by atsci** [comment]
clang-analyzer build *successful*! https://ci.trafficserver.apache.org/job/clang-analyzer-github/339/

**Comment by zwoop** [comment]
Why did the AU check fail? Did you forget to rebase? :)

**Comment by SolidWallOfCode** [comment]
All the changes are related to the hello plugin or its use in the documentation. I will try to be more verbose in the future, however.

**Pull request merged**
