### PR TITLE
Improves logging in SSLCertificateConfig::reconfigure()

### PR DESCRIPTION
**Pull request by dyrock**
Improves logging in SSLCertificateConfig::reconfigure() from hard-coded file name to the actual config file path.

### CODE REVIEW

**Comment by randall** [comment]
This was made in #4764 to make consistent all of the config file load messages.  If you're going to change to absolute path, can you update all of the config file loads for consistency?

**Comment by dyrock** [comment]
yup will take a look.

**Comment by shinrich** [comment]
@zwoop I am confused by your concern.  Perhaps I missed something from earlier versions of the PR.  As it stands, all it does is add the name of the specific ssl_multi_cert file into the message.  So same number of messages.  Just more info in the message.   This was a specific request from one of our ops guys, since we are using non-default names.  Having the specific name of the file with the problem means we are less likely to waste time looking at the wrong file.

**Comment by zwoop** [comment]
Yeh I don’t think we should log the full path to the file, that has always been implied by your runtime. Picking out these two to have full path names in the messages seems superfluous and inconsistent. If it’s just the file name then fine, but that’s not what the patch looks like.

**Pull request closed without merging**
