### PR TITLE
Fixed compiler error with std::string_view

### LINKED ISSUE #5045: Complier Error with g++-7.1 on master
```
make[2]: Entering directory '/root/trafficserver/lib/records'
  CXX      RecLocal.o
In file included from /usr/include/c++/7/bits/basic_string.h:48:0,
                 from /usr/include/c++/7/string:52,
                 from ../../include/tscore/ink_memory.h:29,
                 from ../../include/tscore/defalloc.h:25,
                 from ../../include/tscore/List.h:60,
                 from /root/trafficserver/mgmt/Rollback.h:27,
                 from RecLocal.cc:25:
/root/trafficserver/mgmt/MgmtDefs.h:145:68:   in constexpr expansion of ‘std::basic_string_view<char>(((const char*)"processerver.sock"))’
/usr/include/c++/7/string_view:100:58: error: call to non-constexpr function ‘static std::size_t std::char_traits<char>::length(const char_type*)’
       : _M_len{__str == nullptr ? 0 : traits_type::length(__str)},
                                       ~~~~~~~~~~~~~~~~~~~^~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’

```

```
root@scw00:~/trafficserver_quic/iocore/net# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.1.0-10ubuntu1~16.04.york0' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.1.0 (Ubuntu 7.1.0-10ubuntu1~16.04.york0)

```

### PR DESCRIPTION
**Pull request by scw00**
This is @SolidWallOfCode suggestion 

this closes #5045

### CODE REVIEW

**Comment by SolidWallOfCode** [comment]
I think you need to
```
#include "tscpp/util/TextView.h"
```

**Comment by scw00** [comment]
@SolidWallOfCode  Sorry for missing that. Updated Now.

**Comment by SolidWallOfCode** [comment]
I'm not sure why `std::string_view` doesn't support `constexpr` for literals in older versions of the compiler, you'd think that would have worked from the start.

**Comment by scw00** [comment]
I only found this

**Comment by scw00** [comment]
And g++-8 work well with std::string_view.

**Comment by maskit** [comment]
I'm not sure which way is better, but I'd like to use only one of them (ts::TextView or ""sv).

```
$ git grep constexpr | grep "\"sv"
iocore/net/QUICNetVConnection.cc:static constexpr std::string_view QUIC_DEBUG_TAG = "quic_net"sv;
iocore/net/quic/QUICConfig.cc:static constexpr std::string_view QUIC_ALPN_PROTO_LIST("\5hq-18"sv);
iocore/net/quic/QUICKeyGenerator.cc:constexpr static std::string_view LABEL_FOR_CLIENT_INITIAL_SECRET("client in"sv);
iocore/net/quic/QUICKeyGenerator.cc:constexpr static std::string_view LABEL_FOR_SERVER_INITIAL_SECRET("server in"sv);
iocore/net/quic/QUICKeyGenerator.cc:constexpr static std::string_view LABEL_FOR_KEY("quic key"sv);
iocore/net/quic/QUICKeyGenerator.cc:constexpr static std::string_view LABEL_FOR_IV("quic iv"sv);
iocore/net/quic/QUICKeyGenerator.cc:constexpr static std::string_view LABEL_FOR_HP("quic hp"sv);
iocore/net/quic/QUICPacket.cc:static constexpr std::string_view tag  = "quic_packet"sv;
iocore/net/quic/QUICPacketFactory.cc:static constexpr std::string_view tag   = "quic_packet"sv;
iocore/net/quic/QUICPacketFactory.cc:static constexpr std::string_view tag_v = "v_quic_packet"sv;
src/tscore/unit_tests/test_BufferWriterFormat.cc:  static constexpr std::string_view text{"e99a18c428cb38d5f260853678922e03"sv};
src/tscpp/util/unit_tests/test_TextView.cc:  constexpr TextView d{"Grigor!"sv};
```

```
$ git grep constexpr | grep "TextView "
plugins/experimental/tls_bridge/tls_bridge.cc:constexpr TextView CONFIG_FILE_ARG{"--file"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_MATCH_SRC{"src_ip"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_MATCH_DST{"dest_ip"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_ACTION_TAG{"action"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_ACTION_ALLOW{"ip_allow"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_ACTION_DENY{"ip_deny"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_METHOD{"method"};
proxy/IPAllow.h:  static constexpr ts::TextView OPT_METHOD_ALL{"all"};
src/tscore/unit_tests/test_BufferWriterFormat.cc:  static constexpr ts::TextView fmt{FMT, strlen(FMT)};
src/tscpp/util/unit_tests/test_TextView.cc:  constexpr TextView d{"Grigor!"sv};
```

**Comment by scw00** [comment]
Unfortunately it doesn't work either .

```
make[2]: Entering directory '/root/trafficserver/lib/records'
  CXX      RecLocal.o
In file included from /root/trafficserver/mgmt/BaseManager.h:35:0,
                 from /root/trafficserver/mgmt/LocalManager.h:28,
                 from RecLocal.cc:32:
/root/trafficserver/mgmt/MgmtDefs.h:145:58: error: unable to find string literal operator ‘operator""sv’ with ‘const char [18]’, ‘long unsigned int’ arguments
 constexpr static std::string_view LM_CONNECTION_SERVER = "processerver.sock"sv;
                                                          ^~~~~~~~~~~~~~~~~~~~~


make[2]: Entering directory '/root/trafficserver/lib/records'
  CXX      RecLocal.o
In file included from /root/trafficserver/mgmt/BaseManager.h:35:0,
                 from /root/trafficserver/mgmt/LocalManager.h:28,
                 from RecLocal.cc:32:
/root/trafficserver/mgmt/MgmtDefs.h:145:56: error: unable to find string literal operator ‘operator""sv’ with ‘const char [18]’, ‘long unsigned int’ arguments
 static constexpr std::string_view LM_CONNECTION_SERVER("processerver.sock"sv);


/root/trafficserver/mgmt/MgmtDefs.h:145:49: error: unable to find string literal operator ‘operator""sv’ with ‘const char [18]’, ‘long unsigned int’ arguments
 constexpr std::string_view LM_CONNECTION_SERVER("processerver.sock"sv);
                                                 ^~~~~~~~~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’

```

**Comment by scw00** [comment]
Thanks .

**Comment by scw00** [comment]
@maskit @SolidWallOfCode  updated. I prefer to the original one.

**Comment by SolidWallOfCode** [comment]
You could move it into `BaseManager` and then the `using std::literals` could be scoped by the class.

**Comment by maskit** [comment]
I agree with @SolidWallOfCode . I don't think use of `using namespace x` at global scope in header files is a good idea.

```
$ git grep MgmtDefs.h
mgmt/BaseManager.h:#include "MgmtDefs.h"
mgmt/Makefile.am:       MgmtDefs.h \
mgmt/WebMgmtUtils.h:#include "MgmtDefs.h"
mgmt/api/CoreAPI.h:#include "MgmtDefs.h" // MgmtInt, MgmtFloat, etc
proxy/http/HttpConnectionCount.h:#include <MgmtDefs.h>
```

```
$ git grep HttpConnectionCount.h
proxy/http/HttpConfig.h:#include "HttpConnectionCount.h"
proxy/http/HttpConnectionCount.cc:#include "HttpConnectionCount.h"
proxy/http/HttpProxyServerMain.cc:#include "HttpConnectionCount.h"
proxy/http/HttpServerSession.h:#include "HttpConnectionCount.h"
proxy/http/HttpTransact.h:#include "HttpConnectionCount.h"
proxy/http/Makefile.am: HttpConnectionCount.h \
```

**Comment by scw00** [comment]
I can't put it into a class because 
```
/root/trafficserver/mgmt/BaseManager.h:110:14: error: using-declaration for non-member at class scope
   using std::literals;

```

and https://stackoverflow.com/questions/33713597/error-using-declaration-for-non-member-at-class-scope-using-stdcout said 
>That's not valid C++, in a class body you can only add a using-declaration for members of base classes, not arbitrary names.

So let's go back to `ts::TextView`.

**Comment by maskit** [comment]
Hmm, then I'd suggest `constexpr std::string_view abc{std::string_view("abc")};`, but I'm also ok with `ts::TextView`.

**Comment by SolidWallOfCode** [comment]
You could try `using namespace std::literals`. I thought I'd used that in a class, but it looks like I used it either in nested namespaces or inside functions.

**Comment by scw00** [comment]
Doesn't work ! :-)

```
root@scw00:~/trafficserver/mgmt# git diff
diff --git a/mgmt/BaseManager.h b/mgmt/BaseManager.h
index 9f72212f8..3ad16b63f 100644
--- a/mgmt/BaseManager.h
+++ b/mgmt/BaseManager.h
@@ -106,6 +106,8 @@ class BaseManager
   using MgmtCallbackList = std::list<MgmtCallback>;

 public:
+  using namespace std::literals;
+  constexpr static std::string_view aaa{"aaa"};
   BaseManager();

   ~BaseManager();
root@scw00:~/trafficserver/mgmt#


/root/trafficserver/mgmt/BaseManager.h:109:9: error: expected nested-name-specifier before ‘namespace’
   using namespace std::literals;
         ^~~~~~~~~

```

**Pull request merged**
