### PR TITLE
Doc conditional build

### PR DESCRIPTION
**Pull request by SolidWallOfCode**
Make the docs not build by default, require a "--enable-docs" argument to ./config.

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/1227/ for details.

**Comment by zwoop** [comment]
How about this too:

```
diff --git a/ci/jenkins/bin/docs.sh b/ci/jenkins/bin/docs.sh
index 6754040..f5b2a17 100644
--- a/ci/jenkins/bin/docs.sh
+++ b/ci/jenkins/bin/docs.sh
@@ -22,7 +22,7 @@ test ! -z "${WORKSPACE}" && cd "${WORKSPACE}/src"
 
 # This avoids redoing the configure on every doc build, which is somewhat annoying
 [ ! -f configure ] && autoreconf -fi
-[ ! -f config.nice ] && ./configure
+[ ! -f config.nice ] && ./configure --enable-docs
 
 cd doc
```

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1120/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/1121/ for details.

**Pull request merged**
