### PR TITLE
Fix clang-format-github CI job for 8.0.x branch

### PR DESCRIPTION
**Pull request by masaori335**
Fix failure of the clang-format job against 8.0.x. It looks like trailing whitespaces are removed by 9c1b88a6349a84fa8556fc508d24bf6a25917fad on the master branch.
I'd like to do this cleanup instead of cherry-picking the commit because it has conflicts some files (like traffic_via.pl) are not included.

```
CHANGELOG-8.0.0:  #2196 - Adding DNS over TCP support 
CHANGELOG-8.0.0:  #2437 - null transform test 
CHANGELOG-8.0.0:  #2644 - remove dup setting with NO_FD 
CHANGELOG-8.0.0:  #2696 - Script load speedup for ts_lua remap plugin 
CHANGELOG-8.0.0:  #3530 - Add time option to traffic_ctl host down.  
CHANGELOG-8.0.2:  #4217 - Fix a regression in the traffic_ctl host status subcommand. 
doc/admin-guide/plugins/cachekey.en.rst:The following examples demonstrate different ways to achieve `cacheurl` compatibility on a cache key string level in order to avoid invalidation of the cache. 
doc/admin-guide/plugins/lua.en.rst:**description**: This function can be used to set the watermark bytes of the upstream transform buffer. 
doc/appendices/command-line/traffic_layout.en.rst:A runroot will be created in ``/path/to/runroot``, available for other programs to use. 
doc/appendices/command-line/traffic_layout.en.rst:Use the current working directory or the specific path to create runroot. 
doc/appendices/command-line/traffic_layout.en.rst:workflow: 
doc/developer-guide/internal-libraries/ArgParser.en.rst:or initialize with the following arguments: 
doc/developer-guide/internal-libraries/ArgParser.en.rst:        
doc/ext/traffic-server.py:    
rc/trafficserver.in:# TS_RUNROOT="" 
rc/trafficserver.in:# Make sure the NOFILES limit is set high in case this process is not 
tests/README.md:**gold_tests/** - contains all the TSQA v4 based tests that run on the Reusable Gold Testing System (AuTest)  
tests/README.md:**tools/** - contains programs used to help with testing.  
tests/gold_tests/autest-site/microserver.test.ext:    # this might break if user specifies both both and ssl 
tests/gold_tests/autest-site/traffic_replay.test.ext:# default 'mixed' for connection type since it doesn't hurt 
tests/gold_tests/autest-site/traffic_replay.test.ext:    
tests/tools/README.md:Usage: 
tests/tools/README.md:Session Log format (in JSON): 
tests/tools/README.md: {"version": "0.1", 
tests/tools/README.md:        {"request": {"headers": "POST ������\r\n\r\n", "timestamp": "..", "body": ".."}, 
tests/tools/README.md:         "uuid": "1"}, 
tests/tools/README.md:        {"request": {"headers": "POST ..���.\r\n\r\n", "timestamp": "..", "body": ".."}, 
tests/tools/README.md:        "response": {"headers": "HTTP/1.1..\r\nr\n", "timestamp": "..", "body": ".."}, 
tests/tools/README.md:  ], 
tests/tools/README.md:  "timestamp": "....", 
tools/traffic_via.pl:# 2. Pipe curl output 
tools/traffic_via.pl:# 
tools/traffic_via.pl:        { 
tools/traffic_via.pl:        { 
tools/traffic_via.pl:    
tools/traffic_via.pl:            $via_string = $2;    
tools/traffic_via.pl:    
tools/traffic_via.pl:    if ($header =~ /([a-zA-Z: ]+)/) {   
tools/traffic_via.pl:        
tools/traffic_via.pl:    
tools/traffic_via.pl:    
tools/traffic_via.pl:                push(@ResultArray, $1); 
tools/traffic_via.pl:    
tools/traffic_via.pl:            
tools/traffic_via.pl:    
tools/traffic_via.pl:            if ($key =~ /$flag/) { 
Error: Trailing whitespaces are not allowed!
Error: Please run: git grep -IE ' +$'
Build step 'Execute shell' marked build as failure
```

https://ci.trafficserver.apache.org/job/clang-format-github/10669/console

### CODE REVIEW

**Comment by masaori335** [comment]
I found some PRs removing trailing whitespaces, I’ll open a new PR to backport them.

**Comment by masaori335** [comment]
@randall Could you tell me the options which you used for 994a2f0 ? Some files (only?) on 8.0.x are needed to be fixed.

**Comment by randall** [comment]
I think it was just the default dos2unix from brew.

On your branch, if you run
```
git grep -IE $'\r$' | fgrep -v 'lib/yamlcpp'  | cut -f 1 -d : | sort -u| xargs dos2unix
```

it should get the remaining files.

**Comment by masaori335** [comment]
Thanks! The remaining files are fixed.

**Comment by masaori335** [comment]
[approve ci clang-format]

**Comment by masaori335** [comment]
[approve ci autest]

**Comment by masaori335** [comment]
All green, ready for review.

**Comment by randall** [comment]
@bryancall Can we merge this for 8.0.x?

**Pull request merged**
