### PR TITLE
MultiCache/HostDB: Get and set the lowest level of the bucket correctly

### PR DESCRIPTION
**Pull request by oknet**

### CODE REVIEW

**Comment by zwoop** [comment]
This presumably doesn't apply to 7.x or master?

**Comment by oknet** [comment]
@zwoop yes, this is 6.2.x or previous only, because MultiCache is replaced by RefCountCache.

**Comment by bryancall** [comment]
[approve ci autest]

**Comment by PSUdaemon** [comment]
[approve ci]

**Comment by PSUdaemon** [comment]
@oknet This branch is technically EOL now. Are you still using 6.2.x somewhere? Do you need this?

**Comment by oknet** [comment]
[approve ci ubuntu clang-analyzer]

**Comment by oknet** [comment]
[approve ci ubuntu]

**Comment by oknet** [comment]
@PSUdaemon I still using the 6.0.x branch. IMO, it is a critical bug for version from 2.0.x to 6.2.x. Please merge it if we will have next release for 6.2.x.

**Comment by oknet** [comment]
@bryancall @PSUdaemon 

Is the 6.2.x EOL now?

From http://trafficserver.apache.org/downloads,
```
Current v6.x Release -- 6.2.2
Apache Traffic Server 6.2.2 was released on August 10th, 2017. [PGP] [MD5] [SHA1]

Traffic Server 6.2.2

v6.2.2 is our latest LTS release. Additional details for this release are in the CHANGELOG and the the Jira Release Notes.

For details on the v6.2.x release, please see 6.2.x News.
```

Also, https://wiki.ubuntu.com/Releases and https://packages.ubuntu.com/search?keywords=trafficserver
Ubuntu 16.04 LTS shipped with trafficserver 5.3.0 and it will be EOL on April 2021.
Ubuntu 18.04 LTS shipped with trafficserver 7.1.2 and it will be EOL on April 2023.

Can we have a page like https://wiki.ubuntu.com/Releases ?

**Comment by oknet** [comment]
[approve ci]

**Comment by oknet** [comment]
[approve ci clang-analyzer]

**Comment by bryancall** [comment]
ATS 6.2.x is now EOL and this PR hasn't been updated in a few months.

**Pull request closed without merging**
