### PR TITLE
TS-4659: Log format errors on startup.

### PR DESCRIPTION
**Pull request by jpeach**
Remove extraneous field name constants which accidentally match
with strstr().

### CODE REVIEW

**Comment by atsci** [comment]
FreeBSD build *successful*! See https://ci.trafficserver.apache.org/job/Github-FreeBSD/427/ for details.

**Comment by atsci** [comment]
Linux build *successful*! See https://ci.trafficserver.apache.org/job/Github-Linux/321/ for details.

**Comment by zwoop** [comment]
The patch seems fine, but I'm a little concerned why those were put in there to begin with? Obviously some sort of sentinel at some point? As long as we don't need those, I'm +1 on this.

**Comment by jpeach** [comment]
The original code used the enum value as a sentinel so it would never have hit the empty strings at the ends of the lists.

**Pull request merged**
