### PR TITLE
Fix unchecked return value of initgroups()

### PR DESCRIPTION
**Pull request by maskit**

### CODE REVIEW

**Review by shukitchan — APPROVED** [review]
Looks fine

**Review by bryancall — APPROVED** [review]

**Comment by maskit** [comment]
autest remap_acl failed.

**Comment by maskit** [comment]
[approve ci autest]

**Review by shukitchan — APPROVED** [review]

**Comment by maskit** [comment]
[approve ci autest]

**Comment by cmcfarlen** [comment]
Cherry-picked to v10.0.x

**Pull request merged**
